### ISSUE TITLE
Settings will not open if there is an incorrect ruleset.

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#10053]
**Describe the bug:** 
If the folder with the rulesets contains a mode file that cannot be opened in this version, then for some reason the settings menu stops working (It just doesn't open in any way). If you remove the ruleset, then everything becomes normal. The only problem is that this is a completely non-obvious problem.
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/59089206/92149119-e7b6a800-ee60-11ea-9a4e-567f25d7c9e5.png)
Example .dll - https://github.com/karaoke-dev/karaoke/releases/tag/2020.0802.0
https://youtu.be/rGmc74K0hrY (When you click on the settings icon, the screen shifts to the right, but nothing else happens.)
**osu!lazer version:** 
2020.093.0

**Comment by peppy** [comment]
For the third time, please *follow instructions*. We need you to include everything mentioned in the issue template, including logs. This is your last chance.

**Comment by LumpBloom7** [comment]
This is specifically due to osu-karaoke trying to create a `FullscreenOverlay` for the osu-karaoke changelogs, which got changed in #10044.

The button to toggle the karaoke changelog is within the settings subsection for the ruleset, causing the settings overlay to fail.

Here is the log for that specific problem: 
[runtime.log](https://github.com/ppy/osu/files/5170365/runtime.log)

On a fresh copy of the latest lazer (no db), osu-karaoke will fail to load entirely, causing no issues with the settings overlay.  However if lazer updated to the latest version with that ruleset previously added, it'll complain about not being able to add the ruleset, but the ruleset will still be loaded, and causing problems with things down the line.

**Comment by peppy** [comment]
Thanks a lot.

Probably a good reminder that we should be making such classes `internal` to avoid this.

**Comment by peppy** [comment]
test
