### ISSUE TITLE
External links overflow popup dialog

### ISSUE THREAD

**Issue by Suprnova** [ppy/osu#10085]
**Describe the bug:** External links will overflow out of its "Just checking..." container if they are too long. While it depends on the resolution, this problem doesn't happen with the other text within the container, which simply wraps onto a new line when it needs to.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/68174586/92436959-e264a080-f173-11ea-9164-3ae131fccf5d.png)

**osu!lazer version:** 2020.903.0

**Comment by GSculerlor** [comment]
Was about to fix it by moving out the link from `OsuTextFlowContainer` into separated `OsuSpriteText` since `TextFlowContainer `doesn't handle text with no spaces well (ppy/osu-framework#2982) but seems like defining `RelativeSizeAxes` for truncation make the text isn't centered

![dialog-optimize](https://user-images.githubusercontent.com/6506864/94914012-722c0f00-04d4-11eb-9e9d-c0b0b2c56139.gif)

**Comment by bdach** [comment]
It should just be fixed framework-side.

**Comment by GSculerlor** [comment]
Fair point
