### ISSUE TITLE
Standardised score is not 1-million-based

### ISSUE THREAD

**Issue by Contextualist** [ppy/osu#10144]
**Describe the bug:**

 When I updated to this version (2020.910.0), I noticed that all of my local scores look less than what were displayed in the previous version. (e.g. ~990k scores now become ~780k). SS a map without any mod and bonus point does not yield a score of 1 million.

**Screenshots or videos showing encountered issue:** 

This screenshot shows one of my SS record (without any mod and bonus point). Note that I have `standardised` on in the settings.

![osu_2020-09-11_14-47-49](https://user-images.githubusercontent.com/16000021/92962290-bc265580-f43e-11ea-964d-b75747a8522a.jpg)

**osu!lazer version:** 

2020.910.0

**Logs:**

[logs.zip](https://github.com/ppy/osu/files/5211035/logs.zip)

**Comment by peppy** [comment]
which ruleset?

**Comment by PercyDan54** [comment]
> 
> 
> which ruleset? which beatmap?
Beatmap:
https://osu.ppy.sh/beatmapsets/75890#osu/214234
Ruleset osu!

**Comment by peppy** [comment]
https://github.com/ppy/osu/pull/10141 is likely relevant.

**Comment by Azzirah** [comment]
i think the dynamic scoring calculation takes into account the online/stable max combo of the beatmap and since if i'm not mistaken for the time being sliderends are not accounted in the combo of a map therefore an FC in the current version of lazer would have exactly the number of sliders less combo than an FC made on stable, which i believe is what's happening here.

**Comment by Contextualist** [comment]
@Azzirah 
> i think the dynamic scoring calculation takes into account the online/stable max combo of the beatmap

Agree, the score here seems to reflect what you describe:
Current (Lazer) FC: 170
Sliderends: 77
170/(77+170)\*0.7 + 1\*0.3 = 0.781781
