### ISSUE TITLE
All about song select and Collections

### ISSUE THREAD

**Issue by yansaan** [ppy/osu#10145]
**Describe the bug:** 
Showing error like this screenshot
**Screenshots or videos showing encountered issue:** 
![osu_2020-09-12_02-12-32](https://user-images.githubusercontent.com/21020026/92964050-aa27cf80-f49d-11ea-8f57-c59ec42eee23.jpg)
**osu!lazer version:** 
2020,910.0
**Logs:**
[performance.log](https://github.com/ppy/osu/files/5211114/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5211115/runtime.log)
[database.log](https://github.com/ppy/osu/files/5211165/database.log)

**Comment by yansaan** [comment]
And collection not imported when song add already

**Comment by peppy** [comment]
If you aren't attached to your database. please delete client.db and try again.

**Comment by yansaan** [comment]
Why isn't there a beatmaps reset button, so that the skin doesn't get deleted too

**Comment by bdach** [comment]
Database issues are sort of a weird area right now, since we might end up going away from the current DB framework to realm, so we don't really want to be committing time into the existing system until we know one way or another what direction is going to be taken in the future. The recommended short-term solution for now is to reimport everything.

**Comment by peppy** [comment]
Going to close this one. @yansaan if you need help and don't wish to delete your database, please attach in a zip and I will fix it for you.
