### ISSUE TITLE
Slider velocity Bug

### ISSUE THREAD

**Issue by WolfHD** [ppy/osu#1014]
There is Strange bug with speed of slider after break here in this map: https://osu.ppy.sh/s/319375
![osu bug](https://user-images.githubusercontent.com/25013284/28113400-b2a33294-66fc-11e7-957b-ef91200fe996.gif)

**Comment by swoolcock** [comment]
That slider has both an inherited and a regular timing point at the start.  I managed to track this down to `OsuLegacyDecoder` creating two instances of `DifficultyControlPoint` for the same time (one to reset the speed multiplier to `1`, and one to set it to `2`.

It appears that when the velocity is calculated for the slider, it is using the wrong control point.  I'll try changing it so that `DifficultyControlPoint`s for the same time will be replaced.  This should give the latter control point priority.
