### ISSUE TITLE
Add resume leniency for scrolling rulesets

### ISSUE THREAD

**Issue by Panthr75** [ppy/osu#10202]
**Describe the new feature:** 
Exact same implementation as osu!stable: Gives around half a second to the player before resuming gameplay, allowing them to hold keys for sliders, or get prepared on that one note centimeters in front of the judgement line.

**Proposal designs of the feature:** 
Implement the same implementation as osu!stable, but of course you could add more additions to it. For example, the half a second delay could be canceled if the user presses a key (of course add leniency for sliders so it's maybe within 5 ms or so).

This would really improve osu!mania because every time I pause, I realize that I am in the middle of notespam, or in the middle of a slider, and as such, I don't get enough time from pressing `Resume` to get those notes on the slider so I don't miss.

For example, right now, resuming the game whilst continuing to hold these notes can be difficult if you don't time it right:
![image](https://user-images.githubusercontent.com/29237603/93789880-04d8ce00-fbf8-11ea-9d39-d40250cf1df9.png)

Another example, hitting the notes on the left with `Perfect`s and not lower is also more difficult:
![image](https://user-images.githubusercontent.com/29237603/93790156-541efe80-fbf8-11ea-8161-cff979b5422e.png)

**Comment by bdach** [comment]
I'm not a mania player, so not sure how valid this will be, but how about forcing the player to press the same keys they were pressing before the break (if any), and then resuming with a countdown only after they've done so?

That could both make pause abuse even more impractical than it already is, and also help in resuming inputs.

**Comment by Panthr75** [comment]
That would work, and be even better than my suggestion!

**Comment by LittleEndu** [comment]
> how about forcing the player to press the same keys they were pressing before the break (if any)

Also not a mania player, just curious what the "if any" would look like? Just start the countdown as soon as they press ``resume``?

**Comment by bdach** [comment]
Probably, yeah. Not much to gain in that case.

**Comment by enoslayd** [comment]
#9004 and i was kinda rude on that (sorry)

**Comment by iSimpFor** [comment]
in mania; catch; and taiko, maybe the gameplay should rewind(move back) a bit of time when resuming(already hit notes will remain hit) to allow the player to anticipate the speed of the map

this should come after abuse protection of course

**Comment by Panthr75** [comment]
> in mania; catch; and taiko, maybe the gameplay field should rewind(move back) a bit of time when resuming(already hit notes will remain hit) to allow the player to anticipate the speed of the map

I personally think that this is okay, but I feel that this would be unfair for normal osu! players who have to click the same point on screen that they were at before they paused.

Requiring you to press the same keys would at least have parity between mania and standard.

With that being said, I have no idea how this could be applied to catch. Any suggestions would be appreciated.

**Comment by swetdep** [comment]
another way to handle it would be like newer versions of trackmania; by going back in time for 1-3 seconds so that the player can contextualize but it would be unplayable, and right when the player paused the game would become playable. i think it might have problems with the replays, timings, etc. but if everything worked, it would be a great feature :D

**Comment by toadsworth-jr** [comment]
Again, as bdach said, pause abuse.

**Comment by Doksha** [comment]
I think the stable implementation is perfect, its practically impossible to recover after unpausing in lazer (especially since you cant see the notes), pausing is a normal aspect of the game, and making pausing this heavily punished could cause people to be much more reluctant to put their health before score (really, don't do this, fucking up your hands for a cool score is really not worth it).
Concerning the suggestions for pressing previous keys, it may work, but it depends on when you paused, and how do you determine if a key is in the window of "previously pressed"? seems like way too much of a hassle when there is a perfectly fine implementation in stable
