### ISSUE TITLE
Taiko autoplay doesn't get 300k on big notes in default skin

### ISSUE THREAD

**Issue by MandL27** [ppy/osu#10252]
**Describe the bug:** 
On osu!lazer 2020.923.0, taiko autoplay doesn't get big note judgments in the default skin. Legacy skins work properly now, and all skins support big note judgments in actual gameplay. I think autoplay worked correctly with the default skin in past versions, but I'm not sure.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/10366615/94269032-15e15200-ff0c-11ea-9e98-683c7c3096ea.png)

**osu!lazer version:** 
2020.923.0

**Logs:**

[database.log](https://github.com/ppy/osu/files/5282857/database.log)
[performance.log](https://github.com/ppy/osu/files/5282858/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5282859/runtime.log)

**Comment by bdach** [comment]
I can't see any issue with the screenshot attached.

**Comment by MandL27** [comment]
In both default skins (lazer and classic), big notes produce bigger hitbursts if both sides are hit at the same time. Auto goes for these in both stable and lazer, but lazer's default skin doesn't show big hitbursts during auto. Watching other replays or playing a map normally properly displays big hitbursts under those conditions.

**Comment by bdach** [comment]
I can see how this is happening now... The schedule I added to make sure legacy skins show the correct sprite (300 or 300k) is breaking this, but only in the frame-perfect case.

https://github.com/ppy/osu/blob/a72629437d60d345dc76c48012d07552e58db126/osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs#L188

Because I scheduled the explosion addition, in the case where both hits happen in the same frame, the explosion won't be in the container yet. Not sure where to go with this... Another schedule is definitely bad.

**Comment by MandL27** [comment]
What about making legacy skins show 300k/100k under the same criteria that lazer's default uses? I thought about that during the discussion for implementing legacy 300k but never got around to mentioning it before I saw the PR was merged. That'd also fix an issue I raised on stable's issue tracker about the 300k window not matching the window to get points for hitting both sides.

**Comment by bdach** [comment]
I'm leaning in this direction myself as well as both replicating stable behaviour and fixing the default skin regression is likely to be too complex to be acceptable. I have this queued up and will hopefully be PRing it today for feedback.
