### ISSUE TITLE
Performance issues in multithreaded mode

### ISSUE THREAD

**Issue by memesnightmares** [ppy/osu#10298]
**Describe the bug:**

This bug manifests slightly differently in standard and taiko, but I believe the source and fix are the same.

In standard is simply feels much choppier and feels like frames are just being dropped, while in taiko the circles very quickly stop and then catch up. In both cases, when there are fewer circles on the screen (I think) performance feels fine, but once it starts getting busy it verges on unplayable on both modes.

This bug only occurs when threading is set to multithreading and I believe it was introduced in the 2020.910.0 release, although it could have been introduced in 2020.923 or before 2020.910. When I switch the threading mode back to single threading performance returns to normal.

I think this is likely the same issue that is being encountered in #10269 , however we could confirm by asking them to test with different threading settings. However the fps counters remain normal (60 fps) in my case, which I don't fully understand.

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** As stated above, 2020.925 now but the bug also presents in 1 or 2 prior versions

**Logs:**

All logs appear normal, but if any of them would be useful please do let me know and I'll add them.

**Comment by smoogipoo** [comment]
At the very least, we need:
1. A video showing what you're seeing. With the frame time graph opened up (ctrl+f11 into the mode with the graph).
2. The exact version where this has come up, because we haven't experienced it ourselves.
3. A dxdiag report https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe .

Also, please post in the original issue thread. I'll close this one.

**Comment by memesnightmares** [comment]
Both of my videos are at this link, since they were larger than the github upload limit: https://gofile.io/d/VClWMg

Once is in single threaded, the other is multithreaded.

It occurs in 2020.925.0

I can't open dxdiag as I'm running on linux.

**Comment by smoogipoo** [comment]
That looks like bad frame pacing, which hasn't changed recently. It'll eventually be fixed in the future, but this isn't immediately actionable by us.

> It occurs in 2020.925.0

What I mean is find the exact version where this has first come up. That means, you should be unable to replicate this after trying multiple times prior to version X and should be able to replicate multiple times at version X.

**Comment by memesnightmares** [comment]
Ah ok, I'm about to sign off for today, but I can try and find the version where this was introduced in the next day or two. I'm fairly certain it was the upgrade to 2020.910.0 that did it, but I'll test and update once I've confirmed.

**Comment by memesnightmares** [comment]
The issue occurs at least as far back as 2020.825.0. However, I'm almost certain I didn't notice this until more recently, so I think it may have to do with the update of some other system component that lazer isn't getting along perfectly with. I'll try another few versions back, but I'm fairly certain 2020.825.0 used to work.

**Comment by memesnightmares** [comment]
Yeah, after some further testing, it occurs as far back as 2020.707.0. So either something else in my system changed that's interacting weirdly with lazer or somehow I only noticed it once I updated to one of the 2020.9* versions. Alternatively, did the default value for the single/multi threading preference change from single to multi threaded recently?

**Comment by smoogipoo** [comment]
Nope, nothing has changed. You're just seeing bad frame pacing. Running at a non-vsync frame limiter should help a bit, if your GPU has the extra headroom for it.

But you'll likely just need to wait for us to tackle the issue in the future.
