### ISSUE TITLE
Crash on linux (nvidia)

### ISSUE THREAD

**Issue by poly000** [ppy/osu#10319]
**Describe the crash:** 
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  92
  Current serial number in output stream:  93
```

**osu!lazer version:** 
2020.925.*
**Logs:**
no logs here

**Computer Specifications:** 
```
OS: Arch Linux 
Kernel: x86_64 Linux 5.8.4-zen1-1-zen
CPU: Intel Core i5-8500
NVIDIA Driver Version: 450.66
Graphics Processor: GeForce GTX 1050 Ti
```

**Comment by bdach** [comment]
I'm not sure we can do anything with this report with the current info without having your setup.

* No logs at all? Where did you check?
* Does `dmesg` say anything?
* Would you happen to be using wayland?

**Comment by poly000** [comment]
> I'm not sure we can do anything with this report with the current info without having your setup.
> 
>     * No logs at all? Where did you check?
> 
>     * Does `dmesg` say anything?
> 
>     * Would you happen to be using wayland?

1. ~/.local/osu/logs
2.
```
[16486.052918] NVRM: API mismatch: the client has the version 455.23.04, but
               NVRM: this kernel module has the version 450.66.  Please
               NVRM: make sure that this kernel module and all NVIDIA driver
               NVRM: components have the same version.
```
3. No

I just updated the kernel and forgot to reboot...

**Comment by bdach** [comment]
Please try rebooting then and report back whether that does anything.

**Comment by peppy** [comment]
Closing as likely not our issue.

**Comment by jai-x** [comment]
The Arch `nvidia` package has a hard dependency on the Linux kernel headers and so has to be recompiled and reinstalled every time the kernel is updated, which is why you are seeing the client mismatch error.

To fix this you can just manually update the `nvidia` package with `sudo pacman -S nvidia`.
Alternatively, it may be better to install the `nvidia-dkms` package instead which will automatically perform the recompilation step for you in kernel upgrades using the [DKMS](https://wiki.archlinux.org/index.php/Dynamic_Kernel_Module_Support) system.

**Comment by poly000** [comment]
> 
> 
> Please try rebooting then and report back whether that does anything.

The problem is gone after the reboot.
