### ISSUE TITLE
Option to change certain skin elements in the same skin

### ISSUE THREAD

**Issue by jackdaguy** [ppy/osu#10378]
**Describe the new feature:**
I personally have multiple different "skins" that are just variations of the same skin but with different cursors/trails/hitcircles. An option to change certain elements would be useful. 
**Proposal designs of the feature:**
EG. cursor@2x will be default with an option to change to cursor@2x_1/2 ect. 
![Layer 1](https://user-images.githubusercontent.com/29892729/95143122-0215d580-07c1-11eb-8dde-e157e0c077b0.png)

**Comment by peppy** [comment]
Skins in lazer share the same underlying files, so making copies of them adds no overhead. Rather than adding complexity like this, we will be allowing making copied and (limited to single) user overrides.

What you want should still be feasible by using one of these two methods (your screenshot is basically showing what the "user override" will allow you to do – specify a cursor that overrides any skin choice).
