### ISSUE TITLE
Changing skin doesn't update every color in the editor timeline

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#10398]
**Describe the bug:** There are 2 (quite identical) ways to reproduce it:
1) `Beatmap skin` turned off (using skins):
- open the editor
- change skin (I don't know very much about skin colors, but I guess you need a skin that has its own set)
- result: the timeline changes the blueprint color only to nearby objects. If you scroll the timeline, you can notice all distant objects that change their color when scrolling towards them

2) Enabling `Beatmap skin`:
- similar to the previous way, open the editor with `Beatmap skin` turned **off**
- enable it
- (same result)

**Screenshots or videos showing encountered issue:** (the gif shows the second way)
![Beatmap Skin](https://user-images.githubusercontent.com/43073074/95197743-5b3e3300-07da-11eb-8aea-8dd656aaae6f.gif)

**osu!lazer version:** 2020.1005.0

**Comment by peppy** [comment]
The reason for this is that skin changes are schedule to each individual `DrawableHitObject` in order to alleviate the load of applying the change. In gameplay this works fine, but in the editor the timeline is showing hitobjects outside of their normal `Lifetime` range.

Optimally, this would be something we can fix at a `Playfield`/`LifetimeManagementContainer` level to simplify things. @smoogipoo thoughts? We could probably add some kind of "LifetimeExtend" or "range" parameter that the editor controls in such cases.

Kind of overlapping behaviour with `ScrollingHitObjectContainer`, but not confident how this should be structured.

**Comment by smoogipoo** [comment]
It's not really overlapping, iirc SHOC doesn't handle LifetimeEnd - only LifetimeStart. So yeah maybe having support at `LifetimeManagementContainer` (which HOC derives from) is a nice way to go about it.

**Comment by peppy** [comment]
@smoogipoo I guess this may be covered by your incoming changes? Unassigning for now.

**Comment by smoogipoo** [comment]
Yep, lifetime extensions will cover this.

**Comment by peppy** [comment]
This has since been resolved.
