### ISSUE TITLE
(Android)Delay hit

### ISSUE THREAD

**Issue by DjSeraph-boop** [ppy/osu#10413]
**Describe the bug:** 
Hi,tried this on android and im playing mania and the hit on note is a bit off or delay on my device,is just on the settings or is it not yet optimized? Also my phone drains alot of battery when using multithread and is there any way to save some to battery?
**Screenshots or videos showing encountered issue:** Sorry I uninstall because I cant play well maybe ill go back to the regular osu for now and visit this when its done :)

**osu!lazer version:** 
Im playing mania and its a bit off or delay and all my settings are like 1000mhz for some reason on my device(realme6) but the hit are still delay and cant play well when it had this type of bug or is it just on the settings and I use a keyboard and its definitely noticeable when u play certain maps
**Logs:**

**Comment by bdach** [comment]
Battery drain in multithreaded mode on mobile devices is expected. Single-thread mode *exists explicitly* for mobile. That said performance might not be 100% there yet on mobile, although it is a constant work in progress.

As for the perceived "delay", please record a video of what you're seeing. We unfortunately can't work with such a vague description - because of that I'm going to close this issue for now, but we'll reopen if you decide to provide a video that we can look at and investigate in closer detail.

**Comment by DjSeraph-boop** [comment]
[Uploading Record_2020-10-08-04-01-34_25a1a32208bbcdc1d450b7aa854bb161.mp4…]()

**Comment by bdach** [comment]
The file hasn't actually uploaded in the link above. Please wait until it completes or (better yet) use an off-site video sharing service if possible as the file is probably bound to be on the larger side.

**Comment by DjSeraph-boop** [comment]
Sorry but for some reason I cant put the video and tried to rapidly tap the
comment button just to put it but I delete it somehow sorry,im trying to
put it here instead and im trying to have the cap of 25mb video here on
email,sorry pls be patient

**Comment by DjSeraph-boop** [comment]
[Uploading Record_2020-10-08-04-10-24_25a1a32208bbcdc1d450b7aa854bb161.mp4…]()

**Comment by peppy** [comment]
As already mentioned, please use single thread mode for mobile for best performance/battery for now.
