### ISSUE TITLE
Add support for opening osu:// scheme links

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#10423]
**Describe the new feature:** 

If the implementation isn't difficult, why not?

It's about this button
![IMG_20201008_161321.jpg](https://user-images.githubusercontent.com/59089206/95463243-389a4e80-0981-11eb-925e-b5bdd34e7265.jpg)

**Comment by rawr-x3** [comment]
I can’t speak on Android cause it does the same on iOS, but for computer, you may have chosen osu!lazer as the directory for direct downloads, not stable.

**Comment by Gabixel** [comment]
It doesn't really work like that: the osu!direct button launches osu! with some special arguments that tell him to open the in-game osu!direct with that specific map. It doesn't have much sense to move it to lazer (for now) since it's still under development and users probably want to launch the stable version with that. I guess this is a low priority for now.

**Comment by ThatsNiceGuy** [comment]
`osu://` links already have worked on iOS for a long time. (Open new tab in safari, type in `osu://` into address bar, press enter, Safari will prompt you to open link in the game)

**Comment by Joehuu** [comment]
Yeah, reason why I didn't put an iOS tag on this issue.

**Comment by jamesnicolas** [comment]
I found this recent-ish forum post
https://osu.ppy.sh/community/forums/topics/1936976?n=1
which kind of implies osu!direct links work currenntly. Is that true? I can't seem to get osu:// links to work on linux. I also tried `xdg-open osu://`. Just wondering if there's a setting or configuration I'm missing or it just hasn't been implemented yet.

**Comment by smallketchup82** [comment]
`osu://` links are set up by default on windows. but i cannot speak for macos or linux.

i've tried it myself, setting up mime types and everything, but also can't seem to get it to work. not entirely sure what the issue is but my guess is that lazer isnt handling the url protocol on platforms other than windows. i'll give it a look and see where the problem lies.

**Comment by smallketchup82** [comment]
found the fix. it has to do with your osu.desktop file. for reference, here's mine:

```
[Desktop Entry]
Name=osu!(lazer)
Exec=gamemoderun /home/smallketchup/Desktop/osu.AppImage %u
Type=Application
Icon=lutris_osu
Comment=osu!(lazer)
Categories=Game
Terminal=false
StartupNotify=true
Hidden=false
NoDisplay=false
MimeType=x-scheme-handler/osu
```

the takeaways here is the `Exec=` field and the `MimeType=` field. in the exec field, the `%u` specifies that either a url or a file can be passed as an argument. in the mimetype field, we specify that the desktop file is to handle `osu://` fields. if you use this approach, then run `sudo update-desktop-database`, osu!direct links should open fine.

it might be wise to have velopack create and populate a .desktop file for lazer on installation/first run, since leaving it up to the user can backfire.

**Comment by alixdotsh** [comment]
I don't fully know the status of the osu:// link handling outside of it works on mobile devices now and windows/mac. I do feel like at this point when we have a proper installer for lazer there should be an option to associate osu:// links and osu file types with lazer / overwrite associations that stable currently uses with lazer.

This isn't a really important thing but I think it would be convenient. I find myself having osk files open in lazer, but osz files open in stable. This isn't a pressing issue and I did fix it on my own, but I did want to use that as an example for why we should make that an option in a future installer.

**Comment by smallketchup82** [comment]
technically [velopack](https://docs.velopack.io/packaging/operating-systems/linux#packaging) *should* be automatically setting up a [`.desktop`](https://github.com/ppy/osu-deploy/blob/master/templates/osu!.AppDir/osu!.desktop) file for linux users.

the `.desktop` file is somewhat outdated though, and could use a touch-up. i'll add that to my todo list. it might also be wise to add the `.desktop` file as an artifact for releases (so that users can download them and customize them to suit their needs).

**Comment by jamesnicolas** [comment]
oh nice! updating my desktop file worked

for some context on how I installed it, I used https://github.com/TheAssassin/AppImageLauncher

and I guess this thing doesn't add the `%u` when creating the desktop file

**Comment by smallketchup82** [comment]
@jamesnicolas can I ask what your .desktop file looked like before you added `%u`? this might help me fix the issue permanently (and have it properly integrate)
