### ISSUE TITLE
Carousel shows wrong difficulty color on a beatmap

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#10457]
**Describe the bug:** There's one case where the difficulty color doesn't seem to be correct.
The only beatmap I've found with this problem is [**this one**](https://osu.ppy.sh/beatmapsets/27246#osu/96564).

**Screenshots or videos showing encountered issue:** 
- The carousel shows the hardest difficulty with the yellow color:
![carousel](https://user-images.githubusercontent.com/43073074/95602726-9ef0a100-0a55-11eb-8e7b-9d666c9d9f3e.png)

- But it should be pink since it's 4 stars...
![star rating](https://user-images.githubusercontent.com/43073074/95602755-a6b04580-0a55-11eb-86ed-91c799be5b78.png)

- ...like in the beatmap info page (I guess it's pink there because it retrieves the difficulty from the server?):
![beatmap info overlay](https://user-images.githubusercontent.com/43073074/95602591-6c46a880-0a55-11eb-91c7-6e118da3d036.png)

**osu!lazer version:** doesn't seem to be a regression (or at least it's not recent). Anyway, the latest version is 2020.1009.0

**Comment by Game4all** [comment]
This is likely due to a lack of rounding in `BeatmapDifficultyManager.GetDifficultyRating()`:
https://github.com/ppy/osu/blob/1566882dc4aaa01088ef0f480c7b088d8e75adf4/osu.Game/Beatmaps/BeatmapDifficultyManager.cs#L125-L134

Web reports top difficulty to be 4.00* whereas local difficulty calculation returns 3.9994*, but we are rounding star difficulties to 2 decimal places so it shows up on the star rating display as 4.00* but we are determining the difficulty rating using the non rounded, star diffculty, hence it shows up with hard difficulty rating in song select.
