### ISSUE TITLE
Beatmaps hidden difficulties show 0 stars

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#10458]
**Describe the bug:** (As title) Probably an issue with the dynamic calculation?

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/43073074/95604770-5686b280-0a58-11eb-8bca-b0e49186bea3.png)
![image](https://user-images.githubusercontent.com/43073074/95605132-cc8b1980-0a58-11eb-894b-510ea92cbc1b.png)
![image](https://user-images.githubusercontent.com/43073074/95605178-db71cc00-0a58-11eb-9df8-028be71d7e47.png)

**osu!lazer version:** 2020.1009.0

**Comment by cdwcgt** [comment]
![FK4qszAvi5](https://github.com/ppy/osu/assets/34775378/c303ea20-3438-46a9-af0a-7e1ee9c1f8e7)

I asked about this on the discord server but got no response
I encountered this problem after a certain lazer version, and it has never been solved.

some beatmapset have current difficulties, but mostly 0*
expanded map panel it will give me difficult but cannot sort.

**Comment by cdwcgt** [comment]
![image](https://github.com/ppy/osu/assets/34775378/76491cb5-530f-4d33-a2ba-ed57b04a485e)

**Comment by bdach** [comment]
@cdwcgt you have a single beatmap without a set in your local database. This is not supposed to happen, hence the assertions in the code you have patched above. Since you are capable of writing code, I cannot discount the possibility of this being a data anomaly that you yourself have called into being.

Thus, unless you can replicate a way to create a beatmap without a set via the editor on current master, I don't think we want the patch above until this is proven to be affecting a bigger number of users.

**Comment by peppy** [comment]
@bdach Weirdly, I've managed to repro this multiple times from a stable import. I haven't had a chance yet to figure out how it happens... but it *might* be worth guarding defensively against..

I'm not sure if it can help with investigation, but it's also repro on my current database (run with debug and it should hit an assert on startup).

[client_36.realm.zip](https://github.com/ppy/osu/files/13632839/client_36.realm.zip)

**Comment by bdach** [comment]
> from a stable import

I wouldn't really expect a stable import to trigger this either, but it may be worth looking into. That said I'm not sure a post-facto broken database is going to help any. Logs from the stable import might. Or a dump of the actual data being imported from stable.

I guess we _could_ add the guard. But I'm loath to do it because things will silently corrupt anyways but in a slightly different way. There's a whole bunch of places that may also blow up on a beatmap with no set.

**Comment by peppy** [comment]
> There's a whole bunch of places that may also blow up on a beatmap with no set.

Agree, but it looks like the aforementioned case is going to be breaking *all* processing on a hidden background thread. Seems like one we should consider fixing..

**Comment by peppy** [comment]
Adding a sneaky fix for this one in https://github.com/peppy/osu/commit/0611a1ddc98462af34e6f1820b58dcd231769af5.

**Comment by bdach** [comment]
bit of a weird place to apply that in but sure.

**Comment by peppy** [comment]
Dunno, was touching the same class and I kinda want to make this fix happen without much attention for now 😅
