### ISSUE TITLE
Can't scroll through active result in beatmap result leaderboard in timeshift

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu#10474]
**Describe the bug:** Scrolling in beatmap result screen in timeshift with mouse scrolling and mouse dragging doesn't work when the cursor is currently placed on the active result.

**Screenshots or videos showing encountered issue:** https://youtu.be/qNmpGxF7Sio

**osu!lazer version:** 2020.1009.0

**Comment by bdach** [comment]
This is because scrolling/dragging is sort of precarious on the result screen (we have nested scroll containers in both directions, I believe, and slight movements will lock the scroll in one direction). I believe this is to be addressed by removing horizontal scroll at some point and adding a larger scrollbar, as part of a design update?

**Comment by Gonzalo-Bruna** [comment]
> **Describe the bug:** Scrolling in beatmap result screen in timeshift with mouse scrolling and mouse dragging doesn't work when the cursor is currently placed on the active result.
> 
I thought this "problem" was something known and intentional, [see here](https://github.com/ppy/osu/pull/9161)

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu/pull/18155.
