### ISSUE TITLE
Compatibility/Sync between stable and laser song folders

### ISSUE THREAD

**Issue by ms2mml** [ppy/osu#10473]
**Describe the new feature:**
Not exactly a feature request, but a follow up question to these related issues: #10376 #10221 

**Proposal designs of the feature:**
From what I understand, the file structure between laser and stable are different, so setting up a symbolic link between the songs folder of the two versions does not work if I want to sync beatmaps between the two versions. Each time I want to add a new beatmap, I need to import it to both versions of osu if I want to access it from both, meaning I will have 2 copies of the files for that beatmap.

It's not a very big deal since having both versions of osu isn't a common scenario, but I was wondering if there are any workarounds for setting up sync between the two for testing convenience (e.g. to compare beatmap behavior between stable/laser without having to manually import/export each time the beatmap is changed).

**Comment by peppy** [comment]
If you aren't deleting beatmaps, you can just hit the "import from stable" button in lazer to import over the top. It won't import beatmaps which haven't changed.

But yes, you will have two copies of the files. I did look at adding hard link support for importing but it turns out to be an issue for some of the operations we require. Eventually you will only need one client so we aren't really putting effort into this kind of functionality beyond the basics.

**Comment by ms2mml** [comment]
As a follow up, it looks like I am able to link the `%appdata%\Roaming\osu` folder to something like `D:\osu` to save space on my C drive.

**Comment by Wieku** [comment]
> As a follow up, it looks like I am able to link the `%appdata%\Roaming\osu` folder to something like `D:\osu` to save space on my C drive.
You can just change data folder in lazer settings without creating symlinks...

**Comment by ms2mml** [comment]
Oh, I wasn't aware that option existed. Somehow I missed the change folder button in the settings. That probably works better for me. Thanks!
