### ISSUE TITLE
Timeline requires too much precision to select circles

### ISSUE THREAD

**Issue by RaiLTC** [ppy/osu#10486]
I think making the selection area bigger would cause less headache

https://puu.sh/GBWWL/5c4cebff14.png

Since I personally don't see many people actually dragging the timeline using a mouse, this change would be welcomed

**Comment by Grrum** [comment]
This is a pretty reasonable request that I'd like to look into. The circles on the timeline are kind of small and hard to click individually. There are a few ways to fix this.

Option 1 is to just make the objects bigger on the timeline like in osu-stable.
This option makes the most sense to me. Unless there is a reason to make the objects small, I don't see why they shouldn't be bigger like in osu-stable to be easily grabbable all the time. If I had to guess, it might have been intentional for the circles to be smaller in osu-lazer so that the waveform can still be visible.

Option 2 is to make it so that when the mouse is hovering over the timeline, all of the objects on the timeline get bigger to be able to click on them more easily. When the mapper moves away, all of the objects shrink back to make room for the waveform.

Option 3 is to grow/shrink the objects on an indiviual basis. We could extend the hitbox for the object outside of the current visualization. When the mapper hovers over this extended hitbox, the individual object would grow in size to match the real hitbox and shrink when the mapper leaves the hitbox.

Option 4 is to add a visibility filter to hide or shrink osu objects on the timeline (similar to the filter on waveform, control points, and ticks).

Important to consider is #10487. Bigger objects would naturally lead to less "misaiming" and "cancel[ing] the selection." Properly addressing this issue could potentially address both.
