### ISSUE TITLE
Combo counters update with a delay after the hit is registered

### ISSUE THREAD

**Issue by Firmatorenio** [ppy/osu#10544]
**Describe the bug:** There's a very noticable delay on how the combo counter updates the combo, and it's especially noticable with the new legacy skin parsing. Pretty sure Stable updates the counter right after the hit. It's also present on the lazer skin, but less noticable there because it doesn't pulsate whenever a hit happens. Both look off/wrong when streams are involved.

**Screenshots or videos showing encountered issue:** https://www.youtube.com/watch?v=NuLAHLykN90

**osu!lazer version:** 2020.1017.0

**Comment by bdach** [comment]
I don't believe there's any "delay" on the legacy combo counter. If there's a visual discrepancy compared to stable it might be that the combo counter update effect is not entirely 100% on par with stable. The new updated count shows immediately, but not as the main number, but as the partially-faded larger number in the background, which shrinks down and only after that animation is completed the value is transferred onto the non-transparent counter. That's even visible on the attached video.

Default combo counter *is* delayed, however, due to using `RollingCounter` without additional logic for immediate update in case of incrementing by 1.

**Comment by Firmatorenio** [comment]
I'll admit I was wrong about Stable updating it right on hit (at least in o!s and o!c; o!t and o!m still update right on the hit), but it still looks very off on the legacy counter, because the partially faded number is, well, partially faded, and what is fully opaque (which is still the more visible number) isn't up to date. And the opaque counter makes a small pulse of its own when it _does_ update - basically every hit results in two pulses that aren't timed well together in a way that would make it look like the value gets transferred. It looks kind of messy.

Maybe I'm too used to the way legacy taiko and mania combo counters work.

**Comment by bdach** [comment]
taiko and mania counters simply aren't implemented yet. See #10526.

**Comment by peppy** [comment]
Also noticed the delay with the default counter, should be an easy fix.
