### ISSUE TITLE
Performanse Regression 2020.0814.0 --> 2020.1020.0

### ISSUE THREAD

**Issue by 2str8** [ppy/osu#10568]
First of all, i wanna notice audio latency, it's way bigger on latest client comparing to 0814 one (linux). Secondly, hp now is too aggressive (but it's can be for me only), and third part: in-game performance regression. in my monitoring older client gives me 550-650 fps strongly, while latest one (2020.1020.0) gives 400-450. it's not a big deal for me personally, but combining audio latency it feels way worse. hoping it's just a bug with some latest optimizations, i really wanna hope so.

**Comment by 2str8** [comment]
if someone forgot - in 2020.0814.0 audio latency got some upgrades, and it's way lower than previous one, but after some talking, you decided to go back in next realeses.

**Comment by bdach** [comment]
* The last changes to audio latency caused crackling on some systems. If you want to adjust, please do so manually via pulseaudio/alsa settings for now.
* See #10566 / #10337 / #7975 for drain.
* As for the performance regression part - we have nothing to go on. You haven't attached a video comparison, any specs or anything that we could diagnose by. In fact there were changes aiming to *increase* performance in song select. Please provide actual details.

Closing as this issue is inactionable at this current state. Will reopen if concrete details are provided.
