### ISSUE TITLE
osu!mania HP drain speed is too fast/harsh

### ISSUE THREAD

**Issue by mas-alone** [ppy/osu#10566]
**Describe the bug:** 
The latest version(2020.1017.0) of osu!lazer,mania mode, there is a problem that the HP Drain speed is too fast. For example, in the video, I just didn't hit the "color 300", the HP deduction speed is beyond imagination, and the recovery speed is very slow. I don't have "miss", and it also made me fail quickly.
My suggestion is to optimize the HP value of mania mode to make it closer to the "stable" version, and delete "automatically minus hp" in mania mode, which is very unsuitable for mania mode.

**Screenshots or videos showing encountered issue:** 
youtube:
https://youtu.be/_6TX8KuXMC0

**osu!lazer version:** 
2020.1017.0

**Comment by bdach** [comment]
mania HP was explicitly changed to be a bit harsher to counteract mashing, but that scoring is not final for now. 

Would appreciate if you could link the map being played.

**Comment by mas-alone** [comment]
> mania HP was explicitly changed to be a bit harsher to counteract mashing, but that scoring is not final for now.
> 
> Would appreciate if you could link the map being played.

https://osu.ppy.sh/beatmapsets/1042161#mania/2361763
Hard diff

**Comment by swoolcock** [comment]
FWIW I’ve noticed this too. Get a few 100s and as soon as there are some long hold notes, it’s pretty much game over. I’ll try to find some examples.

**Comment by bdach** [comment]
Yeah, 100s actually take away health now. While that's probably fine for high density maps, I imagine the lower the worse it gets (and even then completely mistiming multiple ones at once can end up being really bad). I'm not a proper mania player, though, so...

**Comment by genskyff** [comment]
I'm a mania4k/7k，lr2 player，"automatically minus hp" is a very unreasonable mechanism, whether it is on a high difficulty map or a low difficulty map. 
Especially in the LN map and SV map, and this leads to a huge increase in the threshold of mania, and it will unreasonably increase the difficulty of playing for professional players, especially for novices (you can’t expect freshman to be able to FC), in high  In the difficulty map, it is very common to miss more than a dozen at a short time.

**Comment by peppy** [comment]
The health processor is supposed to account for scaling to the beatmap, and doesn't seem to be doing a great job right now. I still have weird cases on osu! maps too where missing a couple of 300s could result in <10% hp for the rest of the map, in an irrecoverable way.

Had this yesterday on a HP5 beatmap.

Gonna bump this into a milestone as it's quite a frustrating issue.

**Comment by Firmatorenio** [comment]
On some maps the issue is still not resolved, for example https://osu.ppy.sh/beatmapsets/460142#mania/1002357 (7k Hard difficulty) - you still lose HP if you hit no GOODs or below here and you have to hit PERFECT in order to gain health, resulting in fails on the map that feel very cheap, even for a map short as this.

https://www.youtube.com/watch?v=cWCeLDdtsMw
In this video, in the section between 0:31 and 0:38 there was no hits of GOOD or worse (the colour hit meter can attest to that), yet there's no HP gain to be seen and that causes a fail on the first minor screwup. And even autoplay struggles to keep the HP at max for the majority of the map, making me think that hitting GREAT gives way too much less health compared to PERFECT.

**Comment by peppy** [comment]
@Firmatorenio are you able to open a new discussion to track this? probably better than re-opening this issue (as I do believe the majority of beatmaps have been fixed)
