### ISSUE TITLE
Add setting to select a random skin

### ISSUE THREAD

**Issue by igontusuwu** [ppy/osu#10585]
there could be a button that chooses a random skin for you when you feel like screwing around and/or there's too many skins for you to decide

there will also be an option to automatically choose a random skin on game startup or every time you play a map(doesn't override map skins) for the reasons above

**Comment by Yoyolick** [comment]
idk if this is something that lazer absolutely needs but I'm going to try to implement it as a good first issue, probably just starting with a random button next to skin select.

**Comment by peppy** [comment]
@Yoyolick go for it, definitely something we'd like to see. I thought there was already an issue tracking this but can't seem to find it.

**Comment by Joehuu** [comment]
Actually there's an open PR: https://github.com/ppy/osu/pull/3652. Not sure if still mergeable.

**Comment by Yoyolick** [comment]
looks like it has been inactive for a while, @peppy you said in that PR that you would like to see it more as an option in the dropdown than a UI button?
I agree with you that the second image attached below doesn't look like it fits in, I think I personally would like to see something more like the first one as opposed to hiding it in the dropdown. I as well have a lot of skins and I think to scroll all the way to the bottom each time to randomize (since it closes to dropdown each time you select an option) is inconvenient.
Something like the first option would be more practical but I'm not sure if it's possible to align options consecutively on the same line as it's not been done anywhere else in the options yet as far as I can tell.
Also please excuse the ms paint, the shuffle option would probably be pink as well since it goes with the rest of the button color scheme.
![comparison](https://user-images.githubusercontent.com/43967290/97084577-11c95280-15e6-11eb-8d52-d278f1d44f62.png)

**Comment by bdach** [comment]
Whichever UI pattern we end up going with, there's already one "random" option (but for backgrounds) - I think we should make sure that both places are consistent with each other. The random background option is the last option in the dropdown, I believe.

**Comment by Yoyolick** [comment]
intro sequence has its own dropdown with random as an option, but that's a little different in that it refers to each time the game starts, we could do this for the skin dropdown but I think that people hitting the random button will most likely be doing it more than once at a time so its inconvenient since the dropdown closes on select, and if you have a lot of skins you have to scroll all the way back down repeatedly. I'm ok with just doing the dropdown though, its just preference ill do whatever as I just want to contribute to the project :)
![Screenshot 2020-10-24 122731](https://user-images.githubusercontent.com/43967290/97086925-50660980-15f4-11eb-839c-1fed13207db5.png)
