### ISSUE TITLE
osu!taiko Editor crashing while trying to create map

### ISSUE THREAD

**Issue by Eeveelution** [ppy/osu#10642]
**Describe the crash:** 
I was trying to map with the osu!lazer Taiko Editor, I dropped in my mp3 file and everything and then i tried placing some Circles.
Everytime i Created a Circle in the Taiko Editor, the Notification "A error has been encountered, this issue has been automatically reported to the devs" would appear, and that for every time I tried to place a object. After a few of those errors lazer finally crashed.

If this is important I tried placing objects at the exact position where the Timeline is (On the Taiko playfield the exact location of the approach circle)

**Screenshots or videos showing encountered issue:** 
I sadly did not record any video or made any screenshots, all I know is that while trying to place objects I got the error notification, after 3-4 of those lazer crashed.
**osu!lazer version:** 
2020.1031.0

[performance.log](https://github.com/ppy/osu/files/5470041/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5470042/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5470043/updater.log)
[database.log](https://github.com/ppy/osu/files/5470044/database.log)
[network.log](https://github.com/ppy/osu/files/5470045/network.log)

**Computer Specifications:** 
Intel Core i7-6700
16GB RAM
NVIDIA GeForce GTX 1060 6GB

After trying it out again I cannot seem to be able to replicate this issue, not sure if this was just a 1 time thing but nonetheless i decided to post an issue report here.

**Comment by bdach** [comment]
Reproduction steps:

1. Start editing new beatmap in taiko ruleset
2. Add new sample control point at any point in time
3. Place new object before created control point (but any time point will probably work for reproducing)

Crash site is:

https://github.com/ppy/osu/blob/7d090e0d2ec7272f0583017d2d2eceaff989c94f/osu.Game.Rulesets.Taiko/Audio/DrumSampleContainer.cs#L56

Reason for the crash is that `DrumSampleContainer` is not able to respond to possible changes in the sample control point list, as it creates its own local list when a new beatmap is started (because it has no sample points on its own).
