### ISSUE TITLE
Random stutters

### ISSUE THREAD

**Issue by chenxi050402** [ppy/osu#10681]
**Describe the bug:** 
Random stuttering every around 10 seconds, this only happens recently.

**osu!lazer version:** 
2020.1031.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5481989/database.log)
[network.log](https://github.com/ppy/osu/files/5481991/network.log)
[performance.log](https://github.com/ppy/osu/files/5481992/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5481993/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5481995/updater.log)

**Comment by chenxi050402** [comment]
It draws a single red line in ctrl f11 when a stutter happens.

**Comment by bdach** [comment]
Please attach a video or a screenshot of this, preferably with the "red line" showing.

**Comment by smoogipoo** [comment]
Occasional "red line" (swapbuffer) spikes are generally due to one of two things:
1. You're running at an unlimited frame limiter. osu!lazer should be run at 2x, 4x, or 8x frame limiter.
2. There's a background app causing the stutter, like discord, a web browser, f.lux, shadowplay (or radeon's equivalent), OBS, etc...

Since it's happening every 10 seconds for you, it's more likely that option 2 is what's happening here.

**Comment by Joehuu** [comment]
Closing until we get a follow-up response.
