### ISSUE TITLE
Online difficulty icon always Easy

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu#10725]
**Describe the bug:** 
The online beatmap information(e.g. multiplayer lobby, beatmap details page) always displays as `Easy ` icon. However local beatmap list is fine
**Screenshots or videos showing encountered issue:** 
![osu_2020-11-07_16-51-53](https://user-images.githubusercontent.com/50285552/98437338-4677f680-211c-11eb-8776-ef87695b137f.jpg)
![osu_2020-11-07_16-53-33](https://user-images.githubusercontent.com/50285552/98437350-61e30180-211c-11eb-97b9-75d5913d1b71.jpg)
![osu_2020-11-07_17-05-29](https://user-images.githubusercontent.com/50285552/98437357-627b9800-211c-11eb-972f-f8a58301d423.jpg)
**osu!lazer version:** 
https://github.com/ppy/osu/compare/master...PercyDan54:custom
**Logs:**
[database.log](https://github.com/ppy/osu/files/5504508/database.log)
[network.log](https://github.com/ppy/osu/files/5504509/network.log)
[performance.log](https://github.com/ppy/osu/files/5504510/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5504511/runtime.log)

**Comment by bdach** [comment]
Regressed in https://github.com/ppy/osu/pull/10306 - icon is attempting to perform diffcalc on locally non-existent beatmaps. I see two main options here, both bad for different reasons:

1. Disable on online screens using the [`performBackgroundDifficultyLookup` param](https://github.com/ppy/osu/blob/master/osu.Game/Beatmaps/Drawables/DifficultyIcon.cs#L77) - easy, but also sometimes wrong (see timeshift playlist creation screen - wedge star ratings will include mods, playlist ones won't).
2. Always attempt to fetch local beatmaps before performing diffcalc (i.e. [here](https://github.com/ppy/osu/blob/16f55de4952be72c7ec32549d7a66b456e8dc209/osu.Game/Beatmaps/BeatmapDifficultyCache.cs#L188-L194)) - more correct, but also wildly more expensive (pointless re-queries). Due to the new structure it can't be done any deeper as re-fetching any deeper in the call tree could result in online values getting cached, and as cache entries aren't ever evicted, that would break dynamic calculation going forward.

Unassigning for now pending discussion on how to approach this.
