### ISSUE TITLE
Raw input is broken

### ISSUE THREAD

**Issue by zvshka** [ppy/osu#10743]
**Describe the bug:** 
Raw input on Wacom tablet is totally broken
**Screenshots or videos showing encountered issue:** 
https://1drv.ms/u/s!AoLs_AsM0ODIg5YjxTByuLMUKDOZlQ?e=6GF1CV
**osu!lazer version:** 
Latest (2020.1031.0)

**Logs:**
https://1drv.ms/u/s!AoLs_AsM0ODIg5YiSq-VUKyQjeRkJg?e=AkNnKb

**Comment by bdach** [comment]
Raw input is already known to behave wrong with some tablets (https://github.com/ppy/osu/issues/3364, https://github.com/ppy/osu/issues/3443). We will most likely be addressing this with per-platform implementations instead of the current osutk one.

Closing as duplicate (even if it strictly isn't, not much point to have several similarly vague issues).

**Comment by peppy** [comment]
For reference, was this with the vanilla wacom drivers? We can only support these.

**Comment by zvshka** [comment]
Yes, original

**Comment by zvshka** [comment]
Updated yesterday
