### ISSUE TITLE
Song audio ducking when other sounds play (e.g. hitsounds, menu sounds).

### ISSUE THREAD

**Issue by Akiwoo** [ppy/osu#10765]
**Describe the bug:** 
When a loud song is playing, any other sounds like hitsounds or menu sounds (pressing on a mod for example) will slightly duck the volume of the song down, almost like a limiter compressor. This effect is only subtle, but noticable/distracting.

I've google'd the issue, and people do complain about an issue with windows ducking audio like this, but I only get this problem in osu!lazer, I do not get this same issue in regular osu!

I've followed multiple fixes including reinstalling drivers, making sure audio enhancements are not on etc.

**Screenshots or videos showing encountered issue:** 
Tried to record a video of issue, but with audio compression on youtube the effect is not noticeable, as it is subtle.
**osu!lazer version:** 
2020.1109.0
Have noticed this issue with multiple previous versions.

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/5515664/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5515665/updater.log)
[database.log](https://github.com/ppy/osu/files/5515666/database.log)
[network.log](https://github.com/ppy/osu/files/5515667/network.log)
[performance.log](https://github.com/ppy/osu/files/5515668/performance.log)

**Comment by peppy** [comment]
Initial thought are that we may have the overall bass volume set too high. I believe windows (or drivers?) will automatically do this to avoid peaking.

Probably need to cross-check with stable to see what the difference is (do we have a clamping / multiplier on stable that keeps the overall game volume lower?).

**Comment by enoslayd** [comment]
> I can reproduce this on at least one of my windows PCs.
> 
> Initial thought are that we may have the overall bass volume set too high. I believe windows (or drivers?) will automatically do this to avoid peaking.
> 
> Probably need to cross-check with stable to see what the difference is (do we have a clamping / multiplier on stable that keeps the overall game volume lower?).

actually, lazer is much more louder than stable (at least to me)

**Comment by peppy** [comment]
On a quick check of stable, there's no ratios being applied anywhere, so that's definitely not the issue.

What may be going on is that in lazer we are playing more concurrent samples than stable. Will need to compare the concurrent sample playback logic and potentially match what stable is using (recycling previous samples rather than always playing a new one).

**Comment by peppy** [comment]
Checking concurrency, everything actually looks quite correct as well. Stable has a max concurrency (per sample) of 8, while lazer is specifying 6. Also confirmed that samples are being reused correctly and concurrency is being respected.

Remaining possibility is that the menu effects (and potentially default hitsounds) are actually louder than the ones used on stable.

@Akiwoo can you confirm whether this happens say, at some select when selecting a new beatmap (when only one "effect" sample is played)? Or does it only happen during more intense gameplay segments? Can you also confirm whether it happens on the classic skin, or only custom/lazer default skins?

**Comment by Akiwoo** [comment]
@peppy This happens during song select at menu and during song play. Can only notice on "loud" parts of a song. quiet songs I cannot hear the issue. I found a few songs that I could get to replicate the issue on my end, and used those to test. Happens on both custom skin and default skin.

**Comment by peppy** [comment]
So this is definitely a [windows-level thing since vista](http://www.un4seen.com/forum/?topic=17392.msg122017#msg122017) (and can be disabled using [this kind of dodgy driver-level hack](https://kawamoto.no-ip.org/henteko/myapp.html#dpeaklim).

The next question is why does this apply to lazer and not stable? It's definitely due to lazer playing louder than stable, so the next step is going to be figuring out why that is.

Just leaving the trail so far, I plan to continue investigating this.

**Comment by peppy** [comment]
Volume levels match on stable and lazer for audio playback:

![image](https://user-images.githubusercontent.com/191335/99046749-8e909080-25d6-11eb-8d4c-2f0b9f15a32c.png)

You are probably noticing it more on lazer due to the loud volume of the interface effects.

Of course, we do really want to avoid this happening in the first place. I'll experiment with dropping the playback volume of music and effects so they are generally not able to add together to exceed the peak allowed volume.

**Comment by peppy** [comment]
@Akiwoo can you give the latest release another test? I've adjusted a lot of the samples which were way too loud to give us some overall headroom.

**Comment by Akiwoo** [comment]
@peppy does seem to still be happening. Tested on the same loud song as before and still same result, can't tell if much has changed in terms of how much but can still hear the song audio ducking when hitsounds are played. Obviously this is only happening when master volume is at 100%, and lowering the master volume has just been my temp fix.

**Comment by peppy** [comment]
Are you testing using the default skin still? Do you notice the same issues with "osu!classic" skin? And if you do, can you compare with osu-stable? In theory they should both run into the same issues, since we aren't doing anything different over here than what stable is doing (and the assets are the same).

**Comment by Akiwoo** [comment]
Sorry, that was a test with my custom skin. Just redid the test using default lazer skin and default classic skin and cannot hear the ducking. Also just tested pressing the menu buttons and they aren't ducking the audio like they used to. So my skin's hitsounds are now too loud I guess

**Comment by peppy** [comment]
Can you confirm that your skin in stable has the same issues? If not, I'd appreciate attaching your skin or an audio comparison of stable and lazer so we can ascertain why the behaviour is different between the clients. The only thing that comes to mind is that concurrency of hitsamples may be higher in lazer than stable.

**Comment by Akiwoo** [comment]
Okay testing stable and my custom skin still ducks audio. it's not _as bad_ as lazer is, but still noticeable. Probably never realised this on stable as I never played at 100% master volume on stable before this test.

**Comment by peppy** [comment]
If you can get an audio recording of your system sound in both scenarios (on the same beatmap) that would be useful for analysis.

**Comment by Akiwoo** [comment]
I recorded the intro of the song I've been testing, and using my custom skin for both osu!classic and osu!lazer, looking in audacity I can definitely see more peaking in lazer. Both programs at 100% volume. Also not sure if relevant but when I listen back, I cannot hear the ducking.

[osu audio test.zip](https://github.com/ppy/osu/files/5641636/osu.audio.test.zip)

**Comment by peppy** [comment]
We are currently working on a revamp of all the sound effects in lazer. This issue is being taking into consideration during this process.
