### ISSUE TITLE
Rewinding to beginning of autoplay/replay will miss first hit object

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#10811]
**Describe the bug:** In any game mode, rewinding to beginning or rewinding at lead-in time will go straight to the first object and will miss. I think it should rewind to the start of the lead-in time to prevent misses and weird cut off in replays at the start.

**Screenshots or videos showing encountered issue:** 
![3AtAvna1ff](https://user-images.githubusercontent.com/35318437/99007754-b52cc980-24f9-11eb-98f1-1b45c8a095ea.gif)

**osu!lazer version:** 2020.1109.0

**Logs:** not needed

**Comment by peppy** [comment]
Sounds like a potential regression of replay frame playback logic? Might mean we were missing test coverage..

**Comment by smoogipoo** [comment]
This isn't a regression, it's just that the start time of the graph is exactly the start time of the first DHO, which is also the start time of the click frame in the replay.

**Comment by Flutterish** [comment]
I did some tests ( this is notorious in my ruleset ) and it turns out, the last rewound frame has its events trigerred with negative elapsed time and then never again since lazer thinks it already trigerred them. The solution could be to simulate these events with 0 elapsed time at time = start time of the replay frame on the last rewound frame.

**Comment by ekrctb** [comment]
I cannot reproduce. Can I have a beatmap that can be used to reproduce this issue?

**Comment by Joehuu** [comment]
Beatmap is https://osu.ppy.sh/beatmapsets/296913#osu/666535, can confirm the PR fixes it.
