### ISSUE TITLE
After seeking far into the future in non-frame-stable contexts, previous hitobjects remain alive

### ISSUE THREAD

**Issue by AndyThePie** [ppy/osu#10857]
**Describe the bug:** 
In the editor, you can sometimes select previous objects that are a very long time back (no longer on screen + multiple combos ago). I have no idea what causes this.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/cqepx3

**osu!lazer version:** 
2020.1114.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5544183/database.log)
[network.log](https://github.com/ppy/osu/files/5544184/network.log)
[performance.log](https://github.com/ppy/osu/files/5544185/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/5544186/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/5544187/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/5544188/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/5544190/runtime.log)

**Comment by peppy** [comment]
This is a known issue and happened ever before pooling. Reproduction is easy on a long beatmap: seek forward far into the future and it'll be in this state.

The cause is lifetimes not correctly getting set in non-frame-stable contexts (when time moves too fast). I don't think we have an existing issue tracking this so I'll leave this open and milestone it.

**Comment by smoogipoo** [comment]
I think there is an additional issue here with depth ordering in the editor. Will look into it myself.
