### ISSUE TITLE
Visualizer bars around the osu! logo have visible Moiré patterns 

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#10875]
**Describe the bug:** 
On skins that have ``MenuGlow`` set to high luminosity values, visualizer bars around the osu! logo have visible [Moiré patterns](https://en.wikipedia.org/wiki/Moir%C3%A9_pattern). These patterns change slightly depending on song intensity (I think kiai time changes the amount of bars and makes the patter more visible) and view parallax.

**Screenshots or videos showing encountered issue:**
``MenuGlow: 255, 255, 255`` on these screenshots (what I have set for my skin)
![](https://user-images.githubusercontent.com/11320483/99279377-d6165700-2838-11eb-81b0-8c74fa533b6d.png)

**osu!lazer version:** 
2020.1114.0

**Comment by peppy** [comment]
You could set it lower.

**Comment by LumpBloom7** [comment]
There are several layers of bars drawn over each other. The default colour actually has an opacity of 0.2. MenuGlow completely lacks this opacity adjustment, so full opacity bars are drawn over each other.

Instead of setting the `AccentColour`, the MenuGlow colour should be applied to `Colour`, this ensures that the bars still retain their transparency. An alternative would be to apply the same opacity adjustment before setting `AccentColour`.
```cs
AccentColour = skin.Value.GetConfig<GlobalSkinColours, Color4>(GlobalSkinColours.MenuGlow)?.Value.Opacity(0.2f);
```

I'd PR this myself, but given that it alters the look of the skinned visualizer by a significant amount, I want to make sure that this is an appropriate resolution to this problem.

**Comment by peppy** [comment]
@LumpBloom7 that sounds fine. hopefully it looks very close to stable with that change applied. let me know if you'd prefer i make the change, otherwise go ahead and PR it!

**Comment by LumpBloom7** [comment]
Okay. I'll do it in a bit then.
