### ISSUE TITLE
Combo color of hitcircle inside the editor timeline changes to white when you undo a change

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#10911]
**Screenshots or videos showing encountered issue:** 
https://youtu.be/BCIY4Gst__E

**osu!lazer version:** 
commit 7f3c8ad744df80079bc377b63c570ca6243426f9

**Comment by peppy** [comment]
Seems like it may be another pooling related regression? This definitely used to work.

**Comment by bdach** [comment]
Yep, this is also due to pooling. The following line fails to retrieve the drawable representation of the restored hitobject:

https://github.com/ppy/osu/blob/194f2e621b75003ed1a5027a33b49eeb7c679e7f/osu.Game/Screens/Edit/Compose/Components/Timeline/TimelineHitObjectBlueprint.cs#L161

which in this case hasn't made it back to playfield yet as it only restored in a callback of `HitObjectUsageBegan`. It might be better to decouple the timeline objects from DHOs and make them look up the colour themselves.
