### ISSUE TITLE
Dissapearing combo counter in catch

### ISSUE THREAD

**Issue by ch4tie** [ppy/osu#10929]
The combo counter in catch dissappears after 1 combo. It re-appears after a miss, but will dissappear after 1 combo once again. Seems to happen on all maps and even in replays, as seen in the video. It only seems to happen on skins with the combo above the catcher, since the combo stays on the osu!lazer skin (which has the combo counter next to the score counter) but dissappears on the osu!classic skin (which has the combo counter above the catcher). Can't fully test this since osu!lazer is the only skin I know of that doesn't have the combo counter above the catcher.

Video of the bug: https://icebearbestbear.s-ul.eu/OsN8KxyW (only contains dissappearing combo counter while playing and watching replays)

version 2020.1120.0

**Comment by bdach** [comment]
This is quite a major one... Regressed with #10797. `CatchPlayfield` does this:

https://github.com/ppy/osu/blob/194f2e621b75003ed1a5027a33b49eeb7c679e7f/osu.Game.Rulesets.Catch/UI/CatchPlayfield.cs#L62-L67

The issue is caused by the ordering of calls here. `base.Add(h)` also subscribes to `OnNewResult`, and in fact hooks up `ScoreProcessor` through that. Therefore, with this order, `CatchPlayfield`'s local `onNewResult` receives the judgement result before it's ran through the score processor, which in particular means that the combo counter always sees `ComboAtJudgement == 0`, which is why the counter doesn't update:

https://github.com/ppy/osu/blob/ec30ca24c5cc7875b58fea933f00c398ec2dac41/osu.Game.Rulesets.Catch/UI/CatchComboDisplay.cs#L45

"Just reversing" the order of subscriptions fixes, but the fact that there's an unsafe window in which rulesets can subscribe to `OnNewResult` and get incomplete judgement results has me very worried... Looking for opinions here. Not sure how to even approach this as there are multiple layers of events involved.

**Comment by peppy** [comment]
@ekrctb just going to loop you in here since you're currently looking at osu!catch pooling support. may be something to consider when making changes.

**Comment by ekrctb** [comment]
My current work in progress osu!catch pooling implementation doesn't fix this issue. I used `Playfield.NewResult` and `RevertResult` events but it doesn't change the underlying issue.
I think if an event invocation ordering affects the logic then the code is fragile. Though I don't immediately see how to implement it, probably the combo counter should be exposed as a bindable from somewhere and the catcher uses it.

**Comment by bdach** [comment]
I guess [`GameplayBeatmap.LastJudgementResult` might be usable](https://github.com/ppy/osu/blob/060acb9010892b3b5fa7b3a5843e2a842a54f23c/osu.Game/Screens/Play/GameplayBeatmap.cs#L46), which doesn't however change the fundamental lack of safety of subscription to `OnNewResult`.

**Comment by peppy** [comment]
@smoogipoo any thoughts on this one? Basically, `CatchPlayfield` is binding to `OnNewResult` in its ctor which is giving it precedence to handling this event - before `DrawableRuleset`, which means that the code in `Player` is not running in time to populate the combo etc.

https://github.com/ppy/osu/blob/5053a7baf97526a0d28a1d9202441a395063697a/osu.Game/Screens/Play/Player.cs#L264-L269

Has changed a bit from @bdach 's comments above, but generally the same issue (and the same "hacky" fix can be applied of moving the bindings to `BDL` or `LoadComplete` in `CatchPlayfield`).

**Comment by peppy** [comment]
Proposed fix: create a `protected virtual OnNewResult` in `Playfield` and override that instead (instead of subscribing to a `public` event). Not sure having a class subscribe to its own public events is something we generally want?

**Comment by smoogipoo** [comment]
Events should not be used to enforce ordering at all. I think the combo counter is doing a bad job here by relying on members of `JudgementResult` to be populated when the event location is the `Playfield`. I think one would expect these things to be populated by the `ScoreProcessor`, so there should be events exposed from there to work with. It already sorta does this with `NewJudgement`, with the caveat that it doesn't give the judged DHO, but perhaps it should?
