### ISSUE TITLE
No volume controls in Editor

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#10958]
`Alt` + `Scrollwheel` works everywhere outside the editor. This key combination currently scrolls the timeline

**osu!lazer version:** 2020.1121.0

**Comment by bdach** [comment]
Currently the editor explicitly suppresses any scroll events from propagating outside of it:

https://github.com/ppy/osu/blob/dcfd9517b7c2cda6260632d7ffc9016941f07f4d/osu.Game/Screens/Edit/Editor.cs#L403

This is so that scrolling to seek works anywhere. It's going to be really difficult to figure out a sensible UX that has a possibility of having both volume and scroll available from anywhere. Almost certainly one of them would have to use a modifier key, and <kbd>Alt</kbd> is already taken (zooms waveform/top timeline in/out).

**Comment by peppy** [comment]
Since the use of alt is localised, I think it's fine to deal with this as we are elsewhere.
