### ISSUE TITLE
TestSceneCatchModRelax behaves erratically

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#10967]
https://drive.google.com/file/d/1xlhx2XevqLfx4mMGmJCuM7aSFsRvvvbw/view?usp=sharing

* Jittering back and forth.
* Moving to the hyperdash for one frame before any hitobjects become visible.
* Prior to https://github.com/ppy/osu/pull/10966, it would miss the hyperdash at 200% speed.

Perhaps an issue with framed replay handler? I've tested one commit prior to https://github.com/ppy/osu/pull/10605 and it still occurs, so it's not a recent regression.

**Comment by peppy** [comment]
This test isn't using the replay handler (is testing relax specifically, which uses the live mouse position).

- The jittering you're seeing around 19s is from float precision while the `Player` instance is appearing (does a scale which is likely causing this).
- The weird movement at 12s is possibly due to initial score calculation or something touching the score? Seems to be the until step running and the current value of `ScoreProcessor.Combo` having changed.

Not sure these need to be fixed since they are purely visual (especially the first, second may warrant further investigation).

**Comment by smoogipoo** [comment]
The one at 12s is caused by the cursor being left in the bottom-left position from a previous test run. I think the third point is still an issue though.

**Comment by smoogipoo** [comment]
Let's close this issue for now as it's relatively minor, and revisit if it ever occurs again.
