### ISSUE TITLE
Weird behaviours with screen modes on MacOS

### ISSUE THREAD

**Issue by iamminimoon** [ppy/osu#11087]
Describe the bug: The latest update changed the way lazer behaves on certain screen modes (as well as a few crashes with changing from each mode). I'm not sure if some of these were intended, but compared to the previous version it has more workarounds to do stuff (Explanation based on pure experience)

1. lazer now has three screen modes: Windowed, Borderless, and Fullscreen. The previous version only has Windowed and Fullscreen.
<img width="449" alt="Screen Shot 2020-12-04 at 13 34 45" src="https://user-images.githubusercontent.com/55867946/101130183-92dc2680-3635-11eb-943f-bd6b24fb1c3a.png">

2. on **Windowed**, the experience is practically the same as the previous version. lazer runs as a usual floating window that can be switched into fullscreen by clicking the fullscreen button on the window. However, going into fullscreen from this keeps the screen mode set as Windowed, and switching to Fullscreen mode from this mode results in either black screen or crash (mostly depending on whether you're already on fullscreen or not).

Switching screen mode from any mode to Windowed mode results in the game stretched as two sized window:
<img width="1426" alt="Screen Shot 2020-12-04 at 13 55 09" src="https://user-images.githubusercontent.com/55867946/101131761-683f9d00-3638-11eb-86b3-fda2395d7f69.png">

3. If lazer starts running on **Fullscreen** mode, the game would behave as if it fills on multiple screens (in my case, it's four screens). The cursor feels slower to move with trackpad and the tablet driver only maps the top left quarter area of the screen. You can't switch tabs from the game to the desktop or any app, and moving the cursor towards the top and the bottom of the screen doesn't open the top bar and the app dock which MacOS has. You can only access anything outside the game by changing the screen modes or closing the game as a whole.

Video demonstrating Fullscreen mode and then switched to Windowed mode, ended with a black screen: https://youtu.be/gsdwiDHUlE4

4. I haven't tried the **Borderless** mode too much to know about it, but using it straight up changed the game into this.
<img width="1440" alt="Screen Shot 2020-12-04 at 14 02 12" src="https://user-images.githubusercontent.com/55867946/101132391-878afa00-3639-11eb-8a32-8a3f627fb456.png">

osu!lazer version: 2020.1203.0 (latest)

**Comment by peppy** [comment]
I've tested throughly on macOS and do not have any of the issues, so it's likely due to one of the following:

- You are not running catalina (please specify your OS and hardware)
- You are running a retina display (certainly looks like it based on the borderless display). We may not have this supported correctly for desktop macOS. Please state your screen resolution and display type.

**Comment by iamminimoon** [comment]
I'm using Macbook Pro with the tech specs copied straight from the setting:

MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)
Processor: 2,4 GHz Quad-Core Intel Core i5
Memory: 8 GB 2133 MHz LPDDR3
Graphics/Display: Intel Iris Plus Graphics 655 1536 MB (2560 x 1600). The display here seems like it is using a retina display.

The OS that I use would be indeed Catalina, though I do intend to update it to Big Sur one day which would also apply to the first point you mentioned on the comment.

**Comment by peppy** [comment]
@iamminimoon do you happen to have a dev setup? would be interested in having you try out a framework build if so (specifically on this branch: https://github.com/ppy/osu-framework/pull/4099)

**Comment by iamminimoon** [comment]
I'm not familiar with development stuff unfortunately, so I don’t think I'm capable of giving that level of contribution yet...
I can strictly report things on the release builds as of now, but I'd be down with looking more into it if possible.

**Comment by peppy** [comment]
Okay, please report back after the next release (which will likely include the linked fixes). In theory your issues should be resolved by it.

**Comment by SevenChords** [comment]
having the same issues on a 5k imac, early 2019, running macos catalina (10.15.7), but i have an addition to make to previously stated issues/observations:

1. the issues with rendering multiple screens (point 3 of the original issue posted) in fullscreen mode is only present on resolution >1440p for, setting the resolution to 1440p resolves that issue as well as a graphic tablet only affecting the top left quarter of the screen. (although it only displays the game on a quarter of the screen now with the rest of the screen being black)
2. these issues are all present since release 2020.1203.0, 2020.1128.0 and prior didn't have any of the issues mentioned
3. same issues are present on my 2020 apple m1 macbook running macos big sur as well

**Comment by peppy** [comment]
As above, please report back after the **next release** (which will likely include the linked fixes). In theory your issues should be resolved by it.

Please refrain from commenting until this happens, unless you're willing to build yourself.

**Comment by peppy** [comment]
Closing this as probably-fixed-via-sdl.
