### ISSUE TITLE
Storyboard enum parsing inconsistent with stable

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu#11098]
**Describe the bug:** 

Setting the `Looptype` parameter of a storyboard animation to a high integer works on stable, but behaves incorrectly on lazer.

Found on the SB of [Feryquitous - (S).0ngs//---::compilation.[TQR-f3]](https://osu.ppy.sh/beatmapsets/1124097#osu/2348896):
As an example, the counting units' digit animation (01:55:238, .osb line 169448) is declared like this:
```
Animation,Foreground,Centre,"sb\HUD\timer\counter.png",330,240,10,108,16
```
with `Looptype` set to 16.

Moreover, manually changing say `Foreground` to `16` gives a parsing error on stable and deletes the sprite, but on lazer it imports fine and the animation is still visible. Changing `Animation` to `16` gives an error on stable and deletes the sprite, but on lazer it imports fine except that the animation disappears.

Probably the same bug, but the error handling is a different issue.

**Screenshots or videos showing encountered issue:** 

Stable behaviour - all digits count properly, as if `Looptype` was `LoopForever` (note that it starts from 8 because of fade):
![stable](https://user-images.githubusercontent.com/36758269/101225389-9ef5d180-3691-11eb-9d7b-2765e30760b6.gif)

Lazer with auto mod - units' digit counts to 9 only once, as if `Looptype` was `LoopOnce` (starts from 0, ignoring fade):
![auto](https://user-images.githubusercontent.com/36758269/101225426-b765ec00-3691-11eb-8a90-22894a762146.gif)

Lazer with cinema mod - same as previous except it properly starts from 8:
![cinema](https://user-images.githubusercontent.com/36758269/101225444-bfbe2700-3691-11eb-8712-971ededde53d.gif)

I got the auto behaviour a few days ago and a couple times today, but now only the last behaviour happens. I think it's just inconsistent and not specific to the mod.

**osu!lazer version:** 
Latest release 2020.1204.0 / 9064ca9

**Logs:**

N/A - tell me if they would help

**Comment by bdach** [comment]
I cannot reproduce this. I checked a few of these storyboarded counters and they increment correctly as far as I can tell.

**Comment by Walavouchey** [comment]
This happened on all of them. Redownloading the map fixed the issue. I checked the .osb file and it seems it has been updated, with the declaration changed to this:
```
Animation,Foreground,Centre,"sb\HUD\timer\counter.png",330,240,10,108.16,LoopForever
```

Was able to reproduce it again by changing the last value manually.

**Comment by peppy** [comment]
The files have not changed on the server since point of ranking said beatmaps.

So what we need to do is figure how the last value changed (and whether we need to support it). Can you check whether this happens from saving the map in the osu-stable or lazer editor? Alternatively, could it be from having run something on your PC which altered the files?

**Comment by bdach** [comment]
I'm inclined to say this is a non-issue and well within undefined behaviour. Both stable and lazer expect the `LoopType` to be a textual value, either `LoopOnce` and `LoopForever`. The original version of the `.osb` specified 16.

Now this is the quirky part. `16` can actually pass through `Enum.Parse`, because enums aren't actually enums, as much as aliases for numeric types. Therefore, `Enum.Parse<AnimationLoopType>("16", out var value)` return `(AnimationLoopType)16`. Which is basically just 16. [See this sharplab for reference.](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQiAM7EGYAEA3uvqfnAQKZQQC2+AKpQM7BElmcCCANB56QBC/fAF8RIxAnZoBZAKI1aAOgZgAngAUAhmGaUAPE1YA+ABQAiLhZ74A9hDYA3Xfm0BKANwjOcJAE4zD29ZOXwfBSVVDR09Q2NgcwtBG3tHfBcwfAAjLwjSP0DckLDw0LlFOmitXX0jFkTLJAA2VIdnVwB3AAttYDzygUKzHr6BznE0USA=)

The fact that this worked in stable is caused by the fact that in the animation running code, stable does a equality comparison against `LoopOnce`, while lazer does a non-equality comparison against `LoopForever`. On its face it reads like the two are equivalent, but they actually aren't, because of exactly this possibility of an undefined value slipping through.

All of the above notwithstanding I think the original line can be definitely considered as malformed. About the only question in my mind at this point is whether it should be silently accepted as above, or raise a parsing error.

**Comment by Walavouchey** [comment]
It must have been caused by some script I wrote a while ago, although I usually run them on copies of the original so i'm not sure.

Either way, I agree with raising parsing errors, since it might later catch other maps with errors that work on stable but shouldn't.

**Comment by smoogipoo** [comment]
Unfortunately I think using raw values is actually quite a common occurrence in storyboards. It's the reason why the storyboard decoder falls back to using `Anchor.TopLeft` instead of throwing an exception for origins: https://github.com/ppy/osu/blob/87da6b3270ed98112399d99f6b92b3acdab440ca/osu.Game/Beatmaps/Formats/LegacyStoryboardDecoder.cs#L339-L340

Unfortunately it's not as easy to say "just don't use external tools" for storyboards, so we just have to suck it up and implement it similarly to origins for loop types.

**Comment by bdach** [comment]
I mean in general I agree, but surely there is nothing sane to be done with a loop type of `16`? That was never valid, was it? That said I'm completely fine with coercing anything that's not a string value of that enum to `LoopForever` to preserve compatibility, but I'd at least probably log as error or something...

**Comment by smoogipoo** [comment]
To be clear, it's not anything not a string value, it's values outside of the valid range which in this case is `{0, 1, LoopOnce, LoopForever}`.

I don't think logging will do much, so long as people use external tools to create storyboards (i.e. for as long as we don't have a scripting language of our own) this is always going to be the case. It's just going to be unnecessary verbosity in all regards, imo.

**Comment by bdach** [comment]
Right, 0 and 1 are also unambiguous, that's what I meant. Fair enough, I guess an `IsDefined` check of whatever falls out of `Enum.Parse` should do.
