### ISSUE TITLE
Linux Phone Support

### ISSUE THREAD

**Issue by clay53** [ppy/osu#11152]
**Describe the new feature:** 
New phones that run Linux on ARM are being released like the [Librem 5](https://puri.sm/products/librem-5/) and the [PinePhone](https://www.pine64.org/pinephone/). While these devices will very likely not be in popular use for quite a long time (I don't have one but that'll be my next phone after my current one finally combusts), I just want to make this request for the time being to track support to add support for them. I'm not sure if it's already possible to build for these devices and if not, what changes would have to be made. However, I can assure you that osu! would probably be one of the most popular games (and a good benchmark for gaming capability) on there if official builds started being released for it.

**Comment by bdach** [comment]
It's way too early for this request. Our existing mobile versions already have large enough issues to deal with first (lack of mobile input methods, Android crashes on every suspension).

Closing as out of scope. Official support might never actually be guaranteed due to limited personnel/bandwidth. PRs adding support are welcomed, however.
