### ISSUE TITLE
Add method for Android users to choose beatmap background in editor

### ISSUE THREAD

**Issue by pixelguy126** [ppy/osu#11219]
In android osu lazer to use the editor it says drag and drop the photo but how you cant drag and drop

So why not a button that makes you chose a file from the osu directory

**Comment by bdach** [comment]
Improvements to general file handling on android will be coming next release, but not to the editor yet. Please understand that android development is low priority for now until the desktop version is complete.

And again, I would ask that you do not ignore the issue template.

**Comment by peppy** [comment]
For android I believe the built-in file picker is what we want (to my knowledge, unlike iOS there's no standardised modal overlay file picker which can be called upon? maybe something has changed since I last tested though).

**Comment by bdach** [comment]
Yeah as far as I know Android will delegate the file picking to some other activity (file manager, etc.) via an intent, which is going to be a problem there, seeing that the game can't yield the opengl context cleanly yet.

**Comment by bdach** [comment]
This is now somewhat possible after adding a directory selector popover to the editor, as well as https://github.com/ppy/osu-framework/pull/4838. You still need to grant permissions manually to the game so that it can access files, but other than that I'm going to tentatively close this one as resolved.
