### ISSUE TITLE
Unknown "audio" delay since upgrading PC

### ISSUE THREAD

**Issue by atemerino** [ppy/osu#11223]
**Describe the bug:** 

I've been playing osu! on the lazer client for a few months now.
A few days ago I swapped out my CPU (8700k -> 5900x), reinstalled my Windows 10 and ever since that I've been experiencing a big delay between the audio and keystroke.

I tried changing my offset with the offset wizard map, closing my eyes while doing so and the offset seems to be around -80 to -100ms. Although as both the music and the click sounds are delayed, this isn't solving my issue once I play looking at the screen again.

**osu!lazer version:** 

2020.1212.0

**Comment by bdach** [comment]
Not sure what we are to do here to help resolve this without actually owning said hardware... Please attach DirectX diagnostic info by performing the following steps:

1. Press <kbd>Windows</kbd>+<kbd>R</kbd>, type `dxdiag` in the appearing window and press <kbd>Enter</kbd>.
2. You could be prompted if you'd want Windows to check if the device drivers are signed - there should be no harm in agreeing to that.
3. In the *DirectX Diagnostic Tool* window that will appear, click *Save All Information...* and choose a file to save to.
4. Attach the saved file to this issue.

This is in order to collect complete information about your setup, if you're willing to disclose it.

**Comment by atemerino** [comment]
Thank you for the quick response.

Sure, that's no problem, here's the DxDiag file.
[DxDiag.txt](https://github.com/ppy/osu/files/5721466/DxDiag.txt)

**Comment by bdach** [comment]
Just for a bit of sanity checking, I'd recommend trying to update NVIDIA drivers (for the graphics card, which come bundled with an audio driver as far as I can tell), and trying to see whether disabling/disconnecting any of the sound capture devices listed (the blue snowball and the webcam microphone) changes things in any way.

**Comment by peppy** [comment]
Can you take a video showing what you're seeing? And also hit ctrl-f11 and check your fps on each thread.

**Comment by atemerino** [comment]
I updated my Nvidia drivers and downloaded new audio drivers from the motherboard manufacturer's website. The issue seems to be gone now. Sadly I don't know which driver update exactly caused the issue.

Thank you for the help and sorry for the inconvenience!
