### ISSUE TITLE
Function of changing "double time" to "nightcore" in replay mode.

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#11230]
**Describe the new feature:** 
Due to the new aggressive rules regarding the use of music, it often becomes problematic to upload your own replays due to the fact that most people use double time (since nightcore is not always pleasant to listen to). Is it possible to make a mode switch for replays?

**Comment by bdach** [comment]
Just to note, since the issue mentions "aggressive rules regarding the use of music" - if this does happen, it *should not* be interpreted as a way of bypassing any IP protection measures used by youtube, twitch, or other third party services (see #11241). In fact, we may elect *not* to implement that on that basis as [there's precedent of DMCA claims targeted at repositories due to "circumventing" such measures.](https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md)

**Comment by peppy** [comment]
I missed that. This doesn't sound like a valid use case, so let's just close this for now.
