### ISSUE TITLE
Multiplayer chat room should close when you exit the lobby

### ISSUE THREAD

**Issue by Sinamer** [ppy/osu#11299]
**Describe the bug:** The chat stays opened when you leave multiplayer room, and you are able to interact with it.

**Screenshots or videos showing encountered issue:** 
![osu_2020-12-24_23-19-31](https://user-images.githubusercontent.com/53346335/103107193-9bc48480-4644-11eb-9fd4-f631e12385a6.png)

**osu!lazer version:** 2020.1225.0

**Comment by peppy** [comment]
I'm 99% sure this is intended and how it's always been for playlists.

**Comment by Firmatorenio** [comment]
It makes sense for playlists since they're not real-time and stay open when you leave them. I imagine if a room closed or went private after you left it and you could still see its chat, it wouldn't be very nice.

On another note, even if you do keep the room tabs open, it would be nice if the chat focused the room you just joined after you join multiple - opening chat and seeing the focus on an some other tab is quite annoying.

**Comment by Sinamer** [comment]
For the multiplayer, the chat should definitely be closed. That's how it was in stable, and it makes zero sense if it doesn't remove the tab. That breaks the point of actually being there. You should not be able to access the chat room once you leave

The playlists are different, so it makes sense to leave it open, but the use case is unknown to me
