### ISSUE TITLE
osu!lazer wont launch, again!

### ISSUE THREAD

**Issue by Tob7** [ppy/osu#11337]
osu!lazer wont open, when i clicked the shortcut or the .exe, it show up in task manager but just in a second then disappear. event viewer log:
Faulting application name: osu!.exe, version: 0.0.0.0, time stamp: 0x5f1757ad
Faulting module name: ntdll.dll, version: 10.0.19041.662, time stamp: 0x27bfa5f0
Exception code: 0xc0000409
Fault offset: 0x00000000000a12b0
Faulting process id: 0x2af8
Faulting application start time: 0x01d6dcca42fea408
Faulting application path: C:\Users\Admin\AppData\Local\osulazer\app-2020.1225.0\osu!.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: cb998bab-f3b1-41d1-b8da-b105edec895a
Faulting package full name: 
Faulting package-relative application ID: 
I also try to fix the ntdll.dll but it not working

**Comment by peppy** [comment]
Please attach log files, as per the issue template. Please don't delete the issue template. Please fill out the issue template if you are going to submit an issue.

**Comment by Tob7** [comment]
sorry, first time using github, buttttt im kinda find out whats's wrong
just uninstall the intel graphic driver for intel HD and lazer will run smoothly, pls fix tho, intel graphic driver gave me a decent boost of fps

**Comment by peppy** [comment]
You will need to attach lazer logs as per the issue template if you are looking for help.

**Comment by Tob7** [comment]
but i cant find any in %appdata% ._.

**Comment by mouzedrift** [comment]
you should get a small window if you press the <kbd>windows key</kbd> + <kbd>r</kbd>. it should look like this:
![image](https://user-images.githubusercontent.com/43358824/103191504-874aeb00-48d5-11eb-8595-2d57adb91e33.png)
then you just put ``%AppData%/osu/logs`` inside the field and click on ``ok``. a new window should've opened now with the osu lazer logs so you can just drag and drop them here to upload them.

**Comment by bdach** [comment]
I would recommend checking for updates of the intel driver instead of uninstalling completely.

If the game launches, there should be logs. But if there are none in the case of a crash, please attach Windows Event Viewer info by performing the following steps:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by Tob7** [comment]
> I would recommend checking for updates of the intel driver instead of uninstalling completely.
> 
> If the game launches, there should be logs. But if there are none in the case of a crash, please attach Windows Event Viewer info by performing the following steps:
> 
> 1. Type `Event viewer` in the Windows search bar (shortcut: Windows+S) and press Enter, or open the _Run..._ button (Windows+R), type in `eventvwr` and press Enter.
> 2. The _Event viewer_ window will appear. Expand _Windows Logs_ on the left and choose _Application_. It might take a while to load.
> 3. In the _Actions_ pane on the right click _Save All Events As..._, then choose a location to save to.
> 4. On the _Display Information_ popup, select the second option, then the checkbox to show all available languages, then _English (UK)_ (US would also do fine).
> 5. Append the resulting `.evtx` file to this issue.

u mean, all?

**Comment by Joehuu** [comment]
> u mean, all?

Yes. Also if this is a graphics driver problem, please post the directx information text file as described in https://www.howtogeek.com/258485/how-to-use-the-directx-diagnostic-in-windows/.

**Comment by bdach** [comment]
Closing due to lack of response; will re-open if requested information is provided.
