### ISSUE TITLE
No sound at all on Linux

### ISSUE THREAD

**Issue by nahuelwexd** [ppy/osu#11431]
**Describe the bug:** 
There's no sound at all on my Fedora 33 (Silverblue), and osu!lazer complains about a driver: "BASS faulted with error code 3: Driver". The second notif on the screenshot is related to #9874

**Screenshots or videos showing encountered issue:**
![image](https://user-images.githubusercontent.com/18204745/103716425-c64a0200-4fa1-11eb-9f28-e41b929770c1.png)

**osu!lazer version:**
osu!lazer 2020.1229.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/5773346/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5773347/runtime.log)
[database.log](https://github.com/ppy/osu/files/5773348/database.log)
[network.log](https://github.com/ppy/osu/files/5773349/network.log)

**Comment by peppy** [comment]
Have you installed the suggested package? This is a critical failure with your system configuration, not our end. It means that your sound devices cannot be found by the game. Closing thread as off-topic, but feel free to reply with any further information you find / require.

**Comment by nahuelwexd** [comment]
As I said, the 2nd notification is related to the AppImage package, and that issue was already reported here. I had that notification since the first time that I opened osu!lazer on my system, and the sound was working.

Now I have the first notification too, and the sound is not working anymore

**Comment by peppy** [comment]
This does not change the answer from our end: it's saying your driver is broken. This is a misconfiguration at your system level.

**Comment by Vrabor** [comment]
After a System Update I got the same error today: Bass faulted with error code 3: Driver  
For me this was an issue with ALSA configuration and i got it working again  
Steps to take:
- Step 1: try running osu in the terminal: the error i got there was: `ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave`, in my case the error occurred because ALSA selected the wrong playback-device
- NOTE: this error can also occur if sound is working fine in every other Application, that is because you are probably using a different audio library for those (e.g. pulseaudio, pipewire), it was the same for me
- Step 2: Find out what audio-device is selected in alsa: use `aplay -l` or query `/proc/asound/cards`, the default device usually has index 0
- Step 3: change the default / currently selected audio device: there are probably a million different ways to do this, i'll just tell you the way i did it (please refer to the alsa documentation if this doesn't work for you):
   -  check if the file `/etc/asound.conf` exists and create it if it's missing (it didn't exist for me)
   - add the following lines `defaults.pcm.card 1` and `defaults.ctl.card 1` where 1 is the index of your output device, replace it with the index that's appropriate for your system

Hope this helps anyone
