### ISSUE TITLE
Sometimes when selecting a map, the filter is ignored.

### ISSUE THREAD

**Issue by kkartaltepe** [ppy/osu#11456]
**Describe the bug:** 
Sometimes when selecting a map set, the filter is ignored. Im not sure if its related but my songs are on a fairly slow network drive so there can be a noticeable hiccup when selecting map sets which may contribute to triggering the bug.

The unfiltered mapset remains unfiltered when selecting another mapset and then selecting it again. It gets filtered correctly if I retype the filter.

This happens pretty consistently once an session (30m to an hour) usually within the first few plays, and I cannot remember it happening a second time for the same filter but it has happened again when using a different filter.

**Screenshots or videos showing encountered issue:** 
Example of stars>5 showing maps with stars less than 5
![](https://i.imgur.com/OoJDvCc.png)

**osu!lazer version:** 
2021.109.0

**Logs:**
Bug template references, `~/.local/share/osu/logs` but these logs havnt been modified for months. Is this still the correct path?

**Comment by Joehuu** [comment]
You may be clicking the difficulty icons (which will filter the set to show all diffs).

![u91WXvhwm4](https://user-images.githubusercontent.com/35318437/104142683-6ffa0c00-5371-11eb-93f8-ba3aaa8707a3.gif)

It is intentional behavior (for now). We're been seeing a bit of UX problem reports like these (e.g. ruleset changing when clicking another ruleset's diff) and yeah, I'm leaning against this behavior too.

**Comment by kkartaltepe** [comment]
Ahh you are definitely right, I was considering also mentioning changing rulesets randomly as well. But that sounds like exactly what you describe.
