### ISSUE TITLE
RulesetInfo unique constraint failure

### ISSUE THREAD

**Issue by OrangeSniper** [ppy/osu#11451]
**Describe the new feature:** 
I would love to see an area where people can help with errors and problems with rulesets and their general design too.
**Proposal designs of the feature:** 
maybe a dedicated official discord for rulesets or a place in the website forums

**Comment by bdach** [comment]
I'm not sure what "errors and problems" this is referring to in particular.

If you're having trouble navigating the ruleset API then you are free to ask questions at the osu!dev discord. Note, however, that we don't really have the capacity to walk you through the entire process step by step.

**Comment by OrangeSniper** [comment]
wait, there's a ruleset API? I had no idea

**Comment by bdach** [comment]
Not in the "web" sense of the word. I mean the general C# interface and mechanisms of how to write a custom ruleset.

**Comment by OrangeSniper** [comment]
Ah, that has not helped me in the slightest. I am having a strange problem that I have researched and it hasn't helped.`SqliteException: SQLite Error 19: 'UNIQUE constraint failed: RulesetInfo.ShortName'.` is the error code, I have tried changing the shortname, even to gibberish and it still gives me the error. It was working fine originally and just stopped...

**Comment by bdach** [comment]
It would have been much easier if you reported this as a normal issue instead of starting off with a nebulous question about a "support group".

This will likely be fallout from the recent obsoletion cleanups in https://github.com/ppy/osu/pull/11436. Please upload your `client.db` file.

**Comment by OrangeSniper** [comment]
I had to zip it up, here you go. thanks and I'm sorry.
[client is in here.zip](https://github.com/ppy/osu/files/5791156/client.is.in.here.zip)

**Comment by bdach** [comment]
I'm very confused by this database file. The only ruleset present in it is:

```
osu.Game.Rulesets.swipe.swipeRuleset, osu.Game.Rulesets.swipe, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
```

and, it has a database ID of 1 to boot, which should be reserved for taiko.

I need more information regarding the circumstances of how this might have happened. Is this your first install of the game? Is "swipe" something you've installed, or are developing?

**Comment by OrangeSniper** [comment]
swipe is what I'm developing. when I open Osu with Vs, it's the only gamemode that pops up, before it started not working.

**Comment by bdach** [comment]
On checking, you're using [an ancient version of the `osu.Game` package](https://github.com/OrangeSniper/swipe/blob/f8f8bad368d45396c02f582820def46225977b0a/osu.Game.Rulesets.swipe/osu.Game.Rulesets.swipe.csproj#L13), which doesn't have the fix for https://github.com/ppy/osu/issues/8936, which I believe should be likely to fix your problem.

Please try upgrading the package and seeing if it fixes.

**Comment by OrangeSniper** [comment]
I updated the package and it caused tons of errors in my code, most likely from fixes that aren't reflected in my code. at least it's updated

**Comment by bdach** [comment]
The minimal set of changes to get the templates up to speed is over [here](https://github.com/ppy/osu-templates/pull/32), if you'd like to give manually upgrading a go. Otherwise it might be best to wait for the next release of the template and reinit the project - but I don't think manual upgrade should be too much work.
