### ISSUE TITLE
osu!lazer won't launch anymore

### ISSUE THREAD

**Issue by Aer-Haed** [ppy/osu#11504]
**Describe the crash:** 
When starting osu!lazer the cursor will turn into a loading sign and the program appears in task manager for a few seconds disappering shortly after. After that nothing happens anymore.
osu!lazer worked fine before. 
I am unaware of any changes on my side 
Reinstalling didn't change anything.
 osu stable does still work

I looked through other issues but couldn't find a solution. If I just overlooked one i apologize.

**osu!lazer version:** 
2021.109.0.0

**Logs:**
- %AppData%/osu/logs:
[database.log](https://github.com/ppy/osu/files/5821886/database.log)
[performance.log](https://github.com/ppy/osu/files/5821887/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5821888/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5821889/updater.log)
I can't find anything in the event viewer (not that tech savvy though)

**Computer Specifications:** 
OS: Windows 10 Home, 64 bit (ver 20H2)
CPU: Intel Core i5-7500 CPU @ 3.40GHz, 4 cores
GPU: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
RAM: 8GB DDR4

**Comment by bdach** [comment]
Known issue, reported multiple times: https://github.com/ppy/osu/search?q=foreign+key+constraint+failed+is%3Aissue&type=Issues

The current workaround is to delete `client.db`, if you're not too attached to it. There are efforts in progress on swapping out the current database system for realm so that this doesn't happen going forward.
