### ISSUE TITLE
Multiplayer nullref when pressing escape

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#11511]
**Describe the crash:** Pressing the <kbd>ESC</kbd> key during the transition between song selection and match settings causes the game to return a `System.NullReferenceException`.

If you keep pressing any key with the notifications overlay open, the game may return other errors and may crash with an `NUnit.Framework.AssertionException` (not shown in the video).

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43073074/104812118-630d6a80-5800-11eb-81ed-9de98ad860f4.mp4

**osu!lazer version:** 2021.109.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5824375/runtime.log)

**Comment by bdach** [comment]
This is actually [a framework-side assertion](https://github.com/ppy/osu-framework/blob/c38021e6250bff4cd542308f854a242a2af0fe6f/osu.Framework/Input/Bindings/KeyBindingContainer.cs#L276) and not overly relevant to multiplayer itself seemingly.

Possibly related to screen logic (i.e. consider a `KeyBindingContainer` that didn't receive the press because it wasn't the active screen, but received a release when it was visible, tripping the assertion).

**Comment by peppy** [comment]
i *think* there's a framework issue tracking this... or maybe it was tracking another cases of this which was already fixed.

**Comment by smoogipoo** [comment]
This one's actually not the framework assertion, it's just a nullref.

**Comment by frenzibyte** [comment]
To clarify, this issue originally covers two encountered exception, first is the null reference exception at `OnBackButton`, and second is the framework assertion in `handleNewReleased`.
