### ISSUE TITLE
No osu!stable installation found

### ISSUE THREAD

**Issue by squeezel1** [ppy/osu#11534]
As i described previously in #11532, I wasn't able to import anything because no stable installation was found and one reason for that was that I had my Songs folder on another path (#3763/#1907) so I moved it back to D:\osu!. Despite that, i still can't import anything. I included my logs to see if there was something wrong.

osu!lazer version: 2021.118.1

Logs:
[runtime.log](https://github.com/ppy/osu/files/5831479/runtime.log)
[session.log](https://github.com/ppy/osu/files/5831480/session.log)
[update_success.log](https://github.com/ppy/osu/files/5831481/update_success.log)

**Comment by peppy** [comment]
These are not lazer logs. This is not a tech support forum. Sorry.

**Comment by squeezel1** [comment]
Sorry, these should be the correct ones if i'm not completely mistaken.
[database.log](https://github.com/ppy/osu/files/5831520/database.log)
[network.log](https://github.com/ppy/osu/files/5831521/network.log)
[performance.log](https://github.com/ppy/osu/files/5831522/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5831523/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5831524/updater.log)
Not sure which ones are important

**Comment by bdach** [comment]
There is no trace of an attempt to import maps from stable in the attached log. You might have accidentally attached logs from a fresher run of the game.

Nevertheless usually if the import fails on the normal path, it's because of a lack of [the appropriate registry keys](https://github.com/ppy/osu/issues/4043#issuecomment-454245630), which I believe can be restored manually - if you denied the game UAC permissions originally - by using the "Repair folder permission" button in stable.
