### ISSUE TITLE
In-game selection of APIs for replays and score servers

### ISSUE THREAD

**Issue by resolritter** [ppy/osu#11592]
# Motivation

Give users the ability to see scores and replays from multiple APIs instead of only the official one. Of course, it'd be needed to decide on an open specification for those APIs and, accordingly, version the specification.

This is valuable for allowing users to still access their scores and replays without relying on the official osu! infrastructure (e.g. a third-party community-hosted server) even in the event that it gets removed from the main server for whatever reason.

It would be a use-at-your-own-risk feature. It should probably not be exposed by default and have a disclaimers that the creators of osu! are not liable for any damage or negative side-effect that might occur from using those other APIs.

# Input

The listing endpoint would receive two parameters

- The mapper's username **at the time they submitted the map**
- Map Title

Map Title is usually the song title. It's used instead of a more direct identifier (e.g. a numeric ID) for the sake of having the spec be implemented without relying on the official osu! servers' identification for the entity.

# Response

Although mappers might have multiple maps for the same title, it would possible to differentiate them by the submission date. Therefore, the response would be a dictionary with the submission date as keys, where each value is an array of the following object:

```
{
   score_algorithm_version,
   replay_download_url,
   score,
   accuracy
}
```

# Final notes

This post is supposed to be the in-depth, fully-realized proposal; for instance, many fields might be missing from the Input or Response. I'm putting it here to get an impression for how open you are to the idea. I'd be interested in working on the API spec and implementation if the green light is given.

**Comment by bdach** [comment]
I don't think this is happening. You're outlining an enormous amount of work, adding a lot of rigidity to the infrastructure (any change now breaks potentially however many "community servers"), and the only apparent justification of it is "something might be deleted for whatever reason".

Which sounds shady, if I'm honest with you. Also I don't think the argument of "we disavow anything that happens on these servers" will fly if the option is even available there at all.

All of the infrastructure lazer relies on is open source. I would know since I had a setup with a web instance and multiplayer server running on a local machine. So I don't think any of this is even needed.

**Comment by peppy** [comment]
We may add server selection support via some means in the future, but it definitely will not include the scope mentioned here (would be a hard switch, not attempting to merge multiple data sources or whatever is hoped for).
