### ISSUE TITLE
Getting osu! files (osz, osr, etc) to import to both osu!stable and osu!lazer

### ISSUE THREAD

**Issue by AstroOrbis** [ppy/osu#11628]
this is (a) not currently possible automatically because stable and lazer storage structures are incompatible, (b) not the topic of this issue thread. if you want to sync, then symlinking stable song storage to `~/.osu` as mentioned above, and periodic full reimports are the best that can be done.

locking as off-topic. feel free to reopen your wishes as a separate issue but i wouldn't hold my breath that this will happen as it's a low-priority item that is difficult to get right and we don't have the bandwidth to do that instead of actually bringing lazer up to par with stable.

_Originally posted by @bdach in https://github.com/ppy/osu/issues/3763#issuecomment-769917951_

**Comment by bdach** [comment]
there was an attempt to achieve this via a filesystem hard link before (https://github.com/ppy/osu/pull/9191), but that was complicated enough already. there's also the matter of nearly doubling storage requirements if actual lazer and stable copies of files are to be maintained.

rolling back lazer storage to stable format is not an option, therefore i don't think we should be putting time into this, and should rather be pushing to get the game complete so that this isn't really ever required anymore.

**Comment by peppy** [comment]
this is out of scope.

**Comment by AstroOrbis** [comment]
Oh, ok. Just a few questions (sorry if I didn't see an issue with this question link me to that if there is one): is there an ETA for either lazer to be merged to stable or for laser scores to update? Will badges also update through lazer?

**Comment by peppy** [comment]
please google for either my blog or a recent three hour interview i did for general discussion. this is not the place.
