### ISSUE TITLE
Joining a multiplayer room crashes the game

### ISSUE THREAD

**Issue by elweojus** [ppy/osu#11686]
**Describe the crash:** 
Osu crashes when joining a room in singlethread, also it gives an error using multithreaded
(seems that the crash happens in specific rooms)

**osu!lazer version:** 
2021.205.1

**Logs**
[runtime.log](https://github.com/ppy/osu/files/5933554/runtime.log)

**Comment by peppy** [comment]
This looks to be what will happen if you join a room created by an old version. We're semi-aware of this.

**Comment by peppy** [comment]
Just going to close this one for now. It should be resolved when other users update their client versions.

We strive not to create this kind of breakage but due to the (relatively) low usage of the multiplayer feature it was deemed as okay this time around.

For a path forward, we need some kind of version checking to be performed on game creation. Currently this is only checked on score token request, which is too late to prevent previous versions from causing issues.
