### ISSUE TITLE
Set custom mirror server to download beatmaps

### ISSUE THREAD

**Issue by poly000** [ppy/osu#11781]

**Comment by peppy** [comment]
Sorry but this is out of scope.

**Comment by poly000** [comment]
> Sorry but this is out of scope.

I mean to use the mirror server directly in osu! direct...

**Comment by bdach** [comment]
This has been requested several times before and was also deemed out of scope. Further discussion is not necessary.

Please fill out the issue template next time too, by the way. It's not there just so you can remove it entirely.

**Comment by peppy** [comment]
To add to the reasoning for this: we cannot guarantee the reliability of third party providers without a good API surrounding it. For the game client, where it is critical that the beatmap being downloaded is the correct (and up-to-date) version, I'd rather not take on the overhead of support issues we will deal with by adding this kind of functionality.

We *do* accept mirror applications using the official API though. So you may want to contact the mirror provider and see if they are willing to offer the mirror as an official one, rather than a third party service.
