### ISSUE TITLE
Latest android build is on debug

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#11839]
Refs: https://discord.com/channels/188630481301012481/188630652340404224/812340284402827324 and https://osu.ppy.sh/comments/1468730

**Screenshots or videos showing encountered issue:** 
![Screenshot_20210219-143732](https://user-images.githubusercontent.com/35318437/108569083-22ea4d80-72c0-11eb-8c60-6acead8a519d.png)

**osu!lazer version:** 2021.219.0

**Comment by peppy** [comment]
I've checked the build logs and everything is set to release. Nothing has changed anywhere which should have caused this.

I'm lost for words. Will stop publishing android releases until someone figures out what happened here.

**Comment by LeNitrous** [comment]
Still on debug as of 2021.220.0.

**Comment by bdach** [comment]
After a long while of waiting for a few android builds, looks quite clear that the offending commit shall be https://github.com/ppy/osu/pull/11544/commits/72b2123500f28257f140f6fc5f443e85973f99cf:

30a9a09492b6aa42ee88b04a8a003744a32b596c:

```
2021-02-20 15:03:27 [verbose]: entry assembly is nunit.framework, Version=3.12.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb
2021-02-20 15:03:27 [verbose]: debugging flags = IgnoreSymbolStoreSequencePoints
```

master:

```
2021-02-20 13:58:05 [verbose]: entry assembly is nunit.framework, Version=3.13.1.0, Culture=neutral, PublicKeyToken=2638cd05610744eb
2021-02-20 13:58:05 [verbose]: debugging flags = Default, IgnoreSymbolStoreSequencePoints, EnableEditAndContinue, DisableOptimizations
```

Not sure how to deal with this yet. The framework-side check [queries two assemblies](https://github.com/ppy/osu-framework/blob/105a17bc99cad251fa730b54c615d2b0d9a409d3/osu.Framework/Development/DebugUtils.cs#L39) - its own, and the entry assembly, but the fact that nunit is even *considered* as the entry assembly seems flat out wrong. Maybe it should be the calling assembly, instead?

**Comment by frenzibyte** [comment]
The framework still looks to fall back to the calling assembly if the entry is null, which to my knowledge should be the case for android:
https://github.com/ppy/osu-framework/blob/e0877db88ea71fc4527dea1b806eb82e9405b54b/osu.Framework/Development/DebugUtils.cs#L56-L62

Since you mentioned about `IsNUnitRunning` being true for android in discord, I've realized that property actually returns true if `Assembly.GetEntryAssembly() == null`:
https://github.com/ppy/osu-framework/blob/105a17bc99cad251fa730b54c615d2b0d9a409d3/osu.Framework/Development/DebugUtils.cs#L17-L25

Which would explain why `IsNUnitRunning` returns true for android, and why `DebugUtils.GetEntryAssembly()` returns the nunit assembly. That probably needs fixing as well.

**Comment by bdach** [comment]
well, yes. the things you've stated are rather obvious.

**Comment by Peinn94** [comment]
> Still on debug as of 2021.220.0.
> 
> ![image](https://user-images.githubusercontent.com/20495991/108594860-607dd200-73b7-11eb-92ed-e779293c882c.png)

where is the download link, usually the name is "sh.ppy.osulazer.apk" but now i can't find it

**Comment by peppy** [comment]
![image](https://user-images.githubusercontent.com/191335/108613795-99aa5680-7438-11eb-82bf-8242df618b97.png)
