### ISSUE TITLE
Some hitsounds stop abruptly during game play / replay

### ISSUE THREAD

**Issue by Contextualist** [ppy/osu#11845]
**Describe the bug:** During game play ~~(not seen in replay)~~ *or replay*, occasionally (a few times in a play) a hitsound stops abruptly and produces a glitch sound. It is hard to determine the specific type of notes or maps that triggers the glitch. This is first observed in version 2021.219.0.

**Screenshots or videos showing encountered issue:**

https://user-images.githubusercontent.com/16000021/108585121-9453eb80-7314-11eb-8f25-40aded6de4db.mp4

I concatenate three instances (at about 3s, 7s, 13s) of the glitch in this video. There is an extensive lagging in the recordings, but my actual game play is fine.

**osu!lazer version:** 2021.219.0

**Logs:**
[logs.tar.gz](https://github.com/ppy/osu/files/6014199/logs.tar.gz)

**Comment by peppy** [comment]
Very weird. Sounds like a regression from the recent sample refactor we did, but not quite sure how this could have occurred as a result of that. We've previously seen this kind of artifacting when playing the same channel while it is already playing (rather than instantiating a new instance), but the refactor should have made this *less* likely, not more.

**Comment by peppy** [comment]
@Contextualist can you confirm this is still happening? Also can you confirm it only happens during gameplay and not anywhere at the menus?

**Comment by Contextualist** [comment]
> can you confirm this is still happening?

Yes (as in 2021.302.0)

> Also can you confirm it only happens during gameplay and not anywhere at the menus?

This actually happens at the menus, too. (so not only hitsounds)

> Also, could you please check whether you can reproduce it on a beatmap with slower hitobjects (try disco prince), and whether you can reproduce with only hitcircles (no sliders).

I played that map twice and did not notice any occurrence. I then tried DT twice, and found one instance with hitcircle.

**Comment by peppy** [comment]
This is sounding more like an operating system / audio subsystem issue now. Can you confirm your operating system and... if you are on linux how much you've customised audio settings which could lead to breakage like this?

**Comment by peppy** [comment]
Thanks. Just for confirmation, that's Ear pods not Air pods right?

**Comment by Contextualist** [comment]
Right, it is the wired (not wireless) one.

**Comment by Contextualist** [comment]
This issue seems to go away with **`multithreaded` mode enabled**!

Long time ago I had `single thread` mode on due to a reason I don't recall and keep using it until today, when I feel some visual lagging in gameplay and decide to try changing some settings. `multithreaded` mode seems to fix both the visual lagging as well as the audio problem (as for version 2021.302.0).

Will we phase out `single thread` mode one day? Is there any caveat with `multithreaded` mode?

**Comment by peppy** [comment]
Single threaded was implemented for mobile platforms, where it actually can provide lower latency (due to the threading / input model) and lower power consumption. It will always exist but multi-threaded will also be the default on PC platforms.

**Comment by X9VoiD** [comment]
Can reproduce this exact same issue on Windows 10 20H1 when running on single-threaded mode.

The glitch sounds seem to be due to the whole sound getting played back in just a single moment.

**Comment by peppy** [comment]
I can't seem to repro on macOS or windows using single threaded, unfortunately, so it's likely going to be something more configuration specific.

**Comment by X9VoiD** [comment]
The hitsound issue happens on all of the skins that I currently have, including both osu!lazer and osu!classic skins.

On my system I have [Equalizer APO](https://sourceforge.net/projects/equalizerapo/) to neutralize my headphone's peaks, so I tried doing these tests (with restart in between):

| Installed | Enabled | Result |
| --- | --- | --- |
| Yes | Yes | Bad |
| Yes | No | Bad |
| No | No | Bad |

The issue is still present on all possible configurations for Equalizer APO. I also got to trigger the hitsound issue on [Disco Prince](https://osu.ppy.sh/beatmapsets/1#osu/75) without DT, but only ever happened once during my 5 runs on the map.

The same cannot be said however with [Sagashi Mono (BMS Edit)](https://osu.ppy.sh/beatmapsets/177187#osu/426550) where all of the hitsounds were played correctly in 5 runs.

The hitsound bug happens on [Freedom Dive](https://osu.ppy.sh/beatmapsets/147210#osu/1180753), [Reign of Fear](https://osu.ppy.sh/beatmapsets/347136#osu/799415), and  just as much as it happens to typical 5* farm maps (~0.7 hitsound bugs per minute). But 3* maps and below either follows the same rate, or it happens very rarely like in [Disco Prince](https://osu.ppy.sh/beatmapsets/1#osu/75) or [Zettai Tokken](https://osu.ppy.sh/beatmapsets/546878#osu/1195098).
> All tested for 5 runs

I'd say that there is a negative correlation with hitsound length and the probability that the hitsound bug happens. I also have a relatively weak CPU (i5-3230M) but other than these I have no clue anymore.

**Comment by peppy** [comment]
In order to come to a resolution here, we're going to need someone with developer skills to reproduce this and use some trial and error or deduction to figure out what is going wrong. Going to drop out of the milestone because there's no feasible way to reach a solution as it stands.

Recommendation would be to use multi-threaded mode for the time being, if that resolves the issue for you.
