### ISSUE TITLE
vowel bug

### ISSUE THREAD

**Issue by Zsampier879** [ppy/osu#11858]
hi! i called my friend on discord (he not answered) while i open osu lazer, and the vowels are missing or darker, but just when i am alone in the call (so its not outgoing anymore cuz my friend not answered) and its in the menu and the map select

**Comment by frenzibyte** [comment]
Haven't you read what's said in https://github.com/ppy/osu/issues/11850#issuecomment-782690459..? Follow issue template, attach screenshots, attach logs. How can we help you otherwise, I can't understand what you're talking about, screenshots 100% explain better.

Please read the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue) as well. Closing due to not following issue template.

**Comment by bdach** [comment]
This is the last warning. If you continue to ignore our requests, then we will look into restricting you from submitting issue reports at all.
