### ISSUE TITLE
Error when importing a beatmap from 'beatmap listing' in osu!lazer  

### ISSUE THREAD

**Issue by Modsnotworking** [ppy/osu#11869]
I had this bug when I imported a beatmap from osu!lazer in beatmap listing, here's the screenshot

![osu_2021-02-22_12-15-52](https://user-images.githubusercontent.com/70589304/108672444-135d4580-7508-11eb-8b8c-9125c5d39fce.jpg)

osu!lazer version: **2021.220.0**

Here is the log file(s): 
[logs.zip](https://github.com/ppy/osu/files/6019987/logs.zip)

**Comment by smoogipoo** [comment]
Seems like the download failed because of your network connection. There's nothing we can do here - are you able to reproduce this?

**Comment by Modsnotworking** [comment]
> Seems like the download failed because of your network connection. There's nothing we can do here - are you able to reproduce this?

sorry, I didn't understood by 'are you able to reproduce this?'
and yes I was having a bad slow internet connection, so it seems that it isn't a bug?

**Comment by smoogipoo** [comment]
Has this happened multiple times?

The only thing I can see that's questionable is that the request isn't being retried, meaning it's dying mid-response after having received some data. But I'm not sure that should be retried in the first place as it means more data usage on slow connections. Thoughts @peppy ?

**Comment by peppy** [comment]
We probably need to be more lenient on the timeouts for long-running requests. The shorter timeouts we have in places are generally intended for "real-time" requests where the user is expecting a response within 10-20seconds, but for downloads we can likely set the timeout to more like 60s. If not on the whole request itself, it should maybe be increased on the reads for data (after the initial connection is already established).

I think this raises the question of whether we should be setting custom timeouts at a framework `WebRequest` level in the first place, instead of using those provided by .NET. Maybe the custom timeout should be left to osu! / `APIAccess` to impose?

**Comment by smoogipoo** [comment]
As it turns out, my assertion above was incorrect. `APIRequest` always has retries disabled. Doesn't change anything in your comment though.

**Comment by peppy** [comment]
Ah, that's a thing as well isn't it. A good first step is probably to increase the timeout on beatmap download requests (and open an issue tracking the proposed larger change at a framework side). Adding retry support probably won't gain much because in cases like this report, the same timeouts will likely happen after retry.

**Comment by Modsnotworking** [comment]
> Ah, that's a thing as well isn't it. A good first step is probably to increase the timeout on beatmap download requests (and open an issue tracking the proposed larger change at a framework side). Adding retry support probably won't gain much because in cases like this report, the same timeouts will likely happen after retry.

so does it means that this issue is ready to be closed?

**Comment by peppy** [comment]
It's fine to leave it open. We will be making some changes to improve your situation.

**Comment by Modsnotworking** [comment]
> It's fine to leave it open. We will be making some changes to improve your situation.

ok, I'll let this issue be open
