### ISSUE TITLE
osu!lazer crashes while loading if a Custom Ruleset on iOS

### ISSUE THREAD

**Issue by GiraffeMan3125** [ppy/osu#11861]
**Describe the crash:** 
On my iPhone, I found the `rulesets` folder in osu! (When I plugged it into Finder) and I thought I might be able to put Custom Rulesets in it to play them, but then I open the app, the osu!lazer app crashes.
**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/30411273/108639714-e2c3d000-7463-11eb-98c3-3b6548aa1139.mp4

**osu!lazer version:** 
It just says "local release", but I got it from https://www.reddit.com/r/osugame/comments/jb3yp5/i_compiled_an_ipa_of_osulazer/

**Logs:**
[Logs.zip](https://github.com/ppy/osu/files/6018640/Logs.zip)

**Phone Specifications:** 
iPhone SE 2020, iOS 14.5

**Comment by jai-x** [comment]
At the moment, mobile builds are currently halted due to build tooling reasons.

I don't believe custom rulesets are currently supported on mobile versions.
Additionally, your log files don't seem to have any actionable information.

The IPA you are using is not an official build and is many months old so I don't think we can support issues for it.

Please wait until official builds for mobile become available again. They will be found here: https://github.com/ppy/osu/releases/latest

**Comment by peppy** [comment]
also note that loading rulesets can not be supported on iOS at an OS level.

it will only ever work for those approved and distributed by us.
