### ISSUE TITLE
Creating a collection with a name that already exists causes ArgumentException

### ISSUE THREAD

**Issue by rednir** [ppy/osu#11876]
**Describe the bug:**
You can create multiple collections in the manage collections menu with the same name, causing an unhandled error to be shown (and sometimes even crash the game). 
This also causes the same error to show every time you enter song select.
It also happens if you try to import collections from stable twice.

**osu!lazer version:** 2021.220.0

**Logs:**
Log from a crash: [runtime.log](https://github.com/ppy/osu/files/6024668/runtime.log)

**Comment by peppy** [comment]
@smoogipoo i've started working on a solution to fix this for the user interactive case. need a bit of direction here. what i've done so far (see https://github.com/ppy/osu/compare/master...peppy:fix-collections-name-collisions?expand=1) is:

- Protect the `CollectionManager.Add` flow and perform the automatic "merging" on duplicate collection name
- Change the textbox to not immediately update the collection name, in a hope of adding a validation flow.

This falls apart for multiple reasons:

- `CollectionManager` currently handles `onChange` events to perform background saves, which don't really define what has changed. Feels a bit flimsy, so..
- The flow I was hoping to achieve is having `CollectionManager` bind to `Name.ValueChanged` and if a duplicate name is found, it would set `Name.Value = name.OldValue` to avoid the collision. This turns out to be quite hard to setup due to `ValueChanged` not having a `sender` parameter (meaning unbinding in `CollectionManager` is not feasible, without maintaining a dictionary of bound bindables or something).

Do we have some existing flow which gets around this somehow? Any better suggestions?

**Comment by peppy** [comment]
Another options being to make the `Name` a non-bindable and require a `Remove` then `Add` when renaming collections, which may turn out to be simpler to implement.

**Comment by peppy** [comment]
Another option is to *allow* duplicate collection names, and change the dropdown which is causing the crashes to handle this situation (might be the simplest method of all?). I'm going to try this one initially.
