### ISSUE TITLE
"Favourite/Unfavorite this beatmapset" tooltip box has a lighter color

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#11974]
**Describe the bug:** As title. If I remember correctly, the tooltip box should have this light color only during the transition between two tooltips (e.g. when hovering between mods).

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43073074/110216659-98554100-7eb0-11eb-8fbd-3bfc7061ecf8.mp4

<hr>

Here's a comparison:

![tooltip](https://user-images.githubusercontent.com/43073074/110217076-7492fa80-7eb2-11eb-85e7-77bcc3d28d53.png)

<hr>

The only thing that seemed strange to me is that tooltips without this problem don't have this `Box.Colour` property in the Transform section, while it seems to persist for this tooltip (I'm not sure if it can help in any way):

![transforms](https://user-images.githubusercontent.com/43073074/110216552-fc2b3a00-7eaf-11eb-9737-baeaf7069acb.png)

**osu!lazer version:** `2021.302.0` (latest), it seems to happen since version [`2021.226.0`](https://github.com/ppy/osu/releases/tag/2021.226.0)

**Comment by bdach** [comment]
This is an actual regression from the localisation changes. And a pretty shocking one, at that. In short, this check fails:

https://github.com/ppy/osu/blob/b24174911908fb6c7a640d1ac56689cd3d4bb8d7/osu.Game/Graphics/Cursor/OsuTooltipContainer.cs#L38

The LHS is a `string`. The RHS is a `LocalisableString`. Because of this, an implicit conversion happens, which is fine. What is *not* fine is [this `Equals()` implementation](https://github.com/ppy/osu-framework/blob/7ef604b494e3b4601cb18ae2478008fa0a5feba2/osu.Framework/Localisation/LocalisableString.cs#L25)... again. Because

```csharp
((object)"s1") == ((object)"s1") // is FALSE
```

we essentially have

```
new LocalisableString("s1") == new LocalisableString("s1") // is FALSE
```

I'm not entirely sure whether to call it a framework bug or not. It *feels* like one, but I'm not sure what `LocalisableString.Equals()` should even *be* given that it can be three disparate things (so 9 combinations in total to handle). A local `.ToString()` will also fix this. But I'm afraid as long as the implicit conversion is this gotchas like these will continue to happen.

**Comment by frenzibyte** [comment]
Yeah there are `string == LocalisableString` cases existing throughout the game, so probably worth fixing framework-side.

**Comment by bdach** [comment]
Got any actual proposals on how to fix it? Just saying that it's "probably worth fixing" isn't very helpful.

Honestly I'd probably go the nuclear route and straight up delete `operator ==`. It practically never does anything sane. But I'd like actual discussion with actual proposals to happen first.

**Comment by frenzibyte** [comment]
Yeah no, just pointed out something at that last fix you stated. I would agree with removing the operator altogether as it sounds safest, but nothing comes to my mind otherwise.

**Comment by peppy** [comment]
Definitely requires *something* to change at the framework side. This should not be a silent failure.
