### ISSUE TITLE
BASS Error?

### ISSUE THREAD

**Issue by AverytheFurry** [ppy/osu#11991]
**Describe the bug:** 
I get an error, "BASS faulted with error code 46: Busy."
**osu!lazer version:** 
2021.302.0-1
**Logs:**
[database.log](https://github.com/ppy/osu/files/6106572/database.log)
[network.log](https://github.com/ppy/osu/files/6106573/network.log)
[performance.log](https://github.com/ppy/osu/files/6106574/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6106575/runtime.log)

**Comment by smoogipoo** [comment]
This is going to be something with your audio setup. Some other application has taken exclusive control of the audio device.

**Comment by AverytheFurry** [comment]
Interesting, I don't have any audio issues, it just keeps throwing that error at me.

**Comment by bdach** [comment]
Does sound work? Try changing the audio device to something else.

**Comment by huupoke12** [comment]
Since BASS only supports ALSA on Linux, this will happen if you let applications access hardware devices directly (which don't support hardware mixing, as most onboard sound cards are). Some reason why this hapens:
* You have a ALSA config that make applications directly use hardware devices. Try editing (or removing if you don't need it) `~/.asoundrc`.
* You make the applications (osu!, Firefox) use the hardware device. Try choosing the "Default" device.
* You are using PulseAudio (most distros are using it by default) or PipeWire, but you don't have the necessary ALSA plugin and configuration to make ALSA-only application able to use the PulseAudio/PipeWire as a device. How you do this depends on your distro. Such as on Arch Linux, you need to install `pulseaudio-alsa` if you are using PulseAudio, `pipewire-alsa` if you are using PipeWire.
