### ISSUE TITLE
Screen Tearing Bug osu!lazer

### ISSUE THREAD

**Issue by LollipopFt** [ppy/osu#11995]
Problem:
screen tearing when playing and watching replays of beatmaps. I am unable to record it on video as it seems that the recorder does not record the screen tearing (Hz too low?)

Logs:
[database.log](https://github.com/ppy/osu/files/6115976/database.log)
[network.log](https://github.com/ppy/osu/files/6115977/network.log)
[performance.log](https://github.com/ppy/osu/files/6115979/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6115980/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6115982/updater.log)

**Comment by bdach** [comment]
What frame limiter options are you on and what framerates are you getting?

The typical advice for screen tearing is to either use vsync, or ensure that your fps is a stable multiple of the display's refresh rate.

**Comment by bdach** [comment]
You still haven't given your *actual* in-game FPS (use the built-in FPS counter under <kbd>Ctrl<kbd>+<kbd>F11</kbd>). Having the limit on 8x does not mean you'll actually be getting 480 FPS draw, especially probably not with an Intel integrated card.

Have you tried the vsync limiter option, or 2x, instead?

**Comment by peppy** [comment]
screen tearing is not something caused by the application. it means you have vsync turned off. there's no way to avoid it without turning vsync (or in more modern usages, gsync/freesync) on.

please look into your GPU settings and force one of the above, preferrably one supported by your monitor. if you believe this is a lazer issue and that it didn't happen to you before now, it probably means you have been playing with it on unknowingly, or running in borderless/windowed mode, where it will be applied automatically by windows.
