### ISSUE TITLE
Scores with higher combo from hold notes and get unexpectedly higher score than higher accuracy plays

### ISSUE THREAD

**Issue by AlexHgC** [ppy/osu#12032]
**Describe the bug:** 

My score on one easy map, i have 3 great and 291 combo because i have released LN too late. ( This is why i have 3 great ). Now, you can see the #1 people score, he have 0 great and 285 combo, because he have released the LN at the right timing, so, no more combo. 

The two scores are played on stable, but as you can see, on lazer, i have more score with 3 greats because i have ONLY 5 more combo... it make no sense.

**osu!lazer version:** 2021.302.0

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/31996023/111486243-9ce2ea80-8737-11eb-973f-b88bba8183cc.png) ![image](https://user-images.githubusercontent.com/31996023/111486273-a409f880-8737-11eb-9446-1114b4dbbed1.png)

**Comment by peppy** [comment]
I'm sure you have good intentions, but the way you phrase this issue is a touch incorrect. We are not aiming to have "one unified score"; in fact the implementation is quite the opposite, allowing each ruleset to choose the combo score weighting it uses.

Also do note that we have not done any kind of balance pass yet, as mentioned in the README.

That said, the issue here seems to be that combo is being counted in a place where it maybe shouldn't be (aka missing combo doesn't actually count as a miss, similar to the weird edge case of "sliderbreaks" in osu! ruleset). Are hold not end judgements in lazer counting a hiddden combo-only value? If so that may be the starting point in resolving this very edge-case discrepancy.

**Comment by AlexHgC** [comment]
I have seen lazer have something called "hold ticks". Is this possible to use something like that for stop have more combo before the start/after the end of LN ?

**Comment by smoogipoo** [comment]
Given that both the above scores are >1M indicating that the score's combo is greater than what lazer thinks is the maximum achievable combo (mania doesn't have bonus), we can probably cap the score's max combo to the beatmap's max combo.

It'll fix this case but the underlying issue remains that stable adds a ton of combo unnecessarily for hold notes and will skew scores. For example, suppose a map has 2000 combo where 1000 of that is artificially inflated but that lazer would determine is only 200 combo (so highest max combo = 1200). In this case it could be possible to get 1000 combo in stable (100% artificially inflated), and for lazer to think that counts as 1000/1200 of the combo portion.

Another way would be to calculate a max combo for mania based on `duration / 100` but it's not going to be exact since osu!stable starts adding combo as soon as possible. For example if the user started holding at -50ms relative to the head, the "tick" combo addition would be at +50ms relative to the head, so it could be 1 or maybe 2 ticks off in some edge cases.

The second solution above is actually probably the easiest to do - it's just that mania's difficulty calculator right now doesn't consider ticks as combo _at all_. Otherwise, I'm not against adding ticks more often (every 100ms) as this has been requested in the past as well.

**Comment by smoogipoo** [comment]
![image](https://user-images.githubusercontent.com/1329837/111580354-b5680900-87fa-11eb-8ee1-94d93fda3c85.png)

This is the closest it can get, with matching stable's calculations a bit better.

**Comment by AlexHgC** [comment]
> ![image](https://user-images.githubusercontent.com/1329837/111580354-b5680900-87fa-11eb-8ee1-94d93fda3c85.png)
> 
> This is the closest it can get, with matching stable's calculations a bit better.

Hanss need to have better score than me, not lower. I have 3 great, je have 0, he need to have 1M, not me, here is the real problem

**Comment by smoogipoo** [comment]
Ah right. That's another issue, the calculation only takes into account combo and accuracy, but MAXs are applied silently to the score without affecting either of those.
