### ISSUE TITLE
Slider sections' curve types don't get automatically upgraded like in osu-stable

### ISSUE THREAD

**Issue by DeviousPanda** [ppy/osu#12049]
after you have created a slider that has at least one red node, adding new nodes doesnt make them white (curved) nodes, just red (angled) nodes (but they still look like white nodes) https://clips.twitch.tv/FitBlushingTruffleNotLikeThis-L4otvDzNukhiO9uu

**Comment by RaiLTC** [comment]
Isn't this intended? Default curve type for newly created nodes is Inherit
[Example](https://puu.sh/HqrhA/ed27382992.mp4)

**Comment by peppy** [comment]
The difference here is that when the user places the first set of points, it's locking each segment into a linear type (because there are no nodes between the two red ones). In lazer, when adding a new node there, it's keeping the linear curve type, while in stable where there's no ability to select the curve per section, it's automatically upgrading it.

I'm not sure the best way of handling this. lazer's way makes more sense if you consider things from a fresh perspective, but it obviously doesn't match user expectations.

**Comment by peppy** [comment]
486

**Comment by j-b-z** [comment]
If the new node created between the red nodes is a linear type, then it should be red as well to properly reflect this nature. Right now, the new node is a yellow node and not a red one and so its pretty visually deceiving.

**Comment by peppy** [comment]
@j-b-z that's not how lazer works though. You can now change the curve type per section. The type in the video is linear. This is new functionality which actually allows a lot more flexibility with sliders that was previously either difficult or impossible.

The best path forward here may be to not set the curve type to linear in this case, and leave it as a "linear" bezier curve.

**Comment by j-b-z** [comment]
Ah I see. Is there anything that a linear section can achieve that just making new curve types can't? Coming from stable it seems as if these linear type nodes are functionally behaving just like red nodes.

**Comment by peppy** [comment]
I guess if you look at it that way, no? Except they are doing the same thing with far lower computational and clicking overhead.

**Comment by j-b-z** [comment]
Feels like mappers and modders lose some visual clarity by this (the stable preconceived notion is that red node -> sharp node and yellow/white node -> curve) but I guess it makes sense if the current red nodes are just more expensive to enable the multiple curve types

**Comment by peppy** [comment]
Might be able to improve things by showing the type of each red node.

**Comment by j-b-z** [comment]
Yeah actually color coding these new nodes would be immensely useful

**Comment by j-b-z** [comment]
Can this turn into a feature request? I think it'd actually be so cool to have inherited nodes be based off of what property its inheriting, since they do control the shape of that slider section.

Something like inhereted:
linear -> pink
perfect -> white
bezier -> yellow
catmull -> green

or colors that other people can agree on

**Comment by peppy** [comment]
Yep, that will likely be the direction. I'll experiment with what works well.
