### ISSUE TITLE
Mappers coming from stable expect key binding brings up a rotate control

### ISSUE THREAD

**Issue by DeviousPanda** [ppy/osu#12045]
currently there are a lot of editor shortcuts that almost all mappers use constantly (such as "ctrl + shift + r" for rotation) but in lazer this shortcut randomises the skin that you are using (even inside the editor)

as mappers have been relying on muscle memory shortcuts to streamline the mapping process for over a decade now, it feels weird to change or overwrite these,

one solution would be to just disable these new lazer shortcuts for *only* the editor and have the stable shortcuts take priority over them, how does this solution sound to you?

(editor section for a bank of all current shortcuts https://osu.ppy.sh/wiki/en/Shortcut_key_reference)

**Comment by bdach** [comment]
I think generally shortcuts, if they happen, aim for parity already (see flip/reverse). I believe it's viable to override the global hotkeys with editor-specific ones. That said some alternative tools might also come to supplement the old ones (for instance for rotation, there is the selection box, which supports drag-rotate now - on the surface that seems like a way better system to me than punching in numbers of degrees, but maybe not after however many years of experience).

**Comment by DeviousPanda** [comment]
> (for instance for rotation, there is the selection box, which supports drag-rotate now - on the surface that seems like a way better system to me than punching in numbers of degrees, but maybe not after however many years of experience).

just for this example, a choice to use the drag rotation and inputting degrees into rotation should be there as a lot of mappers use precise angles to create patterns,

**Comment by LittleEndu** [comment]
If precise angles/scaling are needed, wouldn't an alternative be to display the current rotation/scale somewhere while having it snap to integer values (so 2 times, 3 times, 1/2 times, 1/3 times etc.)

Photoshop for instance shows the current angle in a tooltip next to cursor:
![image](https://user-images.githubusercontent.com/11320483/115992917-cade0900-a5d8-11eb-8926-33dd10cdd2c5.png)

**Comment by bdach** [comment]
@LittleEndu #10396.

**Comment by peppy** [comment]
The order of which bindings are handled is already correct, so the issue here where "random takes priority" is already resolved. I'll rename this issue to track the fact that people expect it to rotate, even though the rotation controls are different in lazer.

**Comment by bdach** [comment]
@AxurlizTTV this issue has to do nothing with either hotkey you mention. this issue is about the rotation control specifically. please open a separate discussion for hotkeys to avoid mixing topics.

**Comment by bdach** [comment]
I attempted to have a go, but am not sure of the result...

https://github.com/ppy/osu/assets/20418176/03d06141-9d16-4982-89b4-8b59a21b81c8

I thought attaching the rotate control to the current selection box would be cool, but unfortunately it turns out to be quite jank, especially when combined with the "playfield centre" mode of operation, as it's susceptible to jumping all over.

I also wanted to have the selection move as the slider is dragged, but with the implementation above, that goes about as well as you'd expect it to...

@ppy/team-client any ideas? maybe we want to have this rotation tool dock on the sidebar where the inspector is or something?

**Comment by frenzibyte** [comment]
Agree with moving it to the sidebar, or potentially as a floating popup either on the bottom or the top of the screen depending on the position of the selection. Having it as a popover next to the selection rectangle feels odd, and would probably get worse when we get to support previewing a rotation of the selection.

**Comment by peppy** [comment]
I think people are going to want hotkey access, so sidebar is not a great choice (unless we make it `ScrollTo` or something?).

Could we make a popover mode where it stays fixed in place, or just manually invoke the popover outside of the standard `PopoverContainer` usage?

**Comment by bdach** [comment]
> I think people are going to want hotkey access, so sidebar is not a great choice (unless we make it `ScrollTo` or something?).

I was thinking it would be something that can be activated via a hotkey, like the slider velocity thing is, yeah. `ScrollTo()` and maybe expand or unhide or something.

> Could we make a popover mode where it stays fixed in place, or just manually invoke the popover outside of the standard `PopoverContainer` usage? Optimal UX for me would be a draggable popover (drag anywhere inside the popover which isn't handling clicks).

That is going to be... nontrivial. Half the point of popover design was that you shouldn't need to care about positioning, you just plop down a container that determines display bounds, then the popover itself, and it just figures the rest out. I'd probably rather roll something local than attempt to cram custom positioning in there.

**Comment by peppy** [comment]
How about a popover that spawns from a button (something like "rotation tool" or "adjust rotation") in the right sidebar? I feel like trying to cram the full rotation controls inside the sidebar is going to be hard, but this could work?

**Comment by bdach** [comment]
Sure, that could work (and could possibly even be extended to support the stable scale popup, too).

I'll experiment around and post videos here or something.

**Comment by bdach** [comment]
Okay, how's this?

https://github.com/ppy/osu/assets/20418176/9c855e96-9418-489a-97b6-14a5556c91aa

Think it's getting there, but I will warn that the video looks better than the actual code does right now, I basically did this as a proof-of-concept as the crow flies, it needs polish still. One of the ways this manifests is this *extremely* funny bug in the way the "selection centre" toggle """works""":

https://github.com/ppy/osu/assets/20418176/23eccb34-3e0d-4273-a967-e34463c31282

which as funny it is to see the slider just _launch_ into space, it's obviously not shippable. (TL;DR: floating point error accumulation because I'm undoing previous rotations on every touch of the slider and applying them anew).

And also in general the structure is kinda wonky right now, because thus far the only place that did hitobject transformations was the selection handler, but I'm attaching transform controls to the right toolbar, which is two layers too high (`OsuHitObjectComposer` -> `BlueprintContainer` -> `SelectionHandler`) so I did some pretty cursed stuff to expose that. Not sure how that's gonna hold up, I think splitting out object manipulation methods to a more common, non-drawable place may work better.

**Comment by peppy** [comment]
Definitely looking better.

A couple of quick points:
- I'd hope that entering a rotation value in the textbox updates immediately (I think that's what users expect in stable)
- Those toggle icons are cursed 🤣 We do have `EditorRadioButton` but I'm not sure how well that will fit this usage.

**Comment by bdach** [comment]
> I'd hope that entering a rotation value in the textbox updates immediately (I think that's what users expect in stable)

Yup, for sure.

> Those toggle icons are cursed 🤣 We do have `EditorRadioButton` but I'm not sure how well that will fit this usage.

Cursed in what way, icon selection or otherwise? For what it's worth, the sidebar toggles are `DrawableTernaryMenuItem`s (can't be radio buttons because they're not really radios - if you select one, it'll be selected forevermore) and the ones inside the popover _are_ editor radios already. Can nuke the icons if it's about that.

**Comment by peppy** [comment]
The icons specifically.

**Comment by Skubers** [comment]
Since there was a discuss about hotkey parity with stable, can we address the Scaling hotkey (Ctrl+Shift+S) in editor too? As there's no way of actually putting an object between two objects perfectly in the middle or in quarter of the way.

**Comment by bdach** [comment]
See those videos above? They have a scale button too. Don't you worry, I know.

**Comment by Skubers** [comment]
o right, I'm blind sorry

**Comment by Walavouchey** [comment]
is putting the transform buttons on the right side just to fit things on screen? i'd kinda expect those to categorically be among the left-side toolboxes otherwise

**Comment by bdach** [comment]
There was not much reasoning in putting them on the right, although going with left may complicate implementation due to having to scroll the transform buttons into view. But I'll look into the possibility.

**Comment by Skubers** [comment]
Bringing this back to ask @bdach what about that Scaling feature, it's nowhere to be seen on Lazer :(

**Comment by bdach** [comment]
shall i bring to your attention what i have been spending the last three months on?

**Comment by Skubers** [comment]
> shall i bring to your attention what i have been spending the last three months on?

First of all, this is from August which is more than 3 months from now. Considering that I can see the feature there, I can't really see why it wasnt implemented.

Second of all, am I your manager that I need to know everything that you're doing? I'm just asking about the state of the feature, and if you can't provide the information without being scathing, then consider focusing purely on the developing.

**Comment by bdach** [comment]
it will be implemented when it will be implemented. we do not give estimates here. the editor is not currently a priority. please take your attitude elsewhere thank you!
