### ISSUE TITLE
Mania score grade accuracy thresholds are too harsh

### ISSUE THREAD

**Issue by AlexHgC** [ppy/osu#12061]
**Describe the bug:** 
I don't really know if it's a bug or if it's intended, but accuracy on mania seems a little weird for now. I play only on lazer, and it's really really hard to have S, almost impossible. Here is an score played on lazer, i have no miss, i have "only" 61 good, 941k score, but only under 94%. On stable, you can have S around 800/820k score. On lazer, you can have S around 950/960k score. 960K score on stable is like 98.5/99%. 
Oh, and i have the same problem on all my scores, with better ratio too

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/31996023/111621904-d0ca1880-87e8-11eb-91d6-af514600ec4f.png)

**Comment by smoogipoo** [comment]
In lazer, GREATs diminish your accuracy, which is how they affect your score in comparison to what osu!stable does. This won't be changing. What may change is the % at which different grades are given, though it's done this way for simplicity for the time being.

Perhaps related: https://github.com/ppy/osu/issues/10075

**Comment by enoslayd** [comment]
Then we might be able to see a classic mod for mania too? (Just hoping)

**Comment by smoogipoo** [comment]
What would you like to see in a mania classic mod? It's probably not going to be changing grades.

**Comment by enoslayd** [comment]
Just the greats being done like in stable and the health drain disabled (tho the health one is a different topic)

**Comment by Fvern** [comment]
something that has to be mentioned is that the amount greats diminish accuracy by is _way_ too punishing. as mentioned in #9702 the perfect value was changed from 320 to 350. I don't know why this was changed without first getting data from a survey or so because the original 320 value is completely fine. this issue could be solved by reverting the value (since acc would be a lot less harsh, but still more harsh than stable).

**Comment by smoogipoo** [comment]
I'm generally fine with adding a classic mod for mechanics that aren't silly, if there's much request for them.

In std's case, this was done because a lot of maps depend on not having slider head judgements and other mechanics. However, for example, sliders not giving combo (but also not breaking it) when their tails are missed is a mechanic that isn't returning for now because it's technically challenging and would subvert a bunch of systems in order to apply custom scoring.

It's also a bit of a dick move from a UX perspective - I can't count how many times I've seen people ask "why don't I have a full combo?" or similar questions, when this was the reason.

For those reasons, it is what I define as a "silly" mechanic.

> Just the greats being done like in stable

This is also, like my slider example, a case of stable abusing the things it can do and applying some custom scoring. Porting this to lazer is once again very technically challenging. Because of this I consider it in the same realm of "silly" mechanic, and so it won't be returning for now.

If people provide really really really compelling reasons for why stable should be matched 1:1 in every case (including classic mod), then maybe we'll reconsider, but until then the current scoring system is [super easy to understand](https://github.com/ppy/osu/wiki/Scoring#score) and we want to keep it that way.

> health drain disabled

This one can happen, though I'd just make it a universal "no drain" mod for all rulesets.

**Comment by smoogipoo** [comment]
> why this was changed without first getting data from a survey

This was changed with data from a "survey" - it was changed directly as a result of osu!spotlight rankings that you see in the screenshot in the original issue thread. But it can be adjusted again if you can provide a better value substantiated with data.

It's a simple change, all you need to do is adjust this value and it'll update game-wide (song select, beatmap rankings, gameplay, etc):
https://github.com/ppy/osu/blob/d09ad85c7170e90db750c2e842438b7348bdf1b2/osu.Game/Rulesets/Judgements/Judgement.cs#L183-L184

**Comment by AlexHgC** [comment]
What is the value on stable scoreV2 ? 350 seems little too high

**Comment by smoogipoo** [comment]
SV2 is 300 for combo and 305 for accuracy.

But keep in mind that stable has an accuracy curve of `x^(2+2x)` whereas lazer is linear.

**Comment by enoslayd** [comment]
> I'm generally fine with adding a classic mod for mechanics that aren't silly, if there's much request for them.
> 
> In std's case, this was done because a lot of maps depend on not having slider head judgements and other mechanics. However, for example, sliders not giving combo (but also not breaking it) when their tails are missed is a mechanic that isn't returning for now because it's technically challenging and would subvert a bunch of systems in order to apply custom scoring.
> 
> It's also a bit of a dick move from a UX perspective - I can't count how many times I've seen people ask "why don't I have a full combo?" or similar questions, when this was the reason.
> 
> For those reasons, it is what I define as a "silly" mechanic.
> 
> > Just the greats being done like in stable
> 
> This is also, like my slider example, a case of stable abusing the things it can do and applying some custom scoring. Porting this to lazer is once again very technically challenging. Because of this I consider it in the same realm of "silly" mechanic, and so it won't be returning for now.
> 
> If people provide really really really compelling reasons for why stable should be matched 1:1 in every case (including classic mod), then maybe we'll reconsider, but until then the current scoring system is [super easy to understand](https://github.com/ppy/osu/wiki/Scoring#score) and we want to keep it that way.

Oh ok.. i was just wondering if it can happen but im fine if it didn't (tho im fine if these changes were balanced out, which i know will happen after before it replaces stable)

> 
> > health drain disabled
> 
> This one can happen, though I'd just make it a universal "no drain" mod for all rulesets.

Ohhhh another difficulty reduction mod since we dont have that much of that kind of mods

As always thank you for all of this.....

**Comment by AlexHgC** [comment]
> SV2 is 300 for combo (=GREAT) and 305 for accuracy (=GREAT+5).
> 
> But keep in mind that stable has an accuracy curve of `x^(2+2x)` whereas lazer is linear.

On the wiki, we can see the MAX HitValue v2 is 320, when it's now 350 on lazer. I think revert to 320 can be good, maybe need some test to compare ? 
![image](https://user-images.githubusercontent.com/31996023/111629675-d6782c00-87f1-11eb-8d99-cf152a9be751.png)

**Comment by smoogipoo** [comment]
The wiki lists that number for SV1. SV2 used to be 320 until Dec 2016, where it was changed as a result of discussions in this thread https://osu.ppy.sh/community/forums/topics/466617?start=5372158.

But that was changing from 320combo/300acc -> 300combo/305acc, so the 320 was applied to the combo portion originally.

Yes, I'm asking for comparative tests.

**Comment by Fvern** [comment]
would discussing the value with 5 or so top mania players (who have tried lazer) after explaining how the system works be sufficient? I plan on doing that and averaging out the resultant values to find something decent, then making a table displaying  some scores before and after the change.

**Comment by smoogipoo** [comment]
Top player opinions are always good to have, yep. I'm asking for data only to show that discussion happened and wasn't just pure hearsay.

**Comment by Fvern** [comment]
right, I'll come back with some proposal written up in a day or two

**Comment by AlexHgC** [comment]
Here is a little comparaison on The Empress Jepetski [https://osu.ppy.sh/beatmapsets/315435#mania/713128](url)

**This is my base play, played on osu!stable, with 956k and 99.14% accuracy**
![stable](https://user-images.githubusercontent.com/31996023/111638068-4985a080-87fa-11eb-9137-2afaa48a97d2.png)

**Now, the same play with MAX HitResult at 320 :**
![320](https://user-images.githubusercontent.com/31996023/111638447-9d908500-87fa-11eb-9b7d-251ca1676d1c.png)

**And now, with the actual lazer build, at 350 :**
![350](https://user-images.githubusercontent.com/31996023/111638491-aaad7400-87fa-11eb-9be2-d24ee417a72d.png)

As you can see, the score don't decrease a lot, but accuracy do. I don't think the HitResult is the only problem, do the accuracy calculation change compared to stable v2 ?

**Comment by smoogipoo** [comment]
2.3% of 1000000 is 23000. The acc% is changing by exactly how much I'd expect.

Please read everything that's been posted above. There's changes and it's all been explained.

**Comment by smoogipoo** [comment]
@Fvern By the way, since I just now noticed the twitter link in your post above, I won't be accepting such opinions. "My acc% is too low" is not a valid argument - it's the relative value that matters, and more important to this discussion - how much a PERFECT scales vs GREATs and GOODs (and the lower hit judgements but those two in particular).

If the displayed acc% is the issue, then I suggest they wait until lazer has score submission and scores are ported across from stable leaderboards with fixed acc%'s.

Just to reiterate: the point of collecting this data is to make the RELATIVE player scores more representative of their true differential. It is NOT to make lazer's acc% closer to that of/to equal stable.

**Comment by Fvern** [comment]
yep, that was an extreme opinion just for demonstration that there is in fact discontent in the community. I will have good data to support whatever I suggest.

**Comment by Fvern** [comment]
here are my research/discussion results https://docs.google.com/spreadsheets/d/1JjOg7jn0K_2NDsesZyVmowpzxc-Nv7xbfia2UfIVO94/edit#gid=0

I used scores from the previous mania spotlight (screenshots linked at the top in 'Source Data'), which turned out to be a great idea since the first 2 maps in the list revealed big issues with the current system (discussed in sheet).

I talked to Cryolien (who has won the majority of the lazer spotlights) while writing, and got Irone's approval afterwards. not_aweeb and nobbele are not top players, but they both play mania so I asked them too.

The proposal is to change PERFECTs from 350 to 315, and to change the Acc:Combo ratio to 99:1.

**Comment by AlexHgC** [comment]
I really agree for 99:1 acc:combo ratio in mania

**Comment by iSimpFor** [comment]
i agree with vernonlim, in personal experience, having greats drop your accuracy so much feels like it hurts quite a bit when you want to aim for an s-rank and you happen to score a couple too many greats over perfects, dropping your accuracy under the threshold for s-rank
