### ISSUE TITLE
Editor won't save changes

### ISSUE THREAD

**Issue by K4ktus123** [ppy/osu#12104]
**Describe the bug:** 
In the editor, when I click on File -> Save, it throws an unhandled error. The same thing happens when I click on File -> Exit -> Save changes.

**Screenshots or videos showing encountered issue:** 
https://1drv.ms/u/s!AlJtD8yWv3t4g8J6Sc2x0YkNKu3yKg?e=4g4OVV

**osu!lazer version:** 
2021.320.0

**Logs:**
[updater.log](https://github.com/ppy/osu/files/6175538/updater.log)
[database.log](https://github.com/ppy/osu/files/6175539/database.log)
[runtime.log](https://github.com/ppy/osu/files/6175541/runtime.log)
[performance.log](https://github.com/ppy/osu/files/6175542/performance.log)
[network.log](https://github.com/ppy/osu/files/6175543/network.log)

**Comment by peppy** [comment]
This looks to be a regression from the EF upgrade which wasn't caught during testing. Can reproduce locally.

**Comment by bdach** [comment]
I'm not sure whether this was explained before, but I've taken a look at this and the core reason of all of our troubles with EF post-3.1 seems to be mixing non-tracked and tracked model instances.

Since 3.1, [EF no longer does identity resolution in non-tracking queries](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#no-tracking-queries-no-longer-perform-identity-resolution). This means that it is no longer guaranteed that querying for a non-tracked entity with the same ID twice will return the same instance both times.

I suspect that the instance might have been shared between tracked and non-tracked queries as well, which would explain why this is a problem only now. EF is internally holding up the invariant that each entity key is associated with exactly one entity, which we break by supplying different non-tracked instances to update methods and expecting them to work the same.

The two obvious options seem to be:
* roll back EF for a performance penalty
* ensure that read usages request non-tracked entities, and that write usages request tracked entities (it is a bit haphazard right now - for instance, `GetWorkingBeatmap()` calls `QueryBeatmap()`, which has tracking off - that reference then trickles down to the editor a few steps down, leading to the error).

Not sure how much time we want to be putting into fixing this.

**Comment by peppy** [comment]
The reasoning for moving forward with the package upgrade was more for compatibility than performance. By reference 3.x we were running into cross package dependency conflicts (especially with signalr).

**Comment by bdach** [comment]
Right, I was aware of it. Option 2 would require auditing all database usages, however.

There is a possible middle ground - each model store could be checking whether it has received the tracked model instance, and if not, requery it as tracking and copy changes across. It's similar to the `.Requery()` workaround we have right now, but that one was more for foreign key references, it seems. I'm not sure whether I like that solution too much, though.
