### ISSUE TITLE
Legacy "scorebar-bg" sprite alignment does not match osu!stable

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#12123]
**Describe the bug:** The skin element of the score and accuracy percentage is too far left of where it should be

**Screenshots or videos showing encountered issue:** 
Stable:
![stable](https://user-images.githubusercontent.com/53081750/111899281-d5cada00-8a2b-11eb-9a6d-2d09d535aaee.png)
Lazer:
![lazer](https://user-images.githubusercontent.com/53081750/111899288-debbab80-8a2b-11eb-9669-74b1adae0620.png)

**osu!lazer version:** 2021.320.0

Skin: https://drive.google.com/file/d/1euE-UtCRU6S2D69MA2LRDW8StroFVBP4/view

**Comment by bdach** [comment]
I just checked and it appears fine here:

![osu_2021-03-21_10-16-57](https://user-images.githubusercontent.com/20418176/111899725-9c479e00-8a2e-11eb-89b9-b2bc05a0e70d.jpg)

@Theighlin Do you have UI scaling active? If so I'm not sure whether we should be supporting this instead of just recommending to turn scaling off, to be quite frank. The health display BG was never intended to support this.

**Comment by frenzibyte** [comment]
Also can happen by the window just not being in the right width/height, maybe could potentially be fixed by scaling the legacy health display with the HUD overlay full width, not sure if ever possible though.

**Comment by bdach** [comment]
That is not a viable fix. The health display was not ever specified to take the full width of the window. It'll look terrible on any skin that uses the element for what it was actually intended for.

The fact that this ever worked is a freak accident. While some of these haphazard alignment issues we can resolve, I do not believe there is a way to cleanly resolve this type of accidental background alignment.
