### ISSUE TITLE
Osu!lazer midi inputs and edrums (list of midi inputs)

### ISSUE THREAD

**Issue by AkseliD** [ppy/osu#12198]
Hello,

This feature idea comes from a problem I'm currently having with midi inputs in Osu!lazer (current version : 2021.323.0).
I would like to play taiko with my edrums (Alesis Forge) but the midi inputs are not recognized. My keyboard is recognized and both are plugged in my PC with USB. FL Studio also gets midi signals from both of my instruments.

Feature : Maybe add a way to see which midi device is plugged in and recognized by Osu!lazer. For example a list of devices ? This would be great to know if osu!lazer gets the signals and just decides to not treat them or if it doesn't get them at all.

**Comment by bdach** [comment]
Support for MIDI messages is limited to note on/off messages from the typical 88-key scale. Anything overly fancy will be most likely dropped by framework ([see implementation](https://github.com/ppy/osu-framework/blob/6fbed98abfa9d461e5697c7fe60fd4568f4c55fc/osu.Framework/Input/Handlers/Midi/MidiHandler.cs#L139-L143)).

If you are really so inclined as to confirm whether the messages are getting dropped by the game or not, currently you could try cloning and running framework visual tests in debug configuration - both device connection messages and the actual MIDI messages get logged in that state. They do not get logged in release, which is why you're not seeing much indication in the actual game.

We could probably dump log level of the connection/disconnection messages to at least show in logs in release configuration, but I don't believe we want to be logging MIDI messages outside of debug.

**Comment by peppy** [comment]
Drums generally still use the standard midi key range (there is no "drum" spec - that's handled by software mapping), so this requires some further investigation.

**Comment by ColdVolcano** [comment]
This is probably because midi-drums transmit messages over midi channel 10 (see [Part 5 of this documentation](http://www.music-software-development.com/midi-tutorial.html)) and the implementation in MidiHandler listens only to channel 1 messages (channel number is also included in the eventType variable).
A simple solution would be to mask the eventType to F0 to ignore channel data, but I am away from my workspace to do the pr
