### ISSUE TITLE
osu! spawns too many threads on import initialization when importing absurd amount of beatmaps

### ISSUE THREAD

**Issue by DavidHusicka** [ppy/osu#12229]
**Describe the bug:** Once beatmaps are dragged and droped into the window of the game, the game starts initializing import for all the beatmaps which causes the game to freeze (and causes the rest of the system to be way less responsible) if the amount is too big (2000 for example). While doing so, the game seems to spawn one new thread for each beatmap (checked the amount of threads via external utility).  After some time, the game unfreezes again and starts importing beatmaps one by one and runs smoothly.

**Screenshots or videos showing encountered issue:** 
![osu_2021-03-30_19-28-27](https://user-images.githubusercontent.com/25853767/113041063-cbca7900-9199-11eb-8eba-2bab98255e9c.png)

**osu!lazer version:** 2021.331.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6231534/database.log)
[network.log](https://github.com/ppy/osu/files/6231535/network.log)
[performance.log](https://github.com/ppy/osu/files/6231536/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/6231538/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6231539/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6231540/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6231541/runtime.log)

**Comment by Game4all** [comment]
This issue stems from the fact that SDL2 generates a distinct file drop event for each file when dropping multiple files onto the game window. This is easily noticeable by breakpointing into this method and dropping multiple files in the game window: https://github.com/ppy/osu/blob/52372fe50d39a70b6a1b9f593af93ac6ba7b59db/osu.Desktop/OsuGameDesktop.cs#L159-L167
 And well, since the game will fire a distinct import task with one file path each time instead of all the file paths because of this, it causes this massive spawning of threads potentially slowing down the entire systems when the numbers get huge...

**Comment by bdach** [comment]
Good call. This wouldn't be as bad had it not been for the `LongRunning` flag, [which is even documented to be well within its right](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcreationoptions?view=net-5.0) to overallocate threads.
