### ISSUE TITLE
Mouse moves to the corner of the screen when alt+tab

### ISSUE THREAD

**Issue by initmd** [ppy/osu#12228]
**Describe the bug:** When i alt+tab, the mouse moves to the corner of the screen

**Screenshots or videos showing encountered issue:** https://u.geshii.moe/7uukk7tdbqwf.mp4 (i was using streamlabs, not the best to record :\ )

**osu!lazer version:** 2021.323.0

**Comment by AlexHgC** [comment]
I have Dual screen, when i go on discord in my second screen, my mouse come back to osu after 5sec everytime, i can confirm this issue

**Comment by geshii** [comment]
It's related to the way that osu! manage the cursor and the tablet compatibility i guess

**Comment by geshii** [comment]
It's even weirder when I run a dev build. I can't even move my mouse out of osu! 
It works fine in windowed and borderless. The problem is only in fullscreen
I'm currently working on the framework to fix this issue, I still think that it's related to OpenTabletDriver

Video : https://u.geshii.moe/omfq0jkkjjhv.mp4 (couldn't upload it directly, the file was too big)
(don't mind the errors on the recording, these are related to rulesets)

**Comment by peppy** [comment]
Is this still occurring? We've made various underlying fixes to window manager support since the issue was reported so it may have been resolved.

**Comment by geshii** [comment]
I'll have to check that tomorrow !

**Comment by geshii** [comment]
Yes, still occuring :\

**Comment by peppy** [comment]
@geshii the original video is no longer available. could you please upload one to github instead so we have record of exactly what you're reporting?

**Comment by geshii** [comment]
> @geshii the original video is no longer available. could you please upload one to github instead so we have record of exactly what you're reporting?

Yup, my upload server went down. I'll have to reproduce the issue and re-upload a video. I'll do that asap !
