### ISSUE TITLE
Changing BPM does not update timeline scrolling increments

### ISSUE THREAD

**Issue by OliBomby** [ppy/osu#12268]
In the editor when changing BPM (adding a new timing point with a different BPM, removing a timing point, or changing the BPM of a timing point), the timeline scrolling with mousewheel or arrow keys will still use the old BPM. This results in the current editor time going unsnapped.
Reloading the editor fixes the issue by using the new BPM.

Video showing the issue: https://drive.google.com/file/d/19A5kSBm_81gAOEkTwrthk4osdoSHpCzW/view?usp=drivesdk

**osu!lazer version:** 2021.311.0

**Comment by bdach** [comment]
This is happening because `EditorClock` is using the wrong beatmap's control points (the `WorkingBeatmap` which is the unmodified one, instead of the editor-local one).

Fixing this is pretty easy at face value, but there's also this semi-related todo item that would help a bit in cleaning things up I'd probably be looking to get done first:

https://github.com/ppy/osu/blob/eb1e850f99f5bd9936d1af135ea8eeb8e5cd623f/osu.Game/Screens/Edit/Editor.cs#L138-L139

as it will clean up this area quite a bit I feel.

**Comment by peppy** [comment]
This is pretty major breakage, so it may be better to fix it the easy way as a first step.
