### ISSUE TITLE
Background videos are scaled to fit width and height of the screen resulting in some beatmaps having incorrectly sized video backgrounds.

### ISSUE THREAD

**Issue by ILOVEPIE** [ppy/osu#12291]
**Describe the bug:** 
The osu! lazer client scales video to fit the screen's width and height, where the osu! client only resizes video to fit the screen's width.

**Screenshots or videos showing encountered issue:** 
http://prntscr.com/11462jy

**osu!lazer version:** 
2021.331.0

**Comment by ILOVEPIE** [comment]
I can write a quick PR to fix this if you guys want.

**Comment by bdach** [comment]
I'm not sure it'll be that easy, but knock yourself out if you want I guess.

**Comment by ILOVEPIE** [comment]
I think this is likely caused by:
https://github.com/ppy/osu/blob/97879c3c98bcc19012c52e86287b2b8c8f0357ab/osu.Game/Storyboards/Drawables/DrawableStoryboardVideo.cs#L44

I'll run a quick test and see if changing that fixes it, if so I'll submit a PR for it.

**Comment by peppy** [comment]
In stable, there is the concept of `WidescreenStoryboard`, which gives the storyboard (and video) access to the full screen area. This is already implemented to some extent, and when set to `true` should already be giving correct behaviour (due to the fill mode being applied in the code you linked).

You may find that the default value of this is changed when only a video is present, or otherwise. Please link beatmaps where you are seeing this fail so we can confirm how their code actually looks.

**Comment by ILOVEPIE** [comment]
ok sure,
https://osu.ppy.sh/beatmapsets/685287
https://osu.ppy.sh/beatmapsets/10067

**Comment by peppy** [comment]
Turns out that the widescreen support checkbox only applies to the storyboard itself, not video. I'll look into this further in the osu-stable code base so we can match behaviour here.
