### ISSUE TITLE
Keybinds can be binded to Scroll wheel, resulting in ability to hit 1200+BPM streams

### ISSUE THREAD

**Issue by mangomizer** [ppy/osu#12339]
As the title suggests, keybinds can be bound to scroll wheel resulting is some ludicrous feats of monostream. This is a problem for both osu! and taiko.

OSU! (I am really bad at the game sorry):
https://user-images.githubusercontent.com/30021847/114017131-8e35b200-9863-11eb-85c2-08eb87a70830.mp4

OSU!TAIKO:
https://user-images.githubusercontent.com/30021847/114016219-84f81580-9862-11eb-8ba0-819121b455f3.mp4

osu!lazer version: 2021.407.1

**Comment by frenzibyte** [comment]
That's a bad one. I think the scroll wheel actions should without doubt still be boundable, but instead provide API for rulesets like `osu!` to restrict certain input keys, by specifying the kind of each of their key bindings, whether it would accept positional input, or pressing keys only, etc..

**Comment by peppy** [comment]
I partially see this as being an issue with the gameplay implementation, rather than the input subsystem, but I guess we should be disallowing such keys which get "autofire" behaviour with common hardware for sanity purposes.

@smoogipoo do you agree with disallowing mouse wheel binds for ruleset key binds? Would you prefer a different approach?

**Comment by smoogipoo** [comment]
I do agree with disallowing mouse wheel for ruleset key binds. Do you have any other suggestion?

**Comment by peppy** [comment]
I don't currently. Will go with that then.
