### ISSUE TITLE
Multiplayer matchmaking mode

### ISSUE THREAD

**Issue by Neichoo** [ppy/osu#12355]
It would be fun to see an official osu! matchmaking. With random maps and random mods.
Separate by ranges as in all games to select the difficulties of the maps
It's just a suggestion

**Comment by smoogipoo** [comment]
This is planned, yes.

**Comment by vernonlim** [comment]
there is a [https://oma.hwc.hr/](fanmade service) that does this type of matchmaking with mini "tournament matches", and it utilizes existing tournament mappools as the maps played. 
having a vetted official tournament mappool list sorted into difficulty brackets to use for the maps played would be infinitely better than random maps (due to SR being flawed), and there would be more than enough for standard due to the plethora of them. 
I think doing something similar would be a great idea, since it's utlizing the tournament community's efforts over the many years.

**Comment by smoogipoo** [comment]
We're already aware of these services/tools. No we will not be using random maps - SR is only the least of the problems.

We're yet to really discuss this internally, but there's people in the team that have very hands-on experience with this and we don't really need opinions at this point in time. There's a lot of systems to tie in together which we need to discuss internally, and a lot of other implementations that need to occur first before anything here.

**Comment by peppy** [comment]
Can we close this as duplicate / same direction as https://github.com/ppy/osu/issues/4178?

**Comment by smoogipoo** [comment]
I think so...
