### ISSUE TITLE
In-game tablet driver - demo displayed wrong when area is flipped

### ISSUE THREAD

**Issue by LemonJuicer** [ppy/osu#12399]
![114455279-d9d9ba00-9bdb-11eb-89ac-d1e5a1e10eea](https://user-images.githubusercontent.com/64481039/114549111-e5bb8f80-9c60-11eb-8975-3073044c898e.png)

**Comment by peppy** [comment]
So I've checked on this, and the display is "correct". Are you expecting the *tablet* in the display to have flipped? Because it's not right now. If it was to flip, things are going to get very weird for anything that isn't `180degrees`, so I'm not sure this is what we want to do.

Probably needs some more user feedback to see if others also see the current display method and think it's "wrong".

**Comment by peppy** [comment]
@smoogipoo and others could you let me know which feels better to you? the current display is correct if the example tablet is viewed from the "by design" orientation, not the "probable rotation" of the user when rotating the area.

Problem I can see is that some users may keep the tablet oriented as designed but change the rotation to account for posture or sitting direction.

**Comment by peppy** [comment]
Here's how it will look if we account for user rotation:

https://user-images.githubusercontent.com/191335/114655961-39dd7700-9d28-11eb-824e-7bc72dad8b9a.mp4

Note the weirdness of the offset adjust UX if we do this (since it's based on original orientation).

**Comment by peppy** [comment]
This one is still pending feedback on how we should be displaying this. @smoogipoo any thoughts? I'm thinking of just implementing it as a momentary button as above (maybe calling the button "Preview rotation").

**Comment by smoogipoo** [comment]
I saw this, I don't have any thoughts yet.

**Comment by bdach** [comment]
I feel like setting rotation is primarily used to work with nonstandard alignments of the tablet itself, and as such it would make sense to rotate the device itself on the preview, as on the [video](https://github.com/ppy/osu/issues/12399#issuecomment-819225166) above, rather than rotate the working area itself (which I understand is what happens now). A hold-to-preview button would also be fine with me, though.

**Comment by peppy** [comment]
I think the best way forward is to just apply the change and see if anyone complains about the rotated visualisation. If there are any complaints, we can add the "push to preview" button. Let's keep things simple until they need to be otherwise complicated.
