### ISSUE TITLE
McOsu-Style Local Profiles

### ISSUE THREAD

**Issue by cptslow-osu** [ppy/osu#12411]
**Describe the new feature:** 
McOsu has a feature which allows players to create local account profiles, see their "top 100 scores" their "weighted pp", "average accuracy", "level", etc.
All scores should still submit like normal.
This feature has birthed x-rank and x-pp speedruns and is very nice to have when changing playstyle because it makes tracking progress with said playstyle significantly easier.

**Proposal designs of the feature:** 
Profile Creation in settings menu, profile selection and looking at plays upon clicking a tab in the top tab bar (not sure what it's actually called).

**Comment by smoogipoo** [comment]
I don't think this is ever going to happen. You can deploy a full infrastructure locally to achieve the same.

**Comment by peppy** [comment]
Can agree with this sentiment. Seems like a completely different direction to take the game implementation, and if you already have it elsewhere then there seems to be little benefit in implementing it here. For the majority of players this will never be used (and the implementation overhead is nothing short of *insane*, since we would need to modularise everything to support both online and local display sources).

Deploying a local infrastructure can actually be done with a single command, and is a viable option.

**Comment by smoogipoo** [comment]
It's quite a few commands and steps actually, definitely something that needs to be improved. It requires my auto-import script along with creating users + APIAccess auth token + changing a few other classes osu!-side.
