### ISSUE TITLE
Blue light filter disabled in Compatibility Mode.

### ISSUE THREAD

**Issue by kxu385** [ppy/osu#12545]
**Describe the bug:** I have to run osu! in Compatibility Mode because I'm playing on a laptop, and it helps to mitigate the absurd amount of latency I get which is almost on par with playing on 60hz v-sync. 

Unfortunately,  Windows 10 night light, or the blue light filter, does not work when osu! is running in fullscreen Compatibility Mode. As a result, my eyes feel like they're getting lasered when I play at night, and I also end up feeling restless. 

I'm not sure why this happens, since the blue light filter works when the filter is enabled automatically at sunset, while I'm tabbed in to the game. But if  I were to tab out and then tab back in to the game, the filter just disappears. The filter works outside of osu!.
 
Applies to both stable and cutting edge.

**Computer Specifications:**
[DxDiag.txt](https://github.com/ppy/osu/files/6364254/DxDiag.txt)

**Comment by smoogipoo** [comment]
First, this is not the repository for osu!stable issues. That one is here: https://github.com/ppy/osu-stable-issues.

Secondly, this is intentional and unfixable by us. Fullscreen disables any compositing done by Windows. The reason why you're not seeing it when not running in compatibility mode is because Nvidia Optimus devices don't support fullscreen with OpenGL, so you're really running in borderless mode in non-compatibility.
You can achieve the same blue light filter effect in compatibility mode by running in borderless mode, but you will get input lag as a result.
