### ISSUE TITLE
Hitsample-related hard crash after switching skins during gameplay loading

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#12629]
Reproduction steps (or [15s video](https://streamable.com/jg7jbh)):
1. Play any mania beatmap.
2. Change skins during the gameplay loading screen (for the best chance of reproducing, switch from this skin https://joppe27.s-ul.eu/FUjlsZfd to this one https://joppe27.s-ul.eu/xlubncdY).
3. Quickly press some keys when gameplay starts (you can also use this replay which always reproduces this issue: [Joppe27 playing Montee - Omni (Elekton) [Everything].zip](https://github.com/ppy/osu/files/6401009/Joppe27.playing.Montee.-.Omni.Elekton.Everything.zip)).
4. An unhandled error will occur: `System.ObjectDisposedException: Can not get a channel from a disposed sample.` The game crashes.

Notice how after step 2, the hit samples do not get changed to those used by the new skin. This is especially obvious when osu! doesn't crash after doing these reproduction steps, because then the old skin hitsamples will just keep being used for the remainder (or a portion) of the beatmap. This is probably very much related to the crash I reported here.

Possibly related: #5798.

Logs: [logs.zip](https://github.com/ppy/osu/files/6401192/logs.zip)

Version: 2021.424.0.0

**Comment by peppy** [comment]
Can you reproduce this on any other ruleset? Sounds like a case we haven't caught / potentially won't (due to osu!mania not using pooling yet)

**Comment by frenzibyte** [comment]
I'm not sure if it's reproducible in other rulesets, but the issue is about `SkinnableSound.Play()` still being unsafe.

There's logic in `Column` that plays samples of the next alive/non-alive hit object, and when a skin change is performed before the game is loaded, `PoolableSkinnableSample` will not be updated until they're alive, and the underlying samples retrieved from the old skin would be disposed ([as the local workarounds for keeping old samples not disposed has been removed](https://github.com/ppy/osu/pull/12136)).

Therefore there's the potential of attempting to retrieve sample channels of the old skin's disposed samples, and thus an exception will be thrown.

I'm not really sure whether the logic in `Column` is good or not, the fact that it attempts to play samples of non-alive hit objects seems a bit wrong... but also on the other hand, I'm not really sure about `SkinnableSound.Play()` still being unsafe, feels like it should early-return if the sample is disposed.

**Comment by peppy** [comment]
I don't believe there's a way to know if the sample/channel is disposed, which is the issue in the first place.

Either `updateSample` needs to be called in `PoolableSkinnableSample.Play` (with some kind of equality check), or the logic in column needs to be changed to not rely on the next hitobject. I'd say the column part is probably the point of larger concern here, but the current method is actually a pretty low-complexity implementation which may not be simple if done anothter way.

A temporary fix would be to not play samples of non-alive DHOs.
