### ISSUE TITLE
Game feels more quiet than in stable

### ISSUE THREAD

**Issue by LemonJuicer** [ppy/osu#12646]
I noticed that lazer is quiter than stable version. What can be the cause of this?

**osu!lazer version:** 2021.424.0

**Comment by Joppe27** [comment]
I know this change was intentional to combat audio ducking and for the new sound effects and such, but could this possibly still be considered as an actual issue? Having to turn your system volume up every time you want to play lazer gets old pretty quick. Not lowering the overall volume by as big of an amount would probably be fine already, but 50% as it is right now is a bit much (that amount was probably chosen for a reason though, so it would be great if another way were to be found around the audio issues if possible). You're free to disregard this if those audio changes were temporary, but afaik they are not?

**Comment by bdach** [comment]
I'm not sure it's actually 50% perception-wise. The value *is* 50%, but as stated in #11735, the actual perceptible difference is likely less than that because human perception of sound is logarithmic and not linear, and I believe BASS's default volume mode is linear?

Something that may address this in the longer run is the audio mixer PoC (https://github.com/ppy/osu-framework/pull/4291).

**Comment by peppy** [comment]
@Joppe27 what are you comparing levels to? ie. which application that you use apart from osu! is playing at such a high volume that osu! seems soft?

**Comment by Joppe27** [comment]
I can't seem to find any applications that play audio in the same way osu!lazer does, so I've just took a few I use regularly:
![6](https://user-images.githubusercontent.com/56885706/116808520-88b54a00-ab39-11eb-8d54-f1e6447d30e3.gif)
Because I use headphones, system volume is a bit of a balancing act between getting my ears blasted out if something decides to play at full volume in browser and being able to use other apps at a decent volume level. That's the reason why I can't just turn my system volume up because lazer handles audio differently, and leave it at that level indefinitely. You can see that even when using stable at 75% volume like I usually do, lazer is still a fair bit quieter at 100% which means I'd have to start raising system volume (and lowering it again, ideally when exiting lazer but mostly when I get deafened by some other app because I forgot). To be clear, this isn't a huge deal, but getting a fix for this would still be very nice to have.

**Comment by peppy** [comment]
Are you sure the window is active there?

**Comment by Joppe27** [comment]
It wasn't active, but I set the "window inactive" volume control to 100% before measuring so there should be no difference there.

**Comment by peppy** [comment]
I don't think this will be resolved until we get to bringing the framework-side mixer changes in (https://github.com/ppy/osu-framework/pull/4291). Let's track things there.

**Comment by peppy** [comment]
Due to many people having issue with the low volume levels, we've bumped this back up to 80% in the next release (same as osu-stable) via https://github.com/ppy/osu/pull/13328.
