### ISSUE TITLE
Migrate Lazer to GitHub Actions

### ISSUE THREAD

**Issue by sr229** [ppy/osu#12641]
To maintain consistency between projects, it might be a good idea to also port Lazer to Actions. This would be similar to https://github.com/ppy/osu-framework/issues/4288, though there would be some changes needed to fit better on Lazer as the project builds differently from Framework.

**Comment by frenzibyte** [comment]
Do you plan to do the migration yourself?

**Comment by sr229** [comment]
> Do you plan to do the migration yourself?

Per usual, yes.

**Comment by bdach** [comment]
I believe there was [prior](https://discord.com/channels/188630481301012481/188630652340404224/648450825722527744) [work](https://github.com/peppy/osu/actions) when it comes to a migration, but it seems to have been lost to the depths of time.

**Comment by sr229** [comment]
> I believe there was [prior](https://discord.com/channels/188630481301012481/188630652340404224/648450825722527744) [work](https://github.com/peppy/osu/actions) when it comes to a migration, but it seems to have been lost to the depths of time.

That's interesting, maybe I can continue where this was left off, I've reviewed the AppVeyor CI for a bit so I may have a general idea on what to do, I'd appreciate some guidance as I go however.

**Comment by smoogipoo** [comment]
This doesn’t really need to be discussed/guidance. It’s much of the same stuff as osu-framework. Much simpler in-fact since we already don’t use cake here.

The big difference, which that prior work didn’t handle, is the deploy stage, where we utilise the appveyor nuget repository to deploy with the still-to-be-deploy package version in the csproj.
Since GH actions doesn’t support this, a local package repository is the next best thing. There’s several ways this can be done: https://stackoverflow.com/a/44463578, with the easiest probably being to add a file in the setup stage.

**Comment by sr229** [comment]
> The big difference, which that prior work didn’t handle, is the deploy stage, where we utilise the appveyor nuget repository to deploy rulesets/templates with the still-to-be-deployed osu.Game package version in the csproj.
Since GH actions doesn’t support this, a local package repository is the next best thing. There’s several ways this can be done: https://stackoverflow.com/a/44463578, with the easiest probably being to add a file in the setup stage.

Originally in the prior work in osu-framework I planned to reuse the fork owner's GitHub Package Registry, but that proved to be really hard to do since there were mulitple factors to consider. I should probably bring that back in the near future due to the importance of the NuGet feed for the workflow.

**Comment by smoogipoo** [comment]
Please use local packages anyway - remote solutions tend to have caching/indexing mechanisms that can get in the way.
