### ISSUE TITLE
Autoplay mod should switch song select to use `ReplayPlayer` instead

### ISSUE THREAD

**Issue by ilsubyeega** [ppy/osu#12653]
**Describe the bug:**
When you enable autoplay mod in solo mode(screen) and play it, it changes to the SoloPlayer screen instead of the ReplayPlayer screen.
AT mod could proceed with the solo score submission for this issue. 
(Currently, osu-web doesn't allow "AT" mods as `invalid mod for ruleset: "AT"`)

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/37479424/116805022-61bd3f00-ab5e-11eb-87e4-80c9868ff87c.mp4

(there is solo score submission request on logs)

**osu!lazer version:** local debug based on https://github.com/ppy/osu/commit/05e18e3ee3f7cd142162c06c47b9fdb11ee094ac

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6410877/runtime.log)
[network.log](https://github.com/ppy/osu/files/6410878/network.log)

**Comment by frenzibyte** [comment]
That also means users can't pause/resume the gameplay clock in autoplay, as it's `ReplayPlayer`-only.

**Comment by peppy** [comment]
I'm planning on looking into this, but not too sure on the correct path to take.

Currently, `ReplayPlayer` takes a score as a `ctor` argument, which makes sense for watching a replay, but not for autoplay.

My plan of attack was to move this to `Player`, passing in the replay score in `Player`'s `ctor` (as an optional parameter). But on further investigation, there is already a `CreateScore()` function which is run on player completion (in the base `Player` implementation).

Do you think we should change the whole flow so that function is called much earlier in the process (ie. in the `ctor`), rather than on completion? And if we still need population to occur on completion that can be a new function called `ApplyToScore` or something?

**Comment by smoogipoo** [comment]
So then `ReplayPlayer` would be constructed without a replay and would create the replay + score internally? That sounds backwards to me, because I imagine `SongSelect` instead creating the autoplay and then constructing a `ReplayPlayer` with it.

One of the big sticking problems to all of this is that `ModAutoplay` attaches the replay directly to the `DrawableRuleset`...

**Comment by peppy** [comment]
If we're moving the generation of autoplay to a higher level, how do you see the playable beatmap construction happening? Do you think it's okay to call that stuff a second time before `Player` loads?

**Comment by smoogipoo** [comment]
No, I don't think it's okay. Unless there's caching and loading at a higher level. We're already loading too many beatmaps.
