### ISSUE TITLE
Hotfixed apk gives "app not installed" error if user installed pulled apk (same version) already

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#12660]
**Describe the bug:** Android doesn't allow downgrading or installing the same version, and the only way is to uninstall (and lose all user data) or wait until another version is out. Tested on Pixel 3a with latest Android 11.

The solutions are:
- just bump android version somehow when there's another android-specific problem in the future (no user interaction)
- use https://developer.android.com/guide/topics/manifest/application-element (only Android 10+ though) and point users to uninstall with that ticked on:
	> android:hasFragileUserData
When the user uninstalls an app, whether or not to show the user a prompt to keep the app's data. The default value is "false".
- point users to use a PC and copy their osu folder, uninstall, then copying it back in

**osu!lazer version:** 2021.502.0

**Comment by Rian8337** [comment]
I don't think the third solution is best for mobile users.

As a note, you don't necessarily need a PC. Android 11 restricts access to `Android/data` folder by default, however there are file explorers that are still able to access the contents of the folder. Users can access the folder that way and create a copy directly on their device. The problem here, however, is the reliance on third party applications, which puts user safety in question.

Regardless, the fact that you need a separate software or device to update the game alone is already a questionable user experience, in my opinion.

**Comment by frenzibyte** [comment]
It all sounds like hotfixes should have their own version instead of rebuilding on previous versions to avoid this.

Also, I wouldn't mind setting `hasFragileUserData` to true either way for users to not have their data deleten when they don't want to, this one sounds good for me.

**Comment by peppy** [comment]
Once we do proper releases this will not be the case. Until then it is on you to work around issues with fringe operating systems.
