### ISSUE TITLE
Mouse input lags behind in macOS

### ISSUE THREAD

**Issue by ReNForce72** [ppy/osu#12666]
**Describe the new feature:** 
This is a follow-up to my previous post about raw input; I was ignorantly using the wrong term, and I apologize. 

This time I have a genuine feature I would like to see implemented, as well as a way of showing you exactly what I mean. Right now the game has two cursor modes; default and High Precision Mode; however, there's a noticeable latency with both modes for me. But now that it's been made clear to me that it's nothing more than a performance issue, I've been able to think more about a solution to my issue.
**Proposal designs of the feature:** 

https://user-images.githubusercontent.com/83483901/116833705-5549de00-ab80-11eb-93a2-0bf32f6e8c10.mov

With the video I provided, you see both the in-game cursor as well as the hardware cursor (the cursor generated by my Mac). As you can see, the in-game cursor drags far behind the hardware cursor. What I want to be able to do is use that hardware cursor in-game. 

Is that at all possible to implement? If not, I will stop asking about this.

**Comment by frenzibyte** [comment]
Keep in mind that unfocusing the game disables "high precision" mode internally. So you're not exactly testing with both modes that way.

**Comment by ReNForce72** [comment]
Gotcha, but that doesn't change the fact that I'm able to get 1:1 movement with one cursor and not the other.

**Comment by ReNForce72** [comment]
If this were possible to implement, though, I'd imagine it would be done by asking the computer for some sort of accessibility permission

**Comment by peppy** [comment]
- When reporting a performance issue please include your specs.
- You're comparing a *hardware cursor* implementation. This has nothing to do with the other game being browser or otherwise. We may implement this in osu! if there is enough demand but it does greatly reduce skinning possibilities.
- Please do not send two messages to an issue in a row. Edit your previous message.

**Comment by ReNForce72** [comment]
As long as the idea is at least on the radar, provided there is enough demand for it, that's all I wanted to hear. And I will keep these rules in mind next time I post. Thanks!

**Comment by peppy** [comment]
It won't fix your underlying issue, which is that you're running windowed and inactive. You will never get good game latency (browser or otherwise) if you are not running exclusive fullscreen (not supported on macOS yet). The cursor is just an illusion.

**Comment by ReNForce72** [comment]
based on your reply, I'm not sure if you know this or not, so I just want to make this clear; though I didn't show it, the latency occurs in fullscreen and windowed mode. The only difference is that you can't see the Mac cursor in fullscreen (so I didn't show it because I couldn't show it). As for your second statement, I don't have any latency issues (windowed or fullscreen) with the browser version because it's using the Mac cursor. Here's gameplay of it. https://www.youtube.com/watch?v=1gFRVPc1N2Y It's not "proof", but idk how anyone could do this with latency issues unless they memorized the entire map and they could run it blind.

**Comment by peppy** [comment]
Based on your reply, I am locking this thread and cutting further communication. It is clear that you are not reading nor attempting to understand. You cannot use inactive window in testing as *it intentionally reduces game performance*.

You cannot compare fullscreen or windowed because *they are the same because we do not support exclusive fullscreen*.

The browser version is *using a hardware cursor*.

Good day.
