### ISSUE TITLE
Spam changing rulesets while toolbar is hidden plays all the samples after showing

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#12704]
**Describe the bug:** 

- hide toolbar
- spam toggle between osu and taiko
- show toolbar
- multiple samples play

**Screenshots or videos showing encountered issue:** Can't atm.

**osu!lazer version:** 2021.502.0

**Comment by peppy** [comment]
Probably a case where we want `ToolbarRulesetSelector` to be `AlwaysVisible` (to maintain thread safety of handling the ruleset change).

**Comment by DobbyK** [comment]
I have but I will look again since it was pretty late, sorry for the inconvenience.

**Comment by DobbyK** [comment]
I have also found within this class, an if statement that isn’t complete:

`                if (found != null)
                    Current.Value = found; `

I might be a huge noob, and just wasting your time, but I believe that this may be part of the problem

**Comment by bdach** [comment]
I'm not sure what you mean by saying "it isn't complete".

The root cause of the issue is localised in `moveLineToCurrent()`. That entire method is scheduled to be invoked after the ruleset selector's children have updated. But if the selector has `IsPresent == false` (usually the case a component is hidden), the component's update loop, including scheduled callbacks, do not run until the component becomes visible again, at which point all accumulated callbacks from ruleset changes that took place while the component is hidden, play all at once. That is why the suggested fix is to apply `IsPresent = true;` on the entire component.
