### ISSUE TITLE
osu!lazer not opening

### ISSUE THREAD

**Issue by Pellepunk04** [ppy/osu#12712]
I tried to play osu!lazer today, I installed the latest version and it opened, but nothing was on the screen except a black rectangle in the upper left corner. No audio plays. The game does show up in task manager. I have tried to re-install it but it didn't work. I'm not sure if crashlogs or logs are needed here because it's not a form of crash.

Specs (from what I can tell)

Windows 10
Processor: Intel(R) Pentium(R) CPU G3240 @ 3.19GHz
4GB of ram
64-bit

**Comment by Pellepunk04** [comment]
I can't actually include logs because there aren't any logs recorded. Don't know how to fix that.

**Comment by Pellepunk04** [comment]
Github says it doesn't support the file format.

**Comment by bdach** [comment]
you can zip it or change the extension to a supported one.

**Comment by bdach** [comment]
I am seeing something called `AppHangB1`, whatever that is, followed by an application error in `gdi32full.dll`. I am therefore inclined to believe that this problem is likely related to your hardware, namely the graphics card. Please try updating drivers and seeing if it helps anything.

A dxdiag report or even the name of your graphics card would also be nice to confirm that it's hardware-related.

**Comment by Pellepunk04** [comment]
The name of my graphics card is: "Radeon RX 560 Series"
