### ISSUE TITLE
Crash right before startup.

### ISSUE THREAD

**Issue by Xyphoes** [ppy/osu#12721]
My osu! Lazer crashes right before start up. 
here's my DxDiag-
[DxDiag.txt](https://github.com/ppy/osu/files/6445985/DxDiag.txt)

My specs-
![image](https://user-images.githubusercontent.com/49097995/117542873-16140500-b038-11eb-993f-20e17dabc954.png)

Not sure what to do.

**Comment by bdach** [comment]
From the attached dxdiag:

```
           Card name: Intel(R) G41 Express Chipset
        Manufacturer: Intel Corporation
```

```
Windows Error Reporting:
+++ WER0 +++:
Fault bucket 1170286514866354183, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: osu!.exe
P2: 0.0.0.0
P3: 5fd43c92
P4: coreclr.dll
P5: 5.0.220.61120
P6: 5fd42cad
P7: c0000005
P8: 00000000001d01bf
P9: 
P10: 
```

[Several other users](https://github.com/ppy/osu/search?q=c0000005+is%3Aissue&type=issues) have reported the same type of issue and it usually indicates faulty graphics device drivers, or that your system does not have support for running opengl which is currently required for lazer.

Please try to update your device drivers. If that fails, we can't offer any more support for now - please stay tuned for compatibility updates in the future (via directx support or otherwise).
