### ISSUE TITLE
Centering text has one frame delay when the volume text changes length

### ISSUE THREAD

**Issue by Susko3** [ppy/osu#12733]
**Describe the bug:** 

When changing the volume from 99 to MAX, the text is off-center for one frame, same applies to the opposite situation.

The same happens when text changes from 9 to 10, etc.

**Screenshots or videos showing encountered issue:** 

![one-frame-to-max](https://user-images.githubusercontent.com/16479013/117589103-e5ab9400-b127-11eb-9ac8-766698d15d9a.gif)

Also happens with the opposite: (image only)

![image](https://user-images.githubusercontent.com/16479013/117589106-e8a68480-b127-11eb-8026-7d9d79775ce3.png)

**osu!lazer version:** 2021.502.0

**Comment by frenzibyte** [comment]
Sounds like another instance of https://github.com/ppy/osu-framework/issues/3369 which can be fixed with centred anchor and origin, but...

The way the volume overlay text is placed is a bit of a long story:
<img width="509" alt="CleanShot 2021-05-10 at 02 15 34@2x" src="https://user-images.githubusercontent.com/22781491/117589945-9cfad780-b135-11eb-9cc7-e8ad449f10f2.png">
https://github.com/ppy/osu/blob/af79ad537c048891659eaabadaa3a1877b7aae89/osu.Game/Overlays/Volume/VolumeMeter.cs#L142-L151

The sprite text has a centered anchor and origin, but it's wrapped in a `BufferedContainer` by a special way ([`WithEffect(GlowEffect)`](https://github.com/ppy/osu-framework/blob/bde91c8d51de42c7553b03be4607edd3d4932646/osu.Framework/Graphics/Drawable.cs#L2677-L2682) -> [`GlowEffect.ApplyTo(OsuSpriteText)`](https://github.com/ppy/osu-framework/blob/4f586e063380fdc39d04cc054f0a6cbe9d301f71/osu.Framework/Graphics/Effects/GlowEffect.cs#L53-L64) -> [`BlurEffect.ApplyTo(OsuSpriteText)`](https://github.com/ppy/osu-framework/blob/6d653ddae3bc703c1bbfbfca73bfaaa895b55630/osu.Framework/Graphics/Effects/BlurEffect.cs#L62-L82) -> [`ContainerExtensions.Wrap(BufferedContainer, OsuSpriteText)`](https://github.com/ppy/osu-framework/blob/d9241109214e71c2ad9d230fd0781635d4ebab60/osu.Framework/Graphics/Containers/ContainerExtensions.cs#L16-L62), which ends up moving the anchor and origin specifications to the given `BufferedContainer and resets them back to `TopLeft` on the wrapped `OsuSpriteText`.

It sounds like the wrapped drawable should not have its anchor and origin reset, but I would have to double-check this with the relative size axes case.
