### ISSUE TITLE
in game hud

### ISSUE THREAD

**Issue by xoxxzyy** [ppy/osu#12856]
In game i feel the Hud is crowded i think skins from Stable or should be able to have there custom key overlay as on stable but on lazer because it is big and chunky. i also think that you should allow us to move and change progress bar so it can look more like osu!stable since that's what everyone is used too and i think it almost distracts me from playing.

**Comment by bdach** [comment]
Gameplay HUD skinning support is literally one of the main focuses right now. Progress bar (if you mean the one at the bottom) can already be moved. I believe the key overlay should also become skinnable at some point.

Please wait for further features of the newly-added in-game skin editor, which will be coming. And please use the issue template instead of deleting it.
