### ISSUE TITLE
Spinners are sometimes not visible

### ISSUE THREAD

**Issue by coinworld** [ppy/osu#12867]
**Describe the bug:** 
I can still hit spinner, but there isn't anything on screen

**Screenshots or videos showing encountered issue:** 
![osu_2021-05-19_20-13-44](https://user-images.githubusercontent.com/9151706/118803930-f35ad980-b8de-11eb-8bcc-2167b2c22e9b.jpg)
https://osu.ppy.sh/beatmapsets/1412455#osu/2911635 (Not only for thia map, but the first spinner of this map is visible while second and last one are not visible)

This is last part of map, I am playing auto and there is no visual evidence for spinner while cursor is spinning

**osu!lazer version:** 
Local build, commit db6d980623931ea527060d312f5344216a72a7bd

**Comment by orozso** [comment]
This problem, not only HD. This in also not HD appear:
On a GIF:

![osu_hidden_spinner](https://user-images.githubusercontent.com/12803062/118853646-42e7d800-b8d4-11eb-96e7-8f0082b29a8c.gif)
 
Map: https://osu.ppy.sh/beatmapsets/43513#osu/136528

**Comment by bdach** [comment]
Ran out of time to perform a proper analysis of what this is, but I do know that it regressed with https://github.com/ppy/osu/pull/12627, and that removing an `Expire()` in `DrawableSpinner.UpdateHitStateTransforms()` makes the spinner show again:

https://github.com/ppy/osu/blob/b8c1ffdef3795a625f6f21cf28f467c8343e5573/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSpinner.cs#L167-L182

My hunch is that because the aforementioned PR hard-coupled DHOs with their entries' lifetime, things may be propagating a bit too much there if an expire is used. I have confirmed that the expire indeed mutates the lifetime entry, but am not yet sure how that contributes to the spinners not showing. Some further investigation is probably necessary to determine what exactly went wrong.

**Comment by ekrctb** [comment]
Spinners are drawn using proxy drawables (to draw these on the top of the playfield). A `OsuPlayfield.ProxyContainer`, which is inheriting `LifetimeManagementContainer`, is used to manage the proxy drawables.
As it is written as a breaking change in #12627, a DHO can no longer be managed correctly by a `LifetimeManagementContainer`. This is because the internal `Drawable.LifetimeChanged` event is not invoked when the entry's lifetime is changed.
It turns out that, for the same reason, a proxy of a DHO also causes incorrect behavior with a `LifetimeManagementContainer`, resulting in the proxy drawable (in this case, of a spinner) not drawn when needed.
