### ISSUE TITLE
`Traceable` mod is not selected if it removes `Hidden` + `Grow/Deflate` combination

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#12874]
**Describe the bug:** If you select `Hidden` + `Grow/Deflate`, then select `Traceable`, the previous mods (both invalid with `Traceable`) are deselected as expected, but `Traceable` remains unchecked.

(I've tried with other invalid combinations, but it seems to happen only with this one.)

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43073074/118876304-6408f280-b8ed-11eb-904b-4d8db3aadce9.mp4

**osu!lazer version:** `2021.515.0`

**Comment by bdach** [comment]
This is a bit of a mess... When selecting traceable with hidden and grow selected, the mod overlay button-local logic fires first:

https://github.com/ppy/osu/blob/d8a2b85acbaad81b8195e06981baad2433069885/osu.Game/Overlays/Mods/LocalPlayerModSelectOverlay.cs#L8-L17

Then, `DeselectTypes()` does its thing, but importantly - it doesn't deselect all other mods immediately and instead deselects them one-by-one, depending on button order:

https://github.com/ppy/osu/blob/d8a2b85acbaad81b8195e06981baad2433069885/osu.Game/Overlays/Mods/ModSection.cs#L162-L179

This causes HD to be deselected (as it's first in the order), which in turn causes the game-global logic to fire:

https://github.com/ppy/osu/blob/d8a2b85acbaad81b8195e06981baad2433069885/osu.Game/OsuGame.cs#L492-L496

At this point `Mods.NewValue` is `[OsuModGrow, OsuModTraceable]`, which are incompatible. So that `.Except()` helpfully trims them both, yielding the final result as described in the report.

**Comment by Joehuu** [comment]
Seems to be resolved in the new design.
