### ISSUE TITLE
Disappeared objects appear again when changing some visual settings in replay

### ISSUE THREAD

**Issue by cihe13375** [ppy/osu#12914]
**Describe the bug:** 
Some disappeared objects would appear again when changing visual settings (more precisely, "beatmap skins", "beatmap colours" and "beatmap hitsounds") in replay. Tested both on lazer default and a custom skin. 

**Screenshots or videos showing encountered issue:**  https://streamable.com/15qp58

**osu!lazer version:** 2021.523.0

**Logs:**  [logs.zip](https://github.com/ppy/osu/files/6527920/logs.zip)

**Comment by peppy** [comment]
This has got to be a regression with recent lifetime changes, I think.

**Comment by ekrctb** [comment]
The issue is not related to lifetime. It is a regression from #12519.

When the skin (or a skin setting) changed, callbacks of the event are invoked:
- `DrawableHitCircle`'s `CirclePiece` (a `SkinnableDrawable`) is recreated.
- Transforms of the DHO are re-applied. In `DrawableHitCircle`, `CirclePiece.Animate` is called.

<https://github.com/ppy/osu/blob/774611f14269c5beb9df775914ba86435f2203e6/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs#L185>

Both event callbacks are under their own `Scheduler`. Because `CirclePiece` is a child `DrawableHitCircle`, its callback is executed before DHO's callback.
The transforms just applied are all gone when the piece is recreated, causing the issue.

Not sure what is the best way to solve this issue. CC @peppy
