### ISSUE TITLE
Font customization for tournament view

### ISSUE THREAD

**Issue by VINXIS** [ppy/osu#12968]
**Describe the new feature:** Be able to select our own font choices that are installed in the PC already instead of being limited to the font(s) used by the client currently. This is in order to provide more design customizability for tournaments to have the tournament view be able to fit more into the aesthetic choices that were made for the tournaments that are using this.

**Proposal designs of the feature:** Could add a dropdown here that allows the selection of being able to change the font so the tournament streamer can just toggle their font choice there and go ahead with the rest of their customization
![](https://i.imgur.com/f4m8iHP.png)

**Comment by peppy** [comment]
Fonts from PC will likely never be available. You would need to first convert then to a skin format manually.

**Comment by LeNitrous** [comment]
At the very least, if font color is able to be changed. o!m 4k FL4T as their designs heavily rely on light colors causing this to happen:
![image](https://user-images.githubusercontent.com/20495991/119759965-c3619680-bedb-11eb-9f05-a0cf2eb0a8fc.png)

And probably for long term, which is probably outside the scope of this issue, make the layout be customizable since skin editing (or at the very least moving around elements) is possible now.

**Comment by peppy** [comment]
@LeNitrous you are a developer. Please consider building a build of lazer for your tournament with a single word change to change the colour.

**Comment by VINXIS** [comment]
That also sounds like itd work well too
