### ISSUE TITLE
Tablet does not work as expected when raw input is enabled

### ISSUE THREAD

**Issue by UnnoticedFool** [ppy/osu#1301]
So, I'm not sure if this is just me, but when I try to use my tablet, moving the pen in the slightest makes my cursor go all sorts of places. Without Raw Input, it is too slow for my play style, so after I turn it on, everything goes insane. I've tried changing the in-game sensitivity and going into the tablet's program to change it, but nothing has worked. Also if I set "Confine mouse cursor" to anything other than "Always", moving my mouse will drag around the screen. Basically, the osu! logo in the menu will be moved around, depending where I move my mouse/pen, making most of the screen a pitch black. 
Link to video evidence:
[https://youtu.be/3zqWFJB07Ww](url)

**Comment by Nightfirecat** [comment]
https://github.com/ppy/osu/issues?utf8=%E2%9C%93&q=is%3Aissue%20tablet

**Comment by SlowLogicBoy** [comment]
Readme.md:

> Status
> 
> This is still heavily under development and is not intended for end-user use. This repository is intended for developer collaboration. You're welcome to try and use it but please do not submit bug reports without a patch. Please do not ask for help building or using this software.

**Comment by Frontear** [comment]
You do realize that tablet should be using its own software to manually reduce playsize?

**Comment by gabixdev** [comment]
@Frontear this is not caused by tablet, raw input is broken.

**Comment by FreezyLemon** [comment]
Found the code that causes this: [OpenTKRawMouseHandler.cs#L74](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Input/Handlers/Mouse/OpenTKRawMouseHandler.cs#L74).

The currentPosition is just moved by the difference between current `state` and `lastState`. As this is relative movement ("where is the cursor now" minus "where was the cursor last frame" times sensitivity), absolute positioning like in tablets doesn't work correctly. It basically treats the tablet like a mouse in this case.

**Comment by peppy** [comment]
It shouldn't be a hard fix. With raw input you are generally given the type of input (whether it's absolute or relative); it's likely we are not using that correctly.

**Comment by FreezyLemon** [comment]
The only mention of relative or absolute movement that I can find is inside `osu.Framework.Platform.Windows.Native.Input` (it contains a `RawMouseFlags` field which differentiates between relative and absolute movement), but there is no mention of it inside OpenTK's vectors or States.

Not sure how to get the info at the moment, since it doesn't seem to be supplied anywhere, unless I missed anything (very possible).

**Comment by ZetaDraconis** [comment]
https://www.youtube.com/watch?v=rBwa1STGKk0
take a look at his comment

**Comment by LittleEndu** [comment]
@ZetaDraconis That comment is irrelevant for anyone else who don't use huion 420 tablets. What gets implemented here needs to work for all tablets in what ever mode they are set to.

**Comment by FreezyLemon** [comment]
There is an even bigger issue at hand here that those "fixes" do not address. At the moment it is literally impossible for us to have correctly working raw input since OpenTK's `MouseState`s do not provide us with enough information (I'll be trying to fix this in OpenTK as soon as I find the time).

Even if the cursor does not fly up into the corner of the screen, the tablet pen is still treated like a mouse (movement works, but absolute positioning doesn't).
This means: Move the pen, the cursor moves. Take the pen away, move it somewhere else and then put it on the tablet again, and you will see that the cursor does not snap to its absolute position like it is supposed to.

Those "the cursor goes crazy" issues might be connected, or they might not be. They seem to be very user-dependent (I do not have them, Wacom CTL-480S) and we will probably have to fix more of them later on.

**Comment by nzcreast** [comment]
Just finished testing out tablet support so far. I noticed that when using the H420 with raw input that absolute positioning doesn't work correctly. I have to grab my mouse and move it to the bottom of the screen and then put my pen in the center of the tablet then everything seems to work correctly.

Other issue is that when I have raw input enabled and I'm running the game in borderless window, I can move the mouse off the screen and keep making it go off the screen, I will add a video for context in a few hours.

**Comment by peppy** [comment]
We don't need more information here; it's obvious what is not working.

I have a fix in the pipeline.

**Comment by nzcreast** [comment]
@peppy Wasn't sure if mouse going off screen was addressed. Thank you.

**Comment by Frontear** [comment]
Shouldn't you be keeping Raw Input off, since tablets rely on absolute position by default?

**Comment by peppy** [comment]
raw input supports absolute positioning. please stop and wait for a fix.

**Comment by levifox54** [comment]
raw input for absolute positioning still doesnt work on my arch linux
