### ISSUE TITLE
osu! breaks seriously when no audio device is available

### ISSUE THREAD

**Issue by peppy** [ppy/osu#1302]
probably depends on https://github.com/ppy/osu-framework/issues/489

**Comment by ArtBlnd** [comment]
Do you have any dumps?
I can't disable my audio device on my computer. needs sample.

**Comment by peppy** [comment]
If you can't disable your audio devices then I doubt you can help fix this.

**Comment by ArtBlnd** [comment]
Well, maybe I have to remove my surface intergrated audio device driver...

**Comment by peppy** [comment]
Trust me that that is not true, and you just aren't trying. Please leave these issues to me unless you are willing to actually put down some effort.

**Comment by Tayo-00** [comment]
Disabled all my audio devices in device manager.

Can confirm, the game breaks. Downloaded a map and loaded it up, but the map won't start playing.
Here's a screenshot for reference https://puu.sh/xZ9d6/da2ec4fb9f.jpg It just hangs there.

And the logs https://puu.sh/xZ9fe/8c8940fb5c.zip
(though I doubt they'll be usefull)

**Comment by NITPRUDO** [comment]
Tried this in latest dev build.
When disabling the Windows Audio service, the entire game freezes on startup.
When disabling all audio devices, the same behavior.

**Comment by NITPRUDO** [comment]
Disabled it while it was running, this error appeared.
![image](https://user-images.githubusercontent.com/5941912/34323116-c071c0b0-e808-11e7-8679-47a33b1770ed.png)
I hit retry and visual studio popped up with this:
![image](https://user-images.githubusercontent.com/5941912/34323120-de41a434-e808-11e7-85da-b28f0d184fd9.png)
Doing a quick read of the call shows that its trying to get an available audio device because it noticed the list of devices changed.

**Comment by peppy** [comment]
Yes, it has still not been fixed yet.

**Comment by NITPRUDO** [comment]
Perhaps use stable behavior? We can try to detect that there is no audio device with the exception it gives us up and show a notification and not let the user play. This is the only solution I can think of atm.

**Comment by Aergwyn** [comment]
For that you can take a look at https://github.com/ppy/osu-framework/pull/1165. @MattiaPette tried an approach.

**Comment by MattiaPette** [comment]
Yeah, my approach was to redo the audio handling part, and it works (not sure now it was a few month ago) definetively not an easy fix. My only problem in that fix is the audio player with the Bass.NoAudio device goes like crazy and throws a lot of bg reload cause it changes song as soon as it starta playing (because is the behaviour of Bass.noAudio)
The only real solution (we discussed on discord) was to create a dummyAudioInterface to replace the Bass.noAudio but it's not an easy job and requires (i think) to create a real audio interface with real drives (with c or c++) only when osu is active.
Out there, there are some programs that uses virtual audio interface s it's not like it's impossible (virtualAudioCable is an example).
Just sharing my experience with this issue because i thinkered a lot on it. Maybe it will be usefull, or maybe not :) idk.

**Comment by peppy** [comment]
Nothing in-game relies completely on audio devices, so there should be no need to create low-level audio devices. Anything relying on time should have fallback logic to a virtual implementation (ie. `TrackVirtual`).

Special care will likely need to be given to the change of state between having any device vs no device, to ensure loaded audio tracks remain loaded during transitions, or are reloaded when a device becomes available again.

**Comment by TemTemmie** [comment]
it does to the framework

**Comment by aceman1209** [comment]
I do not quite understand why not make a variable that will contain whether the sound is available or not. As suggested before me (I have not yet learned how to use the search normally) just show a message that the user has a problem with the sound and he needs to check it, and when everything is in order to resume the game through the timer. And in the lists are shifted id because of what happens all the errors, except when CurrentDevice is equal to NoSound.

**Comment by smoogipoo** [comment]
The fix is quite a bit more involved. There is already a work-in-progress PR that addresses this issue: https://github.com/ppy/osu-framework/pull/1165

**Comment by aceman1209** [comment]
Nice to hear. For me it is difficult, I have never encountered such programming. There's a lot that's not clear to me. Starting from "how it started" and ending "where does it get it" :)

**Comment by peppy** [comment]
Anyone can help. You may want to check [this existing PR](https://github.com/ppy/osu-framework/pull/1165), which I believe was never completed.

**Comment by peppy** [comment]
Offering up to $2000 bounty on this one for a solid framework fix (depending on quality). We need a solution to keep audio tracks moving (and game starting) even when a device is not available.

Even an investigation into the state of things, or a proposal would be helpful. If interested, feel free to reach out with questions or anything.

The goal would be to make this work with minimal added complexity, but will probably need to make some use of fallback clocks (inside `TrackBass`) as i don't believe anything bass provides can provide time-tracking without a device prsent.

The solution should gracefully handle switching from a device to no device and back, and be well tested.
