### ISSUE TITLE
Crash when playing osu!mania with "Perfect" mod

### ISSUE THREAD

**Issue by ArztVielfrass** [ppy/osu#13243]
Happens irregardless of beatmap, somehow Sudden Death works perfectly fine. Can't tell if it's with drawing or the timing windows, it seems to only show the frame when a note would be.

I can't pin down exactly when it crashes... 
1. Missing crashes.
2. Sometimes, I can get one note in without it crashing, then the second note causes a crash.

Version: 2021.524.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6565465/runtime.log) // Removed identifying information

**Comment by bdach** [comment]
Caused by a race in the spectator client, between

https://github.com/ppy/osu/blob/f3bde258a2e519acd119020d45896608f3fb81d8/osu.Game/Online/Spectator/SpectatorClient.cs#L168-L178

and

https://github.com/ppy/osu/blob/f3bde258a2e519acd119020d45896608f3fb81d8/osu.Game/Online/Spectator/SpectatorClient.cs#L234-L239

`currentBeatmap` is the culprit in particular (nulled out by `EndPlaying()` before the last `HandleFrame()` calls fire). Not immediately sure what the proper resolution is there...

**Comment by smoogipoo** [comment]
I think `HandleFrame` should have an IsPlaying check...
