### ISSUE TITLE
osu!lazer does not auto-detect osu!stable folder location if songs folder is in a different directory

### ISSUE THREAD

**Issue by ThatBebx** [ppy/osu#13292]
My bad for including 2 bugs in 1 post; they tie into each other. Sorry for the inconvinience.

### **Describe the bug:** 

My osu! install is located in `C:\Users\Bebx\AppData\Local\osu! `, with `AppData` being a hidden folder by default. Lazer can read this, but does not show the folder, likely due to it being hidden. See the screenshots for evidence that `AppData` does not display in lazer (though can be read by lazer, just not navigated to), but does in Windows.

Also note that the reason for lazer not automatically detecting my stable directory is most likely due to my songs folder being located in `G:\osu songs\songs` instead of its default.

### **Screenshots or videos showing encountered issue:** 

<details>
  <summary>Note that AppData does not show at all. (Click to expand.) </summary>
  
  
![osu_2021-06-02_06-40-33](https://user-images.githubusercontent.com/64631024/120387711-972b9700-c36d-11eb-8638-7bf8f791e4d2.png)
  
</details>

<details>
  <summary>However, note that osu!lazer *can* actually read this folder, as when changing the directory for lazer, it starts you already CD'd to this folder. (Click to expand.) </summary>
  
  
![osu_2021-06-02_06-41-29](https://user-images.githubusercontent.com/64631024/120387838-ba564680-c36d-11eb-935c-8a4441239dd7.png)
  
</details>

<details>
  <summary>Here's AppData in the Windows file explorer. Note its existence. (Click to expand.) </summary>
  
  
![image](https://user-images.githubusercontent.com/64631024/120388263-3cdf0600-c36e-11eb-95e3-863aed37ba46.png)
  
</details>

### **osu!lazer version:** 

osu!lazer 21.524.0

### **Logs:**
These seem irrelevant.

**Comment by bdach** [comment]
> osu!lazer does not auto-detect osu!stable folder location if songs folder is in a different directory

lazer does in fact have a code path checking for existence of `osu!.${USERNAME}.cfg` in the game files in order to locate the beatmap/songs directory. But `getStableInstallPath()`, which is supposed to find the directory in which that file is supposed to be, [also checks if the directory has a songs subdir](https://github.com/ppy/osu/blob/e25d6bb11e87b4f37462a484cd629990a5488dfe/osu.Desktop/OsuGameDesktop.cs#L58-L85), which doesn't seem to make much sense.

As for hidden files being skipped - [checks out with what the docs say](https://docs.microsoft.com/en-us/dotnet/api/system.io.enumerationoptions.attributestoskip?view=net-5.0#System_IO_EnumerationOptions_AttributesToSkip).

**Comment by peppy** [comment]
I do think hidden folders should no be displayed. The `AppData` lookup is already performed for the user, so there should be little need to visit hidden folders if the remaining bug was not a bug.
