### ISSUE TITLE
Banana showers will only clear the plate if the last banana is caught

### ISSUE THREAD

**Issue by LiterallyFabian** [ppy/osu#13326]
**Describe the bug:** Banana showers will not clear the osu!catch plate despite ending / starting a new combo, unless the Autoplay mod is used. The attached video shows the same beatmap three times; 
1) In Stable (plate will clear)
2) In Lazer (plate will not clear)
3) In Lazer with Autoplay (plate will clear)

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/47401343/120709285-f0eea700-c4bc-11eb-8871-cde7150d05c7.mp4

beatmap in video:
[beatmap.zip](https://github.com/ppy/osu/files/6594245/beatmap.zip)

**osu!lazer version:** 2021.602.0

**Logs:** n/a

**Comment by bdach** [comment]
Yeah, can repro. Root cause is thus:

https://github.com/ppy/osu/blob/daff4a1a003f46da3538c3c066a57c38db203a1b/osu.Game.Rulesets.Catch/UI/CatcherArea.cs#L42-L55

Bananas have their own `CatchBananaJudgement`s, which return `LargeBonus` (scorable) on hit and `IgnoreMiss` (non-scorable) on miss, therefore the `ShouldExploreJudgement` override:

https://github.com/ppy/osu/blob/daff4a1a003f46da3538c3c066a57c38db203a1b/osu.Game.Rulesets.Catch/Judgements/CatchBananaJudgement.cs#L13

is never even considered for miss.

I don't think that dropping/moving the `IsScorable()` guard is a viable option, however; for the reasoning why I think so, see #8005. Probably going to end up needing special-casing it by type somehow, if this is to be resolved... Would definitely be good to have testing for this.
