### ISSUE TITLE
Language settings not saving

### ISSUE THREAD

**Issue by YoruMaru** [ppy/osu#13383]
When I change my language to japanese, it changed back to english wen i load the game back up.

**Comment by bdach** [comment]
The setting is getting reset on the subsequent game launch after `.AddLanguage()` calls framework-side [trigger changes of the current locale setting](https://github.com/ppy/osu-framework/blob/81121e80e60166aa2f06fd7e3d97fd05c93c4dcd/osu.Framework/Localisation/LocalisationManager.cs#L30-L34). Because English is added before Japanese, that in turn fires the [language update logic](https://github.com/ppy/osu-framework/blob/81121e80e60166aa2f06fd7e3d97fd05c93c4dcd/osu.Framework/Localisation/LocalisationManager.cs#L50-L65), which determines that since Japanese is not registered yet, the setting shall be reverted to English.

I'm not actually sure at which point it is safe to call `.AddLanguage()` without having this happen.
