### ISSUE TITLE
Show replay button doesn't work after completing a solo play

### ISSUE THREAD

**Issue by Speykious** [ppy/osu#13462]
**Describe the bug:**
After playing a map in solo, often, the replay button doesn't work.
Sometimes it does, other times it doesn't.
When it doesn't, clicking it doesn't do anything. It stays there. In the void.
I tried to see if I had to open the heatmap to be able to replay, but I got to replay on one play and not the other, and same for skipping the map. And finally, I tried to see if I could only replay the first map I played. Wasn't the case.
So unfortunately, I have no idea what's causing this, it seems to be completely random from my side.

**Video showing one instance of encountered issue:**
https://user-images.githubusercontent.com/13885008/121745665-f5424200-cb04-11eb-9b3a-ab64aa933534.mp4
Map in the video: https://osu.ppy.sh/beatmapsets/1057848#osu/2251684
EDIT: the play was no-mod.

**osu!lazer version:** 2021.608.0 (Linux)

**Logs:**
[database.log](https://github.com/ppy/osu/files/6640839/database.log)
[network.log](https://github.com/ppy/osu/files/6640845/network.log)
[performance.log](https://github.com/ppy/osu/files/6640841/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6640842/runtime.log)

**Comment by bdach** [comment]
Can reproduce. Reproduction requires playing through the map manually. The following check is being tripped:

https://github.com/ppy/osu/blob/c644e11e5a7098d30145bcac5522bb6ec7c067fa/osu.Game/OsuGame.cs#L427-L437

And it is being tripped because of the following `Player` logic:

https://github.com/ppy/osu/blob/c644e11e5a7098d30145bcac5522bb6ec7c067fa/osu.Game/Screens/Play/Player.cs#L968-L979

The score is being imported with no online score ID, but that score ID being later restored makes it so that the `PresentScore()` flow cannot find it anymore.
