### ISSUE TITLE
Blind mod is broken with barrel roll mod

### ISSUE THREAD

**Issue by gagahpangeran** [ppy/osu#13477]
Today I watched this [koisfishu's video](https://www.youtube.com/watch?v=Q1pHUaEowvU) and in [6:35](https://youtu.be/Q1pHUaEowvU?t=395) it showed the blind mod is broken when played with barrel roll mod.

This video was more than a month ago and I try search the issue with keyword 'blind' or 'barrel roll' and check 'area:mods' label but found nothing.

I check the current build and the bug still exists.

The blind mod's 'door' movement is more broken if the barrel roll mod's roll speed is higher.

https://user-images.githubusercontent.com/4964985/121798749-3eec7300-cc52-11eb-91b4-f149287b905f.mp4

**osu!lazer version:** 2021.612.0

**Comment by aitani9** [comment]
https://github.com/ppy/osu/blob/ee6cf4396a0d6e57f2857967b15b6db64b7379b5/osu.Game.Rulesets.Osu/Mods/OsuModBlinds.cs#L141-L143

The inline comment seems to imply that it is possible for the playfield to move from the center to a different location during a beatmap. Is that actually possible? If so, what would make that happen?

**Comment by bdach** [comment]
Possible or not, is rolling with that assumption an issue? I think it's better to do things explicitly/rely on as little assumptions as possible, like in the linked snippet, rather than assuming symmetry and having the mod break with another mod N months down the line if one really does try to move the playfield.
