### ISSUE TITLE
Placing a slider concurrent with another hit object can cause a "ghost slider" to appear in the timeline

### ISSUE THREAD

**Issue by bluereflega** [ppy/osu#13473]
**Describe the bug:** Placing a slider with the slider head concurrent with a hit circle or another slider head can cause a "ghost slider" to appear in the timeline.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43960495/121785563-1a11e480-cbed-11eb-81d8-41d226a073ef.mp4

In some cases interacting with the editor while these ghost sliders exist can cause unhandled errors or even a crash as shown below. I am not sure how to reproduce these consistently.

https://user-images.githubusercontent.com/43960495/121785570-1ed69880-cbed-11eb-99c3-c5755e4f8a5c.mp4

**osu!lazer version:** 2021.612.0

**Logs:** (these logs are from after the crash)

[database.log](https://github.com/ppy/osu/files/6642696/database.log)
[network.log](https://github.com/ppy/osu/files/6642698/network.log)
[performance.log](https://github.com/ppy/osu/files/6642700/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6642701/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6642702/updater.log)

**Comment by bdach** [comment]
This is quite a spectacular failure, to the point that I'm not even sure where to begin. `HitObjectOrderedSelectionContainer` is very broken by its custom comparer implementation.

https://github.com/ppy/osu/blob/c644e11e5a7098d30145bcac5522bb6ec7c067fa/osu.Game/Screens/Edit/Compose/Components/HitObjectOrderedSelectionContainer.cs#L67-L81

The custom comparer makes framework-side `.Remove()` fail in this case, because that uses `.IndexOf()`/`SortedList.BinarySearch()` to find the item, which falls back to the comparer. One part of the bug is that the params to `CompareReverseChildID` are (I think) inverted, as that function already inverts them once, but the primary mistake here is that the comparer's result depends on fields that are mutated during the placement.

* Assume the hit circle is already placed at index 0, and a slider placement is begun at the same time. The slider has `StartTime == EndTime == 0`, and so the comparer resorts to reverse child ID, but with the with arguments reversed once again, places the slider at index 0 and moves the circle to index 1. IOW, at that point `CompareTo(HitCircle, Slider) < 0`.
* Now add non-zero duration to the slider and finish the placement. The slider now has `EndTime > 0`, so going by its implementation, it should now *follow* the hit circle (IOW, `CompareTo(HitCircle, Slider) > 0`). But the container didn't know anything about that and didn't re-sort its children, so now `BinarySearch()` fails because the list is not properly sorted anymore.'

This is quite the footgun, and the resolution of this might end up being a sweeping change with large implications (from making `EndTime`/`Duration` a bindable, to maybe even framework amendments), so I'm unassigning pending discussion how to handle this.

**Comment by bdach** [comment]
The above can be confirmed by calling `SortInternal()` before every removal - it will prevent the duplicate from remaining. But I am not going to go as far as calling that a "fix" as it feels very inappropriate to do so given the mode of failure, and other similar consistency issues may well appear elsewhere.
