### ISSUE TITLE
In user profile, changing language will not update months under the graph in historical section, only on-hover ones

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#13559]
**Describe the bug:** You can see that the months under the graph are written in japanese because it was the selected language upon opening the game. When changing to another language, it only updates the months when you hover over the graph

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/53081750/122601928-52dd0e00-d072-11eb-8552-8c75d716a31f.mp4

This is how they look when starting up the game in italian
![months](https://user-images.githubusercontent.com/53081750/122601864-3b058a00-d072-11eb-8ddc-0e7978436914.png)

**osu!lazer version:** 2021.619.0

**Comment by bdach** [comment]
Yeah this is something we're going to have to figure out. Things that go through `.ToString()` with culture or humanizer will need to regenerate the text on locale change. Needs framework support to happen first, probably.

**Comment by peppy** [comment]
> Yeah this is something we're going to have to figure out. Things that go through `.ToString()` with culture or humanizer will need to regenerate the text on locale change. Needs framework support of some sort to happen first, probably.

The hopeful path is that we are passing `LocalisableString`s the whole way down. Not sure if that's possible for this specific use case, though.

**Comment by smoogipoo** [comment]
`LocalisableString` was originally made with the intention that it could be extended. It may be possible to have an osu!-side only `HumanisableString` implementation, but I think that will need a little bit more support in o!f (`LocalisableStringEqualityComparer` doesn't consider arbitrary types properly and `LocalisedBindableString` is hard-typed).

**Comment by frenzibyte** [comment]
Since culture strings are the one that needs support for this issue, I've given it an attempt and here's how it went for me:
- https://github.com/ppy/osu-framework/compare/master..frenzibyte:localisable-cultured-string
- https://github.com/ppy/osu/compare/master..frenzibyte:consume-cultured-string

Would like to know if it's in the right direction, before opening PRs for it.

**Comment by bdach** [comment]
The diffs are so small that you may as well have PR'd them.

Aside from some dubious naming (`CulturedString`? `GetOnCulture`?) I think that basing the equality implementation on a `Func` is a quite bad idea. I believe it will actually fail more often than not even if the underlying values are the same, because [you may as well have separate instances of a func that do the same thing but are different references](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgAwFgBQiCM70DcCGYABAGbQDGmRAvEVAKYDuRcArADwCWUwAfABT8AlDV5FMQgNx5CpCghp0mLDtz6CR1MROlp0cTAE5+AEgBEZKJSKcAzkQDe/S9eq0XCgPxEzZoiB8oAHtgHyEAX3oARwh8ABsiYCC5KwQzKSA=).

The way to go is probably to accept an actual piece of data - like an `IFormattable` - into this `CulturedString` thing, and use that for the equality operation.

**Comment by frenzibyte** [comment]
Naming really was a PITA for this specific case, `CulturableString` maybe, not even sure.

As for the equality part, yeah got suspicious about that `Func` equality, your proposal sounds good.

**Comment by bdach** [comment]
I'd probably recommend `LocalisableFormattable` myself if anything.

**Comment by frenzibyte** [comment]
Right, the original idea was a string that gets reloaded everytime the language changes, but it makes all the sense to accept `IFormattable` instead and naming it `LocalisableFormattable` or `LocalisableFormattableString`. Will attempt that in a bit

**Comment by frenzibyte** [comment]
This very specific issue has now been resolved with https://github.com/ppy/osu/pull/14003.
