### ISSUE TITLE
Background image is tinted differently when using screen scaling

### ISSUE THREAD

**Issue by Susko3** [ppy/osu#13607]
**Describe the bug:** 

Background images (this includes beatmap backgrounds and main menu backgrounds) look slightly different when using screen scaling. Only happens when screen is actually scaled, so with scaling set to 100%/100%, it looks the same as if scaling was off.

**Screenshots or videos showing encountered issue:** 

Dim is set to 80% in all examples. Beatmap: https://osu.ppy.sh/beatmapsets/651399

No scaling (or both scale axes set to 100%):

![osu_2021-06-22_01-37-18](https://user-images.githubusercontent.com/16479013/122840473-76b28500-d2fa-11eb-9240-63375d9610f3.png)

`Everything` or `Excluding overlays` scaling:

![osu_2021-06-22_01-37-29](https://user-images.githubusercontent.com/16479013/122840479-787c4880-d2fa-11eb-80f4-1958a02f1051.png)

Stable (for reference):

![screenshot074](https://user-images.githubusercontent.com/16479013/122840485-7ca86600-d2fa-11eb-87a5-6d7ae9eedf07.png)

No scaling (or both scale axes set to 100%):

![osu_2021-06-22_01-39-31](https://user-images.githubusercontent.com/16479013/122840623-c4c78880-d2fa-11eb-8abc-b8403745e22e.png)

`Everything` or `Excluding overlays` scaling:

![osu_2021-06-22_01-39-37](https://user-images.githubusercontent.com/16479013/122840628-c6914c00-d2fa-11eb-95e0-01fb4a95d09c.png)

**osu!lazer version:** 2021.619.1

**Logs:**

[updater.log](https://github.com/ppy/osu/files/6689997/updater.log)
[network.log](https://github.com/ppy/osu/files/6689998/network.log)
[performance.log](https://github.com/ppy/osu/files/6689999/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6690000/runtime.log)

**Comment by peppy** [comment]
The hypothesis is that something is setting alpha on the background rather than using colour fading. I thought we already covered all scenarios, so will require further investigation.

There's also an edge case where the beatmap may be using a png with transparency, but I don't believe that is the case here.

**Comment by peppy** [comment]
On further inspection this is looking to be potentially a shader level issue. Going to bump up in priority until we figure out the root cause. Looks to be triggered by `Masking` turning on, and potentially related to `BufferedContainer`.

Won't happen if the following two lines are commented out:

https://github.com/ppy/osu/blob/d00fb2118840e324cae17f52b481d81e0a7b9012/osu.Game/Graphics/Containers/ScalingContainer.cs#L166-L167

**Comment by smoogipoo** [comment]
As far as I can tell, it does look like this is related to the different shader (`sh_Texture` vs `sh_TextureRounded`). However there's no `BufferedContainer` in use (only gets added when blurred), and I can't repro differences in o!f via the hue selector.
