### ISSUE TITLE
Editor uses a mix of lazer and custom skin

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu#13646]
**Describe the bug:** 
See video
Reloads the skin temporary solves the problem, and the problem appears again if you re-enter the editor

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/50285552/123212370-484dc900-d4f7-11eb-9845-4d547b720cf7.mp4

**osu!lazer version:** 
b6793aa

Edit:
Can't reproduce in 2021.623.0
**Logs:**

**Comment by peppy** [comment]
Seems like a pretty serious regression.

**Comment by nbvdkamp** [comment]
This regressed in #13423, commit e30f658. Something in `RulesetSkinProvidingContainer` or its parent class

**Comment by peppy** [comment]
I believe this may have something to do with load/initialisation order (the part mentioned in the now removed comments in that commit's diff.

Also, when looking into this, we should reevaluate whether the timeline needs skin wrappers. I don't think it does.

**Comment by bdach** [comment]
It is indeed related to load order. The skinnable components get initialised to the default pieces before `RulesetSkinProvidingContainer`'s BDL even runs, although I'm not entirely sure why yet.

This can be confirmed by applying the following:

```diff
diff --git a/osu.Game/Skinning/RulesetSkinProvidingContainer.cs b/osu.Game/Skinning/RulesetSkinProvidingContainer.cs
index c48aeca99a..6e815eab7e 100644
--- a/osu.Game/Skinning/RulesetSkinProvidingContainer.cs
+++ b/osu.Game/Skinning/RulesetSkinProvidingContainer.cs
@@ -55,7 +55,6 @@ private void load()
         protected override void OnSourceChanged()
         {
             UpdateSkins();
-            base.OnSourceChanged();
         }
 
         protected virtual void UpdateSkins()
@@ -75,6 +74,8 @@ protected virtual void UpdateSkins()
                         break;
                 }
             }
+
+            base.OnSourceChanged();
         }
 
         protected ISkin GetLegacyRulesetTransformedSkin(ISkin legacySkin)
```

The `base.OnSourceChanged()` call is supposed to trigger reload via `SourceChanged`. This "fixes" the issue, although it is a bad "fix" as the default pieces are still loaded only to be discarded when that BDL runs.

**Comment by frenzibyte** [comment]
> The skinnable components get initialised to the default pieces before RulesetSkinProvidingContainer's BDL even runs, although I'm not entirely sure why yet.

That's right, it's due to the `content` being added to the ruleset before the container itself is loaded:
https://github.com/ppy/osu/blob/e30f6581b384c35aa7dbe5e9d04ce254bb084e2d/osu.Game/Screens/Edit/Compose/ComposeScreen.cs#L76

causing [the load of the children to happen at `CompositeDrawable`'s BDL](https://github.com/ppy/osu-framework/blob/d02d15db853021669dca5461df5ad1dd91d378be/osu.Framework/Graphics/Containers/CompositeDrawable.cs#L244-L248.), which would be before the `UpdateSkin()` call in `RulesetSkinProvidingContainer`'s BDL.

> @frenzibyte out of curiosity, was there a reason to not have UpdateSkins() always invoke SourceChanged? because that seems wrong to me but the skinning system is still mostly in over my head.

The reason I haven't done that is because `SkinProvidingContainer` itself doesn't do it when DI'ing the fallback source, didn't want to make one behave differently than the other in that aspect.

But the mistake I did, which had lead to this issue, is that I made the container set up the skins at BDL (which can be preceded by loading of children), while `SkinProvidingContainer` sets up the fallback source at `CreateChildDependencies()` (which can't be preceded by loading of children). Not sure if it's intentional or pure luck, but that's probably the way to go with this.
