### ISSUE TITLE
Some default CS values show the "revert to default" button in the Difficulty Adjust mod

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#13649]
**Describe the bug:** For some reason, the `Circle Size` value in the `Difficulty Adjust` mod's customization has the "revert to default" button even if it's already the default (but only with some specific CS values). I noticed it in [this map](https://osu.ppy.sh/beatmapsets/927758#osu) (in the last two highest difficulties).

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43073074/123237336-dfa62280-d4dd-11eb-949b-911a1923799d.mp4

**osu!lazer version:** `2021.623.0`

**Comment by PercyDan54** [comment]
Classic precision loss
![image](https://user-images.githubusercontent.com/50285552/123254923-d3dc4f80-d521-11eb-9d06-dacc9de1e8dd.png)

**Comment by bdach** [comment]
@PercyDan54 it may well be, but i fail to see how a screenshot of chrome devtools showing js behaviour relates to c# behaviour or this issue. have you actually debugged this?

**Comment by PercyDan54** [comment]
> @PercyDan54 it may well be, but i fail to see how a screenshot of chrome devtools showing js behaviour relates to c# behaviour or this issue. have you actually debugged this?

Haven't debugged but I think it's somehow related to this, since he said `only specific values` is affected.

But here's my guess:
https://github.com/ppy/osu-framework/blob/d02d15db853021669dca5461df5ad1dd91d378be/osu.Framework/Bindables/BindableNumber.cs#L79
Here it a float is casted to double, causing this precision loss.

And another screenshot with C# interactive:
![image](https://user-images.githubusercontent.com/50285552/123257310-93ca9c00-d524-11eb-9ae3-5f2de9eeaabf.png)

**Comment by bdach** [comment]
I've *actually* debugged this. `BindableNumber`s handle precision issues correctly. The *actual* problem is that `RestoreDefaultValueButton` always uses a `BindableWithCurrent<T>`, while it should be using `BindableNumberWithCurrent<T>` for numeric controls, which in turn leads it to use the wrong base implementation of `IsDefault` rather than the correct one which comes from `BindableNumber` et al.

@PercyDan54 please refrain from posting untested theories about root causes of a bug in the future if you have not actually debugged and root-caused them properly.

**Comment by frenzibyte** [comment]
Looks to be regressed by #12728 indirectly, since now `RestoreDefaultValueButton` uses a `BindableWithCurrent`, while previously it accesses the bindable instance directly.

One clean solution I can see here is overriding `IsDefault` in `BindableWithCurrent` to point to the current's one. Would like to hear your thoughts on this.

**Comment by bdach** [comment]
by "the current's one" you mean the public `Current`, or the private `currentBound`? because i don't think the former will help (because, again, it's a `Bindable<float>`, and not a `BindableFloat`, and therefore has no precision logic in `IsDefault`), and i'm not sure the further should be allowed because it just makes things messy (different properties of `BindableWithCurrent` will actually access different bindable instances).

i think i'd rather have framework hook up/create the "correct" type automatically somehow, maybe via a factory method (`BindableWithCurrent.Create<T>()` which returns `BindableNumberWithCurrent` when `T` allows it)?

**Comment by frenzibyte** [comment]
I mean the private `currentBound` of course, `Current` points to `this` anyways.

Having a method that constructs either `BindableWithCurrent` or `BindableNumberWithCurrent` is also something I've considered, but it can't really work since `T` must have certain interfaces implemented to be able to use on `BindableNumberWithCurrent`, unless it's fine to do it via reflection? (if that's even possible)

**Comment by bdach** [comment]
I would see it being done via typechecks on `typeof(T)`, which are optimised out by the JIT in the case of generics. Refer to `BindableNumber`'s implementation of `DefaultMinValue` et al. I suppose you _would_ still have to use `Activator.CreateInstance()` to construct an instance even after that.
