### ISSUE TITLE
Using integer keys for settings

### ISSUE THREAD

**Issue by yyny** [ppy/osu#13674]
One issue that bit me yesterday is that key bindings (among some other settings) are stored in a database with their integer key. This meant that adding new key bindings to the `GlobalActionContainer` broke unrelated keybindings because their integer values got shifted. This is not documented or verified at runtime. I had a similar problem earlier, where removing a modded Ruleset caused another installed Ruleset to become the default, and I haven't tested this, but the `game.ini` file seems to suggest the same holds for Skins. The fix for `GlobalActionContainer` is [quite trivial](https://github.com/yyny/osu/commit/fae6a6d2a8d52dd05f54162559b0d8a625fc5d49), but I was wondering why settings are stored like this in the first place? `GlobalAction`s have enum names which seems unlikely to change in the future, and Rulesets and Skins will always have an undetermined install order whereas their install location will likely remain constant. I'm also not quite sure why keybindings specifically are stored in a database in the first place. Am I missing something? Storing keybindings in a `keybinds.ini` seems reasonable enough.

**Comment by bdach** [comment]
Migrating to strings was attempted before but wasn't merged. See #9549.

> where removing a modded Ruleset caused another installed Ruleset to become the default

I don't understand what this is trying to say or why that would be wrong.

> Storing keybindings in a `keybinds.ini` seems reasonable enough.

The game should be the primary means of changing game settings. Allowing users to arbitrarily mess with game files has been a source of many pains in stable and therefore one of the goals of lazer was to lock down undesirable external modifications. Any reasonable functionality that was taken away due to that will be given back via in-game settings of some sort.

**Comment by peppy** [comment]
Rulesets always keep the same ID. Either you ran into a rare bug or did something weird/non-standard.

Please provide logs and actual details for this issue and we will consider reopening it.
