### ISSUE TITLE
Several problems with aspire map

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#13697]
**Describe the bug:** 
Editor problem - "shaking" elements on the timeline, when so mush spinners (first video)
https://youtu.be/sABJFeSbfk8
Negative timeline problems:
https://youtu.be/v8Tk_JdRPqg 
1. If you disable storyboard in the game, music dont stop. But if you disable s/b before the game, there will no music. (0:00 - 0:35)
2. Increasing game speed increase only game speed, not increase music speed, which results in desync. (0:53)
3. If you pausing, then music stops and continue when timeline will have positive value. (1:12)

Storyboard problem:
Elements (notes) are displayed immediately, not when they are needed. (1:20)
Map - https://osu.ppy.sh/beatmapsets/1237363#osu/2571858
Other:
Lazer freeze when this happen (you cant even watch this in the lazer editor):
![screenshot265](https://user-images.githubusercontent.com/59089206/123835239-fbac2880-d910-11eb-8c83-ce61353b82bc.jpg)

**osu!lazer version:** 
2021.623.0

**Comment by peppy** [comment]
This is on the verge of being immediately closeable. You are grouping issues together when they shouldn't be, and also expecting the editor to work on a beatmap which was intentionally game-breaking.

This may never work as expected - just like the stable editor also breaks with similar beatmaps.

**Comment by Moltanicaa** [comment]
These problems are small and only apply to this type of map, so they often do not apply to others. I just consider it necessary to at least point out them. I don't think it's a good idea to create a separate topic for each such problem.

**Comment by smoogipoo** [comment]
Please split this out into multiple issues.

> Editor problem - "shaking" elements on the timeline

Seems to occur when previous objects' lifetimes end towards the left of the timeline. Addressable, but we probably don't want to.

> If you disable storyboard in the game, music dont stop. But if you disable s/b before the game, there will no music

I'd say this is a valid issue, but probably also duplicates https://github.com/ppy/osu/issues/9315

> Increasing game speed increase only game speed, not increase music speed, which results in desync

Also a valid issue.

> If you pausing, then music stops and continue when timeline will have positive value

I'd say this is also valid. Difficult to handle. This is because the "music" in this beatmap is made up of storyboard samples, and we don't restart them. We don't have support for seeking samples in the first place.

> Elements (notes) are displayed immediately, not when they are needed

Probably valid.

> Lazer freeze when this happen

Invalid (at least for the time being) - this is a game breaking beatmap.
