### ISSUE TITLE
Score panels show current date and time after watching their replay

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#13749]
**Describe the bug:** As title. After watching a replay, its score panel shows _temporarily_ the current date (instead of the original one).
Steps to reproduce:
- Open a replay
- Watch the replay
- The "played on" message will show a new time (i.e., when the replay ends).

**Screenshots or videos showing encountered issue:** 

| Before (watching the replay) | After |
|:-:|:-:|
| ![date_before](https://user-images.githubusercontent.com/43073074/124308982-5b514080-db6a-11eb-91db-eb51c951feec.png) | ![date_after](https://user-images.githubusercontent.com/43073074/124309042-71f79780-db6a-11eb-8213-c15ee119abc8.png) |

**osu!lazer version:** `2021.703.0`

**Comment by bdach** [comment]
Regressed in a15cac6, with the introduction of the following:

https://github.com/ppy/osu/blob/ace57a9ee9753b4b808ee3030c02af10b8fbdc65/osu.Game/Screens/Play/Player.cs#L171

and the following:

https://github.com/ppy/osu/blob/ace57a9ee9753b4b808ee3030c02af10b8fbdc65/osu.Game/Screens/Play/Player.cs#L1022-L1023

This is all because `PopulateScore()` sets the date:

https://github.com/ppy/osu/blob/ace57a9ee9753b4b808ee3030c02af10b8fbdc65/osu.Game/Rulesets/Scoring/ScoreProcessor.cs#L342

Unsure of the correct direction to proceed. I feel that either `PopulateScore` shouldn't be setting date, or that replay playback shouldn't need the score to be populated in the first place. Or both?
