### ISSUE TITLE
Improve visual cues on easy mod fail-save

### ISSUE THREAD

**Issue by mk56-spn** [ppy/osu#13844]
https://www.youtube.com/watch?v=d4PfXY7-bkw.

Title plus video really explain it all (yes i also tested without flashlight). I assume this is due to the fact that EZ refills life not being accounted for in the SD mod? 

tested on latest laxer release ( 7th july)

missing on circles also  allows for it

**Comment by bdach** [comment]
I'm not sure fixing this as proposed by forcing easy mod to no extra lives when sudden death is enabled (effectively leading to a situation wherein enabling one mod is affecting settings of another) is a good idea. Sounds like potentially inviting complexity.

Perhaps the extra lives part of easy mod could be split to a separate mod, and that one could be plainly incompatible with sudden death.

**Comment by mk56-spn** [comment]
yeah that makes sense, only reason i brought it up is because right now it feels really not user friendly since the dynamic isnt intuitive, its worth noting that the concept of DT and HT now that rates are a thing also feel out of touch. like it would feel better if it was just a single rate chnage mod with a pitch slider bar  in its options. but thats just me things i guess. not to mention stable users would riot

**Comment by smoogipoo** [comment]
I don't think this is necessarily bad? The bad part for me is that it's not signaled - SD killing you in this situation should probably flash the HP bar or something, along with there being a life count displayed somewhere like a bubble attached to the HP bar.

**Comment by peppy** [comment]
I think the mods being compatible feels fine. Probably needs an audible cue and some kind of visual effect. I think it would potentially be cool to have the hp bar fall away each fail (revealing a new one behind it).

**Comment by Morilli** [comment]
I feel like it makes more sense for the sudden death mod to "override" the extra lives of the easy mod, because
1. It's basically the only thing the sudden death mod does; so it feels like it should be more important than a subfunction of another mod
2. One could argue the main purpose of the sudden death mod is to allow instant-restart on missing a note (or dropping FC), which will no longer be given in this scenario
3. The sudden death mod specifies that it fails a beatmap on miss, not that it drops the health bar to zero. This may be nitpicking but it certainly feels logical this way imo.
