### ISSUE TITLE
Star difficulty  selector resets randomnly on a per map basis

### ISSUE THREAD

**Issue by mk56-spn** [ppy/osu#13852]
Issue: as stated in the title, for a reason I can not comprehend the individual map limits for star rating, as set with the song select/ star range sliders in settings, resets apparently at random when changing mapsets.

Here is a video of the described issue (**0:30 for the issue itself**, previous footage is provided incase it helps for some reason):

https://www.youtube.com/watch?v=eYlRtR8ZNfE

ver: lazer 2021.707.0

windows 10

ps. I should note that something similar happens where I get booted into taiko mode on a standard mapset randomnly on occasion, i shall open an issue for this when im able to capture it happening. 

edit: it only happens for the map being selected. the range for the others is fine.

**Comment by jai-x** [comment]
I think this is case of you clicking the specific difficulty icon by mistake.

If you click on the specific diff icon, it will try and show the difficulty version regardless of the filter settings. 
If you click anywhere else on the beatmap listing it will only show you the filtered diffs.
Unsure if this is intentional or not.

![image](https://user-images.githubusercontent.com/8362491/125173323-a4327600-e1b6-11eb-847f-83120229e10a.png)

**Comment by mk56-spn** [comment]
right yeah tested that and it seems to be the case, sorry, would never have thought the greyed out icons would switch the difficulties

**Comment by jai-x** [comment]
I'm not sure it's intentional for the greyed out icons to override beatmap star difficulty filters so will keep open until confirmed.

**Comment by mk56-spn** [comment]
alright https://www.youtube.com/watch?v=DAiRppsQN70 i'll leave the video of it happening for taiko incase you need it for some reason, sorry for the disturbance

**Comment by frenzibyte** [comment]
I suppose this is intentional as clicking on the difficulty icon essentially triggers a `workingBeatmapChanged` call, which will perform a `Filter` call on all carousel items, with a non-null `SelectedBeatmapSet` value.

This will make all beatmaps belonging to the `criteria.SelectedBeatmapSet` in the currently selected ruleset to appear:
https://github.com/ppy/osu/blob/2b1d3c8e9c9ce4eb5e5790032d64da556a0f7c6f/osu.Game/Screens/Select/Carousel/CarouselBeatmap.cs#L25-L39

In the case of clicking a difficulty icon of a different ruleset, it'll change both the beatmap and the ruleset, causing the same behaviour.

Closing, the part about being an issue with the star rating filter is actually already tracked in https://github.com/ppy/osu/issues/9032, didn't notice that.
