### ISSUE TITLE
Update changed wrong osu! Shortcut on Desktop

### ISSUE THREAD

**Issue by ackhack** [ppy/osu#13864]
**Describe the bug:** 

The newest osu!lazer release change the Path of my osu!stable Shortcut, not the osu!lazer one. I am running Cutting Edge, if that makes a difference.

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/43985368/125288418-6a7c7f00-e31e-11eb-95eb-1dfa663317c8.png)

**osu!lazer version:** 

Updated to 2021.707.0

**Logs:**
[network.log](https://github.com/ppy/osu/files/6801407/network.log)
[performance.log](https://github.com/ppy/osu/files/6801408/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6801409/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6801410/updater.log)
[database.log](https://github.com/ppy/osu/files/6801411/database.log)

**Comment by peppy** [comment]
Not sure on how we should be handling this, open to suggestion. You would hope that squirrel was smart enough to not overwrite an existing shortcut to a completely different target path, but that doesn't seem to be the case.

**Comment by ackhack** [comment]
just looked into it. Squirrel uses the ApplicationName to decide which Shortcut to change. From Update 703 to 707 the Project name changed. Hence it will replace the wrong shortcut. 
![image](https://user-images.githubusercontent.com/43985368/125445135-69c3c6ea-690e-4bb2-bf0b-a90489341686.png)

The way to fix it would either be to rename it back or pass a applicationName to the UpdateManager ctor (not tested but seems plausable).

**Comment by bdach** [comment]
Squirrel [does check if a link exists](https://github.com/ppy/Squirrel.Windows/blob/726634dc40761f9a2e972a609ceb412a853ba98d/src/Squirrel/UpdateManager.ApplyReleases.cs#L213) but then [merrily proceeds to nuke it](https://github.com/ppy/Squirrel.Windows/blob/726634dc40761f9a2e972a609ceb412a853ba98d/src/Squirrel/UpdateManager.ApplyReleases.cs#L228-L237) without checking where it was leading to first. Should be easy enough to add the check in theory, just not sure what to do with the link which was about to be added (add it under a different name? not add it at all?)

**Comment by peppy** [comment]
What I said above (that lazer should just not create an icon if already pointing at another install) may be quite anti-user for users who want to install both osu! versions side by side.

In a potentially lucky turn of events, due to squirrel doing some fallback on both product/title (amongst others), I believe we can fix this in a way where the display name is not changed elsewhere, if that is seen as a better path forward. All without any changes to squirrel itself:

By changing `ProductVersion` back to `osu!(lazer)` or similar, squirrel will create the icon using this while all other display areas (including the window title) will still use "osu!". The result looks something like this:



If no one has any issue / suggestion / problem with this I will go ahead and make the change.
