### ISSUE TITLE
Random mod's seed ignores the first digit typed in after clearing its textbox for the first time

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#13919]
**Describe the bug:** Simply put: after clearing the seed textbox of the Random mod the first time, every first digit typed in when the box is empty won't be registered (but you can still hear the sound of that input).

Here are the steps to reproduce:
- Select the Random mod
- Type a seed (some numbers)
- Clear the textbox
- Type one or more numbers
- The first digit pressed doesn't appear on the textbox (you can repeat this process)

(The on-screen keyboard in the video is just for the recording. I can reproduce the issue even with my physical one.)

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43073074/126067284-f290ed20-97ce-4e42-a736-56f27c6d25a1.mp4

**osu!lazer version:** `2021.707.0-lazer`

**Comment by bdach** [comment]
This is *yet another* case of the base framework textbox's scheduling logic breaking various complex scenarios. Namely, [this text set](https://github.com/ppy/osu-framework/blob/c7b28d822e2a4a2ab3579be4136c68a60584e3b9/osu.Framework/Graphics/UserInterface/TextBox.cs#L657-L667), in particular [this emptying of `text`](https://github.com/ppy/osu-framework/blob/c7b28d822e2a4a2ab3579be4136c68a60584e3b9/osu.Framework/Graphics/UserInterface/TextBox.cs#L663), triggered by a `Current` change, is causing characters to be dropped at `updateCursorAndLayout()` [on this weird guard](https://github.com/ppy/osu-framework/blob/c7b28d822e2a4a2ab3579be4136c68a60584e3b9/osu.Framework/Graphics/UserInterface/TextBox.cs#L345-L346).

I'm 99% sure the other issue (#13920) will be caused by the same thing. But I haven't debugged that one.

**Comment by bdach** [comment]
For whatever it's worth, https://github.com/ppy/osu-framework/pull/4522 with [my patch to fix initial scaling](https://github.com/ppy/osu-framework/pull/4522#issuecomment-864168556) fixes this. It would almost fix #13920 too, if not for the fact that the cursor ends up in the wrong place instead of being reset to start when the `int` bounds are exceeded and the textbox is cleared.
