### ISSUE TITLE
Overlays taking too long to load

### ISSUE THREAD

**Issue by TheBrunoRM** [ppy/osu#13981]
**Describe the bug:** When opening the game, I can't open these menus: profile, settings, music, wiki and changelog.
When I click on the button to open one of those menus, it doesn't actually open it.
For instance, when I click the settings button, it moves the screen a tiny bit to the right but the settings menu doesn't pop up.

I have noticed that after having the game opened for some time, it would finally let me open the said interfaces, but I have no clue whatsoever of how much time it needs to pass.

**Screenshots or videos showing the encountered issue:** https://youtu.be/VMp23ezZt_Q

**osu!lazer version:** 2021.720.0

**Logs:** https://www.mediafire.com/file/vi97f2nsbuz32kl/logs.rar/file

I am really sorry if this bug was reported before, I couldn't find it :(
Apologies for any mistakes I had while writing this.

**Comment by peppy** [comment]
This will happen because they are not loaded yet. Each component is loaded in the background to ensure the game runs smoothly at startup.

If you are running on semi-decent hardware, then this could be due to an actual issue (ie. having too many beatmaps, collections or skins causing some delay in the startup procedure). I can't tell from logs which component is actually taking time to load, so this may require a bit of experimentation from your end. Here's some things to try:

- Disable main menu seasonal/skin backgrounds
- Make sure you're running lazer on a decent disk (ie. not a failing disk of a usb2 device or something)
- Test with no beatmaps loaded to rule that out

Also interested to know your PC specs.

**Comment by TheBrunoRM** [comment]
I would say my pc is decent hardware.
As you say, the issue could be caused by the amount of beatmaps and skins that I have.
Neither way, I think the menu overlays should be loaded first, as I assume they would load faster than a lot of beatmaps.

**Comment by peppy** [comment]
The menus are loaded very early in game startup. Eventually we will make them open and show losing placeholders until they are ready, but even disregarding that what you are seeing is a concern.

I've added extra logging in the next release to help understand this issue. After the next update, please provide your `runtime.log` once more.

**Comment by TheBrunoRM** [comment]
Apologies for taking long to reply. Here's my [runtime.log](https://github.com/ppy/osu/files/6987550/runtime.log) from the current version.

**Comment by peppy** [comment]
Looks potentially related to https://github.com/ppy/osu/issues/14301. Your settings overlay never finishes loading in that execution cycle. Out of curiosity, do you have a lot of skins loaded?

**Comment by TheBrunoRM** [comment]
I do have a lot of skins.

**Comment by peppy** [comment]
we've made multiple improvements to this in the next release (should be out later today). Please check in with us to see how it feels for you!

**Comment by TheBrunoRM** [comment]
Sure, I'll check it out tomorrow

**Comment by TheBrunoRM** [comment]
Nice, I can open the settings menu now.
Thanks!
