### ISSUE TITLE
Intro screens should not allow opening overlays

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu#14081]
**Describe the bug:** 
Pressing ctrl+o in debug builds on startup slightly moves the intro to the right.
Can't reproduce in Release builds.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/50285552/127735576-07f202bb-a3d4-4af9-9ab4-aa09da357bb1.mp4

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6910959/runtime.log)

**Comment by peppy** [comment]
This is due to the settings opening. This is a known issue. They are not loaded yet. Once they load they should appear.

I'm pretty sure this is a duplicate.

**Comment by frenzibyte** [comment]
Oh I thought this was proposing to not open the settings (or any other overlay) while in intro screen, which sounds mostly logical to have.

**Comment by frenzibyte** [comment]
Actually turns out that is already the case, but the overlay activation logic is not being respected on startup for some odd reason.

**Comment by frenzibyte** [comment]
After investigating thoroughly, it appears that any overlay which hasn't passed `LoadComplete` yet would bypass the `OverlayActivationMode.Disabled` state, for two reasons:
 1. The `OverlayActivationMode` is bound and listens to changes on `LoadComplete` (trivial to resolve): https://github.com/ppy/osu/blob/121df57dca7e5f66458ac952920b927861113f0e/osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs#L51-L63
 2. The `UpdateState` method where the `OverlayActivationMode` state is checked only begins to receive calls [after `LoadComplete` from the base `VisibilityContainer` class.](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/Containers/VisibilityContainer.cs#L40-L45) (not trivial to resolve)

I can see two solutions for making `OsuFocusedOverlayContainer`s respect `OverlayActivationMode` state regardless of load state:
 - Virtualizing the `State` bindable osu!framework-side and making a subclass that disallows changing the visibility state when `OverlayActivationMode.Disabled` and otherwise, rather than relying on `UpdateState`. (simple but touches bindables, see [branch](https://github.com/ppy/osu/compare/master...frenzibyte:overlay-visibility-bindable))
 - Refactor `VisibilityContainer` to rename `State` to `StateBindable` and make it immutable, and add a virtual `State` property to override on overlays to disallow on `OverlayActivationMode.Disabled` and otherwise. (avoids dealing with bindables but is a major breaking change, not sure about considering it just yet)

Both of which also allow for not playing the hide sample when activating an overlay while disabled (like during gameplay for example).

Alternatively, we could consider not accessing the visibility state when an overlay isn't fully loaded, as it isn't supposed to make a difference if it's not on the scene yet. (see [branch](https://github.com/ppy/osu/compare/master...frenzibyte:fix-screen-offsetting))

**Comment by bdach** [comment]
Would it not be enough to follow `OsuScreen` and allow overlays to specify their initial activation mode via a virtual property that could be used to initialise the bindable in the constructor?

**Comment by frenzibyte** [comment]
That's another way to resolve the first reason this doesn't work (`OverlayActivationMode` not having the right value), but the second reason would still persist which is that `UpdateState` (where the activation mode is checked to disallow displaying) won't be called until after `LoadComplete`.

**Comment by bdach** [comment]
Then the `IsLoaded` check on top of that would suffice, correct?

**Comment by frenzibyte** [comment]
Yeah for the screen offsetting logic, I'm not sure if we have another case similar to that but if you think it's the right way, I wouldn't mind doing it. (I think it's also more correct to not consider `State` of a non-loaded overlay)

**Comment by frenzibyte** [comment]
@peppy @smoogipoo Any opinions on the [proposed solutions](https://github.com/ppy/osu/issues/14081#issuecomment-890531152)? The bindable subclass way would be a simple change (branch linked), while the other way would avoid that but at the cost of applying major refactor to the `VisibilityContainer` structure.

**Comment by smoogipoo** [comment]
Isn't it a matter of making the overlay not being opened before being loaded? I dunno, that solution sounds like a lot of layers to understand the interactions.

**Comment by frenzibyte** [comment]
The problem here is that even when `OverlayActivationMode.Disabled` is set game-wide, overlays that aren't fully loaded can still have a `Visibility.Visible` state which causes the screen offsetting during intro as described in OP, and it's all due to the base `UpdateState` method not bound until `LoadComplete`.

**Comment by peppy** [comment]
Have you tried making the screen offsets based on the `X` position of the overlays, rather than their visible state?
