### ISSUE TITLE
Muted and mirror mods can't be used as mod / freemod in multiplayer lobby

### ISSUE THREAD

**Issue by minasminas** [ppy/osu#14111]
Choosing one of the two new mods (muted or mirror) throws an error when you try to set them as mod or freemod in multiplayer.

https://user-images.githubusercontent.com/81645139/127919095-2dccf579-3fb6-4f7c-99fd-5f439a54d092.mp4

**Comment by bdach** [comment]
This is a `osu-server-spectator`-side error. I guess due to being compiled against older ruleset packages the server is not aware of the mods' existence and therefore the mod validation logic is kicking in.

When I was testing these I was testing with a local checkout on the spectator server side out of necessity.

**Comment by peppy** [comment]
Thanks, this has been resolved.
