### ISSUE TITLE
Score not saved after beating map better than before

### ISSUE THREAD

**Issue by NieDzejkob** [ppy/osu#14121]
**Describe the bug:**

I beat a particular beatmap with an S rating, then go back to song selection screen which shows only an A on that beatmap. I can reproduce this issue consistently on this map. However, it does not affect everything universally. For example, I purposefully tanked a new beatmap at D and then achieved an A, and it did update on the song selection screen.

Uneducated, wild guess: the results are compared according to the numeric score, even though the accuracy-based grade is actually displayed.

**Screenshots or videos showing encountered issue:** 

[2021-08-03 21-16-18.mkv.gz](https://github.com/ppy/osu/files/6926587/2021-08-03.21-16-18.mkv.gz)

**osu!lazer version:**  2021.731.0 (nixpkgs build, which includes [one patch](https://github.com/NieDzejkob/nixpkgs/blob/osu/pkgs/games/osu-lazer/bypass-tamper-detection.patch))

**Logs:**

[database.log](https://github.com/ppy/osu/files/6926595/database.log)
[network.log](https://github.com/ppy/osu/files/6926596/network.log)
[performance.log](https://github.com/ppy/osu/files/6926597/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6926598/runtime.log)

**Comment by bdach** [comment]
> Uneducated, wild guess: the results are compared according to the numeric score, even though the accuracy-based grade is actually displayed

This is exactly what is happening.

https://github.com/ppy/osu/blob/ceca184b1292832ce6837f6856f7f0443a55d41c/osu.Game/Screens/Select/Carousel/TopLocalRank.cs#L80-L88

This was intentional, I'm pretty sure.

---

Also, as a side-note, please do not try to bypass "tamper detection" with such patches. It is there for a reason and what it is doing is virtually indistinguishable from cheating. Such bypasses will *not* be tolerated for long and the system will eventually become even more locked-down. Please consume official appimage releases if you wish to play multiplayer.

**Comment by frenzibyte** [comment]
Given that the rank displayed on the beatmap item comes from your best score, I don't believe there's an issue here. You may want to wait for proposals like https://github.com/ppy/osu/discussions/14078, or maybe open a discussions thread suggesting better UX for this.

Closing this as not an issue.

**Comment by NieDzejkob** [comment]
Perhaps I'm blind, but I can't see the rank being displayed *anywhere*.

> Also, as a side-note, please do not try to bypass "tamper detection" with such patches. It is there for a reason and what the patch is doing is virtually indistinguishable from cheating. Such bypasses will not be tolerated for long and the system will eventually become even more locked-down. Please consume official appimage releases if you wish to play multiplayer.

The problem with that is that AppImages do not work on NixOS, as there is no libraries or dynamic linker at the FHS locations. I'd like to suggest opening a discussion with upstream nixpkgs to find a solution here. Perhaps a package that unpacks the AppImage and takes the DLLs from there would be acceptable?

**Comment by bdach** [comment]
> Perhaps I'm blind, but I can't see the rank being displayed _anywhere_.

The ranks of all local scores are visible in song select, on the left side, in the "Local" tab:

![2021-08-03-225044_828x863_scrot](https://user-images.githubusercontent.com/20418176/128084396-01a6f214-4230-48b7-ac46-523633b98934.png)

> The problem with that is that AppImages do not work on NixOS, as there is no libraries or dynamic linker at the FHS locations. I'd like to suggest opening a discussion with upstream nixpkgs to find a solution here. Perhaps a package that unpacks the AppImage and takes the DLLs from there would be acceptable?

Since the nixos package was not submitted in an official capacity by anyone from this repository there was never any guarantee of official support. I guess the solution with unpacking the appimages would be preferable if accepted upstream but I do not expect any of the core contributors of this repository will commit time to making that happen due to very low priority relative to other work.

**Comment by NieDzejkob** [comment]
Huh, I didn't notice the tabs there at all. I guess this would've been way less confusing if I'd been aware of its existence. I'd suggest an alternative design for the look&feel of these tabs, but I don't have any idea.
