### ISSUE TITLE
Starting to spectate an osu!mania match from mid-gameplay causes performance issues

### ISSUE THREAD

**Issue by peppy** [ppy/osu#14126]
"Refreshes" count goes from a normal value (~1.5k with two players when spectating from the beginning of the track) to 20-40k. Likely lifetime related, unsure if osu!mania specific.

https://user-images.githubusercontent.com/191335/128123840-3bb0c3bf-0842-47bb-952b-edcebcd2cb6c.mp4

**Comment by ekrctb** [comment]
The issue is easily producible by setting `DrawableRuleset.frameStablePlayback` to `false`.
The mechanism of the original issue (only mania is affected) is:

1. A DHO is added to the playfield. The load state is `Ready`, not `Loaded` yet.
2. Some other hit object is missed. `OrderedHitPolicy.HandleHit` calls `MissForcefully`, setting `Result = Miss` and `State = Miss`.
3. `DrawableHitObject.LoadComplete` calls `updateState(Idle, force: true)`.
4. Because the DHO state is `Idle`, no fade-out transforms are applied. Because the DHO has a result, the hit object stays alive forever.

The overwriting of the state at (3) is the place to fix.
