### ISSUE TITLE
Server asks for the "ends_at" value when attempting to copy a Multi room

### ISSUE THREAD

**Issue by Morodar** [ppy/osu#14161]
**Describe the bug:** 

~~It's basically #11310.~~
Edit: see first comment.

Right-clicking on a room to create a copy, the server returns an error asking for the "ends_at" value.

**Screenshots or videos showing encountered issue:** 

![Animation6](https://user-images.githubusercontent.com/10113399/128613432-a26372cb-d3f3-42a3-a523-052f12655190.gif)

![image](https://user-images.githubusercontent.com/10113399/128613430-392e2131-7467-4f33-9675-ce649b297754.png)

**osu!lazer version:** 
2021.731.0-lazer

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6949772/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6949773/updater.log)
[network.log](https://github.com/ppy/osu/files/6949774/network.log)
[performance.log](https://github.com/ppy/osu/files/6949775/performance.log)

**Comment by frenzibyte** [comment]
This is happening due to a change web-side which expects all rooms with a playlist game type selected to have an `ends_at`/expiration time value. (and as you can see it's currently forced to be playlist for all rooms)

This will be resolved in the next release which corrects the game type (which has been renamed to "match type"), coming very soon.

**Comment by frenzibyte** [comment]
Release published, [2021.808.0](https://osu.ppy.sh/home/changelog/lazer/2021.808.0).
