### ISSUE TITLE
Adjusted values in difficulty adjust mod only updating after you play a map in multiplayer 

### ISSUE THREAD

**Issue by minasminas** [ppy/osu#14235]
Choosing the difficulty adjust mod as a freemod, the adjusted values only get updated after you play a map.

Video:

https://user-images.githubusercontent.com/81645139/129086737-f4f2f73e-7eae-4e99-a3c1-cd19217059b1.mp4

**Comment by NotGumballer91** [comment]
I'm not sure whether it's a similar problem to this but other mods kinda? does this in multiplayer?
Everything updates after you play the map. Such as score multipliers calculates on the results instead on the scoreboard

and some mods just doesn't work properly (like Sudden Death)

**Comment by bdach** [comment]
@NotGumballer91 you're conflating several unrelated issues in your comment. score multipliers may be broken but that's not in scope of this issue, and sudden death will not work as failures are not permitted *at all ever* in multiplayer right now. this issue is for mods with settings exclusively.

**Comment by jacobvm04** [comment]
I looked into this issue, and the problem seems to be that in `ModSettingChangeTracker` adding the `() => SettingChanged?.Invoke(mod)` handler to the `SettingsItem` `SettingsChanged` Event just doesn't work for whatever reason. The `SettingsChanged` event just remains null. I'm not quite sure why this is.
