### ISSUE TITLE
News "show more" button shouldn't appear when there are no more posts available

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#14277]
**Describe the bug:** 
when you select the year 2013 and scroll down to the last post "the revival" there will be the button "show more" but it shouldn't show up since there are no more posts available.

**Screenshots or videos showing encountered issue:** 
![osu!_ojPBPboCEd](https://user-images.githubusercontent.com/43358824/129420242-eda4ae6f-2625-490e-86c2-65a32d51e7ad.png)

**osu!lazer version:** 
2021.809.0

**Comment by frenzibyte** [comment]
It seems osu!web handles this by actually checking whether the returned news posts count match the specified limit per query, rather than `Cursor != null`.

I've opened an issue about the fact that `Cursor` is not null even when reached the end of the year's posts https://github.com/ppy/osu-web/issues/8041, it shall be handled there instead.

Closing this as a web-side issue.
