### ISSUE TITLE
Beatmap creator profil don't updates on some maps for unknow reason

### ISSUE THREAD

**Issue by AlexHgC** [ppy/osu#14306]
**Describe the bug:** 
Here is a video of the bug. This bug only affects the same maps everytime. As you can see, two maps don't refresh the user profile when the 3rd works. 

https://streamable.com/6ln4ut

**osu!lazer version:** 2021.815.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6987309/database.log)
[network.log](https://github.com/ppy/osu/files/6987311/network.log)
[performance.log](https://github.com/ppy/osu/files/6987312/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6987313/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6987314/updater.log)

**Comment by frenzibyte** [comment]
Can you please attach links to the affected beatmaps please.

**Comment by AlexHgC** [comment]
Hm, strangely, the two maps who are not working are marked "pending" but they are unsubmitted. All unsubmitted/deleted maps are now marked as "pending" and have the same issue

**Comment by bdach** [comment]
This is expected for now if the map is unsubmitted. The author of a given map is looked up using data retrieved from the website (more or less).

This will only be fixed for unsubmitted/deleted maps if the author ID is somehow embedded in the beatmap file itself (username lookups are unreliable for this purpose due to name changes).

**Comment by AlexHgC** [comment]
Since it's two different issues, i moved it into #14309 and #14310

**Comment by bdach** [comment]
Going to close this one as it has been split into two
 above.
