### ISSUE TITLE
Logo shaking when you hover over it

### ISSUE THREAD

**Issue by theklensi** [ppy/osu#14366]
**Describe the bug: the logo has schizophrenia** 

**Screenshots or videos showing encountered issue: https://youtu.be/VLZcXnX8z3k** 

**osu!lazer version: 2021.815.0 (android)** 

**Logs: why**

**Comment by peppy** [comment]
If you're talking about the visual delay, this is due to the game running at low frame rate, and there being a one or two frame delay in the layout of the logo in the menu button system (the facade logic specifically, I believe).

For reference, can you share what frame rate you're running at, and which thread mode?

**Comment by theklensi** [comment]
2x refresh rate, multithreaded, 40-60 fps in that screen with play settings and etc

**Comment by Gabixel** [comment]
Following peppy's explanation, it looks similar to https://github.com/ppy/osu/issues/4930

**Comment by theklensi** [comment]
![Screenshot_20210818-000327](https://user-images.githubusercontent.com/86139035/129785659-0c1a6b83-1f08-46f5-a71c-ff19020e0490.png)

**Comment by bdach** [comment]
I think this is close enough to the issue mentioned by @Gabixel to warrant closing as duplicate.
