### ISSUE TITLE
Can't start multiplayer game

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#14410]
**Describe the bug:** Game kicks out in lobby with Invalid client hash, can't submit score

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/53081750/130266398-a69acb21-624d-4c40-9c97-604e319f50a7.mp4

**osu!lazer version:** 2021.820.0-lazer

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/7022986/runtime.log)

**Comment by peppy** [comment]
Should be resolved now.

**Comment by hashelq** [comment]
> Should be resolved now.

Maybe it is not appropriate to ask about it here, but why does the build lock (VersionHash check) exist https://github.com/notgne2/osu-nixos? It makes it impossible to play multiplayer games for people who cannot run appimage or who want to compile the game by themself.

I am pretty sure this will not stop cheaters, because the hacker can always spoof this value.

**Comment by bdach** [comment]
@hashelq the primary reason is for ensuring compatibility of clients with server-side components. as such building from source is not something we can or will support. see https://github.com/NixOS/nixpkgs/issues/132610#issuecomment-893109140

also note that the repository that you have linked to is a work of a person unconnected to this repository, made without counsel with any of us, and the person who made it insists on insulting our intelligence at every juncture rather than discussing the technical points.

**Comment by hashelq** [comment]
@bdach But is not game version enough?

**Comment by bdach** [comment]
for now it may be. but once proper anti-cheat flows come online (https://github.com/ppy/osu/issues/18876) chances are you're not gonna be able to build locally anyways, for reasons that may even not be related to the hash check.
