### ISSUE TITLE
Dimmed toggleable options in settings look weird when enabled

### ISSUE THREAD

**Issue by Sinamer** [ppy/osu#14412]
**Describe the bug:** When the settings section is dimmed and a toggleable option is enabled, it has a ligher pink circle inside

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/53346335/130268951-ca2b5121-7f34-47b9-808b-f87c6884c45a.png)

**osu!lazer version:** 2021.820.0-lazer

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/7023098/runtime.log)

**Comment by Gabixel** [comment]
This also happens in the `PlayerLoader`'s settings:

![player loader](https://user-images.githubusercontent.com/43073074/130270124-17ae6d19-d1cc-430f-9f63-aca8804ede10.png)

**Comment by bdach** [comment]
This is because the layers of the checkboxes are not flattened before applying opacity. The fill and the borders are individual layers, so each gets opacity applied individually, and the intersection of both appears lighter.

This is one of these things where this can probably be fixed but I'm not sure whether the overhead to do so doesn't outweigh the perceived benefit...? A redesign of checkboxes that may happen at some point(TM) may also render this moot.

**Comment by frenzibyte** [comment]
Seems somewhat relevant to https://github.com/ppy/osu/issues/4229.
