### ISSUE TITLE
Pressing left/right keys on slider bars no longer repeat

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#14428]
**Describe the bug:** This is due to the seek replay backward/forward global action using left and right keys, unsetting those will make repeats work again.

**Screenshots or videos showing encountered issue:** 
![Screen Recording 2021-08-20 at 10 15 32 PM 2](https://user-images.githubusercontent.com/35318437/130311417-02dc3a1e-55e4-439a-b521-c36efb42669a.gif)

**osu!lazer version:** Since https://github.com/ppy/osu/pull/13841

**Comment by bdach** [comment]
This is somewhat related to https://github.com/ppy/osu-framework/pull/4690 (i.e. keybinding container/normal event handling crosstalk). Because `GlobalActionContainer` has `SendRepeats => false` by default, and the replay player uses local delegates to handle repeats instead, the global action container sees the first press (because [it has priority over children](https://github.com/ppy/osu/blob/a7e513faedc20a10db0fa87ff152f756ba15caf2/osu.Game/Input/Bindings/GlobalActionContainer.cs#L122-L135)), ignores it as there are no handlers, but then [swallows the repeats with priority](https://github.com/ppy/osu-framework/blob/44f4bd23443f0f125de69a8f0effb901dcaa6973/osu.Framework/Input/Bindings/KeyBindingContainer.cs#L118-L119), preventing the slider bar from ever seeing the repeated events in the first place.

The most robust way to resolve this would probably be to follow the comment in `GlobalActionContainer` and add more local containers.

**Comment by peppy** [comment]
Encountered this same thing in the editor. Definitely warrants a framework fix. `KeyBindingContainer` should not be consuming repeats unless it actually consumed the initial non-repeat action.

**Comment by Joehuu** [comment]
Closing as resolved.
