### ISSUE TITLE
BPM sometimes does not change when changing mod settings.

### ISSUE THREAD

**Issue by rednir** [ppy/osu#14446]
**Describe the bug:**
For example, if you select a beatmap without any mods enabled, then enable DT, the speed increase setting does not impact the BPM displayed. However when selecting a beatmap with DT already enabled, BPM will change with speed increase as normal.

Looks like https://github.com/ppy/osu/pull/14355 is the cause for this bug (specifically this commit: https://github.com/ppy/osu/pull/14355/commits/b419ea716b307eb54fca5892024e5066b81920f0)

https://user-images.githubusercontent.com/10225220/130361437-a095147d-855f-4727-ad8e-2199893479d0.mp4

**Comment by bdach** [comment]
The direct cause is the removal of [this call](https://github.com/ppy/osu/commit/b419ea716b307eb54fca5892024e5066b81920f0#diff-10508e952755970ee0b1dfc1cfaac15497e2e8153598c73c0133e3a3e367ca5fL111). Turns out the bpm display was implicitly relying on the difficulty bindable to update its value, while now it just receives a static mod list per beatmap change and never sees any setting changes due to that if the mod is not selected already when the beatmap is selected.
