### ISSUE TITLE
Hover sample should not be played when opening settings after skin import/deletion

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#14553]
After importing skins from stable / deleting all skins, the settings overlay plays one hover(?) sample for *every* skin that was imported or deleted. This creates an extremely loud noise on opening the settings, depending on the amount of skins changed.

Video speaks for itself:

https://user-images.githubusercontent.com/56885706/131226101-4e161aa8-1832-4181-b95f-a37b8ff271a8.mp4

Version: 2021.828.0

**Comment by bdach** [comment]
The direct reason for this is that [framework-side `Clear()`](https://github.com/ppy/osu-framework/blob/5f65a07b9f1280c3f7a890bf711c65d181fc899e/osu.Framework/Graphics/UserInterface/Menu.cs#L307-L311) calls `updateState()`, which calls `AnimateClose()`, which plays the dropdown close sample.

And the reason why it plays for each item individually is that `SkinSection` sets `Items` N times for N skins imported/deleted:

https://github.com/ppy/osu/blob/7122f48568d2232555f500e4a74e379edd2a337e/osu.Game/Overlays/Settings/Sections/SkinSection.cs#L171-L175

because the skin manager raises events for each skin individually rather than in bulk.

In general I am not too sure why clearing `Items` triggers an `updateState()` call, as clearing doesn't seem to change the dropdown's closed/open state at all? Blame only turns up [this commit](https://github.com/ppy/osu-framework/commit/65afef5fd0abde54f235517b47e85a0cd413d233) which I can't say that I can gather much information out of.

**Comment by peppy** [comment]
Going to bump this up to p0 because I've run into this and it's very startling.
