### ISSUE TITLE
Leaderboard's personal best displayed position doesn't consider score reordering

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#14710]
**Describe the bug:** Not sure if it's something that can be fixed at the moment: this would probably require getting and reordering all ranks from `#1` up to your position (or even further up) to confirm the new correct placement (for people who are not in the top 50), and I'm guessing that's not a very effective/quick method to use for a single case like this.

**Screenshots or videos showing encountered issue:** 

![rank](https://user-images.githubusercontent.com/43073074/132851069-e272e115-7005-4123-acf2-a75c169e9f97.png)

![rank 2](https://user-images.githubusercontent.com/43073074/132852016-71b85756-de47-4a27-9bf0-03bf392014ae.png)

**osu!lazer version:** `2021.907.0`

**Comment by bdach** [comment]
I don't understand this issue. Why would the rank number change, can you elaborate? Was that the rank number that the score had when you originally set it, or...?

**Comment by Gabixel** [comment]
Simply put, the placement shown in "your personal best" (including the one shown in the score panels (see the second screenshot in the OP)) comes from the Classic score and not the Standardized one as shown in the beatmap leaderboard.
(`#28` is the original placement for the Classic version of my score.)

This happens also in the beatmapset overlay when you compare your score to the `#1`:
![image](https://user-images.githubusercontent.com/43073074/132912953-28a97e3d-91ac-4e21-90b3-2bb571073826.png)

**Comment by frenzibyte** [comment]
The top 50 personal score sounds like a resolvable issue, but not sure about the case where it's not in the top 50. I guess it's fine to display the "original" position in that case?

**Comment by bdach** [comment]
Fixing score ranking client-side in general is impractical. This is a server-side consideration.

**Comment by peppy** [comment]
I don't think this is actionable until we reach the point of leaderboard parity.

As has been said, this is a server-side issue and will likely not be resolved until we have all the pieces in place to allow both lazer and stable scores to appear on the same leaderboards, via one means or another.

Something to track, but not something we can fix right now.

**Comment by bdach** [comment]
@ppy/team-client just to confirm, is this on our radar? are we going to get this correct with the current infra work / end-of-year release>

**Comment by peppy** [comment]
Would need to investigate why this is not matching in the first place. Although I feel like this came up in the past and we concluded it was just bad historical data (@nanaya i don't suppose you recall this?)

**Comment by nanaya** [comment]
is it the one which client calculates scores differently from what's stored in index?

**Comment by smoogipoo** [comment]
I believe this issue may be obsolete? The recalculation code doesn't exist anymore, it's using the `total_score` value from the score.

**Comment by bdach** [comment]
Yes, but someone just reported the same symptom of the position on leaderboard not matching (https://github.com/ppy/osu/issues/25831).

**Comment by TimFWinter** [comment]
I also observed these symptoms today and tried to collect as much information on it as I can before posting about it. Some of my observations are being implied in this thread (I think?) but not explicitly stated, which is why I am making this Post.

Today I set a PB score on the following map:
<img width="998" alt="image" src="https://github.com/ppy/osu/assets/65846603/f7a71b01-88a2-43a1-9ee5-a3ef0d612181">

As can be seen in the screenshot, there is a discrepancy between the ranking shown at the bottom of the screenshot and the rank displayed in the list directly above. I was able to reproduce this result by setting new PBs in many different maps. This I am sure all of you are aware off.

After some digging around I figured out that the ranking on the bottom of the screenshot matches the scoreboard seen on [lazer.ppy.sh](https://lazer.ppy.sh/beatmapsets/2079708#osu/4391054) :
<img width="939" alt="image" src="https://github.com/ppy/osu/assets/65846603/b375729e-6382-47e7-a9b6-52d9a95dbb83">


I was wandering why this leaderboard does't match what's displayed in game, until i noticed that on the website every new score submitted is ranked above scores made before a certain cutoff (around 15 days ago in this screenshot), regardless of sore. This behavior is absent in the leaderboards shown in game. 

I have intentionally tried to not interpret these findings, as I am unfamiliar with the source code. 
Hope this post isn't completely redundant.
