### ISSUE TITLE
Maps with slashes in metadata are exported incorrectly

### ISSUE THREAD

**Issue by Wieku** [ppy/osu#14758]
**Describe the bug:** When a map contains slash character anywhere in artist/title/difficulty metadata, after exporting it, it's unimportable in stable. It looks like slashes aren't sanitized so .osu files end up being in subfolders.

Example maps that fail to import after exporting in lazer:
https://osu.ppy.sh/beatmapsets/423194#osu/914570
https://osu.ppy.sh/beatmapsets/855677#osu/1787848

**Screenshots or videos showing encountered issue:**
![image](https://user-images.githubusercontent.com/5307179/133466362-89de4d28-3329-4376-8362-2089ff6c9caf.png)
![image](https://user-images.githubusercontent.com/5307179/133466771-03882078-4b79-4cf0-8ce3-051bb9eaa333.png)

**osu!lazer version:** 2021.907.0-lazer

**Logs:** not needed

**Comment by Youssef-Hammad** [comment]
Can you tell me more about how you recreate the issue?
I downloaded [https://osu.ppy.sh/beatmapsets/423194#osu/914570](url), imported it into osu!lazer, exported it, imported the export in osu! and it loads fine. Tried that with the latest release of lazer and with master with this as the last commit [https://github.com/Youssef-Hammad/osu/commit/90f1592d151229b0fa3f7bdc22662bea5ba554ce](url)

**Comment by bdach** [comment]
@Youssef-Hammad please re-read the opening post. the reproduction scenario is described quite clearly.

the cause is the `exportBeatmap()` call re-saving the beatmap:

https://github.com/ppy/osu/blob/801bee7c47e280555261016ba82edc8743653fe9/osu.Game/Screens/Edit/Editor.cs#L704-L708

which ends up changing the filename of the `.osu` file and making it so that it contains slashes:

https://github.com/ppy/osu/blob/801bee7c47e280555261016ba82edc8743653fe9/osu.Game/Beatmaps/BeatmapManager.cs#L269-L270

as could be seen on the original (if renamed to `.zip` and previewed/extracted) stable looks to sanitize slashes from difficulty names when creating `.osz` archives. the way to proceed here is probably to mirror that.

**Comment by Wieku** [comment]
Additional note, looking at that snippet @bdach shared it seems that any Windows incompatible characters are not sanitized, so maps containing `/`, `<`, `>`, `|`, `?`, `*`, `"` and `:` will fail to import/unpack as well.

**Comment by Youssef-Hammad** [comment]
@Wieku Thanks for the note, I think I got it working for the `/` then I saw your comment

**Comment by peppy** [comment]
This is a pretty important one, but I'm going to hold off fixing it until we've switched to the realm importer, to save fixing it potentially in two different implementations.
