### ISSUE TITLE
Classic mod for osu!taiko on lazer does not accurately replicate behaviour seen in stable

### ISSUE THREAD

**Issue by mangomizer** [ppy/osu#14794]
Below are 4 images of the exact same pattern of the same map, done on Lazer and stable on 4:3 and 16:9.

Lazer:
Resolution: 800x600 (4:3)
![image](https://user-images.githubusercontent.com/30021847/133890325-88243e22-98e2-4875-8313-b973e70b943c.png)

Resolution 1067x600 (16:9)
![image](https://user-images.githubusercontent.com/30021847/133890332-5baa65d3-043c-4831-9f4d-b785e9e7e80d.png)

Stable:
Resolution: 800x600 (4:3)
![screenshot055](https://user-images.githubusercontent.com/30021847/133890405-68acad7c-15f9-445f-b0b3-4f8d578562e3.jpg)

Resolution 1066x600 (16:9)
![screenshot058](https://user-images.githubusercontent.com/30021847/133890471-efbc18f0-4987-44a9-bdce-2d71c78fb505.jpg)

The amount of objects you can see on the screen is consistent - this is correct intended behaviour.

However, you can see that there is some overlap between the circles in stable 4:3 but no overlap on Lazer 4:3. The perceived proximity between circles is something that impacts reading significantly (this is why ultrawide bignote skin on stable +HR is considered an exploit).

In order the replicate the behaviour accurately, the circles in Lazer 4:3 must be scaled up to have the same perceived overlap as seen in stable 4:3. Likewise, the same must be applied for all other resolutions in between and the converse beyond 16:9 (scaled down).

**osu!lazer version: 2021.916.0**

**Comment by mangomizer** [comment]
In fact, I would advocate that this should be the behaviour moving forward for NoMod on lazer as well - since 4:3 on lazer is just a smaller 16:9 that fits on the screen - but this is a discussion for another day once we get community voting underway.

**Comment by zachmanthethird** [comment]
This looks to be an unintended effect of having the playfield height scale with the aspect ratio. The slider velocity has to be scaled to be exponentially faster to compensate.

**Comment by zachmanthethird** [comment]
In osu!stable, playfield height is constant, meaning that less width literally translates to fewer hitobjects on the screen. This makes sense. In osu!lazer, playfield height is proportional to playfield width, meaning that the hitobjects on the screen always remains constant. This also makes sense.
However, in an attempt to replicate stable behavior, instead of keeping the playfield height constant the way stable does, #14106 instead alters the Scroll Speed to make the number of hitobjects on the screen consistent with stable. While this may work for that singular intended purpose, it massively misses the mark and provides unintended difficulty variation in any aspect ratio that isn't 16:9.
To illustrate this, I've made the following recording Unlisted on YouTube: https://youtu.be/f2f49aGx-g0 This recording uses https://osu.ppy.sh/b/3001599 however, I've removed all timing points (shown at 0:11) to eliminate any scroll speed variance throughout the map.

1. Vertical scaling should have no impact on scroll speed. Because the height of the playfield is constant (except for extreme widescreen variations denoted in #14761), vertical scaling has no impact on the playfield; therefore, it shouldn't affect the scroll speed. However, you can see from 1:30 to 2:20 that this is not the current behavior.
2. Because the current solution changes scroll speed to compensate, it actively changes certain aspect ratios' difficulty. Anything past a 1:1 ratio (less than 56% width with 100% height) has a scroll speed higher than Hard Rock (1:07 in the video), while 100% width and 20% height (80:9 or approx. 26.7:1 ratio) has a scroll speed lower than Easy (2:41-3:25 actually compares the two). This actively incentivizes players to use a broken screen scaling.

**Comment by zachmanthethird** [comment]
Adding information after today's community meeting. For the osu!taiko community, this is a priority:0 issue.
Additionally, I'd like to mention that the "Classic" scoring system does not replicate what is seen in stable. The Classic scoring system is combo-exponential meaning that it can easily reach millions in score. The stable system is combo-linear meaning that it's difficult to see any scores above 10 million without a long map duration.
If scores are to be combined, whatever format that takes, this will need to be resolved.

**Comment by peppy** [comment]
> Adding information after today's community meeting. For the osu!taiko community, this is a priority:0 issue.
> Additionally, I'd like to mention that the "Classic" scoring system does not replicate what is seen in stable. The Classic scoring system is combo-exponential meaning that it can easily reach millions in score. The stable system is combo-linear meaning that it's difficult to see any scores above 10 million without a long map duration.
> If scores are to be combined, whatever format that takes, this will need to be resolved.

If leaderboards are to be combined, they would *all* be using "classic" scoring. as in stable would be updated to use that too.

**Comment by Cookie-Tree** [comment]
Disregarding the additional comments from yesterday, I would also like to point out that this aspect ratio handling is extremely exploitable. This is much more potent than an existing exploit that is already punishable with a ban from participating in the taiko world cup (which is using ultrawide + a bignote skin).

**Comment by bdach** [comment]
let me ask this one thing: in the opening post, i can see more hitobjects on the playfield on 16:9 than on 4:3. is this not considered broken? as in, i'd like to think that to have an entirely level playing field, you need to have equal scroll speed, equal overlap *and* equal scroll range / number of hitobjects visible?

i am not trying to wind anyone up, just before i get yelled at. genuine question.

**Comment by zachmanthethird** [comment]
Ideally, yes, to be completely equal, scroll speed, overlap, and visible hitobjects would need to be consistent at every aspect ratio. However, the only way to achieve this is what's already implemented as default lazer gameplay: changing the playfield to fit proportionately based on the aspect ratio.
So ultimately, to differentiate the Classic mod from lazer gameplay, and in the process allow different aspect ratios to have slightly differing gameplay, one of these three items will have to be unequal. The chosen implementation was to have scroll speed being unequal, which spurred on this entire thread. Due to the fact that HR and EZ adjust scroll speed, this isn't viable without making differently aspect ratios egregiously imbalanced. If you kept scroll speed and visible hitobjects constant, the result would be to change the dimensions of the notes themselves to keep overlap consistent. This is what ultrawide/bignote skins do, and as they are considered exploits, this isn't a viable solution either.
The only option left is to keep scroll speed and overlap consistent and vary the number of visible hitobjects on the screen, which just so happens to be the way stable is coded. While I agree that having more/less hitobjects visible is inherently more/less difficult, that's the main topic of discussion in #13047, and out of scope here.

**Comment by frenzibyte** [comment]
Replicating osu!(stable)'s behaviour on the "Classic" mod is possible by disabling the playfield height adjustment, i.e.:
```diff
diff --git a/osu.Game.Rulesets.Taiko/UI/TaikoPlayfieldAdjustmentContainer.cs b/osu.Game.Rulesets.Taiko/UI/TaikoPlayfieldAdjustmentContainer.cs
index 1041456020..e37b739ae2 100644
--- a/osu.Game.Rulesets.Taiko/UI/TaikoPlayfieldAdjustmentContainer.cs
+++ b/osu.Game.Rulesets.Taiko/UI/TaikoPlayfieldAdjustmentContainer.cs
@@ -11,14 +11,12 @@ namespace osu.Game.Rulesets.Taiko.UI
     public class TaikoPlayfieldAdjustmentContainer : PlayfieldAdjustmentContainer
     {
         private const float default_relative_height = TaikoPlayfield.DEFAULT_HEIGHT / 768;
-        private const float default_aspect = 16f / 9f;

         protected override void Update()
         {
             base.Update();

-            float aspectAdjust = Math.Clamp(Parent.ChildSize.X / Parent.ChildSize.Y, 0.4f, 4) / default_aspect;
-            Size = new Vector2(1, default_relative_height * aspectAdjust);
+            Size = new Vector2(1, default_relative_height);

             // Position the taiko playfield exactly one playfield from the top of the screen.
             RelativePositionAxes = Axes.Y;
```

And, along with the "Classic" mod scroll speed adjustment from https://github.com/ppy/osu/pull/14106, matches about exactly with how osu!(stable) feels:

<details>
<summary>osu!(stable) 4:3</summary>

https://user-images.githubusercontent.com/22781491/158036976-fbb3d0d0-4731-45c7-ac6a-ca9382e963de.mp4

</details>
<details>
<summary>osu!(lazer) 4:3 (before)</summary>

https://user-images.githubusercontent.com/22781491/158037632-19d6efc3-267c-44f2-9afa-e927d23c269d.mp4

</details>
<details>
<summary>osu!(lazer) 4:3 (after)</summary>

https://user-images.githubusercontent.com/22781491/158036962-439a9f69-a248-4c60-926b-b4a6dcebfd44.mp4

</details>

However, I'm slightly unsure about PR'ing this right off the bat without first confirming whether that's the preferred direction for osu!taiko's "Classic" mod (which I think it is, since the point of it is to bring back the classic feeling of osu!(stable) with as clean code as possible, if I understand that correctly).

**Comment by peppy** [comment]
In classic mod we do want things to match 1:1, so go ahead with the PR.

I was doing some other work on taiko mod recently to try and make borders display correctly when resizing and was holding off until this logic was revisited (as it would likely break again), so it'd be good to get this sorted.
