### ISSUE TITLE
Long CJK text overflows without wrapping

### ISSUE THREAD

**Issue by Contextualist** [ppy/osu#14837]
**Describe the bug:**
See the comparison for [this map](https://osu.ppy.sh/beatmapsets/1514170)'s comment section:

Lazer's beatmap overlay:
![osu_cjk_long-lazer](https://user-images.githubusercontent.com/16000021/134622025-b7f1b8b6-20ab-49f3-9c97-776302f69964.jpg)

Web:
![osu_cjk_long-web](https://user-images.githubusercontent.com/16000021/134622046-406ac11c-a7f7-4d02-8b99-14f9b789ca42.png)

Long comments in English works just fine, such as those in [this map](https://osu.ppy.sh/beatmapsets/140115).

**osu!lazer version:**
2021.916.0

**Logs:**
Not applicable

**Comment by bdach** [comment]
This was in the back of my mind when thinking about localisation support for text flow. The way I was going to try is to integrate [International Components for Unicode](https://icu.unicode.org/home) with framework - the library in question provides support for [finding potential word break location in a text](https://icu4c-demos.unicode.org/icu-bin/icusegments#2/en).

**Comment by bdach** [comment]
Because I was poking around text flow localisation work anyhow I went to check how big would the overhead involved with adding ICU be. And the results are... not encouraging.

Test cases were: 1 single word, the first paragraph of lorem ipsum, and the first paragraph of the first google search result for "japanese lorem ipsum".

![2021-10-30-212328_1067x207_scrot](https://user-images.githubusercontent.com/20418176/139556078-915c7860-2190-4a83-a37d-7560948d0fff.png)

Maybe I screwed up [my benchmark](https://gist.github.com/bdach/38b89a755d5215c2f6eaec173efa1e73) but I did expect something like this to happen. Probably best to use a naive implementation based on character ranges, then, until someone notices that doesn't work 100% at least.
