### ISSUE TITLE
Currently playing beatmap hyperlink hitbox on the multiplayer listing screen is bigger than expected

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#14965]
from what i've observed this only happens when you enter the multiplayer listing screen and the host hasn't updated the beatmap while you're looking for new lobbys.

https://user-images.githubusercontent.com/43358824/136081454-2bba180d-6cb6-431b-a3af-54a18eb74804.mp4

**osu lazer version:** 2021.1005.0

**Comment by bdach** [comment]
Was tangentially aware that the link had a workaroundy sizing. The relative X sizing will be the cause of this.

https://github.com/ppy/osu/blob/6f7b8293afaab5b3f50fb55ea16229963967ddf7/osu.Game/Screens/OnlinePlay/Lounge/Components/DrawableRoom.cs#L349-L357

@smoogipoo do you recall why this would be needed - is it to make truncation work? Don't really see a reason not to autosize otherwise.

**Comment by smoogipoo** [comment]
It was to make truncation work, yes.
