### ISSUE TITLE
PP counter showing -2147483648 under certain conditions

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#15486]
### Discussed in https://github.com/ppy/osu/discussions/15483

<div type='discussions-op-text'>

<sup>Originally posted by **Ratchet0203** November  5, 2021</sup>
When Relax mod is enabled, you have a max combo of 1 and have gotten a 100 or a 50, the pp counter will display the 32-bit signed integer. I figured this out when I was about to play a map and had to adjust my mouse. I got a 100 on the first slider and I caught the bug out of the corner of my eye as I restarted. I've experimented further with the bug, and this may have to do with the Relax pp formula counting 100s and 50s as misses, as this doesn't occur without Relax, and having all misses doesn't break the counter either. I have attached an example video of me recreating this bug on another attempt.

https://user-images.githubusercontent.com/47193790/140449423-2825be89-2c5a-4d36-8f90-99d8ce4e0626.mp4

Only the conditions I've listed are consistent, however. The counter doesn't always break on the first object. Sometimes, it takes a moment, as shown below.

https://user-images.githubusercontent.com/47193790/140450786-72edc99a-dee0-41c7-ae3d-afc0c5888c3a.mp4

I've also experimented with other mods, and none of them, even classic (which changes the rules for how combo works), seem to change anything.

Lazer version: 2021.1105.0
Logs (as exiting map after recording second video):
[performance-input.log](https://github.com/ppy/osu/files/7480178/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/7480179/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/7480180/runtime.log)
[updater.log](https://github.com/ppy/osu/files/7480181/updater.log)
[database.log](https://github.com/ppy/osu/files/7480182/database.log)
[network.log](https://github.com/ppy/osu/files/7480183/network.log)
[performance.log](https://github.com/ppy/osu/files/7480184/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/7480185/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/7480186/performance-draw.log)</div>

**Comment by Ratchet0203** [comment]
I've done more experimenting with this bug and found that the pp counter breaks specifically on the first slider. Notice how in my first video, the counter broke immediately because the first object was a slider, and in the second, it waited until the first slider to break? I tested this in many other maps and the results were the same. It's sliders that make this glitch possible for whatever reason. To ensure this, I met the described conditions from above on a map with zero sliders, Fireflight - Unbreakable (Sped Up & Cut Ver.) (wafer) [Hard]:

![osu_2021-11-05_16-29-49](https://user-images.githubusercontent.com/47193790/140574600-485c0a1c-3987-4526-accd-cb6d14f19774.png)

As you can see, the counter remained at 0 as intended until the end of the map. This also proves spinners aren't a cause. Regardless of mods, none of this behavior changed. I'm using an MSi GT 73EVR 7RE Titan running Windows 10. However, when I went to test the bug in 2021.1105.0 on my Galaxy Tab S6 running Android 11, the bug never occurred.

**Comment by PercyDan54** [comment]
I could not reproduce this in maps under a certain star range (below ~4.5 stars with Relax)

**Comment by Coppertine** [comment]
Am able to reproduce under some conditions
[replays.zip](https://github.com/ppy/osu/files/7491665/replays.zip)

Below is with no objects hit.
![osu_2021-11-07_13-28-02](https://user-images.githubusercontent.com/37494321/140631379-8f28aa81-b03d-44f5-9f43-b357d3090b51.jpg)

Below is only the first object hit as ok with some Greats hit midway resetting the pp back to 0 in the process.
![osu_2021-11-07_13-29-55](https://user-images.githubusercontent.com/37494321/140631395-ffe4a612-54d5-4017-a815-0d4af522e50f.jpg)

Below is just first object hit as ok
![osu_2021-11-07_13-30-55](https://user-images.githubusercontent.com/37494321/140631399-842a733c-4be2-45a9-9184-2da78481485a.jpg)


To test the claim that it only works with sliders, this is also tested on a map with no sliders with only first object hit as ok
![osu_2021-11-07_13-18-22](https://user-images.githubusercontent.com/37494321/140631410-bfa6a2b4-e2d7-4f8d-8d00-3180aad153a7.jpg)
