### ISSUE TITLE
Linux support 

### ISSUE THREAD

**Issue by CoolGuy12490** [ppy/osu#15504]
I am using ubuntu and wine and it would be cool if I didnt need to use wine to play osu stable
its also not very much an issue but its a suggestion

**Comment by mcendu** [comment]
Linux is supported by lazer. Please report issues for stable in ppy/osu-stable-issues.

 

From: CoolGuy12490 ***@***.***> 
Sent: Sunday, November 7, 2021 7:30 AM
To: ppy/osu ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ppy/osu] Linux support (Issue #15504)

 

I am using ubuntu and wine and it would be cool if I didnt need to use wine to play osu stable

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub <https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fppy%2Fosu%2Fissues%2F15504&data=04%7C01%7C%7Ca69dafeb7bd84084776408d9a17d4b35%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637718381768776392%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1an1fPsACUtE%2FdDNd5Pien2A6c%2FWKhpZA9DFmAmMp6U%3D&reserved=0> , or unsubscribe <https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKM6DA7MGR7766DOBTNRNK3UKXB65ANCNFSM5HQDX7NQ&data=04%7C01%7C%7Ca69dafeb7bd84084776408d9a17d4b35%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637718381768786349%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wrPx0K6AE3UN5IIYPg42K2CyIK5uLSSIxs42EAhR1ik%3D&reserved=0> .
Triage notifications on the go with GitHub Mobile for iOS <https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca69dafeb7bd84084776408d9a17d4b35%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637718381768786349%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zHi7SMEXNsPs%2BEHaoWH2yVaFCnB6AOn63AuhBeZwx8o%3D&reserved=0>  or Android <https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca69dafeb7bd84084776408d9a17d4b35%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637718381768796307%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=e2P3bW6sFQOq7h2xX7LCFkIfO%2Fd%2FdciN8WuMfTjUgaQ%3D&reserved=0> .  <https://github.com/notifications/beacon/AKM6DA5KAEYPF7DSDJ6KMMDUKXB65A5CNFSM5HQDX7N2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4PTCEKOQ.gif>
