### ISSUE TITLE
Backtick doesn't show in key combination

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#15532]
### Discussed in https://github.com/ppy/osu/discussions/15524

<div type='discussions-op-text'>

<sup>Originally posted by **Susko3** November  8, 2021</sup>
This is entirely due to font, works properly if using default font. Not sure why fallback isn't working.

![image](https://user-images.githubusercontent.com/16479013/140747112-b48fad80-43a1-4dc5-b6df-1e5c145f5787.png)
</div>

**Comment by peppy** [comment]
Given that this is a default key in the game, I'm gonna bump this up to p0 as it displays nothing currently.

**Comment by bdach** [comment]
This looks to be caused by an incorrectly-exported spritesheet or a conversion error in bmfont.

![2021-11-09-113756_2532x1023_scrot](https://user-images.githubusercontent.com/20418176/140909161-2ab4cc37-7b98-4e5f-8c30-48da85a2310c.png)

The selected area on the left is a semi-transparent 10x1 rectangle that bmfont claims to correspond to the backtick character.

I guess a way to fix would be to re-export the font with that backtick character excluded and allow fallback to work.

**Comment by peppy** [comment]
Looks like it may have failed in the exporter we use due to its relative positioning to the other characters in the font. We might have to manually fix the font file or use something non-bmfont to get around this..

![20211109 194451 (Adobe Photoshop 2021)](https://user-images.githubusercontent.com/191335/140910381-4c48b132-106f-4e82-bf92-c9b156d21d85.png)
