### ISSUE TITLE
BeatmapDetails' updateStatistics is slow

### ISSUE THREAD

**Issue by peppy** [ppy/osu#1555]
This method is currently synchronously accessing the beatmap and causing non-asynchronous text revalidation.

- Beatmap needs to be accessed asynchronously (probably using https://github.com/ppy/osu/pull/1556).
- Text needs to be updated asynchronously via a yet-to-be-implemented method. Alternatively, the text pieces should be replaced with a drawable container that is loaded using `LoadComponentAsync`.

**Comment by FreezyLemon** [comment]
Loading the new metadata text is doable.. Just create a new Drawable with all the new information, load it with `LoadComponentAsync` and then add it.

But this is not as easy with the metrics (ratings, fails/retries) and the AdvancedStats.
If any of these are replaced by new instances with the new information, they do not animate properly (since the new object instances have no information about the previous information, but the old instances cannot be reused since they have already loaded). 
Does anyone have an idea on how to do this?

**Comment by peppy** [comment]
Those other components are not affected, as the performance overhead is from updating the text (loading of new textures etc.).

**Comment by FreezyLemon** [comment]
So only loading the new metadata info async is what you meant by this issue?

**Comment by peppy** [comment]
That's the second point I brought up in the issue. The first one still stands (beatmap needs to be accessed asynchronously).

**Comment by FreezyLemon** [comment]
Oh, yeah. I meant something else though.. in the second point, are you only addressing the updates of `MetadataSection`s? (aka the text for description source and tags)

**Comment by peppy** [comment]
text specifically, yes

**Comment by peppy** [comment]
Closed by #1601.
