### ISSUE TITLE
Unable to hide beatmaps again after "Restore recently hidden beatmaps"

### ISSUE THREAD

**Issue by FreezyLemon** [ppy/osu#1562]
When hiding one or more difficulties and then restoring them again with the "restore all recently hidden beatmaps" button in the settings menu, you become unable to hide these difficulties again until you restart.

I have also encountered some very rare crashes that I can not reproduce. They seem to occur when spamming the button right after hiding a difficulty.

(Note: I previously said that "the song select menu did not update when restoring a hidden diff". This was my fault, as this does not happen in the Release build, only in the Debug build. Sorry for that).

Should be fixed before #1215 is implemented, since both buttons will suffer from this.

**Comment by PoULkY** [comment]
More info : Found anomaly in Restore function (BeatmapStore.cs:103)

First, i want to tell that there is 2 methods for restore song difficulties that has been hiding.
- By context menu (right click) in song (not difficulties) and choose "Restore all hidden" (let's say this is method A)
- By button in settings menu : "Restore all hidden difficulties" (and this is method B)

When i using method A, it shows. Hide and show multiple times using this method is fine.
But when i restore using method B, i can't hide it anymore (let's called this "broken difficulties").

Now, when you trying to hide **ANOTHER** (not the same one) difficulties in same song and restore it using method A, you can hide that "broken difficulties" again.

I think maybe database not updated when hiding/restoring in method B. But when i check it, it is updated.
And this 2 methods are using same method : Restore() function. So i think this is weird.

After debug i found that when using method B, hidden flag (beatmap.Hidden) in BeatmapInfo is become true. And when i check again, it shows that before executing Refresh() method, hidden flag is false.
![image](https://user-images.githubusercontent.com/15938103/33142867-73168a7a-cfea-11e7-8167-cf5371c4c204.png)

So i think, there is 2 possibilities for this issue : 
1. When using method B, all song that has been hide will be shown and get some kind of "mark", so hidden flag is become true. And method A is cleaning that "mark" (but i don't see any code like that, or maybe i'm not looking thoroughly)
2. There is problem in EntityFramework. Maybe when perform restore, something wrong is happen in EF.

And because i don't understand about EF, i can't proceed anymore, sorry.
Hope this info helps.

**Comment by Aergwyn** [comment]
Not sure if this will be helpful.
Debugging showed that the `Trace.Assert()` in `BeatmapCarousel.Update()` method fails (line 550). When restoring with said button `yPositions` have a random value that is not equal to `panels`.

At this point I'm not sure why this happens but it seems to desync game from the database.
Hidden beatmaps do reappear but the database doesn't get updated. So if you wan't to hide again the `BeatmapStore.Hide()` returns early because the `Refresh(ref beatmap, Beatmaps)` updates the Hidden flag with the database one (which is still true).

Hiding another difficulty and using the working restore syncs game and database again.
