### ISSUE TITLE
Displayed PP at results screen is always 0

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#15700]
Although the in-game counter shows the expected PP, the results screen always shows 0.

It seems like it should be non-0 according to the following code:
https://github.com/ppy/osu/blob/b1fcb840a9ff4d866aac262ace7f54fa88b5e0ce/osu.Game/Screens/Ranking/Expanded/Statistics/PerformanceStatistic.cs#L33-L41

Possibly related to https://github.com/ppy/osu/issues/15699, if difficulty is being calculated such that it's 0*.

**Comment by bdach** [comment]
I've just tried the two simplest possible scenarios I could think of in order to reproduce this (playing back a pre-recorded replay and manual gameplay) and could not reproduce this. Both times I got a non-zero number.

I could imagine this could have something to do with the difficulty cache getting into a broken state.

**Comment by Stunnerr** [comment]
I still have 0 pp in my scores, Arch Linux, tested on 2021.1211.0 and a3b8109 git version, all scores are 0pp
