### ISSUE TITLE
Beatmap background missing behind storyboard on some maps in multiplayer spectator

### ISSUE THREAD

**Issue by bdach** [ppy/osu#15827]
### Discussed in https://github.com/ppy/osu/discussions/15826

<div type='discussions-op-text'>

<sup>Originally posted by **Muffyn** November 26, 2021</sup>
Many storyboards assume the background will be a black screen as it automatically is everywhere else. Multiplayer spectate does not render a black screen behind the storyboard, which can look bad and cause multiple users' gameplays to overlap.
I think the black screen should always be rendered behind multiplayer spectate windows.

https://streamable.com/8q9fyx

Example map:
https://osu.ppy.sh/beatmapsets/694402#osu/1501410</div>

The screen shouldn't even be "black", each player instance should have the scaled-down beatmap background behind it rather than the generic default background asset in order to look properly.

**Comment by Wieku** [comment]
But the point of original discussion is that storyboard expects background to be black (which sort-of happens when beatmap background is referenced in any way in storyboard's script), not to see map's background (which on some heavy storyboarded maps could scream "use storyboard" like in https://osu.ppy.sh/beatmapsets/756794#osu/1605148 ) which can potentially break that storyboard.

**Comment by bdach** [comment]
I'd say that depends on whether the spectating user has storyboards enabled or not.

**Comment by peppy** [comment]
That logic of "black of background" is already handled in the player itself, and would need to be considered when making a change here.

A good temporary solution would be to dim the main background down to a lower level. Right now it is a visual distraction anyway.

**Comment by bdach** [comment]
This was fixed in #24443
