### ISSUE TITLE
Approach circles are left behind when rewinding replay

### ISSUE THREAD

**Issue by peppy** [ppy/osu#1591]
![image](https://user-images.githubusercontent.com/191335/33234290-79663d06-d267-11e7-88d6-bbde16db19b7.png)

**Comment by Aergwyn** [comment]
I can't reproduce this. No amount of rewinding ever leaves something behind. Does this still happen for you?

**Comment by peppy** [comment]
At very least, it should still be visible in the editor when seeking forwards.

**Comment by Aergwyn** [comment]
Ah yes. In editor it happens when going in both directions. It looks like that jumping (not dragging) seems to immediately jump to a point in time (which does not happen in a normal replay where it's kinda a fast forward / quick rewind).
As ApproachCircles are independent from their DrawableHitCircle they seem to be left where they stopped as they don't get updated anymore.
I'll see if I get more time later to get to the core of this.

**Comment by smoogipoo** [comment]
I'll give you a pointer in the right direction - hitobjects are expiring but their approach circles aren't. So the sequence is:
1. Hitobject becomes alive
2. Hitobject expires (fastforward or rewind beyond the lifetime of the hitobject)
3. Hitobject stops updating (esp. stops updating approach circles).
4. Approach circles remain alive, are proxied outside of the hitobject where they're drawn somewhere on the playfield. This works because the approach circles are still alive.

**Comment by Aergwyn** [comment]
Some things confuse me. My understanding of how drawables work / are processed is not that deep.
I already touched the logic how `DrawableOsuHitObject`s work for the HD mod and I looked there to test a few things. There I can easily prevent lone ApproachCircles when going back BUT not forward.

So that brings up several questions for me:
1) Why can I expire HitCircles but not ApproachCircles? If I do the latter they are gone for good. The HitCircles are not. Why are ApproachCircles dead when InitialCircles of Sliders are not?
2) As mentioned before I could prevent lone ApproachCircles when going back. So somehow that works when we go beyond the starting time of the HitObject but not beyond the ending time of the HitObject.
I'm not sure why it's only working in one direction.
![qq](https://user-images.githubusercontent.com/27222621/33806046-4f314948-ddc2-11e7-990b-d41cf9db8096.png)
Could it be the `base.ClearTransformsAfter(transformTime, true);` in `DrawableOsuHitObject` that is responsible for this? So it tries to fade out but the `ClearTransformsAfter` gets rid of it and it just stops?

**Comment by smoogipoo** [comment]
This is issue spans a large portion of the game (alive states, transforms, ispresent checks, replays,...), just a forewarning that this isn't a straightforward fix.

Here's a quick run down (consider auto replays):
1. Replays define important frames, which occur while buttons are pressed. You can think of these as being game frames guaranteed to be run at the hitobject's start time.

2. Because an important frame is run on the hitobject's start time while seeking, its state will be updated to an idle/hit/miss, and UpdateState is likewise guaranteed to be called.

3. UpdateState attempts to ensure that the current state of a hitobject has been fully applied before beginning a transition to a new state. This is done through ApplyTransformsAt.

I believe this is where the issue occurs, there are a few cases to think about:

1. If State = Idle and Alive = true, if then rewound before the alive start time of the hitobject, State isn't going to be updated because there is no important frame before State = Hit. When this happens we are relying solely on transforms being updated to be rewound, and this isn't going to happen if the hitobject's IsAlive = false.

2. If there is a hitobject within the alive start time of the one in #1, then the hitobject in #1 will get updated once more, since there will be an important frame that the game will be forced to update on.

3. It is possible that #2 still may not work correctly, as IsPresent = false will also block children from updating (even if IsAlive = true). This can happen if the hitobject has been determined to be close enough to transparent.

4. The same interactions occur from the hitobject's important frame and fforwarding beyond the alive end time of the hitobject.

5. The editor does none of this, so I suggest not worrying about it right now.

I don't know how to fix this off the top of my head, there are quite a lot of interactions going on.

**Comment by Aergwyn** [comment]
As already stated in Discord yesterday I'm not going to continue looking into this for one and a half reasons:
a) This is going beyond my current knowledge and would take an eternity
*b) Editor ist still WIP anyways*

**Comment by Aergwyn** [comment]
Just a random thought while I'm brooding over the sequences for HitObjects for Hidden.
DrawableHitCircle expire themselves after a certain amount of time when only `ArmedState.Idle` was ever triggered. But when `ArmedState.Hit` or `ArmedState.Miss` are triggered they handle themselves AND the ApproachCircle.
It's just a random idea that I have to test once I'm home but may this be caused by `Hit` or `Miss` never being triggered and `Idle` not doing anything to ApproachCircles?

I mean. If you jump past the lifetime of an object it has to update itself to know that it should disappear. Does this go through the same logic?

**Comment by peppy** [comment]
This is to do with the `ProxyDrawable` usage; I believe @smoogipoo is currently looking into it.

**Comment by peppy** [comment]
Can reproduce easily by adding a `Thread.Sleep` after `decoupledClock.Start();` in `Player.cs`
