### ISSUE TITLE
ModButton tooltips are broken

### ISSUE THREAD

**Issue by peppy** [ppy/osu#1604]
It looks like there are two tooltips assigned to `ModButtons`, likely due to their inheritance of `ModIcon`. The description is being hidden when hovering the icon directly:

https://streamable.com/gos0i

**Comment by PoULkY** [comment]
I change `TooltipText` assign into `mod.Description` instead of `mod.Name`. So when the icon is hovered, it shows the descriptions of the mod.

![image](https://user-images.githubusercontent.com/15938103/33273593-55f71372-d3c0-11e7-9c00-2fb811f641a6.png)

![4](https://user-images.githubusercontent.com/15938103/33273664-8dc95972-d3c0-11e7-8392-460015654a79.png)

Is it OK ?

**Comment by peppy** [comment]
No, that changes the because of ModIcons.

**Comment by peppy** [comment]
Closed by #1669
