### ISSUE TITLE
Going back from spectating deactivates the spectate state

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#16096]
It was done this way to reset the button's state if they want to start spectating again. But it may be possible to ensure the room isn't currently in gameplay before doing so.

### Discussed in https://github.com/ppy/osu/discussions/16093

<div type='discussions-op-text'>

<sup>Originally posted by **Theighlin** December 15, 2021</sup>
As per title, I don't think it should do that as it's annoying to turn it on if you want to spectate multiple matches.

https://user-images.githubusercontent.com/53081750/146144178-e5e65d15-eff8-4e6b-9e8f-fdc60d0ab150.mp4

</div>

**Comment by peppy** [comment]
I think this was left this way because it's.. broken at several other levels. Like it never reaches results and never automatically returns to the lobby.

But I guess I wouldn't be against leaving the user in spectator state on returning. Not sure how that will handle if the users are already in another match, might get pretty weird.
