### ISSUE TITLE
Update game resources with twemoji flags to match osu-web

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#16422]
### Discussed in https://github.com/ppy/osu/discussions/16418

<div type='discussions-op-text'>

<sup>Originally posted by **zachmanthethird** January 12, 2022</sup>
When creating bracket.json files for multiple taiko tournaments, I noticed the flags shown didn't match the flags seen on osu!web.
My best guess is lazer hasn't implemented twemoji flags whereas web has (osu-web#7875 / osu-wiki#6262)
![image](https://user-images.githubusercontent.com/74262407/149021216-5dbb26b1-c789-4352-8019-7fc998f8dcdc.png)

Edit: I realize this is similar to #15182 but I'm unsure how closely related the tournament client would be to the regular lazer client.</div>

**Comment by whtann** [comment]
Hello, I'm a Senior at Clemson University and I'm trying to get into contributing to open source projects.  I was looking for interesting repos to contribute to, and I really wanted to help contribute to osu.  I've read your guidelines for contributing and I was looking for issues that have the label good-first-issue, but the only one still open seemed to already have a merge request.  This issue, however, seems like it might be a good starting point for me.  Please let me know if it would be a good starting point and if so could I be assigned to this issue.

**Comment by bdach** [comment]
@whtann not sure i would recommend taking this on. twemoji flags are svg and need rasterising before they can be used in the game, and sizings of all flag usages across the game and the tournament client need to be updated, because twemoji assets have a different aspect ratio. i do have a script prepared for the first part, but the second part needs careful work still.

also as a matter of principle, due to previous experiences, we don't really assign issues to users who aren't established contributors yet.

**Comment by whtann** [comment]
@bdach ok that's fine.  Do you have any thoughts on what might be a good first issue to tackle then since it seems the label hasn't been used in a while?

**Comment by bdach** [comment]
honestly, i don't, sorry. the problem with that label is that in order to mark a label as a good first issue i have to know in advance it's easy enough which most of the time isn't obvious and i would have to go and actually try to resolve it to know. you can even see that on the only other open "good first issue" which has a PR which got stuck due to implementation complexity. i don't have the bandwidth to check every issue for being a potential good first issue so pretty much the only time i personally apply that label is on obvious one line changes which don't occur too often.
