### ISSUE TITLE
Per-hitobject "Slider Velocity" gets ignored during osu!taiko and osu!catch beatmap encoding

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#16433]
Originally reported in https://www.twitlonger.com/show/n_1sru7be.

Apparently, any velocity set to an osu!taiko drum roll or osu!catch juice stream will be ignored when encoding and saving the beatmap back.

This goes down to [`LegacyBeatmapEncoder.handleControlPoints()`](https://github.com/ppy/osu/blob/692e846acdbb188666e3a0cb2891337f0164a396/osu.Game/Beatmaps/Formats/LegacyBeatmapEncoder.cs#L168-L287), which would ignore the `DifficultyControlPoint`s of any non-osu! hitobject, and instead rely on the `ScrollSpeed` provided by the `EffectControlPoint`.

I'm not 100% sure on the direction forward and whether `TimingControlPoint` should eventually be per-object as well, but if it shouldn't, then we may want these rulesets to allow encoding the `DifficultyControlPoint.SliderVelocity` value, by multiplying it with the `EffectControlPoint.ScrollSpeed` per difficulty point.

https://user-images.githubusercontent.com/22781491/149146279-50716c7b-f096-4ac0-b43d-d356cac40ded.mp4

**Comment by bdach** [comment]
I'm pretty sure this is just the editor writing to the wrong place? As far as I'm aware for scrolling rulesets scroll speed on effect points was supposed to replace/supersede slider velocity?

**Comment by frenzibyte** [comment]
That's what I had in mind at first, but then "scroll speed" is meant to be a global playfield value change rather than per-object IIRC, unless osu!taiko and osu!catch objects shouldn't have had the per-object velocity piece visible to begin with.

**Comment by bdach** [comment]
In taiko you can probably make per-object velocity because that already uses the overlapping algorithm, but if per-object velocity is to be added then _all_ rulesets would have to use the overlapping algorithm, I think?

Assume that the scroll length is 500ms in time units. Say you're at time 0, and there are two incoming objects: one with start time of 500 and a 1x multiplier, and one with a start time of 1000 and a 0.5x speed multiplier. This means that they would both have to appear on screen at the same time, because one of them moves twice slower and so it needs to already appear at time 0 to cover that distance. Which would be classic overlapping behaviour.

I don't even want to think about mania as potential per-column scroll speeds sound like they would be brain-breaking.

**Comment by zachmanthethird** [comment]
For all it's worth, I mentioned this in #15808, which prompted the taiko per-object velocity UI to be hidden. However, it still has unintended side effects, mainly that per-object points have a minimum of 0.1 while global points have a minimum of 0.01, still causing issues with converts in the current version. From what I can tell, the same appears true for mania.

**Comment by bdach** [comment]
I forgot that this was already hidden for taiko. Then I suppose the other scrolling rulesets should have that turned off.

As for the control point limits that has been brought up several times, like in https://github.com/ppy/osu/discussions/14835. Maybe it's time to decrease the lower bound to 0.01x because it's been mentioned so many times already.

**Comment by smoogipoo** [comment]
I agree with decreasing the lower bound to 0.01x.

**Comment by peppy** [comment]
It's going to have to be done for compatibility reasons as I'm pretty sure there's ranked maps using these extents.
