### ISSUE TITLE
Slow scroll speed causes hitobjects to "load in" on the playfield

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#16440]
This is also the case in mania at low user scroll speeds.

### Discussed in https://github.com/ppy/osu/discussions/16439

<div type='discussions-op-text'>

<sup>Originally posted by **zachmanthethird** January 13, 2022</sup>
I've been searching for a long time for a ranked map that displays this behavior, and I've finally found one: https://osu.ppy.sh/b/2862238:

https://user-images.githubusercontent.com/74262407/149232391-75546f0c-ee46-4f65-9463-a404512a297b.mp4

The notes in the kiai section load onto the playfield due to their scroll speed. The lowest seen is 0.14x 110BPM which doesn't even hit the old minimum of 0.1x let alone the new 0.01x minimum.
Additionally, this behavior can be easily observed in some slower scroll speed taiko maps when applying Difficulty Adjust with 0.25 scroll speed (this example uses https://osu.ppy.sh/b/1803863):

https://user-images.githubusercontent.com/74262407/149234860-7e46df80-129b-4f57-a183-946bad18532b.mp4

Version 2022.108.0</div>

**Comment by bdach** [comment]
The reason why this is happening is very simple:

https://github.com/ppy/osu/blob/4ca2822d409ff8b4b17213f9ef1c2916d8fdd706/osu.Game/Rulesets/Objects/HitObjectLifetimeEntry.cs#L92

The current default assumption is that an object won't start showing on screen sooner than 10s before its end time. The linked taiko maps, as well as very slow scroll speeds, violate that assumption.

The big question is what to do about it. This was only ever added for scrolling rulesets because it wasn't very easily possible to calculate the exact lifetime start without knowing how big in size the object is. Blanket increasing this number will cause performance regressions.

I'm not sure I have any good answers that won't increase complexity in some respect.

**Comment by smoogipoo** [comment]
We should use an approximate size of hitobjects as per @ekrctb's PR from a while back.

**Comment by ekrctb** [comment]
I agree #12959 's approach can be used.
