### ISSUE TITLE
Crash on restoring hidden beatmaps

### ISSUE THREAD

**Issue by peppy** [ppy/osu#1645]
1. Hide last beatmap from song select (so all are hidden)
2, Return to main menu
3. Click "Restore all hidden difficulties" in settings

![image](https://user-images.githubusercontent.com/191335/33510728-2908a7e0-d753-11e7-9ee9-7bbef2b49bfd.png)

**Comment by Aergwyn** [comment]
I looked into this last evening.

Because we now allow to continue in this method when group is null we reach this point. While this NullReference is easily (?) fixed there creeps up something else afterwards.

The `Trace.Assert()` in BeatmapCarousel.Update() fails because apparently there are 0 `panels` while `yPosition` says there are 4 things.

So `yPosition` is aware of the restored panels before the `panels` themselves?

Debugging shows that `computeYPositions()` is called first. Afterwards it knows that there are 4 panels that will show up but then `Update()` runs while the list of `panels` is still empty.

**Comment by Aergwyn** [comment]
I digged a bit more. Went to one release prior to see if I broke it. It didn't crash but restoring from main menu also didn't seem to work correctly.

The event chain after restoring goes from `BeatmapStore` ->`BeatmapManager` -> `SongSelect`.
`SongSelect` says `Schedule(() => carousel.UpdateBeatmap(b)` but `UpdateBeatmap(b)` never gets called.

![qq](https://user-images.githubusercontent.com/27222621/33514016-a9305fa0-d74c-11e7-94ee-add4a650db35.png)

It works from `SongSelect` itself but never from `MainMenu`
