### ISSUE TITLE
Mod select design refresh

### ISSUE THREAD

**Issue by bdach** [ppy/osu#16917]
Reference designs: https://www.figma.com/file/NkdREXr6wFkA99oLw8PnBv/Client%2FMod-Selection?node-id=0%3A1

I've started work on this.

**Comment by thecakeu** [comment]
The new UI in the background looks insanely good! Wouldn't it be alot of work to remake the whole UI before a reskinner is implemented though?

**Comment by peppy** [comment]
> The new UI in the background looks insanely good! Wouldn't it be alot of work to remake the whole UI before a reskinner is implemented though?

I don’t know how to respond to this. Skinning support is available for the gameplay which should show that we have “reskinner”. on your words. Skin support for the menus is out is scope for now and not a current focus.

**Comment by thecakeu** [comment]
> > The new UI in the background looks insanely good! Wouldn't it be alot of work to remake the whole UI before a reskinner is implemented though?
> 
> I don’t know how to respond to this. Skinning support is available for the gameplay which should show that we have “reskinner” in your words. Skin support for the menus is out is scope for now and not a current focus.

I meant a menu reskinner, yeah; i know that you can reskin the in-game HUD.
What i was asking is if bdach actually planned on also reskinning/remaking the menu UI like in his reference designs.

**Comment by bdach** [comment]
> What i was asking is if bdach actually planned on also reskinning/remaking the menu UI like in his reference designs.

I'm not interested in discussing that in any capacity until mod select is done.

**Comment by TheFantasticLoki** [comment]
Very good work but I think the mod select window should move upwards when the customize window shows. Not married to the idea but I think it makes sense and will work well.

**Comment by TheFantasticLoki** [comment]
> Very good work but I think the mod select window should move upwards when the customize window shows. Not married to the idea but I think it makes sense and will work well.

Or another idea would be to allow the items to scroll farther down when the customize window is visible so the last mod in each section would show just above the customize window

**Comment by bdach** [comment]
@TheFantasticLoki yes i'm aware. it's one of the parts i need to actively figure out still. i've tried a few obvious resolutions but they all had shortcomings.

please hold the feedback for now until i'm anywhere near done. right now it's mostly noise.

**Comment by bdach** [comment]
Not much progress was made this week, pieces are slowly being PR'd, and I've been downsizing all components to match intended figma dimensions better - but I have a decently sized queue of components and also think I've figured out a good way to integrate the mod settings panel into the general design (with the help of stream):

https://user-images.githubusercontent.com/20418176/156938627-2e9ca97a-714c-46bd-8a65-1876f2dbd040.mp4

Will try to PR these piece by piece over the coming week.

**Comment by bdach** [comment]
So I'm going to ask for advice here, because there's a bit of a problem (obviously, when aren't there problems) and I don't want to stray off on a bad path too much.

I've got [a branch here](https://github.com/ppy/osu/compare/master...bdach:mod-overlay/integration?expand=1) that finally replaces the old design with the new and it appears to work in light manual testing:

https://user-images.githubusercontent.com/20418176/166822228-814bc7f1-4076-43cf-985e-0e8d42f8c3af.mp4

The problem is, as I have it, screens now depend on `OsuGame` show the mod overlays correctly and therefore mod overlays don't work in tests that aren't full `OsuGame` tests anymore:

https://user-images.githubusercontent.com/20418176/166822455-3fece230-5f76-4c7d-9376-af0a6500f0de.mp4

There are 2 reasons why I introduced a dependency on `OsuGame`:

* The old overlay was added as a child of `SongSelect` and didn't dim anything. This doesn't work if you want to have a full-screen overlay that uses `DimMainContent => true`. And that is because if you set that, the overlay will dim the background screen, but if it is a *child* of said background screen, it will end up dimming *itself* in the process, too (check out [this particular commit](https://github.com/ppy/osu/commit/c8892239694a4696027a3ce13c89febdc862c2c8) for a demonstration of this).
* `SongSelect` shows a back button. The back button is managed at an `OsuGame` level. I want to be able to show the overlay in front of the back button. I cannot do this from within the screen, as the back button is not even in the screen stack, it's in front of it in `OsuGame`.

So my options are either to:
1. PR this as is, and deal with broken tests.
2. Try to reimplement screen dimming inside of `SongSelect` and somehow hack around the back button.
3. ??? (suggestions welcome here)

Option 1 can be *slightly* improved by adding test-exclusive code paths that add the overlays locally to the screens without dim, but it's a bit jank:

https://user-images.githubusercontent.com/20418176/166823214-166595b1-9d42-4041-92e8-864bbc7e733d.mp4

**Comment by peppy** [comment]
As expected, integrating this with song select is going to be an interesting one as nowhere in @arflyte's design has he shown how this should be done. There are a lot of remaining questions, like how the footer should behave such that the mod overlay can still be dismissed by the button clicked to enter it. Or what happens to the back button. Or how to address the fact this this looks like a clash between 8 different design patterns to the point I'm not sure what users are going to say when it's added. Or that the design of the mod select overlay has already changed in the designs on figma.

![osu! 2022-05-05 at 05 40 18](https://user-images.githubusercontent.com/191335/166868529-bea78a27-0f73-41ce-84f5-2cba2a87ce44.png)

Part of this is due to the old and new designs being next to each other, but the other part is that there is nowhere in any of figma that I can find which shows how individual pieces are supposed to work together. ie. how can the toolbar at the top coexist with the overlay? is the bottom footer supposed to be global rather than per-screen?

Rants aside, I think your path of making `OsuGame` a dependency is alright. An improvement may be moving the `RegisterBlockingOverlay` to an interface and implementing that in `TestOsuGameBase`. Definitely don't implement dim locally, though. If anything we want to move more of these concepts globally rather than local.

**Comment by arflyte** [comment]
I’ll write an explainer in the Figma file

**Comment by bdach** [comment]
> like how the footer should behave such that the mod overlay can still be dismissed by the button clicked to enter it

I've mentioned this offhand before, but I find that the behaviour on figma makes zero sense to me. There is no reason why the song select footer buttons should be visible on the mod screen. Imagine clicking "random" on the mod screen - the beatmap would be randomised in the background but the mod select overlay itself wouldn't really change.

> the design of the mod select overlay has already changed in the designs on figma

I was tangentially aware of this but ignored that for the time being. The one major difference between design and implementation as-is, is how the customisation area is presented - do you think it is best that I implement that first?

**Comment by peppy** [comment]
> Imagine clicking "random" on the mod screen - the beatmap would be randomised in the background but the mod select overlay itself wouldn't really change.

I agree on this, but would also hope that the "mod" button is clickable to exit the screen, in the same place it was clicked to enter it. Being able to quickly toggle the overlay using mouse like this just feels good.

> is how the customisation area is presented - do you think it is best that I implement that first?

Definitely not, because it'll probably change again while you're doing so. I was more focused on the header though, which is detached in the newer version (which may fit better when adjacent to the top toolbar?)
