### ISSUE TITLE
Beatmap carousel refreshes current beatmap when beatmap offset is changed

### ISSUE THREAD

**Issue by peppy** [ppy/osu#17142]
I noticed this while implementing and left it because it doesn't harm anything, but it's also probably something we want to avoid. Or maybe not? Will need to investigate whether the editor flow is relying on this, for instance.

See https://github.com/realm/realm-dotnet/issues/2833#issuecomment-1059014784 for a bit of related discussion as to why this occurs.

**Comment by peppy** [comment]
As I suspected, this flow is used by the editor save flow to actually update the carousel to a sane state. Removing...

https://github.com/ppy/osu/blob/eb25730b614ececc5f6672e298dc5e786984c92e/osu.Game/Screens/Select/BeatmapCarousel.cs#L257-L258

...fixes the issue at hand here, but will cause the title and other metadata to not be refreshed after exiting the editor.

From this perspective, I'm not too sure how to handle this more correctly. I think for now having the beatmap refresh at such a high level isn't a bad thing (as it ensures all song select components are up-to-date), but it does look a bit weird, especially as it may trigger things like a leaderboard refresh.

Interested in more thoughts regarding this. Maybe something to bump down to a lower priority and fix by handling bindings closer to each component?

**Comment by bdach** [comment]
I mean the detach there is not giving many options. Either it must be there and therefore the carousel has to know whether to respond to an `UpdateBeatmapSet()` with a reload (yes if coming from editor, no if offset changed), or all components need to be using non-detached entities and checking which properties were actually changed in order to update properly. I assume refresh wouldn't raise property changed events for metadata stuff on offset change so it'd work.

I guess you could half-ass it by manually comparing the property values before/after on the detached object but that seems like the worst of both worlds and reinventing what realm is supposed to provide out of the box anyway.
