### ISSUE TITLE
skin editor does not allow to interact with the game

### ISSUE THREAD

**Issue by IsGris** [ppy/osu#17584]
### Type

Other

### Bug description

if you exit the skin editor while it's playing a beatmap you won't be able to interact with the game

### Screenshots or videos

https://user-images.githubusercontent.com/83012795/161166099-5c95cb44-7a00-47d7-85bc-939e7f3a1290.mp4

### Version

2022.327.0

### Logs

[database.log](https://github.com/ppy/osu/files/8393620/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/8393621/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/8393622/network.log)
[performance.log](https://github.com/ppy/osu/files/8393623/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8393624/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8393625/updater.log)

**Comment by CenTdemeern1** [comment]
There might be more to this than just not being able to interact with the game- 2 out of 3 of my attempts to reproduce this crashed the game.

**Comment by CenTdemeern1** [comment]
Exiting the editor with the escape button does not seem to yield any of these effects...?
Also, you can get out of the "softlock" by opening the skin editor again (open the settings with ctrl+o, maybe click export skin because the first time the skin editor button didn't seem to work?) and exit using escape.
When it doesn't crash the game, that is.

**Comment by peppy** [comment]
Duplicate, already fixed, don't use the exit option from menu for now.
