### ISSUE TITLE
Maps failing to load

### ISSUE THREAD

**Issue by Pearoo-XD** [ppy/osu#17738]
### Type

Game behaviour

### Bug description

I tried to play Lagtrain (Sagu), but it didn't load the map and gave me an error.
![unknown](https://user-images.githubusercontent.com/63553775/162572832-14ac0280-bc08-4d05-a7f5-158e18cef249.png)

I've noticed an update stopped in the background for some reason, so I restarted the client because I thought it was the update interfering with the files (I couldn't cancel it).
![unknown](https://user-images.githubusercontent.com/63553775/162572882-e9092ffa-1921-4eba-925d-91d2b1e21307.png)
![unknown](https://user-images.githubusercontent.com/63553775/162572889-4b3b291f-cd13-4b31-af5c-9dc1689983eb.png)
It didn't fix it.

A simple reinstall helped, but at the uninstall section of Windows, I noticed something: Classic and Lazer are the same in the app selection, which might cause confusion.
![unknown](https://user-images.githubusercontent.com/63553775/162572933-be718164-0e12-456b-b761-592b31ef080b.png)

### Version

osu! 2022.409.0-lazer

### Logs

Because I uninstalled the client, the logs are gone.

**Comment by bdach** [comment]
please link the map that is failing to import, at least. without either that or the logs, we cannot do anything about this report.

**Comment by CenTdemeern1** [comment]
> please link the map that is failing to import

[I found it through a simple Google search.](https://osu.ppy.sh/beatmapsets/1222543)

**Comment by bdach** [comment]
just checked the map linked above and it imports fine here. so unless there is any new information about the circumstances of this i don't think there's much more to do here.

@CenTdemeern1 as for your "simple google search" remark: just for your information, it has been the case several times at this point that these sorts of issues didn't happen when the map was downloaded from the website/beatmap listing overlay, because the map was imported from the local stable installation/was an older version/was a "practice difficulty", etc. which is the primary reason why i asked.

**Comment by Pearoo-XD** [comment]
> please link the map that is failing to import, at least. without either that or the logs, we cannot do anything about this report.

every map failed in my downloaded maps list

**Comment by bdach** [comment]
I'm just going to go ahead and close this due to a lack of actionable information here. If this happens again, please post a comment to this issue - with logs this time - and we'll reopen.
