### ISSUE TITLE
Incorrect slider follow circle size in editor with beatmap skins enabled

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#17745]
### Type

Game behaviour

### Bug description

With beatmap skins enabled, the follow circle is massive in the editor compared to gameplay.

Can be reproed via https://osu.ppy.sh/beatmapsets/18428#osu/101850

### Screenshots or videos

Gameplay:
![image](https://user-images.githubusercontent.com/1329837/162578733-8fe3d2e9-3c62-432b-9772-094888c4c980.png)

Editor with beatmap skins enabled:
![image](https://user-images.githubusercontent.com/1329837/162578995-ab17497c-56a2-413e-a00b-a656d78a4945.png)

Editor without beatmap skins enabled:
![image](https://user-images.githubusercontent.com/1329837/162578978-0f111d59-6894-4491-a0c6-d8cdc0717579.png)

### Version

f2e67d00ccc7cb86abcfedc7b5075b323cd83de0

### Logs

[database.log](https://github.com/ppy/osu/files/8457146/database.log)
[network.log](https://github.com/ppy/osu/files/8457148/network.log)
[performance.log](https://github.com/ppy/osu/files/8457149/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/8457150/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/8457151/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/8457152/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/8457154/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/8457155/runtime.log)

**Comment by toodols** [comment]
After doing a lot of testing, i have no idea what is going on. .osz files are a zip file which *can* contain beatmap specific skins. sliderfollowcircle.png is the "buggy" image in question. Apparently, any skin can be resized beyond their normal dimensions. For sliderfollowcircle.png, normally it should be 128x128 (i think), while the one here is 284x284.

Of course, you can go way higher, I changed approachcircle.png and sliderfollowcircle.png both to 500x500. 
https://user-images.githubusercontent.com/67543533/163547787-e0ac04cb-62c5-4e3e-9157-70056f4e424e.mov

*Here is the [severely broken beatmap](https://github.com/ppy/osu/files/8494960/brokenmap.zip), due to github i had to rename it to zip, so you need to rename it back to osz.*

That seems to actually be an intended feature, as image upscaling works on stable and during gameplay. The real bug here is why it appears differently in the editor and during game. Both can be upscaled, but the one in editor appears significantly bigger than the on during gameplay. For that... I don't know. Probably a bug.

_I'm not osu expert, some things I said may be wrong but just trying._

**Comment by frenzibyte** [comment]
@toodols To put simply, if it works correctly in gameplay, then editor is doing something wrong. Nothing about scaling.

---

As for the actual issue at hand, the `OsuLegacySkinTransformer` is no longer applied to the beatmap skin in editor, this is due to the editor using an edit wrapper for the beatmap skin, which doesn't inherit from `LegacySkin`:
https://github.com/ppy/osu/blob/1c7cbc862156659d31651b3cfb748d4490e6ac6b/osu.Game/Screens/Edit/EditorBeatmapSkin.cs#L20

Therefore not having the transformer applied to it:
https://github.com/ppy/osu/blob/d7cbacc5a066947d6500313dcd296df43364a2e0/osu.Game/Skinning/RulesetSkinProvidingContainer.cs#L42

(one might ask how is it even displaying the legacy sprites from beatmap skin in that case, and the answer lies [here](https://github.com/ppy/osu/blob/fb9fe4213df4b89ddfec65c71765322aeb38742e/osu.Game/Skinning/LegacySkin.cs#L396))

Simplest solution I can think of is to add an `ILegacySkin` marker interface for the editor beatmap skin wrapper, to make the transformer apply to it as well:
```diff
diff --git a/osu.Game/Screens/Edit/EditorBeatmap.cs b/osu.Game/Screens/Edit/EditorBeatmap.cs
index c9449f3259..edf743aca3 100644
--- a/osu.Game/Screens/Edit/EditorBeatmap.cs
+++ b/osu.Game/Screens/Edit/EditorBeatmap.cs
@@ -100,7 +100,7 @@ public EditorBeatmap(IBeatmap playableBeatmap, ISkin beatmapSkin = null, Beatmap
             this.beatmapInfo = beatmapInfo ?? playableBeatmap.BeatmapInfo;

             if (beatmapSkin is Skin skin)
-                BeatmapSkin = new EditorBeatmapSkin(skin);
+                BeatmapSkin = new EditorBeatmapSkin((LegacySkin)skin);

             beatmapProcessor = playableBeatmap.BeatmapInfo.Ruleset.CreateInstance().CreateBeatmapProcessor(PlayableBeatmap);

diff --git a/osu.Game/Screens/Edit/EditorBeatmapSkin.cs b/osu.Game/Screens/Edit/EditorBeatmapSkin.cs
index 429df85904..e252f63e52 100644
--- a/osu.Game/Screens/Edit/EditorBeatmapSkin.cs
+++ b/osu.Game/Screens/Edit/EditorBeatmapSkin.cs
@@ -17,7 +17,7 @@ namespace osu.Game.Screens.Edit
     /// <summary>
     /// A beatmap skin which is being edited.
     /// </summary>
-    public class EditorBeatmapSkin : ISkin
+    public class EditorBeatmapSkin : ILegacySkin
     {
         public event Action BeatmapSkinChanged;

@@ -27,9 +27,9 @@ public class EditorBeatmapSkin : ISkin
         /// </summary>
         public readonly BindableList<Colour4> ComboColours;

-        private readonly Skin skin;
+        private readonly LegacySkin skin;

-        public EditorBeatmapSkin(Skin skin)
+        public EditorBeatmapSkin(LegacySkin skin)
         {
             this.skin = skin;

diff --git a/osu.Game/Skinning/LegacySkin.cs b/osu.Game/Skinning/LegacySkin.cs
index f7d5581621..26372b0d74 100644
--- a/osu.Game/Skinning/LegacySkin.cs
+++ b/osu.Game/Skinning/LegacySkin.cs
@@ -21,6 +21,7 @@
 using osu.Game.IO;
 using osu.Game.Rulesets.Objects.Types;
 using osu.Game.Rulesets.Scoring;
+using osu.Game.Screens.Edit;
 using osu.Game.Screens.Play;
 using osu.Game.Screens.Play.HUD;
 using osu.Game.Screens.Play.HUD.HitErrorMeters;
@@ -28,7 +29,7 @@

 namespace osu.Game.Skinning
 {
-    public class LegacySkin : Skin
+    public class LegacySkin : Skin, ILegacySkin
     {
         /// <summary>
         /// Whether texture for the keys exists.
diff --git a/osu.Game/Skinning/RulesetSkinProvidingContainer.cs b/osu.Game/Skinning/RulesetSkinProvidingContainer.cs
index b884794739..d913abfc2e 100644
--- a/osu.Game/Skinning/RulesetSkinProvidingContainer.cs
+++ b/osu.Game/Skinning/RulesetSkinProvidingContainer.cs
@@ -39,7 +39,10 @@ public RulesetSkinProvidingContainer(Ruleset ruleset, IBeatmap beatmap, [CanBeNu
             Ruleset = ruleset;
             Beatmap = beatmap;

-            InternalChild = new BeatmapSkinProvidingContainer(beatmapSkin is LegacySkin ? GetLegacyRulesetTransformedSkin(beatmapSkin) : beatmapSkin)
+            if (beatmapSkin is ILegacySkin legacyBeatmapSkin)
+                beatmapSkin = GetLegacyRulesetTransformedSkin(legacyBeatmapSkin);
+
+            InternalChild = new BeatmapSkinProvidingContainer(beatmapSkin)
             {
                 Child = Content = new Container
                 {
@@ -69,7 +72,7 @@ protected override void RefreshSources()
             {
                 switch (skin)
                 {
-                    case LegacySkin legacySkin:
+                    case ILegacySkin legacySkin:
                         sources.Add(GetLegacyRulesetTransformedSkin(legacySkin));
                         break;

@@ -92,7 +95,7 @@ protected override void RefreshSources()
             SetSources(sources);
         }

-        protected ISkin GetLegacyRulesetTransformedSkin(ISkin legacySkin)
+        protected ISkin GetLegacyRulesetTransformedSkin(ILegacySkin legacySkin)
         {
             if (legacySkin == null)
                 return null;
```

I'm not sure if that's one step behind the envisioned new skinning structure though, cc @peppy.

**Comment by bdach** [comment]
I am really not liking the hard cast in `EditorBeatmap` in the patch above. Would like it to not be there if feasible.

**Comment by frenzibyte** [comment]
It's more about if the beatmap skin is an actual `Skin` instance, then it should be a legacy skin. But could change it to:
```csharp
if (beatmapSkin is LegacySkin legacyBeatmapSkin)
    BeatmapSkin = new EditorBeatmapSkin(legacyBeatmapSkin);
```
If that looks better.

**Comment by bdach** [comment]
It does not. Why would the editor only be able to save legacy beatmap skins?

Where's that change even coming from? It's not like `EditorBeatmapSkin` is a `Skin`, is it - so it should not pass the existing `beatmapSkin is Skin skin` check?

**Comment by frenzibyte** [comment]
The original line is here:
https://github.com/ppy/osu/blob/51251e3204aa4b5097eabecc0f312d244672022f/osu.Game/Screens/Edit/EditorBeatmap.cs#L102-L103

The above lines check if the source beatmap skin is of type `Skin`, not `EditorBeatmapSkin`. 

Since the `EditorBeatmapSkin` wrapper is marked as an `ILegacySkin`, it should only accept `ILegacySkin`s as a source beatmap skin. 

But I suppose `EditorBeatmapSkin` shouldn't be marked as `ILegacySkin` to begin with, and there should be a different wrapper for this instead (just for the other wrapper to have the `ILegacySkin` interface marked to it):
```csharp
if (beatmapSkin is ILegacySkin legacySkin)
    BeatmapSkin = new EditorBeatmapLegacySkin(legacySkin);
else if (beatmapSkin is ISkin skin)
    BeatmapSkin = new EditorBeatmapSkin(skin);

...

public class EditorBeatmapLegacySkin : EditorBeatmapSkin, ILegacySkin
{
    public EditorBeatmapLegacySkin(ILegacySkin skin)
        : base(skin)
    {
    }
}
```

**Comment by bdach** [comment]
> Since the `EditorBeatmapSkin` wrapper is marked as an `ILegacySkin` in the changes, it should only accept `ILegacySkin`s as a source beatmap skin.

i have no idea where this requirement is coming from, and i do not agree with it either. care to provide a reason why?

**Comment by frenzibyte** [comment]
I don't think it possibly makes sense for an `ILegacySkin` wrapper to have non-`ILegacySkin` sources..? Feels wrong and could lead to non-`ILegacySkin` beatmap skins potentially having a legacy skin transformer applied to it.

**Comment by bdach** [comment]
`EditorBeatmapSkin` was supposed to be just a mutability wrapper, nothing more. unless there is a valid reason to split legacy/non-legacy wrappers i'm not sure this is a good path to take.

if this is the direction where things are headed, then maybe the issue should be considered the other way around - rather than annotating `EditorBeatmapSkin` to be legacy or not legacy, the actual usable skin (legacy or not) should be extractable from it, and that should be the thing getting transformed inside editor.

**Comment by frenzibyte** [comment]
That seems like one alternative and simpler solution. I haven't considered it since I was under the thought `EditorBeatmapSkin` may be manipulating the lookup flow (`GetXyz` methods) and therefore should be the one transformed instead. But it seems it modifies the skin source itself directly instead.

Diff:
```diff
diff --git a/osu.Game/Screens/Edit/EditorBeatmapSkin.cs b/osu.Game/Screens/Edit/EditorBeatmapSkin.cs
index 429df85904..bb5651a048 100644
--- a/osu.Game/Screens/Edit/EditorBeatmapSkin.cs
+++ b/osu.Game/Screens/Edit/EditorBeatmapSkin.cs
@@ -21,17 +21,20 @@ public class EditorBeatmapSkin : ISkin
     {
         public event Action BeatmapSkinChanged;
 
+        /// <summary>
+        /// The underlying beatmap skin.
+        /// </summary>
+        public Skin Skin { get; }
+
         /// <summary>
         /// The combo colours of this skin.
         /// If empty, the default combo colours will be used.
         /// </summary>
         public readonly BindableList<Colour4> ComboColours;
 
-        private readonly Skin skin;
-
         public EditorBeatmapSkin(Skin skin)
         {
-            this.skin = skin;
+            Skin = skin;
 
             ComboColours = new BindableList<Colour4>();
             if (skin.Configuration.ComboColours != null)
@@ -43,16 +46,16 @@ public EditorBeatmapSkin(Skin skin)
 
         private void updateColours()
         {
-            skin.Configuration.CustomComboColours = ComboColours.Select(c => (Color4)c).ToList();
+            Skin.Configuration.CustomComboColours = ComboColours.Select(c => (Color4)c).ToList();
             invokeSkinChanged();
         }
 
         #region Delegated ISkin implementation
 
-        public Drawable GetDrawableComponent(ISkinComponent component) => skin.GetDrawableComponent(component);
-        public Texture GetTexture(string componentName, WrapMode wrapModeS, WrapMode wrapModeT) => skin.GetTexture(componentName, wrapModeS, wrapModeT);
-        public ISample GetSample(ISampleInfo sampleInfo) => skin.GetSample(sampleInfo);
-        public IBindable<TValue> GetConfig<TLookup, TValue>(TLookup lookup) => skin.GetConfig<TLookup, TValue>(lookup);
+        public Drawable GetDrawableComponent(ISkinComponent component) => Skin.GetDrawableComponent(component);
+        public Texture GetTexture(string componentName, WrapMode wrapModeS, WrapMode wrapModeT) => Skin.GetTexture(componentName, wrapModeS, wrapModeT);
+        public ISample GetSample(ISampleInfo sampleInfo) => Skin.GetSample(sampleInfo);
+        public IBindable<TValue> GetConfig<TLookup, TValue>(TLookup lookup) => Skin.GetConfig<TLookup, TValue>(lookup);
 
         #endregion
     }
diff --git a/osu.Game/Screens/Edit/EditorSkinProvidingContainer.cs b/osu.Game/Screens/Edit/EditorSkinProvidingContainer.cs
index decfa879a8..694d0253e0 100644
--- a/osu.Game/Screens/Edit/EditorSkinProvidingContainer.cs
+++ b/osu.Game/Screens/Edit/EditorSkinProvidingContainer.cs
@@ -16,7 +16,7 @@ public class EditorSkinProvidingContainer : RulesetSkinProvidingContainer
         private readonly EditorBeatmapSkin? beatmapSkin;
 
         public EditorSkinProvidingContainer(EditorBeatmap editorBeatmap)
-            : base(editorBeatmap.PlayableBeatmap.BeatmapInfo.Ruleset.CreateInstance(), editorBeatmap.PlayableBeatmap, editorBeatmap.BeatmapSkin)
+            : base(editorBeatmap.PlayableBeatmap.BeatmapInfo.Ruleset.CreateInstance(), editorBeatmap.PlayableBeatmap, editorBeatmap.BeatmapSkin?.Skin)
         {
             beatmapSkin = editorBeatmap.BeatmapSkin;
         }
```

**Comment by bdach** [comment]
seems much better to me, but i do suppose it's just my opinion.

**Comment by peppy** [comment]
The last proposal looks closer to what we want.
