### ISSUE TITLE
"OK" judgement accidentally looks up unrelated sprite on specific beatmap due to name clash

### ISSUE THREAD

**Issue by shirozii** [ppy/osu#17934]
### Type

Cosmetic

### Bug description

Affected beatmap(s?): https://osu.ppy.sh/beatmapsets/27441
~~During gameplay, random parts (usually close to where a circle or the gameplay cursor is) of the beatmap's background will randomly flicker~~ 

~~Issue seems to not be present if you have autoplay or relax on~~
The random part turns out to be `ok.jpg` inside the beatmap which lazer thinks it should replace the current skin's `OK` sprite with: https://github.com/ppy/osu/issues/17934#issuecomment-1106708304
Autoplay or relax dont have the issue because both of them can never get `OK` judgement: https://github.com/ppy/osu/issues/17934#issuecomment-1106703393

### Screenshots or videos

https://user-images.githubusercontent.com/96925398/164751613-e54b21e1-6151-46d7-925f-36a9d9913b8c.mp4

### Version

2022.418.0

### Logs

[performance.log](https://github.com/ppy/osu/files/8542374/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8542375/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8542376/updater.log)
[database.log](https://github.com/ppy/osu/files/8542377/database.log)
[network.log](https://github.com/ppy/osu/files/8542378/network.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/8542379/legacy-ipc.log)

**Comment by Gabixel** [comment]
On a quick check, the weird flickering image seems to appear when the beatmap skin is enabled and you get the "ok" judgement.

**Comment by Susko3** [comment]
There is a `ok.jpg` in the bearmap. Stable works just fine (doesn't use this image for ok)

![image](https://user-images.githubusercontent.com/16479013/164762275-821266d0-1938-40b6-9e2d-49b1bbefaf5f.png)

**Comment by shirozii** [comment]
Updated the issue to include the findings above

**Comment by frenzibyte** [comment]
I think at this point, it makes all the sense to make the transformer actually handle all `OsuSkinComponents` rather than have this weird fallback logic in `LegacySkin` which has always been a source of hiding issues / causing unexpected behaviour:

https://github.com/ppy/osu/blob/fb9fe4213df4b89ddfec65c71765322aeb38742e/osu.Game/Skinning/LegacySkin.cs#L396

**Comment by bdach** [comment]
Maybe? I'm honestly rather cautious about that proposal. The scary part with removing such fallback paths is not knowing what will break. I'd hope test coverage catches some breakage but I'm not sure we've got coverage that will fail for every single little corner of legacy behaviour...

**Comment by frenzibyte** [comment]
I think this one should be a safe change, since all that needs to be taken care of is whether all `ISkinComponent`s of different types and different enum members are handled at transformers or inside `LegacySkin` without ever reaching that fallback.

And now that I look at it again, the `break` statement in https://github.com/ppy/osu/blob/71e4c4f752c5a0fb353489d9f44e7ef8f6d9e5f9/osu.Game/Skinning/LegacySkin.cs#L378-L393 should've been a `return null;` instead, since no hit/judgement animation was found.

Will fix the current issue in one PR and remove the fall back in another as a proposal PR.
