### ISSUE TITLE
Skin editor scene library uses autoplay despite selected mods being incompatible with autoplay

### ISSUE THREAD

**Issue by AfterPlayer** [ppy/osu#17936]
### Type

Game behaviour

### Bug description

So I just wanted to add a pp counter using the skin editor but I forgot that I had Magnetised on, however the autoplay still played like there wasn't magnetised on since its supposed to be not compatible.
By doing so you can also make autoplay play with other incompatible mods like No Fail or Spun Out

### Screenshots or videos

https://imgur.com/a/cyflxId

### Version

2022.418.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8542842/database.log)
[network.log](https://github.com/ppy/osu/files/8542843/network.log)
[performance.log](https://github.com/ppy/osu/files/8542844/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8542845/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8542846/updater.log)

**Comment by bdach** [comment]
The simplest possible fix I can imagine would be to just unapply user mods when opening the gameplay scene from the scene library. Although that may annoy some people because I know the concept of "mod-specific skins" exists, so maybe it should do that just for mods that aren't autoplay-compatible...
