### ISSUE TITLE
Incorrect rank displayed at 90.00% accuracy

### ISSUE THREAD

**Issue by IAmDeviant** [ppy/osu#17974]
### Type

Cosmetic

### Bug description

The result screen shows that I achieved a B rank on "Fukagyaku Replace" on the Hishigata custom ruleset. However, the circular meter shows that I achieved an A rank. Accuracy was exactly on 90%. I have thought of reporting this as I am unsure whether or not this only applies to custom rulesets as I noticed the rank system is accuracy-based.

### Screenshots or videos

![rankissue](https://user-images.githubusercontent.com/73929686/165195178-5375ad81-a86e-427a-ace0-8637ed1750c4.png)

### Version

2022.424.1

### Logs

[database.log](https://github.com/ppy/osu/files/8558754/database.log)
[network.log](https://github.com/ppy/osu/files/8558755/network.log)
[performance.log](https://github.com/ppy/osu/files/8558756/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8558757/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8558758/updater.log)

**Comment by frenzibyte** [comment]
That lines up with the grading logic (and also matches [stable](https://osu.ppy.sh/wiki/en/Gameplay/Grade)): 

https://github.com/ppy/osu/blob/5ec2d86c094e26f1c2663047ba895c47271b9d6c/osu.Game/Rulesets/Scoring/ScoreProcessor.cs#L374-L388

Though hard to say if it's right or wrong, and the rank circular display should probably be fixed to be exclusive rather than inclusive to match at least.

**Comment by peppy** [comment]
Those should likely be `>=`.
