### ISSUE TITLE
Compilation guide should have instructions for windows / macOS

### ISSUE THREAD

**Issue by peppy** [ppy/osu#1802]
Also should mention GUI alternative for linux users.

**Comment by FreezyLemon** [comment]
What's meant by "GUI alternative"? IDEs? Or a GUI for git?

The instructions for Windows would be nearly identical to Linux, just without Mono. I'm not sure we need a separate instruction for Windows unless we want to explain building in an IDE.

If this applies to macOS too (I'd assume it's similar to Linux) we can pretty much explain the build process in just one instruction with some comments rather than three separate ones.

**Comment by peppy** [comment]
We've already updated the readme with better instructions, so personally I think there's no need for `COMPILATION.md` any more.

**Comment by FreezyLemon** [comment]
Hm.. I mostly agree, though there could be an explanation for non-Windows users who want to build for themselves and not install an IDE just for that.. Isn't that why `COMPILATION.md` existed in the first place?

**Comment by ticotaco72** [comment]
@peppy propably this issue isn't existing in actual codebase anymore
