### ISSUE TITLE
SDL Wayland backend no longer working since 2022.515.0

### ISSUE THREAD

**Issue by GiantNuker** [ppy/osu#18273]
### Type

Crash to desktop

### Bug description

Game crashes when started with `SDL_VIDEODRIVER=wayland` due to missing primary display. My compositor does not actually have a primary display, and programs (including older versions of osu) just open on whatever display my mouse is on, which is expected/fine. (Maybe fall back to the old display logic when there is no primary display?)

When started with `SDL_VIDEODRIVER=x11` it opens on the display my mouse is on, but with the resolution of my other connected display, instead of the expected resolution of the display it opens on. This is repeated every time I open osu.

The game crashes with the following error when using wayland:
```
Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at osu.Framework.Platform.SDL2DesktopWindow.get_PrimaryDisplay()
   at osu.Framework.Platform.SDL2DesktopWindow.SetupWindow(FrameworkConfigManager config)
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-2/ppy/osu/osu.Desktop/Program.cs:line 105
```

Edit: Resolution also breaks whenever focus is lost on x11

### Screenshots or videos

https://streamable.com/olsm6a
(video is cropped on the sides due to hardware encoder limitations)

### Version

2022.515.0

### Logs

[x11_database.log](https://github.com/ppy/osu/files/8694496/x11_database.log)
[x11_legacy-ipc.log](https://github.com/ppy/osu/files/8694497/x11_legacy-ipc.log)
[x11_network.log](https://github.com/ppy/osu/files/8694498/x11_network.log)
[x11_performance.log](https://github.com/ppy/osu/files/8694499/x11_performance.log)
[x11_runtime.log](https://github.com/ppy/osu/files/8694500/x11_runtime.log)
[x11_updater.log](https://github.com/ppy/osu/files/8694501/x11_updater.log)
[wayland_runtime.log](https://github.com/ppy/osu/files/8694502/wayland_runtime.log)
(only runtime.log was present for wayland)

**Comment by bdach** [comment]
The assumption is the title is wrong, you misinterpreted the stack trace. It's not that the "primary display" wasn't found, rather than *no* display was found.

Anyway, looking into this, since I'm actually in a position to investigate wayland issues now. However this is 99% something that should/will be reported upstream.

**Comment by GiantNuker** [comment]
I see that now, and quickly checking the git blame at the stacktrace (hasn't changed since 2020) it does appear to be upstream.
Should I change the issue title?

**Comment by bdach** [comment]
So it appears that after the latest SDL2-CS bump the wayland SDL backend is entirely unavailable. When running framework sample game with `SDL_VIDEODRIVER=wayland`, `SDL_Init()` silently fails (silently because return value is not checked) with the following:

![image](https://user-images.githubusercontent.com/20418176/168467482-fe09db02-4f6a-4608-9483-5d73c0c5f58a.png)

Further corroborated by [build log of latest linux libs](https://github.com/ppy/SDL2-CS/runs/6349729064?check_suite_focus=true#step:5:575), note that `SDL_WAYLAND` is marked off in configure output. There's probably a dependency missing causing configure to not select the wayland backend to be built, not sure which one yet.

**Comment by ekrctb** [comment]
https://github.com/ppy/SDL2-CS/runs/6349729064?check_suite_focus=true#step:5:436

```
-- Checking for modules 'wayland-client>=1.18;wayland-egl;wayland-cursor;egl;xkbcommon>=0.5.0'
--   Requested 'wayland-client >= 1.18' but version of Wayland Client is 1.16.0
```

Probably this one?

**Comment by bdach** [comment]
Probably. This is a bit of a rock-and-a-hard place situation because wayland-client [is not available at 1.18 in the ubuntu 18.04 repositories](https://packages.ubuntu.com/search?keywords=libwayland-client). If we bump the runner to run on 20.04, it will fix this, but in turn will likely break 18.04 because of incompatible glibc versions...

**Comment by ekrctb** [comment]
Probably we can revert https://github.com/libsdl-org/SDL/commit/13337e17a56ac116c39841afac6e1c8482032ca5 https://github.com/libsdl-org/SDL/commit/f3ff0c568e7b599bf0e5293e124c0085c7aa69ea on our fork and call it a day?

**Comment by bdach** [comment]
I mean, maybe? What about potential commits *after* those two that may be silently dependent on 1.18? That would require a full audit of all wayland changes which I sure as hell do not feel comfortable about doing.

**Comment by ekrctb** [comment]
Agree, it is also bad going to back maintaining a SDL2 fork.

**Comment by bdach** [comment]
Related upstream thread: https://github.com/libsdl-org/SDL/pull/5429

Looks like upstream is plain giving up on wayland on older distros, which I suppose from their perspective is understandable, but is putting us in a bad spot due to an "unconventional" (in the linux world) release model. I wouldn't be necessarily opposed to giving up on older distros ourselves, ubuntu 18.04 merely has a year of LTS left and there are two newer stable releases now, but I don't feel it's my call to make.

**Comment by smoogipoo** [comment]
Imo I think it's fine bumping up the CI runner. People tend to upgrade their desktops to the latest software, if possible (which is pretty much always the case with Linux).

**Comment by memesnightmares** [comment]
This appears to be resolved in the latest release, at least on my system. Should it be closed? Apologies for the noise if not.

**Comment by bdach** [comment]
I believe the fix for this has propagated through the chain, yes (new sdl2 binaries -> new sdl2-cs package -> new framework release -> new game release). Closing as resolved.
