### ISSUE TITLE
Distance snap not shown for juice streams in catch editor

### ISSUE THREAD

**Issue by rcfox2** [ppy/osu#18469]
### Type

Game behaviour

### Bug description

Title says enough, sliders don't show distance snap when circles do. See video.

### Screenshots or videos

https://user-images.githubusercontent.com/68173946/170847016-5b7b2de5-3a4d-430f-87b9-ae2946702a9b.mp4

### Version

2022.528.0

### Logs

[updater.log](https://github.com/ppy/osu/files/8792389/updater.log)
[database.log](https://github.com/ppy/osu/files/8792390/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/8792391/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/8792392/network.log)
[performance.log](https://github.com/ppy/osu/files/8792393/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8792394/runtime.log)

**Comment by ekrctb** [comment]
This check
<https://github.com/ppy/osu/blob/20701edc23e3f48ac137db28cddceccb8324851f/osu.Game.Rulesets.Catch/Edit/CatchHitObjectComposer.cs#L148-L152>
hides the distance snap grid so the first fruit of a juice stream should be snapped but rest of the path shouldn't be snapped.
However, #18149 broke this because `PlacementObject` is now set earlier.
