### ISSUE TITLE
Can't right click objects in the editor timeline

### ISSUE THREAD

**Issue by rcfox2** [ppy/osu#18470]
### Type

Game behaviour

### Bug description

You can't right click objects on the timeline in the editor. You could previously do this. (I think this has been a bug since last version?)

### Screenshots or videos

https://user-images.githubusercontent.com/68173946/170847283-9c4d3683-539a-4c69-9228-457130ad8386.mp4

### Version

2022.528.0

### Logs

[performance.log](https://github.com/ppy/osu/files/8792403/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8792404/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8792405/updater.log)
[database.log](https://github.com/ppy/osu/files/8792406/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/8792407/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/8792408/network.log)

**Comment by bdach** [comment]
Regressed in https://github.com/ppy/osu/pull/18219. @frenzibyte please advise

**Comment by frenzibyte** [comment]
Looking at the cause, it turns out #18219 regressed this because it blocks the mouse event from reaching the screen-level `OsuContextMenuContainer` that's placed in `Editor`, via `OnMouseDown() => true`.

This wasn't the case prior to https://github.com/ppy/osu-framework/pull/5118 due to `ScrollContainer` early-returning when the pressed mouse button isn't left, therefore allowing right clicks to get past `Timeline` and into the context menu container.

It's arguably shocking for a drawable inside a certain mouse-blocking container to no longer have context menus opened because the corresponding `OsuContextMenuContainer` is not within that container.

I would imagine `OsuContextMenuContainer` to be prioritised in the input queue in some form, but for the time being, I believe working around this by a `e.Button != Left` should suffice (although it means you could right-click objects in the ruleset screen while hovering over the timeline, but that's pretty much how it worked before).
