### ISSUE TITLE
Beatmaps with `OnlineID = -1` not playable in multiplayer or re-downloadable/re-importable

### ISSUE THREAD

**Issue by buritzcold** [ppy/osu#18600]
### Type

Game behaviour

### Bug description

The map [Heartbit (feat. Tia Simone)] [https://osu.ppy.sh/beatmapsets/1557716#osu/3182052](url) refuses to play while in the spotlight playlist or any other playlist. The 'Start' icon is grey and does nothing. However the map will play in single player. All other maps in the spotlight playlist work just fine. Reinstalling the map did not fix the issue neither did re-converting all my beatmaps from stable. In the top scores in the spotlight the beatmap also displays that it is 0.00 stars while it is a little over 5.

### Screenshots or videos

https://user-images.githubusercontent.com/107019523/172295896-80ee8640-769d-4ab2-aae5-2305c81514bf.mp4

### Version

2022.605.1

### Logs

[performance.log](https://github.com/ppy/osu/files/8850108/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8850109/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8850110/updater.log)
[database.log](https://github.com/ppy/osu/files/8850111/database.log)
[network.log](https://github.com/ppy/osu/files/8850112/network.log)

**Comment by smoogipoo** [comment]
Please provide the `client.realm` file in your osu! folder. You can click the button in settings to go to the folder.

**Comment by buritzcold** [comment]
github does not support the filetype of client.realm so it wont let me upload it here.

**Comment by smoogipoo** [comment]
You can just rename the file to have a .zip extension.

**Comment by buritzcold** [comment]
[client.realm.zip](https://github.com/ppy/osu/files/8850390/client.realm.zip)

**Comment by smoogipoo** [comment]
For the time being, you can delete the beatmap in song select -> restart osu! -> re-download the beatmap.

For others following along there's two parts here:
1. Redownloading the beatmap doesn't work because the `CanSkipImport` test passes - one beatmap of four has `OnlineID > 0`.
2. The download button checks only the set's online ID, not the beatmap's online ID.

**Comment by peppy** [comment]
Just to document initial findings and propose a direction:

## `OnlineID` is being relied on too much

Right now, for already imported beatmaps, `OnlineID` is considered to be a 100% confirmation that the imported beatmap is in a "good state". ie. it will cause `BeatmapDownloadTracker` to display that the beatmap is "locally available". If the imported beatmap happens to have a hash which doesn't match the actual online beatmap, or if the user locally modified the beatmap, because the `OnlineID` is still set correctly this will cause issues like being unable to play the beatmap in multiplayer.

A first step is to remove the reliance on `OnlineID`. We can't be certain that a beatmap is in a good state by just checking it has the correct `OnlineID`.

This also leads into the fact that manually attempting to import a corrected version of a beatmap in a "bad state" will skip the import.

## Import skip conditions

Currently beatmap import can be skipped if:

- Before import begins (as an optimisation for large imports):
  - If an existing beatmap (matched by `.osu` file hashes) has an online ID
  - If all files exist on disk for the already imported beatmap
  - If all filenames match between the prospective import and existing beatmap

- After import begins (`RealmFileInfo`s have been created and files have been copied to the store):
  - All files match (at a byte level)
  - All filenames match

The issue here is the optimised import step. A first step towards fixing this would be to isolate the import optimisations to only cases where large imports are occurring (either `import.Count > 0` or `is ImportFromStable`).

## Work actions

- Fix `BeatmapDownloadTracker` not checking hashes and relying on `OnlineID`
- Add a path through the import process which skips the optimised import checks and always attempts an import

I'm going to start working on these, but welcome feedback in the mean time.

**Comment by peppy** [comment]
This issue is marked as being closed by #18689, but I'd like to note that:

> Fix `BeatmapDownloadTracker` not checking hashes and relying on `OnlineID`

Will be addressed in future work (see https://github.com/ppy/osu/issues/18665#issuecomment-1153774257). It's not easy to resolve that one in an isolated manner, and the changes in #18689 will allow manual recovery from the issue mentioned in this thread so I think closing is fine.
