### ISSUE TITLE
Metadata being in original language preference should be part of the first run setup

### ISSUE THREAD

**Issue by peppy** [ppy/osu#18617]

**Comment by vegguid** [comment]
I looked into this and I'm not sure what would be the best way to implement this. As the only page where it would make sense would be the Behaviour screen but on this screen there are only things that are different from stable with the text also saying that 

> Some new defaults for game behaviours have been implemented, with the aim of improving the game experience and making it more accessible to everyone.
We recommend you give the new defaults a try, but if you'd like to have things feel more like classic versions of osu!, you can easily apply some sane defaults below.

But this setting was not changed from stable so that would make no so sense.
So either the text would need to be changed or it needs to be placed somewhere else.

**Comment by peppy** [comment]
I'd see it existing on the first screen along with language selection.
