### ISSUE TITLE
Idea for a new "mod"

### ISSUE THREAD

**Issue by CaptainTristana** [ppy/osu#1863]
So as we know, mania has this binding for the users to change the note falling speed, it could be implemented to standard aswell as a mod as a AR modifier, which would reduce the gained score by 10% and reduce PP gain by 5%, the user could choose 1 AR up or under the current song setting with the cap being AR10, it would still apply with other mods, so for example if a song is AR8 and you decide to use this mod to reduce it to AR7 and then use HR, it would end up being AR9.8

**Comment by Frontear** [comment]
Unfortunately, this wouldn't work with osu. AR serves more purpose than sim[;y difficulty. There are rhythmic factors to consider (fast songs or higher bpm songs tend to have higher AR), as well as object density, reading rate, blah blah (Mappers probably have more information if you are interesting). This idea won't fit well with osu's current mapping philosophy. Besides, everyone would pretty much use AR 10 only. This also wouldn't make sense in terms of skillful plays either, since you could play HDDTHR and lower your AR rate to something absurdly low, making the map suddenly easier to read (no more 300ms reactions), and 5% pp reduction isn't doing anything to nerf that. It isn't really a mod, more than it is a cheat.

**Comment by TemTemmie** [comment]
fork the repo then modify the mods files. this isnt the place to request features 🤔

**Comment by lolord** [comment]
If that's the case, then it shouldn't be a problem to implement a mod with which you can change values such as AR, OD, HP, CS(maybe BPM and Speed aswell) as long as that mod isn't ranked right? It's not like it isn't already possible right now(You can change the first 4 values through the beatmap editor and the speed/BPM with the [BPM Changer](https://github.com/smoogipoo/osu--BPM-Changer) or of course with McOsu), but having a mod with which you can change those values in the official client would make it a lot easier to do those things.

**Comment by peppy** [comment]
Feel free to implement these kinds of mods without making issues. We will judge them post-implementation.
