### ISSUE TITLE
Mod columns can scroll by using the mouse wheel on the toolbar during customisation

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#18673]
### Type

Game behaviour

### Bug description

Moving the mouse wheel in the toolbar while the mod customisation panel is open allows scrolling in the mod columns. Generally, this scenario should open the volume panel, so I'm not sure if it's intentional.

### Screenshots or videos

![osu! 2022 06 13](https://user-images.githubusercontent.com/43073074/173316410-a0a93036-f62f-4fbf-ac68-98b5c80be5fb.gif)

### Version

2022.612.0-lazer

### Logs

n/a

**Comment by peppy** [comment]
I think the toolbar should probably handle scroll events itself, rather than even pass to the volume controls. There may be a point in the future where it has horizontally scrolling elements within the toolbar, so I'd want to reserve that behaviour for it rather than having users get used to using it to adjust volume.
