### ISSUE TITLE
osu! freezes then crash on macOS

### ISSUE THREAD

**Issue by Naozumi520** [ppy/osu#18759]
### Type

Crash to desktop

### Bug description

So basically everytime I play it freezes and it only happens in game. However, I've never seen it occurred in the main menu. When I'm playing, the screen randomly gets stuck. It could be the beginning of the map, in the middle or even the song is finishing. 
It doesn't always happen, but it often happens like every time I open the game to play then it gets stuck.

I'm not sure if this is related to [This issue](https://github.com/ppy/osu/issues/12944) and the behavior look different to me as the screen is getting stuck randomly.

I can't provide screenshots or video as I can't even record video because it's getting stuck also.

### Version

2022.615.0

### Logs

Here's the logs:
[database.log](https://github.com/ppy/osu/files/8933713/database.log)
[network.log](https://github.com/ppy/osu/files/8933714/network.log)
[performance.log](https://github.com/ppy/osu/files/8933715/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8933716/runtime.log)
And this macOS log file as well:
[crash.txt](https://github.com/ppy/osu/files/8933720/crash.txt)

**Comment by bdach** [comment]
Game log attached looks like it comes from a normal execution without a crash. macOS log attached includes:

```
Graphics hardware encountered an error and was reset: 0x00000002
```

Not sure there's anything we can do about this without metal/veldrid/whatever else to not use opengl on mac.

**Comment by naoey** [comment]
This could be related to https://github.com/ppy/osu/issues/8278? It's the same device model, hardware and symptoms.

**Comment by Annonymus-v02** [comment]
Happens to me as well, but on a mac pro, not a macbook like the one in #8278. Shortly after starting, the screen will freeze* and two minutes later the watchdog throws a kernel panic because it hasn't heard from windowserver in 120 seconds.

[Here](https://github.com/ppy/osu/files/9083489/panic-full-2022-07-11-105530.0003.ips.zip) is the OS's panic log (zipped because github doesn't like ips files). I also found [a number of gpurestart logs](https://github.com/ppy/osu/files/9083513/gpurestart.logs.zip) which were generated while osu!lazer was running (I haven't checked the exact time so not sure if it happened during or before the crash). All the gpurestart logs were generated while osu! was running, even though I ran other applications which use the GPU at other times, so it seems to be anomalous behavior relevant to osu!

*audio still works so I can confirm that the game is still running since I hear the "song failed" sound shortly after, it's just the display that freezes

**Comment by peppy** [comment]
@Annonymus-v02 if you're hitting the same thing as me, it's gl memory exhaustion. The AMD driver has a bug which causes this, and it's out of our control. You can monitor memory (and gl context count) via `OpenGL Driver Monitor` to check what's happening, but this is not something we can fix at our end.

We'll eventually support metal to resolve this, because there's basically zero chance apple will fix issues with GL at this point in the timeline.

**Comment by zwzheng45** [comment]
I'm using a MacBookPro16,1 and there is a compromise solution which works fine for me. Because it's a AMD driver fault so I tried to run it on the integrated UHD 630 and it solves the problem! The game doesn't freeze or crash any more, but it will run at a lower frame rate (which is still playable).

**Comment by Joehuu** [comment]
Closing as stale (this was before Metal was implemented).
