### ISSUE TITLE
Update gameplay HUD visuals

### ISSUE THREAD

**Issue by peppy** [ppy/osu#18888]
New HUD designs have been available for some time now. This involves applying the new layout, and also updating pieces which feel pretty jank currently (like the song progress display). May require some extra design effort.

**Comment by ItsShamed** [comment]
I tried to implement the Argon variant of the song progress display and I want to give it a try at PRing it.
Also, I may need some directions UX-wise. I have made some assumptions, but I'm not sure if that's the right direction.

**Comment by frenzibyte** [comment]
@peppy Since this is included in the project, I've taken a look at it. To start off, should I begin by following each detail in the design provided in figma (i.e. stuff like the decorating lines around the key counter and the song progress)? or should I stick to the main components like the ones at the top left.

<img width="1077" alt="CleanShot 2023-09-25 at 00 29 42@2x" src="https://github.com/ppy/osu/assets/22781491/8233ef29-2c4e-41b9-ad4d-5dc66df20938">

**Comment by peppy** [comment]
I'm not too sure about the line details for now, as they may need to change depending on where the key counter is placed (or at very least need user configuration over their position).

The main goal of the issue is to update the top-centre cluster (score, combo, accuracy) to match argon, so I'd focus on those as a priority.
