### ISSUE TITLE
Better file management

### ISSUE THREAD

**Issue by peppy** [ppy/osu#18902]
Currently it's not easy for a user to manually change files within a beatmap. An initial implementation should see the editor "mount" a folder with the beatmap where it can be modified by the user, then importing any changes back into the game's database.

This will allow for external tools to still work with the editor, and also working with things like storyboards before the editor supports them fully.

**Comment by frenzibyte** [comment]
Related: https://github.com/ppy/osu/issues/12029

**Comment by smallketchup82** [comment]
I'd be interested in tackling this for skins specifically.

I'm not too sure about mounting *literally*, a good approach would be to query the realm database for the specific files needed (which should be easy, since each skin object in the database has a `Files` column), copy those over into the a directory within the temporary directory of the operating system, then when the user presses "save changes and quit", the files are hashed, and files with hash mismatches are taken in as the new version for that specific file, then the directory is deleted. Going this route, a feature can be added called just "save changes" to run the diffing logic but not delete the directory after diffing.

Given we'd be copying to the temporary directory, we don't really have to put a priority on disposing/deleting the directory, say in case an error occurs, since it'll be cleaned up by the OS eventually.

**Comment by smoogipoo** [comment]
Your idea of mounting matches the suggestion in the OP.

**Comment by peppy** [comment]
To ease review/merging, I'd recommend making this work in the beatmap editor first. As mentioned on discord, I'm slightly reluctant to add this for skins when implementing an in-game UI for replacing assets is pretty low bar (and will provide a better experience).

To be clear, I'm not against enabling this in the skin editor alongside a UI implementation (and if done correctly it should be pretty portable between skins/beatmaps).

**Comment by smallketchup82** [comment]
> (and if done correctly it should be pretty portable between skins/beatmaps)

Looking at the database, the `Files` property for both beatmaps and skins have the exact same structure, so it would definitely be portable. I guess I could focus on implementing it for beatmaps first, then extending it to work with skins.

I've already gotten an implementation for mounting beatmap files. The hard part is the diffing logic, which kinda just doesn't want to work. I'll keep [working on it](https://github.com/smallketchup82/osu/tree/file-mounting) though.

**Comment by bdach** [comment]
> The hard part is the diffing logic, which kinda just doesn't want to work

https://github.com/ppy/osu/compare/master...smallketchup82:osu:file-mounting#diff-7b0432cda4c2c1a6621ecbb98a9a88605dcfb0262665eb0e1f06218f66cb686fR82-R85

This conditional looks backwards no? Hashes are equal yet comments and log statements claim "this file has been modified"?

**Comment by smallketchup82** [comment]
@bdach Yes, I noticed that and fixed but forgot to push. The current issue is that the new file doesn't seem to get added to the storage. When [this code](https://github.com/smallketchup82/osu/blob/f1955557774cc1d4e8fa3a2060d783439f1854e2/osu.Game/Database/FileMounter.cs#L83) runs, the game logs an error saying that the beatmap hash could not be found in the storage.

The weird part is that I'm not sure if it's the beatmap hash that isn't being updated, or if its the file itself that isn't being added to the storage.

**Comment by peppy** [comment]
Maybe an aside but deleting files directly from storage sounds very wrong. This is handled by the realm  file store already.

**Comment by smallketchup82** [comment]
> deleting files directly from storage sounds very wrong. This is handled by the realm file store already on next startup.

Didn't know that, I'll remove the direct calls to `storage.Delete`, thanks for letting me know. But there's still the issue of the realmFile's hash not getting updated or added to the storage, which I'll try to diagnose.

**Comment by smallketchup82** [comment]
Seems like it could be the fact that `Hash` is the primary key, and realm doesn't seem to like updating primary keys. I'm going to try an alternative approach with deleting and adding a new RealmFile to the beatmapSet's files.
![CleanShot 2024-05-30 at 09 44 35@2x](https://github.com/ppy/osu/assets/69545310/d055092f-b229-41a2-9ebc-5e7b8121832d)

**Comment by peppy** [comment]
Yeah, that's the correct approach. Check other usages such as saving a beatmap.

https://github.com/ppy/osu/blob/413b7aab602bcd6b4f60265fe893bc88c23b63e8/osu.Game/Beatmaps/BeatmapManager.cs#L467-L475

**Comment by smallketchup82** [comment]
Doing that just results in a ton of NullReferenceException's (specifically in BeatmapImporter's CalculateHash function).

On the other hand, take the scenario of a user making another .osu file intending to create a new difficulty, adding in more logic to create a new difficulty for the beatmapset would result in a lot of duplicate code.

It'd be better to run `BeatmapImporter.ImportAsUpdate` to import the new directory as if it was an update to the beatmapSet. I had changed my code to use it, and it actually worked pretty well. The only issue was that I would get an error saying that the `.osu` couldn't be found in the storage. Though, upon mounting the files again, the `.osu` would be present, albeit every single line under the [HitObjects] clause being deleted.

**Comment by peppy** [comment]
@smallketchup82 could you push the `ImportAsUpdate` code to a branch so I can take a look?

**Comment by smallketchup82** [comment]
@peppy I've pushed it to [my branch](https://github.com/smallketchup82/osu/tree/file-mounting), look at `osu.Game/Database/FileMounter.cs`

To test, open the editor for any beatmap, go to File -> mount files. Once the directory opens up, take any .osu present and open it in the editor. Change the circle size to 9, and save it. Then, go back to the editor and press File -> dismount files. You'll be forced out of the editor, to where you can see that the circle size of the map properly updates, but the BPM information and all hitobjects are removed. Remounting the files and inspecting the .osu again will also reflect that.

On my end, I seem to be getting a `System.IO.DirectoryNotFoundException` upon dismounting the files. But that can't be correct as the file mounter will [create any directories](https://github.com/smallketchup82/osu/blob/e49f431387c864d3f41c445b105cb5feeb46174e/osu.Game/Database/FileMounter.cs#L40-L44) that the files need or should be in.

I also get an error that the `.osu` couldn't be found in the right place, which doesn't make any sense, because remounting the files shows that the `.osu` does in fact exist where it's supposed to be, but that theres a lot of stuff deleted from it.

This is the full stacktrace on my end, but it's rather ambiguous:
```
[database] 2024-06-01 17:27:18 [error]: System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/folders/lh/m2n_gn5s60x0tlc9xm0jx5740000gn/T/A Match Into Water'.
[database] 2024-06-01 17:27:18 [error]: at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
[database] 2024-06-01 17:27:18 [error]: at System.IO.Enumeration.FileSystemEnumerator`1.Init()
[database] 2024-06-01 17:27:18 [error]: at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
[database] 2024-06-01 17:27:18 [error]: at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
[database] 2024-06-01 17:27:18 [error]: at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
[database] 2024-06-01 17:27:18 [error]: at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
[database] 2024-06-01 17:27:18 [error]: at osu.Game.IO.Archives.DirectoryArchiveReader.get_Filenames() in /Users/smallketchup/RiderProjects/osu/osu.Game/IO/Archives/DirectoryArchiveReader.cs:line 32
[database] 2024-06-01 17:27:18 [error]: at osu.Game.Beatmaps.BeatmapImporter.getDateAdded(ArchiveReader reader) in /Users/smallketchup/RiderProjects/osu/osu.Game/Beatmaps/BeatmapImporter.cs:line 325
[database] 2024-06-01 17:27:18 [error]: at osu.Game.Beatmaps.BeatmapImporter.Populate(BeatmapSetInfo beatmapSet, ArchiveReader archive, Realm realm, CancellationToken cancellationToken) in /Users/smallketchup/RiderProjects/osu/osu.Game/Beatmaps/BeatmapImporter.cs:line 156
[database] 2024-06-01 17:27:18 [error]: at osu.Game.Database.RealmArchiveModelImporter`1.<>c__DisplayClass27_0.<ImportModel>b__0(Realm realm) in /Users/smallketchup/RiderProjects/osu/osu.Game/Database/RealmArchiveModelImporter.cs:line 338
[runtime] 2024-06-01 17:27:18 [error]: Beatmap failed to load (file Pierce The Veil - A Match Into Water (puxtu) [pishi_s Extra].osu not found on disk at expected location 3/3b/3bacac205a19f082abf6f1f940f4b902f6a9e92c2ec9c0fa7c26191deaad143f).
[database] 2024-06-01 17:27:18 [error]: Could not import (A Match Into Water)
[database] 2024-06-01 17:27:18 [error]: System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/folders/lh/m2n_gn5s60x0tlc9xm0jx5740000gn/T/A Match Into Water'.
[database] 2024-06-01 17:27:18 [error]: at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
[database] 2024-06-01 17:27:18 [error]: at System.IO.Enumeration.FileSystemEnumerator`1.Init()
[database] 2024-06-01 17:27:18 [error]: at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
[database] 2024-06-01 17:27:18 [error]: at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
[database] 2024-06-01 17:27:18 [error]: at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
[database] 2024-06-01 17:27:18 [error]: at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
[database] 2024-06-01 17:27:18 [error]: at osu.Game.IO.Archives.DirectoryArchiveReader.get_Filenames() in /Users/smallketchup/RiderProjects/osu/osu.Game/IO/Archives/DirectoryArchiveReader.cs:line 32
[database] 2024-06-01 17:27:18 [error]: at osu.Game.Beatmaps.BeatmapImporter.getDateAdded(ArchiveReader reader) in /Users/smallketchup/RiderProjects/osu/osu.Game/Beatmaps/BeatmapImporter.cs:line 325
[database] 2024-06-01 17:27:18 [error]: at osu.Game.Beatmaps.BeatmapImporter.Populate(BeatmapSetInfo beatmapSet, ArchiveReader archive, Realm realm, CancellationToken cancellationToken) in /Users/smallketchup/RiderProjects/osu/osu.Game/Beatmaps/BeatmapImporter.cs:line 156
[database] 2024-06-01 17:27:18 [error]: at osu.Game.Database.RealmArchiveModelImporter`1.<>c__DisplayClass27_0.<ImportModel>b__0(Realm realm) in /Users/smallketchup/RiderProjects/osu/osu.Game/Database/RealmArchiveModelImporter.cs:line 338
[database] 2024-06-01 17:27:18 [error]: at osu.Game.Database.RealmAccess.Run[T](Func`2 action) in /Users/smallketchup/RiderProjects/osu/osu.Game/Database/RealmAccess.cs:line 444
[database] 2024-06-01 17:27:18 [error]: at osu.Game.Database.RealmArchiveModelImporter`1.ImportModel(TModel item, ArchiveReader archive, ImportParameters parameters, CancellationToken cancellationToken) in /Users/smallketchup/RiderProjects/osu/osu.Game/Database/RealmArchiveModelImporter.cs:line 262
[database] 2024-06-01 17:27:18 [error]: at osu.Game.Database.RealmArchiveModelImporter`1.<>c__DisplayClass26_0.<importFromArchive>b__0() in /Users/smallketchup/RiderProjects/osu/osu.Game/Database/RealmArchiveModelImporter.cs:line 247
[database] 2024-06-01 17:27:18 [error]: at System.Threading.Tasks.Task`1.InnerInvoke()
[database] 2024-06-01 17:27:18 [error]: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[database] 2024-06-01 17:27:18 [error]: --- End of stack trace from previous location ---
[database] 2024-06-01 17:27:18 [error]: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[database] 2024-06-01 17:27:18 [error]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[database] 2024-06-01 17:27:18 [error]: --- End of stack trace from previous location ---
[database] 2024-06-01 17:27:18 [error]: at osu.Game.Database.RealmArchiveModelImporter`1.importFromArchive(ArchiveReader archive, ImportParameters parameters, CancellationToken cancellationToken) in /Users/smallketchup/RiderProjects/osu/osu.Game/Database/RealmArchiveModelImporter.cs:line 252
[database] 2024-06-01 17:27:18 [error]: at osu.Game.Database.RealmArchiveModelImporter`1.Import(ImportTask task, ImportParameters parameters, CancellationToken cancellationToken) in /Users/smallketchup/RiderProjects/osu/osu.Game/Database/RealmArchiveModelImporter.cs:line 196
[database] 2024-06-01 17:27:18 [error]: at osu.Game.Database.RealmArchiveModelImporter`1.<>c__DisplayClass23_0.<<Import>b__0>d.MoveNext() in /Users/smallketchup/RiderProjects/osu/osu.Game/Database/RealmArchiveModelImporter.cs:line 123
```

**Comment by peppy** [comment]
@smallketchup82 tracked the issue down in minutes. if it's saying the file doesn't exist, it doesn't, so i checked on disk and you're doubling the `files` directory in storage:

![Finder 2024-06-03 at 06 40 15](https://github.com/ppy/osu/assets/191335/deb037c3-8b2b-4fde-9905-028d0a2c0879)


```diff
diff --git a/osu.Game/Database/FileMounter.cs b/osu.Game/Database/FileMounter.cs
index 93c5fe195b..08857ac073 100644
--- a/osu.Game/Database/FileMounter.cs
+++ b/osu.Game/Database/FileMounter.cs
@@ -16,7 +16,7 @@ namespace osu.Game.Database
     public class FileMounter(RealmAccess realmAccess, Storage storage, BeatmapManager beatmapManager)
     {
         private readonly BeatmapManager beatmapManager = beatmapManager;
-        private readonly Storage storage = storage.GetStorageForDirectory(@"files");
+        private readonly Storage storage = storage;
         private readonly string tempDirectory = Path.GetTempPath();
 
         /// <summary>
@@ -30,9 +30,11 @@ public void MountBeatmapSet(BeatmapSetInfo beatmapSetInfo)
             if (Directory.Exists(beatmapSetDirectory)) Directory.Delete(beatmapSetDirectory, true);
             Directory.CreateDirectory(beatmapSetDirectory);
 
+            var fileStorage = storage.GetStorageForDirectory("files");
+
             foreach (var realmFile in beatmapSetInfo.Files)
             {
-                string fullPath = storage.GetFullPath(realmFile.File.GetStoragePath());
+                string fullPath = fileStorage.GetFullPath(realmFile.File.GetStoragePath());
                 Logger.Log("Mounting file " + fullPath);
 
                 string destination = Path.Join(beatmapSetDirectory, realmFile.Filename);

```

**Comment by smallketchup82** [comment]
> so i checked on disk and you're doubling the files directory in storage

:facepalm: 

> Also please don't use new c# features like class level constructors. 

Got it.

I guess I'll give this another go then

**Comment by smallketchup82** [comment]
So I have exams and will have to wait on this for a bit, but I'll get started on it again in a few weeks. In the meantime, I'm going to note down some considerations I should probably take when developing this, let me know if I should make any changes in my approaches here.

- The current way of using a menu button works, but we have the issue of players being able to edit the map in the editor while the files are mounted.
  - I was originally thinking of just blanking out the game window while files are mounted, but that comes with the issue of also blanking out the menu buttons.
  - We could just disable saving the beatmap manually until the files are dismounted. This is an easy change and would probably fix the issue. It might not be the best in terms of UX but it gets the job done infra side.
  - My last idea would be to add a new screen for file mounting. By adding a new screen we could also add in some nifty features like a linting/validation button which checks to make sure that the `.osu` has proper syntax, and reports any discrepancies to the user. Only issue is that I've never worked with screens/UI's so something like this would take me a while to implement in comparison to just disabling saving
- The user can exit the editor or quit the game while the files are still mounted
  - I don't really care about the files persisting if the game quits, since the files are put in the temp directory anyways. But deleting the directory when the user exits the editor is easy to implement. Currently my code fixes this.

I'll probably edit this and add more as I go, but these are some concerns that I've got so far

**Comment by peppy** [comment]
I think pushing a temporary screen is probably going to work best in terms of isolating user interaction, but see how you fare.

**Comment by peppy** [comment]
@smallketchup82 are you still intending to work on this? if not I may try and get your branch/feature into a usable state.

**Comment by smallketchup82** [comment]
Yesterday, It was mentioned that it's planned to move lazer's update system from what we have now to velopack. That personally got me interested, so I've been working towards that instead.

You can fork my branch and continue developing.
