### ISSUE TITLE
Position in (global) leaderboard does not match shown position

### ISSUE THREAD

**Issue by BlauFx** [ppy/osu#19168]
### Type

Game behaviour

### Bug description

In the global leaderboard the position is listed as 46 and 49.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/34138240/179374464-3fbdc79d-ef49-467a-abdd-cd5ff79e3726.png)

### Version

2022.716.1-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/9126733/runtime.log)
[performance.log](https://github.com/ppy/osu/files/9126734/performance.log)
[network.log](https://github.com/ppy/osu/files/9126735/network.log)

**Comment by frenzibyte** [comment]
The position shown in "personal best" is returned directly from the server, while the ones in the leaderboard are computed based on the scores returned from the server ordered by total score. 

My only guess is that some scores are not shown due to reindexing (although that should've been done 1-2 days ago already), but could potentially be other problems such as server determining position via different method than how client does it. 

cc @peppy

**Comment by peppy** [comment]
Probably going to have to deflect to @nanaya to take a look into this one. Could be any number of things, but definitely something osu-web end.

**Comment by nanaya** [comment]
that's weird, when the user score is already part of the (top 50) leaderboard, it checks the position in the leaderboard itself so it should always be correct...

**Comment by frenzibyte** [comment]
It should be refetching the user's own score along with the leaderboard scores from the API (via the `/api/v2/solo-scores` endpoint) at the point of selecting the beatmap in the screen, so no caching if I understand correctly. 

@BlauFx please check whether this is still the case.

**Comment by BlauFx** [comment]
It is still weird.
![osu_2022-07-18_10-06-13](https://user-images.githubusercontent.com/34138240/179489783-0e5fc4d5-68ea-4ccd-8cc7-db78a8994e32.png)

It is just the global leaderboard that has this issue. For example country leaderboard works fine.
![osu_2022-07-18_10-06-22](https://user-images.githubusercontent.com/34138240/179489881-a72d7c6b-0229-4e47-a25a-68f898190e24.png)

**Comment by peppy** [comment]
So what's going on here is that the total score stored in the database doesn't match the locally calculated total score. For displaying leaderboards, the total score is always recalculated by the client, which is why this discrepancy is visible.

I haven't yet looked into why they don't match (probably old scores in the database with incorrect values, though).

**Comment by peppy** [comment]
This will be fixed when we reprocess scores and with the introduction of server-authority over score calculation (via #19380 and whatever follow). Going to close for now.

**Comment by peppy** [comment]
See #19519.
