### ISSUE TITLE
Cursor stop moving for a second every second with tablet

### ISSUE THREAD

**Issue by SyrokVincent** [ppy/osu#19186]
### Type

Game behaviour

### Bug description

I'm on windows 8.1 and my tablet is a "Bamboo wacom CHT-461" 

When using the tablet my cursor stop moving aproximatly every 1 second  for 1 second. It alternate between being able to move and being stuck in place. While the cursor stop moving I'm a still able to click with the tablet, so it's only the "moving" that is affected.

My tablet is pretty old and is not detected in the game settings but was working perfectly fine before this version/update

### Version

2022.716.1

### Logs

[performance-input.log](https://github.com/ppy/osu/files/9127543/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9127544/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9127545/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9127546/updater.log)
[database.log](https://github.com/ppy/osu/files/9127547/database.log)
[network.log](https://github.com/ppy/osu/files/9127548/network.log)
[performance.log](https://github.com/ppy/osu/files/9127549/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/9127550/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9127551/performance-draw.log)

**Comment by Susko3** [comment]
Disable `High precision mouse` in osu! settings and see if it helps. I can reproduce a similar issue with my wacom.

**Comment by SyrokVincent** [comment]
Thank you, disabling that option solved the problem, 
and sorry I probably should have played a bit more with the settings before oppening an issue

**Comment by approachcircle** [comment]
@Susko3 if you disable "high precision mouse" in settings, it doesn't allow you to change your sensitivity, which is quite a big issue for people playing on tablet that have a custom sensitivity

**Comment by approachcircle** [comment]
@SyrokVincent you can leave this issue open, as disabling "high precision mouse" implies that you have the issue, you play on tablet, and you haven't got a custom sensitivity set

**Comment by Susko3** [comment]
Those wanting to have more control over their tablet should use in-game tablet support. The tablet in question is supported by [OpenTabletDriver](http://opentabletdriver.net/Tablets?search=cth-461).

Or they can adjust their tablet area in the driver in lieu of in-game sensitivity.

If both of those solutions don't work for you, please open a new issue or discussion.

**Comment by approachcircle** [comment]
so you're saying that from now on, you won't ever be able to have your tablet area decided by your tablet's driver, and use the cursor sensitivity to fine-tune it, and instead, you now need to purely use the built-in OpenTabletDriver to reselect your tablet area, and you aren't able to use cursor sensitivity because it freezes your cursor every so often?

**Comment by frenzibyte** [comment]
Cursor sensitivity shouldn't be used to control tablet area, I can't even imagine how you intend to have it work that way (that setting is for relative input devices, tablet is an absolute input device). Either you use `OpenTabletDriver` externally and disable "raw input", or use in-game tablet driver and not deal with disabling that. As for tablet area, you'll have to figure out a roughly matching tablet area without the cursor sensitivity you have applied.

**Comment by approachcircle** [comment]
i understand that using cursor sensitivity to control an absolute input device isn't the best idea, but i have had it setup that way in stable ever since i started playing with a tablet a while ago, and i had the sensitivity setup in exactly the same way in lazer to keep the tablet area consistent, but now that the cursor freezes every now and again when you have high precision mouse enabled, i'm never going to have an exact consistency with tablet area between lazer and stable because of the offset that the cursor sensitivity provides as a neat single value

**Comment by tsunyoku** [comment]
If you want to get a somewhat near area, multiply your length and width by whatever sensitivity you were using. That is the best you will get.

**Comment by tsunyoku** [comment]
divide* not multiply

**Comment by approachcircle** [comment]
i suppose it'll do

**Comment by jamesbt365** [comment]
Actually, it is exactly the same area with just correct precision so it may feel off but its right.

**Comment by approachcircle** [comment]
oh okay, that's good to know
