### ISSUE TITLE
Animations in storyboards are offset from the same animations in osu!stable

### ISSUE THREAD

**Issue by blueberrymuffin3** [ppy/osu#19366]
### Type

Cosmetic

### Bug description

The start time for Animations in storyboards seems to be calculated differently in osu!stable and osu!lazer. In [this beatmap](https://osu.ppy.sh/beatmapsets/470977#osu/1010030), This affects the appearance of certain parts of the beatmap.

### Screenshots or videos

Correctly rendered in osu!stable:
![image](https://user-images.githubusercontent.com/12852902/180693685-a222a0f8-d4ca-4db5-b8a8-c76cdb317f82.png)

Incorrectly rendered in osu!lazer (Notice how the 1's and 0's form vertical "columns"):
![image](https://user-images.githubusercontent.com/12852902/180694183-15dfced4-001b-4562-b94d-930369650f74.png)

### Version

2022.723.0.0

### Logs

[database.log](https://github.com/ppy/osu/files/9177828/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9177829/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9177830/network.log)
[performance.log](https://github.com/ppy/osu/files/9177831/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9177832/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9177833/updater.log)

**Comment by smoogipoo** [comment]
Whoa. This is a recent regression because this map is part of my regular testing.

**Comment by kionell** [comment]
Actually, I was able to find the reason a month ago. Just saw #20156 and thought it solved the problem, but unfortunately it didn't.
The problem is incorrect starting time of storyboard sprites and appears because of [this](https://github.com/ppy/osu/blob/master/osu.Game/Storyboards/StoryboardSprite.cs#L33-L55) code. Removing it completely solves the problem with all animations on the map.
![image](https://user-images.githubusercontent.com/43014304/189504581-cc7f5711-d21d-40db-b1f6-839b0ee654b5.png)

**Comment by smoogipoo** [comment]
@peppy want to take a quick look into this and see if anything comes up? You're more well-versed in this than I am.

**Comment by peppy** [comment]
Yeah, it's on my list while my mind is still fresh with the logic.

**Comment by peppy** [comment]
As per the comment above, this is due to the start time optimisation behaving differently from stable. While we consider storyboard elements to only require updating from when they first have an alpha, stable seems to be running them invisibly before their initial alpha, which causes animation time to update even when they are not visible, causing the interleaving seen in that storyboard.

```csharp
Animation,Background,Centre,"SB\z.png",320,240,2,150,LoopForever
 S,0,81325,85165,0.08 // first transform, when stable would start tracking the animation
 C,0,81472,85165,255,255,255
 P,0,81472,85165,A
 F,0,82102,82852,0,1 // first alpha
 M,1,82102,83102,-143.84,362.854,317.7,170.55
 F,0,84665,85165,1,0
```

At the point we should probably just drop the optimisation and make it take the earliest transform time? That said, I know the optimisation was added for a specific case where *not having it* caused a performance issue, so removing it would require first finding and revisiting that case.

**Comment by peppy** [comment]
This goes pretty deep into framework `Animation` as well. I can fix it locally but it will fail depending on whether fast forward is involved or not on the first execution. Will spend a bit longer and see if I can find an amicable fix..
