### ISSUE TITLE
Volume meter keybindings take precedence over ruleset keybindings

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#19362]
### Discussed in https://github.com/ppy/osu/discussions/19336

<div type='discussions-op-text'>

<sup>Originally posted by **Nekomosh004** July 23, 2022</sup>
Unlike Stable/CE, adjusting the volume in lazer keeps the options up when playing in osu!catch because we use the left and right arrow keys (by default) to control the catcher. I think its best described on these videos:

**What lazer do:**

https://user-images.githubusercontent.com/82471957/180611401-96b6ef9e-cc98-493f-8c34-fa8af575d8b6.mp4

**What Stable/Cutting Edge do:**

https://user-images.githubusercontent.com/82471957/180611626-3c92f15b-557d-450f-8665-dfef00881db6.mp4

I think its better if the options were auto-hidden mid any gameplay. Thank you for your attention on this! :D</div>

**Comment by peppy** [comment]
Copying across my response in the closed issue:

In stable, the volume overlay can still be shown during gameplay. The only thing being blocked is the left and right arrows, and only in catch where they are used by gameplay. As in, during non-catch gameplay you can still navigate left and right between volume controls unless those keys are used as gameplay bindings.

This should be fixed by giving gameplay bindings precedence over the volume controls if anything. I don't know how simple that is with the order of processing right now, would need to be tested.

**Comment by AndrewHack242** [comment]
This is the main reason I have not switched to lazer yet.
