### ISSUE TITLE
Can only add one item to playlist

### ISSUE THREAD

**Issue by mangoepic** [ppy/osu#19458]
### Type

Game behaviour

### Bug description

I tried to create a playlist in osu! mania, but could only add one track to the playlist
Adding another song by clicking "Edit Playlist" just did overwrite the previous one
(After submitting the playlist the songs wouldn't appear either)

### Screenshots or videos

https://user-images.githubusercontent.com/71931749/181757690-c6091764-a10c-4168-8ec2-403a4a7e0562.mp4

### Version

2022.723.0 (23 July 2022)

### Logs

[database.log](https://github.com/ppy/osu/files/9219842/database.log)
[network.log](https://github.com/ppy/osu/files/9219843/network.log)
[performance.log](https://github.com/ppy/osu/files/9219844/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9219848/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9219850/updater.log)

**Comment by frenzibyte** [comment]
When editing a playlist, you're modifying the last item you added. In order to add a new item, select the beatmap you want to add and then press the following button:

<img width="493" alt="CleanShot 2022-07-29 at 15 27 10@2x" src="https://user-images.githubusercontent.com/22781491/181758191-283cb0e9-2e54-464d-b13d-78a2bc9c6dc2.png">

Once you're done, click on the "osu!" cookie.

**Comment by mangoepic** [comment]
Oh got it 👍 I think it's a bit unexpected UX wise though since there are two playlists now, maybe pressing enter on a song should add it to the playlist on the left side
