### ISSUE TITLE
Lag spike before fast slider

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#19585]
### Type

Performance

### Bug description

This map contains fast slider - https://osu.ppy.sh/beatmapsets/409227#osu/889632 on 01:26:780, but lag spike happen on 01:25:559 (even in editor)

I pressed Ctrl+F2 and noticed that at the time of the spike, 13000 something is loaded.

### Screenshots or videos

![Inkedosu_2022-08-05_09-10-04](https://user-images.githubusercontent.com/59089206/183013751-e0d20122-c680-46ed-bea2-42524d43a9a2.jpg)

https://user-images.githubusercontent.com/59089206/183013886-49474164-aa1a-4ff0-af06-347148b3b705.mp4

### Version

2022.731.1

### Logs

I don't think they are needed here.

**Comment by peppy** [comment]
The root cause here is that the slider in that beatmap has around 200 repeats, which exceeds the available pool and forced immediate creation at that point in time, causing a lag spike depending on how powerful your CPU is.

Can you confirm that you can feel the lag spike with the global statistics view *closed*? I ask this because having that overlay open adds huge overheads and should not be left open when actually testing performance.

**Comment by Moltanicaa** [comment]
Yes, it is felt during the game, which is why I paid attention to it.
