### ISSUE TITLE
Multiplayer star rating does not initially update for the host

### ISSUE THREAD

**Issue by NiceAesth** [ppy/osu#19601]
### Type

Cosmetic

### Bug description

If you create a multiplayer lobby, the star rating does not display the actual star rating of the beatmap, but instead shows 0.00

### Screenshots or videos

![osu_2022-08-06_13-09-11](https://user-images.githubusercontent.com/8437201/183244466-ad66d85a-0c49-45a9-953e-4fe6849ce31c.jpg)

https://user-images.githubusercontent.com/8437201/183244524-fbab70ba-f056-4850-ac10-7266d3789280.mp4

### Version

2022.731.1

### Logs

[legacy-ipc.log](https://github.com/ppy/osu/files/9274811/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9274812/network.log)
[performance.log](https://github.com/ppy/osu/files/9274813/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9274815/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9274816/updater.log)
[database.log](https://github.com/ppy/osu/files/9274817/database.log)

**Comment by its5Q** [comment]
I've done some digging around, and I think I found the cause of this problem.
https://github.com/ppy/osu/blob/9ac322d337e348f63d824e5995942c2ee367dc2a/osu.Game/Screens/OnlinePlay/Components/StarRatingRangeDisplay.cs#L95-L100
There, it's trying to get beatmaps from room's playlist, but as said in the comment, some beatmaps could be unpopulated. Because the code doesn't check if the beatmap is populated, it sets the displayed difficulty to 0.
Another thing I noticed, while you create the room, you get 3 playlist updates, with one of them containing populated beatmaps. But if you edit the playlist or add/remove beatmaps, the updates won't contain populated beatmaps. So, just checking if beatmaps are populated won't cut it, because if you change the playlist after room creation, the star rating won't update.

**Comment by smoogipoo** [comment]
We can't really query the API like that comment suggests there. There's a bit of an optimisation where the panels in the queue also don't load/query until they're scrolled to, to avoid querying MB of data at once.

For rooms in the lounge listing... osu-web actually serialises a difficulty range along with the room. `MultiplayerRoom` currently has no such things.

Options are:
- Add `RoomDifficultyRange` to `MultiplayerRoom`, have `osu-server-spectator` populate it.
- Add `StarRating` to `MultiplayerPlaylistItem`.

Tending towards the first, but it also means every playlist update is one more SignalR callback to the client, so I'm not sure that's the best option. The second option is a bit more efficient.

Also have to consider - and this is also something that osu!web doesn't consider - that lazer has many more mod combinations than actually stored in the database. So _something_ will eventually have to compute difficulties with lazer mods, meaning it may also be an interesting time to make use of `osu-beatmap-difficulty-lookup-cache`.  
But for now I suppose returning the beatmap's unmodded difficulty is fine (as osu-web does).
