### ISSUE TITLE
Incorrect statistics in replay

### ISSUE THREAD

**Issue by thiccyoshi4568** [ppy/osu#19766]
### Type

Game behaviour

### Bug description

Got a score with 95.00% and watched the replay. The accuracy after the replay somehow increased to 95.13%. Looking at the screen recording, it seems that the judgement counts changed. I'm so sorry for the watermarks and bad video quality by the way.

### Screenshots or videos

![osu_2022-08-15_12-19-05](https://user-images.githubusercontent.com/94721605/184569172-ceb33c12-f907-42e4-a21e-3560d52ea3a7.jpg)

![osu_2022-08-15_12-18-56](https://user-images.githubusercontent.com/94721605/184569159-04a0a610-6208-46b6-a80c-485efc5a4b27.jpg)

https://user-images.githubusercontent.com/94721605/184568655-c1945ffe-1c98-4f21-ba20-1802b1d6f248.mp4

### Version

2022.810.2-lazer

### Logs

[performance-audio.log](https://github.com/ppy/osu/files/9334806/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9334807/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9334808/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9334809/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9334810/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9334811/updater.log)
[database.log](https://github.com/ppy/osu/files/9334812/database.log)
[network.log](https://github.com/ppy/osu/files/9334813/network.log)
[performance.log](https://github.com/ppy/osu/files/9334814/performance.log)

**Comment by Sobsz** [comment]
Another example in `2022.923.1-lazer`: [Sobsz playing EMILIA (CV_ Takahashi Rie) - Stay Alive (Seto Kousuke) [Insane].zip](https://github.com/ppy/osu/files/9646303/Sobsz.playing.EMILIA.CV_.Takahashi.Rie.-.Stay.Alive.Seto.Kousuke.Insane.zip)

In the actual play, I failed just before the end, but the replay fails 12 seconds before the end instead:

![osu_2022-09-26_14-53-11](https://user-images.githubusercontent.com/18291848/192281641-8a42c597-fd39-4588-9628-dd1d0a04f9bd.png)

Additionally, skipping to the very end leads to a pass:

![osu_2022-09-26_14-54-33](https://user-images.githubusercontent.com/18291848/192281760-3e5f3c98-32d7-4e5d-b095-ba2f98bbbce2.png)

[performance-audio.log](https://github.com/ppy/osu/files/9646281/performance-audio.log)
[performance-update.log](https://github.com/ppy/osu/files/9646282/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9646283/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9646284/updater.log)
[database.log](https://github.com/ppy/osu/files/9646285/database.log)
[network.log](https://github.com/ppy/osu/files/9646286/network.log)
[performance.log](https://github.com/ppy/osu/files/9646287/performance.log)

**Comment by peppy** [comment]
Probably warrants investigating as these may be incorrectly being sent to the server too.

**Comment by smoogipoo** [comment]
I'm investigating this one.

Part of the issue seems to be the `AllowedImportantTimeSpan` check which exhibits different behaviours with/without fast forwarding:
https://github.com/ppy/osu/blob/f3184525107b29018d7271e7bbcf779eec7ad1d8/osu.Game/Rulesets/Replays/FramedReplayInputHandler.cs#L113-L114

Another part of the issue seems to be... Matrix-transform related? At least one of the hits in the above replay is a pixel hit, which somehow changes depending on fast forward or not.

**Comment by ekrctb** [comment]
> Another part of the issue seems to be slider start circles tracking slightly in non-ffwd when compared to ffwd. Likely the slider having one more update frame in the non-ffwd case.

is tracked in #13352

**Comment by Detze** [comment]
The OP is just https://github.com/ppy/osu/issues/11311#issuecomment-1888399637 (map is OD 7, gameplay's Perfect hit window is 17.2 ms, replay's is 17.5 ms due to rounding, rest are all 0.5 ms wider in replay than gameplay due to rounding, so replay accuracy is better across the board - stable would be the same as replay, but fewer Perfects due to differing Perfect hit window formula).

**Comment by bdach** [comment]
closing as duplicate
