### ISSUE TITLE
Decide whether we want to keep passive health drain

### ISSUE THREAD

**Issue by peppy** [ppy/osu#1990]
Until now, osu! has had passive health drain (ie. the health bar drains constantly during play time and the user must keep hitting to keep the game from failing). We need to decide whether want to keep this going forward. Discussion is welcome.

Pros
- Creates a sense of urgency
- Can be very thrilling
- Makes the health bar more of a dynamic element (even when the user is getting 300s it still has movement)

Cons
- Implementation is complex
- Hard for a user or mapper to understand
- Can piss people off that don't like the sense of urgency

**Comment by jorolf** [comment]
Passive drain can be really frustrating when you nearly fail a hard part and it's followed by a slow part. You die a slow death because you can't refill your health eventhough you only hit 300s

**Comment by peppy** [comment]
If you only hit 300s you can't fail.

**Comment by Frontear** [comment]
There used to be an issue with Health drain, and the way it was implemented in the old OSU client. I'm thinking, it really is a nice thing to have, mainly since most users are comfortable with it anyways. If this were to be getting implemented, something needs to be done about the bug. Not certain if it has already been fixed or not, and since I personally don't have much insight, the most I can do right now is link phisifat's video about health drain, which went into detail exploring the reasons for the odd rapid draining of health (https://m.youtube.com/watch?v=1h9fJ31WOMc). I personally think it should be kept around, just because of how used to it many players are. It also keeps players on edge most of the game, knowing they are never really safe, and such kind of pressure could force them into playing better.

**Comment by Yutsuten** [comment]
I personally like the passive health drain, even though I've already lost some maps because of it (exactly as jorolf described).
With high health drain and after a difficult part (low health), the drain was taking more life than I could recover, even by hitting all 300.

But if the mapper have set the health drain high and created such circumstance, I see it as a challenge...

**Comment by UselessToucan** [comment]
@peppy What do you plan to do with existing scores/ranking after this change? I mean, you already have a lot of scores which were set with passive health drain. You can't just drop them. And you also can't just mix them with new scores without passive drain.

**Comment by Aergwyn** [comment]
I quite liked Drain but there are a few scenarios were it can be weird. Maps where the drain is just extreme and only a handful of 100s fails you or spinners where you just inevitably lose if you don't reach something like 400 RPM over the entire duration.

**Comment by thatprogrammer1** [comment]
Agreeing with @Aergwyn , just the few edge cases that make drain annoying to play. The first is long spinners, I don't see a problem in just disabling hp drain during a spinner or lowering the amount of RPM to counteract the drain. The second is having the drain above 7, which makes it a challenge to pass maps even when you can get above ~96% acc. The second is kind of a problem with hard rock, which raises hp drain. We could create a lower maximum for whenever hard rock is applied.

**Comment by thatprogrammer1** [comment]
@UselessToucan I don't see a problem with mixing scores, removing passive drain really only affects the people that had good runs and then failed.

**Comment by cferret** [comment]
Drain isn't usually a problem, but a few fringe cases (MENDES and FIRST HR come to mind) spinners are especially broken. I would definitely at least remove spinner drain. High HP is sometimes annoying since you can fail 95% FCs just because of accuracy, or a 98% FC because of a single miss. In my opinion, maps that you can play reasonably well (90+%) shouldn't be failed on unless you completely miss a pattern. I personally think passive drain should be removed completely, but a lower maximum HP rating would be fine as well.

**Comment by Toybickler** [comment]
Drain is generally alright aside from maps on HP 10 HR with a long spinner, slow slider, or low BPM.

You could try to scale drain by note density, so that it'll drain faster during faster sections (where you have more opportunity to hit 300s and stay alive) and make it essentially cancel out on sections with an ending spinner or slider.

**Comment by Kverto** [comment]
Absolutely not, it is very punishing and the rate of drain is pretty arbitrary right now. I have failed 5+ minutes long maps with 99,5+% full combo just because I cannot spin at a certain speed.

It also limits mappers, since they need to play around the drain system so their maps would be playable.

**Comment by Leggo15** [comment]
I vote to keep the passive drain, reasons: all the pros u listed. the passive drain adds so much to the game!
Keep up the good work x3 Lazer looks awesome!!

**Comment by Yusomi** [comment]
@peppy How about hp drains to a minimum of 33%~ HP then you must actually miss/get bad acc to make it go below that. This way spinners can't kill you unless you are so slow you don't even clear it. This also keeps the dynamic hp bar that Toy said he liked

**Comment by VortexCoyote** [comment]
The "Can piss people off that don't like the sense of urgency" is enough to remove passive drain imo. It's one of the factors that made me switch to mania. I also think it's bad from a game design perspective. If a player hits all the notes on a slow part and fails, it gives the player the _perception_ that the game is faulty, thus making osu an "unfair game". Also, I've noticed that maps can become exponentially more difficult by increasing the HP drain - A 4* map can differ very much in difficulty compared to another 4* map, which can ruin a "natural difficulty progression". But I also think mappers have a responsibility to some degree. Though, "Hard for a user or mapper to understand" is enough of an argument for that. 

Passive drain is something that should be removed, mainly because it promotes "bad game design" and can demotivate players.

**Comment by LittleEndu** [comment]
If I get it correctly the current hp drain is constant through all of the map. What about making it variable?  I would assume since hp setting being per hit object that it wouldn't seem weird to the player to see that hp drain is slower in the slow part and faster during kiai

**Comment by progamor** [comment]
if hp drain is to be left in, they shouldn't be in with spinners. A spinner shouldn't kill you unless you miss the spinner, especially if the map has been full combo'd/SS'ed.  Personally i'd take it out and make it that missing notes decrease hp heavily while hitting adds the hp back in small parts

**Comment by peppy** [comment]
So the main take I have for this is that most people like drain as long as spinners are fixed. Good to know, we'll use this knowledge to come to a decision 👍

**Comment by Toybickler** [comment]
It's not just spinners, you can fail out of SS with really long slow sliders as well.

**Comment by pyrates313** [comment]
I think it should be changed for variables like spinners as others mentioned as it makes little sense failing songs at one part like that.

One upside to hp drain that I see is that it, besides of keeping the thrilling part, helps against mashing your way through the song, which as it seems really also becomes relevant with the current hdhrdt plays. Taking away the hp part and allowing more 80% passes/fc's with that pp scaling could lead to some high scores which are not really representing any rhythm in a rhythm game and are still highly rewarded.

**Comment by Kverto** [comment]
What about being able to choose between a battery or a conventional system? The type of pass could be displayed next to the score and players could filter if they only want to see one type.

**Comment by peppy** [comment]
Thanks for the discussion, but I've already got enough information here for now. There will likely be a toggle for passive drain, if anything.

**Comment by ahmedgamedev** [comment]
thank u

**Comment by LukerMaster** [comment]
Okay, maybe this is gonna work well:

Create a value that is gonna contain time between hitobjects. Call it hpDelta. Everytime you hit/miss it resets to 0. After that it starts to increase until the next object needs to be clicked. Then (depending on if you hit/miss) your HP will be decreased/increased by the amount of hpDelta. The more time there was between objects, the more HP you will get/lose
Result:
Missing fast streams will be punished much less and recovering in long streams will be easier.
"Slow" parts will give you a lot more HP even with great HP drain but missing there will punish you very hard.
HP bar is gonna be dynamic object

What about spinners/long sliders? Simple:
After around 2 seconds of holding single slider/spinner overall HP drain will start to decrease significantly over time (down to 0 at sliders) allowing you to slowly reduce the drain and even refill HP with spinning or just watch HP drain slowly stops on a very long slider.

**Comment by Nogooduser** [comment]
I'm gonna go a little bit against the current here (please don't kill me). I think there's a decent case to be made for removing the HP bar, because ultimately osu should be a rhythm game, not a "try not to die during this song" game. 

Sometimes it feels like the HP bar is an added obstacle because you know you can lose mid song during a hard section, and when that happens it can create a lot of frustration for players. Beyond that, there's been so many great examples of people failing right at the end of a song, not even because of death spinners (those are also problematic), but because they just slip up accidentally and it ends up ruining the entire thing because HP is a factor in the game. Some maps have also gotten a bad reputation for their unforgiving HP drain. This all results in many people who just want to play and improve on a map feeling annoyed and angry. Personally I also feel the HP bar often detracts me from focusing on playing the map and adds unnecessary tension a lot of the times. I know some will call it thrill, but that's where opinions diverge I guess (that's why we're having this discussion).

I know some might say "well if you just get better then you won't die" or "just use no fail" but I think that's missing the point a little. I don't think it's fair to, say, lose on a 10 min song because you slipped up on the last 30 seconds even though you were FCing the song up until then (yes, this is a very edge case, but I'm just trying to put things into perspective). The penalty for missing that bit should be reflected on your score, acc and pp received of course, but why must you be punished by having such an amazing play never be submitted to the leaderboards? It seems a bit unfair and I don't think it's justified by telling someone to "just get better" because it's likely the person is good enough to pass but they just had poor luck, it happens to all of us, but because of the HP bar being a factor that person now will never get to submit their score and who knows when they'll be able to get another chance to do it again.

There are other rhythm games that have no HP bar that can be incredibly challenging because the whole focus is on getting good accuracy. Others have a minimum amount of accuracy you need to hit to submit your score (or pass a song if you will). Removing the HP bar in these games simply means (at least in my personal experience) that the focus is shifted on getting increasingly better at playing the map so you can improve all the metrics until you get that sweet 100%.

I guess what I'm trying to say is that, in the end, I feel like letting osu be focused solely on getting good at maps without the pressure from an HP bar could really add to the enjoyment of many users and wouldn't really detract from the core of the game at all.

I am not at all opposed to just tweaking how HP drain works, or how spinners/sliders/circles affect said drain, that would improve a lot of things as well, I'm just saying that not having the HP bar wouldn't really ruin the game in my view.

**Comment by peppy** [comment]
There's a mod for that, called no fail.

Losing due to hp means you are already doing very badly, anyway.
