### ISSUE TITLE
Weird fullscreen behavior on Intel GPU

### ISSUE THREAD

**Issue by girlbossdev** [ppy/osu#19978]
### Type

Game behaviour

### Bug description

Every time the game goes in or out of focus (such as when opening/closing it or alt-tabbing) it appears to do something to mess with the display mode (external monitor goes blank for a few seconds, laptop screen flickers) 

OS: Windows 11 Pro
CPU: i3-8145u
GPU: Intel UHD Graphics 620 (latest driver - 31.0.101.2111)

### Version

2022.821.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/9436238/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9436239/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9436240/updater.log)
[database.log](https://github.com/ppy/osu/files/9436241/database.log)
[network.log](https://github.com/ppy/osu/files/9436242/network.log)

**Comment by peppy** [comment]
We currently do some weird stuff when entering/exiting fullscreen mode to ensure compatibility, but it definitely does switch between display modes at least one time too many.

**Comment by Lunaero1** [comment]
> We currently do some weird stuff when entering/exiting fullscreen mode to ensure compatibility, but it definitely does switch between display modes at least one time too many.

Just for the record I got a new computer recently and am not using a dedicated GPU, instead the intel iGPU in my processor, (I have an i3 with intel hd 4400) and I am experiencing the same things, except sometimes I also just get a black screen that's only fixed by restarting the game regardless of window mode. Same thing happens on my laptop too which has the intel hd 530 graphics chipset. (I don't mind this reply comment getting deleted btw, I just wanted to bring this to your attention)
Tbh it is quite annoying..

**Comment by mirh** [comment]
> Every time the game goes in or out of focus (such as when opening/closing it or alt-tabbing) it appears to do something to mess with the display mode

Sounds like exclusive fullscreen for you...
Even though it shouldn't be all that much of a big deal. Maybe the resolution timing in the game is ever so slightly different than the one of the desktop (causing a full mode switch).
