### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by ImPalyYT** [ppy/osu#20001]
### Type

Performance

### Bug description

I always have 1 - 7 fps.

Cpu: Intel Celeron Processor 900
Ram: 3Gb
.Net Version: 6
GPU: Mobile Intel 4 Series Express Chipset Family

### Version

2022.821.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/9439769/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9439770/updater.log)
[database.log](https://github.com/ppy/osu/files/9439771/database.log)
[network.log](https://github.com/ppy/osu/files/9439773/network.log)
[performance.log](https://github.com/ppy/osu/files/9439774/performance.log)

**Comment by bdach** [comment]
Performance work is a constant work in progress. We're aware that older devices may struggle to keep up with running lazer as is, and there are a few things lined up (such as compatibility mode) that may help. That said, I'm closing this issue because there is no single simple fix for this and issues like that generally don't work for us from a development process standpoint.

**Comment by smoogipoo** [comment]
You are lacking hardware acceleration, and, based on the runtime log, appears as if you're running under a virtualisation layer (WSL?). The configuration you're running is not supported, and you'll probably have to wait for us to switch rendering backends before you can get reasonable performance.
