### ISSUE TITLE
Repel/Magnetised/Depth mods prevents hit judgements from showing

### ISSUE THREAD

**Issue by Doksha** [ppy/osu#20139]
### Type

Cosmetic

### Bug description

if you enable the repel mod, hit judgements do not show.

### Version

2022.902.1-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/9486702/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9486703/updater.log)
[database.log](https://github.com/ppy/osu/files/9486704/database.log)
[network.log](https://github.com/ppy/osu/files/9486705/network.log)
[performance.log](https://github.com/ppy/osu/files/9486706/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/9486707/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/9486708/performance-update.log)

**Comment by smoogipoo** [comment]
Yeah, this is intentional (due to replays I think?) but I'm hoping this can be addressed better.

**Comment by integerrr** [comment]
Related: 
- #16812

**Comment by Doksha** [comment]
yeah, the main difficulty from the repel mod doesnt come from the repulsion itself, it comes from not having any reference to whether you are hitting the notes or not.
Also, what is the difference between repel and barrel roll that makes it more difficult to implement?

**Comment by ggliv** [comment]
https://github.com/ppy/osu/pull/5774#issuecomment-1028521634
Judgement drawables aren't moved along with the hitobjects so you're left with a bunch of nonsense at higher attraction/repulsion settings.

> yeah, the main difficulty from the repel mod doesnt come from the repulsion itself, it comes from not having any reference to whether you are hitting the notes or not.

Hits are definitely still being judged, there's no problem with that. It's just the display of the judgements.
>Also, what is the difference between repel and barrel roll that makes it more difficult to implement?

BR moves the whole playfield while MG/RP move the hitobjects.

**Comment by DavidBeh** [comment]
I want to get judgements to work with magnetised because i really like the mod and judgements are really missing for me.

[This](https://github.com/ppy/osu/commit/beee76d64ab5b7604787603a2c9c8f559910d604) is my first attempt. It makes all types of judgements (and follow paths) work visually (except maybe slider judgements not moving after appearing at the right position and sliders continuing to move after that if you count that as misbehavior) but it breaks replays at probably influences scoring (although i think scoring based on the position at the time a hitobject got a result (hit/miss) may be interesting and maybe better than doing it with the constant factor. However, that is another topic however and i would first focus on getting judgements to work visually without side effects). It also uses a static `ConditionalWeakTable` which seems to be bad practice here. So my solution is unusable, but at least i got more familiar with the codebase.

In the original code [here (https://github.com/DavidBeh/osu/blob/beee76d64ab5b7604787603a2c9c8f559910d604/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuJudgement.cs#L44-L44) the `DrawableJudgement`s position is set using the original Position of the non-drawable `HitObject`.

I noticed that the DrawableHitObject is set as a property in `DrawableOsuJudgement` so i tried to set its position like [this](https://github.com/DavidBeh/osu/blob/331f1f31b08c508d4d51008a402df2b9d6b46238/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuJudgement.cs#L42-L46). Now the actual position of the DrawableHitObjects are somehow reflected by the judgements position, but with an unwanted offset:

![osu!_oyfUdhIAyV](https://github.com/ppy/osu/assets/67109172/2ccbd724-57f5-428d-8d06-101e0c31d500)

And also follow paths are broken again.
I will look into this later.
