### ISSUE TITLE
Spinner points starting from 200, not 0 in editor.

### ISSUE THREAD

**Issue by xavierfuchs06** [ppy/osu#20212]
### Type

Game behaviour

### Bug description

I was making a custom difficulty of a map, and ran through it just to make sure everything was correct. I noticed that the spinner points started from 200 and were going down to 0, then back up as normal. 

### Screenshots or videos

https://user-images.githubusercontent.com/106923083/189445605-7fd6a117-8aa5-48a0-ab47-58157118fa92.mp4

### Version

2022.902.1-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9538775/database.log)
[network.log](https://github.com/ppy/osu/files/9538776/network.log)
[performance.log](https://github.com/ppy/osu/files/9538777/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/9538778/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9538779/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9538780/performance-input.log)
[runtime.log](https://github.com/ppy/osu/files/9538782/runtime.log)
[performance-update.log](https://github.com/ppy/osu/files/9538781/performance-update.log)
[updater.log](https://github.com/ppy/osu/files/9538783/updater.log)

**Comment by Gabixel** [comment]
This issue is covered by #10455. You can fix this by re-entering the editor.

As shown in the original thread, with the default skin you can see that the points start at `-200`, so I can assume that legacy skins don't have some kind of sprite to show the minus symbol.
![image](https://user-images.githubusercontent.com/43073074/189447509-9712da66-1a53-497e-8288-69dc3bd3d544.png)

**Comment by xavierfuchs06** [comment]
Actually found that issue while searching but didn't really understand it to be honest. Thanks for your quick reply
