### ISSUE TITLE
`TotalScore` type is undetermined

### ISSUE THREAD

**Issue by peppy** [ppy/osu#20298]
https://github.com/ppy/osu/blob/08d0c08750ae7341334a99aefa8920c9922f36f3/osu.Game/Scoring/ScoreManager.cs#L71

https://github.com/ppy/osu/blob/27d4016ccb360991c37750bf5fe67e193b8fa038/osu.Game/Rulesets/Scoring/ScoreProcessor.cs#L36

https://github.com/ppy/osu/blob/ba2ef424d4cac407692ad78c7c1c75b44110d419/osu.Game/Online/API/Requests/Responses/SoloScoreInfo.cs#L34

We should standardise these to a single type. Not sure if `double` or `long` makes more sense.

**Comment by CC-0000** [comment]
Hey I'm new to open source contribution, but I would like to take a stab at this issue if possible. I think that standardizing to long would make more sense since the scores are never displayed as a double and the previously linked issue #17783 requests that the total score functions return `int` instead of `double`. It also appears that #17783 never got a pull request as it seems to be not be updated in the current codebase.

**Comment by CC-0000** [comment]
After I changed all the datatypes to long, and built and ran osu(lazer), the score for any map I played for stuck at 000000

**Comment by o-dasher** [comment]
I think long should be preferred for this to be honest since it makes the intention of the data type more clear, scores shouldn't ever be floating points :/

**Comment by smoogipoo** [comment]
Correct, long should be preferred.

**Comment by loma-baldsson** [comment]
what happens for the classic scoring system? will it become unsupported?

**Comment by smoogipoo** [comment]
The classic scoring system is supported by `long`.

**Comment by bdach** [comment]
As far as I can tell, resolved by #21140.
