### ISSUE TITLE
`TotalScore` in client database is incorrect

### ISSUE THREAD

**Issue by peppy** [ppy/osu#20299]
While maximum statistics has since been populated, local `TotalScore` has not been updated in line with mod multiplier changes.

In most cases this is not visible due to use of `ScoreManager` to process `TotalScore` locally (and it's generally not used for ordering as we have `ScoreManager.OrderByTotalScore`).

Maybe it's not even required to store this in the local database to keep things using a single flow, in that case?

**Comment by smoogipoo** [comment]
Dropping this out of P1 since it's not displayed anywhere.

**Comment by Syndace** [comment]
I would like to have the `TotalScore` field in a state where it can be used to sort scores. This would allow requesting sorted scores directly from realm, instead of the `request -> detach -> manual sort` flow that is currently in use with `ScoreManager.OrderByTotalScore`. It would also enable filtering of beatmaps based on the best local score in a realm query, which I believe is useful for (or even a requirement of) #4917 .

I'm aware of two ways in which the `TotalScore` field is broken currently: the first is what this issue is about, and the second is that replays/scores imported from stable have the stable score in the `TotalScore` field and not the standardized lazer score.

What do you think about this? Do you agree that the field is worth saving for the above reasons, or do you have other ideas for #4917 ?

I would like to work on these issues if we find agreement.

**Comment by bdach** [comment]
I would not be opposed to normalising all db entries to have standardised score in the `TotalScore` field (with backwards migration). But I'm going to need backup from @ppy/team-client to confirm that there is agreement on this.

**Comment by bdach** [comment]
I want to say that this is actually as close to resolved as it'll ever get after our new standardised score migration efforts (https://github.com/ppy/osu/pull/23638, https://github.com/ppy/osu/pull/23892, https://github.com/ppy/osu/pull/24072).
