### ISSUE TITLE
Gridsnap not working for non-base control points for sliders

### ISSUE THREAD

**Issue by 19peytonsmith** [ppy/osu#20296]
### Type

Game behaviour

### Bug description

Didn't find an issue related to this, but as the title says, if you have grid-snapping enabled, only the slider head snaps to the grid, any other control point added to the slider aren't snapped the grid, I know in stable you are able to do this, so I think it should be reflected here.

### Screenshots or videos

https://user-images.githubusercontent.com/54728307/190059925-e72ac24d-f910-47b3-b327-ca7bbbced551.mp4

### Version

2022.911.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/9562674/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9562675/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9562676/updater.log)
[database.log](https://github.com/ppy/osu/files/9562677/database.log)
[network.log](https://github.com/ppy/osu/files/9562678/network.log)

**Comment by B3nn1** [comment]
I've been trying to fix this recently [on this branch](https://github.com/ppy/osu/compare/master...B3nn1:osu:slider-controlpoint-snapping).

The problem I'm encountering now is that the snapping stops working correctly e.g. if you move the slider once without snapping enabled.

https://user-images.githubusercontent.com/9751465/191102561-755a9ce3-9b27-471a-841a-e356247befc1.mp4

I don't really know what's happening since this doesn't seem to be happening with regular `HitObject` snapping. Did I use `snapProvider` incorrectly or miss something?

**Comment by peppy** [comment]
You are adjusting individual points in a slider, but slider points are actually relative to the slider head. When you misalign the head from the grid, it will therefore cause the points to seem off-grid.

To fix this, you'll have to change your calculating to consider the slider's `Position` (remove it, perform the grid alignment, then add it back is the easiest way). See how you go with this.
