### ISSUE TITLE
lag in editor, seeking to late part in map fixes it.

### ISSUE THREAD

**Issue by Axilotl17** [ppy/osu#20462]
### Type

Game behaviour

### Bug description

when editing maps, my framerate is really low, but when i click to a part later in the map and back to the beginning, it fixes itself?

with all maps longer than like, 10 minutes, but the longer the map the more severe the lag. (seeking to the end makes them all the same)

### Screenshots or videos

https://user-images.githubusercontent.com/78441708/192130154-07555f3d-6f9b-4618-8c8c-979056189adc.mp4

### Version

2022.923.1-lazer

### Logs

[logs.zip](https://github.com/ppy/osu/files/9640110/logs.zip)

**Comment by peppy** [comment]
I can't find the beatmap in your video. In the future please link the beatmap.

**Comment by peppy** [comment]
The issue here is that the timeline tick logic is generating with a huge range immediately on entering the editor. 
```
[runtime] 2022-09-27 07:33:12 [verbose]: Regenerating ticks for range (-772125.75, 772125.75)
[runtime] 2022-09-27 07:33:12 [verbose]: Regenerating ticks for range (-3066.7593, 3066.7593)
[runtime] 2022-09-27 07:33:12 [verbose]: Regenerating ticks for range (-3030.6143, 3102.9048)
[runtime] 2022-09-27 07:33:12 [verbose]: Regenerating ticks for range (6033.604, 12167.123)
```

It also has a logic which stops it from regenerating unnecessarily, meaning it will only recover after the seek mentioned in the issue.

https://github.com/ppy/osu/blob/f8830c6850128456266c82de83273204f8b74ac0/osu.Game/Screens/Edit/Compose/Components/Timeline/TimelineTickDisplay.cs#L94


Still investigating a solution, but dropping this here for documentation purposes.
