### ISSUE TITLE
Unsaveable ranked score will the global leaderboard will not save

### ISSUE THREAD

**Issue by Vad1mCSO2** [ppy/osu#20474]
### Type

Other

### Bug description

I playing a ranked map will be saved to local score, in global score not saved. please fix

### Screenshots or videos

![osu_2022-09-26_10-14-26](https://user-images.githubusercontent.com/76803825/192186910-986c8ff9-89fe-47af-8cde-105a4ded4f2b.png)
![osu_2022-09-26_10-12-41](https://user-images.githubusercontent.com/76803825/192186915-df2098d0-38f4-4e12-9a4c-a4540f09a843.png)

### Version

2022.923.1

### Logs

[database.log](https://github.com/ppy/osu/files/9642687/database.log)
[input.log](https://github.com/ppy/osu/files/9642688/input.log)
[network.log](https://github.com/ppy/osu/files/9642689/network.log)
[performance.log](https://github.com/ppy/osu/files/9642690/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9642691/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9642692/updater.log)

**Comment by peppy** [comment]
Could you please check again?

**Comment by peppy** [comment]
I've confirmed your score is there now:

![osu! 2022-09-26 at 03 32 27](https://user-images.githubusercontent.com/191335/192188636-29cdb506-46bc-4625-8eab-d0c4a8b8047d.png)


The indexing process crashed earlier today due to some ongoing work I've been doing behind the scenes. Should be back in real-time now.
