### ISSUE TITLE
osu!Catch editor plays hitsounds very loudly

### ISSUE THREAD

**Issue by hburn7** [ppy/osu#20597]
### Type

Game behaviour

### Bug description

When scrubbing through an osu!Catch map in the editor, the hitsounds first play very loudly as if every note that is scrubbed past plays it's hitsound at the same time. After scrubbing through the timeline a few times, no hitsounds can be heard.

### Screenshots or videos

https://user-images.githubusercontent.com/38370573/194396607-eede56bd-cbe4-4da4-9036-eb48d4e849a3.mp4

### Version

2022.923.1

### Logs

[database.log](https://github.com/ppy/osu/files/9727786/database.log)
[network.log](https://github.com/ppy/osu/files/9727787/network.log)
[performance.log](https://github.com/ppy/osu/files/9727788/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9727789/runtime.log)

**Comment by peppy** [comment]
Might be a regression with lifetime changes?

**Comment by ekrctb** [comment]
Isn't hitsound not playing because the song is not playing?

**Comment by peppy** [comment]
Yeah, in local testing it seems to work fine for me, so I'm not sure what this issue is about.

**Comment by hburn7** [comment]
After some testing I've found that the hitsounds do in fact play consistently. Scrubbing while playing and not playing result in the hitsounds playing and not playing respectively which is expected. However, I find that the audio for the hitsounds when scrubbing while playing are _extremely_ loud. Compare the hitsounds to the audio here in the test.

![Adobe_Premiere_Rush_LB4Ug7g8kU](https://user-images.githubusercontent.com/38370573/195956058-06f4116c-3b98-44d2-b72e-619a1f201596.png)


(Volume warning)

https://user-images.githubusercontent.com/38370573/195956029-12eaa8ec-6ce2-4a1c-81af-63b49623cd3f.mp4

**Comment by peppy** [comment]
Stable gets around this by having global debounce on sample playback (when the sample name matches). We don't do that in lazer which is why this can happen in the first place.

We do have an alternative, which is the sample playback disable flow:

https://github.com/ppy/osu/blob/349d262c1820d5056282bc2a3a2014a6535a17af/osu.Game/Screens/Edit/Editor.cs#L886-L891

But I believe in your case because your "seek" is very manual, this is intermittently triggering and not covering all playback. Adding a delay before switching playback back to an enabled state may fix this.
