### ISSUE TITLE
Stack leniency doesn't affect objects immediately in Editor

### ISSUE THREAD

**Issue by okolenmi** [ppy/osu#20675]
### Type

Cosmetic

### Bug description

Stack leniency setting works only after editor reloading. Has no visual effect without reloading.
On screen no stacking after map loaded with stack leniency 0 and then adjusted to 1.0. But stacking is enabled after reloading.

### Screenshots or videos

![изображение](https://user-images.githubusercontent.com/55319814/194791499-6b58fa4d-4b45-4394-b6f3-cfdb139afc56.png)

### Version

osu! 2022.1008.2-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/9743113/network.log)
[performance.log](https://github.com/ppy/osu/files/9743114/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9743115/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9743116/updater.log)
[database.log](https://github.com/ppy/osu/files/9743117/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9743118/legacy-ipc.log)

**Comment by B3nn1** [comment]
[This](https://github.com/ppy/osu/commit/606db2287a54fe532ccf3b2e7c18e39fe781a1f6) fixes the problem, but only works after the beatmap has been saved once. Any idea as to why this could be?

**Comment by frenzibyte** [comment]
This can be easily noticeable by using a debugger and breakpointing at the point of applying stack positioning. It's happening due to the beatmap that `BeatmapProcessor` uses belonging to `PlayableBeatmap` rather than `EditorBeatmap`, causing the states to not sync immediately. One way to fix this would be to let the processor use the separate `BeatmapInfo` instance via constructor ([diff](https://github.com/ppy/osu/compare/master..frenzibyte:osu:fix-stack-leniency)), but this begs the question of why `PlayableBeatmap.BeatmapInfo != EditorBeatmap.BeatmapInfo` in the first place. This all sounds like that should be fixed instead.
