### ISSUE TITLE
Implement mirror mod for osu!mania

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#2067]
Should flip the columns. Probably unranked.

**Comment by underjoy** [comment]
Supporting this strongly. 
Also, since the mod in fact does not make anything easier or harder, rankability might be possible and convenient.
Take note of mirror's behaviour with 7+1K style. Mirror should not work on scratch.

I wish I could contribute '_>'

**Comment by LastExceed** [comment]
This would be very relieving for left handed mania players (such as myself), because of 2 reasons:

1. **Column balance**
There is quite a few maps that (mostly unintential) have more notes on the right side than on the left (vice versa also exists, but is very rare).
[Here is an example of a well-mapped beatmap that has a strong hand imbalance (45/55)](https://osu.ppy.sh/b/661803)
Ofcourse overall column balance should be a ranking criteria, but sometimes its just part of the mapping style. 

2. **Anchors**
An anchor, for those who don't play mania, is when a pattern has a particularly high amount of notes in the same column, in regular spacing. I have observed that righthanded mappers tend to unconsciously put the majority of anchors on the right side, just as I have obeserved myself doing the opposite (since I am lefthanded). Playing an anchor on the right as a lefthanded player (or vice versa) feels awkward to play for obvious reasons, a good example for this are double trills in 4k. All 1/1 and 1/2 beat notes are on the right and all 1/4 beat notes are on the left (or vv). 
[Here is an example of a pattern that is easy if you're righthanded but awkward if you're lefthanded](http://puu.sh/znvvc/03ca32d26a.png)
Now I know what you're thinking, "one should be able to play both" and yes thats correct, but that argument only works if the amount of anchors on the right was about equal to the amount of anchors on the left, which unfortunately isn't the case since the majority of mappers are right handed. But keep in mind that all maps have both, its just not equally divided in some cases.



A mirror mod would be the perfect solution for both of these problems, there's already a couple players that made their own workarounds for this (eg Urusai plays with upscroll enabled and his monitor upside down to mirror the stage, and I myself have already played with a physical mirror next to my monitor a few times.

I don't see why you'd make it unranked. Mirror should be ranked just like upscroll, and I'd even suggest mirror to be part of the skin instead of a mod if it wasn't for the fact that there are a couple leftweighted maps too.

As underjoy pointed out, a mirror mod would require **true 8k** and **7+1k** to be clearly distinguished. other than that the only issue with implementing a mirror mod i see is players using it to escape mindblocks, but whether or not thats a bad thing is kind of an open question...
