### ISSUE TITLE
Multiple tracks playing on entering/exiting song select

### ISSUE THREAD

**Issue by Kitichu** [ppy/osu#2080]
During song select if you pick a song and close out of it in a short amount of time the song will still continue to be playing and the music starts overlapping each other without it stopping. example: https://www.youtube.com/watch?v=OPu_qOJElVM&feature=youtu.be

**Comment by peppy** [comment]
This should theoretically be impossible. Must have been a recent regression.

**Comment by UselessToucan** [comment]
I can't reproduce the problem on [this revision](https://github.com/ppy/osu/commit/e1a6017df9f022c9f7850d030ac10dd9fb882ef7).

@Kitichu 
1. Can you confirm if the bug stable or not?
2. Can you provide steps to reproduce?

I tried the following steps with no success:
1). Enter song select screen.
2). Start a beatmap.
3). Press esc on the PlayerLoader screen.
4). Press left/right arrows rapidly a couple of times.

**Comment by tgi74** [comment]
I found a way to reproduce (https://github.com/ppy/osu/commit/2910fc53dc1fbd6d58911906d4c2b30a98ccbfc6):
1. Enter song select screen.
2. Switch beatmap set(press right/left).
3. Go back to the Main Menu (press espace) during the transition (needs timings).

Result: The track of the beatmap you switched to will be playing at volume 100%, but the game will still show you the beatmap you switched from.

- This effect can stack.
- The "ghost" tracks will not follow the volume level or mute by pressing F4.

Videos:
- Volume level not affecting (WARNING: loud) -> https://youtu.be/OHcKCcVVqmw
- Multiple "ghost" tracks (stacked) -> https://youtu.be/9LLNcaWnkDg

**Comment by FreezyLemon** [comment]
I am pretty sure that I found the problem.
If you want to debug this for yourself, here is a picture of a breakpoint that only breaks when this bug occurs: ![Image](https://i.imgur.com/AnGIQB5.png)

What I found is that the `TrackManager` responsible for these tracks does _not_ remove the (currently playing) track from its list of tracks because the track is not disposed.

We could (almost definitely) fix this by either
1. manually cancelling the `selectionChangedDebounce` on Screen exit (since this can only happen through a scheduled task after the screen has exited) or
2. manually disposing the old track to make the trackmanager delete it from its items.

Option 1 would mean that the selection change would be cancelled when exiting the SongSelect screen, while option 2 would apply the change after screen exit (though i don't know how easy option 2 would be to implement).
