### ISSUE TITLE
Difficulty point edit popover does not work correctly in cultures where decimal separator is not `.`

### ISSUE THREAD

**Issue by Maks1mio** [ppy/osu#20989]
### Type

Game behaviour

### Bug description

I did this piece of map entirely in osu!lazer
And along the way I ran into a lot of trouble.
I'll just show you.

### Screenshots or videos

https://evt.tixte.co/2022.1022.0.mp4 - Problem with playing hits while holding

https://evt.tixte.co/2022.1022.2.mp4 - The problem is the volume, out of 45 it still sounds like the value of 100

Problem with copying and pasting and changing number manually

https://user-images.githubusercontent.com/44835662/198541594-ff31def3-33d0-47f5-a60d-ece9ac3797c1.mp4

Cosmetics

![bug](https://user-images.githubusercontent.com/44835662/198541490-c2b9819f-f590-4086-b3bf-506c52d93ba4.png)

Map, if needed - https://evt.tixte.co/Vaundy_-_odoriko_(EvT).osz

### Version

2022.1022.0

### Logs

[performance.log](https://github.com/ppy/osu/files/9886596/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9886597/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9886598/updater.log)
[database.log](https://github.com/ppy/osu/files/9886599/database.log)
[network.log](https://github.com/ppy/osu/files/9886600/network.log)

**Comment by bdach** [comment]
- Not sure hitsounds not playing for objects that currently are being dragged is a real issue.
- Slider volume issue is likely #15618.
- The remaining issue with the textbox input is a localisation failure stemming from the usage of the decimal comma rather than decimal dot. `IndeterminateSliderWithTextBoxInput` prints the value to the textbox using current locale, but parses through `Bindable.Parse` which expects invariant locale.

Renaming issue to track the third problem only. First one is a low priority one IMO and should be opened separately anyways.
