### ISSUE TITLE
Remapping a keybind adds tablet pen to the keybind

### ISSUE THREAD

**Issue by gepbird** [ppy/osu#21000]
### Type

Game behaviour

### Bug description

Context: no stylus button is pressed down, and the stylus is far from the tablet, not activating it.

Starting osu!, going into the key configuration and trying to remap for example the Back action. Pressing `Esc` to set the keybind, sets the keybind to `Esc-Tablet Pen 2`. Pressing just `Esc` to trigger the Back action doesn't work (only pressing `Esc` and `Tablet Pen 2` at the same time does). So when setting the keybind, the game thinks I'm holding down the pen button, but when trying to use that keybind, it knows the pen button is not pressed down.

Activating the tablet solves this issue, but the issue comes back after restarting the game.

~~This bug was introduced in 92167afaab4ab223f65ddad269a50a0a11bd5dc0.~~

### Screenshots or videos

![2022-10-28_20-43](https://user-images.githubusercontent.com/29818440/198709399-2e0b40b1-a56a-47e2-855e-ad6e43630ad9.png)

### Version

local release built from 223cb5f497b0eb34a3a03122fb6f21ef2c9b707c

### Logs

[input.log](https://github.com/ppy/osu/files/9891147/input.log)
[network.log](https://github.com/ppy/osu/files/9891148/network.log)
[performance.log](https://github.com/ppy/osu/files/9891149/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9891150/runtime.log)
[database.log](https://github.com/ppy/osu/files/9891151/database.log)

**Comment by bdach** [comment]
I cannot reproduce this issue, and the bisection provided makes no sense (https://github.com/ppy/osu/commit/92167afaab4ab223f65ddad269a50a0a11bd5dc0 has no right to introduce this bug).

Likely something to do with the specific device in question.

**Comment by gutyina70** [comment]
It looks like this issue is caused by a race condition. I repeated the same test 20 times (start the game on the latest commit, change a keybind, let the game close without killing it): works, fails, works, fails, works, fails, fails, fails, works, fails, fails, works, fails, works, works, fails, works, fails, fails, works.

When the framework [creates a tablet](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs#L66), it creates a seperate thread that [waits a small amount](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Input/Handlers/Tablet/TabletDriver.cs#L64) then calls [OTD's Detect](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Input/Handlers/Tablet/TabletDriver.cs#L72). Meanwhile the newly created thread is waiting (or finished), the first thread [starts listening to tablet inputs](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs#L69), then calls OTD's Detect just to be safe. And OTD's Detect will end up [reporting a pen button press](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/v0.6.0.4/OpenTabletDriver/InputDevice.cs#L97) to test the tablet.

Swapping the [input listening subscription](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs#L69) and the [tablet detection](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs#L70) statements looks like it solved the issue (it worked 10/10 times when I tested using the previous method), but it still may be possible that the delayed thread calls OTD's Detect after osu! is already listening to tablet inputs, causing this issue.

**Comment by peppy** [comment]
So if your investigation is correct, this sounds like an issue at OTD's end then? Since we should not be seeing that "test" press report.

**Comment by peppy** [comment]
@gutyina70 Are you able to make a pull request with the proposed changes? Seems like you have a good idea of what is required.

**Comment by gepbird** [comment]
This issue was fixed in an OTD update.
