### ISSUE TITLE
osu!catch dashing with mouse shows cursor

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#21088]
### Discussed in https://github.com/ppy/osu/discussions/21080

<div type='discussions-op-text'>

<sup>Originally posted by **Aimiks** November  3, 2022</sup>
The cursor appear and a "click" sound effect is played when using MB1 to perform dash in osu!catch.
This is distracting for players using MB1 or MB2 button to dash.

I've looked into the settings but it doesn't seem to have any options regarding this.
Is there any ?</div>

**Comment by peppy** [comment]
This is likely going to be a partial regression due to the change in cursor visibility logic. That said, I'm not sure how well we can handle this scenario. You would expect the cursor to still display when the mouse is moved to a certain degree, right?

Probably the best we can do is ensure the lenience to have the cursor display ignores small movements, and ensure the cursor does not display from a click alone (or, if easy to make happen, doesn't display if a gameplay usage of the click occurs, but that's probably a harder one to make happen structurally).

**Comment by Aimiks** [comment]
To compare with stable, the cursor doesn't even appear when making movements when playing catch (outside of breaks and the beginning of the beatmap). 
This logic is fine because the cursor visibility (and cursor by itself) is completely useless when playing osu!catch.

Adding to this, the cursor is all-time visible when playing relax (using mouse to control the catcher) making the gameplay a bit confusing compared to stable where the cursor is invisible.

**Comment by loma-baldsson** [comment]
Does this happen in other rulesets where one might want to use mouse buttons, but won't want the cursor to show (osu!taiko comes to mind first)

**Comment by peppy** [comment]
Yes, it will happen across all rulesets as mouse handling is currently roughly the same across all rulesets.
