### ISSUE TITLE
Patch notes showing up below settings panel

### ISSUE THREAD

**Issue by 25huizengek1** [ppy/osu#21162]
### Type

Cosmetic

### Bug description

1. Click on the settings menu
2. Scroll all the way down
3. Click on the version number

### Screenshots or videos

![image](https://user-images.githubusercontent.com/50515369/200405987-c8d07718-b05e-4386-ad5f-e1394ea6a448.png)

### Version

2022.1101.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9955096/database.log)
[input.log](https://github.com/ppy/osu/files/9955097/input.log)
[network.log](https://github.com/ppy/osu/files/9955098/network.log)
[performance.log](https://github.com/ppy/osu/files/9955099/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/9955100/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9955101/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9955102/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9955103/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9955104/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9955105/updater.log)

**Comment by ItsShamed** [comment]
I think this is expected, I don't know what's the issue here. Also instead of scrolling all the way down to the settings to get the changelogs you can just click this button. 

![IMG_20221107_213039.jpg](https://user-images.githubusercontent.com/39100084/200409241-fbe4b851-a54e-47d4-9760-4e6023d2c99a.jpg)

**Comment by loma-baldsson** [comment]
if youre opening a menu from another menu, you'd probably expect the new menu to display on top of the old one. as an example, clicking a username in chat will open their profile on top of the chat. similar thing here with opening changelog from settings

that said i think this issue is a duplicate.

**Comment by 25huizengek1** [comment]
No, it even happens when you click settings first, and I think it should pop up above the settings menu or the settings menu could just close, because in that case you opened the changelogs after you opened settings. That said, yes I am aware of the changelog button.
