### ISSUE TITLE
Map awarding more playtime than it should

### ISSUE THREAD

**Issue by xasuma** [ppy/osu#21198]
### Type

Game behaviour

### Bug description

There is a loved map in taiko that awards 60 mins playtime for a 4 min map. This is abusable as it can even be done with NF. 
https://osu.ppy.sh/beatmapsets/692689#taiko/2585343 (20 - The Entire World (Axer))

I tested this with some diffs from the unforgiving in osu standard that show the map being longer than it actually is, but those playtimes are being given accurately. This issue seems to be specific to this map maybe(?), but maybe it's not. Easily replicable. 

### Version

b20221104.2

### Logs

not relevant

**Comment by LiterallyFabian** [comment]
you're looking for https://github.com/ppy/osu-stable-issues as this repo is for lazer issues

I wasn't able to repro it in lazer with NF & NC, so I guess it's stable only? Probably caused by the map length being 20x longer than the drain length, but yeah create a new issue in the repo above

![image](https://user-images.githubusercontent.com/47401343/201204855-7a55e0b0-20b9-4961-85d5-d7c8c7770cdb.png)

**Comment by xasuma** [comment]
My bad, I'll repost it there.
