### ISSUE TITLE
Gimmick taiko map loads for infinity and then slows the game down when exiting

### ISSUE THREAD

**Issue by reo-the-enby** [ppy/osu#21217]
### Type

Crash to desktop

### Bug description

This map (tournament nm4/gimmick map): https://osu.ppy.sh/beatmapsets/1876177#taiko/3860984 loads for infinity. When I exit the map loading the game starts to freeze and go down to low fps.

When trying to load it in the editor after the game crashes

Probably due to this 
![bild](https://user-images.githubusercontent.com/81715029/201493119-78e6109c-b241-4660-b9eb-f6a5e3c6df9c.png)

### Version

2022.1101.0

### Logs

[database.log](https://github.com/ppy/osu/files/9995862/database.log)
[input.log](https://github.com/ppy/osu/files/9995863/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9995864/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9995865/network.log)
[performance.log](https://github.com/ppy/osu/files/9995866/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9995867/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9995868/updater.log)

**Comment by peppy** [comment]
That beatmap is just fucked. I've left a blocking comment in the beatmap's discussion. If you have another example which is ranked then please provide it and I'll take another look.

**Comment by sw1tchbl4d3r** [comment]
For some clarification, the beatmap is not ranked, and the timing point is needed for gimmick/Aspire behavior, the community is well aware that this is unrankable. This doesn't prevent it from getting loved though, as such it pretty much falls under #20108 anyway.

**Comment by peppy** [comment]
A good starting point nay be to explain what “gimmick” having a time value of negative 6 days worth would require.

**Comment by sw1tchbl4d3r** [comment]
Do have to say I didn't quite look at it correctly, in this case this huge offset really isn't required, and since gimmicks are not rankable and they're only recently entering loved votings there are no examples of this specifically (yet).
I feel like lazer should adapt to these kinds of maps, not the other way around, but this may grow off topic very quickly and as this issue would be closed either way that'll be all from me at least here.

**Comment by Kasumiikun** [comment]
Very confusing as to why this can't be dealt with in a respectful manner to the mapper. The comment on the beatmap is extremely unnecessary, especially when you see the map break a billion ranking criteria rules...
If you want examples of that, you're not ever getting it in ranked to begin with, it doesn't respect its rules.
Loved maps are hard to give.
Geniunely the only thing you can be given if you want to look into gimmicks in taiko, with them being pretty fairly popular in the taiko tournament scene, and taiko scene in general, are tournament maps.
They're all fully playable, with evidence being literal streams where they have been played.
I'm giving this, but considering you way you answer it doesn't look like it will have much of a follow-up.

I do not remember negative infinity maps, but there are maps using infinity BPMs.
https://osu.ppy.sh/beatmapsets/1869763#taiko/3848473 
this train going nowhere and Misfortune*Star are notable ones.
dont say "i can sample that" for 24 hours challenge also does uh, very interesting things with having made notes that cannot be hit while not dropping combo.

All of these are very interesting gimmicks, fairly appreciated by the community. 
I feel like it would be a shame to just say they're not allowed to exist on lazer, due to them abusing the game, to be fair, after years of players enjoying these.
