### ISSUE TITLE
UI layer issue for collection assignment

### ISSUE THREAD

**Issue by Inconsist** [ppy/osu#21602]
### Type

Cosmetic

### Bug description

For long collection names the menu flips over and is then coverd by the UI that's already there. Would be nice to have it be atop for this so you could see what you're doing more easily. Also my specific collections are nolonger sortet in the same way in the dropdown as they are where you can rearrange them in the "Manage" panel.

### Screenshots or videos

 for the layer issue
![image](https://user-images.githubusercontent.com/87947227/206884669-3889ff27-558a-48d1-8615-67c96fd43089.png)

the way I sort them
![image](https://user-images.githubusercontent.com/87947227/206884865-633706b9-7924-4774-8aac-52cc9f74e5e4.png)
the way I see them
![image](https://user-images.githubusercontent.com/87947227/206884879-38a2cedc-c322-46b6-ac0b-99b3779fb72a.png)

### Version

2022.1208.0-lazer

### Logs

[input.log](https://github.com/ppy/osu/files/10201428/input.log)
[network.log](https://github.com/ppy/osu/files/10201429/network.log)
[performance.log](https://github.com/ppy/osu/files/10201430/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10201431/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10201432/updater.log)
[database.log](https://github.com/ppy/osu/files/10201433/database.log)

**Comment by Inconsist** [comment]
actually I figured out how to order collections, theyre still sortet alphabetically, you just have to press enter after a namchange. the hamburger drag and drop reorder thing has no effect, thats misleading design.

**Comment by sponnify** [comment]
hi, i’d like to add some context to this issue. as a mapper who heavily uses collections, these issues make it difficult to use lazer for editing beatmaps for my workflow.

i’ve noticed that new collections created in lazer’s manage collections window are not correctly organised alongside collections imported from the stable version. they appear at the bottom of the collections listing, regardless of their names or any symbols used. this isn’t due to exceeding stable’s character limit for collection names, as i’ve demonstrated in the following videos.

https://github.com/ppy/osu/assets/69046095/b30d623c-b8e2-4bea-9b9e-091f41fcf33f
https://github.com/ppy/osu/assets/69046095/077e1d89-896b-4324-bde4-74dd10a3922d

however, the manage collections window does display the collections in the correct order when opened. this discrepancy between the ordering in different parts of the ui is confusing and hinders efficient use of the collections feature. i agree that this is misleading and can be quite frustrating for users who rely on collections for their workflow.

**Comment by peppy** [comment]
> i’ve noticed that new collections created in lazer’s manage collections window are not correctly organised alongside collections imported from the stable version

I've fixed this in https://github.com/ppy/osu/pull/25139
