### ISSUE TITLE
`CircularProgress` does not display properly on iPad devices

### ISSUE THREAD

**Issue by NiceAesth** [ppy/osu#21775]
### Type

Game behaviour

### Bug description

Currently, the circular song progress element does not display on iOS.

### Screenshots or videos

![IMG_E493C4A7D36B-1](https://user-images.githubusercontent.com/8437201/209412082-604d9453-dc9d-4a57-b831-b7fc7e31e337.jpeg)

### Version

2022.1208-0

### Logs

[database.log](https://github.com/ppy/osu/files/10297616/database.log)
[network.log](https://github.com/ppy/osu/files/10297617/network.log)
[performance.log](https://github.com/ppy/osu/files/10297618/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10297619/runtime.log)

**Comment by frenzibyte** [comment]
Coming from [discord](https://discord.com/channels/188630481301012481/589331078574112768/1056353110395715624), it turns out not only `CircularProgress` doesn't render, but `CircularBlob` as well, along with colour pickers displaying solid black. This is a definite indicator that the shader cannot contain the value of the white-pixel texture coords/rectangle. Investigating further on discord...

**Comment by frenzibyte** [comment]
After a couple of [trial-and-error attempts](https://discord.com/channels/188630481301012481/589331078574112768/1056364919274086420) with @NiceAesth, it turns out the iPad 11" behaves differently in terms of precision modifiers. Specifically, `highp` behaves exactly as `mediump`, and such components stop rendering whenever `v_TexRect`/`v_TexCoord` exceed the `mediump` range despite the uniforms being explicitly marked with `highp`.

Now that being said, as shocking as it sounds, replacing all precision modifiers in the framework's shaders to `highp` actually [fixed the issue](https://discord.com/channels/188630481301012481/589331078574112768/1056401568620089354), so there's still hope in fixing this issue without actually changing the numbers in `TextureWhitePixel`. All that's left to do is to determine the place that actually needs the precision change, which @NiceAesth will be looking at.

**Comment by peppy** [comment]
Can confirm at least that I was seeing the same components not working on iPad (11, 13) but working fine on phones.

Sounds like the mismatch in types causing some weird edge cases in floating point precision. Agree that if we can fix it without changing `WhitePixel` itself, that's the best immediate path forward.

**Comment by NiceAesth** [comment]
After some testing, I've found that the following changes to `sh_Texture2D.vs` fix the issue.
```diff
- attribute mediump vec2 m_TexCoord;
- attribute mediump vec4 m_TexRect;
+ attribute highp vec2 m_TexCoord;
+ attribute highp vec4 m_TexRect;
```

```diff
- attribute mediump vec2 v_TexCoord;
- attribute mediump vec4 v_TexRect;
+ attribute highp vec2 v_TexCoord;
+ attribute highp vec4 v_TexRect;
```
