### ISSUE TITLE
Beatmap leaderboards on client do not match experimental website

### ISSUE THREAD

**Issue by megadrive7** [ppy/osu#21977]
### Type

Game behaviour

### Bug description

number displayed under personal best is not the same as the actual global ranking. this may not be a bug, as if only scores without the classic mod are counted then my score is the sixth, but if this is the case its misleading at best.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/112918046/210160767-3962e9df-4bbd-4ce0-a60f-7ac86a0e7ff7.png)

### Version

2022.1228.0-Lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10328253/database.log)
[input.log](https://github.com/ppy/osu/files/10328254/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10328255/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10328256/network.log)
[performance.log](https://github.com/ppy/osu/files/10328257/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10328258/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10328259/updater.log)

**Comment by bdach** [comment]
Also reported on twitter (https://twitter.com/Nnm_Sebby/status/1609031733663436805/photo/2).

Both the song select global leaderboard and the beatmap set overlay leaderboard do score recomputation on the client side to support multiple scoring modes, which leads to this wrong outcome. Unsure how this should be addressed, probably requires conferring with the web team. A proper leaderboard merge rather than what's done currently (classic scores being appended after lazer scores) will also presumably resolve this.

**Comment by smoogipoo** [comment]
This is not going to happen anymore after https://github.com/ppy/osu/pull/23638
