### ISSUE TITLE
Mod "Autopilot" shouldn't display click-to-resume overlay 

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#22001]
### Type

Game behaviour

### Bug description

Stable doesn't display this overlay when the mod is on. And generally, the cursor's position doesn't matter when resuming gameplay in such case, so there's no reason to have it displayed.

### Version

2022.1228.0

### Logs

-

**Comment by cdwcgt** [comment]
The same issues to relax

**Comment by frenzibyte** [comment]
Relax should still have the click-to-resume overlay, otherwise users won't be able to return to where they have originally paused at in order to continue gameplay.

**Comment by cdwcgt** [comment]
But actually using relax on stable does not have this overlay.
if stable is designed like this because it does not upload relax/autopilot score. Maybe providing this limit on lazers that can upload scores would increase the competitive.

the only reason I raise this question is because it is not consistent with the behavior of stable, lazer can of course be different from it if it is better to do so
