### ISSUE TITLE
Changelog overlay shows up behind mod selection overlay if opened via notification card

### ISSUE THREAD

**Issue by TwoQuantumBits** [ppy/osu#22287]
### Type

Cosmetic

### Bug description

When opening the changelog from a notification card (e.g. new version changelog notification) while opening the mod selection overlay, the changelog overlay opens behind the mods overlay. Opening the changelog from the main (top) bar will still display the changelog overlay above the mod selection overlay as expected.

### Screenshots or videos

https://user-images.githubusercontent.com/37262651/213349638-d1448732-99f1-4381-973f-6da9341d530d.mp4

### Version

2022.1228.0

### Logs

_(Note: the log files and the video are from two separate reproductions of the bug)_
[database.log](https://github.com/ppy/osu/files/10453235/database.log)
[input.log](https://github.com/ppy/osu/files/10453236/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10453237/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10453238/network.log)
[performance.log](https://github.com/ppy/osu/files/10453239/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10453240/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10453241/updater.log)

**Comment by Joehuu** [comment]
This is because showing builds schedules `ChangelogOverlay` causing:
https://github.com/ppy/osu/blob/e86748626a71065e22114541d4df1d5b33cf88f2/osu.Game/Overlays/ChangelogOverlay.cs#L25
`IsPresent` to be true since https://github.com/ppy/osu/commit/4afbccfcff2544fa4a4e80d765a2bccb270c1658, and
https://github.com/ppy/osu/blob/e86748626a71065e22114541d4df1d5b33cf88f2/osu.Game/OsuGame.cs#L1047-L1056
early returning and not changing depth.

---

I don't know schedulers that much, but if I had to guess, adding `Scheduler.HasPendingTasks` to `IsPresent` in https://github.com/ppy/osu/commit/4afbccfcff2544fa4a4e80d765a2bccb270c1658 only saves frames of loading and isn't really needed? The `Schedule()`'s used in this class are followed by a `Show()` anyway so it won't take long for it to be `IsPresent`.

**Comment by peppy** [comment]
> I don't know schedulers that much, but if I had to guess, adding Scheduler.HasPendingTasks to IsPresent in https://github.com/ppy/osu/commit/4afbccfcff2544fa4a4e80d765a2bccb270c1658 only saves frames of loading and isn't really needed?

You'll want to blame back to see when that line was added. My assumptions would be that it was added to ensure a scheduled task still gets run when the overlay isn't necessarily visible. This is usually because there's a `Schedule(() => Show())` call or similar, where if the `override` was not in place it would never actually show.

So blame as to why this is there, and hope that it's no longer needed because the code it was there for has been refactored. If not, I still agree with trying to remove it by refactoring whatever was depending on it.
