### ISSUE TITLE
Beatmap imports using the local cache lookup do not get a submitted / ranked date populated

### ISSUE THREAD

**Issue by Loreos7** [ppy/osu#22416]
### Type

Game behaviour

### Bug description

(Title). Works the same with Date Ranked sorting criteria.

Beatmap: https://osu.ppy.sh/beatmapsets/25861#osu/92939

### Screenshots or videos

https://user-images.githubusercontent.com/86934170/214570836-893e45fd-7c0e-471c-bcf6-ebd396c5796e.mp4

### Version

123

### Logs

-

**Comment by Theighlin** [comment]
I can see said beatmap even with the date submitted sorting
![image](https://user-images.githubusercontent.com/53081750/214591710-feed54aa-75f8-4db8-83a2-3f9f35837109.png)

But i'm more curious on why at the end of the video the game seems to show every beatmap you have as updateable?

**Comment by Loreos7** [comment]
@Theighlin This is due to https://github.com/ppy/osu/discussions/19551
Logs are 
[network.log](https://github.com/ppy/osu/files/10500475/network.log)
[runtime.log](https://github.com/ppy/osu/files/10500477/runtime.log)
[performance.log](https://github.com/ppy/osu/files/10500478/performance.log)
[updater.log](https://github.com/ppy/osu/files/10500479/updater.log)
[database.log](https://github.com/ppy/osu/files/10500480/database.log)

**Comment by bdach** [comment]
> The issue was resolved by deleting online.db file.

I'm... not sure that is an acceptable fix. Do you recall how the map might have been imported?

These symptoms may indicate that there's a gap somewhere in the metadata population flow that we may need to address.

**Comment by Loreos7** [comment]
> > The issue was resolved by deleting online.db file.
> 
> I'm... not sure that is an acceptable fix. Do you recall how the map might have been imported?
> 
> These symptoms may indicate that there's a gap somewhere in the metadata population flow that we may need to address.

I've just downloaded it through lazer client someday.
I deleted this beatmapset completely, downloaded again then nothing happened: previous behaviour was being repeated. So I decided to go to the osu! folder, deleted online.db and then restarted the game.

**Comment by Loreos7** [comment]
@bdach You're right.
I can reproduce this issue again. I downloaded the beatmapset through the web, imported to osu!stable client, then imported it through `Run setup wizard`

**Comment by peppy** [comment]
https://github.com/ppy/osu/blob/27c497145f87449ac17c08796fc57026d3129f2e/osu.Game/Beatmaps/BeatmapUpdaterMetadataLookup.cs#L233

**Comment by hachuyenden** [comment]
I think the problem is if importing multiple beatmaps into osu!lazer at once, for example importing a bunch of beatmaps from osu!stable or dragging and dropping multiple osz into osu!lazer. osu!lazer will automatically skip the process of sorting by date summitted and date ranked, making date summitted and date ranked sort by date added.

If download beatmaps from within osu!lazer itself, osu!lazer can check-in and sort each beatmap according to date summitted and date ranked.

I remember that this error did not occur before June 2023, but after that version it occurred

**Comment by StarBleu1** [comment]
Not sure whether this counts as this issue or other one
Sorting by Date ranked, Date submitted and Date added doesnt seem to work at all for maps imported from stable.

Video for reference: https://streamable.com/0w1r6w
Gamever: 2024.817.0-lazer
[1724241695.performance.log](https://github.com/user-attachments/files/16691331/1724241695.performance.log)
[1724241695.database.log](https://github.com/user-attachments/files/16691332/1724241695.database.log)
[1724241695.updater.log](https://github.com/user-attachments/files/16691333/1724241695.updater.log)
[1724241695.runtime.log](https://github.com/user-attachments/files/16691334/1724241695.runtime.log)
[1724241695.network.log](https://github.com/user-attachments/files/16691335/1724241695.network.log)

**Comment by bdach** [comment]
It'll be invariably caused by this issue, yes.

**Comment by hachuyenden** [comment]
> Not sure whether this counts as this issue or other one Sorting by Date ranked, Date submitted and Date added doesnt seem to work at all for maps imported from stable.

For 2 years now I still think this is the biggest bug because the most useful lazer function which is date ranked doesn't work properly because of importing maps from Stable.

One of the ways I used to fix the error is https://github.com/molneya/osu_db_helpers. To update date added in stable to date ranked. Then enter map in lazer.

This way will bypass the error that causes lazer to still record date ranked as date added. But still can not avoid the original error.

Hope @bdach considers.

**Comment by bdach** [comment]
I personally don't have the means to fix this at present because I don't have to means to change the process that is generating the offline cache lookup sqlite dbs.
