### ISSUE TITLE
Increasing the number of slider repeats doesn't correctly extend the slider visuals in editor

### ISSUE THREAD

**Issue by Axilotl17** [ppy/osu#22698]
### Type

Game behaviour

### Bug description

when you create a slider and add a backtick, when played the slider disappear after the backtick gets hit. 

### Screenshots or videos

https://user-images.githubusercontent.com/78441708/220034779-43f24f54-895a-422c-922d-617f06f9a18a.mp4

### Version

2023.207.0 & latest dev build

### Logs

[runtime.log](https://github.com/ppy/osu/files/10780490/runtime.log)
[performance.log](https://github.com/ppy/osu/files/10780492/performance.log)
[network.log](https://github.com/ppy/osu/files/10780493/network.log)
[input.log](https://github.com/ppy/osu/files/10780494/input.log)
[database.log](https://github.com/ppy/osu/files/10780495/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10780496/legacy-ipc.log)

**Comment by peppy** [comment]
By backtick, do you mean repeats? If possible, please use standard terminology when describing issues.

**Comment by peppy** [comment]
So this absolutely does not happen on the last release. You must have been mistaken when stating that.

@ekrctb this looks to have regressed with https://github.com/ppy/osu/pull/22291, could you take a quick look?

**Comment by ekrctb** [comment]
This issue also occurs when any hit object (not just sliders, all rulesets) is moved in the timeline.

Hit animation uses `HitStateUpdateTime` and it is same as `Result.TimeAbsolute`.
Results are preserved even if the hit object is modified and the end time is changed.
Previously, only `Result.TimeOffset` is stored and absolute time is computed as `end time + offset`. Now, result's absolute time is stored and therefore it will be stale when the hit object is modified.

Storing absolute time instead of time offset was a deliberate decision. Storing time offset has floating-point precision issues and also complicates the revert logic.

- Currently, there is no way to hook for hit object end time changes. `HitObject.StartTime` is a bindable, but duration and end time are not.
- One must be careful to not write `Result.RawTime` in-place to not break the revert logic, which relies on the invariant of monotone time.
- Hypothetical expression `NewResultTime = OldResultTime + (NewEndTime - OldEndTime)` has the floating-point precision issue.

Not immediately sure how to solve this issue.

**Comment by bdach** [comment]
I'm weakly opposed to reverting the PR. Sure this breakage is not great but the pull fixed other issues, including spurious rewinds in *actual* gameplay due to floating point error (https://github.com/ppy/osu/issues/17482).

Can we not do something like hook into [`HitObjectUpdated`](https://github.com/ppy/osu/blob/06e73594f80855ffa9cb08195bf65b84b8854c15/osu.Game/Screens/Edit/EditorBeatmap.cs#L46-L49) and clear all results of objects that have been touched in the editor? This is maybe a bit nuclear, but it has the potential to fix a whole lot of other issues like this.

**Comment by peppy** [comment]
Feels quite ugly to me. Like we've done something wrong at all levels and this is a hack to work around that :/

**Comment by Cootz** [comment]
Similar behavior for spinner

https://github.com/ppy/osu/assets/50776304/1602def1-d3f6-4960-a717-65f2fced7a1f
