### ISSUE TITLE
Hold on legacy skins are invisible

### ISSUE THREAD

**Issue by distrair** [ppy/osu#22768]
### Type

Cosmetic

### Bug description

On osu!mania, if you use a legacy skin from the stable, hold notes are become invisible.

### Screenshots or videos

https://user-images.githubusercontent.com/78724291/222486565-67020fe6-4db1-47ed-8c6d-0eb6faebcc34.mp4

### Version

2023.301.0

### Logs

[performance-audio.log](https://github.com/ppy/osu/files/10873404/performance-audio.log)
[updater.log](https://github.com/ppy/osu/files/10873405/updater.log)
[runtime.log](https://github.com/ppy/osu/files/10873406/runtime.log)
[performance-update.log](https://github.com/ppy/osu/files/10873407/performance-update.log)
[input.log](https://github.com/ppy/osu/files/10873422/input.log)
[database.log](https://github.com/ppy/osu/files/10873423/database.log)
[network.log](https://github.com/ppy/osu/files/10873424/network.log)
[performance-input.log](https://github.com/ppy/osu/files/10873409/performance-input.log)
[performance-draw.log](https://github.com/ppy/osu/files/10873410/performance-draw.log)
[performance.log](https://github.com/ppy/osu/files/10873411/performance.log)

**Comment by zzahkaboom24** [comment]
Same thing for me. So atm the skin is unusable for me. Ill send the skin I use if it helps with anything
I zipped the osk file because github said osk is not supported

[Stepmania Ultralight [Stepmania Ultralight V1.43] (Toshiyuki Doma (arvinkent098)).zip](https://github.com/ppy/osu/files/10875682/Stepmania.Ultralight.Stepmania.Ultralight.V1.43.Toshiyuki.Doma.arvinkent098.zip)
