### ISSUE TITLE
`LegacyLastTick` is still being used for gameplay and editor displays

### ISSUE THREAD

**Issue by peppy** [ppy/osu#22805]
I'm not sure if we want this from a game mechanic perspective, but it's probably something worth noting until we discuss / finalise things.

https://github.com/ppy/osu/blob/f060e6a780c43057eea6cab2e140c8b6ca8da26e/osu.Game.Rulesets.Osu/Objects/Slider.cs#L196-L207

Noticed this while looking at https://github.com/ppy/osu/discussions/22726.

**Comment by bdach** [comment]
I'm not really even sure what's to discuss in this one. Seems like the spark here was an editor bug caused by using the legacy last tick's end time for the editor marker, but I'm not sure what else this issue encompasses beyond that?

We're working around `LegacyLastTick` in several places already:

https://github.com/ppy/osu/blob/36ebdd8d30130276d59a1268d85af28b17935324/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs#L290-L293
https://github.com/ppy/osu/blob/36ebdd8d30130276d59a1268d85af28b17935324/osu.Game.Rulesets.Osu/Mods/OsuModSynesthesia.cs#L39-L44

and this comment seems to imply that the thing is largely there for diffcalc purposes:

https://github.com/ppy/osu/blob/36ebdd8d30130276d59a1268d85af28b17935324/osu.Game/Rulesets/Objects/SliderEventGenerator.cs#L69-L75

so what even would need to happen to progress this? Would one have to try and nuke that from the face of the earth and see what gameplay/difficulty implications this has?

**Comment by peppy** [comment]
The issue I see is that `SliderTailCircle` has become the new `LegacyLastTick`. It's holding a non-correct end time for sliders which could easily be used without realising (as has been in the editor in the issue that spurred the creation of this issue).

The discussion that needs to happen is whether we want this to continue to exist into the future, or whether it should
- Be confined to classic mod, removed from everywhere else (seems better but no idea how the implementation would look)
- Be confined to old beatmap versions (meaning beatmaps made after some point won't have the offset). Would be nice to fix this for new maps, but backwards compatibility is likely going to be an issue. And I have no idea (and don't really want to find out) if the 36ms offset is still required in stable for things to work correctly.

When this was implemented classic mod didn't even exist, so maybe it can be moved into a very localised implementation there?

**Comment by bdach** [comment]
Hmm. That's probably one to bounce off players and mappers alike, then.

We'll probably have to make this problem digestible to them somehow and concoct a less technical description, but it seems like it affects both playability and mapper agency.

**Comment by peppy** [comment]
Potentially.  The 36ms does mean that you can release sliders before they visibly end. If players prefer this then we may have to stick to it.

**Comment by Zyfarok** [comment]
I didn't know this was a thing in stable, but this would have a huge impact on difficulty if removed indeed. 36ms seems arbitrary, but it does make sense to allow the player to exit the slider-end within the 300s leniency at the very minimum, since there's no reason to allow a player to be late on hit-circles and slider-heads but not on slider-ends (and slider-ticks ?). The "follow-circle" radius being bigger than the radius of slider-ends (and slider-track) was partially addressing the issue but doesn't work well for fast sliders because the follow-circle size doesn't scale with the speed.

I would take it further and say it would make sense to even allow the player to reach that slider-end late too, effectively providing a timing leniency window to slider-ends, and also extending this behaviour to slider-ticks since there's not much reason to treat them differently. Having a timing leniency window on slider-ticks would reduce the feeling that a lot of players have that "fast-slider maps are random" and make it less necessary to "cheese" such sliders by snapping the slider-ticks directly and not following the track at all. This has the opposite problem of make slider-maps easier than originally designed to be. I'd love to see what the community thinks of this.

Note: This might sound weird, but this would be equivalent to making the follow-circle be a "3D cylinder where the 3rd dimension is time".

**Comment by Zyfarok** [comment]
In any case, my point is this LegacyLastTick should remain (unless an alternative leniency mechanic that allows for the same leniency), even for newer maps. If mappers want to have sliders that forces you to reach the slider-end without allowing for any "space"-leniency, then a new object-type should be created, with that object providing a visual hint of the "effective slider-end radius" to make it clear that the user should enter this circle (within a +/- 36ms of the slider-end timing ?).

**Comment by peppy** [comment]
The good thing about this one is that the existing implementation is in the user's favour, so leaving it be is not something many players would be against.

Another counter point is that this has gotten in the way of certain maps, and as far as I recall, has caused a clause in the ranking criteria to be added:

> There must be at least 10 milliseconds between a hit circle and the next object, and at least 20 milliseconds between the end of a slider and the next object. osu!mania and osu!catch difficulties are exempt from this.

(would be good if @Walavouchey or someone else can confirm this is the base reasoning, and not something notelock related)

**Comment by bdach** [comment]
For whatever it's worth, I also sent this thread over for the NAT's general consideration on the mapping side of things, and the general opinion seems to be leaning towards keeping it in as a generally beneficial mechanic, and if anything, tweaking it for very fast/gimmick sliders, as the part about figuring out where is "36ms before slider end circle" exactly is a very real pain on those.

There were a few solutions floated as to how to fix those degenerate cases (such as being able to turn leniency off, but with a clear visual indicator like a large tick; having the leniency scale with SV; etc.), but I'm not sure as to whether we want to be trialing new game mechanics right now.

> Another counter point is that this has gotten in the way of certain maps, and as far as I recall, has caused a clause in the ranking criteria to be added

I haven't seen that one, I'll go ask right now...

**Comment by peppy** [comment]
..I actually think it has something to do with ordering of tick vs hitcircle judgement causing scoring changes if placed too close together. In which case maybe the leniency actually *helps* here rather than hinders?

**Comment by bdach** [comment]
Blame on wiki says https://github.com/ppy/osu-wiki/pull/7433, which points to https://osu.ppy.sh/beatmapsets/1691083/discussion/-/generalAll#/3020552 (tl;dr it broke pp)

**Comment by Walavouchey** [comment]
> > There must be at least 10 milliseconds between a hit circle and the next object, and at least 20 milliseconds between the end of a slider and the next object. osu!mania and osu!catch difficulties are exempt from this.
> 
> (would be good if @Walavouchey or someone else can confirm this is the base reasoning, and not something notelock related)

this was written mainly to prevent double taps because they gave a whole lot of easy pp. it has nothing to do with the 36 ms slider thing

https://github.com/ppy/osu-wiki/pull/7433
https://osu.ppy.sh/community/forums/topics/1563145

![image](https://github.com/ppy/osu/assets/36758269/907512a2-6db3-4dbb-a6e1-b46cadd544c8)

**Comment by Zyfarok** [comment]
I didn't know it wasn't some form of leniency and that aiming the slider-end correctly could lead to a "miss". Thank you @Bubbleman532 for clarifying.

In that case, I would say the MINIMUM change necessary to make the behaviour sensible on fast-sliders should be that a player should be able to be validate the slider-end if he is inside the follow-circle at ANY TIME between that LegacyLastTick and the actual slider-end timing.

An additional question is: Should a player validate if he is within "follow-circle-radius"of the slider-end (within a virtual follow-circle centered at the slider-end) at some point during the 36ms that precede the slider-end timing, but wasn't inside the actual slider-ball-centered follow-circle during this period. (And this question could be extended to any intermediate location of the follow-circle from the LegacyLastTick to the slider-end)

Regardless of this, my suggestions above on the bidirectional leniency and application to slider-ticks still holds though.

**Comment by Bubbleman532** [comment]
"In that case, I would say the MINIMUM change necessary to make the behaviour sensible on fast-sliders should be that a player should be able to validate the slider-end if he is inside the follow-circle at ANY MOMENT between that LegacyLastTick and the actual slider-end timing."

This is general opinion as well - we're still discussing what the impact on accuracy that missing slider ends should have, as well as feedback for missing slider ends (stable players are used to seeing 100s and recognising them as missing a slider end on sv1, same with 50s on sv2)

**Comment by bdach** [comment]
So - to try to progress this out of discussion - the consensus seems to be:

- yes, legacy last tick should live
- yes, it is a problem on fast sliders
- there is an agreed-upon proposal of what _could_ be done about it

The first point doesn't seem to require action on our behalf, but are we willing to stomach / try out implementing the rest?

**Comment by peppy** [comment]
Maybe we just want to leave things as-is, if it's implemented well enough and working as expected. The workarounds we have in place could be revisited in a future where we make this offset more baked into the code, and less of a "legacy afterthought".

Probably doens't require immediate attention?

**Comment by peppy** [comment]
@smoogipoo interested in your opinion here. feels like maybe wasted effort in the short run to attempt to change this when it "works".

**Comment by Zyfarok** [comment]
> maybe we just want to leave things as-is

@peppy The legacy tick should remain BUT what should be changed is that the player should validate the slider-end if he is inside the follow-circle at any-point between the legacy last tick and the true slider-end, as discussed above, as the current stable behavior is problematic (counterintuitive), and especially apparent on fast-slider maps.

**Comment by Walavouchey** [comment]
the judgement is checked at a precise point 36 ms before the slider end, but @Zyfarok is saying that it should be valid to be inside the slider ball / follow circle at any time *between* the `LegacyLastTick` and the end of the slider.

consider the below slider from [this ranked map](https://osu.ppy.sh/beatmapsets/754103#osu/1595588). the position of the slider ball is the position of the `LegacyLastTick`. you need to be inside the follow circle, or inside the slider ball in case the follow circle is inactive, in order to hit the slider end.

![image](https://github.com/ppy/osu/assets/36758269/80ddd40d-a11a-495a-a127-88d5409d5178)

in the below video i first play the slider naively (which by the proposal *should* be valid), then "correctly" by taking into account the `LegacyLastTick` separation.

https://github.com/ppy/osu/assets/36758269/2b9c892a-4127-4543-b810-db215e37b4e1

this was discussed by @isakvik (-GN) and others in Bubbleman's lazer feedback discord

**Comment by peppy** [comment]
That is fucked up.

So you're proposing a change to stable *and* lazer to fix this issue in some weird edge case manner? Basically taking a hack and adding more hacks on top. I don't know that this is a great idea.

**Comment by smoogipoo** [comment]
The proposal makes intuitive sense given that the last tick is hidden. But that's all that I can really say at this point and I'm not making a call on it, because the last ticks is a primary cause of other headaches that I'm not entirely sure how to address yet (judgements - "combo drop").

**Comment by Zyfarok** [comment]
The original purpose of the LegacyLastTick makes sense: Basically, just like we allow the player to be a bit early or late on aiming and tapping circles through the hit-windows, it makes sense to also allow the players to be a bit early or late on aiming slider-ends and on the release of the key.

For that purpose, the legacy works well if the sliders have a reasonable speed because people will follow the track and as long as they don't release the key any earlier that the LegacyLastTick, they validate the slider-end.

But for fast sliders and weirdly shaped slides, players naturally "snap" the slider-ticks and slider-ends to reduce the risk of missing instead of following the track regularly.

This is why i believe the approach suggested above makes a lot of sense.

One alternative solution could have been to only check that the key is still hold on the LegacyLastTick, but actually only check the aim part (that the cursor is inside the follow-circle) at the timing of the slider-end. This would be simpler but would however be a huge change in behavior compared to stable and all players would have to relearn how to aim slider-ends as they were previously intuitively leaving the slider-track early.

**Comment by Zyfarok** [comment]
Yep, the OD-dependent leniency would make sense. It would probably have to be larger than the current hit-window of 300s though ? (to stay around ~30 on OD 10)

**Comment by peppy** [comment]
I'm going to move this out of discussion and look at a path forward based on the above feedback. Thanks to everyone for providing opinions and expectations, should help a lot with coming to an amicable solution.

My initial investigation will be adding test coverage of these edge cases (if it doesn't already exist) and then looking at whether we can change this to a release lenience, not having it positional based, as per the unanimous agreement above that this is a good direction.

Whether this gets ported back to stable or not is another question we can deal with later.

**Comment by peppy** [comment]
I'm still going through this structurally to figure how we can fit this into the code in the nicest way possible, but to summarise and make sure I have the right idea, conceptually:

- At a fixed 36ms before a slider's true end time, the player must be tracking the slider (aka the follow circle is expanded)

This is the **only** condition I see being required here. @Zyfarok @isakvik @Walavouchey please confirm this meets your expectations.

**Comment by peppy** [comment]
I guess the above is incorrect for the example @Walavouchey brought up. The player may not be tracking because they are aimed at the end instead?

So I guess the conditions would have to be something like either:

- At a fixed 36ms before the slider's true end time, the player must be tracking the slider, OR
- At the slider's true end time, the player must be tracking the slider.

or, another proposal

- At a fixed 36ms before the slider's true end time, the player must be within tracking range of either the `LegacyLastTick` or the slider's true end position (or somewhere in between??)

Both of these could be pretty ugly to implement, so I'd want to get consensus before going too far down a rabbit hole.

**Comment by Walavouchey** [comment]
> - At a fixed 36ms before a slider's true end time, the player must be tracking the slider (aka the follow circle is expanded)

i.e. current behaviour

> - At a fixed 36ms before the slider's true end time, the player must be tracking the slider, OR
> - At the slider's true end time, the player must be tracking the slider.

you get two discontinuous alternatives for where to aim (potentially separated by a large distance), which as you can imagine still leaves janky edge cases

> - At a fixed 36ms before the slider's true end time, the player must be within tracking range of either the `LegacyLastTick` or the slider's true end position (or somewhere in between??)

(including anywhere in between) this is probably what i described, yes

in terms of the video example, you'd be able to aim anywhere in between the `LegacyLastTick` position and the true slider end

**Comment by isakvik** [comment]
> At a fixed 36ms before the slider's true end time, the player must be within tracking range of either the LegacyLastTick or the slider's true end position (or somewhere in between??)

"Somewhere in between" is pretty important to actually achieving the goal of more lenient sliders rather than something that's gonna be accidentally circumvented in other maps with ridiculous slider speeds (like the kinds of maps they put into OWC's NM3 slot, for example). The ideal version would be:

* Between a fixed 36ms and the slider's true end time, the player must have been tracking the slider at some point

I don't see this version being possible without saving some state on a per-slider basis, though. 

If you would want to avoid that, something like having multiple ticks at the end of a slider (dividing the 36ms window into multiple), and only requiring you to be tracking the slider on one of them OR at the slider's true end is a practical idea - I'd say 3 ticks with a 12ms window would be sufficient since there would start to be significant overlap in followcircle area on even the most ridiculous ranked slider.

**Comment by peppy** [comment]
Luckily it is possible, and I have it working solidly. So as long as everyone is on board with:

- The player must be in a tracking state at **any point** between 36 ms before the slider's end time and the slider's end time.

Here's how this looks in practice (20% speed, 240 BPM slider with SV 10x to exaggerate lenience position, green = final tick hit, red = final tick missed):

## Miss

https://github.com/ppy/osu/assets/191335/420acf91-d762-4718-b723-5f2687362a55

## Valid hits

https://github.com/ppy/osu/assets/191335/ea3e93b3-e4c1-41c8-be6d-d58dd4be64de

https://github.com/ppy/osu/assets/191335/12ffba12-e9fe-47f5-8d4a-5a241cf8de65

https://github.com/ppy/osu/assets/191335/4dc684ce-1dab-4133-ad7f-794c8d4a73cc

https://github.com/ppy/osu/assets/191335/6f6c90d1-33b5-4af6-82c6-773cd70bd767

https://github.com/ppy/osu/assets/191335/d5d3b584-2446-4bca-ae86-766a1667a91c

We good?
