### ISSUE TITLE
Some (wmv) videos cause hard crashes on some platforms

### ISSUE THREAD

**Issue by r00ster91** [ppy/osu#22829]
### Type

Crash to desktop

### Bug description

https://osu.ppy.sh/beatmapsets/72#osu/166

This 15-year-old beatmap causes a crash for me when I start it on the newest osu!lazer for desktop (I'm on Linux). The first time it crashed for me was in a multiplayer room with Hard Rock on. Now in solo without any mods it crashes too.
In the multiplayer room it crashed for one other person too, not the host though (I think he used other mods too).

### Version

2023.305.0-lazer

### Logs

Because the issue seems to be quite consistent (it has never not crashed for me when I started the map) and this seems easy to reproduce I have decided to not provide logs.
Well I saw this after taking a quick look:
```
 60 2023-03-10 14:51:55 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
 59 2023-03-10 14:51:55 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
 58 2023-03-10 14:51:55 [error]: at osu.Framework.Threading.GameThread.processFrame()
 57 2023-03-10 14:51:55 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
 56 2023-03-10 14:51:55 [error]: An unhandled error has occurred.
 55 2023-03-10 14:51:55 [error]: System.ArgumentException: '0' cannot be greater than -9223372036854776.
 54 2023-03-10 14:51:55 [error]: at System.Math.ThrowMinMaxException[T](T min, T max)
 53 2023-03-10 14:51:55 [error]: at osu.Framework.Graphics.Animations.AnimationClockComposite.get_PlaybackPosition()
 52 2023-03-10 14:51:55 [error]: at osu.Framework.Graphics.Video.Video.Update()
 51 2023-03-10 14:51:55 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
 50 2023-03-10 14:51:55 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
 49 2023-03-10 14:51:55 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
```
Again, you should be able to reproduce this consistently on your own (you might need Linux though) so that you can take a look yourself.

**Comment by gadielisawesome** [comment]
It did the same thing for me on my iPhone.

**Comment by peppy** [comment]
Please attach your full `runtime.log`, not just an excerpt of it.

**Comment by r00ster91** [comment]
Are you not able to reproduce it? Here you go. [runtime.log](https://github.com/ppy/osu/files/10948402/runtime.log)

**Comment by monochrome22** [comment]
It will only crash with Storyboard / video enabled.
Interestingly, if you go into editor and save without making any changes, then it will no longer crash, but the video won't load. Also, even if you delete the video file, it still crashes. This map does not have a storyboard.

**Comment by peppy** [comment]
> Are you not able to reproduce it? Here you go. [runtime.log](https://github.com/ppy/osu/files/10948402/runtime.log)

Regardless of this, we ask that you attach the full log as the excerpt you provided is not useful in isolation.

I can't repro, but here's the relevant log portion:

```csharp
2023-03-11 11:40:55 [error]: An unhandled error has occurred.
2023-03-11 11:40:55 [error]: System.ArgumentException: '0' cannot be greater than -9223372036854776.
2023-03-11 11:40:55 [error]: at System.Math.ThrowMinMaxException[T](T min, T max)
2023-03-11 11:40:55 [error]: at osu.Framework.Graphics.Animations.AnimationClockComposite.get_PlaybackPosition()
2023-03-11 11:40:55 [error]: at osu.Framework.Graphics.Video.Video.Update()
2023-03-11 11:40:55 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2023-03-11 11:40:55 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
```

It looks like an issue with the video on some platforms, where the length is somehow being read as a very negative number. Potentially a 32/64bit conversion error. Will require further investigation from someone that can reproduce this themselves. Probably guarding rather than crashing in `Video`.

**Comment by monochrome22** [comment]
After further investigation, it seems that the crash happens when background is written as 1,0 in .osu [Events].

Beatmap mentioned in this issue:
Crashes:
[Events]
1,0,"daft.jpg"
1,0,"daft.wmv"

Doesn't crash:
[Events]
0,0,"daft.jpg"
1,0,"daft.wmv"

Other maps that also crash: 
[Beatmap id 151](https://osu.ppy.sh/beatmapsets/151) The (Easy) difficulty crashes, (Normal) difficulty doesn't. 
(Easy) difficulty:
[Events]
1,0,"p3title.jpg"
1,0,"video.wmv"

(Normal difficulty):
[Events]
0,0,"p3title.jpg"
1,0,"video.wmv"

Another map that crashes is [Beatmap id 664](https://osu.ppy.sh/beatmapsets/664). This one uses .avi as a video file. The (Easy) difficulty doesn't crash, other difficulties crash. 
(Easy) difficulty:
[Events]
//Background and Video events
0,-1,"ssbm.jpg"
1,300,"faruconpan.avi"

Other difficulties:
[Events]
1,0,"ssbm.jpg"
1,300,"faruconpan.avi"

**Comment by peppy** [comment]
Thanks for that, it helps a lot.
