### ISSUE TITLE
SDL fullscreen display error on iPad 

### ISSUE THREAD

**Issue by vladfrangu** [ppy/osu#22997]
### Type

Other

### Bug description

I'm currently running osu!lazer on an iPad Pro 11' from 2021, and with the recent update (which brings Metal support too, although that seems to have its own performance issues that I don't know where to start reporting), every time the game is launched (either in Metal or OpenGL (Legacy) mode, OpenGL crashes on boot) the `Failed to get fullscreen display mode: Display index: 0. SDL error: Couldn't find display mode match` warning/error is thrown. This doesn't _seem_ to affect anything but it also doesn't look intended. I _did_ see there was a commit on osu-framework possibly related to this, but I thought I'd report it here to be safe! 😅 

### Version

2023.326.1-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11073313/database.log)
[input.log](https://github.com/ppy/osu/files/11073314/input.log)
[network.log](https://github.com/ppy/osu/files/11073315/network.log)
[performance.log](https://github.com/ppy/osu/files/11073316/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11073317/runtime.log)

**Comment by Joehuu** [comment]
This is already tracked as a framework issue at https://github.com/ppy/osu-framework/issues/5709. Will leave this open for more visibility, though.

**Comment by vladfrangu** [comment]
The one place I didn't think to search for the error, my bad! 😅

**Comment by peppy** [comment]
This is a bit of a painful one to investigate. It seems like framework is trying to set or map a display mode (possibly left in the user's config?) which isn't available on the target device.

On the way I noticed a few things:

- The code to set the default display mode no longer works as `Window` is always null at the point of attempting to access it:

https://github.com/ppy/osu-framework/blob/dadea495a1ad4e572690fce6682cd6ff8e0c2ba3/osu.Framework/Platform/GameHost.cs#L1152-L1153

This regressed with the reversing of init order to allow the preferred renderer to be read from config.

- The whole `tryFetchDisplayMode` is kinda pointless and doing too much on mobile.
- In my testing, the window state is changing multiple times on iOS startup. We probably want to get that down to one at most.

**Comment by Susko3** [comment]
(The below logs are in chronological order)

The function that is causing an error ([tryFetchDisplayMode](https://github.com/ppy/osu-framework/blob/2e68808cdbca97d2fb91eac4542de3a7fd296ec5/osu.Framework/Platform/SDL2Window_Windowing.cs#L619-L651)) works fine at first. Note that it queries the `desktop` resolution, meaning the window being in `WindowMode.Windowed` is helping it. The resolution is scaled, which is to be expected from Apple devices, and the refresh rate (something that matters for the frame limiter) is correct: 120 Hz "ProMotion".

```cs
2023-03-26 23:05:35 [verbose]: Updated display mode to desktop resolution: 1194x834@120, SDL_PIXELFORMAT_ABGR8888
```

Later, when the window state is fullscreen (most likely set to fullscreen [here](https://github.com/ppy/osu-framework/blob/d0a25b53d56deff1f04c7f0ed69406effede9317/osu.Framework.iOS/IOSWindow.cs#L38-L37), and then later fetched [here](https://github.com/ppy/osu-framework/blob/2e68808cdbca97d2fb91eac4542de3a7fd296ec5/osu.Framework/Platform/SDL2Window_Windowing.cs#L551)) the function fails. I presume this is because SDL on iOS doesn't expose any fullscreen modes, as an application cannot change the fullscreen resolution.

```cs
2023-03-26 23:05:36 [verbose]: SDL error log [debug]: Couldn't find display mode match
2023-03-26 23:05:36 [error]: Failed to get fullscreen display mode. Display index: 0. SDL error: Couldn't find display mode match
```

There is also this entry a bit later, but no framework logging. Seems like we don't have error handling set up for this callsite.

```cs
2023-03-26 23:05:36 [verbose]: SDL error log [debug]: Couldn't find display mode match
```

I think the main issue here is that we consider and set the iOS SDL window to be fullscreen, even though there are no fullscreen modes available. Would be useful to have confirmation on this (@peppy `TestSceneDisplayMode` in framework tests should be useful here).

The window is set to fullscreen with the intention of hiding the status bar ([link](https://github.com/ppy/osu-framework/blob/d0a25b53d56deff1f04c7f0ed69406effede9317/osu.Framework.iOS/IOSWindow.cs#L37)). The [docs](https://wiki.libsdl.org/SDL2/README/ios#notes----iphone-sdl-limitations) mention using the `SDL_WINDOW_BORDERLESS` flag to hide it instead. Maybe things would work out better if we consider the window to be `WindowMode.Borderless` and set the flags as SDL expects it (the more things we leave as default, the better, so probably best to avoid calling `SDL_SetWindowFullscreen` and the like on mobile platforms).

Having a `protected virtual SDL.SDL_WindowFlags GetDefaultWindowFlags()` that are passed into `SDL_CreateWindow` could be useful for this.

**Comment by Susko3** [comment]
I'd like to fix this, but I don't have any iOS device to test on. I could make a PR with what I have in mind if you wish.

**Comment by peppy** [comment]
This has been silenced for now, so I'll close the issue. I'm not sure how important a more resilient fix is (and I know there was some other work done around this area so it may already be in a better state).
