### ISSUE TITLE
Saving a replay while displaying a video goes to the leaderboards.

### ISSUE THREAD

**Issue by toadsworth-jr** [ppy/osu#23016]
### Type

Crash to desktop

### Bug description

Saving failed replays with a video displayed on the background causes the game to go to the leaderboard screen as if the player had just successfully passed the map.
This doesn't work with storyboards, as it just functions as intended.

### Screenshots or videos

https://user-images.githubusercontent.com/75596775/227962469-b2a41012-0a09-4df3-b438-99ac2cf7eda7.mp4

### Version

2023.326.1

### Logs

[database.log](https://github.com/ppy/osu/files/11079401/database.log)
[network.log](https://github.com/ppy/osu/files/11079402/network.log)
[performance.log](https://github.com/ppy/osu/files/11079403/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11079404/runtime.log)

**Comment by bdach** [comment]
Have looked at this one briefly and the following logic is primarily at fault:

https://github.com/ppy/osu/blob/6924dc5c5066e761e00822c47a62f9999dbc69b8/osu.Game/Screens/Play/Player.cs#L361-L365

WIth videos, the last event time is the start time of the video (since they don't currently have a duration), which means that the storyboard will be marked "ended" as soon as the video starts. This activates the entire `progressToResults()` machinery which then fires at the first available chance (namely, when it is allowed to import a score via the button on the fail overlay).

Unsure if it's a regression from the last changes to that logic. It might have been exposed by them, but the "storyboard ends at video start" issue has been there for longer than that.

**Comment by peppy** [comment]
From what I can tell, the main issue here stems from some of the completion check logic existing locally inside `scoreCompletionChanged`:

https://github.com/ppy/osu/blob/556964eae0ad400e2d8157b42cbd1137659e20d5/osu.Game/Screens/Play/Player.cs#L732-L734

But this is not being checked when `progressToResults` is triggered by a storyboard reaching the end.

So really, this was a bug waiting to happen but avoided until now by storyboards always having a delay from the end of gameplay before they trigger the logic.

**Comment by peppy** [comment]
And the reason this didn't trigger until now (and only happens on a fail replay import) is that the call to `progressToResults` from the storyboard end conditional was being early returned inside a scheduler loop by this line:

https://github.com/ppy/osu/blob/556964eae0ad400e2d8157b42cbd1137659e20d5/osu.Game/Screens/Play/Player.cs#L773

...which gets unblocked when the fail replay is imported. Very very dodgy.
