### ISSUE TITLE
Skin elements cannot be selected via left or right click when flipped horizontally or vertically

### ISSUE THREAD

**Issue by ikkue** [ppy/osu#23042]
### Type

Game behaviour

### Bug description

How to recreate:

1. Select ~~`DefaultSongProgress`~~ any skin element in the skin editor.
2. Flip the element horizontally or vertically using the "Flip horizontally" or "Flip vertically" button respectively.

The element now cannot be left or right-clicked as if its hitbox has seemingly disappeared somewhere else.

### Screenshots or videos

Video: https://youtu.be/L2kgwUHjMZY

### Version

2023.326.1

### Logs

[database.log](https://github.com/ppy/osu/files/11092301/database.log)
[input.log](https://github.com/ppy/osu/files/11092302/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11092303/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11092304/network.log)
[performance.log](https://github.com/ppy/osu/files/11092305/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/11092306/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/11092307/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/11092308/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/11092309/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/11092311/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11092312/updater.log)

**Comment by bdach** [comment]
The issue is a lot more general than the OP presents. Can happen for any skin element, after horizontal *or* vertical flip.

Pretty sure this is inadvertently caused by https://github.com/ppy/osu-framework/pull/5670. That pull assumed that `Quad` always has verts in screen-space counterclockwise fashion as per [comments](https://github.com/ppy/osu-framework/blob/d586bb33ad4961d98db7c7f5a1acd7762977752b/osu.Framework/Graphics/Primitives/Quad.cs#L15-L20), but this is not actually going to be the case here after a flip is done.

Not sure whether it's the game's fault or the framework's...

**Comment by bdach** [comment]
So initially I was going to change `Quad.FromRectangle(RectangleF)` to normalise the rectangle before converting it to a quad, which *would* fix this exact scenario, but then I realised that from a framework perspective, you can also do

```csharp
            var quad = new Quad(-5, -5, 10, 10);
            quad *= new Matrix3(
                -1, 0, 0,
                0, 1, 0,
                0, 0, 1);
```

and the problem is immediately back, and you can't normalise very easily anymore.

So I'd probably be tending to go fix `Quad.Contains()` again. I have 2 variants to offer:

### Fast but ugly

```csharp
        public bool Contains(Vector2 pos)
        {
            if (Width == 0 && Height == 0)
                return pos == TopLeft;

            float perpDot1 = Vector2.PerpDot(BottomLeft - TopLeft, pos - TopLeft);

            float perpDot2 = Vector2.PerpDot(BottomRight - BottomLeft, pos - BottomLeft);
            if (float.IsNaN(perpDot2) || perpDot1 * perpDot2 < 0) // negative product of perpDots means that one must be positive and one negative => point can be rejected.
                return false;

            float perpDot3 = Vector2.PerpDot(TopRight - BottomRight, pos - BottomRight);
            if (float.IsNaN(perpDot3) || perpDot1 * perpDot3 < 0 || perpDot2 * perpDot3 < 0)
                return false;

            float perpDot4 = Vector2.PerpDot(TopLeft - TopRight, pos - TopRight);
            if (float.IsNaN(perpDot4) || perpDot1 * perpDot4 < 0 || perpDot2 * perpDot4 < 0 || perpDot3 * perpDot4 < 0)
                return false;

            return true;
        }
```

|   Method | NumPoints |        Mean |      Error |    StdDev | Allocated |
|--------- |---------- |------------:|-----------:|----------:|----------:|
| Contains |        10 |    71.46 ns |   1.221 ns |  1.254 ns |         - |
| Contains |       100 |   686.28 ns |   6.623 ns |  6.195 ns |         - |
| Contains |      1000 | 7,096.99 ns | 101.865 ns | 95.284 ns |         - |

Performance is almost unchanged, surprisingly.

### Nice but slower

```csharp
        public bool Contains(Vector2 pos)
        {
            if (Width == 0 && Height == 0)
                return pos == TopLeft;

            int orientation = MathF.Sign(Vector2Extensions.GetOrientation(GetVertices()));
            if (orientation == 0)
                // quad has degenerated to a point or segment - at this point clockwise or counterclockwise order doesn't matter.
                orientation = 1;

            return Vector2.PerpDot(BottomLeft - TopLeft, pos - TopLeft) * orientation <= 0
                   && Vector2.PerpDot(BottomRight - BottomLeft, pos - BottomLeft) * orientation <= 0
                   && Vector2.PerpDot(TopRight - BottomRight, pos - BottomRight) * orientation <= 0
                   && Vector2.PerpDot(TopLeft - TopRight, pos - TopRight) * orientation <= 0;
        }
```

|   Method | NumPoints |        Mean |     Error |    StdDev | Allocated |
|--------- |---------- |------------:|----------:|----------:|----------:|
| Contains |        10 |    102.9 ns |   2.08 ns |   2.55 ns |         - |
| Contains |       100 |  1,012.3 ns |  20.05 ns |  37.67 ns |         - |
| Contains |      1000 | 10,568.8 ns | 211.34 ns | 282.13 ns |         - |

@ppy/team-client thoughts?

**Comment by peppy** [comment]
I'd still go for the fast solution, as this is very very low level code that *in theory* we should not need to touch after it's working to expectations.
