### ISSUE TITLE
Can't move timing point using "Use current time"

### ISSUE THREAD

**Issue by reo-the-enby** [ppy/osu#23147]
### Type

Game behaviour

### Bug description

Moving back in the timeline and then clicking a timing point moves you

### Screenshots or videos

https://user-images.githubusercontent.com/81715029/230337844-f8847e85-679e-4c63-83d9-e31e400280b9.mov

### Version

2023.403.1

### Logs

.

**Comment by smallketchup82** [comment]
The timing editor currently tracks the control point left of the timeline clock. 

I think that the easiest way to fix this (to an extent) is to change tracking behaviour to track the nearest control point to the clock. This would allow for more manoeuvrability but would also be bad if you want to, say, move the control point to the other end of the map.

Another way to go about it is to move the button to a right click menu. This allows for updating the position of the control point to basically anywhere in the map, but also require more effort than the other method to implement.

The last way that I thought of, is to remove the tracking system and instead change the behaviour of the control point rows. To select a control point, you click it in the table. To seek to it, you double click it in the table. The tracking system is modified to instead of selecting the beatmap left of the cursor, it simply highlights it in the control point table to show which control point you're in the domain of. This allows you to go back to a control point to edit it without having to change position & fixes the issue of moving timing points.

I personally think that the first one would be good enough for _most_ use cases. The second one would provide a complete fix but would take longer to implement vs the first solution. The third one makes the timing editor feel more like the typical NLE but is really extreme when considering the scope of this issue.
