### ISSUE TITLE
LN head persists when notes are released late but not missed

### ISSUE THREAD

**Issue by longnguyen2004** [ppy/osu#23186]
### Type

Game behaviour

### Bug description

If LNs are released late, the LN heads persist, even though it's not counted as a miss. This is very obvious in LN heavy maps, where people usually release late, which causes a lot of visual clutter.

### Screenshots or videos

Both video contains 3 cases: released "in time", released early, released late. The first 2 cases are correct, while the last one is wrong

stable
https://user-images.githubusercontent.com/15729831/231247537-02ba5867-daea-405c-b167-d4747fe348b3.mp4

lazer
https://user-images.githubusercontent.com/15729831/231248170-d45ba6f0-591f-4349-bd0c-460c80675532.mp4

### Version

2023.403.1

### Logs

[database.log](https://github.com/ppy/osu/files/11203424/database.log)
[input.log](https://github.com/ppy/osu/files/11203425/input.log)
[network.log](https://github.com/ppy/osu/files/11203426/network.log)
[performance.log](https://github.com/ppy/osu/files/11203427/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11203428/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11203429/updater.log)

**Comment by bdach** [comment]
I see the difference but am not sure which way is necessarily "correct". Probably need mania player opinions as to whether this is more of a "classic mod setting" situation or something to fix globally without a setting.

**Comment by longnguyen2004** [comment]
I'd vote for a global change, since no other VSRGs behave like that (to my knowledge anyway)

**Comment by Eve-ning** [comment]
stable looks fine, I'd say that lazer's implementation is off

I'd recommend to fix globally

**Comment by peppy** [comment]
So it's not about "persisting" or not. This is only a side-effect of your skin having a texture where you can't see the full length of the hold note.

The issue is that it resumes the scroll animation as soon as the end time of the hold is reached. This is due to the method we're using to keep the head object aligned (adjusting the size of the container which is being used to draw the full hold note):

https://github.com/ppy/osu/blob/d97daee96be2c10f90709cc30beceb1f369ae225/osu.Game.Rulesets.Mania/Objects/Drawables/DrawableHoldNote.cs#L243-L251

Not sure how easy this is going to be to resolve. May have to change the strategy used to align the head so it can remain stationary until judgement is completed.
