### ISSUE TITLE
"Angle sharpness" slider value doesn't always scale by 0.5 with the arrow keys

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#23202]
### Type

Other

### Bug description

As title: changing the "angle sharpness" slider of the Random mod using the arrow keys doesn't always increase/decrease its value by `0.5`.

### Screenshots or videos

![slider](https://user-images.githubusercontent.com/43073074/232024633-89c5794e-1880-4a99-8822-c1ff2de7ba98.gif)

### Version

2023.403.1-lazer

### Logs

n/a

**Comment by Terochi** [comment]
This happens because we explicitly say to use `SettingSlider<float>` in `SettingSourceAttribute`, which leads to having the step value 1/20th of the full range (`0.45` in this case). The default step value for all other floating point sliders is `0.1`. This is also the case for [Muted](https://github.com/ppy/osu/blob/master/osu.Game/Rulesets/Mods/ModMuted.cs#L44) and [AccuracyChallenge](https://github.com/ppy/osu/blob/master/osu.Game/Rulesets/Mods/ModAccuracyChallenge.cs#L35), although there the the default behavior feels correct. So either don't specify the control type [here](https://github.com/ppy/osu/blob/master/osu.Game/Rulesets/Mods/ModAccuracyChallenge.cs#L35) and rely on the default step of `0.1` or create a new type that explicitly sets this value to something else (as said `0.5` probably works best here).
