### ISSUE TITLE
My android phone overheating and discharging when playing osu!(lazer)

### ISSUE THREAD

**Issue by yesseruser** [ppy/osu#23223]
### Type

Performance

### Bug description

When playing Lazer on my Google Pixel 6 (with Android 13), the phone overheats and discharges much more than when playing other games. (Overheating is much more notable, and a big problem since players on mobile usually hold their phone in their hands).
I am not using a phone case.

### Version

2023.403.1-lazer

### Logs

Here are my logs:
[database.log](https://github.com/ppy/osu/files/11254096/database.log)
[network.log](https://github.com/ppy/osu/files/11254098/network.log)
[performance.log](https://github.com/ppy/osu/files/11254099/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11254100/runtime.log)

**Comment by yesseruser** [comment]
This issue seems to be more apparent in multithreaded mode than single threaded mode.

**Comment by tutacat** [comment]
osu! is not optimised, so it doesn't work as well on android, because phones have (generally) less performance than desktops, and the thermal design is not as optimised for high performance long-running tasks.
So devices that are budget will struggle. This also means even if it is running well, it is probably pinning the SoC. The best option is to limit the framerate, and single threading the renderer will reduce the effective framerate because it is limited to a single thread. That is why. Maybe force it at 60fps, or, possibly, 120fps. But lower framerate means less CPU pinning and less heat generated.

**Comment by peppy** [comment]
Multi-threaded is not intended for mobile use. Use single thread.
