### ISSUE TITLE
Mipmap generation no longer works properly on Android

### ISSUE THREAD

**Issue by p3nguin-kun** [ppy/osu#23249]
### Type

Cosmetic

### Bug description

When I update to 2023.419.0, I can see aliasing everywhere in osu!lazer, even when I turn on 2x anti-aliasing

Device: Vsmart Active 1 (BQ Aquaris X2 Pro)

Android: 10

CPU: Qualcomm Snapdragon 660

![Screenshot_20230420-122751](https://user-images.githubusercontent.com/123321507/233269990-62eeb0b1-b677-469d-a6af-4dd0d2c32fb1.png)
![Screenshot_20230420-123342](https://user-images.githubusercontent.com/123321507/233270070-58100f6d-411f-4db5-9e7a-fdc7d1e3e6e2.png)
![Screenshot_20230420-123918](https://user-images.githubusercontent.com/123321507/233270106-eee1495b-6d2e-4c30-8564-061a6a67635f.png)
![Screenshot_20230420-124022](https://user-images.githubusercontent.com/123321507/233270208-ac790315-51a4-4a6a-81bf-a00806c1a5ea.png)
![Screenshot_20230420-123934](https://user-images.githubusercontent.com/123321507/233270242-0589ff2f-2ca7-472c-bd11-302df8b04355.png)

### Version

2023.419.0

### Logs

[database.log](https://github.com/ppy/osu/files/11280230/database.log)
[network.log](https://github.com/ppy/osu/files/11280231/network.log)
[runtime.log](https://github.com/ppy/osu/files/11280232/runtime.log)
[performance.log](https://github.com/ppy/osu/files/11280233/performance.log)

**Comment by frenzibyte** [comment]
Can you confirm what you're seeing is similar to https://github.com/ppy/osu/issues/23240?

**Comment by p3nguin-kun** [comment]
> Can you confirm what you're seeing is similar to #23240? Nevermind, it looks like you have the osu! logo displaying correctly.

seem like that but osu! logo is not bugged

**Comment by p3nguin-kun** [comment]
> Can you confirm what you're seeing is similar to #23240? Nevermind, it looks like you have the osu! logo displaying correctly.

seem like that but osu logo is not bugged

**Comment by frenzibyte** [comment]
Let's keep this open for now.

**Comment by p3nguin-kun** [comment]
> > Can you confirm what you're seeing is similar to #23240? Nevermind, it looks like you have the osu! logo displaying correctly.
> 
> seem like that but osu logo is not bugged

everything runs properly, just aliasing

**Comment by Susko3** [comment]
**Devices:**
- Realme 6
Android 11
Mediatek MT6785 Helio G90T
Mali-G76 MC4
2400x1080

- LG G7 Fit
Android 9
Qualcomm MSM8996 Snapdragon 821 
Adreno 530
3120x1440

- Samsung Galaxy 02s
Android 12
Qualcomm SDM450 Snapdragon 450
Adreno 506
1600x720

There is a difference with @frenzibyte's branch, but it doesn't fix the issue, and it seems it's [mostly negative](https://discord.com/channels/188630481301012481/589331078574112768/1099372149254398013).

Sample as it appears on each device with [frenzibyte/compute-mipmap-generation@7a0f5c6a](https://github.com/frenzibyte/osu-framework/tree/7a0f5c6aaa39ae30ab1214157671ee870ba46fe8):

(The Samsung looks the worst, but it could be due to screen resolution/density.)

Realme:

![dev](https://user-images.githubusercontent.com/16479013/233796651-8191ccea-094b-48ad-9202-986ad68795d4.png)

LG:

![dev](https://user-images.githubusercontent.com/16479013/233796662-8cddde17-2ef2-41eb-a023-e60c0d3afab2.png)

Samsung:

![dev](https://user-images.githubusercontent.com/16479013/233796696-20c0e6ba-14aa-4cd5-aa5b-9e99166c1d43.png)
