### ISSUE TITLE
"Encountered unsupported tablet" on a supported tablet with weird behaviour of the cursor

### ISSUE THREAD

**Issue by eversiege** [ppy/osu#23289]
### Type

Game behaviour

### Bug description

I have a Wacom CTL-672, which is supported by OpenTabletDriver. I have also installed required Wacom drivers for the tablet to work. osu! behaves really erratically with my cursor, jumping back and forth to a smaller window. Scrollable items don't appear to be hit, unless they are big enough. 

### Screenshots or videos

https://user-images.githubusercontent.com/69052669/233814884-8daad229-10bc-4c7c-9aca-6c64b40027ce.mp4

### Version

2023.419.0-lazer (latest as of 23/04)

### Logs

[logs.zip](https://github.com/ppy/osu/files/11302643/logs.zip)

**Comment by hwsmm** [comment]
OTD doesn't require Wacom drivers at all. You need to remove it for OTD to function correctly.

**Comment by frenzibyte** [comment]
The notification comes directly from these warning messages sent by OTD:
```
2023-04-23 01:46:12 [verbose]: [Tablet] Detect: Searching for tablets...
2023-04-23 01:46:12 [important]: [Tablet] Device: Failed to set device feature: 02-02
2023-04-23 01:46:12 [verbose]: [Tablet] Detect: Found tablet 'Wacom CTL-672'
2023-04-23 01:46:12 [important]: [Tablet] Detect: Failed to find auxiliary device, express keys may be unavailable.
```

That was already fixed in https://github.com/OpenTabletDriver/OpenTabletDriver/issues/1170, pending new OTD release.

Also, as per above, try disabling Wacom drivers, as it may potentially intercept tablet input from reaching the game. Report back if it doesn't work for you, I'll close the issue for the time being.

**Comment by eversiege** [comment]
UPD: Figured out why it behaved like this, apparently Windows Ink is the issue.
