### ISSUE TITLE
Reconsider scoring of `SmallTick` / `LargeTick`

### ISSUE THREAD

**Issue by peppy** [ppy/osu#23403]
Opening a tracking issue to make sure this discussion is not missed, as I think it's quite important in terms of game balance.

### Discussed in https://github.com/ppy/osu/discussions/22884

<div type='discussions-op-text'>

<sup>Originally posted by **Rekunan** March 17, 2023</sup>
If I'm understanding the scoring page in the GitHub wiki correctly (https://github.com/ppy/osu/wiki/Scoring#hit-results), `LargeTick` represents a slider tick and `SmallTick` represents a sliderend. That would mean that compared to Stable, giving a weighting of 100 for dropped sliderends, and 100 or 50 for dropped slider ticks, they only have a weighting of 10 and 30 respectively. I would like to ask why that is, and if possible, for them to be increased to either 50 or 100.

As it stands, players have very little incentive to aim for sliderends as they no longer contribute to combo, and they have a miniscule impact on accuracy. This means that if the difficulty of aiming to sliderends is too much, such as on maps with hard sliders, players will opt for dropping sliderends as it preserves combo, and it'll only drop accuracy minutely.

Even if players choose to play the same way as in stable, it becomes harder to compare scores on maps with hard sliders unless you look for the pp value or the slider ticks and slider ends metric in the score details screen.</div>

**Comment by Zyfarok** [comment]
What makes a gameplay element important or not is both the judgement value and whether it gives combo and break combo.
- Currently, slider-ticks (LargeTick) giving 30 points are fine, because they also give 1 combo and can break combo too. Most of the weight of the tick is on the combo-break potential. It might be better to have them be upgraded to 50 or 100 points so that they also impact the accuracy part of the score, especially for low-combo plays, but that's about it.
- But for slider-ends (SmallTick), they only give 10 points and have no impact on combo at all (while they did give 1 combo in stable). It's fine to have them not give combo but then they indeed have to give at the very least 100 points, and it would make sense for them to give something closer to 200. In stable (v1 and v2), "missing" a slider-end makes you do a 100 on the slider, thus virtually giving a weight of 200 points to the slider-end, additionally to the "loss" of 1 combo which can also have a big impact on the score. The weighting of slider-ends in stable is very reasonable thus it would make sense to have a similar weighting in lazer.

**Comment by smoogipoo** [comment]
Is the issue that judgement results are different? There's certainly an argument to be made for that, but I'm not sure it's the primary issue here. We've already made [concessions](https://github.com/ppy/osu/pull/24166) that lazer scoring is not going to match stable scorev2, even initially, so judgement results being different is fine imo (as long as it's justified).

As far as I understand, the primary issue is the difference in acc/combo additions. In particular, slider ends only drop accuracy but not combo in lazer.

**Comment by bdach** [comment]
I guess as per [the summary newspost](https://osu.ppy.sh/home/news/2023-07-11-community-meeting-recap) from the last community discussion there is nothing to discuss here balance-wise as the consensus is that osu!-the-ruleset slider tick score values should be restored to parity with stable?

Just switching the numerical values as the OP suggests is going to impact catch too as it also uses the current 10 / 30 values.

> Strong hit ... `LargeBonus * 7`
> Large drum roll hit ... `LargeBonus * 3 + SmallBonus`

@Walavouchey How on earth were these derived? These do not look right at all.

I also generally agree with @smoogipoo that we should not be looking to 1:1 match everything until proven otherwise. This issue's scope seems more specifically about sliders in osu!-the-ruleset.

**Comment by Walavouchey** [comment]
> Is the issue that judgement results are different?

slider ticks were the only thing we seemed to agree should match stable during the meetings (as there were people complaining about it). the table above is to inform of any side effects from changing values

> Strong hit ... LargeBonus * 7
> Large drum roll hit ... LargeBonus * 3 + SmallBonus
> @Walavouchey How on earth were these derived? These do not look right at all.

i'm serious. strongs and large drum roll hits are just randomly multiplied elsewhere (also look at footnote 3)

https://github.com/ppy/osu/blob/00c87c782b7971ebbf9b289b43482c7e1b993bdf/osu.Game.Rulesets.Taiko/Scoring/TaikoScoreProcessor.cs#L36-L42

stable uses a similar conditional but since the values are way different, it's not even the whole story (that i haven't uncovered yet, but i'm probably dropping this for now since it's too complicated)

https://github.com/peppy/osu-stable-reference/blob/master/osu!/GameplayElements/Scoring/Processors/ScoreProcessorTaiko.cs#L61

**Comment by bdach** [comment]
> i'm serious. strongs and large drum roll hits are just randomly multiplied elsewhere (also look at footnote 3)

Ah right I forgot about this... It was to mostly match stable. I think it's a "leave it there" kind of thing.

I think we should pull this back to sliders specifically and decide on whether we want to be changing the point values for sliders, or doing whatever else wrt tails impacting combo or whatever. I'm not really sure I have a well formed opinion on that, probably would look to yield to someone more competent gameplay-wise (@ Bubbleman? dunno if there's an actual github handle I can use here)

**Comment by smoogipoo** [comment]
Moving this out of the project for the time being. We'll go with the current mechanics as they are and see how it is with more user feedback post-ranking.

**Comment by Zyfarok** [comment]
@smoogipoo this doesn't make sense since changing this post-ranking means a score-wipe which players absolutely don't want.
However, note that this topic is 100% tied with https://github.com/ppy/osu/discussions/25739 and thus this issue is redundant with the discussion happening there.

**Comment by bdach** [comment]
@Zyfarok your opposition [is](https://discord.com/channels/188630481301012481/188630652340404224/1184135883096592414) [well](https://discord.com/channels/188630481301012481/188630652340404224/1184149827630665849) [noted](https://discord.com/channels/188630481301012481/188630652340404224/1184150281722794045) at this point. there is no need to repeat the same talking point ad nauseam. please let us work.

**Comment by peppy** [comment]
This has largely been resolved now. Some may argue that "ticks should be worth more" but we've locked things in for now and further discussion will happen after we have more experience and feedback of the system as it stands.
