### ISSUE TITLE
Barrel Roll combined with Easy doesn't apply size change

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#23411]
### Type

Crash to desktop

### Bug description

This happens on all maps. All other 'fun' mods work correctly as far as I can tell

### Screenshots or videos

video: https://youtu.be/ebWkpiB5-n0

### Version

2023.419.0-lazer

### Logs

no logs

**Comment by bdach** [comment]
That's not what's happening there. What *is* happening there is that with Barrel Roll active, the *entire* playfield is scaled down, so that the entire playfield can be *visible* when it is rotating:

https://github.com/ppy/osu/blob/8c3b1faa01f7e3463d016cb27ff4687ef94c3844/osu.Game/Rulesets/Mods/ModBarrelRoll.cs#L48-L56

As such, the mod is working as intended.
