### ISSUE TITLE
Issues scaling skin elements with non-standard size

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#2358]
Using my personal osu skin ([LittleEndu/osuSkin](https://github.com/LittleEndu/osuSkin) or [.osk](https://drive.google.com/open?id=1MSEU7AiOjFIisJM74lDsxEx_hVgmrU1A)) as an example. Lazer seems to resize all skin elements to standard size even tho that shouldn't be a thing for elements that have their anchor in the center like all hitobject related elements have. 

For my skin, I have a slight shadow on approach circle and hitcircle overlay, their size is 256x256 instead of the standard 128x128 so they are sized down two times in lazer.  

Using [Re:TrymenT](https://osu.ppy.sh/beatmapsets/519521/#osu/1165773) as the example beatmap

This is how my skin looks in stable editor:
![](https://i.imgur.com/tEjQjMT.png)

This is how my skin looks in lazer editor (timing is a bit off as there's no scrolling options in lazer editor yet):
![](https://i.imgur.com/igU5pLT.png)

**Comment by Trigger-b0y** [comment]
Now is default size for circles 118x118(@1x) and 236x236(@2x).
Use this def sizes for correct display

**Comment by LittleEndu** [comment]
The issue here isn't that I couldn't get my skin to work in lazer, the issue is that my skin works in stable so I would expect it to also work in lazer...

Either that or there should be better conversion when importing a skin and not just plain scale down.

**Comment by peppy** [comment]
Some skins that didn't conform to sizing correctly *will* need manual updates. This is an intentional move to provide a more stringent skinning system. Each element in lazer can specify whether it allows users to exceed the given sizes. Gameplay elements (like approach circles) will not allow this.

**Comment by RockRoller01** [comment]
"This is an intentional move to provide a more stringent skinning system."
And that is exactly the opposite of what people are asking for. Everyone is hoping for a more relaxed system and not a shittier system. Its allready really annyoing and hard to archive certain things. And even if you limit stuff, we will find a way again to break your system, unless you limit EVERY file, which would make a terrible system.
If we can't use e.g. shadows on the HC anymore many skins just wont work. There is no reason in limiting HC and AC in size. If you think there is one please explain it.

**Comment by peppy** [comment]
Hitcircle textures already allow for a shadow area.

Reason for limiting: to provide a level playing field for ranked play. This is already enforced in many areas on osu-stable and will continue to become more stringently implemented in lazer. It will not be limiting and is not open for discussion until implementation, as it sparks redundant discussions such as the one we're having.

The issue in this thread is to do with a broken source skin or incorrect 2x handling. Not what you said.

**Comment by KarBoy2314PL** [comment]
[*cough* make skinning great again *cough*](https://osu.ppy.sh/community/forums/topics/797942)

**Comment by RockRoller01** [comment]
"to provide a level playing field for ranked play." I don't see how a bigger HC could give you any advantage over others, because the hitbox wouldn't be increased. It just limits us shadow, glow and compatability wise. And when 236 is the new size for HD there wouldn't be place for a glow. 
And my comment has to do with it, since its about new sizing (-> new system) and I'm talking about sizing.

**Comment by peppy** [comment]
Please reference the skin template. It contains element sizes for reference.

**Comment by jpsouzasilva** [comment]
As this has been given attention for now, I wanted to ask what's the purpose in mind for LegacySkin.cs.

https://github.com/ppy/osu/blob/master/osu.Game/Skinning/LegacySkin.cs

Will this be a way to use skins on gameplay in a "unconstrained" manner like it is now on stable?

Or does it have the name Legacy because the new skins will follow a different format?

---

I'd also like to take this chance to ask if there are some downsides to leave it as it is on stable, in terms of drawing efficiency, visual exploits or any other related concerning effects.

I brought this topic up on the osu! skinning server some days ago and the most compelling argument I've found is that skinning is "a thing" on osu. The same way gameplay is a source of entertainment, theming the game the way you want to look like is something people care about doing individually. I've spent dozens of hours customizing borders, shadows, shapes, and even animations, editing the assets and reloading the game continuously until it matched **exactly** what I wanted to look like.

Seeing as skinners have learned to get around the skinning system's limitations throughout the years and even got creative about doing it, going through all of this trouble of trial-and-error just to have a way to reflect their visual goals within the game... I'd think the idea now would be to give more avenues of visual expression, and not to impose any kind of extra conforming boundaries instead.

Please notice that I'm not implying that X or Y thing won't be doable in the new skinning system, because no one complaining here knows that yet. I'm interested in knowing why this is a needed change from a game design perspective, since it touches in one of the things people actively enjoy doing; there are communities on osu! specifically devoted to skinning, even the silly ones.

Thank you for listening.

**Comment by peppy** [comment]
legacy skin will cover all existing skins with minimal modifications. as you said, there will be a new more powerful and more organised skin format native to lazer going forward.

**Comment by Joehuu** [comment]
Hitcircle overlay has been fixed, only approach circle remains.

**Comment by peppy** [comment]
Closing for now as this should have been resolved for all remaining skin assets via #7078.
