### ISSUE TITLE
Changing a beatmap's background in the editor immediately saves

### ISSUE THREAD

**Issue by peppy** [ppy/osu#23669]
Another case of editor mutations leading to pollution of actual realm databased beatmaps. This one's especially bad because the background flow ensures the filename is always `bg.jpg`, so it will overwrite the previous file on save.

Needs further investigation as to whether the `Metadata` mutation is actually saving out somehow (unlikely) or whether this is just the `RealmFileStore` operations being run inline (with no ability to revert):

https://github.com/ppy/osu/blob/aaeb43fbb2f48ce1f364c9ffd267abddcdcb3898/osu.Game/Screens/Edit/Setup/ResourcesSection.cs#L87-L93

### Discussed in https://github.com/ppy/osu/discussions/23663

<div type='discussions-op-text'>

<sup>Originally posted by **Gabixel** May 25, 2023</sup>
I noticed this while checking if changing a beatmap background updates the status to `local` (which seems to work perfectly), but if I exit without saving the new background, the beatmap just loses the original one (and the status is still `ranked`). Not sure if it's the correct behaviour. I think I'm combining two issues here.
I'm also scared to test this with the audio track... (but maybe it has a different outcome)

https://github.com/ppy/osu/assets/43073074/bc74868c-4b5a-479d-882d-9744fbea1ed2
</div>

**Comment by Gabixel** [comment]
Looks like the editor's saving logic has been tweaked recently: dragging an image into the image field instantly applies the change, which prevents reproducing the process explained in the OP.

I'm actually a bit confused though, because there's no way to choose whether the dropped image should be applied to the current beatmap only, or to the whole mapset (it automatically does the latter, while you can choose if you're using the in-game file browser), and it's also odd that there's no way to have this as a "pending change" instead of saving it immediately.

So I'm not sure if this is 100% fixed, or if there's room for improvement (by bringing back a "discard" flow that might cause this problem to reappear).

**Comment by frenzibyte** [comment]
> Looks like the editor's saving logic has been tweaked recently: dragging an image into the image field instantly applies the change, which prevents reproducing the process explained in the OP.

Indeed, the issue can be closed now.

> I'm actually a bit confused though, because there's no way to choose whether the dropped image should be applied to the current beatmap only, or to the whole mapset (it automatically does the latter, while you can choose if you're using the in-game file browser), and it's also odd that there's no way to have this as a "pending change" instead of saving it immediately.

This is an overlooked method of changing the background. Should be in a separate issue thread though.
