### ISSUE TITLE
Scroll speed not being rounded when using non-English languages

### ISSUE THREAD

**Issue by RBQcat** [ppy/osu#23750]
### Type

Cosmetic

### Bug description

Occurs when adjusting Scroll speed in any non-English language

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/74862110/2c178171-700f-44c4-be51-a314bb35ea52)

### Version

2023.605

### Logs

N/A

**Comment by bdach** [comment]
It's because crowdin doesn't seem to support number formatting suffixes like this one:

https://github.com/ppy/osu/blob/25d0f0f3da506aa0af19edf58c8fe4222a3f6532/osu.Game/Localisation/RulesetSettingsStrings.cs#L85

`LocalisationAnalyser to-resx` outputs them just fine, so it seems that it is crowdin that's dropping them. That means that we probably cannot use inline number format specs.

**Comment by bdach** [comment]
Actually no, disregard the above, it seems *other* strings support this? kinda?

Take [this](https://github.com/ppy/osu-resources/blob/3e52067dccfdaf51acda17b905b207a7c3ba406d/osu.Game.Resources/Localisation/Editor.de.resx#L119) string, for instance. It specifies `{0:0}`, but in game *really* behaves like what it *originally* was prior to https://github.com/ppy/osu/pull/23247 which is `{0:0.0}`.

And in the case of the string above, [it didn't use to have a format spec next to it](https://github.com/ppy/osu/pull/23691/files#diff-8bde66a226c1275792b81927c37d45548e023ce7abe6e4f7f59ab3b66d73c024L85-R85).

**Comment by bdach** [comment]
I left 2 comments before attempting to explain why this happened, both terribly wrong.

The truth is that this is happening because the string was updated in https://github.com/ppy/osu/pull/23691/files#diff-8bde66a226c1275792b81927c37d45548e023ce7abe6e4f7f59ab3b66d73c024L85-R85 to have the format spec in the translation, and the translations just haven't been updated to match yet.

**Comment by peppy** [comment]
If we're using anything non-standard format string there's argument that it should be included in the localisations so it can be customised to match the target language. Probably fine to leave it there for the time being regardless.

Shall we update the crowdin strings and close this issue?

**Comment by bdach** [comment]
Sure, we can try that and see how it pans out in the future.
