### ISSUE TITLE
osu!mania has a strange score performance

### ISSUE THREAD

**Issue by Mabbs** [ppy/osu#23821]
### Type

Game behaviour

### Bug description

I updated the latest version of the osu! client and found that the same performance was much lower than before

### Screenshots or videos

<img width="1280" alt="截屏2023-06-09 00 08 52" src="https://github.com/ppy/osu/assets/17966333/238a190e-6eb8-432d-9241-b7edb41794dc">

### Version

2023.605.0

### Logs

[database.log](https://github.com/ppy/osu/files/11690920/database.log)
[input.log](https://github.com/ppy/osu/files/11690922/input.log)
[network.log](https://github.com/ppy/osu/files/11690923/network.log)
[performance.log](https://github.com/ppy/osu/files/11690924/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11690925/runtime.log)

**Comment by bdach** [comment]
This is because the implementation of score was changed last update to score V2. That will not change, and the resulting problem that creates is tracked as https://github.com/ppy/osu/issues/23782. However, last release also tweaked the combo/accuracy ratio for mania, which used to be 99:1, and was changed to 80:20 last release. That change has since been rolled back (https://github.com/ppy/osu/pull/23816) and next release we will be back to 99:1.

Closing as partially duplicate and partially resolved.
