### ISSUE TITLE
Skin editor change will revert and not save in gameplay if change some specific visual settings

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu#23915]
### Type

Game behaviour

### Bug description

1. Do some skin layout change in Skin Editor at Gameplay.
2. Change Beatmap skins or Beatamp colours in Visual Settings (Actually also work in settings layout which open by ctrl+O)
3. Change reverted.
4. Exit Gameplay and found change not saved.

Under normal circumstances, the skin will be saved when exiting player screen even didn't click save in Skin Editor.

### Screenshots or videos

https://github.com/ppy/osu/assets/34775378/295d08d8-2471-4975-b4bc-2b3df6f7056e

### Version

2023.614.1

### Logs

eh... no related log, just some `OsuScreenStack` log

```
2023-06-14 12:32:53 [verbose]: 📺 OsuScreenStack#527(depth:6) exit from ReplayPlayer#446
2023-06-14 12:32:53 [verbose]: 📺 OsuScreenStack#527(depth:6) resume to ReplayPlayerLoader#254
2023-06-14 12:32:53 [verbose]: 📺 OsuScreenStack#527(depth:5) exit from ReplayPlayerLoader#254
2023-06-14 12:32:53 [verbose]: 📺 OsuScreenStack#527(depth:5) resume to PlaySongSelect#317
```

**Comment by peppy** [comment]
This is due to the HUD getting reloaded when anything in the skin hierarchy changes. By toggling beatmap skin you're forcing a reload, which will wipe all changes.

This is similar to https://github.com/ppy/osu/issues/22561. A fix to both of them may be to disable skinnability of the HUD from beatmaps, but it seems that this is actually done by some ranked beatmaps (example: https://osu.ppy.sh/beatmapsets/1960602#osu/4063073) so that may not be a valid direction.

**Comment by bdach** [comment]
> The best UX, if we want to keep everything working as it is, may be to disable the toggle buttons whenever the local skin is in a dirty state. And also force the beatmap skin option off when opening the skin editor to ensure #22561 doesn't happen.

Tend to agree with this.
