### ISSUE TITLE
Gameplay mods are selected when clicking not releasing

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#2392]
Like mostly all of the game buttons are using the release action(you hold down and it triggers when you release on the same area).

**Comment by santerinogelainen** [comment]
Tried changing this to OnMouseUp (can't use OnClick since it doesn't trigger on right click). Because OnMouseUp triggers even if the mouse is not over the button when released we need to check if the mouse position is over the button. The problem is the ModButton/Drawable Contains method returns False even through the mouse position is over the button. The problem seems to be in ToLocalSpace method that Contains uses. ToLocalSpace method's return value is offset by a lot.

Here's my OnMouseUp function if anyone want's to continue investigating:
```C#
        protected override bool OnMouseUp(InputState state, MouseUpEventArgs args)
        {
            Debug.WriteLine(Contains(state.Mouse.Position)); // returns false when the mouse is on the button
            Debug.WriteLine(ToLocalSpace(state.Mouse.Position)); // offset by a lot

            switch (args.Button)
            {
                case MouseButton.Left:
                    SelectNext(1);
                    break;
                case MouseButton.Right:
                    SelectNext(-1);
                    break;
            }

            return true;
        }
```

**Comment by jorolf** [comment]
I think the xml-doc of `Contains` mentions that it requires screen space coordinates
