### ISSUE TITLE
Free adjustable playback speed in editor

### ISSUE THREAD

**Issue by AlFasGD** [ppy/osu#2393]
Seeing the new scroll for the playback speed in the replays, I think it's feasible to implement something similar in the editor as well. Considering that in osu!lazer, we've gotten rid of the 25% playback speed that used to exist in osu!stable, I think it would be usfeul to extend the currently supported speeds into a wider spectrum of values ranging between 50% and 100% (or even from 25% up to 100% if need be).

**Comment by Frontear** [comment]
Mind if I ask, how useful would such a feature really be?

**Comment by peppy** [comment]
It seems like we aren't going to get far without having people requesting 25% playback speed, so let's use this issue to track both variable selection and also finding a way to allow the playback to be as low as 25%.

Would anyone have qualms if we used a pitch shifting slow down (aka just adjust the frequency) rather than time shifting? This is something I could get behind because it has less of a detrimental effect on the audio sub-sample timing, which means it can more correctly be used for timing than the existing stable editor's method.

**Comment by peppy** [comment]
Based on there being no responses, I'm going to give that a try.
