### ISSUE TITLE
Notes and music desynchronized after playing for a while

### ISSUE THREAD

**Issue by Gustysh** [ppy/osu#23992]
### Type

Game behaviour

### Bug description

This problem has haunted me in the Laser version since the moment I started using a laptop.
After a certain time in the game, the notes move as if by an offset and appear clearly later than their original position on the map. Usually this is somewhere around 5-10ms, but in this case I left the game minimized for 2 hours, and the notes here are probably shifted by 1 or more seconds. The offset is set to 0, of course. When i restart the game everything is temporarily back to normal.

Specs:
Laptop (Windows 11 22H2 x64)
Monitor 144hz
Nvidia 3060rtx
Ryzen 5 5600H
RAM 16GB

Graphics Settings:
Fullscreen
Renderer: Automatic (Direct3D 11)
Limiter: 8x
Threading mode: Multithreaded
Hardware acceleration: ON

### Screenshots or videos

https://github.com/ppy/osu/assets/67452496/f21c93cb-b6b9-4431-bc72-35adfc0a5d5c

https://github.com/ppy/osu/assets/67452496/8cb56811-9290-466c-a8d7-bce3cad03bd9

### Version

2023.621.0-lazer

### Logs

[input.log](https://github.com/ppy/osu/files/11826478/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11826479/legacy-ipc.log)
[database.log](https://github.com/ppy/osu/files/11826482/database.log)
[network.log](https://github.com/ppy/osu/files/11826483/network.log)
[performance.log](https://github.com/ppy/osu/files/11826484/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11826486/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11826487/updater.log)

**Comment by peppy** [comment]
Probably https://github.com/ppy/osu-stable-issues/issues/306.

Basically we have no idea how this happens, but suspect it's heat, ambient temperature, or system clock drift related.

**Comment by peppy** [comment]
Sorry I didn't mean overheating. The issue we've seen in stable builds up over time, and may be due to room environment temperature affecting timing internals of your PC, or something equally weird. This may sound farfetched but we've been through everything in the stable thread and still come up with nothing.

Out of interest, have you played osu! stable in the past? If so, have you ever experienced anything similar?

**Comment by Gustysh** [comment]
Yeah, I have played a lot and sometimes still play the stable version of osu and I didn’t have such bugs on a laptop or on a PC. This bug for me personally exists only in the lazer version.

**Comment by peppy** [comment]
If you happen to have another audio device you can test with, that would be a good start to rule out audio driver issues. ie. if you have a USB headset or some kind of USB sound card / DAC device.

**Comment by Gustysh** [comment]
> If you happen to have another audio device you can test with, that would be a good start to rule out audio driver issues. ie. if you have a USB headset or some kind of USB sound card / DAC device.

Unfortunately I don't have an another audio device at the moment and I'll try it as soon as I can, however I did find one strange pattern in the choice of renderer.

If you choose Direct3D and leave Lazer minimized for a while (this is the most stable way to achieve this bug), then the notes will go before the music. If you choose OpenGL, then the notes will go later than the music.

This behavior is confusing, and it seems to me that it can halp to lead to some specific reason for this bug, because the renderer clearly affects its behavior in some way.

**Comment by peppy** [comment]
I'm hoping this was fixed via #24449. Could anyone in this thread please report back whether things are better now?

**Comment by yoyyoy** [comment]
I've had this issue happen to me and https://github.com/ppy/osu/pull/24449 initially fixed it for me, but this has recently resurfaced. I switched from plugging my headphones from into my monitor to into my motherboard. I did this because i recently heard about REAL.exe and wanted to take advantage of it, but the nvidia audio drivers don't support smaller buffer sizes than the default 10ms so REAL.exe does nothing when i connect my headphones to my monitor. as soon as i switched i noticed the desync and was reminded of the issues i faced before that clock fix.

when the game is out of sync, setting the audio output device from default, to my headphones fixes it temporarily. despite my headphones already being the default. setting the output to my monitor I was unable to get it to happen

as for fixes I tried, I've tested with and without using REAL.exe and it happens in both cases. i've tried updating my audio driver but it was already up to date. I tried what asus provides for my motherboard, some realtek driver, but that caused really high audio latency so i immediately went back to windows default driver. I noticed after i uninstalled the realtek driver, which required a restart, i had no issues for the rest of the day. but today it happened again. maybe putting my computer to sleep caused issues.

it may very well be a driver issue, but considering most people are probably using windows default driver I feel it's worthwhile to try and at least mitigate it. I've seen other users with similar behavior, like https://github.com/ppy/osu/issues/26237 or https://github.com/ppy/osu/issues/28595,  plus, i've never seen this behavior in stable so it must be something unique to lazer

**Comment by ChicagoTed7172** [comment]
I have a similar issue with Lazer only, and it seems to be exacerbated by Doubletime. I tried looking through the github for more relevant topics but this one seemed like the best place.
I regularly play with Doubletime at varying speeds, but playing at x2.00 always seemed to cause a more visible effect, quicker.
Today I have left my osu! open and minimized on the song select with x2.00 active, and when I return every so often, the delay I experience (Hit objects gradually drifting behind beatmap audio) is more and more obvious.

This is always remedied by a restart, but I am yet to leave my game open without Doubletime on for an extended period to determine if the problem persists.

[Clips showcasing the issue](https://www.youtube.com/watch?v=oTvFZxXopyk)
Clip 1 was after: Leaving my game minimized, on the song select, with x2.00 selected for about 15 or minutes.
Clip 2 was after: A further 15 or so minutes.

I can't personally say if I have this issue without Doubletime, as after leaving it for about 15 minutes I saw no discernable difference, but could be that I need to leave it running a lot longer.

[1735483834.auth.log](https://github.com/user-attachments/files/18270379/1735483834.auth.log)
[1735483834.nauth.log](https://github.com/user-attachments/files/18270380/1735483834.nauth.log)
[1735483834.runtime.log](https://github.com/user-attachments/files/18270381/1735483834.runtime.log)
[1735483834.network.log](https://github.com/user-attachments/files/18270382/1735483834.network.log)
[1735483834.performance.log](https://github.com/user-attachments/files/18270383/1735483834.performance.log)

First time github poster, so will shotgun upload all logs this session, for someone smarter than me to pick out what's relevant, if any of it is in the first place.
Thanks for all the hard work on lazer and osu! as a whole for all these years <3

**Comment by yoyyoy** [comment]
personally I fixed it by switching to linux, but that's not a readily available choice for everyone. unfortunately, I was only able to find a workaround, and as discussed in https://github.com/ppy/osu/discussions/31128 a workaround isn't desired. we need a true fix instead.
