### ISSUE TITLE
Sort by Date Ranked

### ISSUE THREAD

**Issue by ALegendsTale** [ppy/osu#2425]
While playing osu, I noticed there wasn't a sorting feature by the date the mapset was ranked. I love to play a mix of old and new maps and I think a feature like this would be heavily used. Many other players on the [forums](https://osu.ppy.sh/community/forums/topics/61864) seem to agree. Additionally, this looks like it's already in place in osu!direct.

Due to this, I decided to try and take a look at the code to find a way to implement this. It's my first time trying to contribute and I've added a few lines. When running visual tests, I noticed that there weren't any other online based info sorting filters in place yet. Is there a way I can test this without online features or maybe a way that I can access them?

I'd love some help so that I can learn how I can test it.
Thanks!

**Comment by peppy** [comment]
If this is already on the new web, then it does definitely need to be implemented in game.

Some tests are missing, which should be added where possible when working on the components missing tests. If you need specific help along the way, feel free to ask on discord.

**Comment by hburn7** [comment]
I have considered writing a PR for filtering and sorting beatmaps by date. I don't see this functionality implemented yet, so I wanted to clarify what the ideal functionality of this feature would be. I assume filtering by "year" would refer to year last updated. Sorting by date would use the beatmap's last updated date. That way ranked, unranked, loved, etc. maps are covered, instead of just ranked maps. If this is the way to go, I'll submit a PR after I get everything working.

As for filtering, I imagine `year<=2019`, `year=2010`, etc. would be appropriate, again using the beatmap's last updated date as the reference.

**Comment by peppy** [comment]
Last updated is not really correct. In some cases it may differ from the ranked date by years, in either direction. I'd say it should be used either as a fallback or as a separate search keyword if anything.

Keep in mind the requirements for this are not yet stored to realm, so that should be done as a first step. It should also be added to the sqlite lookup database if not already there. Finally, keep in mind that it won't apply to already imported beatmaps until we have a process which can fetch data for existing beatmaps, but that can come later.

**Comment by hburn7** [comment]
Great to know. Admittedly, I am unfamiliar with realm and the inner-workings of the lookup database (this would be my first contribution). I'll have to learn some more and revisit, or let a more experienced contributor take this one. Thank you for sharing what steps need to be taken in order for this to be achieved.
