### ISSUE TITLE
Song setup screen implementation in the editor

### ISSUE THREAD

**Issue by AlFasGD** [ppy/osu#2434]
I would like to get involved in at least adding the UI for the setup screen and implement a feature or two, but I am not sure if I should add all the features osu!stable has one by one, or if some are not planned to be added at all.

So I came here to ask what the plans for the design of this screen are and what's going to be removed.

**Comment by smoogipoo** [comment]
Just pasting these here for reference:

![image](https://user-images.githubusercontent.com/1329837/42362613-1b9ba3ec-812f-11e8-9a65-3d60b5a87eb3.png)

![image](https://user-images.githubusercontent.com/1329837/42362632-3042c92e-812f-11e8-8ee8-85ad31f83745.png)

![image](https://user-images.githubusercontent.com/1329837/42362636-35b1e52a-812f-11e8-8b55-8b693697104d.png)

![image](https://user-images.githubusercontent.com/1329837/42362645-3ba29dda-812f-11e8-9cd3-77c8b3bae66b.png)

![image](https://user-images.githubusercontent.com/1329837/42362656-4469bd68-812f-11e8-8f5b-3371d08779be.png)

![image](https://user-images.githubusercontent.com/1329837/42362662-49f2bb9a-812f-11e8-9657-2e7fc8f4ec6d.png)

**Comment by EVAST9919** [comment]
Looks really cool
Damn, there's a big progress here

**Comment by mcendu** [comment]
Shoudn't we put it into #6686?

**Comment by bdach** [comment]
Are the designs above still usable? Not sure whether I'd want to commit to implementing the entire screen but I may have a go at some pieces of it at least.

**Comment by peppy** [comment]
They are, yes! And there's some PRs which have partial implementations of them (they actually worked quite well but had some code quality shortcomings, so I'll leave it up to you to determine whether it's worth salvaging. i did so for the LabelledSliderBar i think, and it may have been more effort than it was worth.)

**Comment by bdach** [comment]
How does that relate to the current setup screen look? There are a few details that are different (mainly the colour scheme - blueish on designs, greenish in game, and the placement of the beatmap background thing), and I'm not sure whether that was a temporary arrangement, or an intentional change.

**Comment by peppy** [comment]
The stuff I added was get-it-done-quick, so was likely copied from another existing UI area. I don't think it was an intentional change. Was hoping to double-check but as usual I can't find the relevant designs. @arflyte care to check on and link the latest figma versions of the above?

**Comment by arflyte** [comment]
I was actually working on the osu!editor and theme editor last week; mostly to keep the design up to date. Probably can get everything done by this week. I'll put the link here once it's done.

**Comment by bdach** [comment]
Over the last weeks/months I have slowly but steadily moved most pieces from stable's setup screen to lazer. Aside from some quality-of-life/polish stuff that isn't necessarily required at this stage (like slider bar shift-to-adjust-precisely, or some helper text about the ranking criteria) the one major remaining omission is the audio section.

The reason I haven't touched that yet is because stable's audio section seems... a little strange? Unless the map has no sample points, the only available setting there concerns adjusting sample playback rate to gameplay rate. And given that sample stuff has just received a major change (by which I mean associating sample points with hitobjects rather than having explicit sample points), I do wonder if that tab isn't obsolete at this point and if all that was needed to achieve parity with stable has been achieved if that is the case...

**Comment by peppy** [comment]
Much of that tab's content should be moved to within the audio sample popover (ie. what you'll get when you go to change a bank/sample for one or more hitobjects). Safe to not implement such settings, they date way back before sample changing was even possible via control points.

**Comment by frenzibyte** [comment]
I believe then that the song setup screen has been fully migrated to osu!lazer now, and this issue can be closed now? unless we're still tracking the remaining "adjust sample frequency to gameplay rate" setting.

**Comment by peppy** [comment]
Should probably be added under design if we're going for parity.

**Comment by peppy** [comment]
I think it's safe to close this tracking issue now? We can probably track any remaining considerations which have been overlooked as they are reported by users.
