### ISSUE TITLE
Taiko Classic mod has reduced note sizes when playing on mobile

### ISSUE THREAD

**Issue by OpenSauce04** [ppy/osu#24363]
### Type

Cosmetic

### Bug description

The size of the taiko hits when using the classic mod on mobile are much smaller than without the classic mod. Despite the smaller note size, the on-screen spacing between the notes is very similar, resulting in the perceived speed of the notes being increased. This results in notes being harder to hit when playing using classic mod.

### Screenshots or videos

![Screenshot_20230725_160656](https://github.com/ppy/osu/assets/48618519/2b711200-1ac6-4191-8c94-f380bdfaf30b)
![Screenshot_20230725_160753](https://github.com/ppy/osu/assets/48618519/4da51db5-a9a3-4e98-961d-c9d5c21dc2b7)

### Version

2023.717.0

### Logs

N/A

**Comment by bdach** [comment]
This is intended and a result of a grueling community-driven process of trying to get taiko to follow stable's wonky screen aspect ratio handling logic (rather than use a consistent 16:9 scale everywhere, which is what non-classic mod does), while retaining constant scroll speed irrespective of aspect ratio.

See: https://github.com/ppy/osu/pull/17225, https://github.com/ppy/osu/pull/22325, https://github.com/ppy/osu/pull/23325.
