### ISSUE TITLE
Weird behavior when using play/pause shortcuts when loading map

### ISSUE THREAD

**Issue by Sukuratchi** [ppy/osu#24385]
### Type

Game behaviour

### Bug description

When pressing play/pause while a map is loading, hit objects may appear sooner vs when you normally load a map
Sometimes a completely different song may play instead

### Screenshots or videos

Normal behavior

https://github.com/ppy/osu/assets/66184829/94597156-040f-457a-812a-39ee99912526

Second song playing over the beatmaps song

https://github.com/ppy/osu/assets/66184829/352022aa-1cab-4b87-b28a-35319125c02a

Hit objects appear too soon

https://github.com/ppy/osu/assets/66184829/06a79258-be8d-413f-af02-5fe99038a3aa

### Version

2023.717.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/12188645/database.log)
[input.log](https://github.com/ppy/osu/files/12188646/input.log)
[network.log](https://github.com/ppy/osu/files/12188647/network.log)
[performance.log](https://github.com/ppy/osu/files/12188648/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12188649/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12188650/updater.log)

**Comment by peppy** [comment]
Step 1: understand why this is happening
Step 2: adjust https://github.com/ppy/osu/pull/24361 to apply from loader screens (i had this in a previous iteration)?

**Comment by alexpado** [comment]
Also, spamming play/pause during the gameplay make the sound shutter. Idk why this is a thing but yeah

**Comment by alexpado** [comment]
Yeah I just verified the linked PR and can confirm this, my bad

**Comment by bdach** [comment]
> Second song playing over the beatmaps song

I can't reproduce that one. @Sukuratchi can you perhaps state two things for me there?

- Which key were you pressing? Was it <kbd>F3</kbd>, or was it a multimedia "play" key that is on some laptops / keyboards?
- Can you identify the other track that was playing on that video, and are you positive that it is a beatmap you have imported locally?

The goal of both questions is to make sure this isn't a separate thing, like you having a media player open in the background that received a "media play" hotkey at the same time as osu! did (https://github.com/ppy/osu/discussions/24395)

> Hit objects appear too soon

This one I can reproduce. It's basically because of a timing hole in how the filtering of `GlobalAction.MusicPlay` is currently done. `MusicKeyBindingHandler` relies on `LocalUserPlaying.Value` to filter out the presses:

https://github.com/ppy/osu/blob/55cb400674c23656bc6cde9345c2871002380bd4/osu.Game/Overlays/Music/MusicKeyBindingHandler.cs#L43-L45

Here's how `LocalUserPlaying` gets updated:

https://github.com/ppy/osu/blob/55cb400674c23656bc6cde9345c2871002380bd4/osu.Game/Screens/Play/Player.cs#L478-L483

Here's what happens in the fail case:

```
[runtime] 2023-07-29 20:03:32 [verbose]: gameplay state: HasReplayLoaded=False IsPaused=False IsBreakTime=True HasFailed=False
[runtime] 2023-07-29 20:03:33 [debug]: Pressed (MusicPlay) handled by MusicKeyBindingHandler.
[runtime] 2023-07-29 20:03:33 [debug]: KeyDownEvent(F3, False) handled by GlobalActionContainer.
[runtime] 2023-07-29 20:03:33 [verbose]: gameplay state: HasReplayLoaded=False IsPaused=False IsBreakTime=False HasFailed=False
```

`IsBreakTime` initially assumes it's inside a break before its first update. Therefore, if you manage to hit the timing window between the load of `Player` and the first update of the break tracker, you get to resume playback _after_ `GameplayClockContainer.Reset()` and ruin everything.

I believe that https://github.com/ppy/osu/pull/24361 fixes this with no further adjustments necessary, since `AllowGlobalTrackControl` there is applied at the point of `OnEntering()` which is going to be before `StartGameplay()` / `GameplayClockContainer.Reset()`. But I wouldn't be necessarily opposed to blocking global track control on load screens as well.

**Comment by Sukuratchi** [comment]
> The goal of both questions is to make sure this isn't a separate thing, like you having a media player open in the background that received a "media play" hotkey at the same time as osu! did (https://github.com/ppy/osu/discussions/24395)

My apologies you're right. I had a github tab open of an earlier issue that I made that got solved. Didn't think that the media keys would play it!
