### ISSUE TITLE
Keys are falling through texboxes

### ISSUE THREAD

**Issue by tux1230** [ppy/osu#2447]
yes

**Comment by LittleEndu** [comment]
![No it does not](https://i.imgur.com/Cjtb5VJ.gif)

**Comment by escolasticokid** [comment]
Could this possibly be that bug where sometimes, while typing in a chat or any dialogue box, a key will open up a menu behind the chat? I'm not sure what the cause is, but I just got the same thing to happen, without pressing "d" specifically.

**Comment by Frontear** [comment]
I have had this bug occur before, however it really isn't reproducible. It happens infrequently. May just be race-conditions between textbox focus and global keybinds.

**Comment by peppy** [comment]
You can reproduce this by pressing two keys perfectly simultaneously.

**Comment by smoogipoo** [comment]
Looked into this a bit, it's because `OpenTKKeyboardHandler` binds to `KeyDown` while `GameWindowTextInput` binds to `KeyPress`.

`KeyDown` is called before `KeyPress`.

So all that's required is for the update thread to luckily pull a new input state from the handler, and propagate that input down, prior to `KeyPress` being called.

**Comment by peppy** [comment]
Seems to have regressed.
