### ISSUE TITLE
Kiai stars in the osu!classic skin are not working properly

### ISSUE THREAD

**Issue by Tenkotataii** [ppy/osu#24503]
### Type

Cosmetic

### Bug description

When kiai starts and you hold on sliders, the kiai stars appear. Somehow, their behavior is strange.

### Screenshots or videos

https://github.com/ppy/osu/assets/100620548/13271ab9-0866-4b0c-8814-c1d4f69dc24e

### Version

20230811

### Logs

[performance.log](https://github.com/ppy/osu/files/12324478/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12324479/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12324480/updater.log)
[database.log](https://github.com/ppy/osu/files/12324481/database.log)
[input.log](https://github.com/ppy/osu/files/12324482/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12324483/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12324484/network.log)

**Comment by bdach** [comment]
Regressed in #24208, unsurprisingly. Directly offending line seems to be

https://github.com/ppy/osu/blob/5e2a0bd73302f2f6be74bb9792d0e067f1c092ac/osu.Game/Graphics/ParticleSpewer.cs#L60

which then combined with

https://github.com/ppy/osu/blob/5e2a0bd73302f2f6be74bb9792d0e067f1c092ac/osu.Game/Graphics/ParticleSpewer.cs#L39
https://github.com/ppy/osu/blob/5e2a0bd73302f2f6be74bb9792d0e067f1c092ac/osu.Game/Graphics/ParticleSpewer.cs#L34

prevents the particles from finishing falling. @peppy do you recall what that null assignment was fixing? Because when I try removing it I can't find any immediate breakage, and blame isn't telling me a lot (https://github.com/ppy/osu/commit/ccbb30cdda8370ad626b30a56d1d9c7f169d03ec).
