### ISSUE TITLE
Remove slider head movement entirely

### ISSUE THREAD

**Issue by bdach** [ppy/osu#24639]
It's going away.

The main sticking point is deciding what to do with slider snaking (see discussion thread below). Not sure we have a consensus on that yet.

### Discussed in https://github.com/ppy/osu/discussions/23320

<div type='discussions-op-text'>

<sup>Originally posted by **tovc** April 26, 2023</sup>
osu!lazer changes slider heads such that they can be clicked while moving. While this may be 'proper' functionality, it cuts into the back end of the hit window for slider heads. On slow sliders, this is mostly ( but not entirely ) a non issue. On very fast sliders, such as those found in higher difficulty 'tech' maps, this can result in the back end of a slider head's hit window being nearly entirely cut off. This issue parallels the infamous issue with osu!stable's short sliders, which players usually played by deliberately hitting early. There was solace in that you wouldn't lose acc by playing them that way. In this case, losing acc is the only practical way to play such patterns.

![image](https://user-images.githubusercontent.com/49025619/234688035-f70b38e7-7ee7-4bc4-9bfb-d9bd5ed95ff1.png)
the hit window of a slider head at OD8 should be ±119.5ms. In this example, the hit window is effectively -119.5ms to +32ms, as the slider head has entirely left the area where the head was. Not only does this result in a hit window nearly 40% smaller than that is intended, it also results in a hugely asymmetrical hit window.

the now infamous fast sliders in [t+pazolite - Oshama Scramble ! (IOException Edit) [Special] mapped by IOException](https://osu.ppy.sh/beatmapsets/1376308#osu/2844649) are an example of a pattern that is largely impractical to play by hitting on time. Even if you want to cry 'skill issue', they can still result in a miss for something that _feels_ like it should have at least been a 100.

I am aware that the classic mod's 'no slider head movement' functionality fixes this, but I believe that it should be default functionality, not that hidden away in a pile of mods that many players won't even touch.</div>

**Comment by Zyfarok** [comment]
For the visual aspects, the main take-away from https://github.com/ppy/osu/discussions/23320 is:
If the head is hit late, the part of the track that is "already snaked out" should remain partially visible until the head is hit, and fade-away along with the slider-head as soon as the head is hit.

Now, the question where no consensus was made was whether the opacity of this "already snaked out" track should be a constant (like 30% opacity) or progressively fading out (from 100% at 0ms to 0% at the end of the hit-window ?) or maybe even something in the middle (progressive from 60% to 20% ? Or using a non-linear progression curve like `1-x^2`) or anything else (Non-uniform opacity across the track ? Slider-head catching up with the slider-ball once hit ?).

It would be good if a test scene is implemented with parameters, to allow to get feedback on this. Otherwise alternatively, we could go with a simple solution first and come back to evaluate the possibilities later.

**Comment by bdach** [comment]
@peppy has requested to take point on the visual aspects of this, hence the assignment. Don't think further discussion is necessary or productive at this point.
