### ISSUE TITLE
Slider length does not get recalculated while adding new anchor in editor

### ISSUE THREAD

**Issue by minetoblend** [ppy/osu#24647]
### Type

Game behaviour

### Bug description

When adding a new anchor to a slider in the editor, the slider length will get updated for the anchor's initial position, but won't update while moving the anchor around afterwards. Only after releasing the left mouse button and then moving it again the slider length gets recalculated.

### Screenshots or videos

https://github.com/ppy/osu/assets/8039761/2edc136e-40af-433a-9d75-e3fb44af7b3f

### Version

2023.815.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/12424028/network.log)
[performance.log](https://github.com/ppy/osu/files/12424029/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12424030/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12424031/updater.log)
[database.log](https://github.com/ppy/osu/files/12424032/database.log)
[input.log](https://github.com/ppy/osu/files/12424033/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12424034/legacy-ipc.log)

**Comment by RatinFX** [comment]
It seems like the newly added `PathControlPointPiece` in [`SliderSelectionBlueprint.cs`](https://github.com/ppy/osu/blob/3ab083b696906a03a6c6cd575ab81b8fe5541c39/osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderSelectionBlueprint.cs#L180) always has `IsDragged == false` when you first move it around, which likely results in none the drag handlers being called in [`PathControlPointVisualiser.cs`](https://github.com/ppy/osu/blob/21bf288277e08044e88bdc33ce53a779b293c617/osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/PathControlPointVisualiser.cs#L270)

Though it looks like a relatively quick fix, I'm unsure how to do it properly due to my current lack of framework insight
