### ISSUE TITLE
Fullscreen forces a lower resolution than the one I have

### ISSUE THREAD

**Issue by xRasea** [ppy/osu#2477]
A couple months ago I had an Nvidia GTS 450 and I was using an overclocked monitor running at 1440x900@75hz. My current GPU is an AMD Radeon 560 with the same PC and monitor I had before but without overclocking it (1600x900@60hz) and after updating osu!lazer I can't get it to run at 1600x900 with fullscreen on.
![osu_2018-05-01_14-51-18](https://user-images.githubusercontent.com/35492066/39473425-22d991fa-4d4f-11e8-88af-5ec1b6ff3cc7.png)

Borderless Window gets detected properly
![osu_2018-05-01_14-52-13](https://user-images.githubusercontent.com/35492066/39473458-4601cf1c-4d4f-11e8-909e-460b86f358ce.png)

tried changing the framework.ini, no luck there either.

Edit: after changing the values for WidthFullscreen and HeightFullscreen they reset back.

**Comment by FreezyLemon** [comment]
From DesktopGameWindow.cs:
```csharp
case Configuration.WindowMode.Fullscreen:
    DisplayResolution newResolution = DisplayDevice.Default.SelectResolution(widthFullscreen, heightFullscreen, DisplayDevice.Default.BitsPerPixel, DisplayDevice.Default.RefreshRate);
    DisplayDevice.Default.ChangeResolution(newResolution);
```

It's a bit bare bones at the moment. The problem in this case seems to be that the "DisplayDevice.Default.RefreshRate" is 75 (I'd assume, since you set it to that before).
This means that it now tries to select 1600x900@75Hz (which is not supported), and falls back to the current resolution.

This probably doesn't really have to be fixed on its own, as the fullscreen "handling" is a bit bare bones and will be changed later. But this shows that maybe the refresh rate should be added as an option too.

**Comment by xRasea** [comment]
Neat, at least it's not something very obscure. 

I was just doing a play session in lazer to see if I could report something important and I'm still playing a little bit, I guess issue reporting is useful. Anything that I should know if I keep threading issues?

**Comment by xRasea** [comment]
Forcing osu to be closed or osu not closing properly will cause the window resolution of the PC to stay like that until you change it manually. Seemed relevant to add to the issue.

**Comment by peppy** [comment]
This may be resolved by https://github.com/ppy/osu-framework/pull/1652
