### ISSUE TITLE
Swells in osu!taiko are cheeseable by binding don and kat to same key

### ISSUE THREAD

**Issue by peppy** [ppy/osu#24780]
Likely needs to be fixed.

### Discussed in https://github.com/ppy/osu/discussions/24763

<div type='discussions-op-text'>

<sup>Originally posted by **Non-Binary-Programmer** September  9, 2023</sup>
If one key is bound to both a rim hit and a center hit, then hitting that key will always advance a spinner by two keypresses. The most practical way to do this without external programs would be to bind the built-in second input for the left side center and rim inputs to the same key, and use the remaining 4 inputs regularly. This might be problematic, but doesn't give an advantage over someone who can properly alternate dkdk with both hands. However, by using external programs, or by sacrificing your regular inputs for the right side center and rim, you can hit all four with one key, allowing you to advance the spinner by 4 hits with one keypress, and generating a major advantage.

Is this intentional?</div>

**Comment by bdach** [comment]
I looked at what stable does to curtail this, and as far as I can tell, it:

- Disallows being able to bind multiple keys to same binding
- Due to the nature of how stable appears to handle input (`InputManager` setting input flags are updated once per game update loop, and then read once per frame by gameplay components), you can't trigger more than one swell tick per frame
- There's also... this code:

```csharp
            // punish if less then 30 ms has passed since the last invalid button
            // ignore if we are in relaxmode
            if (((AudioEngine.Time - lastInvalidButtonTime) >= 30 || Player.currentScore?.Processor != null) && !Player.Relaxing)
            {
                // Only increase if you alternate.
                // We start with lastButton=0 so the user can choose
                // the first note to begin to alternate with.
                if (hitRed)
                {
                    if (lastButton != red_Button)
                    {
                        increase = true;
                        lastButton = red_Button;
                    }
                    else
                    {
                        if (Player.currentScore?.Processor == null)
                            lastInvalidButtonTime = AudioEngine.Time;
                        return IncreaseScoreType.Ignore;
                    }
                }
                else if (hitBlue)
                {
                    if (lastButton != blue_Button)
                    {
                        increase = true;
                        lastButton = blue_Button;
                    }
                    else
                    {
                        if (Player.currentScore?.Processor == null)
                            lastInvalidButtonTime = AudioEngine.Time;
                        return IncreaseScoreType.Ignore;
                    }
                }

            }
```

(src: https://github.com/peppy/osu-stable-reference/blob/3ea48705eb67172c430371dcfc8a16a002ed0d3d/osu!/GameplayElements/HitObjects/Taiko/SpinnerTaiko.cs#L206-L242)

It appears to be anti-cheese protecting against spamming keys too much, wherein repeated presses of an invalid key closer than 30ms cause input to be blocked to the swell altogether - but the weirdest part about it are the `Processor == null` checks, which in stable basically boil down to "this is only enabled when score V2 is off". So while the rest is rather obvious, I'm not entirely sure what to do about _that_ part...
