### ISSUE TITLE
Slider shape is different on stable vs lazer

### ISSUE THREAD

**Issue by peppy** [ppy/osu#24841]
Notice the slider path extends slightly about the head circle.

| lazer | stable |
| :---: | :---: |
| ![image](https://github.com/ppy/osu/assets/191335/efcfe3ba-3185-4b4c-81b2-315bf8cd96c4) | ![image](https://github.com/ppy/osu/assets/191335/a245e691-b607-45ca-850d-f22bd149e7f6) |

https://osu.ppy.sh/beatmapsets/714359#osu/1509693
01:09:439 (1) 

Transferred from report on twitter: https://twitter.com/windr727/status/1703205933688533359

**Comment by windrosu** [comment]
If it helps, I made a recording of me moving this anchor to show the difference in behavior

https://github.com/ppy/osu/assets/145377511/f24eb157-f018-417f-8ccd-56165cd98b83

It seems like the curve change in Lazer is more smooth than it is in Stable

**Comment by Magnus-Cosmos** [comment]
The slider paths are the same (if you watch Auto on Stable slowed down, the slider ball/cursor goes upwards for a split second):
![osu-stable_slider](https://github.com/ppy/osu/assets/39173355/b2317fde-5750-4765-b6f4-db37bc063738)
The difference is that Stable renders the slider body differently, it "merges" the paths when the distance between them is 6px or less. In this case, the "backwards" paths are completely gone since their max distance from the starting position is less than 3px.

**Comment by bdach** [comment]
If that's the case I'd argue that we probably could leave this be since lazer is arguably more correct?

**Comment by Magnus-Cosmos** [comment]
I'd say so too, majority of maps aren't affected by this and gameplay wise there shouldn't be any difference.

**Comment by peppy** [comment]
Going to close this one as "working as intended" based on the above conversation.

**Comment by smoogipoo** [comment]
This was fixed for Catmull sliders here: https://github.com/ppy/osu/pull/27734, and I believe there was a reason I didn't apply the fix universally. We may want to revisit this in the future.
