### ISSUE TITLE
Reverse arrows fade instead of disappearing with hidden

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#24902]
### Type

Cosmetic

### Bug description

Reverse arrow fades out instead of instantly disapperaing

### Screenshots or videos

https://github.com/ppy/osu/assets/53081750/92660e50-5e87-4390-8324-c2e0f7741085

### Version

2023.924.0-lazer

### Logs

/

**Comment by bdach** [comment]
[Relevant code from stable:](https://github.com/peppy/osu-stable-reference/blob/1531237b63392e82c003c712faa028406073aa8f/osu!/GameplayElements/HitObjects/Osu/HitCircleSliderEnd.cs#L118-L134)

```
        internal override void Disarm()
        {
            bool hidden = ModManager.CheckActive(hitObjectManager.ActiveMods, Mods.Hidden);
            if (hidden) return;


            base.Disarm();


            for (int i = 0; i < SpriteCollection.Count; i++)
            {
                pSprite p = SpriteCollection[i];
                if (p.Clock == Clocks.Game)
                    continue;


                p.Transformations.RemoveAll(t => t.TagNumeric == ARMED);
                p.Transformations.Add(new Transformation(TransformationType.Fade, 1, 0, StartTime, StartTime) { TagNumeric = ARMED });
            }
        }
```

In particular `SpriteCollectionText` contains `SpriteHitCircleText` [which is the arrow](https://github.com/peppy/osu-stable-reference/blob/1531237b63392e82c003c712faa028406073aa8f/osu!/GameplayElements/HitObjects/Osu/HitCircleSliderEnd.cs#L34-L37).

@peppy you're probably the best person to ask this from an UX/aesthetics standpoint - do we apply this unconditionally? classic mod only? not at all?

**Comment by peppy** [comment]
That code looks like the intention is to always fade immediately. Have you figured why there's a special case for hidden there?

**Comment by bdach** [comment]
Ok I missed the early-return _and_ also forgot that `Disarm()` doesn't do what I keep wrongly thinking it does (it's the equivalent of `ArmedState.Idle()`).

`Arm()` has this:

```csharp
        internal override void Arm(bool isHit)
        {
            bool hidden = ModManager.CheckActive(hitObjectManager.ActiveMods, Mods.Hidden);
            if (!isHit || hidden || (GameBase.Mode == OsuModes.Edit && !ConfigManager.sEditorHitAnimations))
                return;


            foreach (pSprite p in SpriteCollection)
            {
                if (p == SpriteSelectionCircle)
                    continue;


                p.Transformations.RemoveAll(t => t.TagNumeric == ARMED);
                p.Transformations.Add(new Transformation(TransformationType.Fade, 1, 0, StartTime, StartTime + HitObjectManager.FadeOut) { TagNumeric = ARMED });
                p.Transformations.Add(new Transformation(TransformationType.Scale, 1.0F, 1.4F, StartTime, (int)(StartTime + HitObjectManager.FadeOut), EasingTypes.Out) { TagNumeric = ARMED });
            }
        }
```

which... also kinda doesn't look like the relevant code because `hidden` early-returns here too, but the rest looks _somewhat_ related because the non-early-return branch is adding fades/scales. Probably gonna need to debug this over because from source alone I can't see what's going on here.

**Comment by bdach** [comment]
After debugging stable, I can confirm that the early-return in `Arm()` shown above is responsible for the instant fade. The reason why that is the case is that the instant fade-out is otherwise applied via `HitCircleSliderEnd : HitCircleOsu` inheritance:

- https://github.com/peppy/osu-stable-reference/blob/3ea48705eb67172c430371dcfc8a16a002ed0d3d/osu!/GameplayElements/HitObjects/Osu/HitCircleOsu.cs#L147
- https://github.com/peppy/osu-stable-reference/blob/3ea48705eb67172c430371dcfc8a16a002ed0d3d/osu!/GameplayElements/HitObjects/Osu/HitCircleSliderEnd.cs#L131-L132

and then, by the time `Arm()` fires on completion of the repeat, the early-return prevents the fade from overwriting that disarm 0-length transform with the one that has actual duration.

I guess the question at this point would be - how do we want to apply this if at all?

**Comment by peppy** [comment]
I think we do want it to not fade (ie. hidden should match the non-hidden instant-fade display). The fade looks very weird.
