### ISSUE TITLE
Investigate elements that are possibly animatable in lazer (but shouldn't be)

### ISSUE THREAD

**Issue by bdach** [ppy/osu#25011]
Came out of https://github.com/ppy/osu/issues/24973, [and the relevant discord discussion](https://discord.com/channels/188630481301012481/188630652340404224/1159246285040259072).

On checking, we seem to be using `.GetAnimation()` on some elements where we should probably not be, namely:

- `hitcircleoverlay` / `sliderstartcircleoverlay` / `sliderendcircleoverlay` (100% wrong, was patched in stable: https://github.com/ppy/osu-stable-issues/issues/950 - it can even be seen animating in test scenes)

  https://github.com/ppy/osu/blob/66824ce8caa75db4ce44f55d3ccebd39457c5dec/osu.Game.Rulesets.Osu/Skinning/Legacy/LegacyMainCirclePiece.cs#L79-L83
- `reversearrow` (needs to be cross-checked against stable)
  https://github.com/ppy/osu/blob/66824ce8caa75db4ce44f55d3ccebd39457c5dec/osu.Game.Rulesets.Osu/Skinning/Legacy/LegacyReverseArrow.cs#L42-L46
- `taikohitcircle` / `taikobigcircle` (needs to be cross-checked against stable; the `overlay` variants are 100% fine to be animatable, but the others - probably not so much)
  https://github.com/ppy/osu/blob/66824ce8caa75db4ce44f55d3ccebd39457c5dec/osu.Game.Rulesets.Taiko/Skinning/Legacy/LegacyCirclePiece.cs#L50-L63

Could probably be accompanied by a full sweep of `.GetAnimation()` usages across rulesets to ensure no funny business as a bonus.

**Comment by peppy** [comment]
I'm not too sure adding animation support for elements which don't already have it is a huge deal, as long as the dimensions are correctly defined.

As in, I'm not sure I see it as a priority to fix this, unless a specific reason is given. The only potential issue is that people start using this and then ask for it to be added to stable, or that we need to remove it due to some compatibility issues in the future.

But if it's low effort then I guess we can match things up.
