### ISSUE TITLE
User can get stuck in Playing state in Multiplayer when clicking import notification at end of beatmap

### ISSUE THREAD

**Issue by breaddevv** [ppy/osu#25060]
### Type

Game behaviour

### Bug description

When importing from previous version, clicking an imported notification (Imported Scores specifically, unsure whether this persists through the other ones), at the end of a beatmap appears to exit the user out into the lobby but continues to leave the player in the 'Playing' state until the user exits the lobby as a whole, preventing them from doing anything other than leave.

Repro steps:
- Import scores from previous version
- Don't interact with 'Imported x scores' notification 
- Start a multiplayer room
- Add beatmap (I found this easiest to reproduce on https://osu.ppy.sh/beatmapsets/8023#osu/33502)
- Wait until beatmap ends and loading begins
- Open notifications and click the 'Imported x scores' notification
- Cancel out of warning

### Screenshots or videos

https://github.com/ppy/osu/assets/94323077/a25243d6-b65a-4938-9056-4a665863009a

### Version

2023.1008.1

### Logs

[database.log](https://github.com/ppy/osu/files/12841852/database.log)
[network.log](https://github.com/ppy/osu/files/12841853/network.log)
[performance.log](https://github.com/ppy/osu/files/12841854/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12841855/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12841856/updater.log)

**Comment by frenzibyte** [comment]
This has been indirectly resolved by https://github.com/ppy/osu/pull/25097. 

To briefly explain what's going on: the client changes the user state to `FinishedPlay` when the score is being finalised for the results screen, which happens after the 1000ms completion delay. Before the PR linked above, when the user exits during the delay period, `PrepareScoreForResultsAsync` is not called, and the checks in `Multiplayer` cannot choose to abort gameplay instead because the gameplay state is set to "passed".

But with the above PR, `PrepareScoreForResultsAsync` is called when exiting while gameplay state is "passed", therefore the client correctly changes state to `FinishedPlay` in the OP's scenario.

Closing as resolved.
