### ISSUE TITLE
Fast distorted audio sometimes

### ISSUE THREAD

**Issue by taep96** [ppy/osu#25156]
### Type

Game behaviour

### Bug description

Sometimes when opening the game audio sounds weird, a restart (of the game) fixes it. Maybe it's related to the clocks update that was mentioned on the lazer updates video.

### Screenshots or videos

https://github.com/ppy/osu/assets/64481039/d1540bd2-fbda-484f-be67-0ba7f1ad2c23

### Version

2023.1008.1 (could be earlier)

### Logs

[database.log](https://github.com/ppy/osu/files/12927866/database.log)
[input.log](https://github.com/ppy/osu/files/12927867/input.log)
[network.log](https://github.com/ppy/osu/files/12927868/network.log)
[performance.log](https://github.com/ppy/osu/files/12927869/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/12927870/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/12927871/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/12927872/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/12927873/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/12927874/runtime.log)

**Comment by bdach** [comment]
> Maybe it's related to the clocks update

No it's probably related to your linux setup. Let me guess, pipewire?

Likely similar thing as https://github.com/ppy/osu/issues/23149 and co.

**Comment by taep96** [comment]
I think it started happening in this or maybe the previous version of the game but I'm not sure if I updated PipeWire in that time. Should I close this issue?

**Comment by bdach** [comment]
Unless you can conclusively prove that this was caused by our changes by way of comparing releases and/or providing a reproducer, probably.

**Comment by dali99** [comment]
Since this issue is about the audio being _faster_ than intended I'm posting some information that might help for other users with the same symptoms here.

running `pw-top`: 

```
R   48   1024  48000 769,5us   0,8us  0,04  0,00    0    S16LE 1 48000 alsa_input.usb-my-real-headset-00.mono-fallback
R   47      0      0   7,7us 130,7us  0,00  0,01    0    S24LE 2 48000  + alsa_output.usb-my-real-headset-00.analog-stereo
...
R  116    441  44100  16,0us  34,5us  0,00  0,00    0    F32LE 2 44100  + alsa_playback.osu!
```

These are the default values I get on my distro without configuring pipewire  or wireplumber with anything other than creating a few sinks and sources

If I use `pw-metadata -n settings 0 clock.force-quantum <n>` with any value above 441 (the buffer osu sets) it will have the sped up distortion. The same or below makes it sound right (at least to my ears)

Setting this value low is the kind of thing an osu player would do to get lower latency _anyways_ so maybe this is why the error is not common?

I don't know how or why `411` is chosen or if that value is stable
