### ISSUE TITLE
Miss count discrepancy on slider heavy maps

### ISSUE THREAD

**Issue by Natelytle** [ppy/osu#25200]
### Type

Crash to desktop

### Bug description

When [this replay](https://osu.ppy.sh/scores/osu/4420153031) is viewed back on the latest master, the miss count jumps from 3 to 8. May be caused by #24966.

### Screenshots or videos

https://github.com/ppy/osu/assets/92956514/28fa07eb-501c-40dc-ac7d-49029c0fc452

https://github.com/ppy/osu/assets/92956514/7db3194f-8e73-46ee-887c-0f03e56f1e64

https://github.com/ppy/osu/assets/92956514/fa73fbb9-46c1-4905-8797-82fa2daf24dc

https://github.com/ppy/osu/assets/92956514/d979bbe4-97c9-44f2-b528-3b5997a9925b

### Version

d0599496bdd76fca2f81b8865a19f77dff70d156

### Logs

[database.log](https://github.com/ppy/osu/files/13061664/database.log)
[input.log](https://github.com/ppy/osu/files/13061665/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/13061666/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/13061667/network.log)
[performance.log](https://github.com/ppy/osu/files/13061668/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13061669/runtime.log)

**Comment by bdach** [comment]
> May be caused by #24966

Did you bisect this / compare against latest release to say this? Or is this just an educated guess?

**Comment by Natelytle** [comment]
Just an educated guess, because I noticed some similar behaviours when I was testing it out for the first time. I just assumed this was fixed by the followup commits but maybe it wasn't

**Comment by Natelytle** [comment]
Update: Bisected now that I'm at my PC and this issue was caused by 9e1fec0213d8541a813300d415d1956417979c6a

**Comment by bdach** [comment]
Yeah that checks out unfortunately.

The first extra miss on this replay is here:

![osu_2023-10-23_11-05-51](https://github.com/ppy/osu/assets/20418176/2427d8a0-c74c-4096-b6a9-5e9128a7342f)

This slider is 37.5ms long, so it qualifies for the "legacy last tick is in the middle of the slider" case.

Judgement order before https://github.com/ppy/osu/pull/24966:

```
[runtime] 2023-10-23 09:28:07 [verbose]: osu.Game.Rulesets.Osu.Objects.SliderTailCircle @ 95143.75 judged @ 95143.75 as SmallTickHit
[runtime] 2023-10-23 09:28:07 [verbose]: osu.Game.Rulesets.Osu.Objects.Slider @ 95125 judged @ 95162.5 as Ok
[runtime] 2023-10-23 09:28:07 [verbose]: osu.Game.Rulesets.Osu.Objects.SliderHeadCircle @ 95125 judged @ 95225.66132676424 as LargeTickMiss
```

The tail is judged out of order at the midpoint of the slider.

After that pull:

```
[runtime] 2023-10-23 09:26:36 [verbose]: osu.Game.Rulesets.Osu.Objects.SliderHeadCircle @ 95125 judged @ 95226.7903388258 as LargeTickMiss
[runtime] 2023-10-23 09:26:36 [verbose]: osu.Game.Rulesets.Osu.Objects.SliderTailCircle @ 95162.5 judged @ 95162.5 as SmallTickMiss
[runtime] 2023-10-23 09:26:36 [verbose]: osu.Game.Rulesets.Osu.Objects.Slider @ 95125 judged @ 95162.5 as Miss
```

The head circle of the slider, due to having a nonzero hitwindow, _blocks_ the tail from being judged (since the aforementioned bisect commit disallows judging nested objects out of order), therefore causing the entire slider to be missed.

I don't even know where to begin with this one. The choices seem to be either to accept this state of affairs or drop the "nested objects must be judged in order" thing and instead either try to hack score to not be broken (https://github.com/ppy/osu/pull/24966#issuecomment-1743308602) or accept score as broken................

**Comment by peppy** [comment]
Can we not just change the conditional added in https://github.com/ppy/osu/commit/9e1fec0213d8541a813300d415d1956417979c6a to only match ticks? At a glance, that seems to be what it's trying to do. The fact it's matching on a `SliderHeadCircle` wasn't something I considered when adding that change (forgot they came up as nested objects).

```diff
diff --git a/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderTail.cs b/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderTail.cs
index df55f3e73f..e52451e75d 100644
--- a/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderTail.cs
+++ b/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderTail.cs
@@ -4,6 +4,7 @@
 #nullable disable
 
 using System.Diagnostics;
+using System.Linq;
 using JetBrains.Annotations;
 using osu.Framework.Allocation;
 using osu.Framework.Graphics;
@@ -133,7 +134,8 @@ protected override void CheckForResult(bool userTriggered, double timeOffset)
             //
             // This covers the edge case where the lenience may allow the tail to activate before
             // the last tick, changing ordering of score/combo awarding.
-            if (DrawableSlider.NestedHitObjects.Count > 1 && !DrawableSlider.NestedHitObjects[^2].Judged)
+            var lastTick = DrawableSlider.NestedHitObjects.LastOrDefault(o => o.HitObject is SliderTick || o.HitObject is SliderRepeat);
+            if (lastTick?.Judged == false)
                 return;
 
             // The player needs to have engaged in tracking at any point after the tail leniency cutoff.

```

**Comment by bdach** [comment]
Theoretically, yes, you could do that. But if you do, then that now means there are 2 possibilities:

- head is judged before tick
- tick is judged before head

And because the slider head is a 'large tick' and as such affects combo, this also affects score, bringing back the aforementioned issue wherein now it may not be possible to get 1M score just because of unlucky judgement ordering.

**Comment by peppy** [comment]
An addition of forcing a miss of the head in such a case could resolve this (and sounds amicable to me). What do you think?

**Comment by bdach** [comment]
Maybe? That seems to be conceptually similar to https://github.com/ppy/osu/discussions/25129, although that seems to propose forcing the head to be hit rather than missed, and contains a condition of "closeness" to the head that I don't understand.

**Comment by peppy** [comment]
#25129 focuses on cases where the head is *hit*. Correct me if I'm wrong, but the case in this issue doesn't involve the head getting hit by the user.

**Comment by bdach** [comment]
Yeah fair enough. You're not wrong.
