### ISSUE TITLE
Slider velocity doesn't change back after undoing it.

### ISSUE THREAD

**Issue by LacticWhale** [ppy/osu#25239]
### Type

Cosmetic

### Bug description

If you change slider point position and strech the slider length (change velocity on timeline) undoing this action once will cause to slider velocity be as before edit on timeline but actual slider velocity will be different.

Steps to reproduce:
1. Place slider
2. Move slider end to different location
3. Strech slider on timeline
4. Ctrl + Z

### Screenshots or videos

https://github.com/ppy/osu/assets/48318484/51927f1b-4bd1-4945-b00e-0b55d57fe459

### Version

2023.1026.0

### Logs

[input.log](https://github.com/ppy/osu/files/13178258/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/13178260/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/13178261/network.log)
[performance.log](https://github.com/ppy/osu/files/13178262/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13178263/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13178264/updater.log)
[database.log](https://github.com/ppy/osu/files/13178265/database.log)

**Comment by LacticWhale** [comment]
I hope it is a bug, and I am not just insane.

**Comment by LacticWhale** [comment]
Just noticed undo event in any order will not modify slider velocity back.

**Comment by peppy** [comment]
This issue looks to stem from this line:

https://github.com/ppy/osu/blob/1a37543d288fa3b62d19a34d443ee97943920fbd/osu.Game/Screens/Edit/LegacyEditorBeatmapPatcher.cs#L54-L53

- Velocity is changed (and applied to `Slider.Velocity`)
- Undo operation performed, entering legacy diff mode
- Control points are compared after legacy info being dropped, so velocity change is not visible to the diff system

As far as I'm concerned this can't be hotfixed (and even if it can be, any further band-aids on this legacy patcher is going to make things illegible). Focus should be on replacing the differ with a more modern approach.

@bdach interested in your thoughts here since you've worked closely with this.
