### ISSUE TITLE
Right clicking an object in the hit object timeline incorrectly selects playfield objects

### ISSUE THREAD

**Issue by AIOM786** [ppy/osu#25283]
### Type

Game behaviour

### Bug description

While making a Osu!Catch beatmap using the Osu Lazer editor for Osu!Catch when I went to select a hit object and right click it to set the hitobject to a new combo or to delete the object the dropdown menu did not appear but instead it selected the hitobject that was hidden behind the hitobject timeline as shown in the video below.        

### Screenshots or videos

https://github.com/ppy/osu/assets/149255845/c7338d82-83b8-4f6e-b2db-dcc4d1691dbf

### Version

2023.1026.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/13196270/network.log)
[performance.log](https://github.com/ppy/osu/files/13196271/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/13196272/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/13196273/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/13196274/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/13196275/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/13196276/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13196277/updater.log)
[database.log](https://github.com/ppy/osu/files/13196278/database.log)
[input.log](https://github.com/ppy/osu/files/13196279/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/13196280/legacy-ipc.log)

**Comment by peppy** [comment]
Another annoying one.

`SelectionHandler` is receiving input from anywhere out of necessity:

https://github.com/ppy/osu/blob/19f892687a0607afbe4e0d010366dc2a66236073/osu.Game/Screens/Edit/Compose/Components/SelectionHandler.cs#L119-L125

Also important is that `BlueprintContainer` will selectively not block right clicks to make sure they fall through to the `ContextMenuContainer`:

https://github.com/ppy/osu/blob/19f892687a0607afbe4e0d010366dc2a66236073/osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs#L122-L126

But because the whole editor is sharing a `ContextMenuContainer` and it's at a higher level than both components, we observe here the playfield's `SelectionHandler` intercepting the right click before it can reach the `ContextMenuContainer`.

**Comment by peppy** [comment]
So naming the `mainContent` and DI'ing for this purpose? I considered that path but it's quite something.

**Comment by bdach** [comment]
I mean yeah I probably wouldn't cache a `Container`. Could just make a special dummy `EditorMainContent : Container` class for this or something. Or pass via ctor if feasible (doesn't require ferrying across N levels of hierarchy).
