### ISSUE TITLE
Serious performance issues with the new argon health bar

### ISSUE THREAD

**Issue by ghost** [ppy/osu#25542]
### Type

Performance

### Bug description

I had this issue since the health bar was added (before the UI revamp). It only occurs when the health bar is rendered on the screen, which is what I'm trying to show near the end by scrolling up and down on the skin editor.

### Screenshots or videos

https://github.com/ppy/osu/assets/151527469/e3c464b8-3ad1-462d-8f8d-380857c94caf

### Version

2023.1114.1

### Logs

[database.log](https://github.com/ppy/osu/files/13440932/database.log)
[input.log](https://github.com/ppy/osu/files/13440934/input.log)
[network.log](https://github.com/ppy/osu/files/13440935/network.log)
[performance.log](https://github.com/ppy/osu/files/13440936/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13440937/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13440938/updater.log)

**Comment by peppy** [comment]
Hardware:

```
2023-11-10 23:58:28 [verbose]: Direct3D 11 Initialized
2023-11-10 23:58:28 [verbose]: Direct3D 11 Feature Level:           11.1
2023-11-10 23:58:28 [verbose]: Direct3D 11 Adapter:                 AMD Radeon R7 M265 Series
2023-11-10 23:58:28 [verbose]: Direct3D 11 Dedicated Video Memory:  2027 MB
2023-11-10 23:58:28 [verbose]: Direct3D 11 Dedicated System Memory: 0 MB
2023-11-10 23:58:28 [verbose]: Direct3D 11 Shared System Memory:    6100 MB
2023-11-10 23:58:28 [verbose]: UseStructuredBuffers: True
```

https://www.notebookcheck.net/AMD-Radeon-R7-M265.109394.0.html

It seems weird this card would have such low performance. The health bar *is* using some buffered containers, but so is a lot of other stuff in the game.

@boogeyoogeyman Are you able to make sure you're on the latest graphics card drivers available? Also, could you please make a video with performance stats visible? You can toggle the frame graphs with Ctrl+F11, and detailed performance statistics using Ctrl+F2 (just scrolling through these slowly while the issue is occurring may help us figure out what's going on here).

**Comment by boogeyoogeyman** [comment]
Unfortunately, I'm not on the latest graphics drivers, and currently using [these](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-15-7-1). I tried to install Adrenalin drivers before, but they would cause the entire system to freeze after 2 seconds. Even when it doesn't, nothing works. No startup programs start, no taskbar icons work, no folders load, etc. It puzzles me how a graphics driver can cause this even when it's not the one rendering the desktop.

Regardless, here's the updated video.

In the second video, it seems to be dropping frames when the hp bar is animating. Something else to take note of.

Note: FPS values are slightly lower because of recording, but the issue is there.

https://github.com/ppy/osu/assets/151527469/50d45f22-dcd1-4bf4-86a2-53827b82c66c




https://github.com/ppy/osu/assets/151527469/943aec43-791f-46f8-95b6-cbee35bc62a9

**Comment by boogeyoogeyman** [comment]
The issue doesn't exist with Intel HD card, although the performance is naturally lower. Except on stable, which I always used that over the AMD card because it performed better.

**Comment by peppy** [comment]
That's a 2015 driver...? I'm not sure we can support that.

**Comment by boogeyoogeyman** [comment]
That's reasonable. I understand.

It's slightly better with argon skin but much worse overall. 

I was just puzzled because everything works fine but that one cheeky hp bar haha. Thanks.

**Comment by NotGumballer91** [comment]
Initially I thought this was an AMD GPU issue so I tested it for myself and apparently it was. I'm seeing a considerable performance difference without the new Argon HP bar. I highly doubt it's a driver issue specifically. I'm using preview driver (23.12.1). _Technically the latest one._

As peppy suggested, Switching to OpenGL did help a bit. It makes sense this is worse and more apparent for lower end ones.

**With Argon HP Bar:**

https://github.com/ppy/osu/assets/64581009/5f9a93b9-6d2a-400a-84de-d8bbd90b2404

**Without Argon HP Bar:**

https://github.com/ppy/osu/assets/64581009/7f8ea0e0-8029-413c-b314-cef74aa80446


[performance-draw.log](https://github.com/ppy/osu/files/13619998/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/13619999/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/13620001/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/13620002/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13620003/updater.log)
[database.log](https://github.com/ppy/osu/files/13620004/database.log)
[input.log](https://github.com/ppy/osu/files/13620005/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/13620006/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/13620007/network.log)
[performance.log](https://github.com/ppy/osu/files/13620008/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/13620009/performance-audio.log)
