### ISSUE TITLE
Perfect mod fails if player gets Great judgement in osu!mania

### ISSUE THREAD

**Issue by longnguyen2004** [ppy/osu#25581]
### Type

Game behaviour

### Bug description

Got this while trying out Perfect and wondering why I kept failing. A quick look through the code shows that failure is triggered when the judgement isn't the max judgement, which doesn't match with mania on stable

https://github.com/ppy/osu/blob/a6cf1e5d2eabb3cd5f32da0b213e20c1ab601a91/osu.Game/Rulesets/Mods/ModPerfect.cs#L30-L32

### Version

2023.1114.1

### Logs

Not needed

**Comment by bdach** [comment]
This report made sense when both great and perfect were weighted 300, but now that perfect is weighted 305, I don't know if it still does...

@smoogipoo tagging you in only because you touched perfect in https://github.com/ppy/osu/pull/26036 - do you think we should be changing this locally to mania perhaps?

**Comment by smoogipoo** [comment]
Yep, local to mania in this case.
