### ISSUE TITLE
osu! lazer mania play not calculating daycore for some reason

### ISSUE THREAD

**Issue by Detable** [ppy/osu#25719]
### Type

Game behaviour

### Bug description

so i was playing the osu mania galaxy collapse map (https://osu.ppy.sh/beatmapsets/400078#mania/992512) with daycore and it said it was worth around 250pp at first but then when i looked at the score again it said 405pp which i think it would be worth without daycore with this acc

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/129502455/823a556e-895f-4688-9bf3-90d1e54a1ecf)
![image](https://github.com/ppy/osu/assets/129502455/27d23288-0f36-4cd4-b53e-21a08e0b5441)

### Version

2023.1130.0-lazer

### Logs

[input.log](https://github.com/ppy/osu/files/13627940/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/13627941/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/13627942/network.log)
[performance.log](https://github.com/ppy/osu/files/13627943/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/13627944/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/13627945/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/13627946/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13627947/updater.log)
[database.log](https://github.com/ppy/osu/files/13627948/database.log)

**Comment by Detable** [comment]
![image](https://github.com/ppy/osu/assets/129502455/555407fb-0986-4e5c-83a2-a0d2332b69e6)
another one this one only should be 107

**Comment by bdach** [comment]
I'm not yet sure what has happened here but the values do appear to be incorrect in the way described.

**Comment by bdach** [comment]
Yeah as far as I can tell this going to be an `osu-queue-score-statistics` issue.

[This is the list of mods valid for pp for lazer scores currently.](https://github.com/ppy/osu-queue-score-statistics/blob/98912d4d56fff8b7edebff5d65f02c4df5715dbc/osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs#L149-L219) Notably, it contains mods that do not exist in stable, namely: `ModDaycore`, `ModMuted`, and `ModClassic`. The last two are _likely_ not an issue for now, but the former is.

The significance of these mods not being in stable is thus: Currently `osu-queue-score-statistics` is operating with `REALTIME_DIFFICULTY=0` in production. The effect of this is that the difficulty attributes are fetched from the database rather than computed on-demand.

The fetch pathway contains [this logic](https://github.com/ppy/osu-queue-score-statistics/blob/31745808995127a1f0f7a12d7217cfd740137535/osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs#L88-L89). The significant piece is the `ruleset.ConvertToLegacyMods()` call. Because daycore does not exist in stable, it is not handled by that method, and as such is essentially dropped when looking up difficulty attributes. This causes daycore scores to look up nomod difficulty attributes instead, which changes the star rating used for pp calculation, and makes nomod and daycore scores receive the same pp value.

The end goal is likely to enable realtime difficulty as it will be required to support lazer mods at _some_ point. However I do not know when that point is.

Possible resolutions I can see for now that would not require enabling realtime difficulty:
- Disable daycore giving pp for now
- Patch daycore scores locally to `osu-queue-score-statistics` by substituting in half-time mod in its stead?

ping @ppy/team-client for visibility / discussion

**Comment by smoogipoo** [comment]
> Patch daycore scores locally to `osu-queue-score-statistics` by substituting in half-time mod in its stead?

I propose we go with solution. We're not going to be using `REALTIME_DIFFICULTY=1` for now because I guarantee it's not going to scale gracefully (hasn't been tested in prod, something I've been hoping to do but hasn't come to fruition yet).
