### ISSUE TITLE
Random squares appear in osu!catch

### ISSUE THREAD

**Issue by LovelyA72** [ppy/osu#2578]
It happens randomly when the hit object hits the catcher's plate. And when I am playing back my record to take screenshots of this issue, I found that these circles for the hit object become squares too! If you need logs, I will be happy to provide.

Here are some screenshots: 
![image](https://user-images.githubusercontent.com/29054052/40219629-c9803228-5aa8-11e8-8f1d-ac6eb7576417.png)
![image](https://user-images.githubusercontent.com/29054052/40219647-dded3652-5aa8-11e8-8ec8-16c8becedfe0.png)
![image](https://user-images.githubusercontent.com/29054052/40219736-44f3a552-5aa9-11e8-9a18-66086bc015c6.png)
![image](https://user-images.githubusercontent.com/29054052/40219775-6366404e-5aa9-11e8-8054-f241d4b98a24.png)

**Comment by dragonGod97677** [comment]
Are u using any skins? If u use: may be its the skin.. If not: maybe a bug/graphics bug/etc..(u name it)

**Comment by DudeMartin** [comment]
So I was looking into this issue, and I found it interesting that when I tried to get the bounding box of a caught fruit, I would get a `NullReferenceException`. It turns out that `caughtFruit.Parent` is `null` inside `CatcherArea#OnJudgement(...)`. I added this code after line 64 in `CatcherArea`:

```
                try
                {
                    Console.WriteLine(caughtFruit.BoundingBox);
                }
                catch (NullReferenceException)
                {
                    Console.WriteLine(caughtFruit.Parent == null); // always prints `True`
                }
```

This *only* prints `True`. It also has another interesting effect: merely calling `caughtFruit.BoundingBox` completely stops displaying the occasional rectangle on the catcher area, and instead displays a smaller version of it in the top-left corner of the screen. Here is a picture of what that looks like:

![smallerboundingboxintopleftcorner](https://user-images.githubusercontent.com/1411294/40282347-11207900-5c3c-11e8-9249-a5518f94f4f5.png)

Is the parent `null` because the fruit drawable is being prematurely disposed?

**Comment by smoogipoo** [comment]
@DudeMartin That's intended. Catch removes the fruit from the draw hierarchy to move it somewhere else. It's a pretty dodgy way of going about things and I'd much prefer if it constructed new fruit, though...

Actually think this might be a recurrence of the CircularContainer invalidation issues we had a while back, since it's replicable in mania's judgements too.
