### ISSUE TITLE
Entered text does not show up in text boxes until IME confirmation on Android

### ISSUE THREAD

**Issue by Jan-Arbus** [ppy/osu#25851]
### Type

Game behaviour

### Bug description

When entering cjk text, the entered text should be displayed in the text box as shown in Video 2

### Screenshots or videos

https://github.com/ppy/osu/assets/74862110/5b05f2bd-a352-4ca2-8ddc-662a619b5a7f

video2: 

https://github.com/ppy/osu/assets/74862110/de980641-526d-4909-9f89-ce738b96d2d5

### Version

2023.1218

### Logs

N/A

**Comment by bdach** [comment]
I can corroborate and [it's not even unique to CJK](https://discord.com/channels/188630481301012481/589331078574112768/1186299419738521670).

**Comment by bdach** [comment]
I'm like 99% sure this is happening because gboard changed something on their side and now it's not working like it used to. Corroborating circumstances:

- checked out 2023.1004.1 framework release on my test device where this is broken and it was still broken, and it was 200% not broken for this long
- checked out latest framework master on my other test device (that does not use gboard, notably) and it works fine

This used to be a bit of a thing before but gboard is *the* software keyboard out there now, so we're gonna have to bend over backwards and fix whatever's causing it...

**Comment by Susko3** [comment]
@bdach could you give https://github.com/ppy/osu-framework/compare/master...Susko3:osu-framework:android-ime-composition a try. You should expect the text to appear as IME composition, and clicking on the suggesting or dismissing the keyboard will hopefully commit the text.

Try dismissing by clicking the native back button and just tapping elsewhere in the game.

**Comment by bdach** [comment]
@Susko3 it's an okay start, but things are a bit broken still, especially when deleting text, and inputting numbers:

https://github.com/ppy/osu/assets/20418176/13b3c49a-2387-4bca-bfa3-f3831f28d2a9

Were you writing that code blind? If so, then it may be more productive for me to take a look at some point.

**Comment by Susko3** [comment]
Half-blind. I can test actual IME input (eg. Japanese, Chinese) and that works fine. But I'm not able to test the problem with Latin input.

> If so, then it may be more productive for me to take a look at some point.

Agreed.

**Comment by bdach** [comment]
Android changed something their end again and I can't reproduce the latin issue anymore but I also can't get CJK IME to do anything in any of the game textboxes.............

**Comment by Jan-Arbus** [comment]
Now this problem has disappeared, maybe it is due to the migration to sdl3. But I am not sure
