### ISSUE TITLE
Switching beatmap sound plays when exiting gameplay

### ISSUE THREAD

**Issue by Stoppedpuma** [ppy/osu#25875]
### Type

Game behaviour

### Bug description

The switching maps sound effect will play on the beatmap into when spamming left click.

Only happens when going from song select into the map, not from retrying.

### Screenshots or videos

https://github.com/ppy/osu/assets/58333920/9f685050-1190-490d-881b-cfee992dad3d

### Version

2023.1218.1

### Logs

[shorter_runtime.log](https://github.com/ppy/osu/files/13708668/shorter_runtime.log)

**Comment by Stoppedpuma** [comment]
Seems to play even without pressing left click as well

**Comment by OliBomby** [comment]
I noticed this sound often also comes associated with a lag spike for me. Considering the lag spike always happens when this 'switching beatmap' sound plays, i figured it might be related. The lag only happens when I have the song select sorted by Difficulty. I also have like 100k beatmaps imported which might be related.

https://github.com/ppy/osu/assets/17460441/6425d446-d88d-494a-ad35-3ca4410de160

**Comment by peppy** [comment]
I think this might be related to ongoing background processing. @OliBomby can you confirm that your background processing is still running when this happens? You should also be able to cancel it via the notification if it is, and confirm that fixes the issue.

**Comment by peppy** [comment]
Scratch that, this is a regression from the hotfix fixing the last regression.

**Comment by peppy** [comment]
Clicking is not required to make this happen.
