### ISSUE TITLE
Judgements sometimes disappear before their animation is complete

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#26009]
### Type

Cosmetic

### Bug description

This is probably related to pooling or expiry in some way, as it doesn't always happen. Easiest way to see it happen is with the osu! classic skin.

Try staring at the centre of the screen while watching the video, and see if you notice any of the judgements popping out before their fadeout is complete. You should see it for example on the first purple circles towards the bottom left of the screen.

### Screenshots or videos

https://github.com/ppy/osu/assets/1329837/0b4ceba8-f84d-4fef-8086-cbaeefb90c6e

### Version

https://github.com/ppy/osu/commit/716d866178367d0f85247cc10fb1f9e247b925ad

### Logs

-

**Comment by MCSulphate** [comment]
I believe I'm having a related issue since the latest update, except from it's happening on every judgement except from slider-related misses from not pressing a key. I am using a skin imported from stable a couple months ago.

This was not happening around a week or so ago, although I can't pinpoint exactly as I've not played for around a week.

https://github.com/ppy/osu/assets/11224024/8eaf57f9-5917-412a-8c65-04d08e655eef

**Comment by bdach** [comment]
@mcsulphate that's https://github.com/ppy/osu/issues/26801, and a hotfix release for that is building right now
