### ISSUE TITLE
Weird interactions in skin editor with ui elements

### ISSUE THREAD

**Issue by Sukuratchi** [ppy/osu#26021]
### Type

Cosmetic

### Bug description

When moving certain skin elements in the gameplay preview, the playback, visual settings and audio settings popups move when a skin element is nowhere near them

### Screenshots or videos

https://github.com/ppy/osu/assets/66184829/35f257ab-9c40-48c9-8b51-8b0ee78ca0a5

### Version

2023.1222.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13746327/compressed-logs.zip)

**Comment by bdach** [comment]
This is an intentional behaviour, based on a heuristic whose purpose is to automatically lay out the elements in question in a place where it can be correctly displayed without overlapping other elements:

https://github.com/ppy/osu/blob/a7326e3891a67a548d622ad146c38203cabe2a85/osu.Game/Screens/Play/HUDOverlay.cs#L260

Possibly it can be improved in the future, but for now this is intended.
