### ISSUE TITLE
`ArgonKeyCounterDisplay` and `DefaultKeyCounterDisplay` does not show up in gameplay

### ISSUE THREAD

**Issue by ikkue** [ppy/osu#26062]
### Type

Game behaviour

### Bug description

As seen in the video, both `ArgonKeyCounterDisplay` and `DefaultKeyCounterDisplay` disappear (but are technically still there with presumably zero width) when in normal gameplay, but reappear once "Gameplay" in the scene library is selected in the skin editor. But once you exit out of the skin editor, both are gone again.

### Screenshots or videos

https://drive.google.com/file/d/1966v59F1EjEBvSIQcxrHyzJFzom8BetK/view?usp=sharing

### Version

2023.1223.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13755259/compressed-logs.zip)

**Comment by bdach** [comment]
It's because you have "Always show key overlay" unchecked in settings. If you check it, it should show up as intended. The reason it shows up via the gameplay scene is that that shows a replay, and key overlay always shows up on replays, but not always during gameplay (specifically not when the aforementioned option is off).

Not ideal, eventually this setting will be moved to the skin editor, but that is what it is.

**Comment by ikkue** [comment]
Oh, I did not realise that! My C drive was too full when downloading today's update and that ended up resetting every setting I had upon restarting the game.
