### ISSUE TITLE
"Deselect all mods" keybind not working as expected

### ISSUE THREAD

**Issue by Sclafus** [ppy/osu#26347]
### Type

Game behaviour

### Bug description

I changed the "Deselect all mods" and set it to "1" for muscle memory with Stable. 
If I press "1", it simply searches the character "1".

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/31241607/b4fb9e2b-debd-48bb-812a-76b0b0dcbb83)
![image](https://github.com/ppy/osu/assets/31241607/9ea8efdb-d4c9-467d-8570-ebb76b2bd27b)

### Version

2023.1231.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13814066/compressed-logs.zip)

**Comment by Sclafus** [comment]
Actually, also the default (backspace) seems to be captured by the search box.

**Comment by bdach** [comment]
This is by design. You can unfocus the search box by pressing <kbd>Tab</kbd>, at which point you will be able to use the deselect hotkey and the individual mod hotkeys.

If you would like the textbox to not focus by default there is also a setting option for that (search for "Automatically focus text box in mod select").
