### ISSUE TITLE
Pausing gameplay can cause phantom misses

### ISSUE THREAD

**Issue by Locas1000** [ppy/osu#26442]
### Type

Crash to desktop

### Bug description

I paused on top of a slider and when I unpaused it counted as a miss but the combo score didn't change. The replay shows a miss but the end screen says the total combo 

### Screenshots or videos

https://clipchamp.com/watch/IOwL5sv38f7

### Version

2023.1231.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13867290/compressed-logs.zip)

**Comment by peppy** [comment]
This is going to be due to the rewind happening when pausing/unpausing. We might just want to completely disable that (and the frequency ramp which is the reason for it existing) until things are in a better place.

**Comment by frenzibyte** [comment]
I cannot seem to reproduce this one at all, not sure what I'm missing.

**Comment by peppy** [comment]
Try adjusting platform offset to something very high (and also not zero, which is what you have due to macOS). It will be related. I think universal offset may also work.

If that still doesn't work, try increasing the ramp time https://github.com/ppy/osu/blob/6572fa4378811663971527a80ea86b9db1c94103/osu.Game/Screens/Play/MasterGameplayClockContainer.cs#L123 to absurd levels. It should cause gameplay to skip back on resume.
