### ISSUE TITLE
Drawing sliders when using a touch device doesn't work as expected

### ISSUE THREAD

**Issue by peppy** [ppy/osu#26509]
https://github.com/ppy/osu/assets/191335/4dc57134-a6fe-4b13-a5fd-361454b34d04

**Comment by Susko3** [comment]
Placing any kind of object with touch is broken: for the initial click, it uses the old mouse position instead of the new touch/mouse position. With sliders, only the first control point is broken.

This is because [the position of the placement is updated in `Update()`](https://github.com/ppy/osu/blob/288ac930e44bd8dc5b5ab8d5f5f342228625fc0d/osu.Game/Screens/Edit/Compose/Components/ComposeBlueprintContainer.cs#L329-L330), which happens after input handling [finalises](https://github.com/ppy/osu/blob/0ab0c52ad577b3e7b406d09fa6056a56ff997c3e/osu.Game.Rulesets.Osu/Edit/Blueprints/HitCircles/HitCirclePlacementBlueprint.cs#L37-L43) or [starts](https://github.com/ppy/osu/blob/83e108071a123650991fded528f64ad80421d155/osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderPlacementBlueprint.cs#L139-L148) the placement.

https://github.com/ppy/osu/assets/16479013/e1a52687-bd0f-4702-8a6f-339a756061e2

**Comment by bdach** [comment]
see https://github.com/ppy/osu/issues/19422#issuecomment-2210851495 for update on this i guess
