### ISSUE TITLE
TestCaseBeatmapInfoWedge can't be automatically recompiled due to protection level

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#2656]
```
27.05.2018 19:21.57: Recompiling TestCaseBeatmapInfoWedge...
27.05.2018 19:21.58: Error with dynamic compilation!
27.05.2018 19:21.58: System.Exception: C:\osu!lazer\osu\osu.Game\Screens\Select\BeatmapInfoWedge.cs(56,28): error CS0122: 'CanBeNullAttribute' is inaccessible due to its protection level
```

Tested by compiling the test case then just saving it again to recompile.

**Comment by peppy** [comment]
We probably want to resolve this one before expanding our usage of jetbrains attributes.

**Comment by FreezyLemon** [comment]
Uhh I _think_ I found it, but I have no clue how to fix it...
So, to replicate how I found this:
1. Remove the framework from the `osu.Game` NuGet packages
2. Find a spot in `osu.Game` where the `NotNullAttribute` is used
3. See "Inaccessible due to protection level", hit F12 to "Go to Definition"
4. See that it's trying to reference [this](https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/Shared/CodeAnnotations.cs#L12) because EF Core is used
5. Wonder why the EF Core team thought it was a good idea to use the same namespace...
