### ISSUE TITLE
In the skin editor, right-clicking an object when holding it randomly teleports it

### ISSUE THREAD

**Issue by Timkador** [ppy/osu#26640]
### Type

Game behaviour

### Bug description

I was making a skin layout and I wanted to adjust an object's origin, but I right-clicked when I was still holding it which teleported it. I tested this with other objects and it teleports them too.
Also as I result I have two random healthbars in random places, one of which is not visible in the editor, but visible in gameplay, because I play on a widescreen monitor, is there a way to remove them?

### Screenshots or videos

https://github.com/ppy/osu/assets/104220939/bb184a5a-27c2-4d3f-9090-68b62934aa97

### Version

2024.114.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13997669/compressed-logs.zip)

**Comment by Gabixel** [comment]
Very strange. (Probably has something to do with how context menus work, but I'm not an expert yet).

Anyway, to fix your out-of-bounds problem with components, you can follow these (unintuitive) steps for the time being:
- <kbd>CTRL</kbd>-<kbd>A</kbd> to select all objects
- Hold again <kbd>CTRL</kbd> and click **on each visible object** so that you can deselect them, and do it until you get to the point where you are only keeping selected what is off the screen
- Delete the selected objects with <kbd>Del</kbd>

Here's a video of the steps:

https://github.com/ppy/osu/assets/43073074/720fbc59-a0b4-4957-84b3-38693354d41f

**Comment by Gabixel** [comment]
Also related: #12795

**Comment by Gabixel** [comment]
This is more of a question to the devs, but I think this is another scenario for [https://github.com/ppy/osu-framework/issues/6102](https://github.com/ppy/osu-framework/issues/6102)? I can also reproduce this with the middle mouse button

**Comment by frenzibyte** [comment]
> This is more of a question to the devs, but I think this is another scenario for [ppy/osu-framework#6102](https://github.com/ppy/osu-framework/issues/6102)? I can also reproduce this with the middle mouse button, therefore the context menu is irrelevant here

Thought the same but turns out it was another part of the movement logic causing the issue (see https://github.com/ppy/osu/pull/26661).
