### ISSUE TITLE
ContextFactory.GetForWrite() should probably take in a delegate

### ISSUE THREAD

**Issue by peppy** [ppy/osu#2670]
Currently we use `using` for this pattern, but this means the write context cannot handle any nested exceptions, requiring the consumer to report exceptions back to the write context if it wishes for a rollback to occur, like so:

```csharp
using (var write = ContextFactory.GetForWrite())
{
    try
    {
        // actions
    }
    catch (Exception e)
    {
        write.Errors.Add(e);
    }
}
```

It may work better to change the pattern to 

```csharp
ContextFactory.PerformWrite(() => {
    // actions that used to be nested inside the using block
});
```

such that the ContextFactory can capture exceptions without any overhead.

**Comment by FreezyLemon** [comment]
So the desired solution would be one where the `ContextFactory` catches all exceptions internally and rolls back the transaction. The goal would be that the user can specify a delegate with business logic instead of worrying about handling exceptions, right?

How is the user supposed to be notified of the write failing? A `bool TryPerformWrite`? Throw a custom `DatabaseException`, maybe?

**Comment by peppy** [comment]
It can/should still throw the exception outwards. It just needs to do the rollback internally.

**Comment by peppy** [comment]
This can be done at some later point. Usage should not increase at a rate that makes refactoring overhead increase.

**Comment by peppy** [comment]
Funnily enough, this is happening with #16535 in realm this time.
