### ISSUE TITLE
Some Beatmaps are not sorted correctly by artist after update to 2024.219.0

### ISSUE THREAD

**Issue by sbreaks** [ppy/osu#27259]
### Type

Game behaviour

### Bug description

After updating to version 2024.219.0, when sorting by artist in song select some maps are out of order.

### Screenshots or videos

![osu_2024-02-19_19-23-58](https://github.com/ppy/osu/assets/86324553/79919ddb-c837-4c92-97f5-ae570f7e94ae)

### Version

2024.219.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14337828/compressed-logs.zip)

**Comment by frenzibyte** [comment]
Relevant: https://github.com/ppy/osu/pull/26895

**Comment by frenzibyte** [comment]
I'm seeing two options here:
 - Revert https://github.com/ppy/osu/pull/26895 and keep uppercase/lowercase ordering unknown (aka https://github.com/ppy/osu/issues/26817)
 - Replace https://github.com/ppy/osu/pull/26895 with [this proposal](https://github.com/ppy/osu/pull/26895#issuecomment-1947891093) to fix the issue and match stable

**Comment by bdach** [comment]
It's going to be revert unless you can demonstrate the proposal doesn't regress sort performance.

**Comment by frenzibyte** [comment]
For starters this only affects comparing beatmaps that have the same artist, title, or whatever the sort mode is, where a second comparison is performed to determine order in casing. I can try setting up a quick benchmark for this.

**Comment by ProtogenDelta** [comment]
Flagging for notifications and to chip in with my 2 cents here.

It should also be noted that this is affecting all (string-related) ordering of map selection, not just by artist, but by title, author, etc. as well.

This breaks known patterns/behaviours long since established from stable, and I'd go as far as to say it fundamentally breaks the song selection flow in general - at least from a muscle and/or general memory perspective.

---

A quick comparison between string sorting options, purely from an output perspective (without taking into account performance benchmarking and/or overheads, [as mentioned in the PR](https://github.com/ppy/osu/pull/26895#issuecomment-1947862967))

Given an input list with items `{"1", "2", "3", "A", "B", "C", "a", "b", "c"}` the following behaviours were observed.

| Method | Output | Behaviour |
| --- | --- | --- |
| `StringComparison.Ordinal` | `{"1", "2", "3", "A", "B", "C", "a", "b", "c"}` | Raw Ordinal |
| `StringComparison.OrdinalIgnoreCase` | `{"1", "2", "3", "A", "a", "B", "b", "C", "c"}` | Capital First |
| `StringComparison.InvariantCulture` \* | `{"1", "2", "3", "a", "A", "b", "B", "c", "C"}` | Lowercase First |

*\* = Mentioned as having potential i18n overhead on comparisons?*

**Comment by ProtogenDelta** [comment]
> @bdach: you don't need to do this, and your comment basically restates things we already know. please refrain.

Unnecessary hostility here, but alright.

Reminder that the PR (#26895) was originally to address issue #26817, and the PR focused only on the case from said issue, with no regard for changes to the rest of sorting (i.e. lowercase titles getting pushed to the *end* of the list.) The changes were then *approved* by peppy, before any concerns regarding the sort order were raised, and merged without proper discussion.

Sure, I could've clicked "Subscribe" on this thread and left it at that, but I'd rather contribute to the actual discussion going on here, rather than sitting by and letting this slip through and change core behaviour for the worse.

Cheers.

**Comment by peppy** [comment]
> * = Mentioned as having potential i18n overhead on comparisons?

`CurrentCulture` is the one I was worried about. `InvariantCulture` is likely fine.
