### ISSUE TITLE
Maps show without correct "status" and won't submit new scores

### ISSUE THREAD

**Issue by Arrzed** [ppy/osu#27332]
### Type

Game behaviour

### Bug description

Status refering that is missing the graveyard/loved/ranked pill, causing to also not display the leaderboard for the map in the case of loved/ranked

Redownloading the map seems to fix the issue but i'd rather find another way to deal with it

Initially i thought it was because of custom diffs from osutrainer but i found other maps with custom diffs and they're normal

Also, you can't even open the beatmap page from the diff itself, you have to go from the set

### Screenshots or videos

![diff](https://github.com/ppy/osu/assets/83354828/46f77972-dcb4-4350-8b71-b30d991b608a)
![set](https://github.com/ppy/osu/assets/83354828/10144ca9-7c34-4e63-89c8-e1cf1ca605a7)
![no leaderboard](https://github.com/ppy/osu/assets/83354828/46761941-3550-44d0-8829-981dcdfb845a)

### Version

2024-221.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14379862/compressed-logs.zip)

**Comment by bdach** [comment]
How did you import the maps originally? Were you logged in/online at the time!

**Comment by Arrzed** [comment]
I'm not certain, it was a couple of days ago. Thinking about it, i should've opened the issue earlier lol. I tried importing today before submitting the issue and i was for sure logged in today

**Comment by bdach** [comment]
> I tried importing today before submitting the issue and i was for sure logged in today

...and did those imports work as you'd expect them to? If not, please link maps that didn't import status correctly.

**Comment by Arrzed** [comment]
These ones to name a few:
[https://osu.ppy.sh/beatmapsets/1417973#osu/2921554](url)
[https://osu.ppy.sh/beatmapsets/1596950#osu/3271237](url)
[https://osu.ppy.sh/beatmapsets/1621130#osu/3309939](url)

**Comment by bdach** [comment]
Okay so I _think_ might have happened here is...

The logs show an import from stable:

```
2024-02-22 18:13:45 [verbose]: 📺 ScreenStack#294(depth:4) entered ScreenImportFromStable#772
2024-02-22 18:14:08 [verbose]: Received beatmap updates 1 updates with last id 8147794
2024-02-22 18:15:10 [verbose]: ⚠️ Beatmap import is initialising...
```

The same log also appears to suggest that you were _not_ logged in at the time, because of a lack of indicative lines (such as a `GetMeRequest` on startup, etc.)

So my theory is that what happened is that you have a bit of an older local metadata cache on your device that is not aware of the maps that are missing status. Normally mass imports (e.g. from stable, among others) will try the offline cache and then fall back to online if they fail to match on local cache. However, because you weren't logged in, what I presume happened is that the game tried a local stale metadata cache, failed to find the maps, and as such didn't award them any status.

To confirm, can you upload `online.db` from your game directory?

**Comment by peppy** [comment]
I think we should probably be forcefully updating map status when the map is selected at song select, just as a safety measure. I think stable does something very similar.

**Comment by Arrzed** [comment]
> To confirm, can you upload online.db from your game directory?

[online.zip](https://github.com/ppy/osu/files/14390010/online.zip)

**Comment by bdach** [comment]
Thanks, this confirms the issue. The date of the last beatmap update in the sqlite file is 2020-04-30 21:26:10, which is earlier than the submission date of any of the aforementioned beatmaps.

I'm also half of the mind that we should be periodically re-downloading the local metadata cache. Not sure how often that is updated if ever, but the latest version I just pulled seems to contain maps from 2024-02-15, so it _is_ getting updated. Maybe we can have clients pull that down once every few months or something.

**Comment by peppy** [comment]
One of the hundreds of items on my todo list:

![2024-02-24 19 24 40@2x](https://github.com/ppy/osu/assets/191335/b07ca3d1-565e-4b51-8933-b4082354bd83)

😮‍💨

**Comment by BadAimWeeb** [comment]
There is another bug for some beatmaps also causing map to not show the correct status (and won't submit new scores).

For some reason, some beatmaps have a different online ID in .osu file rather than the correct ID. Stable handle this difference fine, but lazer freaks out and won't accept status data from online.
```
----------------------------------------------------------
database Log for BadAimWeeb (LogLevel: Verbose)
Running osu 2024.412.1.0 on .NET 8.0.4
Environment: Windows (Microsoft Windows NT 10.0.22631.0), 16 cores 
----------------------------------------------------------
2024-05-04 07:22:13 [verbose]: [?????] Beginning import from tmpthpntl.osz...
2024-05-04 07:22:13 [verbose]: [e5d50] [APIBeatmapMetadataSource] Online retrieval mapped Mestre3224 - Caramelo da desgraca (Niko_Plays) [Extra] to 1926366 / 3977760.
2024-05-04 07:22:13 [verbose]: [e5d50] [APIBeatmapMetadataSource] Online retrieval mapped Mestre3224 - Caramelo da desgraca (Niko_Plays) [Maxim's Insane] to 1926366 / 4024477.
2024-05-04 07:22:14 [verbose]: [e5d50] [APIBeatmapMetadataSource] Online retrieval mapped Mestre3224 - Caramelo da desgraca (Niko_Plays) [Normal] to 1926366 / 3978358.
2024-05-04 07:22:14 [verbose]: [e5d50] [APIBeatmapMetadataSource] Online retrieval mapped Mestre3224 - Caramelo da desgraca (Niko_Plays) [Vincus' Another] to 1926366 / 3993089.
2024-05-04 07:22:14 [verbose]: [e5d50] [APIBeatmapMetadataSource] Online retrieval mapped Mestre3224 - Caramelo da desgraca (Niko_Plays) [hexe's Hard] to 1926366 / 3978606.
2024-05-04 07:22:14 [verbose]: Discarding metadata lookup result due to mismatching online ID (expected: 4096310 actual: 3978606)
2024-05-04 07:22:14 [verbose]: [e5d50] Import successfully completed!
```

*stable works fine with this beatmap*
![image](https://github.com/ppy/osu/assets/29724654/8d774281-7671-48e5-b0b5-6d3d34cf08c9)

*...but lazer failed to get online status and won't display anything, and can't submit scores*
![image](https://github.com/ppy/osu/assets/29724654/1bd5148f-4e53-47b8-a68e-064b000bc833)

https://osu.ppy.sh/beatmapsets/1926366#mania/3978606

**Comment by peppy** [comment]
I'm going to look at a server-side fix for this as a priority.
