### ISSUE TITLE
Performance points calculation in the end screen is wrong after watching a replay

### ISSUE THREAD

**Issue by u3o** [ppy/osu#27465]
### Type

Game behaviour

### Bug description

After watching a replay, the end screen shows wrong pp value. It also showed the wrong value in top scores on my profile page at first, but i didnt capture it. Ive seen this bug a couple of times and its always 1 lower or greater than the actual value of pp given for the play.

### Screenshots or videos

https://youtu.be/FalS--ZsdCk

### Version

2024.221.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14469452/compressed-logs.zip)

**Comment by frenzibyte** [comment]
That happens when the web is behind on PP calculation algorithm updates. This has been reported multiple times before (most recently https://github.com/ppy/osu/issues/27368), perhaps we could add some sort of an indicator to make it clear to the user that the viewed PP is sourced from online and may not be up to date? cc @peppy

**Comment by frenzibyte** [comment]
Right, I missed that part. Let's track this in https://github.com/ppy/osu/issues/25405 for now. I'm not really sure about the circumstances at which PP become different between web and lazer, so I'll disregard the point I made above and leave it for later.
