### ISSUE TITLE
Negative OD breaks spinners

### ISSUE THREAD

**Issue by Stoppedpuma** [ppy/osu#27536]
### Type

Game behaviour

### Bug description

Found while testing #27526

These are the results I got when testing with auto at 1:42 on the map in the video.

-6.3 Last time the spinner works correctly
-6.4 Auto doesn't spin, bar spinner meter is missing, no miss happens
-8.7 auto spins again, fill meters completely broken, maxes out spinner, misses

These results are not consistent with the rest of the spinners in the map as tested with the spinner at 0:40 from the same map.

-5.5 Last time the spinner works correctly
-5.6 Auto doesn't spin, bar spinner meter is missing, no score or max, no miss happens
-9.5 Auto spins again, fill meters completely broken, maxes out spinner, misses

These results happen with both auto and by just playing normally

### Screenshots or videos

https://github.com/ppy/osu/assets/58333920/c40a3e05-1342-4d51-a990-0eca5dbb278c

### Version

master

### Logs

.

**Comment by bdach** [comment]
This is an invalid issue because *we do not support negative OD at this time*. We support negative *AR*.

The fact that you want to implement this does not make it an issue. It makes it *your problem if you want to implement it*.

Nevertheless the problem would be here:

https://github.com/ppy/osu/blob/5d40fdca867db2e75348624f915d126dbb0cd6aa/osu.Game.Rulesets.Osu/Objects/Spinner.cs#L76

The behaviour needs to be defined if negative OD is to be supported. But again, _it currently isn't, so this is not an issue._

**Comment by Stoppedpuma** [comment]
> we do not support negative OD

Easy + Halftime makes negative OD possible

![osu_2024-03-08_22-43-34](https://github.com/ppy/osu/assets/58333920/e11f974c-87ee-45f5-b190-28d2860fa14e)

**Comment by bdach** [comment]
No it doesn't, because that's "effective OD" on that screen there. And either way an OD of -3 still wouldn't cause this problem.
