### ISSUE TITLE
'I Can See The Top' medal not awarded

### ISSUE THREAD

**Issue by Kruchji** [ppy/osu#27581]
### Type

Game behaviour

### Bug description

I am in the top 50k in Catch ([profile](https://osu.ppy.sh/users/11397889/fruits)) with pp from Lazer counted. But even using the new release this medal is not awarded. (May be related to https://github.com/ppy/osu-web/issues/10937 as Highest rank shows above 50k)

### Screenshots or videos

![top_medal](https://github.com/ppy/osu/assets/32173730/862206fd-6e26-4fca-bbcd-4376c0a358fc)
![top_medal2](https://github.com/ppy/osu/assets/32173730/29d5cc60-0a31-4f17-87ae-f8267d885a10)

### Version

2024.312.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14565663/compressed-logs.zip)

**Comment by BlockHead007** [comment]
My guess is that for now only stable rank counts for these medals. We should wait until lazer pp are fully merged with stable so there will be no difference between them. Try to set a few more scores, then go back to stable, set a score here and look if your rank will be above 50k and you'll get a medal. But I think for now lazer scores are still lazer only, so stable doesn't count them and that's why you didn't get that medal because for it you are still below 50k.
