### ISSUE TITLE
Switching gamemodes on a song which is not inteded to be played on another mode causes a crash

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#2788]
[runtime.log](https://github.com/ppy/osu/files/2096157/runtime.log)

**Comment by peppy** [comment]
Can you explain the process you're taking to reproduce this?

**Comment by Lolihunter1337** [comment]
i recorded a video with the steps. probaly easier to explain. Streamable did not work for so i hope youtube is fine. https://youtu.be/ObcEhIh5dvg

**Comment by jaysc** [comment]
Took a look at this:

Wasn't able to replicate it when changing songs like the video until i turned hard mod on.

Was able to replcate it majority of the time when selecting hard mod on osu, closed the mod menu fully, then switch to taiko.

I believe the problem is due to when `GetPlayableBeatmap` is ran and `mod.ApplyToHitObject(obj);` is hit since `Mods` still contain the hard mod, causing the error:
`'Unable to cast object of type 'osu.Game.Rulesets.Taiko.Objects.RimHit' to type 'osu.Game.Rulesets.Osu.Objects.OsuHitObject'.'` on `OsuModHardRock.cs`

I say sometimes the error occurs since the `Mods` gets cleared down somwhere and I can't figure out where.

**Comment by peppy** [comment]
Should probably be resolved already. Please re-test.

**Comment by Lolihunter1337** [comment]
works fine for me

**Comment by Lolihunter1337** [comment]
ok nevermind. it does *not*

**Comment by peppy** [comment]
Marking as duplicate of #2847.
