### ISSUE TITLE
Storyboard elements appear over playfield

### ISSUE THREAD

**Issue by AnicJov** [ppy/osu#27953]
### Type

Game behaviour

### Bug description

While playing the [following](https://osu.ppy.sh/beatmapsets/2015361#mania/4467782) 5k mania map I noticed that some storyboard elements were displaying above (in front) of the playfield. This is clearly visible around the 1:00 mark of the song.

I'm attaching videos of the issue, and leaving the full recordings [here](https://www.youtube.com/watch?v=m_x081MpX8o) and [here](https://www.youtube.com/watch?v=RyfsEctoURk).

I could reproduce the issue with any skin, including the default Argon one.

This is the only map I've noticed this on, and I have no way of checking if this is the same behavior as stable but I'm assuming that it's not intended.

### Screenshots or videos

https://github.com/ppy/osu/assets/25593018/f03b3971-2dfa-4f3b-9e2c-3a1358a4f784
https://github.com/ppy/osu/assets/25593018/0cb4dbc6-aa22-4b23-95a7-7b7b0c6c2b67

### Version

2024.412.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15049933/compressed-logs.zip)

**Comment by Joehuu** [comment]
Stable also has this. The feature is relatively recent (2019), see https://www.reddit.com/r/osugame/comments/cn60bm/latest_osucuttingedge_update_adds_a_new/, so that is why it's rare to find maps with it. It's already rare to find a beatmap with a storyboard.

It's not even documented in the wiki: https://osu.ppy.sh/wiki/en/Storyboard/Scripting/General_Rules#layers. Will make an issue for that.

**Comment by AnicJov** [comment]
I see! Didn't realize this was a thing, thanks for the info.
