### ISSUE TITLE
Localization for Multiplayer not applied correctly

### ISSUE THREAD

**Issue by Pigeon0v0** [ppy/osu#28007]
### Type

Game behaviour

### Bug description

Go to multiplayer in osu game and then find that the localization is not applied correctly. 

I have checked (Crowdin)[https://crowdin.com/project/osu-web] and the dashboard says Chinese Simplified is actually 100% translated, but in the game it does not display the localized text. I have also checked some other languages and its behaviour is like before. 

In addition, my system version is Windows 11 23H2 Build 22635.3495 with system language set to Chinese Simplified. 

### Screenshots or videos

![Multiplayer 1](https://github.com/ppy/osu/assets/60414767/42b25bc0-3538-4258-a8f1-f1496b289c86)
![Multiplayer 2](https://github.com/ppy/osu/assets/60414767/14f4b715-bd25-4bda-a494-d20ad42469ff)

### Version

2024.412.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15132075/compressed-logs.zip)

**Comment by bdach** [comment]
The screen does not currently support localisation in any language. This is not a question of "application".

The reason why crowdin says "100% translated" is because all _available_ strings have been translated. If a screen doesn't support localisation, its strings just won't exist on crowdin.

I don't see a reason for this issue to specifically remain open as multiplayer is not the only screen that does not have full localisation support.
