### ISSUE TITLE
Opening the overall offset adjustment does not close during loading.

### ISSUE THREAD

**Issue by shiumano** [ppy/osu#28187]
### Type

Performance

### Bug description

Play the beat map once without ever opening the settings screen.
Click the Adjust Global Offset button from the retry screen, the operation will stop while the settings are loaded.
If you opened the settings in the normal way, you can close it even while it is loading.

### Screenshots or videos

problem behavior

https://github.com/ppy/osu/assets/75152752/d286a56d-dede-4e85-810d-18f984a29386

normal behavior

https://github.com/ppy/osu/assets/75152752/0e2b5581-a1bf-4d1b-98ed-e63630d471b3

### Version

2024.412.1

### Logs

[logs.zip](https://github.com/ppy/osu/files/15331257/logs.zip)

**Comment by bdach** [comment]
The actual issue is that the settings overlay shouldn't be lagging this much during loading to begin with. I believe the "difference in behaviour" on the videos above to be incidental and/or irrelevant. If the settings overlay loaded properly this would not be an issue.

Probably something better addressed by https://github.com/ppy/osu/issues/5715 or similar.
