### ISSUE TITLE
Multi-finger input may block input

### ISSUE THREAD

**Issue by Jan-Arbus** [ppy/osu#28211]
### Type

Game behaviour

### Bug description

Use two fingers to input at the same time, and pay attention to the cursor. If the cursor is still in the pressed state after releasing the finger, it means that it is successfully triggered. This greatly affects the gameplay of mania
The attached video is the most extreme case, the input will be completely blocked
The game runs on Android

### Screenshots or videos

https://github.com/ppy/osu/assets/74862110/2b361592-68c4-4e26-ac5f-2f77bcd8ce61

### Version

2024.519-

### Logs

N/A

**Comment by bdach** [comment]
My main question is why do you have a mouse pointer on android? If you're using touch you should not be seeing mouse pointers. Are you playing with a mouse? What device is this being played on?

**Comment by Jan-Arbus** [comment]
>My main question is why do you have a mouse pointer on android? If you're using touch you should not be seeing mouse pointers. Are you playing with a mouse?

Just turn on "Show gameplay cursor during touch input" in settings
>What device is this being played on?

I'm playing on my xiaomi pad 5 pro. I tried it in my other android and it can trigger this issue too

**Comment by Susko3** [comment]
From your video, the issue seems to be related to touching three fingers at the same time.
- Are you able to reproduce it on the main menu as well?
- Please mention all devices you can trigger this issue on.
- Try disabling any global three-finger gestures provided by your device (they are usually gestures for taking a screenshot)
- Try disabling game mode (this sometimes, ironically, causes issues with input in games)
- Try to reproduce the issue in a more controlled way, try to see _how_ you need to tap to cause the issue. Use the No fail mod if it only happens in gameplay.

**Comment by MATRIX-feather** [comment]
Same issue here.

* The main menu seems to also have this issue.
* Device is Xiaomi Pad 6 Pro
* Most gestures are disabled, except several that don't have a toggle.
* Disabling game mode doesn't help.
* Normally tapping with >= 2 fingers would cause the issue.

![未命名](https://github.com/ppy/osu/assets/55654482/4c164441-a32e-40c1-81a5-350ddacf54d7)

**Comment by Susko3** [comment]
- Fixed upstream in https://github.com/libsdl-org/SDL/pull/9842
