### ISSUE TITLE
Different results before and after replay

### ISSUE THREAD

**Issue by AmerusTheMan** [ppy/osu#28231]
### Type

Game behaviour

### Bug description

I have not seen any other maps where this has happend, but on the map "Deadlocked", mapped by walter85, My score on the leaderboard is way to low. When i press in on the play from the leaderboard, the score is 85,301. And after i finnish the replay, the score is 240,100. Some other stats have also changed like accuracy, combo and slider tick.

### Screenshots or videos

Before replay:
![image_2024-05-19_152000722](https://github.com/ppy/osu/assets/166036637/37e703b0-1679-4b5f-9f20-5d688d1a7518)

After replay:
![image_2024-05-19_151902597](https://github.com/ppy/osu/assets/166036637/8206c8a8-f775-4109-99e7-2a08235e1329)

### Version

2024.519.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15369545/compressed-logs.zip)

**Comment by DarkbitNetwork** [comment]
If I recall correctly, old replays set before 2023.1218.0 weren't migrated to the new scoring system. This could explain why your score is much higher after the replay than before it.

Accuracy changes might be because of #11311 mainly because lazer gameplay and lazer replay handle hit windows differently.

Also, the result before the replay is missing the slider end counter because of #25342 (both slider ticks and slider ends are included in the slider tick counter).

**Comment by bdach** [comment]
The above is roughly correct. We do not put in effort to support lazer scores set before pp went live, sorry. Too much work for too little gain.
