### ISSUE TITLE
Change default keyboard layout in osu!standard

### ISSUE THREAD

**Issue by MikelJohnson** [ppy/osu#2824]
This is proposal to change default mapping to 'A' and 'S'. There are few reason to do this:
1. The default keys in taiko and mania are already on second row in QWERTY keyboards. This would bring consistency to the default keyboard layout.
2. There are few keyboards that have "special" faster WASD keys.

Although this change may be disruptive to current player, it may help newcomers that either have "special" faster WASD keys and cause less confusion in figuring out layout in other gamemodes.

**Comment by peppy** [comment]
I cannot disagree with this one, for both of the reasons stated.

**Comment by LastExceed** [comment]
Another reason would be users with a non-QWERTY keyboard not being forced to change their layout anymore.
E.g. on a german keyboard (QWERTZ) XZ is unplayable as they're very far apart and in different rows.

I suggest SD instead of AS to be the new default though to prevent conflict with french keyboards (AZERTY) while we're at it.

**Comment by peppy** [comment]
Yes, that's one of the main reasons to do this.

**Comment by jorolf** [comment]
Not sure if anyone actually ever tested this but lazer uses the physical key. So XZ maps to XY on a german keyboard

**Comment by peppy** [comment]
That raises a larger issue (it is actually incorrect behavior) and should be fixed as a separate issue.
