### ISSUE TITLE
Ln visual bug on Android

### ISSUE THREAD

**Issue by Nawle-0** [ppy/osu#28379]
### Type

Game behaviour

### Bug description

Hi. I recently installed osu!lazer on Android and noticed a quite annoying visual bug.
It seems that certain skins have a visual bug with the LNs and only show the final tail of the LN (and also the note), making maps that have LNs completely unplayable.
(I used the skin of myuka cinnamoroll)

Android 14 QPR2
AP1A.240405.002.A1

### Screenshots or videos

https://github.com/ppy/osu/assets/170393222/0a9e5309-474f-4b26-b52d-5eed59d4b7dc

### Version

2024.521.2

### Logs

[1717311545.runtime.log](https://github.com/user-attachments/files/15524429/1717311545.runtime.log)
[1717311545.network.log](https://github.com/user-attachments/files/15524430/1717311545.network.log)
[1717311545.input.log](https://github.com/user-attachments/files/15524431/1717311545.input.log)
[1717311545.auth.log](https://github.com/user-attachments/files/15524432/1717311545.auth.log)
[1717311545.performance.log](https://github.com/user-attachments/files/15524433/1717311545.performance.log)

**Comment by Nawle-0** [comment]
Apparently I got confused and only the note appears...

**Comment by Nawle-0** [comment]
That was a missclick

**Comment by longnguyen2004** [comment]
Please provide the skin file

From my guess, I'm pretty sure this is due to the use of "percy" LNs (aka "cut" LNs, aka LNs that look shorter than they actually are). These skins abuse super large textures (30000+px) to make the visual length of the LN shorter. These aren't fully supported in lazer (and probably will never be, due to their hacky nature).

I have [a PR](https://github.com/ppy/osu/pull/27726) pending that will provide a better way to achieve the same result without super large textures.

**Comment by Nawle-0** [comment]
Yes, it seems that the LN Tail is 40000px
[myu skin (cinnamoroll).zip](https://github.com/user-attachments/files/15525911/myu.skin.cinnamoroll.zip)

Thanks!

**Comment by bdach** [comment]
Closing as duplicate / known issue / unsupported for now
