### ISSUE TITLE
Exporting beatmaps into osu!stable pushes out-of-bounds objects back into the playfield

### ISSUE THREAD

**Issue by nikunaku** [ppy/osu#28417]
### Type

Game behaviour

### Bug description

**Recreating the issue:**
1. Create a beatmap (don't edit an existing one) and add an out-of-bounds object(s)
2. Export it to .osz
3. Open the .osz in osu!(stable)

The result being all out-of-bounds objects getting pushed back into the playfield.
Importing the .osz into lazer however, places the hit objects as is.

### Screenshots or videos

Beatmap in lazer editor: (expected)
![osu_2024-06-07_09-32-00](https://github.com/ppy/osu/assets/166950173/e6c4f536-c764-45ff-b7ed-850bd5257a50)

Beatmap exported into stable:
![screenshot001](https://github.com/ppy/osu/assets/166950173/785a704c-b477-4cc3-af76-e9365bba58a0)

### Version

2024.521.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15688480/compressed-logs.zip)

**Comment by bdach** [comment]
Not sure how to even to respond to this because I'm not sure what's correct.

You could say that the bug is being able to _place_ objects outside of the playfield in lazer, which is fixable her. Or you could say that stable is wrong for clamping, which is not fixable here and would need to go live in https://github.com/ppy/osu-stable-issues (and possibly not get fixed because stable feature lock).

**Comment by nikunaku** [comment]
I'm talking about the latter.

I opened the issue here since I came to the conclusion that the resulting .osz contained some metadata that told stable, but not lazer, to clamp object positions. (which seems to be wrong, and in hindsight kind of nonsensical)

I'll see how I can open an issue on that page,

**Comment by nikunaku** [comment]
I'm talking about the latter.
I opened the issue here since I assumed this was a problem with how lazer exported .osz files, but that doesn't seem to be the case.
