### ISSUE TITLE
Taiko Constant Speed mod can change base scroll speed for map

### ISSUE THREAD

**Issue by JamieWright99** [ppy/osu#28566]
### Type

Game behaviour

### Bug description

I found a few Taiko songs where enabling Constant Speed will make the scroll speed faster, even though the maps use 1x SV value throughout the map. Here's some ones I found:

https://osu.ppy.sh/beatmapsets/31061#taiko/102998
https://osu.ppy.sh/beatmapsets/29226#taiko/99153
https://osu.ppy.sh/beatmapsets/28063#taiko/112935

The video shows what I mean, bottom has Constant Speed enabled.

### Screenshots or videos

https://github.com/ppy/osu/assets/102170503/f4d7a778-f100-4ed0-93db-4cde7b8df310

### Version

2024.625.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15966502/compressed-logs.zip)

**Comment by smoogipoo** [comment]
Isn't this intentional, because constant speed is otherwise too slow?

https://github.com/ppy/osu/blob/3d6a9ccb6d8e2ed270ca45a97ed5a0fa18e9781f/osu.Game.Rulesets.Taiko/UI/DrawableTaikoRuleset.cs#L85-L90

**Comment by bdach** [comment]
@Hiviexd maybe you can provide some insight here

**Comment by smoogipoo** [comment]
Well, the actual multiplier itself was added by me and @peppy in https://github.com/ppy/osu/pull/24550 . The implementation above only moved it to a more base level. But I remember there being maps that were indeed "sluggish" with constant mod, hence the multiplier.

**Comment by XeZey** [comment]
Im not sure what is meant by "sluggish". It is true that especially on lower bpm maps, the scrolling is rather slow, (due to 1/4 spacing being the way it is) but this is kind of just part of how taiko scrolling works. Mappers will intentionally adjust scroll speed to be higher on low bpm maps for more difficult maps, especially if the map is really dense despite low bpm (constant usage of 1/8 patterns for example). However, as a default, having a difference in scrolling speed across beatmaps for readability sake seems really weird. Taiko players are used to having "spacing" and not "speed" be an important factor for readability. Even if a map was 50 bpm, as long as the map only uses 1/4 spacing and doesnt try to do some weird 1/16 in order to map quasi 200bpm patterns, that scroll speed would be perfectly readable for taiko players and it would not feel off at all.
If anything, another way to address this would be to add a scroll speed adjustment to this mods settings, which could however already be done via the "difficulty adjust" mod. This would still be more intuitive and imo just strictly better than having this mod try to adjust for "sluggish" scrolling by itself.

**Comment by Firmatorenio** [comment]
It would seem on a map that is entirely at base scroll speed (aka with no modifications to scroll speed on its timing points), the applied multiplier ends up being roughly 1.35x, which would be almost on par with adding HR on 4:3 on stable. Needless to say, that is _a lot._ I tried recommending trying this mod to a muzukashii player friend who was struggling to beat a certain map because it would change the scroll speed to a significantly faster one which they couldn't read, and this mod only made everything worse because now they couldn't read the entire map.

The mod's expected behavior for me would be one of the following scenarios:
a) all the timing point modifications to the map's scroll speed are removed (but its base 'slider velocity', which on most maps is set to 1.4, is kept);
b) all the timing point modifications to the map's scroll speed are removed _and_ its slider velocity multiplier is set to 1.4;
c) a customization slider is provided for the constant speed the player wants, with the scenario (b) as a default.

The last case admittedly reminds me of the conversation of potentially splitting Difficulty Adjust into separate mods for each modifiable stat, as this could be the mod to modify the scroll speed of a map in general (something currently done by DA) that would also have an extra toggle to make the set speed constant rather than applied as a multiplier to everything.

**Comment by Hiviexd** [comment]
> a) all the timing point modifications to the map's scroll speed are removed and its slider velocity multiplier is set to 1.4 (aka bring it to the default for the bpm) - this keeps changing scroll speed on bpm changes, but in an expected way;

this was the original intention of the mod. initially I handled it on a beatmap level via equalizing all effect points' scroll speed to 1x,but then I switched to toggling the visualisation method as that's much simpler. would be ideal if we adjust the latter to be dependent on the map's BPM.

> d) a customization slider is provided for the constant speed the player wants, with the most used bpm as a default.

technically users can use Constant Speed with Difficulty Adjust's scroll speed customization, which is... suboptimal at best, especially that the numbers involving the process feel a bit too arbitrary to players (they don't know the scroll speed BPM at a glance, and DA's scroll speed adjustment applies a multiplier on top of that), which makes it harder for them to set up their exact preferences intuitively.
