### ISSUE TITLE
"Processing beatmap's headers failed. This map is likely corrupt!" when importing osu!lazer mapped .osz to stable

### ISSUE THREAD

**Issue by Dika312** [ppy/osu#28607]
### Type

Other

### Bug description

I was applying a mod on osu!lazer to change some patterns and when that is done I import to stable to see this error, I did the same thing yesterday and there was no issue. (thank god it didn't during CWC custom rush)

Also note that the HS diff I didn't change anything and that diff is not corrupted.

I'll add the map's .osz and .olz file here for examination
[Risa Yuzuki - Yumemiru Milky Way feat. Aitsuki Nakuru (Dika312).zip](https://github.com/user-attachments/files/15983290/Risa.Yuzuki.-.Yumemiru.Milky.Way.feat.Aitsuki.Nakuru.Dika312.zip)

### Screenshots or videos

https://github.com/ppy/osu/assets/173878925/8faefa58-ecea-4b1f-9de2-71ec35c0fd5c

### Version

2024.652.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15983392/compressed-logs.zip)

**Comment by smoogipoo** [comment]
I was going to fix this one, but it might need more consideration because this affects mania beatmap conversion:

https://github.com/ppy/osu/blob/173c4f430ac17f3750a849790978496eed8d9603/osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/PatternGenerator.cs#L92-L114

Basically:
- Stable parses as ints.
- Lazer parses (and encodes) as doubles.

Although it's unlikely for a 1ms difference to make a difference in conversion, it's one of those "there's bound to be some edge case somewhere" sort of scenarios.

So either we have to make stable use doubles for event times and everything involved, or make lazer use integer-based break times. The lazer path may be the easiest. This is also likely relevant for @bdach given the recent break work in the editor.

**Comment by bdach** [comment]
From your description I'm not sure what the problem is, is it that the breaks have a fractional time? 

If it is that, then can't we mirror what is already done with control points, eg. truncate on legacy export?:

https://github.com/ppy/osu/blob/master/osu.Game%2FDatabase%2FLegacyBeatmapExporter.cs#L63

**Comment by smoogipoo** [comment]
I guess I don't see anything particularly wrong with that.
