### ISSUE TITLE
Dialogs with dangerous buttons don't have pop in/out and button sounds

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#28688]
### Type

Game behaviour

### Bug description

Noticed something was off with dialogs when coming back to contribute. Regressed since https://github.com/ppy/osu/pull/28652.

### Screenshots or videos

https://github.com/ppy/osu/assets/35318437/7cbfb8ea-668a-4937-be48-ec4deed7d898

### Version

master (since https://github.com/ppy/osu/pull/28652)

### Logs

N/A

**Comment by smoogipoo** [comment]
Hmm... This thing never worked properly in the first place so now these issues are coming up. Basically the cutoff is applied to the global sample mixer, which the pop in/out sounds are part of.

This also results in some weird layering and/or audio clicking for me when you hold the button and close the dialog at the same time.

Not sure how to fix immediately.

**Comment by smoogipoo** [comment]
@nekodex Perhaps you have a better idea how the low pass filter on these dialogs is intended to be used/applied?

Do we need to put the samples played here outside the global `SampleMixer` so that they're not affected by the low pass applied at the same time?

**Comment by nekodex** [comment]
I _think_ my original intention was for the filter effect to apply to both the looping sample for `DangerousButton` filling up (in a creative "filter opening up" manner), in addition to filtering any hitsounds played by the editor when the dialog is triggered during playback (to match the music being filtered).

As you say, this never worked (and I intended to remove it as part of #28547 anyway), so that may coincidentally fix this issue. Although the removal leaves us with hitsounds played by the editor not being filtered when the dialog is shown, which feels a bit odd. This is potentially fixable by using seperate mixers for UI SFX and gameplay/hitsounds, which is kinda similar to what you suggested?

My cursory investigation into what would be involved to do that suggested it's currently non-trivial to route samples to a different mixers at the moment, so I never got around to digging into it much further.

**Comment by smoogipoo** [comment]
> This is potentially fixable by using seperate mixers for UI SFX and gameplay/hitsounds, which is kinda similar to what you suggested?

Yeah, that's sort of the direction I was suggesting. The alternative is that it should be at an `OsuScreen` level, i.e. apply the mixer to the entire content _behind_ the dialog overlay? It might be simple to just add a `DrawableAudioMixer` into the hierarchy there.

Should we revert #28652 for now?
