### ISSUE TITLE
Select osu!mania difficulty increasing mods lowering stars (osu!lazer)

### ISSUE THREAD

**Issue by whamer100** [ppy/osu#28687]
### Type

Game behaviour

### Bug description

This doesn't feel intentional, but in the mods for osu!mania the four mods that affect notes/view area (Fade In, Hidden, Cover, and Flashlight) all lower the star count despite being difficulty increasing mods. And additionally, Cover is unranked (but this might just be something I never noticed).

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/10352720/ab1f09c1-e87f-4f1c-ae0d-da26fffec2a8)
![image](https://github.com/ppy/osu/assets/10352720/bea60203-3f59-4852-96af-d506a014cb21)
![image](https://github.com/ppy/osu/assets/10352720/e8650432-6e8f-404c-80f1-0b4a7c309c67)

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16047261/compressed-logs.zip)

**Comment by smoogipoo** [comment]
Can't repro, even on the map you selected: https://osu.ppy.sh/beatmapsets/1470790#osu/3023028

It doesn't even make sense because the mods aren't referenced anywhere in diffcalc.

**Comment by whamer100** [comment]
Ok now this is bizarre, I'm now unable to reproduce it trying to go back to the mods. I'm going to retrace my steps and see if I can cause it again.

**Comment by smoogipoo** [comment]
Weird. I managed to reproduce in a different scenario that also doesn't make sense. Will investigate further.

**Comment by whamer100** [comment]
What did you do to reproduce it?

**Comment by smoogipoo** [comment]
Just keep selecting mods. It'll happen at random with mods that shouldn't change difficulty at all. It's looking to be a data race between the game-wide mods bindable being an `IReadOnlyList<>` (i.e. technically mutable because `List<>` is an `IReadOnlyList<>`), and diffcalc using `IEnumerable<Mod>` on top of that so there's no strict guarantee of immutability, all the while things are being passed between async threads etc.
