### ISSUE TITLE
Storyboard positioning is slightly wrong compared to stable

### ISSUE THREAD

**Issue by MrHeliX** [ppy/osu#28861]
### Type

Game behaviour

### Bug description

Best shown with an example:

Beatmap: https://osu.ppy.sh/beatmapsets/1790039#osu/3667879
Timestamp: around 18788

Lazer behaviour: 
![osu_2024-07-14_15-48-13](https://github.com/user-attachments/assets/71325247-076f-4d29-b44a-f5935dfc5410)

Stable behaviour (expected):
![screenshot1900](https://github.com/user-attachments/assets/f4eb20d2-e75b-45e6-9b31-f6c4c2697ea3)

These are two square elements with anchors CentreLeft and CentreRight and both set at position 320,240 (the middle of the screen). The gap that is visible in Lazer should not exist.
Storyboard code for these elements:
```
Sprite,Overlay,CentreRight,"sb\square.png",320,240
 C,0,15112,,0,0,0,213,174,88
 V,0,15112,,0,0,0,10
 V,2,15112,16112,0,10,15,10
 F,0,23445,,1,0
Sprite,Overlay,CentreLeft,"sb\square.png",320,240
 C,0,15112,,0,0,0,213,174,88
 V,0,15112,,0,0,0,10
 V,2,15112,16112,0,10,15,10
 F,0,23445,,1,0
```

Another example if it helps:

Beatmap: https://osu.ppy.sh/beatmapsets/1485845#osu/3046792
Timestamp: around 107495

Lazer: 
![osu_2024-07-14_15-48-52](https://github.com/user-attachments/assets/8368b279-5dc7-43f6-a0c4-07a6114c19f1)

Stable:
![screenshot1899](https://github.com/user-attachments/assets/d7ff7f4d-6407-4042-abb9-df5ba8517a85)

These are two rectangles sliding from the top and bottom of the screen to meet in the middle. In stable they connect perfectly, in Lazer they leave a gap.

Storyboard code:
```
Sprite,Overlay,BottomCentre,"sb\square.png",320,-100
 F,0,106468,,0,1
 C,0,106468,,0,0,0,224,74,61
 V,0,106468,,0,0,20,10
 MY,1,106879,107290,-100,240
 F,0,107691,,1,0
Sprite,Overlay,TopCentre,"sb\square.png",320,580
 F,0,106468,,0,1
 C,0,106468,,0,0,0,224,74,61
 V,0,106468,,0,0,20,10
 MY,1,106879,107290,580,240
 F,0,107691,,1,0
```

I'm playing both Lazer and stable in fullscreen, UI scaling is set at 1 and screen scaling is turned off.

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16227722/compressed-logs.zip)

**Comment by frenzibyte** [comment]
I am running on 2024.625.2 and I cannot seem to repro any of the issues you brought up. Both examples align just fine on my end, contrary to your screenshots:

https://github.com/user-attachments/assets/181ce0dd-9d0f-489c-8185-60c7668c0a85

**Comment by cihe13375** [comment]
I tested on my own pc and it seems that the issue appears only when the "beatmap skins" is enabled.

**Comment by tadatomix** [comment]
> I tested on my own pc and it seems that the issue appears only when the "beatmap skins" setting is enabled.

After I tested on MrHeliX's beatmaps, I can agree. For some reason, this setting, quoted above, is messing up bounds of sprites. When, usually, bounds of sprites are scaled notmally, without leaving blurred parts, lazer, for some reason, adds blur to them. 

For whatever reason, I was unable to replicate that bug, using lines from MrHeliX code and sprites from those beatmaps. But, after I changed MrHeliX's square sprite to 1x1 white pixel file, problem left and was even more visible.


![osu!_EY0WKEekps](https://github.com/user-attachments/assets/f0b3b25a-21fb-4e99-a883-af9805c91ce6)
Here's how sprite looks like in osu!stable. As we can see it's a normal square without any blurry sides

![osu!_6K8Vw1xo51](https://github.com/user-attachments/assets/c11969bd-0213-4c50-bfa2-96cc7e175cd2)
Now here's the same sprite in osu!lazer. Every side is blurry, what makes it lookin more like a star, instead of square.

That's what MrHeliX tried to show. Sprites, like this one, are scaling incorrectly in their beatmap, leaving those gaps, as we can see in screenshots, presented by them. I dunno why it works only in case with their beatmaps and only when the "beatmap skins" setting is enabled, but truth is truth. This bug actually exists

**Comment by peppy** [comment]
> I tested on my own pc and it seems that the issue appears only when the "beatmap skins" setting is enabled.

Which skin are you using? Did you actually reproduce this without CHANGING storyboard sprites? Because I can't discern that from your reply.

**Comment by tadatomix** [comment]
> > I tested on my own pc and it seems that the issue appears only when the "beatmap skins" setting is enabled.
> 
> Which skin are you using? Did you actually reproduce this without CHANGING storyboard sprites? Because I can't discern that from your reply.

Okay, my bad for changing sprites. Thought, in that case, issue will be more visible. 

Yes, without changing any storyboard sprites, on any skin, this issue is the same as on MrHeliX's screenshots, when you have "Beatmap skins" setting on. So like on the images bellow:
![osu!_GQt6hbxSL8](https://github.com/user-attachments/assets/5f002a4c-ee16-4dbe-95ba-c8b83dcfca25)
Custom legacy skin
![osu!_NsD9NYXxaz](https://github.com/user-attachments/assets/3c626138-2611-4ff2-8df1-a98f4fdacea4)
Default legacy skin
![osu!_CJ1JYskqRF](https://github.com/user-attachments/assets/14f92cc0-2939-4aa8-b995-7a48569659ae)
Argon

After you turning off this setting, everything goes back to normal state, like in stable. So like on the images bellow
![osu!_Zt76gbUI9p](https://github.com/user-attachments/assets/5596a4df-0bfd-482d-872c-7601e467561f)
Custom legacy skin
![osu!_LoHKGpses1](https://github.com/user-attachments/assets/e5ba6422-27d7-4618-ad42-c7c833941314)
Default legacy skin
![osu!_SnGgNncX2D](https://github.com/user-attachments/assets/33de05fb-b913-4480-bfb7-fd6517a91eab)
Argon

**Comment by tadatomix** [comment]
I think it might somehow be related to the custom skin MrHeliX have on their beatmaps, since, after turning off that setting, everything fixes

**Comment by tadatomix** [comment]
Also, on [frenzibyte's](https://github.com/frenzibyte) video, this bug isn't shows, since they have "Beatmap skins" setting off, as we can see on this screenshot
![U8J54se5RN](https://github.com/user-attachments/assets/4356c513-d954-4280-afc0-7972ccb2b54d)

**Comment by cihe13375** [comment]
> > I tested on my own pc and it seems that the issue appears only when the "beatmap skins" setting is enabled.
> 
> Which skin are you using? Did you actually reproduce this without CHANGING storyboard sprites? Because I can't discern that from your reply.

I tested with two maps MrHeliX linked in the first post, without any changes. I tried setting system-wide skin to either argon or a custom skin, and the issue appears as long as the "beatmap skins" setting is enabled. Basically my observation is same as tadatomix's second post (https://github.com/ppy/osu/issues/28861#issuecomment-2230138828)
