### ISSUE TITLE
Alt F4 in-map brings up pause menu, then quit the game on second trigger

### ISSUE THREAD

**Issue by PythonTryHard** [ppy/osu#2887]
Like the title said. Since I'm familiar with Alt F4 directly quitting to map selection, this throws me off my habits. Except, Alt F4 the secons time at pause exits.

Edit: Also Alt F4 quits the game at autoplay

**Comment by peppy** [comment]
alt-f4 should generally quit on first keypress going forward, bypassing the pause screen.

we may want to add an exit keybinding that bypasses the pause screen if this is a common use case.

**Comment by LastExceed** [comment]
In stable, alt+f4 has 2 different functions depending on the current screen. I'll refer to them as "quickescape" and "ragequit". 

quickescape is when you press alt+f4 while in a beatmap or loading screen before a beatmap. It is used to either cancel beatmap loading without the need to wait until loading finished, or quickly exit a beatmap without going to the pause screen, saving half a second and an input (alt+f4 instead of esc->arrowUP->enter).

ragequit is when you use alt+f4 anywhere but during gameplay (e.g. song selection) to do what alt+f4 usually does in most programs: close the window and quit the game as quickly as possible.

lazer should either do the same as stable currently does, or in case we want to be able to ragequit from gameplay without pressing alt+f4 a second time, we should implement a new hotkey for quickescape.

**Comment by peppy** [comment]
in lazer, alt-f4 will be an instant quit, as per other applications.

**Comment by Joehuu** [comment]
Regressed in https://github.com/ppy/osu/pull/6992.

**Comment by peppy** [comment]
Can you state the regressed behaviour, since this has been through multiple states.

**Comment by Joehuu** [comment]
<kbd>ALT</kbd> + <kbd>F4</kbd> makes you go to the pause menu during gameplay again. It should bypass that and go to the main menu's exit dialog.

![cQihgsx6MC](https://user-images.githubusercontent.com/35318437/83369354-e57c1380-a370-11ea-8f6e-d95555d70d78.gif)
