### ISSUE TITLE
Beatmap export turns symbols into Underscores in filename

### ISSUE THREAD

**Issue by aL1NaZ4R** [ppy/osu#29003]
### Type

Other

### Bug description

Hi. Exporting beatmap in lazer editor, causes the special symbols to turn into Underscores, which is different behavior compared to osu stable exports.
![image](https://github.com/user-attachments/assets/8ec63601-20cf-4834-affc-4e2f774ab1eb)

The "Insane" one is the same, because I didn't touch it in lazer editor.

### Version

2024.718.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16336747/compressed-logs.zip)

**Comment by aL1NaZ4R** [comment]
Also it's still un-importable, despite #28609

**Comment by aL1NaZ4R** [comment]
> Also it's still un-importable, despite #28609
Wait wait wait wait! It's working pretty good while exporting, my bad, BUT it has the same issue as before when you use the new option "Edit externally"

**Comment by bdach** [comment]
This is intentional because stable only supported windows; with native support for multiple platforms the list of valid characters in a filename gets narrower.

https://github.com/ppy/osu/blob/7e5fda45396ce7823a7b5e63c7204c9ceafd184c/osu.Game/Extensions/ModelExtensions.cs#L158-L166

This will not be changing because you really shouldn't care about what this filename is.

**Comment by aL1NaZ4R** [comment]
> Also it's still un-importable, despite #28609
> it has the same issue as before when you use the new option "Edit externally"

Should I make another issue about this one?

**Comment by bdach** [comment]
> Should I make another issue about this one?

I'm not even sure what you're exactly trying to say with that one, so probably?
