### ISSUE TITLE
Barrel Roll mod won't change visual Circle Size stat

### ISSUE THREAD

**Issue by SHOESKE-H** [ppy/osu#29155]
### Type

Cosmetic

### Bug description

When enabling the Barrel Roll mod, the visual Circle Size stat on every visual showing CS won't change to the new CS value.
Note that it's not a visual update issue. The CS change from BR mod is just completely ignored and not accounted for, even after updating the visual manually using Difficulty Adjust, etc.

### Screenshots or videos

https://github.com/user-attachments/assets/392caf88-6fe1-4d55-adce-67028191f235

### Version

2024.727.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16401938/compressed-logs.zip)

**Comment by Gabixel** [comment]
Note that barrel roll doesn't actually change any circle size. It does its best to keep most of the playfield visible since it rotates (or almost, at least. https://github.com/ppy/osu/issues/13683), that's what it does.
So in short, it's the playfield that's scaled, not the circles themselves. I think we can say that the value is correct.

**Comment by SHOESKE-H** [comment]
Thanks for clarifying!
Kinda confusing since most players won't notice (like I did), but I guess the value is technically correct.
Although then "circle size" kinda loses it's meaning. 
Welp, guess for a mod like this one it's inevitable to not have to scale the playfield
