### ISSUE TITLE
Save and reload truncates all hit object coordinates

### ISSUE THREAD

**Issue by OliBomby** [ppy/osu#29340]
### Type

Game behaviour

### Bug description

Saving and reloading a beatmap in the osu! standard editor truncates all decimal object coordinates. This behaviour matches stable but for beatmaps fully made in lazer its preferrable to preserve decimal precision. I suppose this was previously implemented for compatbility with stable but since the addition of the compatibility export feature its no longer necessary to do truncation in the beatmap encoding.
The legacy beatmap decoder should still truncate coordinates for beatmaps below file format V128 for compatibility, but skip truncation for V128 beatmaps.

### Screenshots or videos

https://github.com/user-attachments/assets/072b85b1-df68-4950-9164-dbbfb655e305

### Version

2024.731.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16532880/compressed-logs.zip)

**Comment by smoogipoo** [comment]
I think this might be because of the decoder. We're parsing the beatmap before re-saving it in lazer format for whatever reason (I wasn't involved in this so I don't know):

https://github.com/ppy/osu/blob/8773c2f7ebc226942d6124eb95c07a83934272ea/osu.Game/Rulesets/Objects/Legacy/ConvertHitObjectParser.cs#L51
