### ISSUE TITLE
New line (\n) doesn't work on notifications in languages other than english

### ISSUE THREAD

**Issue by 64ArthurAraujo** [ppy/osu#29431]
### Type

Cosmetic

### Bug description

Probably a issue with how localization strings are interpreted by notifications

### Screenshots or videos

![pic-selected-240815-0840-37](https://github.com/user-attachments/assets/6b051e97-cf7e-4304-bbff-fce7ab35dd8c)
![pic-selected-240815-0840-58](https://github.com/user-attachments/assets/ea83c3e2-11ce-4684-a3cd-5b238fb79d67)
![pic-selected-240815-0841-20](https://github.com/user-attachments/assets/803f46e0-c4e1-48bd-b34a-b7ebe7168681)

### Version

2024.731-0

### Logs

n/a

**Comment by smoogipoo** [comment]
These are not translated correctly in crowdin.

<img width="749" alt="image" src="https://github.com/user-attachments/assets/bd8fe168-6248-482e-afc3-a85847a87b65">

They should use newlines like the source string rather than trying to bake escape sequences into the string itself.

This is how it should look (Finnish):

<img width="758" alt="image" src="https://github.com/user-attachments/assets/b731d8d9-9e31-4257-b3f9-fbec9a34063c">

If you're interested in helping out, check the readme: https://github.com/ppy/osu?tab=readme-ov-file#contributing
