### ISSUE TITLE
change folder location doesn't work

### ISSUE THREAD

**Issue by ArtemChik103** [ppy/osu#29505]
### Type

Game behaviour

### Bug description

i tried to change my osu! lazer folder to a new place on a different disk and it said that everything was good, i boot up osu! lazer and it started as a brand new client without any maps and skins, i opened the osu folder through the game button and it was a brand new folder which i didnt ask to create since i changed its location but it just didnt work.

### Screenshots or videos

![изображение](https://github.com/user-attachments/assets/cbda498d-f181-4783-ba94-13ae2cfc4f0a)

### Version

2024.817.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16659069/compressed-logs.zip)

**Comment by bdach** [comment]
Can you attach logs from the *old* location of lazer too please?

**Comment by peppy** [comment]
Also as an attempt to recover from this, you can try using the "change location" and specifying the same place you did last time. It may just use the correct files this time around.

**Comment by EVAST9919** [comment]
Related note: some parts of transfer process are confusing.

For example: at the end of the transfer there's a pop-up which tells to delete remaining files in the old location, however it doesn't tell that you shouldn't delete `storage.ini` which contains the path to the new location. I saw some streamers encounter this problem (and so did I my first time using this feature) where they were transfering data from `C:\` to another drive and deleted all the files in `{AppData}/Roaming/osu`. And since there's no `storage.ini` left anymore in there, osu will start fresh in the old location.

**Comment by peppy** [comment]
For anyone affected by this, using the "change folder location" a second time and making osu! aware of where you migrated to should immediately fix the issue.
