### ISSUE TITLE
the export externaly button is gone 

### ISSUE THREAD

**Issue by NeofetchNpc** [ppy/osu#29662]
### Type

Game behaviour

### Bug description

this happens in the latest version of osu! lazer (i use android) 
please fix ppy i really need this feature to export my beatmaps 
Oh yes, I also asked for the manager file section to be fixed, because the one on Android doesn't really read the files on Android. 

### Screenshots or videos

- Manager File Screenshot 

![Screenshot_20240831_003322](https://github.com/user-attachments/assets/90bc5ad3-3e91-4dc1-8c6c-a50972869a4a)
![Screenshot_20240831_003329](https://github.com/user-attachments/assets/dd712e76-cf2e-4e00-ae95-dcf342ee56d2)

- Screenshot export externaly 

![Screenshot_20240831_003312](https://github.com/user-attachments/assets/9d9f7132-e768-40fb-bfa2-974390a72f6d)

### Version

latest

### Logs

[1725030888.performance.log](https://github.com/user-attachments/files/16820505/1725030888.performance.log)
[1725030888.runtime.log](https://github.com/user-attachments/files/16820506/1725030888.runtime.log)
[1725039140.auth.log](https://github.com/user-attachments/files/16820507/1725039140.auth.log)
[1725039140.database.log](https://github.com/user-attachments/files/16820508/1725039140.database.log)
[1725039140.input.log](https://github.com/user-attachments/files/16820509/1725039140.input.log)
[1725039140.network.log](https://github.com/user-attachments/files/16820510/1725039140.network.log)
[1725039140.performance.log](https://github.com/user-attachments/files/16820511/1725039140.performance.log)
[1725039140.runtime.log](https://github.com/user-attachments/files/16820512/1725039140.runtime.log)

**Comment by smallketchup82** [comment]
Seems like this was intentional. The export externally functionality is locked to desktop-only:
https://github.com/ppy/osu/blob/a09c6e2a25468c46631d1605a687db075ffda0ad/osu.Game/Screens/Edit/Editor.cs#L1201

While not explicitly mentioned/discussed in the PR adding it, it likely has to do with the way exporting externally works. It pseudo-mounts the beatmap's files in the temporary directory of your PC, then opens a file manager window in that directory.

On mobile, you probably won't have access to the temporary directory, and it wouldn't be possible to open a file manager to view the files.

Taking all of this into consideration, it's unlikely that the edit externally feature will ever be available on mobile devices, at least not in the near future. There's too many moving parts that don't mix well with the mobile environment. It's probably the same reason as to why you're also missing the generic "Export" functionality.

**Comment by NeofetchNpc** [comment]
Okay, thanks for the explanation, I hope this problem will be resolved in the next update :3

**Comment by smoogipoo** [comment]
This will not be resolved in the next update and likely not in the near future. As mentioned above, this is intentional, and will require other methods of handling.

**Comment by NeofetchNpc** [comment]
> This will not be resolved in the next update and not in the near future. As mentioned above, this is intentional, and will require other methods of handling.

I hope at least the export button section is added again
