### ISSUE TITLE
Window was not created on game starting.

### ISSUE THREAD

**Issue by whamer100** [ppy/osu#29682]
### Type

Game behaviour

### Bug description

I just opened the game and went to Discord to start screensharing while the game was launching (something I have already done before), and for some reason the game window just never spawned. It was not visible in the task bar or alt-tab view. The only way I could even tell it was running was the fact I can hear the music and see it in task manager. It was also not using any GPU.

### Screenshots or videos

![Taskmgr_2024-09-02_22-05-27](https://github.com/user-attachments/assets/eec4be72-ae06-447f-b147-707e7ee4d3a0)

### Version

2024.817.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16843736/compressed-logs.zip)
(you'll have to check the second most recent logs to see if anything was reported, as I had to re-open the game to export them)

**Comment by smoogipoo** [comment]
Dunno. Could it be that it opened on another desktop workspace or something?

Regardless, I can't reproduce, and it's not worth keeping this open unless it can be reproduced. And in that case, probably the best way is to submit a dump of the process (from task manager) to `pe@ppy.sh`.

**Comment by whamer100** [comment]
Was able to somehow replicate the issue and get a memory dump. I've just sent it to `pe@ppy.sh`. It seems to happen very rarely when I just open the game and click on something else while the game is loading.

**Comment by smoogipoo** [comment]
Had a look through and can't really find much. The game does think it's minimised, but otherwise everything appears normal - the window's initialised, it's attached to an active display, and all threads appear to be running normally.

Perhaps it's a thread race with SDL2, as you say "click on something else" which is triggering the minimisation.

I think it's probably best to wait for the next version which will change the windowing system to SDL3. Or, you can test it already by setting the `OSU_SDL3=1` environment variable.
