### ISSUE TITLE
Control point type unable to be changed when added between initial and intermediate points after slider creation

### ISSUE THREAD

**Issue by m1ntleaf** [ppy/osu#29752]
### Type

Game behaviour

### Bug description

While mapping, I noticed an issue where adding a new slider control point after creating the slider would sometimes cause the control point to default to linear with no way of changing it. I assumed this was a bug since I could not figure out a way to reset the point besides deleting the slider and making a new one.

### Screenshots or videos

https://github.com/user-attachments/assets/3f3ca826-a39f-490d-81e5-8a1bd0f948d2

### Version

2024.906.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16913983/compressed-logs.zip)

**Comment by cihe13375** [comment]
I don't see any bug from the video. At least the colors of anchors seems to change correctly following the operations.

I think it's just that the anchor type mechanism in lazer need some time to get familiar with. For example, to make the section between 1st anchor (sliderhead) and 4th anchor curved, one should set the 1st anchor to e.g. bezier and set 2nd and 3rd to inherit:
![11111](https://github.com/user-attachments/assets/a9571404-1ad6-4eeb-bf99-6fe35962da57)

**Comment by m1ntleaf** [comment]
> I don't see any bug from the video. At least the colors of anchors seems to change correctly following the operations.
> 
> I think the point is that the anchor type mechanism in lazer need some time to get familiar with. For example, to make the section between 1st anchor (sliderhead) and 4th anchor curved, one should set the 1st anchor to e.g. bezier and set 2nd and 3rd to inherit: ![11111](https://private-user-images.githubusercontent.com/33959010/365356723-a9571404-1ad6-4eeb-bf99-6fe35962da57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MDM1MTAsIm5iZiI6MTcyNTcwMzIxMCwicGF0aCI6Ii8zMzk1OTAxMC8zNjUzNTY3MjMtYTk1NzE0MDQtMWFkNi00ZWViLWJmOTktNmZlMzU5NjJkYTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDEwMDAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3OTg1NGZkMGUzNjk0ZGZiOTAxMWFhNThjNzk3MTYyYzllZDU1YmIxMzc3ZTUwZTg4MTBkMTY0OGEwMDE2Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JCm0HKJm9lOWOyTYUl2an_cJ53p9dEJNVekD47TLkhA)

Take a closer look. The video shows that even when I set the point to be inherit/bezier, it does not BEHAVE like a bezier curve like intended.

**Comment by cihe13375** [comment]
I watched the video again I still think they do behave as designed.

In the video there are multiple bezier anchors placed consecutively and they seem to behave as linear anchors. That's because every anchor whose type is *not Inherit* starts a new section of the slider. For example the slider in the 1st figure below has the same shape as the combination of sliders in the 2nd figure (you can construct this by right click on an uninherited anchor -> split control point):
![1](https://github.com/user-attachments/assets/106d5b35-ff9c-4238-8232-9f856a295f89)
![2](https://github.com/user-attachments/assets/ff022574-1ef4-4bad-9e13-7c67f2689240)

As a more extreme case, if no anchor is set to inherit, then the whole slidershape would always behave in a "linear" way, regardless of the specific anchor type chosen:
![3](https://github.com/user-attachments/assets/eff5fc0f-3a7d-4c9c-aa00-8cd97b7989c9)

If you still believe there are bugs I suggest point out specific timestamps in the video otherwise I don't know if there is anything else I can comment on.

**Comment by smoogipoo** [comment]
As above, this is working as intended. A non-inherited control point starts a new segment of that type; it does not continue an existing segment even of the same type.

So if you have { Start, Bezier, Bezier, End }, there are 3 discrete segments:

- { Start, Bezier }
- { Bezier, Bezier }
- { Bezier, End }

All of which are linear because there's only 2 control points in each.
