### ISSUE TITLE
The Judgement Counter does not count slider body and slider end

### ISSUE THREAD

**Issue by ZenoG2** [ppy/osu#29854]
### Type

Crash to desktop

### Bug description

title

### Screenshots or videos

https://youtu.be/4uj17V_L5L0

### Version

2024.906.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16983538/compressed-logs.zip)

**Comment by Joehuu** [comment]
Intentional, see https://github.com/ppy/osu/wiki/Scoring (ctrl-f `SliderTick` and `SliderTail`). In short, they don't give miss judgements.

You can also change the display mode of the counter to include ticks and ends:
<img width="852" alt="Screenshot 2024-09-12 at 1 42 02 PM" src="https://github.com/user-attachments/assets/c980cf0b-bbdf-4c3b-83d0-1901ef3fcf40">

**Comment by ZenoG2** [comment]
Hmmm... but it definetly seems weird for everything to be a "Perfect" but the Rank shown to be an A.

**Comment by Joehuu** [comment]
What do you mean by "perfect"? Can you upload a replay that shows that?
