### ISSUE TITLE
Deferred_Vulkan renderer fails assert in Mesa WSI common code

### ISSUE THREAD

**Issue by llyyr** [ppy/osu#29951]
### Type

Crash to desktop

### Bug description

1) Compile and use Mesa with asserts not removed (`-Db_ndebug=false`)

2) Try to run `osu.AppImage`

osu should crash with the following message:

`osu!: ../src/vulkan/wsi/wsi_common.c:1530: wsi_common_queue_present: Assertion 'image->acquired' failed.`

The assert in question: https://gitlab.freedesktop.org/mesa/mesa/-/blob/fd11bbbb90eba6b174371caf07a9b8ca51310730/src/vulkan/wsi/wsi_common.c?page=2#L1538-1539

### Version

2024.906.2-lazer

### Logs

[1726926688.runtime.log](https://github.com/user-attachments/files/17084271/1726926688.runtime.log)

**Comment by bdach** [comment]
This could be thirty different things and the vulkan backends are a dead end that will not receive fixes, it'll sooner get rewritten entirely. 

Which is to say that all in all, the value of this bug report to us is zero. If vulkan is broken then don't use it.

**Comment by llyyr** [comment]
> _if_ this is our fault (very unlikely)

```
VK_LOADER_LAYERS_ENABLE=VK_LAYER_KHRONOS_validation osu.AppImage
VUID-VkPresentInfoKHR-pImageIndices-01430(ERROR / SPEC): msgNum: 1219306694 - Validation Error: [ VUID-VkPresentInfoKHR-pImageIndices-01430 ] Object 0: handle = 0x1b400000001b4, type = VK_OBJECT_TYPE_SWAPCHAIN_KHR; | MessageID = 0x48ad24c6 | vkQueuePresentKHR(): pPresentInfo->pSwapchains[0] image at index 0 was not acquired from the swapchain. The Vulkan spec states: Each element of pImageIndices must be the index of a presentable image acquired from the swapchain specified by the corresponding element of the pSwapchains array, and the presented image subresource must be in the VK_IMAGE_LAYOUT_PRESENT_SRC_KHR or VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR layout at the time the operation is executed on a VkDevice (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkPresentInfoKHR-pImageIndices-01430)
    Objects: 1
        [0] 0x1b400000001b4, type: 1000001000, name: NULL
osu!: ../src/vulkan/wsi/wsi_common.c:1530: wsi_common_queue_present: Assertion `image->acquired' failed.
```
The validation layer would suggest otherwise.

> Which is to say that all in all, the value of this bug report to us is zero. If vulkan is broken then don't use it.

Would a fix be accepted if I figured out what's broken here and submitted a patch? I don't build Mesa with a OpenGL driver for reasons and would prefer to use Vulkan.

**Comment by bdach** [comment]
> The validation layer would suggest otherwise.

Let me restate this more clearly: The fix for this will 100% not live in this repository. If I were to bet, then my odds would be that it's a 1% chance that what you want to fix is https://github.com/ppy/osu-framework, and a 99% chance that what you want to fix is https://github.com/veldrid/veldrid. The latter project's maintainer is no longer _doing work on that project_, and we essentially maintain it ourselves now (@smoogipoo specifically), and we don't want to do that going forward because veldrid's general API and the vulkan backend implementation has been deemed too broken to attempt saving. Last I heard the plan was that we would be trying the new graphics API that SDL3 merged in (https://github.com/libsdl-org/SDL/pull/9312) and seeing if it's any better.

> Would a fix be accepted if I figured out what's broken here and submitted a patch? I don't build Mesa with a OpenGL driver for reasons and would prefer to use Vulkan.

Maybe. Read all of the above and make your own conclusion. I definitely can't guarantee that a fix will be accepted in the current situation.

**Comment by smoogipoo** [comment]
As above - Vulkan is broken, don't use it. If you want to submit a fix it'll go into https://github.com/ppy/veldrid but you're on your own.
