### ISSUE TITLE
osu!lazer Crashing.

### ISSUE THREAD

**Issue by Nebbilies** [ppy/osu#3021]
When I open up osu!lazer, it just shows up a black screen 
![image](https://user-images.githubusercontent.com/41163344/42645576-971f2824-8628-11e8-86e5-3eac430e4dff.png)
then suddenly closes itself. There is no "osu!lazer has stopped working".
Here are the log files:
[performance.log](https://github.com/ppy/osu/files/2189382/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2189383/runtime.log)

**Comment by AlFasGD** [comment]
Could you please provide us with your system's specs? The most important information is your system memory (RAM), CPU, GPU, OS, however feel free to include even more information in case it is needed.

**Comment by AlFasGD** [comment]
Outright the issue seems to be your extremely low amount of memory. Please consider equipping your device with more memory to be able to handle the game. In general, 2 GB of RAM are barely enough to run the OS itself, which is making your device struggle a lot.

**Comment by peppy** [comment]
Could you please check event view (under Applications) for more details on the crash? The logs you provided unfortunately don't tell us much.

**Comment by smoogipoo** [comment]
May be related:

According to microsoft: https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x

**For Windows 8.1 and earlier versions, or Windows Server 2012 R2 and earlier versions:**

Make sure that your Windows installation is up-to-date and includes [KB2999226](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows), which can be installed through Windows Update. If you don't have this update installed, you'll see an error like the following when you launch a .NET Core application: The program can't start because api-ms-win-crt-runtime-1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.

**For Windows 7 or Windows Server 2008 R2:**

In addition to KB2999226, make sure you also have [KB2533623](https://support.microsoft.com/en-us/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot) installed. If you don't have this update installed, you'll see an error similar to the following when you launch a .NET Core application: The library hostfxr.dll was found, but loading it from C:\<path_to_app>\hostfxr.dll failed.

**Comment by second2050** [comment]
I have the same problem as the op.

My System:
AMD Ryzen 7 1700
Nvidia Geforce 1070
16GB RAM

My log files:
[performance.log](https://github.com/ppy/osu/files/2838195/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2838196/runtime.log)

**Comment by smoogipoo** [comment]
@second2050 your issue is a little different, please make a new issue.
