### ISSUE TITLE
Profile banner size/scalling is diffrent on lazer, compared to the website.

### ISSUE THREAD

**Issue by leoneleonel** [ppy/osu#30298]
### Type

Cosmetic

### Bug description

Banner on lazer is cut off on the bottom, compared to the website.
Top is website, bottom is lazer.
![ieriewbewge](https://github.com/user-attachments/assets/9608afd9-4041-4ab8-a46f-f0fb81ce925b)

### Version

2024.1009.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17384301/compressed-logs.zip)

**Comment by bdach** [comment]
Nice meme, but I think this is a wontfix.

Web uses 1000x250 size for the cover...

![image](https://github.com/user-attachments/assets/b6755bfe-68c7-4a87-bd24-3d58791a1039)

...but only if the size of the window is at 900px or above...

![image](https://github.com/user-attachments/assets/2ea4b2c5-185b-4860-8162-247a4e1cc2af)

...which establishes fact 1, namely that _web gives no guarantees that the full height of the cover will be shown_.

lazer shows these overlays at differing widths, depending on your screen resolution. Which means that we can't use "1000x250", we have to use "width of the overlay x 25% of said width". Which leads to fact 2, namely that doing this looks ridiculous at some resolutions:

![osu_2024-10-16_10-24-33](https://github.com/user-attachments/assets/ab9fd46b-9616-4742-b297-c9617736ee78)
![osu_2024-10-16_10-23-32](https://github.com/user-attachments/assets/92c42004-fc77-4df1-a7e3-3c7b4305a0ca)

So we generally cannot guarantee that the full cover will be shown nor do I think we should be beholden to that because that's not the general purpose of cover images. I would say no further action is required here.

**Comment by Voykaria** [comment]
It would be nice to make lazer's scaling match the website, or atleast make the website match lazer's, but I think that the first option is the better one.

Changing the page zoom on the website preserves the banner & profile picture scaling very consistently, & when it starts to cut the banner, it cuts it on the sides, not the top & bottom. On lazer, the banner scaling changes for every single UI scaling change, cutting top & bottom for smaller scales & then cutting both sides for bigger scales, the profile picture scaling also changes.

On a 1080p display, UI scaling at 1,16x on lazer is the one that most closely resembles the website, but the website still looks better & it preserves this same scaling for multiple zoom levels, without cutting the elements, which makes their design way more consistent overall:

Website (looks this way for multiple zoom levels):
![Image](https://github.com/user-attachments/assets/6ea92a31-b52f-4630-93df-d7820bca84d5)

osu!lazer (changes for every UI scaling change):
![Image](https://github.com/user-attachments/assets/87d93097-eadc-43f9-a1b7-384a15010d3b)

That's why I think that the way the website scales those elements is better than how lazer does it, & making lazer match the website's scaling is the better option, instead of making the website match lazer's or leaving them inconsistent.
