### ISSUE TITLE
Reverting a keybinding to default when its default key is a secondary one erroneously warns of a conflict

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#30430]
### Type

Other

### Bug description

Short backstory to understand:
I started using <kbd>D</kbd> and <kbd>F</kbd> (and <kbd>S</kbd> for smoke, since it's the closest button in my layout) with osu! for a while, so I currently have this configuration:

![image](https://github.com/user-attachments/assets/f6410308-2074-4cef-9ea4-3f3904287782)

And I kept <kbd>Z</kbd> and <kbd>X</kbd> as fallbacks, just in case.
I needed to rebind <kbd>M1</kbd> and <kbd>M2</kbd> to make them work in gameplay and to test some stuff, so I used the quick "revert to default" button. This left me with a strange surprise:

![image](https://github.com/user-attachments/assets/6233748d-fe37-43b0-8c68-db58b71d4dbe)

So apparently all you need to do to reproduce the issue is to have the following setup (i.e., have the default button listed as the second item, and something else listed as the first one), and then click the "revert to default" button:

![image](https://github.com/user-attachments/assets/a1c6c77a-642e-41f7-bf62-025854f04c02)

### Version

2024.1009.1

### Logs

N/A

**Comment by Gabixel** [comment]
Can also be tested with the "Select" keybinding, which seems to show that this only happens when the their default slot is **shifted to the right**:

https://github.com/user-attachments/assets/4ca31fc0-6afe-4fa7-92c7-84b17c3f3ea5

**Comment by BunnyTub** [comment]
(Bad assessment possibly incoming)

Why collision is detected erroneously (Self checking)
- When the code tries reverting the keybinds to their defaults, it first checks for any possible collisions against other keybinds, but doesn't exclude the current slot (e.g. Select). I think that the change should change functionality to exclude the current slot when resetting the slot's keybinds to their defaults, as all the keybinds inside will be reverted to their defaults.

As for why nothing happens when the default keybind is the same as the current (_Enter_ is _Enter_)
- When the code checks for any possible collisions on the _Enter_ key, presumably called by some function to set the keybind, the code checks one by one for each slot, ignores the current slot (e.g. Select), and then I think **doesn't** set the keybind, because _Enter_ is _Enter_.
