### ISSUE TITLE
Progressively worse stuttering from UR counter with very high note count maps

### ISSUE THREAD

**Issue by longnguyen2004** [ppy/osu#30635]
### Type

Performance

### Bug description

Observed this while playing casually. Towards the end of the map, every note hit causes a very noticeable stuttering

Reproduction step:
- Play https://osu.ppy.sh/beatmapsets/1956376#mania/4094064 on Auto
- Seek to near the end of the map
- Add the UR counter. Observes that each note hit will result in a spike on the Update frametime graph
- Remove the UR counter. Observes that the spikes are gone (the remaining spikes seem to be GC related and can be ignored)

### Screenshots or videos

https://github.com/user-attachments/assets/847abe97-829e-4066-be80-2b8d133fdcb0

### Version

2024.1009.1

### Logs

[1731660081.network.log](https://github.com/user-attachments/files/17772114/1731660081.network.log)
[1731660081.performance.log](https://github.com/user-attachments/files/17772116/1731660081.performance.log)
[1731660081.runtime.log](https://github.com/user-attachments/files/17772117/1731660081.runtime.log)
[1731660081.auth.log](https://github.com/user-attachments/files/17772118/1731660081.auth.log)
[1731660081.input.log](https://github.com/user-attachments/files/17772119/1731660081.input.log)

**Comment by smoogipoo** [comment]
There's two issues here:

The _raw_ performance of the method itself is pretty bad. A lot of time is spent checking types:
<img width="912" alt="image" src="https://github.com/user-attachments/assets/832d73b6-8608-40c7-9ba3-3c0f386a2c86">
This could be fixed by something like this: https://gist.github.com/smoogipoo/fda9c73371309a2a581c726a12bceeb9, which I'd say is something we can apply with little thought.

That change will already make it somewhat reasonable for one displayed combo counter. The rest is because it's running over every single `HitEvent` every judgement, once per counter. Perhaps this could be improved by storing incremental data locally or via `ScoreProcessor`, but there comes the question of handling rewind (maybe you don't and static calculation?).

Leaving this here for now if anyone else wants to take the lead.
