### ISSUE TITLE
AppImage is missing the icon in file managers

### ISSUE THREAD

**Issue by TechniKris** [ppy/osu#30759]
### Type

Cosmetic

### Bug description

The AppImage file doesn't show its icon in Linux file managers (on some desktops?), which seems like a regression introduced in `2024.906.1` (assuming correctly set up thumbnailers).

I encountered the discrepancy on KDE Plasma desktop, in Dolphin file manager, and confirmed the same behavior in Thunar.
I tried downloading randomly selected old osu! AppImages (`2023.326.1`, `2021.212.0`, `2020.408.1`) and they all displayed correctly. A screenshot below presents many more examples of versions neighboring the `2024.906.1` release, where that specific release seems to be the cutoff point where the icons broke.

The issue doesn't seem to affect icons in Plasma's taskbar.

[AppImageLint](https://github.com/TheAssassin/appimagelint) seems to freak out on the `.DirIcon` inside of the AppImage mountpoint of builds `2024.906.1` and newer. It seems to align with what's being reported in https://github.com/ppy/osu/discussions/30466 on `2024.1009.1` that "the icon on the application is gone".
I included logs from it, as well as a diff file with a relevant change of behavior, in the Logs section.

Possible culprit: https://github.com/ppy/osu/issues/29783 mentions `icon.png` missing from `.nupkg`s since `2024.906.1`.
I presume the regression might've been introduced by the transition from Squirrel to Velopack.

I started up a Fedora VM with Gnome desktop to see if the behavior is the same on other desktops, but the thumbnail generation was very inconsistent, most of the time refusing to generate thumbnails for any version, so I mostly ignored it in my testing.
It is worth mentioning though that after a reboot the `2024.1115.3` did finally get an icon, but not any other version (although that was with a checkerboard instead of transparency, so something's broken on the Gnome side as well).

### Screenshots or videos

Icons in Dolphin on Plasma:
![Missing icon on KDE](https://github.com/user-attachments/assets/479507d0-d790-4778-94d7-b149bdbe1eaa)

### Version

From 2024.906.1 up to 2024.1115.3 (current release)

### Logs

Game logs, the newest run being on `2024.1115.3`:
- [compressed-logs.zip](https://github.com/user-attachments/files/17801080/compressed-logs.zip)

AppImageLint logs:
- [2024.817.0.log](https://github.com/user-attachments/files/17801556/2024.817.0.log)
- [2024.906.1.log](https://github.com/user-attachments/files/17801562/2024.906.1.log)
- [2024.1115.3.log](https://github.com/user-attachments/files/17801564/2024.1115.3.log)
- [trimmed-diff-2024.817.0-vs-2024.906.1.txt](https://github.com/user-attachments/files/17801953/diff.txt)

**Comment by peppy** [comment]
Probably fixed in next release? (see https://github.com/ppy/osu-deploy/pull/181)

**Comment by ravener** [comment]
AppImages aren't really supposed to have icons by default, unless some thumbnailer plugin handles them on your system/file manager but that varies.

osu! however has had this line in the code https://github.com/ppy/osu-deploy/blob/master/templates/osu!.AppDir/AppRun#L3

on launch it'd attempt to copy its icon into the thumbnail cache, have you run those files at least once? since the thumbnail cache uses checksums and differs for each appimage

honestly this feels too hacky and I would've suggested its removal at some point, appimages shouldn't touch the thumbnail cache like that, that's for the file manager and thumbnailer programs to handle, and by default app images are simply portable executables, Linux has no concept of .exe icons like on windows either, so they are just files as far as the system is concerned, if you need the menu entry on your desktop you should 'integrate' the app image which something like [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) or [Gear Lever](https://flathub.org/apps/it.mijorus.gearlever) can do

**Comment by ravener** [comment]
> (although that was with a checkerboard instead of transparency, so something's broken on the Gnome side as well).

GNOME's file manager just does that, with a checkboard, it's normal since the thumbnail generation feature was meant for media previews like images and videos

**Comment by ravener** [comment]
I did a bit more reading and it's interesting, apparently KDE Dolphin handles thumbnails differently and they also thumbnail appimages it seems, I've heard things like having to install the libappimage package for it to work though so maybe look into that.

I don't have a lot of experience with KDE though, gnome user here and appimages aren't supposed to have icons by default here

**Comment by ravener** [comment]
Oh I just found more interesting stuff, apparently appimages can contain a `.DirIcon` (see [spec](https://docs.appimage.org/reference/appdir.html#general-description)) file that can be used for thumbnailers, I guess kde dolphin picks up that file.

This existed in old osu! app images but no longer in newer ones. I'm guessing this is about the migration to Velopack, since they have their custom logic for building appimages, where as the old ones relied on the standard appimagetool that probably automatically generated a .DirIcon file.

This probably belongs to an upstream issue to Velopack to handle that since it should be standard, I'll look more into it soon

**Comment by 7deok7** [comment]
Yes, the logs I provided in #30466 show .DirIcon is missing (FileNotFoundError: [Errno 2] No such file or directory: '/tmp/.mount_osu.ApxLzii3/.DirIcon'). I think looking into the full output of appimagelint is a good idea.
Also just for clarification, the bug occurs on I’m pretty sure all DEs. I’ve tried it on KDE and Cinnamon myself and the error is the same. Also also, yes some AppImages are meant to carry icon files (Modrinth app, Lunar Client, such and such).

**Comment by TechniKris** [comment]
> have you run those files at least once? since the thumbnail cache uses checksums and differs for each appimage
 
Yes, I have, although Dolphin on Plasma seems to pick up on these immediately, without even needing to launch - case in point: the randomly picked AppImages I downloaded got their thumbnails almost instantly after opening the directory that contained them).

> on launch it'd attempt to copy its icon into the thumbnail cache

Yeah, osu! even throws a message in the terminal if the directory doesn't exist (e.g. on freshly installed systems), instead of just creating it... Yeah, I forgot to report that bug since it's such a miniscule thing. 😅 I guess it doesn't matter at this point considering you're removing the functionality altogether.

> if you need the menu entry on your desktop you should 'integrate' the app image which something like [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) or [Gear Lever](https://flathub.org/apps/it.mijorus.gearlever) can do

Yeah, I myself don't really have a need for those - I'm using [the AUR package](https://aur.archlinux.org/packages/osu-lazer-bin), which provides the icon of its own for the application launcher to use. I made this issue mostly with the standalone AppImages in mind.

> apparently KDE Dolphin handles thumbnailers differently and they also thumbnail appimages it seems

Yup.

![obraz](https://github.com/user-attachments/assets/f24f6355-6e46-40b9-affd-9a90c59dbd61)

**Comment by ravener** [comment]
Yeah everything is clear now,

* appimage thumbnails are generated from a file called `.DirIcon` this existed in old versions but no longer after moving to Velopack, therefore I opened https://github.com/velopack/velopack/issues/367 so they can implement this, we'll see what they have to say on this, we could also add the file ourselves but I figured it'd be better if Velopack supported it directly like appimagetool handled it before.
* The `.DirIcon` missing is also making AppImageLint fail, and AppImageLauncher unable to integrate it.
* PR https://github.com/ppy/osu-deploy/pull/185 removes osu's own self-thumbnailing capability since that should be up to file managers and not apps themselves

**Comment by ravener** [comment]
@TechniKris @7deok7 As of `2024.1208.0` the new fixes are out, it passes AppImageLint and AppImageLauncher can integrate it with proper icons, it should also fix KDE Dolphin's AppImage previews.

Can you guys confirm on your side? and then we can close this.

**Comment by TechniKris** [comment]
@ravener Works in Dolphin on KDE now ^^
![obraz](https://github.com/user-attachments/assets/35c66c87-8020-4493-ae13-85fe20f11d84)
