### ISSUE TITLE
Unstable Rate shouldn't be converted in osu!mania

### ISSUE THREAD

**Issue by peppy** [ppy/osu#30828]
Bumping to issue since it seems like something which needs resolution.

### Discussed in https://github.com/ppy/osu/discussions/30698

<div type='discussions-op-text'>

<sup>Originally posted by **KapiWilq** November 17, 2024</sup>
A year ago, [there was introduced a change in the way that the Unstable Rate is calculated](https://github.com/ppy/osu/pull/25415). It made the Unstable Rate account for the gameplay rate, which made the Unstable Rate not require conversion when playing with rate-changing mods. [There was raised a fair concern about osu!mania](https://github.com/ppy/osu/pull/25415#issuecomment-1807452912), but according to [these](https://github.com/ppy/osu/pull/25415#issuecomment-1811435714) [replies](https://github.com/ppy/osu/pull/25415#issuecomment-1815833239) the Unstable Rate value for osu!mania should be correct. It's not correct.

## Why?
osu!mania scales hit windows to account for the rate change[^1][^2]. This makes the Unstable Rate not require conversion when playing with rate-changing mods since hit windows are being resized to make them "effectively" the same size as if you are playing without rate-changing mods. Therefore, by converting the Unstable Rate in osu!mania, it's value is incorrect. This also makes the Unstable Rate value shown in osu!(stable) correct.

| osu!(stable) | osu!(lazer) |
| - | - |
| ![screenshot352](https://github.com/user-attachments/assets/219f5f29-a917-4d23-b1d0-f26e2b77aca2) | ![osu_2024-11-16_18-15-38](https://github.com/user-attachments/assets/7be2de05-2a13-40b3-b30c-b3ad9d8b6eb7) |

This is the score that I used for the comparison in these screenshots: https://osu.ppy.sh/scores/mania/301846710

[^1]: https://github.com/ppy/osu/blob/master/osu.Game.Rulesets.Mania/Mods/IManiaRateAdjustmentMod.cs#L28
[^2]: https://github.com/ppy/osu/blob/master/osu.Game.Rulesets.Mania/Scoring/ManiaHitWindows.cs#L39-L45</div>

**Comment by ssz7-ch2** [comment]
> osu!mania scales hit windows to account for the rate change. This makes the Unstable Rate not require conversion when playing with rate-changing mods since hit windows are being resized to make them "effectively" the same size as if you are playing without rate-changing mods. Therefore, by converting the Unstable Rate in osu!mania, it's value is incorrect. This also makes the Unstable Rate value shown in osu!(stable) correct.

Does this actually make sense? Unstable Rate has nothing to do with hit windows so even though osu!mania scales hit windows, it shouldn't affect the Unstable Rate.
For sanity check, here's the Unstable Rate for a NM play on the same map with similar hit counts.

![screenshot047](https://github.com/user-attachments/assets/9f433c03-b16f-4c24-95d9-77342684672f)

The UR should be similar between the two scores, since the perceived hit window is the same.
So the converted UR of 119 for the DT score makes a lot more sense here.

**Comment by frenzibyte** [comment]
I don't see how two scores with similar hit counts should have similar UR. The UR's data is the time difference between perfect hit time and the player's time of the hit, the player could've hit the object at the beginning of the hit window X rather than the end of it. Am I missing something here?

Whether osu!mania should convert UR with gameplay rate or not is probably as subjective as the concept of converting UR in the first place. It was [discussed](https://github.com/ppy/osu/pull/25415#issuecomment-1807452912) in the original PR and a [similar answer](https://github.com/ppy/osu/pull/25415#issuecomment-1815833239) was posted there (that being the UR not being tied to the hit window).

Whether that makes sense or not seems up in the air, it's probably as subjective as the concept of converting UR with gameplay rate in the first place. 

If I were to give my own opinion on this, the UR being scaled/descaled makes most sense because the perceived hit window is smaller/larger on rate-changing mods. Going with that logic, osu!mania should not be scaled/descaled. But again, mania players may think otherwise, for other factors that define UR better than "perception of hit windows".

Perhaps this should be demoted back to a discussion thread until there's more traction / discussion going on to reach a consensus on this.

**Comment by ssz7-ch2** [comment]
> I don't see how two scores with similar hit counts should have similar UR. The UR's data is the time difference between perfect hit time and the player's time of the hit, the player could've hit the object at the beginning of the hit window X rather than the end of it. Am I missing something here?

Over a large sample of hits, the distribution of the hits will pretty much follow the same distribution (unless you're a robot). So scores with similar hit counts will have relatively similar URs.


> If I were to give my own opinion on this, the UR being scaled/descaled makes most sense because the perceived hit window is smaller/larger on rate-changing mods.

The reason why UR is converted (at least in osu!std) is because of the gameplay rate, not because the perceived hit window has changed.

Compare these two scenarios:
1. Play a map with DT
2. Use an external tool to speed up the same map by 1.5x and play it

If a player sets the same score on both maps, should the UR be the same?
In stable, the UR would be different. That's why converted UR is used, so that the UR will be the same in both scenarios.

It doesn't matter if the two maps have different perceived hit windows or not. Whether the second map is OD0 or OD10, I don't think the UR should be affected by it.

I'm not part of the mania community so I don't know if they think differently of this, but the claim given in the initial discussion doesn't give any explanation as to why UR should account for scaled hit windows. And I don't think this change should be made without proper consideration.

**Comment by Natelytle** [comment]
This issue indeed does not make sense. UR does not care about the hit window, so whether or not the hit window is scaled by rate doesn't change whether UR should be converted. The only thing that matters is if the underlying game clock is faster, which it still is in mania, and thus the unstable rate should still be converted by rate.

> If I were to give my own opinion on this, the UR being scaled/descaled makes most sense because the perceived hit window is smaller/larger on rate-changing mods. Going with that logic, osu!mania should not be scaled/descaled. But again, mania players may think otherwise, for other factors that define UR better than "perception of hit windows".

UR is a pretty well defined metric, it is intended to be the deviation of your taps in milliseconds multiplied by 10. Rate change mods for all modes speed up or slow down the game clock, which changes the speed of a millisecond, so the adjustment simply brings them back in line. I don't see a case for the "perception of hit windows" usage, or else UR would additionally scale with overall difficulty.

**Comment by frenzibyte** [comment]
Fair enough, I will leave this discussion as I don't think I need to have a say on how this should work.

**Comment by bdach** [comment]
I'm not wholly convinced there's anything to fix here either, but it depends on perceptions.

What I guess @kapiwilq (tagging to get them into here) was angling for in the original discussion is that this change while in some ways "correct" makes it not really possible to I guess "compare" UR between HR/DT/nomod plays? That would fit in my mental model of mania players saying rate changing is "mostly preference" and not wanting to make it affect difficulty anything including multipliers and pp. Would that be a correct view? No idea. Probably something we should ask mania people about somewhere.

**Comment by peppy** [comment]
This is definitely more nuanced than I expected it to be and really is a matter of perspective. Let's downgrade this back to [the discussion](https://github.com/ppy/osu/discussions/30698).
