### ISSUE TITLE
Assigned hitsound volume breaks after the undo action under certain circumstances

### ISSUE THREAD

**Issue by rust2** [ppy/osu#30899]
### Type

Game behaviour

### Bug description

Assigned hitsound volume breaks if the undo action involves overlapping slider end and slider start whose placed at one tick.
I got into that trouble some times accidentally. Mainly because of distance snapping turned on which sometimes (I can not reproduce it when I try to do that intentionally) allows to place multiple objects at the same one tick when moved too close to each other.

### Screenshots or videos

https://github.com/user-attachments/assets/8939fdca-f541-4a32-9a6b-f5f5710d8596

### Version

2024.1115.3-lazer

### Logs

are needed?

**Comment by peppy** [comment]
cc @OliBomby

**Comment by bdach** [comment]
I'm not even sure this is fixable. I haven't looked into it much but the reason this happens is 99% because of the overcomplicated logic that attempts to make per-object hitsounds work using stable style sample control points. When a slider end coincides with a slider start, things in that logic (see https://github.com/ppy/osu/pull/28619) get smushed together so that there's no sane way to actually query what was saved anymore.

**Comment by OliBomby** [comment]
Bdach is right. The legacy file format doesnt support multiple volumes on the same tick.

We can fix the undo behaviour with #30314 but it will still break on save/reload until we have a new file format.

**Comment by rust2** [comment]
Okay, I understand. It's just was not intuitive to me as it looks like I can just have the distinct volume per each object. But this often happens for me when I use distance snapping which automatically moves objects back and forth on the timeline
