### ISSUE TITLE
Inaccuracies in autoplay

### ISSUE THREAD

**Issue by fntStique** [ppy/osu#3107]
Playing songs in osu!lazer with AT mod on,sometimes the songs lag up a few frames on higher BPM songs (200-210) and songs that the stable version is able to 100% osu!lazer can not.

**Comment by peppy** [comment]
Could you please give an example of a beatmap where this happens (and also specify which ruleset)?

**Comment by chrisny286** [comment]
The rewind is especially problematic in catch mode because the fruit that were caught massively stack up
[like this](https://puu.sh/CANsU/ae72e4ed45.mp4).

**Comment by peppy** [comment]
I believe this has since been resolved (please confirm if able).

**Comment by chrisny286** [comment]
there are still circumstances under which this happens. e.g. rewind to a time where the cursor is amidst a slider -> will result in a miss or 50(in std.) in taiko and mania misses also happen at the time point you rewind to(probably because a note is loaded and not getting hit by AT since the rewind timepoint is within the timewindow of the hitobjectobject but past its perfect timing).
In CTB no misses whatsoever can be provoked the only thing still present in CTB is the stacking up fruits on rewind as shown in the video of my previous comment.

**Comment by peppy** [comment]
Can you make a video of this happening on a slider?

**Comment by Joehuu** [comment]
Closing as stale. Performance has drastically improved since, the maps listed get 100% now, catch fruits stacking too much after rewinding fixed in https://github.com/ppy/osu/pull/6032, and missing after rewind/ff fixed in https://github.com/ppy/osu/pull/12376.
