### ISSUE TITLE
quick retry not working when when at the fail screen or the continue screen

### ISSUE THREAD

**Issue by GGchung69** [ppy/osu#31131]
### Type

Game behaviour

### Bug description

i was trying to play daily challenge today and when i go to do something and suddenly i cannot press the quick retry key, i wonder if there was something wrong with the code, i'll give you a video showing the bug
update: i figure out the space button in osu! was asign with something else and would not be pressed in fail screen and continue screen as i just try a different keybind and it work, why though?

### Screenshots or videos

https://github.com/user-attachments/assets/c03b7557-3360-4632-83ab-69a1c7dbb300

### Version

2024.1208.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18139319/compressed-logs.zip)

**Comment by peppy** [comment]
Do you have space bound to "select"? If so, this is expected behaviour I think. It's hard for us to support the global "select" key having the same binding as "quick retry" (which should take precedence? probably both based on context, which we're not really interested in making work as it would be a huge amount of subjective decisions).
