### ISSUE TITLE
Editor: Changing curve type doesn't actually do anything

### ISSUE THREAD

**Issue by BrettZolstick** [ppy/osu#31155]
### Type

Game behaviour

### Bug description

Changing the the curve type of a slider's control point doesn't seem to be working for me. It changes colors, but the curve stays linear.

### Screenshots or videos

https://github.com/user-attachments/assets/47c0c0ed-b3cf-4a09-a242-e1c3aee0aa97

### Version

2024.1208.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18150109/compressed-logs.zip)

**Comment by kongehund** [comment]
Selecting a curve type of a control point means that you start a new curve segment from that control point and onwards. Changing the curve type of the middle point does nothing because the segment it creates only has two points (the middle and the last one).

To get the behavior you expect, change the curve type of the first point in the slider, not the middle one.
