### ISSUE TITLE
Support for option combination keys in text boxes in Mac

### ISSUE THREAD

**Issue by plankp** [ppy/osu#3125]
Not sure if this applies to other input sources.

In the "ABC" input source, by pressing the option key with another key maps to another key.

For example:

Option + A = å
Option + X = ≈
Option + ` = the accent on the "è"

Will this ever be supported in text boxes?

**Comment by Joehuu** [comment]
This is somewhat working as of now (linked PR doesn't seem needed now), but text isn't being consumed since https://github.com/ppy/osu-framework/pull/2029 and only after pressing a regular key will show the pending text.

Not sure what was the direction when the chat tab navigation was implemented (apart from conforming to stable), but https://github.com/ppy/osu/pull/3889#issuecomment-448997013 seems like a good solution now to not conflict the option combination keys on macOS.

https://user-images.githubusercontent.com/35318437/131976943-cc3fc413-4bae-4101-a405-31db8450fce5.mov

**Comment by bdach** [comment]
That alt/ctrl conditional checking if a key produces text in text box really needs to go in general. It's wrong on any other platform/language with diacritics, too.

The only reasons I haven't gone and done that is lack of time and it being a bit of a scary change (not sure what key combinations will break). Some changes to `ITextInputSource` may possibly help.

**Comment by smoogipoo** [comment]
Should be fixed via https://github.com/ppy/osu-framework/pull/4985
