### ISSUE TITLE
A way to tag maps

### ISSUE THREAD

**Issue by segalll** [ppy/osu#3295]
I think this would be a nice feature that many would enjoy. For example, if there is a map I like that is a great practice map for patterns for me, I could nickname it "Pattern Practice" or something like that. I think you should be able to see both the real name of the map and the nickname if you have one. I think these would be stored in a file nicknames.db, based off of what was done with collections.

**Comment by peppy** [comment]
Sounds like you're proposing tags, or collections (they all have the same purpose).

**Comment by LastExceed** [comment]
@segalll tags are basically what you are asking for. You add a tag to map so you can find it later by searching for that tag. As peppy said they basically serve the same purpose as collections. You can find an implementation of this system in [Etterna](http://etternaonline.com/)

**Comment by LastExceed** [comment]
While it doesn't make much sense to have multiple sorting systems (eg Etterna has favourites, playlists, tags and packs which is completely overkill), it is a valid question to ask which of these systems we want to use in the future:

osu!stable uses collections, which might be the most intuitive but lack the ability of multi filtering (i.e. you can't filter for maps that are present in multiple collections) and also collections currently can't be searched for (if you have a large number of collections and are looking for a particular one you have to find it manually in the alphabetically sorted list). The latter is something that could be fixed, but the former is a notable advantage of tags over collections.

Favourites is definitely a bad choice as its basically the same as tags except its limited to a single tag, and packs are a StepMania thing.

This leaves us with tags vs collections. I would vote for tags due to the advantage in functionality (multi-filtering) and because I don't see a downside to it. Actually, since database wise they're kinda the same thing, fixing the drawback of collections mentioned above (i.e. making collections searchable to display the given collection when in the "collections" tab, or its maps when in the "no grouping" tab) would basically result in implenting tags without getting rid of collections as we know them.
