### ISSUE TITLE
Perfomance issues (High consume of CPU and RAM)

### ISSUE THREAD

**Issue by Paulo-Cesar-S-S-F** [ppy/osu#3319]
Stable Osu! (the other one) runs quite well on my notebook (it is old, but still works):
- Intel Celeron Bay Trail N2806 @ 1.6 Ghz;
- 2 GB RAM;
- Intel HD graphics 4400;
- Windows 8.1 Single Language;

The next screenshot show the hardware usage when osu! is in stand-by (not playing nor downloading beatmaps...):
![Osu!](https://user-images.githubusercontent.com/33911792/44633547-2dcbfd80-a963-11e8-87be-3896448e2a31.png)

As you can see, the CPU and RAM usage is very low, so Osu! runs quite smoothly.

But when i launch Osu!lazer, the performance decreases to the point i can't play at all;
![Osu!Lazer](https://user-images.githubusercontent.com/33911792/44633445-d0837c80-a961-11e8-85f9-b73a509555bf.png)
Please, notice the higher usage of CPU and RAM.

In both situations, i ran nothing but Osu! or Osu!lazer.

Is this because my old notebook will not handle Osu!Lazer or because Osu!Lazer still in development?

**Comment by segalll** [comment]
This is a known issue. Optimization is necessary.

**Comment by peppy** [comment]
A few things to point out:

- Stable's cpu is only so low because you don't have it focused. It goes into a very low power mode. Try giving it focus and you will notice it will use similar amounts of CPU to lazer.
- Lazer is currently optimised for having 4 cores or more. We will be adding a mode for 1-2 core processors in the future.
- RAM usage being higher is currently intentional (it allows for better performance) and while it may change going forward, should not be contributing to performance issues. The exception here is increases when entering song select, where beatmap panels are currently alocating more texture memory than their final implementation will require.

**Comment by peppy** [comment]
I believe this should be a lot better these days. We've both drastically reduced memory (in all but intense gameplay) and reduced CPU via reduced allocs and optimisations. There is also a single threaded mode for low power PCs like the one mentioned in this issue.

**Comment by enoslayd** [comment]
So, single thread mode makes lazer work more like stable? Does that mean input is dependent on draw frames?

**Comment by smoogipoo** [comment]
That's correct
