### ISSUE TITLE
Osu!Lazer don't start at Windows 7 x64 at All

### ISSUE THREAD

**Issue by AsterXML** [ppy/osu#3344]
Osu!Lazer don't start at Windows 7 x64 at All. In Task Manager i don't see the Process.

**Comment by Aragami1408** [comment]
That might be the RAM I think. Or it isn't compatible with Windows 7

**Comment by peppy** [comment]
Check event viewer for any error details please. Alternatively, upgrade.

**Comment by AsterXML** [comment]
Nothing

**Comment by AsterXML** [comment]
Where i can look this?

**Comment by LastExceed** [comment]
I am running the release version of win7hp64 (i.e. no updates installed ever) and lazer works perfectly fine for me. So pretty sure the problem isn't the os.

**Comment by AimsterZ** [comment]
lazer not support 32bit anymore?

**Comment by peppy** [comment]
For the time being the release builds are x64. You are free to build x86 yourself.

**Comment by smoogipoo** [comment]
@AsterXML can you test again with the latest release, and tell us which is the last release that worked for you?

**Comment by smoogipoo** [comment]
According to microsoft: https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x

**For Windows 8.1 and earlier versions, or Windows Server 2012 R2 and earlier versions:**

Make sure that your Windows installation is up-to-date and includes [KB2999226](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows), which can be installed through Windows Update. If you don't have this update installed, you'll see an error like the following when you launch a .NET Core application: The program can't start because api-ms-win-crt-runtime-1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.

**For Windows 7 or Windows Server 2008 R2:**

In addition to KB2999226, make sure you also have [KB2533623](https://support.microsoft.com/en-us/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot) installed. If you don't have this update installed, you'll see an error similar to the following when you launch a .NET Core application: The library hostfxr.dll was found, but loading it from C:\<path_to_app>\hostfxr.dll failed.
