### ISSUE TITLE
Cannot find exe file when building on Crouton

### ISSUE THREAD

**Issue by pinguallyj** [ppy/osu#3375]
It supposed to be somewhere in osu desktop folder but I can't find it anywhere, thus I can't launch the game

**Comment by jai-sharma** [comment]
Please provide more information about your build environment.
OS, Complier/Runtime etc

**Comment by pinguallyj** [comment]
I use this guide [https://www.reddit.com/r/linux_gaming/comments/7m7hb6/how_to_buildrun_osulazer_native_on_ubuntu_1710/](url)
I did everything succesfully but there is no exe. I run chromeos with installed Crouton under xfce4 environment. This guide uses mono to build and run it.

**Comment by LastExceed** [comment]
The tutorial you linked is way outdated. It is trying to use .NETframework via mono instead of .NETcore natively.

I highly recommend using vscode with the C# IDE extension to run osu!lazer on linux (you can do it without it but with vscode things will be much easier). Other than that you'll need git and the dotnet SDK.

```
git clone --recurse-submodules http://github.com/ppy/osu
cd osu
dotnet restore
```
then open the repo in vscode and build the project using the preset launch tasks.

**Comment by peppy** [comment]
Closing this for now. I think the above post should be ample to resolve the issue.
