### ISSUE TITLE
Song select shows deleted beatmaps

### ISSUE THREAD

**Issue by peppy** [ppy/osu#3382]
- Open song select
- Return to main menu
- Delete all beatmaps
- Open song select

There will be beatmaps in the background (behind the import prompt) that should not be displayed. We are likely not binding to Add/Delete events of the manager early enough.

**Comment by qwewqa** [comment]
This happens to me when I open and close song select while it is still deleting.

It looks like this happens because of the following reasons
- Database changes from the deletion are not saved until after all beatmaps are deleted. When each individual beatmap is "deleted", it is removed from the current carousel but the change is not saved to the database until the batch deletion has finished.
- When you return back to menu, a new song select instance is created.
- That loads the beatmaps from the database, but the database changes from deletion are not saved yet
- This means that any beatmaps that were already "deleted" are loaded
- Songs that hove not been "deleted" yet are removed from the carousel as they are "deleted", but beatmaps that have already been "deleted" are not.

**Comment by peppy** [comment]
Has been resolved.
