### ISSUE TITLE
osu-lazer on linux no audio

### ISSUE THREAD

**Issue by Puffycheeses** [ppy/osu#3471]
When running osu-lazer! while another audio source is playing no sound plays and console outputs:

```
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
``` 

Running latest version

installed with `yaourt -S osu-lazer-git`

**Comment by WebFreak001** [comment]
are you playing sound when the game starts? I need to have some sound playing for the sound device creation to work properly too, afterwards when osu is running I can turn off whatever I was running again and it still works.

**Comment by Puffycheeses** [comment]
It only works if no other audio is playing

**Comment by qwewqa** [comment]
Do you have pulse audio installed?

**Comment by jai-x** [comment]
@Puffycheeses Please refrain from using the AUR osu!lazer package as it is unsupported.

If you would like to run osu!lazer on Linux, you can download and compile it yourself. Instructions are in the readme.

On arch linux, the build toolchain on depends on having the `dotnet-sdk` and `git` packages installed.

**Comment by morguldir** [comment]
@jai-x The AUR package is completely fine, its basically just a shell script that compiles it with the same instructions that you would normally use

@Puffycheeses Please post your runtime.log, it should be at `~/.local/share/osu/logs/runtime.log` or `$XDG_DATA_HOME/osu/logs/runtime.log` if you have that variable set

**Comment by redstik** [comment]
Try changing the sound device, this worked for me. if not, try https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting this guide, as im assuming you are using pulseaudio with ALSA.

**Comment by smoogipoo** [comment]
We may want to consider init-ing with `BASS_DEVICE_DMIX` if the exclusive device fails to open.

**Comment by Chermnyx** [comment]
I've resolved this issue by `rm ~/.local/share/osu`. Changing the sound device haven't worked for me.

**Comment by Zyfarok** [comment]
Just like Puffycheeses states, on my Archlinux setup (with osu-lazer installed from the osu-lazer AUR package, plasma as desktop, and Pulseaudio with ALSA for the audio), I have the sound **if and only if** no other application uses the sound when I launch osu-lazer.

Also, I would like to add that if osu-lazer was started without any other application playing sound (and that osu-lazer actually plays sound correctly), then **MOST of other application can't use the sound anymore until osu-lazer is closed**. (discord and osu!stable (via wine, using pulse) can't play audio, but SMPlayer/mpv can though)

I suppose it's because osu-lazer is using ALSA and blocking the pulseaudio driver in some way...

If ALSA was somehow choosen instead of pulseaudio for latency reasons, please note that pulseaudio doesn't add much latency if configured correctly as you can see in ThePooN's guide for osu! stable on wine : https://blog.thepoon.fr/osuLinuxAudioLatency/

**Comment by peppy** [comment]
Did you try changing the output device to pulseaudio?

**Comment by Zyfarok** [comment]
If you mean the "PulseAudio Sound Server" out there, it doesn't work.
![image](https://user-images.githubusercontent.com/10669609/60852838-b4936d00-a1f9-11e9-858e-9afc0b8cf749.png)

**Comment by peppy** [comment]
You're going to have to debug why this doesn't work. Linux per-system / per-distro compatibility issues are not a focus for us, but we do welcome PRs improving the situation.

**Comment by Zyfarok** [comment]
Are you saying that because it was tested on and works great on other distros ? If yes, then yeah I'll give it a try when I'll have the time.

Note : And here is the confirmation that it's using ALSA
![image](https://user-images.githubusercontent.com/10669609/60852997-83676c80-a1fa-11e9-8ce4-b0a0012acf01.png)

**Comment by peppy** [comment]
osu! will use whatever device you select in output.

**Comment by Zyfarok** [comment]
Ok, after seeing this post : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913045
I fixed it by creating some .asoundrc file with :
```
ctl.dmixer {
type pulse
}
pcm.pulse {
type pulse
}
ctl.pulse {
type pulse
}
pcm.!default {
type pulse
}
ctl.!default {
type pulse
}
```
Inside my home directory

Could be useful for anyone else having this issue, but I guess it's more of an ALSA or archlinux issue (wrong defaults ?) than an osu!lazer issue.

Sorry for the annoyance, but at least I guess this issue can be closed ?

**Comment by peppy** [comment]
Closing for now.

**Comment by Nomeji** [comment]
I think it's mostly a ArchLinux issue since the pulseaudio-alsa isn't installed by default. Installing it fixed the issue for me. Just followed the instructions here: https://wiki.archlinux.org/index.php/PulseAudio#ALSA

It's still kind of bug. osu shouldn't be using ALSA directly. ALSA can only have one audio source at time. What osu is trying to do here is to take full control of the selected sound card. If another program is already using this card (pulseaudio) it fail and give this error: ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave. The pulseaudio-alsa package is a workaround that route ALSA audio to Pulse. A real fix should be to add PulseAudio support in osu.
