### ISSUE TITLE
Linux Bitmap/Song and Skinks directory(s)

### ISSUE THREAD

**Issue by Kardzhilov** [ppy/osu#3487]
Installed it works great but i can't locate where it is storing the bitmaps and skins. 
I would like to import the original skin from the non Lazer version and maybe change the directory for songs but there is no in-game reference to their location.

**Comment by peppy** [comment]
You can drag .osk files into the window or use command line to specify them as an argument on startup.

**Comment by Alexmitter** [comment]
@peppy the problem is, due to the new folder structure of which i still don't get smart of, it is not possible to just import your old beat-maps into osu!lazer on linux.
OT: Is there any big reason to the new folder structure, would it not be possible to at least choose a path were the old song library sits?

**Comment by smoogipoo** [comment]
We will probably add an option to select the beatmap/songs folder to import from via the "Import from stable" button at some point, but it isn't an immediate goal right now. For now you can just create a symlink for the `Songs` folder in `~/.osu`.

**Comment by Alexmitter** [comment]
@smoogipoo would it not make sense to have both import and export from and to the old format? Sharing one osu song library over two PCs or even moving to a new of just get harder with the new format.

**Comment by smoogipoo** [comment]
No, because the databases are incompatible. We will have an import process but not an export process.
