### ISSUE TITLE
install.exe can't install osu!lazer

### ISSUE THREAD

**Issue by technovn** [ppy/osu#3524]
The install.exe gives me this error everytime I try to install lazer, and somehow it doesn't work ***even when I try to install it in VM***

> Error:
![this is the error](https://user-images.githubusercontent.com/36879694/46335391-75743200-c651-11e8-97e8-f649a771ed71.png)

> Setup log: 
[SquirrelSetup.log](https://github.com/ppy/osu/files/2436950/SquirrelSetup.log)

If you need, my system is Windows 7 32-bit

**Comment by technovn** [comment]
Oh ok, thanks for the information

**Comment by ticotaco72** [comment]
@techovn you can compile lazer yourself for 32bit system. Instructions are described in Readme.md

**Comment by JWWolstenholme** [comment]
I'm also getting this but I'm on 64-bit Windows 10.

[Setup Log](https://pastebin.com/tdJqvwCj)

**Comment by Zmxhawrhbg** [comment]
@JWWolstenholme

The error described in your log is something different than the issue describes. Your error seems to be related to something having an open handle on the osu executable when trying to delete the old folder (due to you trying to update an old lazer version). This could be due to a virus scan or the like. Restarting usually fixes the issue when I get it with other processes.

**Comment by JWWolstenholme** [comment]
@Zmxhawrhbg 

Ah, alright. Thanks for the info.

**Comment by peppy** [comment]
Closing in favour of #3984.
