### ISSUE TITLE
Osu!.exe crash

### ISSUE THREAD

**Issue by pjlazuli** [ppy/osu#3556]
I'm trying to open osu lazer after finishing istalling it but it only show the blank pages and then it stopped...btw my os is window 8.1 pro 64bit

**Comment by miterosan** [comment]
Please provide logs. Both osu!lazer logs and also windows logs. 

You can find the laser logs by navigating to ``C:\Users\**YOUR_WINDOWS_USER_HERE**\AppData\Roaming\osu\logs``

You can find the windows logs by opening ``eventvwr.msc`` or ``Event Viewer``.
In there you click on ``Custom Views``, and then on ``Administrative Events`` 
You should be treated with a list of messages. You can click on them to get more details.
Please share the one that includes the word osu.

**Comment by smoogipoo** [comment]
According to microsoft: https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x

**For Windows 8.1 and earlier versions, or Windows Server 2012 R2 and earlier versions:**

Make sure that your Windows installation is up-to-date and includes [KB2999226](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows), which can be installed through Windows Update. If you don't have this update installed, you'll see an error like the following when you launch a .NET Core application: The program can't start because api-ms-win-crt-runtime-1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.

**For Windows 7 or Windows Server 2008 R2:**

In addition to KB2999226, make sure you also have [KB2533623](https://support.microsoft.com/en-us/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot) installed. If you don't have this update installed, you'll see an error similar to the following when you launch a .NET Core application: The library hostfxr.dll was found, but loading it from C:\<path_to_app>\hostfxr.dll failed.
