### ISSUE TITLE
Ability to change game mode/ruleset in profile page

### ISSUE THREAD

**Issue by plankp** [ppy/osu#3606]
Currently if you open a player's profile in osu, it only shows the status (level and ranking) of the default game mode. It would be nice if, just like the webpage, you can switch between the game modes.

**Comment by peppy** [comment]
Bumping to P1 as this is a pretty huge oversight.

**Comment by bdach** [comment]
So my initial attempts today yielded a big obstacle to adding this. The overlay as a whole is heavily dependent on bindable flow. Unfortunately `APIUser` implements `IEquatable` since https://github.com/ppy/osu/pull/8029/commits/ffa8a50c6bcddfd643c6a5abd3c213b4fb750e2e, which means that if I have an `APIUser` with an ID and stats for osu!, and try to replace it with an `APIUser` with the same ID but stats for a different ruleset, nothing happens because bindable equality decides that the models are equals and the value didn't change.

Ergo, I need to get rid of the equality override. Because I was long fed up with how overloaded `APIUser` was with usages (it's everywhere, has all fields ever even if the appropriate endpoints don't return them, and for no real good reason too), so I thought that this could be a good time to start splitting it up, except that to do it, I'd have to reimplement the entirety of the data structures, and add copies of existing requests too (because `GetUserRequest` is in `APIAccess`, i.e. the thing everything relies on).

Going to have a think about this. The ugly way for now may be to wrap the `APIUser` in whatever else reference type to trick the bindable flow into firing value changes. Not sure.

**Comment by bdach** [comment]
Spent most of today trying the compromise solution of extracting a new type (tentatively named `UserProfile`) to wrap the `APIUser`. Got to the point where changing ruleset is now possible, although I did touch a metric ton of files trying to beat the overlay into shape. It's feeling... alright. Not great, not terrible.

I think that what I have is as good as can get for now honestly, so I'll be splitting that into relatively digestible pieces and PRing those once I feel there is review bandwidth available for it. May spend the rest of the weekend doing a design refresh on the overlay too.
