### ISSUE TITLE
beatmap detail overlay shows nothing

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#3635]
![osu_2018-10-24_23-45-05](https://user-images.githubusercontent.com/32620809/47464160-b1319000-d7e8-11e8-84a1-f0ba47276b61.jpg)
![osu_2018-10-24_23-48-07](https://user-images.githubusercontent.com/32620809/47464161-b1319000-d7e8-11e8-877a-35224392db75.jpg)
[database.log](https://github.com/ppy/osu/files/2512483/database.log)
[debug.log](https://github.com/ppy/osu/files/2512484/debug.log)
[network.log](https://github.com/ppy/osu/files/2512485/network.log)
[performance.log](https://github.com/ppy/osu/files/2512486/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2512487/runtime.log)

maybe related to that i can't find this beatmap on osu.ppy.sh now

**Comment by ticotaco72** [comment]
similar here:
![osu_2018-10-24_23-51-36](https://user-images.githubusercontent.com/32620809/47464376-42086b80-d7e9-11e8-8df4-abc5744dba15.jpg)

can't find id s of this

maybe they're deleted by mappers?

**Comment by ticotaco72** [comment]
id of toy: 785843
id of odd future: 783489

**Comment by smoogipoo** [comment]
I believe this should be resolved by https://github.com/ppy/osu/pull/3632

**Comment by peppy** [comment]
Have you tried deleting the beatmaps, restarting lazer, then reimporting?

**Comment by Joehuu** [comment]
https://github.com/ppy/osu/blob/55a8e88609940dd4d1d3552e4e35dd39346280bd/osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmapSet.cs#L132-L133

https://github.com/ppy/osu/blob/55a8e88609940dd4d1d3552e4e35dd39346280bd/osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmap.cs#L183-L184

The context menu item to open the overlay shouldn't appear if there isn't an ID associated with the beatmap. Deleting beatmapset / adding more diffs on the website mess up this local check, so updating local beatmaps is the solution (tracked in https://github.com/ppy/osu/issues/4823).

Closing this as both visual issues (no loading feedback in beatmap overlay and details not showing) have since been resolved.
