### ISSUE TITLE
Osu!Lazer wont open or load.

### ISSUE THREAD

**Issue by deadlymffin** [ppy/osu#3653]
I just downloaded osu!lazer and when I first downloaded it, it said "osu!lazer did not install correctly" and there was 2 options, "Re-install with correct settings" and "This program is installed correctly" I chose the _re-install_ option. After it "re-installed", I couldn't open it. My cursor turns into the loading cursor but nothing happens or pops up.

**_SIDE NOTE: I am not good or have lots of experience in programming, or know what to do in situations like this, if I have to program something I might need some help._**

**Comment by smoogipoo** [comment]
Check your `%appdata%\osu\logs` folder for any log files, and if there are none, check your windows event viewer for any ".NET Runtime" logs.

**Comment by RealBobTheBlob** [comment]
What computer specs do you use? I don't think 32bit works with osu!lazer, correct me if I'm wrong though.

**Comment by deadlymffin** [comment]
> What computer specs do you use? I don't think 32bit works with osu!lazer, correct me if I'm wrong though.

wait why are you here? whatever, mine is 64bit .

**Comment by deadlymffin** [comment]
> Check your `%appdata%\osu\logs` folder for any log files, and if there are none, check your windows event viewer for any ".NET Runtime" logs.

I cant seem to find any osu! file in %appdata%, only in %localappdata%. In my localappdata logs there are 2, runtime and update_success.
![screenshot_23](https://user-images.githubusercontent.com/44560851/47790425-1ab61f00-dd52-11e8-8d23-85c0638ff2bc.png)

**Comment by deadlymffin** [comment]
I also noticed that I have missing info, here are my specs.

![screenshot_24](https://user-images.githubusercontent.com/44560851/47790591-8dbf9580-dd52-11e8-932e-80bb0c0494f0.png)

Also I noticed osu!Lazer is on %localappdata% with my osu!stable. Is is supposed to be like that?

**Comment by Morilli** [comment]
> Also I noticed osu!Lazer is on %localappdata% with my osu!stable. Is is supposed to be like that?
Yes, osu!lazer installs in %localappdata%, although it stores its data in %appdata%. If there is no osu folder as you said, it means osu!lazer didn't create any post-installation files. Did you check your windows event viewer for more information on any occuring errors?

**Comment by deadlymffin** [comment]
I don't know how to use Windows Event Viewer, but it seems like there is no errors. There might be but I have no idea how to use windows event viewer. Sorry :cry:

**Comment by FreezyLemon** [comment]
1. Try to open lazer again (to get a "new" crash)
2. Open the Event Viewer
3. Go to "Windows Logs" -> "Application"
4. There should be an error somewhere high up in the list. Check if that says anything about ".NET", and if it does, post the information here.

Hope I could help!

**Comment by smoogipoo** [comment]
According to microsoft: https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x

**For Windows 8.1 and earlier versions, or Windows Server 2012 R2 and earlier versions:**

Make sure that your Windows installation is up-to-date and includes [KB2999226](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows), which can be installed through Windows Update. If you don't have this update installed, you'll see an error like the following when you launch a .NET Core application: The program can't start because api-ms-win-crt-runtime-1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.

**For Windows 7 or Windows Server 2008 R2:**

In addition to KB2999226, make sure you also have [KB2533623](https://support.microsoft.com/en-us/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot) installed. If you don't have this update installed, you'll see an error similar to the following when you launch a .NET Core application: The library hostfxr.dll was found, but loading it from C:\<path_to_app>\hostfxr.dll failed.
