### ISSUE TITLE
Bug with @ Key on german keyboard layout.

### ISSUE THREAD

**Issue by Mempler** [ppy/osu#3658]
I've just noticed that when you're pressing the key `@` (`alt gr + q`) you also have to press another key to get the `@` character.

![Proof](https://s.mempler.de/2018-10-29_20-10-15.gif)

(Tested on latest git clone)

[Runtime Log](https://s.mempler.de/runtime.log)

**Comment by jorolf** [comment]
The issue is a global osu-framework issue. You should probably close this issue and reopen it on the other repository.

**Comment by jorolf** [comment]
The problem is that ``TextBox`` returns early when either super or ctrl is pressed. (AltGr is (in most cases) identical to ctrl + alt). This causes ``@`` (and other character that are typed with AltGr) to not update the pending input.
https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/UserInterface/TextBox.cs#L649

The culprit seems to be https://github.com/ppy/osu-framework/commit/35e0782f because before that commit text input was handled _before_ ctrl was checked

**Comment by Mempler** [comment]
Ok, i'll move this issue to framework when i'm home ^^
