### ISSUE TITLE
certain songs eat up all the RAM while importing

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#3757]
**Describe your problem:** Certain maps cant be imported due to extreme High RAM usage. In this case: https://osu.ppy.sh/beatmapsets/478093/#osu/1029976 as soon you import this map RAM usage goes to 100% ( i have 8GB RAM ) and lazer freezes and crashes a while later 

**Screenshots or videos showing encountered issue:** N/A

**osu!lazer version:** 2018.1120.0

**Logs:** N/A nothing to see there other than "Importing sky_delta - Grenade (MinG3012)..."

**Comment by qwewqa** [comment]
Is this not a dupe of #750? Referenced beatmap has -infinity bpm.

**Comment by bdach** [comment]
The referenced beatmap seems to import fine on 2019.1021.0, albeit it does seem to raise some parsing issues due to the aforementioned out-of-range BPM. But since this issue is mostly about RAM usage, I'm going to close this for now - please reopen or open another one if any new cases are spotted "in the wild".
