### ISSUE TITLE
osu!lazer won't open

### ISSUE THREAD

**Issue by kravque** [ppy/osu#3966]
screenshots: http://prntscr.com/m0w7sz

osu!lazer version 2018.1228.0

*logs* there is no log for this bug

---------------

oky so when i open the osu!lazer.exe there is nothing shows up
i tried to see the taskmanager and nothing happend it's like i didn't open it
and i downloded the last NET.Framework 4.5.2
and it didn't work
i disabled the windows defender and it didn't work
deleting it and installing it again didn't work
changing the file location didn't work

the version of the OS is Windows 7 ultimate x64 Version 6.1 (Build 7601: Service Pack 1)
RAM: 2GB (uses 1.89 of it)
proccesser: intel Celeron (1.6GHz)
graphics card: intel (R) HD Graphics Family ( the VRAM is close to 128MB )
so why?

**Comment by EVAST9919** [comment]
Osu!lazer doesn't work with Intel HD graphics yet.

**Comment by SpeedIDNSTORM** [comment]
When the osu!lazer support Intel HD graphics??

**Comment by Appreciativeness** [comment]
@EVAST9919 Explain how Intel HD Graphics 620 works then? Is it older HD Graphics models that cause this?

**Comment by ticotaco72** [comment]
It does work on Intel HD graphics.
And even if not there would be some logs. It's something else causing problem.

**Comment by SpeedIDNSTORM** [comment]
Have any way to run it?

**Comment by smoogipoo** [comment]
@kravque Can you list more exact specs of your PC?

Also it's likely that the error was eaten up and sent to your windows event viewer logs instead, so check that too.

**Comment by kravque** [comment]
@smoogipoo yes i tried and there is no log too

and there is no need to show more about my pc specs
but there you go http://prntscr.com/m7fkkh

**Comment by kravque** [comment]
@ticotaco72 i tried no log

**Comment by smoogipoo** [comment]
Are you able to run osu!stable? If so, can you post the logs from it in here?

**Comment by smoogipoo** [comment]
According to microsoft: https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x

**For Windows 8.1 and earlier versions, or Windows Server 2012 R2 and earlier versions:**

Make sure that your Windows installation is up-to-date and includes [KB2999226](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows), which can be installed through Windows Update. If you don't have this update installed, you'll see an error like the following when you launch a .NET Core application: The program can't start because api-ms-win-crt-runtime-1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.

**For Windows 7 or Windows Server 2008 R2:**

In addition to KB2999226, make sure you also have [KB2533623](https://support.microsoft.com/en-us/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot) installed. If you don't have this update installed, you'll see an error similar to the following when you launch a .NET Core application: The library hostfxr.dll was found, but loading it from C:\<path_to_app>\hostfxr.dll failed.

**Comment by Jack13213** [comment]
mine just open but crash fastly like if it was a ghost app

**Comment by bdach** [comment]
@Jack13213 please stop spamming random unspecific comments and provide actual details. we will not help you otherwise.
