### ISSUE TITLE
black screen on start, only sound

### ISSUE THREAD

**Issue by HipHopCat** [ppy/osu#4068]
when I open the game the screen stays black, the "welcome to osu" sounds and the music starts, it lets me move through the menus and even select song but I can not see anything on the screen only black

**Comment by smoogipoo** [comment]
Does it fix itself when you resize the window by any chance?

**Comment by HipHopCat** [comment]
what happens is that when the screen starts it goes black immediately then I can not access the settings in any way

**Comment by jvyden420** [comment]
Try pressing alt+enter to switch to windowed. Does anything change?

**Comment by HipHopCat** [comment]
mixing the 2 solutions they gave me (window mode and the size of the tab) works but in an exact resolution and sometimes the audio is gone

**Comment by kultajaba** [comment]
I have this issue almost every time I start up osu. I haven't discovered a permanent solution but here is what works for me every time: Start up osu so that I hear the sounds and see black press ALT + ENTER to go into windowed mode and still see black. Press ALT + F4 to close osu. Open osu back up and this time it starts full screen working fine.

**Comment by smoogipoo** [comment]
@HipHopCat Please try the newest release (2020.714.0).
