### ISSUE TITLE
Taiko FL proposal (score v2)

### ISSUE THREAD

**Issue by pavlukivan** [ppy/osu#4120]
currently it seems really unbalanced - it's very rarely used alone, just on really short maps with slow SV. Indeed, if you remember the map you can just use HDFL that is nearly the same on longer maps. My proposal is to buff FL by increasing it's visible area (maybe to something that allows you to see the same note amount as playing HR in 4:3 resolution, or around that) and disabling/reducing it's scaling based on combo. That way sightreading with FL becomes actually possible so people will use it more against HDFL.

**Comment by pohmx** [comment]
that would just be inverted HD, then what's the point of having a FL mod at all... I don't see the point in making every mod combination possible, that would make it both, fun and boring... Because of course you have freedom in choosing but then playing an impossible mod combination would lose it meaning cuz there would be nothing impossible
