### ISSUE TITLE
Mobile Input Methods

### ISSUE THREAD

**Issue by miterosan** [ppy/osu#4201]
I think that osu! on mobile requires proper touchscreen support. Just adding a virtual mouse or keyboard is not enough.  

## osu

the osu ruleset should be controlled by having Finger 1 as the cursor position. Finger down  counts as a click and start of hold down. Finger Up counts as the end of the hold down.

Example from osu!revolution (fork of osu!droid): https://www.youtube.com/watch?v=x9_0JWgw-3A

## catch

~~Moving the finger 1 over the screen offsets the catcher. If finger 2 is put on the screen, then hyper drash is activated until finger 2 gets removed from the screen.~~

Split the screen into two halves horizontally. The left half moves the catcher to the left and the right to the right. Holding the second finger down activates dashing.

## mania

Finger down counts as a click and hold down. Finger up counts as the end of hold.

Example: www.youtube.com/watch?v=XMi1MNXKAGg

## taiko

Split the screen in 4 sections that correspond to the section of the drum. Finger down is a click.

Example: www.youtube.com/watch?v=wbL11_vJSEo

**Comment by swoolcock** [comment]
The default input style for osu! standard should essentially be the same as osu!stream.  If we were to implement the touch style you’ve demoed here, it would need to be an option the user can enable, rather than the default.

**Comment by HoLLy-HaCKeR** [comment]
I wouldn't use dragging a finger as the only option for catch, it wouldn't be responsive enough for levels above 2 stars. Perhaps splitting up the playfield into areas that trigger left, right, and dash?

Some options, starting from best:
- Splitting screen into 3 areas horizontally, with left being dash and middle/right being moving left/right respectively. Dash area could take up either 50% of 33% of the screen. This resembles keyboard play more and should be the easiest way to play.
- Splitting screen into 2 areas horizontally, touching each area to move that direction. Dash could be triggered with 2 fingers? This wouldn't be optimal for high-level play, but fine for casual play
- Dragging left/right, using second finger for dash (as described in first post). Also find for low-level casual play.

For standard, I'd also prefer the osu!evolution style to be available, otherwise streams are neigh-impossible.

**Comment by LeNitrous** [comment]
There should instead be options to choose between a virtual keyboard or traditional touch screen for standard and catch to fit the best of both worlds.

**Comment by peppy** [comment]
I believe virtual controls will be enough to cover all scenarios. It will be an option in addition to non-virtual modes which have per-ruleset implementations.

Related to #4195.

**Comment by milankkk** [comment]
Is this still going to be a thing?

**Comment by swoolcock** [comment]
When one of us has the time to implement it.  Feel free to submit a pull request if you want to contribute.

**Comment by 40m41h42t** [comment]
Some android devices support OTG input, like Huawei Pad M6. In this way mouse and keyboard can be linked. However, in-game cursor seems not support OTG-mouse, will this be fixed?

**Comment by khalid151** [comment]
Samsung Note devices have a Wacom digitizer built-in. But hovering with the stylus isn't working. It should be the same as moving a mouse around the screen.

Should this be on a different issue by itself?

**Comment by smoogipoo** [comment]
@khalid151 https://github.com/ppy/osu/issues/6401

**Comment by RayOfDoom** [comment]
This has been under discussion for over a year, and unfortunately I still don’t see an option for it. What has caused this and similar issues to be put into low priority?

**Comment by jai-x** [comment]
Ensuring the osu!lazer desktop version has feature parity with osu!stable takes priority over adding mobile specific features.

**Comment by mcendu** [comment]
> This has been under discussion for over a year, and unfortunately I still don’t see an option for it. What has caused this and similar issues to be put into low priority?

There isn’t proper multitouch support yet.

**Comment by peppy** [comment]
There are open PRs framework-side with initial implementations of touch input. These need to be reviewed and merged for any further progress to happen.

It will happen when we have the bandwidth. Our focus is still on desktop primarily.

**Comment by recognitionmark** [comment]
Alright, so as usual, osu!lazer is now focused on desktop. But, what if I suggest some ideas for inputs?
STD - Use either osu!droid input or osu!stream input (toggleable in settings)
CTB - split the screen, and doubletapping causes hyperdash, doubletapping again cancels it.
Taiko - make 4 halfcircles (near opaque) for the buttons.
Mania - convert the screen vertical and play it like a touchscreen mania rhythm game.

**Comment by bdach** [comment]
@recognitionmark as far as I can see you've basically restated the ideas in the opening post, save for the catch idea.

**Comment by gabeis** [comment]
agreed

**Comment by akuza55555** [comment]
Could these controls also be implemented in the desktop version? I have a tablet pc and I want to map and play with it without having to use any external peripherals. I think you could add a "touch mode" toggle into the settings that would enable these controls or something.

**Comment by bdach** [comment]
I believe adding this universally (so for desktop too) was planned, but I can't find where that was stated.

**Comment by akuza55555** [comment]
Alright. Is it possible to give any estimation on when it'll get implemented?

**Comment by bdach** [comment]
No. See `low-priority` label. Completing the experience for desktop comes first and foremost.

**Comment by Blue-Beaker** [comment]
When this is implemented whether touchscreen controlls can be enabled on the desktop version for windows/linux touchscreen device for example a x86 tablet?

**Comment by frenzibyte** [comment]
If you're referring to the virtual controller from https://github.com/ppy/osu/issues/4195, then yes it'll be an option in the settings.

**Comment by xslendix** [comment]
I was thinking of the input implementation on this and I started looking at BeatX. For mania and taiko, you can split the screen vertically in 4 quadrants. They can also be overlapping, as for catch, something like how malody

**Comment by xslendix** [comment]
I also thought about dynamic skins, which for example, would make bars longer thus covering a bigger screen area

**Comment by peppy** [comment]
Please refrain from commenting unless you are looking to implement this feature. We don't need suggestions for the initial implementation (it's a fairly simple and straightforward system to imagine).

**Comment by heikomaru** [comment]
The truth is, certainly, the current Osu! Lazer only looks like a port from PC to Android, but the question if it is going to be a mobile game, this must be coupled with what has been said, it is not much use that you put PC options if most of you have mobile It is more in other places nobody would take a mouse and a keyboard to play a mobile game, but certainly the other OSU model! What is the Osudroid that I catalog as something that did work and thought it was for Android, how bad is that osu! is that it no longer receives support for which there are no updates, instead the lazer is much better because of the accessibility environment and optimal graphics

**Comment by dumb-stuff** [comment]
still waiting.....

**Comment by jayson2468** [comment]
One question.
How to implement the input?
I have search in the settings to how to implement this and I find nothing.Please help.

**Comment by frenzibyte** [comment]
You may be confused here. I'm not sure what you mean by "implement", but there is *no* support for mobile input methods in gameplay currently, hence why this issue is open. You'll need an external keyboard/mouse connected or otherwise for the time being.

**Comment by funnym0th** [comment]
> ## taiko
> Split the screen in 4 sections that correspond to the section of the drum. Finger down is a click.
> 
> Example: [www.youtube.com/watch?v=wbL11_vJSEo](http://www.youtube.com/watch?v=wbL11_vJSEo)

Wouldn't it be better if it was like the original Taiko controls for touchscreens? A inner circle in the bottom of the screen for Don notes and the rest of the screen for Ka notes (e.g Taiko no Tatsujin games for DS and 太鼓の達人+ for Android)

**Comment by Cutiebestgoon** [comment]
Would the drag and click be resolved on osu!iOS because it is quite uncomfortable using one finger and not being able to stream like i would on pc, please make it where you can drag and click input

**Comment by frenzibyte** [comment]
Yes, that's the point of this issue thread.

**Comment by JustAHippo** [comment]
any update on the standard osu! getting touch fixed in the style of osu revolution? its been quite a while now.

**Comment by reco1I** [comment]
### osu!std touch 

I would like to do this implementation by myself but unfortunately i can't make a PR right now.

Looking around the issue in touch devices (you can't stream) I found something that can be good and a working solution.

osu!std allows only 2 triggers/buttons (B1 and B2) that can hit circles. Now that's a mess when it comes to touch screens and specifically multi touch.

My proposal to handle that on a touchscreen is determine if the cursor triggers or not.

When there's no cursor (no touch points):

- If user single tap and its touch point position is inside a hit circle consider it as cursor and trigger B1 then release it instantly.

- If user single tap and its touch point position is inside a slider/spinner consider it as cursor and trigger B1 then release once note is over or if user lift the finger (or in the case of sliders if user moves outside slider ball).

- If after any of the 2 cases above user starts dragging once note is over consider that touch point as cursor without triggering B1 (released).

When there's already a cursor (a touch point that it's considered as cursor because dragging):

- Any touch point that's not the cursor consider it as a button trigger (B1 or B2 depending of which buttons are released)

Important concern:

- Cursor can only be one so if it's already a cursor it will not change until the user lift the finger.

Hope you understand, anyways you can ask if i not considering any case.

**Comment by peppy** [comment]
Thanks for your proposal. It's indeed one of the directions I have already tried. The difficulty comes from deciding when the "release" should happen on touches which have not actually been released. There's also a consideration that mobile players will be able to "triple tap" as a result, giving a slight advantage over what you can do on desktop platforms.

No further feedback is required, but you're welcome to think about it on your own! It's already assigned to me and I intend to see it through to completion.

**Comment by reco1I** [comment]
> 

I specified when release should happen but i guess you referring to some code-wide difficulty to approach that.
Now the triple tap can be reach in desktop platforms with a sequence of M1, K1 and K2. It's hard but it's possible or I'm not getting what you mean. Anyway thanks for you consideration.

**Comment by peppy** [comment]
It's not possible on desktop. You need to release M1 physically first. That would not be the case with any usable multi-touch implementation.

It's not a show-stopper, but something worth understanding as we figure touch screen balance.

**Comment by reco1I** [comment]
> 

First thing: If cursor is triggering then that button got locked so there's not possibility to do a "triple tap" since one button will be locked until it goes released. (Could be easily handled if touch input were indexed)

Last thing make sense and i believe only happens for hit circle, I have a new consideration about how release should happen in that case (hit circle): 

- Release it when user lift finger or starts a move event / dragging.
- When there's a cursor and user taps with another finger automatically release the cursor trigger (if it's triggering) and transfer the trigger to that new touch point.

I think there's where we can get the human "release time" avoiding lightning touches.

**Comment by peppy** [comment]
It can't be locked. Think through it again.

Thanks for your feedback but I won't be responding further. Work through it on your own.
