### ISSUE TITLE
First game with autoplay on any map removes background dim completely

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#4204]
How to reproduce: just start any map with autoplay (by adding a mod or pressing Ctrl+Enter - no matter). After few seconds background dim will be removed. Btw dim Bindable isn't changing.
Example (thanks @KoziLord): https://streamable.com/3fhjl

**Comment by peppy** [comment]
can't reproduce

**Comment by KoziLord** [comment]
Can reproduce, however instead of the background being dimmed to pitch black the dim disappears completely.

Steps to reporoduce (build 2019.131.0):Go from the main menu to play, solo, launch any map with autoplay on. The background dim should fade away after random amount of time.

Video example: https://streamable.com/3fhjl

**Comment by EVAST9919** [comment]
oops, I meant this ^

**Comment by peppy** [comment]
This doesn't look related to autoplay, it looks specific to break time?

**Comment by peppy** [comment]
It's likely that BreakOverlay is incorrectly using FadeAlpha/FadeColour after https://github.com/ppy/osu/pull/4131.

**Comment by KoziLord** [comment]
The fade out being so close to a break in the recording seems to be a coincidence as it also happens on maps without any breaks and there doesn't seem to be a pattern as to when it's gonna happen (sometimes it happens right at the start, sometimes at the middle or near the end).
