### ISSUE TITLE
Osu!Lazer not open on iOS 10.2

### ISSUE THREAD

**Issue by chriskjpk** [ppy/osu#4239]
I downloaded osu!lazer on TestFlight I tried to open it but it crashes immediately (IOS 10.2 on IPhone 6s Plus

**Comment by peppy** [comment]
This is a known issue due to high memory usage. Will eventually be fixed, with a bit of luck.

**Comment by daniel11420** [comment]
I'm on a 6s and it works perfectly. You might want to update ios, you are waaay behind and it works on the latest ios on 6s

**Comment by MarcoProlo** [comment]
It is true that updating ios is a solution around it. But for some people, they just want to stay at that particular version because there are too many restrictions in ios 12. Once you updated, you can't go back down if you regret getting the update

**Comment by Joehuu** [comment]
> This is a known issue due to high memory usage. Will eventually be fixed, with a bit of luck.

During the time this issue was made, an iPad mini 2 (iOS 12) crashes on direct, past the player loader, and song select with more than one song downloaded. Now, it can handle direct while in song select and play average maps throughout without crashing mostly.

@chriskjpk performance improved, and suggest you try it again.

The comments here seem like it is an iOS version issue with the 6s. Nevertheless, lazer should be able to load with the improvements until now. Closing.
