### ISSUE TITLE
Minimising the game causes stuff to FLY

### ISSUE THREAD

**Issue by peppy** [ppy/osu#429]
https://streamable.com/j5mte

**Comment by Jorolf** [comment]
looks cool though ;)

**Comment by FayneAldan** [comment]
would look cooler if it all flew from the taskbar icon ;)

**Comment by peppy** [comment]
would be cooler if you fixed the issue rather than made such comments

**Comment by Arefu** [comment]
I vote we leave this bug in market as a "design" not a flaw.

Waiting for my boy Dean to say "fuck off" to me

**Comment by a1batross** [comment]
It looks like OpenTK sends a MouseMove event every maximize. In combination with parallax effects it gives this bug. 
osu! original client also have this bug(kind of). When maximizing, the mouse cursor trails appears on screen.

I tried to ignore MouseMove events when osu! is minimized, but due to lack of C# and OpenTK skills, it does not helped.

**Comment by thatsabop** [comment]
@a1batross - Try checking GetForegroundWindow with FindWindowA. For example,
`if(GetForegroundWindow() != FindWindowA((string)null, "osu!")) return;` or something of the sort.

**Comment by Nabile-Rahmani** [comment]
@thatsabop Platform-specific hack much ?
Even if this had to be done, it'd be preferable to use the window handle rather than finding the first window matching some title.

Besides, the framework exposes that already (`GameWindow.Visible`).

**Comment by peppy** [comment]
Resolved by https://github.com/ppy/osu-framework/pull/623.
