### ISSUE TITLE
StoryBoard not pausing when pausing the game.

### ISSUE THREAD

**Issue by jimchen5209** [ppy/osu#4476]
**Description:** StoryBoard keeps playing in background when the game is paused.

**Video showing encountered issue:** https://streamable.com/4hri3

**osu!lazer version:** 2019.314.0

**Comment by peppy** [comment]
do you mean animation frames?

**Comment by Zelaxion** [comment]
Its more that the animations start as soon as the song starts without the pacing of the original storyboard, they arnt halted to preserve the animations for specific parts of the song when you pause and they stop playing all together after all animations have been played back to back and you are left with a black background instead of the original background of the song. Furthermore if you switch songs after one the original song's storyboard has ended and is now black the next song with a storyboard will not play its own storyboard but still be a black background.
