### ISSUE TITLE
Random line in song select when hovering over the bottom bar

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#4515]
**Describe your problem:** When I hover the mouse cursor over the bottom bar in the song carousel, a random line shows up below the search bar. The line vanishes when the mouse is no longer over the bar. Its colour seems to change based on what song is selected.

**Screenshots or videos showing encountered issue:** 
[osu!lazer 2019-03-22 21-37-39.zip](https://github.com/ppy/osu/files/2998232/osu.lazer.2019-03-22.21-37-39.zip)

**osu!lazer version:** 2019.323.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/2998223/database.log)
[debug.log](https://github.com/ppy/osu/files/2998224/debug.log)
[network.log](https://github.com/ppy/osu/files/2998225/network.log)
[performance.log](https://github.com/ppy/osu/files/2998226/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/2998227/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/2998228/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/2998229/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/2998230/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/2998231/runtime.log)

**Comment by peppy** [comment]
For reference:

![image](https://user-images.githubusercontent.com/191335/54867416-47330c00-4dc3-11e9-9de4-b5782cfcf5af.png)

This is the result of the background wedge being parallaxed but not having enough excess draw region.

**Comment by Gabixel** [comment]
This seems to happen to the bottom bar too.

![image](https://user-images.githubusercontent.com/43073074/54878330-577ed180-4e2b-11e9-97a4-22d5f6b690d4.png)
(It's hard to see in these screenshots from small displays)
![image](https://user-images.githubusercontent.com/43073074/54878322-3f0eb700-4e2b-11e9-87f9-fbb06e5fe958.png)

But yeah, it's just a design problem caused by parallax, easy to fix I guess.
