### ISSUE TITLE
Problem with Fullscreen

### ISSUE THREAD

**Issue by GetterSetterAndDot** [ppy/osu#4558]
**Describe your problem:** After Alt+Tab the window  changes position (it moves down and right)

**Screenshots or videos showing encountered issue:** 
![Снимок экрана от 2019-03-30 02-10-14](https://user-images.githubusercontent.com/47123924/55267234-1b67c880-5292-11e9-9356-18085ccabbdb.png)

**osu!lazer version:** local release 
**OS:** Linux  Ubuntu 18.10

**Comment by peppy** [comment]
Is that your background to the left?

**Comment by GetterSetterAndDot** [comment]
> Is that your background to the left?

Yes, it is my wallpapers for Desktop

> We're going to need more details from you, since this is 99% going to be your DWM causing the issue.

 How I can help you (give some logs and so on and so forth, if yes, what)?

**Comment by peppy** [comment]
A video would be a good place to start, since it's hard to determine how the interaction is taking place currently.

**Comment by GetterSetterAndDot** [comment]
[2019-04-03_21-47-26.zip](https://github.com/ppy/osu/files/3040267/2019-04-03_21-47-26.zip)
Video in archive

**Comment by peppy** [comment]
I don't know. Have you tried turning off animations and stuff in your DWM? Or tried a different DWM?

**Comment by GetterSetterAndDot** [comment]
>  Have you tried turning off animations and stuff in your DWM? 

It doesn't help

> Or tried a different DWM?

In classic gnome lazer works stable, without this bug. In Wayland lazer throws this message: No protocol specified

**Comment by Ferdi265** [comment]
Also Linux-user here:

I've encountered that sometimes the cursor will drift to the lower-right or top-right. For me most often exiting and entering full-screen helps, and in all other cases I can fix it by restarting osu. (Window Manager is i3)

My theory is that the DWM and osu don't agree on whether the window is in full-screen or not, leading to osu calculation the cursor-position wrongly. I haven't verified this or tested this thoroughly, as it is not a pressing problem for me (since it happens rarely and I can workaround it).

**Comment by Ferdi265** [comment]
Nevermind, I just noticed the issue wasn't about cursor movement, but window movement

**Comment by GetterSetterAndDot** [comment]
In new version Ubuntu (19.04) problem doesn't exist, I think I can close issue
