### ISSUE TITLE
Some stacked objects shake incorrectly

### ISSUE THREAD

**Issue by peppy** [ppy/osu#4602]
https://puu.sh/DaRs2/c751faf49d.mov

**Comment by smoogipoo** [comment]
This is a super complex + deep issue. I haven't resolved it but I'm going to list my findings, so that it's not forgotten.

# Judgement results don't get reverted until after the result time is passed (not reached).

Suppose two stacked hitcircles, h1 then h2.

1. Rewind to h2.
2. Update h2 -> don't revert (time == result time).
3. Rewind to h1.
4. Update h2 -> revert (time < result time).
5. Update h1 -> don't revert (time == result time).

Solution: Check if moving backwards and revert judgements at time == result time.

# Input is handled before children update

(Assume the above issue is fixed)

Suppose two stacked hitcircles, h1 then h2.

1. Rewind to h2.
2. Trigger key press. h2 is already AllJudged = true due to not having been updated, key press falls through.
3. Update h2 -> revert h2's judgement.
4. Rewind to h1.
5. Trigger key press. h1 is already AllJudged = true due to not having been updated, key press falls through.
6. h2 handles the key press since it was previously reverted.
7. Update h1 - revert h1's judgement.

I.e. h2 handled h1's input.

Solution: Check if moving backwards, if so update children THEN update input (reverse order).

# SliderBall input propagates.

(Assume both issues above are fixed)

Suppose a slider, s1, and a hitcircle h1 positioned at the slider's end point some time after the slider.

1. Rewind to h1.
2. Revert h1's judgement.
3. Trigger key press.
4. Trigger result for h1.
5. Rewind to s1's end time.
6. Revert h1's judgement.
7. Revert s1's judgement.
8. Trigger key press.
9. SliderBall becomes Tracking = true.
10. Click is not blocked, h1 handles key press.

Solution:
* Update tracking in `SliderBall.OnPressed()` and block input if the tracking state changes.
* Sliders should be able to track at time == end time.

# HitObject result time offsets aren't reverted

Solution: Set TimeOffset = 0 on revert of the result.

# Some hitobject states don't get reverted

Some e.g. hitcircles begin with their approach circle at the end scale, sliders "pop" in.

Fixing the above issues still does not fix this one.

**Comment by smoogipoo** [comment]
Not entirely sure how I feel about my "proposed solutions", because they all (except for one) seem like hacks added in random locations to prevent specific events from occurring.

One thing we may want to do when we pass an important frame is:
1. Set time = frame time - 1
2. Update the subtree with _no_ input
3. Set time = frame time
4. Update the subtree with the frame's input

It would cover cases (1) and (2), and the slider wouldn't have to become trackable at its end time for (3). It's possible that this may also fix (5).
