### ISSUE TITLE
Beatmap intro skip doesn't behave the way stable does

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#4676]
**Describe the bug:** Generally lazer seems to seek not as far as stable does, so after every intro skip you have to wait longer for the map to start in lazer than in stable. Furthermore (not sure if related or not) on a map like https://osu.ppy.sh/beatmapsets/456986#osu/979232 it is simply not possible to skip in lazer, resulting in having to wait 7 seconds each time the map is loaded.

**osu!lazer version:** 2019.418.0

**Comment by Flaviu1817** [comment]
I researched the bug. The minimum beatmap start delay must be of ~ 3 seconds in order to use the `skip` feature. I checked the mentioned map with difficulty in both stable and lazer editors, and seems like it has ~ 2 secs delay. That means the player must wait ~ 5 seconds for gameplay to start, which is less than 6 (~ 3 secs from osu! delay, and ~ 3 secs from beatmap delay), so the non-skip behaviour is normal. This doesn't solve the problem since osu!lazer says 7 seconds. Debugging the code I found the following anomaly: the `startTime` shows 56 milliseconds, rather than ~ 2000. On other maps tested by me, without any modes, the value is normal. I tested everything without any mod on.
![image](https://user-images.githubusercontent.com/35461917/57026606-e0670500-6c42-11e9-8218-0bbc65cb4d7d.png)

**Comment by Morilli** [comment]
While the issue with this specific map seems to be resolved, I can still see some discrepancies between stable and lazer. Take for example [this map](https://osu.ppy.sh/beatmapsets/54631#osu/166019). The intro  is pretty long in stable, but it is not possible to skip, although now in lazer it is very much possible to skip about a full second. Is that intended?

**Comment by peppy** [comment]
We haven't matched them 1:1. So please report issues if they "feel" bad, not whether they match perfectly.

**Comment by Morilli** [comment]
Right now it certainly feels better than before, so I think this is fine the way it is.
