### ISSUE TITLE
Some maps have "reversed" objects at the end of a play

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#4705]
**Describe the bug:** After I played **[this map](https://osu.ppy.sh/beatmapsets/205777#osu/485540)** on multiplayer, I noticed that there's a weird bug if there's a spinner as the last object on a song. (Also tested on **[this](https://osu.ppy.sh/beatmapsets/271159#osu/893209)** map and **[this](https://osu.ppy.sh/beatmapsets/2201#osu/19043)** last one because of it's big amount of spinners)

**Screenshots or videos showing encountered issue:** https://streamable.com/gq5fq

**osu!lazer version:** 2019.504.0

**Logs:** N/A

**Comment by Gabixel** [comment]
Interesting.. this doesn't happen on **every** map with spinner at the end, like **[this](https://osu.ppy.sh/beatmapsets/712959#osu/1506887)** one, but testing with maps that don't have a spinner at the end this bug seems to not appear, so I'm sure that the spinner is part of the issue.

**Comment by iiSaLMaN** [comment]
[this](https://osu.ppy.sh/beatmapsets/130725#osu/529988) map too, but the last object is a slider + it's not that random objects appears but it's because the playback rate of the clock became reversed somehow, and to proof that, after you finish the spinner, the rate reverses to that spinner you just finished, then the stream at the top being played in reverse, i'm not sure what's the issue exactly, but i'm trying to compare them with normal maps to see if i can find something that might be the issue, thanks for reporting.

**Comment by Gabixel** [comment]
Yeah, initially I also thought they weren't "random": in fact, it's like a reversed play as you said. Interesting that it happened with sliders too: I'll change the title because it no longer matches the issue correctly.

**Comment by iiSaLMaN** [comment]
By the way, that issue occurred after ver. 2019.418.0

**Comment by peppy** [comment]
Does this only happen in multiplayer? I cannot seem to reproduce on solo play.

**Comment by Gabixel** [comment]
It's weird because I tried again in multiplayer, but it didn't happen. I did other tests in Solo and apparently, if you try to jump straight at the end of the song (in this mode you have to wait for the autoplay to reach the end), the play starts from zero. Also, the same "reverse" thing happens in osu!editor: https://streamable.com/8v3gl

**Comment by sicaduo** [comment]
This bug also happens consistently on [this map](https://osu.ppy.sh/beatmapsets/885878#osu/1851468). https://streamable.com/3nle2
I've only tried it on solo play.

**Comment by LeNitrous** [comment]
Similar to https://osu.ppy.sh/beatmapsets/193980

The issue is that the audio files end immediately thus "looping back" to the start as the player is transitioning to the results screen.

This is the waveform of the audio file of the beatmap above
![image](https://user-images.githubusercontent.com/20495991/57746147-70588480-7702-11e9-8a36-8dd0ff6b4df2.png)

Similar cases are observed with other sets that are linked in previous comments.
