### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by DavidHusicka** [ppy/osu#4757]
**Describe the new feature:** 
Lazer should support translations to multiple languages.

**Proposal designs of the feature:** 
There would be a folder with files including all strings to be translated and their translation. This files could be simple csv files which would just include original text (for indexing and understanding) and the translation. 
Example image:
![image](https://user-images.githubusercontent.com/25853767/57571338-fe83f080-740c-11e9-810f-294487404438.png)

Also I'd like to be assigned to this as a person who will write the code for this.

**Comment by arphox** [comment]
The idea is great, however the implementation idea should be refined.

**Comment by byDave251** [comment]
@arphox any ideas how?

**Comment by peppy** [comment]
Will need to source from crowdin: https://crowdin.com/project/osu-web

Also requires automation for download/upload.

**Comment by arphox** [comment]
> 
> 
> @arphox any ideas how?

I do not have experience so I am not the person who will say.
In any ways, a research should be done so we choose the best available implementation option.

**Comment by byDave251** [comment]
@peppy cool. I found that Crowdin uses json files so it shouldn't be so hard. (https://support.crowdin.com/file-formats/json/). Can you please check that it does so so could count on the json implementation? Also, if translations would be downloaded from online resources, should be this thing be done on client side or on the side of the repository?

**Comment by byDave251** [comment]
I just ended searching for strings to be translated in the source code. @peppy, could you please create a project called "osu" on the Crowdin? I can then add all the strings there if you give me permissions. I also attach file with all the strings and I am creating pull requests where I'll put all the code I'll write for this issue. You don't have to do anything, I will add all the strings to Crowdin myself, because I will need to format some strings into form I need to be in for the source code.

**My vision on the implementation right now:**
The Lazer client will download all the translations from Crowdin and save them into local database. Then on every start of the client, the database would be loaded to cache and used.

The file can miss few strings but I hope it doesn't.
[strings to be translated.txt](https://github.com/ppy/osu/files/3172659/all.texts.txt)

**Comment by peppy** [comment]
The client should not download from crowdin. This should be done as a processing step, similar to osu-web. The localisations would be included with the distribution.

**Comment by loonytoony0** [comment]
I'm not familiar with C# at all, but what about good old gettext? There are libraries implementing it for C#, for other languages it is usually pretty easy to integrate, very easy to translate with software like Poedit or Lokalize. You can deploy a web service such as Pootle to let non-programmer users help with translations.

**Comment by huoyaoyuan** [comment]
@claike see ppy/osu-framework#3154 .
> but what about good old gettext?

GetText is just one of several text storing mechanism. The "libraries implementing it for C#" just brings it into the list. This is the simplest part.

> You can deploy a web service such as Pootle

The game website has already used crowdin for a long time. This is solved.

> I'm not familiar with C# at all

Then you are missing the complex part. The game comes with a self written **framework** and all texts are manually displayed by the framework. I'm working on the framework to get more natural translation displaying support.

**Comment by smoogipoo** [comment]
Closing this one since localisation has been implemented. Lazer can now be localised via the Roslyn tool for lazer-specific components:
![image](https://user-images.githubusercontent.com/1329837/122179031-1a96cd80-cec2-11eb-9143-b1b51e89adc8.png)
Or via an existing osu!web string for "web" components (see https://github.com/ppy/osu/pull/13512 and https://github.com/ppy/osu/pull/13516 for examples).
