### ISSUE TITLE
osu! "full size" logo has weird position when entering SongSelect

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#4792]
**Describe the bug:** The big version of the osu!logo has a weird transition when entering SongSelect without getting its "small" version.

**Screenshots or videos showing encountered issue:** https://streamable.com/0xbpi

**osu!lazer version:** 2019.514.0

**Logs:** N/A

**Comment by peppy** [comment]
Do you have a video of this happening without the huge lag spike? It's hard to tell what's going on in the current one.

**Comment by Altenhh** [comment]
its a bit difficult to not have a lag spike, but here's a clip where its more noticeable on whats going on
https://alten.s-ul.eu/xtKZQKv4.mp4

**Comment by LastExceed** [comment]
The expected behavior is a transition animation where the logo slides off to the left. However the logo gets moved to an incorrect location for an instant before the transition starts. If your PC is fast and your beatmap collection small then its too short to notice, but if the game freezes in just the right moment then you can see it (as demonstrated above).

if you watch the linked videos frame by frame then you can see how the position of the logo is actually getting corrected by the transition after the lag before it switches to the song selection (the rest of the transition animation is skipped, probably because the game is trying to catch up with the time lost during the lag)
