### ISSUE TITLE
osu! sound in disclaimer

### ISSUE THREAD

**Issue by BlauFx** [ppy/osu#4816]
**Describe the bug:** When you hover in the middle of the window while the disclaimer is there the audio/hover sound is played. I don't know if it's intended or not.

**Screenshots or videos showing encountered issue:** https://streamable.com/nljlk

**osu!lazer version:** 2019.514.0

**Logs:** N/A

**Comment by Gabixel** [comment]
Well. I guess that's intended because if you look carefully, you can see that the hover sound is played when you hover the Discord/supporter link, but you can't see the mouse (probably for a design reason):
![hover](https://user-images.githubusercontent.com/43073074/57958348-df4efc80-78ff-11e9-9ccf-2ee857ffdfc7.png)

**Comment by BlauFx** [comment]
makes sense but I would display the cursor(maybe with with low opacity) because I can not see where my mouse is and til I know where my mouse is the disclaimer is gone

**Comment by peppy** [comment]
If it matters that much, removing the ability to interact with the link is preferable.

**Comment by BlauFx** [comment]
Either remove it or display the cursor. I suggest just to display the cursor.

**Comment by Joehuu** [comment]
Closing for now as https://github.com/ppy/osu/pull/8211 removed the link, and this is a temporary screen anyway.
