### ISSUE TITLE
Add ability to update beatmaps to latest available version

### ISSUE THREAD

**Issue by iSimpFor** [ppy/osu#4823]
![updatething](https://user-images.githubusercontent.com/44514667/57978233-c06b6b80-79ce-11e9-9925-f60c6c1229a1.png)

(The update beatmap button should not appear if the beatmap is already at the latest version, this also applies to the other 2 buttons)

The other 2 buttons are for when you have so many beatmaps and you can't take the time to update them all.

**Comment by smoogipoo** [comment]
@arflyte we'll need a design to update (/re-download) beatmaps.

**Comment by peppy** [comment]
Probably worth thinking through the UX before asking for a design (I haven't done this yet).

**Comment by LittleEndu** [comment]
Stable calls this action "redownload" (not 're-download' and not 'update'). Just saying it so this issue pops out for people who search issues mentioning "redownload"

**Comment by ilsubyeega** [comment]
uh just wanted to give idea: add "Redownload" item at ContextMenuItems at DrawableCarouselBeatmap(Set)
![image](https://user-images.githubusercontent.com/37479424/111639001-31d00b80-883e-11eb-8ffd-9baf05105d25.png)

**Comment by iptq** [comment]
Can this update button also pull beatmap-related assets? In stable, it's not possible to pull a new mp3 via that button, which means that if the offset is updated, players will have to re-download the map since the map's new offset will no longer correspond to the old mp3. (also not possible to pull maps with new hitsounds or storyboard elements without re-downloading)

Maybe this can be realized by having re-download button on the set trigger a full re-download vs. button on the map only updating that single difficulty's contents

**Comment by iSimpFor** [comment]
for that, i think osu!lazer could compare downloaded assets and uploaded assets in some way and redownload depending on what changed

**Comment by Loreos7** [comment]
8 times since 2019. There is definitely a need for this feature

**Comment by yellowsink** [comment]
Not sure if this is the most appropriate place for this, but also noting that this may be a relevant improvement for users with pending or qualified maps, which may have since became ranked.

Maybe appropriate to recheck the map's rank state (not redownload or anything ofc) when loading online leaderboards? This would solve the client showing "not available" message when rclicking => details shows ranked.

**Comment by yellowsink** [comment]
Oh thats true, maybe instead show that the status is changed instead of the "no leaderboard" message, kinda stable style. 

Though of course that then does depend on map update infrastructure being in place for it to work from a ux standpoint I guess...
