### ISSUE TITLE
Adding links to beatmap info wedges, sources, and tags

### ISSUE THREAD

**Issue by JackLee9355** [ppy/osu#4870]
**Describe the new feature:** 
I am hoping to make more of the beatmap information open internal links. To be exact I would like the sources and tags to open the search function. And for the info wedge to open the beatmap listing page.

I will be able to handle this if it gets approval.

**Proposal designs of the feature:** 
My idea for the sources and tags are pretty straight forward.
![source and tags](https://user-images.githubusercontent.com/6157330/58451167-f350e600-80d7-11e9-9046-1461b7be0426.png) Make those blue clickable links. My only concern with this is the text color will not match that of the descriptions. 

The first thought for the beatmap listing follows the same idea. 
![title](https://user-images.githubusercontent.com/6157330/58451274-65c1c600-80d8-11e9-9ce9-8522d94fcc57.png) Make the title clickable. I fear this would suffer the same issue as the tags but much worse. As an alternative, and what I think would look better, I propose making the entire wedge clickable and link to the listing page.

**Comment by LastExceed** [comment]
clickable text doesn't have to be blue (we can make the visual whatever we want) so I don't see a design problem, but I do see a potential ux problem with the latter proposal because a. the title being a button doesn't seem very intuitive (although I must admit that [this button](https://puu.sh/DzOcF/df1d4a045c.png) wasn't very intuitive either) and b. we already have [this](https://puu.sh/DzOhc/bca2a78ff2.png) so it's unnecessary to add another button with the same functionality

**Comment by Joehuu** [comment]
> Make those blue clickable links. My only concern with this is the text color will not match that of the descriptions.

The text was blue before, but it was not linked to anything. Reason why I changed it to gray in #2698 as I cannot implement the search.

So no design problem.

**Comment by welsar55** [comment]
I was unaware of the details button in the context menu. I view the entire second section as redundant and unnecessary because of it.

**Comment by peppy** [comment]
For now it is fine to use the same hyperlink colour game-wide. Going forward we will be changing the designs to accommodate this so don't think too hard about it.
