### ISSUE TITLE
Bad audio quality

### ISSUE THREAD

**Issue by Tomycj** [ppy/osu#4891]
All audio quality is now noticeably worse than before (sounds like a broken, cheap headphone). 
It started a few months ago, including the current version. Before that, the audio was ok, like in the classic osu! client. I tried different audio devices and ports with no luck. 
Here's a short recording of it:
[Bad audio quality example.zip](https://github.com/ppy/osu/files/3244285/Bad.audio.quality.example.zip)
Is there anything else I can try? Thanks for helping

**Comment by peppy** [comment]
Please tell us what operating system and audio hardware you are using. Also which build this started occurring on.

**Comment by Tomycj** [comment]
I'm in Windows 10, currently using a headset, the same that I use for osu!. I just tried with a pair of speakers and it still sounds different. I don't know the exact version this started happening. Is there a way to download old builds to try and see where it works well?

**Comment by peppy** [comment]
https://github.com/ppy/osu/releases you can download the `install.exe` corresponding to each release.

**Comment by Tomycj** [comment]
Ok, I can confirm that 2019.131.0 is the last version that goes well.

**Comment by Joehuu** [comment]
Probably fixed in https://github.com/ppy/osu-framework/pull/3146. [This version](https://osu.ppy.sh/home/changelog/lazer/2019.214.0) (after ^) had a bass update which probably introduced sample ramping.

![](https://puu.sh/EUB7u/aced2e6b67.png)

I also kinda felt something was wrong with the audio during that time 🤷‍♂ .
