### ISSUE TITLE
OsuHoverContainer doesn't play transition if hovering when object becomes enabled

### ISSUE THREAD

**Issue by peppy** [ppy/osu#4904]
- Hover a disabled `OsuHoverContainer`
- Wait for it to become enabled through some means
- Note that hover effect does not play

Proposed solution: hover state is already stored as a private bool. It should be checked when enabled becomes true and the appropriate effects should be run.

I'd hope for a test case covering this (although `TestSceneShowMoreButton` made this obvious).

**Comment by arphox** [comment]
I would like to work on this issue, however I do not really understand what You mean.

Reproduction steps I am trying:
1. Start osu!lazer
2. Click on trumpet icon at top header
3. Hover over different tabs like Stable, Stable Fallback, Beta, Cutting Edge, Lazer, Web. I expect hearing sounds when I hover over them, and it does.

The description of the issue is foggy for me.

Can you help me out?

**Comment by Aergwyn** [comment]
It's about a disabled element. If you hover it while it's disabled it won't show as that but after you enabled it it doesn't show as hovered even if it should.

**Comment by arphox** [comment]
How can I reproduce the behavior described?
Do you have any idea from the UI or I have to write some code for it?
