### ISSUE TITLE
Key counter lit animation slows down with the fail one

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#4993]
**Describe the bug:** The key counter `lit` animation seems to slow down with the fail animation. (Not a big issue, but that's probably not the correct design)

**Screenshots or videos showing encountered issue:** https://streamable.com/sd7o7

**osu!lazer version:** 2019.608.0

**Comment by iiSaLMaN** [comment]
That's because `KeyCounter` is one of `GameplayClockContainer`'s Children, which holds the playback rate, will be fixed soon with my PR

**Comment by iiSaLMaN** [comment]
I've been thinking about this, It could be fixed by making a Clock that has a decoupled rate, and it seems that there is a clock (`GameplayClock`) that couples everything to the underlying clock except that it adds something to it (`IsPaused` Bindable).

Maybe we could introduce a `OverridableCoupledFramedClock` which contains all clock properties as virtual and are pointing to the underlying clock by default:
```csharp
public class OverridableCoupledFramedClock : FramedClock
{
    public virtual double Rate => underlyingClock.Rate;
    public virtual double CurrentTime => underlyingClock.CurrentTime;
    public virtual bool IsRunning => underlyingClock.IsRunning;
    ...
}
```

And use that for the `KeyCounter` to set a constant rate or `Math.Sign(Rate)`
```csharp
public class KeyCounterClock : OverridableCoupledFramedClock
{
    public override double Rate => Math.Sign(base.Rate);
}
```

**Comment by iiSaLMaN** [comment]
After a bit of looking, I've realized that `FramedClock` has exactly what I proposed except that `Rate` is not virtual, can be fixed easily.

**Comment by iiSaLMaN** [comment]
The correct solution to this, is simply not using `GameplayClock` at all but just read it's `CurrentTime` instead.
