### ISSUE TITLE
Wrong transition when going back from PlayerLoader/gameplay/result-screen of a replay

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#5232]
**Describe the bug:** Pressing `Esc` (or the Back/Home button in some scenarios) while in the PlayerLoader/gameplay/_after-gameplay result-screen_ of a replay doesn't send you to the `PlaySongSelect` as expected, but it sends you to the `MainMenu` ~(keeping the mods applied). This cause the bouncing animation for the icons to "break" with mods like DoubleTime~ (this part has already been fixed).

**Screenshots or videos showing encountered issue:** https://streamable.com/etwd6

**osu!lazer version:** 2019.704.0

**Comment by bdach** [comment]
I'd looked at the screen transition part, and I wasn't sure of the fix I wanted to apply here so I backed off, but I figure I can at least leave some trace of the investigation itself.

`ReplayDownloadButton` uses `OsuGame.PresentScore()` to show the replay. Relevant lines are:

https://github.com/ppy/osu/blob/3907d859f5ecca419c54761d1748d86b1ab38075/osu.Game/OsuGame.cs#L315-L320

`performFromMainMenu`, as the name suggests, goes to the main menu before starting to execute the actions to follow. In some instances it's possible that unwinding the screen stack to the main menu is not necessary, and this function provides an out for this:

https://github.com/ppy/osu/blob/3907d859f5ecca419c54761d1748d86b1ab38075/osu.Game/OsuGame.cs#L380-L385

However, that doesn't work in this scenario, since when the score is presented, the screen stack is:
```
MainMenu -> PlaySongSelect -> Results
```
and the function doesn't *unwind* the stack, it checks the top of it (the current screen, which is `Result` - not the one we want) and then unwinds all the way out to `MainMenu` to continue.

The problem here is, we don't have the instance of `PlaySongSelect`, so there's really no way to call `MakeCurrent` on it. A way out I devised would be to add a way for `ScreenStack` to unwind to a particular screen type, but since that requires a framework-side change, I had decided against going for that.

I also attempted navigating from the main menu back into `PlaySongSelect`, but it doesn't look good visually - it makes the main menu background fade in and then out again back to the beatmap background.

**Comment by smoogipoo** [comment]
Have you tested that this is still an issue? I can't replicate this on the latest master or 2019.925.0.

**Comment by Gabixel** [comment]
Still happens on the latest master: https://streamable.com/tvcah

**Comment by smoogipoo** [comment]
Not sure what I'm supposed to be looking at there, everything seems fine? What you mentioned as `This cause the bouncing animation for the icons to "break" with mods like DoubleTime.` isn't displayed and it seems to work fine on my end.

**Comment by Joehuu** [comment]
That part was fixed but not the screen transition part.
