### ISSUE TITLE
Add touchscreen detection (and apply correct "TD" mod)

### ISSUE THREAD

**Issue by TsavyPrince** [ppy/osu#5378]
**Describe the new feature:** 
Whenever I play osu!, I use a touch screen. However, even though the osu! the website shows a touchscreen mod icon on leaderboards, osu!lazer doesn't whenever I beat a map using a touchscreen. This also applies to multiplayer tag coop plays.
**Proposal designs of the feature:** 
Add in mod icons for tag coop and touchscreen to display like any other mod on leaderboards.

**Comment by peppy** [comment]
I'm not sure if the touchscreen mod will be a thing in lazer. It was implemented as a mod on stable because it was the easiest way of making it happen, but really it should probably not be a mod.

This will become a focus once we are closer to having online leaderboards in lazer.

**Comment by ticotaco72** [comment]
there are already live...
![osu_2019-08-13_20-18-26](https://user-images.githubusercontent.com/32620809/62966559-8bbd5380-be07-11e9-9229-b5d94d354e57.jpg)

**Comment by frenzibyte** [comment]
@peppy I've added this issue thread to the "osu!(lazer) ranked play" project as it's crucial to prevent unfair advantage from touchscreen players in the leaderboards.

**Comment by Susko3** [comment]
I think https://github.com/ppy/osu-framework/pull/5309 is relevant for this issue as the client-side touch detection will probably rely on the event type. And currently some pen tablets are seen as touch events in some cases.

**Comment by bdach** [comment]
Would be we relying solely on the incoming input event types here, or should stable's detection algorithm be somehow ported? (And if it's going to be the latter, the main question is whether that should be public source...)

**Comment by peppy** [comment]
If we can base on input detection, that is best IMHO. If we also want the algorithm method as a fallback, it can be made public (as long as the code isn't too bad).

The edge case I can think of is something like a wacom touch tablet where you can use touch or the pen. I'm not sure if we can discern between the two (I think OTD does, but have not confirmed).

**Comment by bdach** [comment]
I had a very rough go at an extremely basic implementation of this. How's this look UX-wise?

https://github.com/ppy/osu/assets/20418176/69696282-8b47-4fda-b02f-c86882cbd5ab

- Uses input event type for now.
- Yes I know the "touch device" mod should start showing in the upper right of the screen too. The issue with that is that the *entire* player has thus far (and probably rightly so) assumed that mods are immutable. So for now I'm only appending the mod to `Player.Score`, but it doesn't show everywhere yet unless / until I upend half of `Player` to be able to respond to mod changes.
- The criteria to show the toast are as follows:

```csharp
        private void ensureTouchModActive()
        {
            if (gameplayState.HasPassed || gameplayState.HasFailed || gameplayState.HasQuit)
                return;

            if (player.Score.ScoreInfo.Mods.OfType<OsuModTouchDevice>().Any())
                return;

            if (player.IsBreakTime.Value)
                return;

            if (gameplayState.ScoreProcessor.HitEvents.Any())
                onScreenDisplay?.Display(new TouchDeviceDetectedToast());

            // TODO: this is kinda crude. `Player` (probably rightly so) assumes immutability of mods.
            // this probably should be shown immediately on screen in the HUD,
            // which means that immutability will probably need to be revisited.
            player.Score.ScoreInfo.Mods = player.Score.ScoreInfo.Mods.Append(new OsuModTouchDevice()).ToArray();
        }
```

i.e. I don't want a mobile user to get spammed with the toast every play, so if the user _starts_ with touch, they don't get the toast. Similarly, touches are ignored for completed scores, and during pause, too.

Rest of source available for perusal at https://github.com/ppy/osu/compare/master...bdach:osu:basic-touchscreen-detection?expand=1 if so inclined.

I haven't tested if this submits properly yet either since that's finicky, but will do so if the UX gets a blessing (plus minus the "upper right mod display doesn't update" part).

**Comment by Susko3** [comment]
> The edge case I can think of is something like a wacom touch tablet where you can use touch or the pen. I'm not sure if we can discern between the two (I think OTD does, but have not confirmed).

OTD does have [`ITouchReport`](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/b996c8feb0b3da53ff0599940af550118f6422ca/OpenTabletDriver/Tablet/Touch/ITouchReport.cs), but the framework is [not handling that specific device report](https://github.com/ppy/osu-framework/blob/e7b7f40a5e3f9a6a970006b93ef7d79fbf68b177/osu.Framework/Input/Handlers/Tablet/OpenTabletDriverHandler.cs#L109-L121). So touches from a tablet should be ignored.

**Comment by Susko3** [comment]
A player playing with a touchscreen would probably also navigate the main menu / song select with one. I think applying the mod earlier makes more sense. (The gameplay detection should still be there, to catch anyone trying to cheat or not using touch in song select).

Since [TD affects star rating](https://osu.ppy.sh/home/news/2022-09-30-changes-to-osu-sr-and-pp#touch-screen-now-affects-star-rating), having it applied at song select makes that more transparent to players. No issue with "I played a 6* map but didn't get the 6* medal."

Also solves the problem with `Player` not responding to mod changes.

**Comment by bdach** [comment]
> I think applying the mod earlier makes more sense

Maybe farfetched but what if the user navigates the menu via touch but then switches to tablet or mouse *only* for gameplay?

**Comment by peppy** [comment]
Interesting idea to have it showing earlier. I think this could work?

> Maybe farfetched but what if the user navigates the menus via touch but then switches to tablet or mouse only for gameplay?

I think as long as it's very clear it was applied, and... unapplied when switching to mouse? maybe it could work. ie. it would only be in the correct state if they used the same device at song select, but at least it would give an accurate representation based on their current input device usage.

Of course, during gameplay it would only work in one direction (disabled -> enabled).

Maybe this all adds too much complexity though.

**Comment by bdach** [comment]
Showing it at song select in an acceptable way would entail
- adding the notion of "touch device" mod to ruleset API
- having song select use that to apply/unapply the mod (or not bother)

If you can accept this extra complexity then I guess it can be tried.

**Comment by peppy** [comment]
That doesn't sound like too much complexity, but I'd proof-of-concept it first to see how it works in practice. I'm not sure how much things like song select / mod select like a mod being toggled on arbitrarily like that (in theory we should have this covered these days but who knows).

**Comment by Susko3** [comment]
I have a touchscreen monitor so it's quick and easy for me to test.

Just tested your branch at 5a1f0942b4c6d1e20d8f5e5e500ba6abc4d8bf27 in a full game scenario and it crashes when changing mouse &lrarr; touch when loading, during gameplay and in the results screen (list not exhaustive). Is this expected?
Works fine in the tests and in song select.

```cs
2023-10-30 17:45:43 [error]: System.InvalidOperationException: Can not set value to "osu.Game.Rulesets.Mods.Mod[]" as bindable is disabled.
2023-10-30 17:45:43 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
2023-10-30 17:45:43 [error]: at osu.Game.Screens.Select.SongSelectTouchHandler.updateState() in C:\...\osu\osu.Game\Screens\Select\SongSelectTouchHandler.cs:line 53
2023-10-30 17:45:43 [error]: at osu.Game.Screens.Select.SongSelectTouchHandler.<LoadComplete>b__10_2(ValueChangedEvent`1 _) in C:\...\osu\osu.Game\Screens\Select\SongSelectTouchHandler.cs:line 37
2023-10-30 17:45:43 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2023-10-30 17:45:43 [error]: at osu.Framework.Bindables.Bindable`1.SetValue(T previousValue, T value, Boolean bypassChecks, Bindable`1 source)
2023-10-30 17:45:43 [error]: at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
2023-10-30 17:45:43 [error]: at osu.Framework.Bindables.Bindable`1.SetValue(T previousValue, T value, Boolean bypassChecks, Bindable`1 source)
2023-10-30 17:45:43 [error]: at osu.Framework.Bindables.Bindable`1.set_Value(T value)
2023-10-30 17:45:43 [error]: at osu.Framework.Configuration.ConfigManager`1.SetValue[TValue](TLookup lookup, TValue value)
2023-10-30 17:45:43 [error]: at osu.Game.Input.TouchInterceptor.Handle(UIEvent e) in C:\...\osu\osu.Game\Input\TouchInterceptor.cs:line 26
2023-10-30 17:45:43 [error]: at osu.Framework.Graphics.Drawable.OnMouseMove(MouseMoveEvent e)
2023-10-30 17:45:43 [error]: at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
2023-10-30 17:45:43 [error]: at osu.Framework.Input.InputManager.PropagateBlockableEvent(SlimReadOnlyListWrapper`1 drawables, UIEvent e)
2023-10-30 17:45:43 [error]: at osu.Framework.Input.InputManager.handleMouseMove(InputState state, Vector2 lastPosition)
2023-10-30 17:45:43 [error]: at osu.Framework.Input.InputManager.HandleMousePositionChange(MousePositionChangeEvent e)
2023-10-30 17:45:43 [error]: at osu.Framework.Input.InputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
2023-10-30 17:45:43 [error]: at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
2023-10-30 17:45:43 [error]: at osu.Framework.Input.StateChanges.MousePositionAbsoluteInput.Apply(InputState state, IInputStateChangeHandler handler)
2023-10-30 17:45:43 [error]: at osu.Framework.Input.InputManager.Update()
2023-10-30 17:45:43 [error]: at osu.Framework.Input.PassThroughInputManager.Update()
2023-10-30 17:45:43 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2023-10-30 17:45:43 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2023-10-30 17:45:43 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2023-10-30 17:45:43 [error]: at osu.Framework.Threading.GameThread.processFrame()
```

**Comment by bdach** [comment]
> Is this expected?

Do I have to answer that? I did say it was untested...

I forgot about the decoupled mod bindable monstrosity in song select. That will piss in my cereal some more because now there's a possibility that a touch was registered while song select isn't current and the song select handler should do nothing until suspended but then actually apply the touch device mod on resume so it's not an immediately obvious fix that I could try and write without testing. This scenario wasn't exercised in the tests because there's no full-stack test exercising that yet I guess.

**Comment by bdach** [comment]
I've pushed fixes to the aforementioned branch, and solo seems to work alright in basic testing, but multiplayer / playlists are going to be the big remaining issue.

Basically, in both multiplayer and playlists:
- touch device must _never_ be a required mod
- touch device must _never_ be an explicitly-specified free mod
- ...but touch device must _always_ be accepted on submission if it's there

This is a bit of a new notion and will likely require `osu-web` changes so that touch device can essentially be attached to a submitted multiplayer score at will completely bypassing the required/allowed mod systems.

**Comment by peppy** [comment]
~~One could argue that playlists should be able to require touch mod to create touch-only rooms (or touch-forbidden rooms)~~

Probably something to consider in the future, not now.

**Comment by Joehuu** [comment]
Resolved in https://github.com/ppy/osu/pull/25348.
