### ISSUE TITLE
Chat tabs in dropdown cannot be parted

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#5448]
Currently there's no way to remove channel from tabs dropdown in chat.
Few possible fixes:
- ability to close them using context menu
- they must be moved into the main tabs container if there's enough space for that

**Comment by peppy** [comment]
option 2 is fine.. and should already be happening

**Comment by Joehuu** [comment]
Option 2 did regress with the recent chat changes.

Reference: https://puu.sh/E1OcM/897f223cc8.mp4

**Comment by EVAST9919** [comment]
It's not recent changes fault

**Comment by nyquillerium** [comment]
This is framework. The following test in `TestSceneTabControl` will fail:
```csharp
[Test]
public void TestRemovingFromDropdown()
{
   AddStep("Remove test3 from tabs", () => simpleTabcontrol.RemoveItem(TestEnum.Test3));
   AddAssert("Test 4 was moved out of dropdowns and into visible tabs", () => !simpleTabcontrol.Dropdown.Items.Contains(TestEnum.Test4));
}
```

**Comment by nyquillerium** [comment]
So I took a deeper look at this. This regressed in https://github.com/ppy/osu-framework/pull/2431, which changed the way tab items are hidden when they overflow from being dependant on `IsPresent` to being isolated inside `TabFillFlowContainer`. 

Since `FillFlowContainer.ComputeLayoutPositions` depends on `FlowingChildren`, and `FlowingChildren` only considers tabs that are `IsPresent`, once a tab is hidden it'll never be shown again. This is because to show a tab, it depends on having its layout position calculated and then having it be on the first row.

A simple fix would be to simply consider not present children by overriding `FlowingChildren` in `TabControl`, but if we want to go down the path of isolating the overflow logic in `TabControl` this is not ideal. As a result, it is likely we'll need to rewrite `TabControl` such that it doesn't depend on flow calculations, which may mean we need to remove and add-back tabs instead of hiding them. 

I've taken a look at doing this rewrite myself, but I'm not confident in making this kind of large change to a framework-level component, especially considering there are a number of other functions dependent on there are actual hidden drawable tabs. Would be interested if anyone else has any ideas as how to solve this.
