### ISSUE TITLE
anti-mashing in osu!mania

### ISSUE THREAD

**Issue by genericthing** [ppy/osu#5686]
this is anti-mashing, where it prevents mashing(repeatedly pressing the button as much you can at certain points until the objective is reached) in osu!mania

how the anti-mash would work is to check if the key pressed has a timing window to hit. 
if there is none, the game will check if any timing windows are within the mash press. 
if any are detected, then the game will give a miss for those notes.

**Comment by dscnnctd** [comment]
I’d rather have this as a mod rather than having it on normal gameplay. It ruins the experience for most mania players when it comes to higher difficulty maps.

**Comment by genericthing** [comment]
i think having it as a mod ruins the point of anti-mashing

also, harder mania maps would usually have sections covered where you will probably hit a timing window no matter which lane you hit if you are trying

**Comment by dscnnctd** [comment]
>i think having it as a mod ruins the point of anti-mashing ...

@genericthing
It just doesn’t feel right since the other game modes don’t have it. Plus, it makes the gameplay stressful because you would need to worry about not pressing the wrong note in a specific beatmap. People would not like this change otherwise if this was implemented in normal gameplay, so making this an _unranked_ mod would be a better option even if it doesn’t sound right.

**Comment by genericthing** [comment]
I'm not sure what you mean by where the stress is coming from but i can adjust the idea to be less extreme

how the anti-mash would work is to check if the key pressed has a timing window to hit.
if there is none, the game will check if ~~any~~ the lanes next to the mash press have timing windows within the mash press.
if any are detected, then the game will give a miss ~~for those notes~~ but it will not break combo and the notes can still be hit, if the person FCs, then the FC will show up but it will show more than 0 misses.

**Comment by dscnnctd** [comment]
I think it’s right to not have anti-mashing for mania at all or rather implement it on a less extreme way.

As you mentioned, _FC will still show up but will show the amount of misses for mashing the keys without breaking the combo_. So having the mash counter as a separate at the end screen would be a good idea to put in. Is this the direction we want this to be implemented now?

**Comment by jai-x** [comment]
If the intent of the "anti-mashing" feature is to prevent from pressing keys while there are no active hit objects on screen and make such presses count as misses, I believe the idea is better described in the issue for the proposal of the Finger Control mod: https://github.com/ppy/osu/issues/6555

If so, that this issue can be closed as a duplicate of https://github.com/ppy/osu/issues/6555

**Comment by genericthing** [comment]
@dscnnctd 
yeah i think that is fine at that point, anti-mash that breaks combo is annoying due to how the game works but there should be something showing if a person mashed a lot through a map or just made a few mistakes.

@jai-x
i wouldn't intend this to be a mod since this mechanic is supposed to prevent cheesing maps.

also, the issue mentioned doesn't intend their mod to be a anti-mashing mechanic, the missed given for mashing will not affect anything expect the mash-miss counter on the results screen and pp.

extra notes:
the mash-miss counter should affect pp but it will affect pp a lot less than if you actually missed the note.

do you think the mash-miss counter should show up in scores, not show up, or be merged with misses(but still count as mash-misses)?

**Comment by dscnnctd** [comment]
@genericthing 
I like the direction on where this proposal goes but it only affects mania whilst the issue @jai-x mentioned serves as a mod that _"could be"_ compatible in each mode. Though both issues were mentioned, it’s now hard to decide which proposal does the better job to provide the better experience for the players who wanted it.

If #6555 becomes most favoured, it would make some sense since **IF** it could be playable across different modes even if the mod is not really meant for anti-mashing _(as mentioned in the issue)_.

With the first comment I have inputed 12 hours ago, it does not feel right nor better for most players to have this mechanism at normal gameplay as mania players _might_ prefer playing without it at all. If it were to be implemented to all game modes, it could make sense. If this proposal becomes a mod, it should not affect mania only, but other modes as well (disregarding _UNRANKED_, should be a difficulty increase instead).

**Comment by dscnnctd** [comment]
As mentioned by @LanTenDragon from mentioned issue:

>Yes I intend it to be implemented in the four main rulesets.

He confirmed that this mod will be useable across four rulesets. Also mentioning that PP deduction will not be required as he had score deduction in mind due to _osu!lazer’s **standardised system**_.

This issue however, mentioned that it should affect the PP scoring system at end-screen but not mentioning the score. Because of lazer’s _standardised system_, score deduction will be implemented for the proposed mod.

During a discussion on the discord server, we decided that you’re trying to change **osu!mania’s ruleset**, which affects every existing beatmap specifically for that mode to increase difficulty.

Your excuse for _"cheesing maps"_ is not valid since you can’t _really change the way_ you play in mania.

Plus, you’re enforcing this ruleset proposal without asking for community feedback. It affects everyone who play this game mode, not only you. Let them decide whether to have _anti-mashing mechanism_ in game or keep it the same as **osu!stable’s ruleset**.

As a result, I recommend @LanTenDragon’s proposal more because it does not require community feedback to make it a mod across four different rulesets. Your proposal only affects **osu!mania’s ruleset** as a whole and it required community’s feedback, including the fact that you only targeted the **PP system** excluding score. **PP deduction** for the proposed mod isn’t necessary since it looks for the amount of keys pressed during gameplay and calculating the amount of extras the player presses in the end, deducting the score the player gained.

**Comment by genericthing** [comment]
alright, will close this issue
