### ISSUE TITLE
Add back cursor smoke trails

### ISSUE THREAD

**Issue by revelsix** [ppy/osu#5721]
**Describe the missing feature:** The ability to scribble on the screen during gameplay (mainly breaks) by pressing a remappable button

**Proposal designs of the feature:** ![screenshot111](https://user-images.githubusercontent.com/45189851/63025838-0a51d980-be78-11e9-9965-1d5515a77341.jpg)

**Comment by darkralts** [comment]
pls peppy i need the smoke

**Comment by MakelMagus** [comment]
Hello, I was about to post an issue regarding this, but I believe it goes better as a side comment here:

<h3>Shouldn't this be considered a low tier parity issue?</h3>

For me, being able to draw random doodles between breaks is a detail that can very easily disrupt the monotony of trying to beat a hard map, and also adds a sense of personality to replays and spectating.

And so one of the first things I noted in gameplay (other than the beautiful hub), was the lack of such ability, which genuinely made the game feel... colder, even with everything else around telling otherwise.

I don't know if this has been talked about in some obscure Osu! forum, but I really couldn't find any mention of this missing feature, other than the closed issues due to being clones of this one, and I'd really like to know what's the deal behind it:
 - Is drawing considered such an inconsequential action that it doesn't deserve to be talked about in public?
 - Is it that it requires to first solve some crucial missing pieces? _(e.g some inherent visual error it may cause)_
 - Or is it that under the current system it is a lot harder to implement, so it'll be **completely** ignored until **all** other parity issues have been resolved?

[A video of my sadness](https://mega.nz/file/cfgyEJYb#NhLMi4heoRr2I1OtMvJlk-vAG0iFZm7elrl-NiKCEXQ)

Wait a second, IT DIDN'T RECORD OSU! LAZER, I'll check if there's an issue for that already made, if not, I'll make it tomorrow.

**Comment by peppy** [comment]
Your post is unnecessary. If you want to show your support for the feature, please respond to the opening post. It will be implemented in time.

**Comment by Joehuu** [comment]
Added in https://github.com/ppy/osu/pull/20376.
