### ISSUE TITLE
Add a "Import Beatmaps from local storage" button for Android client

### ISSUE THREAD

**Issue by X4X5** [ppy/osu#5761]
**Describe the new feature:** This is like the button on Lazer that says "Import Beatmaps from Stable", but for the Android port, this feature would look for .osz files in the Android downloads folder from internal storage.

**Proposal designs of the feature:** It would look like any other button in the settings, but it would be categorized under maintenance.

**Comment by LittleEndu** [comment]
Expanding on this, doesn't android go through all the files and indexing them so that other apps can just say "I want all the mp3s the user has" and the system gives them all the mp3 files? If I remember this correctly then this importing shouldn't only be limited to the downloads folder. 

Quick googling says it's called MediaStore, unsure if this could support custom mime types.

**Comment by PercyDan54** [comment]
#10882 solves this?

**Comment by bdach** [comment]
Closing as resolved.

**Comment by nt1513** [comment]
> Closing as resolved.

There's been multiple new release of Android so please reopen it you bastard

**Comment by bdach** [comment]
Please see the aforementioned PR link. An in-game file import view has already been added. It's in the settings menu.

And do watch your language, please, because you'll find that cursing away in issue comments will end with your ability to leave comments being promptly taken away.
