### ISSUE TITLE
Message formatter can't create a correct link with opened square bracket in the link title

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#5772]
Example:
![Screenshot_3](https://user-images.githubusercontent.com/22874522/63274347-4c2fb500-c2a8-11e9-9916-3deda01fb55d.png)
![Screenshot_4](https://user-images.githubusercontent.com/22874522/63274349-4c2fb500-c2a8-11e9-8e6e-fae1a369cc4e.png)

Usage: Kudosu History can return link to the post, in which there's only one opened square bracket in the name.
![Screenshot_2](https://user-images.githubusercontent.com/22874522/63274484-89944280-c2a8-11e9-8b7d-59b9cbd51664.png)

**Comment by EVAST9919** [comment]
Not a high-priority, I can just use another link format.

**Comment by EVAST9919** [comment]
Nevermind. Another format can't handle round brackets.

**Comment by EVAST9919** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/22874522/64130812-57690180-cdcd-11e9-8624-6d7f9eafb3cc.png)
@peppy that's why I was using `AddLink`

**Comment by bdach** [comment]
So those are two issues in two separate formats.

The original issue was caused by an imbalanced opening bracket in the new-style link, [and since the `new_link_regex` expects brackets in link text to be matched](https://github.com/ppy/osu/blob/97580a4117b46dc55491bf2b9481cc4ab99bbd40/osu.Game/Online/Chat/MessageFormatter.cs#L19) using [balancing groups](https://docs.microsoft.com/en-us/dotnet/standard/base-types/grouping-constructs-in-regular-expressions#balancing_group_definition), the regex fails to match.

The second one (in the comment directly above) arises from [`markdown_link_regex` not using the same trick](https://github.com/ppy/osu/blob/97580a4117b46dc55491bf2b9481cc4ab99bbd40/osu.Game/Online/Chat/MessageFormatter.cs#L22) and failing to match the link text, since the first capturing group is ended by the first closing square bracket and then the opening paren never matches, since the next token is the second closing square bracket.

The second issue is easily fixable. The first, I'm not even convinced *can* be fixed using regular expressions. I don't have a formal proof but I'm pretty sure a context-free language would have to be used to properly parse those link formats to preserve intent and also allow mixing with other link types (ie. wiki-style links). So I don't know whether it's worth the hassle - using some escapes might be more economical; for example `string.Format` requires braces to be doubled up for escaping purposes (as in you'd have to do
```
[https://osu.ppy/sh This is a link with an annoying double brace in the text [[]
```
to display the link text of `This is a link with an annoying double brace in the text [`

**Comment by bdach** [comment]
FYI I'm working on this, I'm going to be adding support for balanced braces in Markdown and old link fomat as well as backslash escapes everywhere. (By the way, do any wiki pages have square braces in their names?)
