### ISSUE TITLE
Very poor performance when dragging the seek bar

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [ppy/osu#5799]
**Describe the bug:** Dragging the seek bar in replays instead of clicking to seek, results in really bad performance.

**Screenshots or videos showing encountered issue:** [Video](https://streamable.com/igg2k)

**osu!lazer version:** 2019.814

**Logs:** 
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3527670/performance-gamethread.update.log)
[performance.log](https://github.com/ppy/osu/files/3527671/performance.log)

**Comment by peppy** [comment]
This is indeed very weird. Have you tried on latest master? I cannot reproduce anything like this.

**Comment by HoLLy-HaCKeR** [comment]
The same still happens on 76d34967a4ba0acd3a510c17921c2c43da194816, which is latest master.

**Comment by peppy** [comment]
It would be helpful if you can profile this via visual studio and try to figure what is causing the slowdown.

**Comment by HoLLy-HaCKeR** [comment]
I used Rider's Sampling profiling but I have no experience with profiling multithreaded games so I don't know how to interpret this, with all threads having functions that block them while they're waiting for something else.
[snapshot.dtp.zip](https://github.com/ppy/osu/files/3530403/snapshot.dtp.zip)

**Comment by bdach** [comment]
The issue reproduces for me too. I looked into this, and I *think* this is a resource contention issue?

I ran CPU/GPU utilization first, and weirdly enough there are no spikes in CPU/GPU usage, just frame time spiking and framerate plummeting. Usage actually seems to decrease slightly.

![stutter](https://user-images.githubusercontent.com/20418176/63652030-da4de480-c75b-11e9-9e99-10a3dc8d0673.PNG)

So then I ran a diagnostic for resource contention, which showed this hot stack during the stutter periods:

```
Function Name	Module Name	Inclusive Contentions	Exclusive Contentions	Inclusive Blocked Time (ms)	Exclusive Blocked Time (ms)
 + dotnet.exe		1 528	0	5 975	0
| + osu.Framework.Threading.GameThread.runWork()	osu.Framework.dll	1 526	0	4 706	0
|| + osu.Framework.Threading.GameThread.ProcessFrame()	osu.Framework.dll	1 526	0	4 706	0
||| + osu.Framework.Platform.GameHost.UpdateFrame()	osu.Framework.dll	1 524	0	4 688	0
|||| + osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()	osu.Framework.dll	1 524	0	4 688	0
||||| + osu.Framework.Graphics.Drawable.UpdateSubTree()	osu.Framework.dll	1 524	0	4 688	0
|||||| + osu.Framework.Input.PassThroughInputManager.Update()	osu.Framework.dll	1 524	0	4 688	0
||||||| + osu.Framework.Input.InputManager.Update()	osu.Framework.dll	1 524	0	4 688	0
|||||||| + osu.Framework.Input.StateChanges.MousePositionRelativeInput.Apply(class osu.Framework.Input.States.InputState,class osu.Framework.Input.StateChanges.IInputStateChangeHandler)	osu.Framework.dll	1 524	0	4 688	0
||||||||| + osu.Framework.Input.UserInputManager.HandleInputStateChange(class osu.Framework.Input.StateChanges.Events.InputStateChangeEvent)	osu.Framework.dll	1 524	0	4 688	0
|||||||||| + osu.Framework.Input.InputManager.HandleMousePositionChange(class osu.Framework.Input.StateChanges.Events.MousePositionChangeEvent)	osu.Framework.dll	1 524	0	4 688	0
||||||||||| + osu.Framework.Input.MouseButtonEventManager.HandlePositionChange(class osu.Framework.Input.States.InputState,valuetype osuTK.Vector2)	osu.Framework.dll	1 524	0	4 688	0
|||||||||||| + osu.Framework.Input.MouseButtonEventManager.HandleMouseDrag(class osu.Framework.Input.States.InputState,valuetype osuTK.Vector2)	osu.Framework.dll	1 524	0	4 688	0
||||||||||||| + osu.Framework.Input.MouseButtonEventManager.PropagateMouseButtonEvent(class System.Collections.Generic.IEnumerable`1<class osu.Framework.Graphics.Drawable>,class osu.Framework.Input.Events.MouseButtonEvent)	osu.Framework.dll	1 524	0	4 688	0
|||||||||||||| + System.Linq.Enumerable.TryGetFirst(class System.Collections.Generic.IEnumerable`1<!!0>,class System.Func`2<!!0,bool>,bool&)	System.Linq.dll	1 524	0	4 688	0
||||||||||||||| + osu.Framework.Graphics.UserInterface.SliderBar`1.OnDrag(class osu.Framework.Input.Events.DragEvent)	osu.Framework.dll	1 524	0	4 688	0
|||||||||||||||| + osu.Framework.Graphics.UserInterface.SliderBar`1.handleMouseInput(class osu.Framework.Input.Events.UIEvent)	osu.Framework.dll	1 524	0	4 688	0
||||||||||||||||| + osu.Game.Screens.Play.SongProgressBar.OnUserChange(float64)	osu.Game.dll	1 524	0	4 688	0
|||||||||||||||||| + osu.Game.Screens.Play.SongProgress.<.ctor>b__22_0(float64)	osu.Game.dll	1 524	0	4 688	0
||||||||||||||||||| + osu.Game.Screens.Play.HUDOverlay.<load>b__22_0(float64)	osu.Game.dll	1 524	0	4 688	0
|||||||||||||||||||| + osu.Game.Screens.Play.GameplayClockContainer.Seek(float64)	osu.Game.dll	1 524	0	4 688	0
||||||||||||||||||||| + osu.Framework.Timing.DecoupleableInterpolatingFramedClock.Seek(float64)	osu.Framework.dll	1 524	0	4 688	0
||||||||||||||||||||||   System.Threading.Tasks.Task`1.GetResultCore(bool)	System.Private.CoreLib.dll	1 524	1 524	4 688	4 688
```
I *think* this might be [this line in `DecoupleableInterpolatingFramedClock`](https://github.com/ppy/osu-framework/blob/5fb21e83803e51668ca8772f89aeedb3cd73e5d8/osu.Framework/Timing/DecoupleableInterpolatingFramedClock.cs#L142), which then in the implementation hits `TrackBass` wherein we have [a `.Result` call on `SeekAsync`](https://github.com/ppy/osu-framework/blob/97aad686e3e72892150174e0a5a736222976ef56/osu.Framework/Audio/Track/TrackBass.cs#L243). I'm not sure about anything with the underlying I/O, so I won't even attempt to speculate what could be going on under the hood, but with the seek events being generated really quickly this could very well stutter on waits.

To verify I did a horribly dirty hack wherein I fire-and-forgot-run that task via `Task.Run` and then returned `true` unconditionally in `TrackBass`, and the framerate improved. The audio started being horribly choppy though, and that sort of code should probably never land anywhere near the final fix.

Not sure what the fix is here either, maybe throttling the seek events so they don't kill the performance?
