### ISSUE TITLE
Replace triangle intro sequence video with a shader (or otherwise) implementation

### ISSUE THREAD

**Issue by oSumAtrIX** [ppy/osu#5805]
I have a WQHD Monitor with is 2560 × 1440 pixels and the video with a resolution of 1080 × 1080 pixels looks pretty pixelated since it starts at being scaled up to 120% and scales down to 80%.
I suggest a resolution of 1,296 × 1,296 pixels for SD and double resolution for HD and up.

https://github.com/ppy/osu-resources/blob/master/osu.Game.Resources/Textures/Menu/logo-triangles.mp4

https://github.com/ppy/osu/blob/76d34967a4ba0acd3a510c17921c2c43da194816/osu.Game/Screens/Menu/IntroTriangles.cs#L221

**Comment by peppy** [comment]
If anyone is interested in attempting this, we can provide the after effects file showing each layer / curve. Note that this is not to be considered a simple task (would be worth $300+ for a near-frame-perfect implementation).

**Comment by yuuiko** [comment]
@peppy 

https://airbnb.design/lottie/

**Comment by peppy** [comment]
Cool library, but won't help us.

**Comment by yuuiko** [comment]
https://github.com/airbnb/lottie-web

Don’t know if this is any more help but apparently it works for HTML / javascript too. I’m not that familiar with how osu works though. But i found this library from someone else who makes mac apps. I also got an animation to work on the web.

**Comment by peppy** [comment]
It is not relevant. osu! is not a web-based project.

**Comment by jorolf** [comment]
I would like to give this a try however I don't have After Effects to open the file. Maybe the plugin mentioned on that website can help? It exports the animations in a json format.

**Comment by peppy** [comment]
the AE format is already pretty well supported. @arflyte can you drop the file in here when you have a chance?

**Comment by EmilySunpy** [comment]
Been thinking of a few ways to handle this issue, but have come to the conclusion that the easiest and lightweight method is probably the best. My proposal is to render out a png with shifting color value to make a path. I generated this sample png with after effects: ![osu! (258 KB ~= 1529 frames)](https://user-images.githubusercontent.com/17113395/63689422-353e1500-c80a-11e9-88a1-5c04cb990a74.png) (258 KB & ~1529 possible frames with this spesific instance)

I reinstalled my OS a little while ago so I have not gotten around to run dotnet yet so I made a demo on shadertoy: ![Shadertoy gif](https://user-images.githubusercontent.com/17113395/63689635-c4e3c380-c80a-11e9-9a2d-e042d27622de.gif) (Note that on shadertoy it ignores alpha channel on png input so there are some small artifacts that wont be there if used in osu framework)

**Comment by peppy** [comment]
Awesome thinking! Would you still find the AE file helpful?

**Comment by arflyte** [comment]
[Lazer Intro folder.zip](https://github.com/ppy/osu/files/3544390/Lazer.Intro.folder.zip)

Here's the AE file.

**Comment by repsanims** [comment]
> My proposal is to render out a png with shifting color value to make a path.

Would it be more reliable using a vector path to animate the logo?

Since the png still a raster meaning if it's exported at 1080p it still create the low-res artifact, and even 2160p will still be a low-res if you're using an 8K projector.

Anyway, I just recreate a cleaner osu transition in AE (thanks @arflyte for the AE file)
![Screenshot (30)](https://user-images.githubusercontent.com/45067376/64169592-4e813a00-ce78-11e9-8701-22604a972108.png)
I made it using a single stroke in a single object with a controller so it's easier to have fun with it! (If the shader would use a vector path)

[logo-triangles.zip](https://github.com/ppy/osu/files/3569228/logo-triangles.zip)

**Comment by ed722** [comment]
I'd be interested to try this over the weekend, but I had a few questions before I got started.

It sounds like the "logo texture" solution proposed by EmilySunpy is not enough because the logo texture may still look bad at very high resolutions.  Instead, we need the path to be rendered by the GPU.

It seems like GLES and older OpenGL support is needed, and only very new versions of GLES support geometry shaders.  So it is not really possible to have the GPU draw the image given the vector path and have compatibility with older hardware.  Without geometry shaders, the GPU cannot really create primitives by itself, it can only transform primitives given from the CPU.

Instead we could triangulate the path on the CPU, and just have the shader add the "scrolling" effect.  Does this approach sound okay?  If we did this, would it be better to do the triangulation ahead of time, and store a file with all the triangles?  Or store the path and do the triangulation in the game before it plays the animation?  

In either case, what formats for storing the triangulation/path would be acceptable? Is this something that can be hardcoded to the current logo, or should it be easy to change to a different path?  Parsing a whole SVG file for the logo will be a nightmare, but perhaps just the `<path>`s from the SVG?

**Comment by Wieku** [comment]
I think 2K, 4K or even 8K (depending on osu!'s resolution/platform) mipmapped texture shouldn't be that bad. I think custom geometry just for 1 second animation is like shooting to a fly with a cannon.

I modified @EmilySunpy logo a bit in GIMP:
![logo-test](https://user-images.githubusercontent.com/5307179/71755720-52f04a80-2e8c-11ea-913c-43d7342a2ba2.png)

I've made a demo using my own client (click for YT video):
[![Click for video](https://img.youtube.com/vi/l1IhagRNNw8/hqdefault.jpg)](https://www.youtube.com/watch?v=l1IhagRNNw8)

And my fragment shader looks like this (highlight and animation are controlled by Glider objects):
```
#version 330

uniform sampler2DArray tex;
uniform float highlight;
uniform float animation;

in vec2 tex_coord;

out vec4 color;

vec3 rgb2hsv(vec3 c)
{
    vec4 K = vec4(0.0, -1.0 / 3.0, 2.0 / 3.0, -1.0);
    vec4 p = mix(vec4(c.bg, K.wz), vec4(c.gb, K.xy), step(c.b, c.g));
    vec4 q = mix(vec4(p.xyw, c.r), vec4(c.r, p.yzx), step(p.x, c.r));

    float d = q.x - min(q.w, q.y);
    float e = 1.0e-10;
    return vec3(abs(q.z + (q.w - q.y) / (6.0 * d + e)), d / (q.x + e), q.x);
}

void main() {
    vec4 in_color = texture(tex, vec3(tex_coord, 0));

    vec3 hsv = rgb2hsv(in_color.rgb);

    color = vec4(vec3(hsv.r < highlight ? (hsv.r < animation ? 0.4f : 1f ) : 0f), (hsv.r < highlight ? 0.8f : 0f) * in_color.a);

}
```

If someone want to try it (sorry for the size, Hibernate lib weights a lot, was too lazy to make another gradle module just for the test, Java 8 is needed, should work on Windows, Linux and MacOS): https://drive.google.com/file/d/19NYLcKGmzr0DkiHtUELFjjKiGLWy_JkU/view?usp=sharing

**Comment by Wieku** [comment]
Not everyone trusts random binaries so I've made a new branch with that animation: https://github.com/Wieku/danser/tree/lazer-logo-test

**Comment by Wieku** [comment]
I suck in AE, so I would be thankful for hue-exported original logo (It would be the best if rounded edge will be added, explanation below). I will try to implement it in lazer tomorrow.
![image](https://user-images.githubusercontent.com/5307179/71770706-14ac6700-2f30-11ea-8bfe-d4a31306ee5a.png)

**Comment by Wieku** [comment]
Ok, I made a try in lazer this time with the logo above: https://youtu.be/3VQ9RuhWhQs

**Comment by iiSaLMaN** [comment]
The logo lines seem to be thick, otherwise great job!

**Comment by Wieku** [comment]
It looks like this right now (I know, there are still a lot of artifacts) : https://youtu.be/rqIPQtHx_yI

If someone wants to play with this I created a branch on my fork: https://github.com/Wieku/osu/tree/logo-shader

Of course you need different osu-resources:
https://github.com/Wieku/osu-resources/tree/logo-shader

**Comment by peppy** [comment]
That's looking pretty good! Just needs some tweaking to bring it closer to the existing animation.

**Comment by Wieku** [comment]
Also with that we will need higher resolution gamemodes textures. The last one before animated logo looks pretty pixelated on 27" WQHD screen.

As for animation, I still have to find an efficient way to generate caps at the end of paths.
