### ISSUE TITLE
Creating 3 point sliders still uses Bezier curve shape

### ISSUE THREAD

**Issue by malachimdube** [ppy/osu#5845]
**Describe the missing feature:** 
In Osu!Stable, creating a slider with 3 points in the editor creates a curve based on the circle containing all three points rather than using the standard bezier curve shape. Currently Osu!Lazer is capable of handling such sliders in existing maps correctly (displays correctly and behaves correctly when moving points around), but will always create bezier sliders when making new hit objects in the editor. 

A large portion of mappers would also likely agree that any segment of a slider between red anchors or ends with only one grey tick should use this circular curve shape as it is much easier to work with and looks a lot better, but this would be a new feature.

**Proposal designs of the feature:** 
If a slider is created with exactly three points, it should use the circular curve shape rather than the bezier curve shape to match Osu!Stable. It should not be impossible to create 3 point bezier sliders, as creating a slider with 4 points and then deleting one results in a 3 point Bezier curve in Osu!Stable.

Making all slider sections containing three points use this shape could be achieved via approximation, such as described here: http://spencermortensen.com/articles/bezier-circle/.

**Comment by peppy** [comment]
Both of these additions are planned.

**Comment by FullTablet** [comment]
While mappers from stable are already used to 3 points making a circular slider, and 4 points + 1 anchor deletion making a quadratic Bezier curve. Don't you think that behavior is counter-intuitive for new mappers?

Also, the current slider format doesn't allow Bézier sliders that have consecutive anchor points in the same position (since those are interpreted as Red anchor points by the game client). Nor does it allow concatenating Bézier curves with circular curves (like Bézier curves are concatenated by using red anchor points).

What about making a new anchor color (for example, green) for making circular sliders?

1. When clicking 3 points to make a slider, the mid point is made Green. This makes a circular slider.

2. Anchor points colors can be modified by right clicking and Ctrl-click, just like in stable.
Delete <-> White Anchor <-> Red Anchor <-> Green Anchor.
Two Green anchors can't be consecutive (and even if someone made one by editing the .osu file, the color of the anchor point that follows the first green anchor point is ignored when generating the slider).

3. When there is only White and Red anchors, the slider behaves as a concatenation of Bezier curves (like it does in stable for Bezier type sliders).

4. Each Green anchor is the middle anchor point of a circular path. Regardless of its color, the point that follows it is both the end point of the circular curve, and the start of the next curve if there are more anchor points. The path of the slider can continue either with a Bezier curve or with another circular curve.

5. Instead of specifying the whole slider type as either B| (Bézier) or P| (Circular) in the .osu file, and denoting red anchor points by repeating anchors, the color of each anchor point is specified by a prefix (R| is red, G| is green, | is white).

Examples:
Simple circular slider (with 3 points)
302,156,11546,2,0,G|323:227|306:300,1,150,2|8,0:0|0:0,0:0:0:0:
(old format: 302,156,11546,2,0,P|323:227|306:300,1,150,2|8,0:0|0:0,0:0:0:0:)

Concatenation of linear Bezier curves:
228,96,19560,2,0,R|260:88R|276:96|312:88,1,75,2|0,0:0|0:0,0:0:0:0:
(old format: 228,96,19560,2,0,B|260:88|260:88|276:96|276:96|312:88,1,75,2|0,0:0|0:0,0:0:0:0:)
Note that 228,96,19560,2,0,|260:88|260:88|276:96|276:96|312:88,1,75,2|0,0:0|0:0,0:0:0:0: in the new format would denote a 5-degree Bézier curve that wasn't possible to do with the old format.

Concatenation of a circular curve and a Bezier curve:
200,100,19560,2,0,G|250:150|300:100|300:50|300:50|350:75,1,75,2|0,0:0|0:0,0:0:0:0:
Which would create a curve that looks like this https://i.imgur.com/8ielRpu.png

**Comment by malachimdube** [comment]
Three point bezier curves are almost always not useful in comparison to circular shapes. Really, the only cases where it's really nice to have this as a feature is with longer, sweeping slider shapes. I would say that the interface should make it much easier for new mappers to access circular curves than 3 point bezier curves. Virtually every new mapper ends up discovering how to do this accidentally anyways. 

The way of storing curve types individually seems okay, just remember that there is a third type of curve, catmull, which appears in a good number of older ranked maps. It would also require old maps to be scanned and rewritten to use the new format, which already is done to some degree I believe but would end up taking even longer. My idea was to use the current format (in which all sliders with more than three points are treated as bezier concatenations), but tack on to the end an optional list of what you were calling green anchors, which would be stored in four values: X position, Y position, the index of the anchor on the slider that green anchor comes after, and how many bezier points are being used to represent this curve. Upon saving the map, the editor would create bezier points in the .osu using the approximation technique in the link I shared above, and would store the green anchor's information so that opening up the map in the editor afterwards would still show the green anchor, not the bezier replacements. Upon opening or uploading a map, a check will be done on all green anchors to make sure they are correctly being approximated (in other words, that the .osu has not been tampered with in a way that makes the bezier points not represent the green point correctly). In the event that the .osu has been messed with, it just deletes the green anchor and leaves the new bezier points instead.

**Comment by FullTablet** [comment]
I was suggesting that if the mapper makes a slider with 3 points, the middle point would turn green, so it turns into a circular slider. One advantage of this over the current system in the stable build is that there is more visibility of what is happening to the slider, which helps new mappers understand how the system works faster. Also, changing between a circular slider (green middle point), a quadratic bezier (white middle point), and 2 concatenated linear beziers (red middle point) is more intuitive.

The first line of an .osu file indicates the version of the format. Current ranked maps are in formats that range from v3 to v14, and the .osu files themselves do not need to be changed. My proposal would increase the version used by new maps to v15. Catmull and Linear type sliders could still be compatible with the new version just for retro-compatibility, by checking if the anchor point list starts with C| or L| and using the old format.

The problem with your proposal is that you would need to keep the green point information in a comment attached to the hitobjects (something I am not even sure the format allows). If those comments aren't supported, you would need to raise the current version to v15 anyways. If they are allowed, reading and interpreting the lines describing sliders in the .osu file becomes considerably more complex.

The advantage biggest I see is that the stable client would successfully load the sliders during gameplay (even if it read it has an incompatible v15 version, it could attempt to read it anyways, and be successful at doing so).

**Comment by peppy** [comment]
We will be offering the ability to select curve style separately from point count.
