### ISSUE TITLE
Allow for disabling hitcircle fade out effect

### ISSUE THREAD

**Issue by toiglak** [ppy/osu#5913]
**Background:**
I use [WubWoofWolf's skin](https://circle-people.com/wp-content/Skins/Black%20W0lf%20(WubWoofWolf)/WWW%20v1.8.1%20[2017-09].osk) and it has implemented hitcircles in default-x. 
This was made to bypass fade out effect of hitcircle in osu!stable.
![image](https://user-images.githubusercontent.com/37531387/64060777-9f233980-cbd1-11e9-8e5b-8a8b2f508e76.png) 

**Request:**
As default-x is now broken in lazer (and I think it's intentional due to new skin standards) I'd like to get an option to enable or disable this effect. 
I would add it alongside "snaking sliders" and "cursor trial" in the menu or just as setting in the future implementation of skin.ini.

**Comment by peppy** [comment]
I believe this is only broken in the current build. Please try the previous or next bulld.

**Comment by ToIGLAK** [comment]
Yeah, it broke after 2019.828.0 release.

**Comment by peppy** [comment]
Slider ball colour will be fixed in an incoming skin configuration refactor.

**Comment by Piefayth** [comment]
Sorry for the noise on this old issue. 

If anyone's as insistent as I am about playing without hitcircle fade, but also wants to beta test lazer, you can pull in the changes from the `nofade` branch on [my fork](https://github.com/Piefayth/osu/pull/1/files). This will give you an option under the ruleset specific settings for osu to disable the fade.

I don't intend to PR this, since -
1. It does not behave the same as stable. This will disable the circle fade out on ALL legacy skins, not just skins where the hitcircle is baked into `default-x`.
2. I believe this will be irrelevant when the lazer skinning implementation is complete.

But I've been enjoying playing with it, so I thought I'd share with anyone who comes across this issue with the same question. 👍
