### ISSUE TITLE
Inconsistent sound effects when clicking mod icons

### ISSUE THREAD

**Issue by phosphene47** [ppy/osu#5916]
**Describe the bug:**

When left-clicking on a mod icon, you can hear both checkbox and button sounds.
When right-clicking, you can only hear the checkbox sound.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/n66rj

**osu!lazer version:** 2019.830.0

**Logs:** irrelevant

**Comment by bdach** [comment]
@phosphene47 Are you sure you haven't mixed up right and left clicks? I hear an extra squeaky sound effect on the left click (sounds like two, and one on right click).

I think [`HoverClickSounds.OnClick()` does not fire when right-clicking](https://github.com/ppy/osu/blob/76474987ef2f5f95febaab385634d99d38b31e0f/osu.Game/Graphics/UserInterface/HoverClickSounds.cs#L27), hence the extra sound effect on left-clicks. [Changing `HoverClickSounds` to just `HoverSounds` on `ModButton`](https://github.com/ppy/osu/blob/07983877dbc891f2214f9a6ca9fa52bfd5d9e454/osu.Game/Overlays/Mods/ModButton.cs#L286) would ensure consistency but remove the extra effect. I haven't looked too deeply yet into going the other way (adding the missing effect to the right click), the event would have to be routed to `HoverClickSounds`.

But then again, I'm not sure that second option would be OK UX-wise, since `HoverClickSounds` are reused all over the place, even in controls that don't really do anything when right-clicked and therefore probably shouldn't emit a sound effect. Possibly maybe some additional subclassing could be done? (`HoverClickSounds -> HoverLeftClickSounds` and then a `HoverClickSounds` that fires the effect on both?)

**Comment by phosphene47** [comment]
That's right, my bad. Left-clicking produces an extra sound.

**Comment by bdach** [comment]
Probably worth reopening this after the revert in #5983.

**Comment by bdach** [comment]
I'll give this a second go - as discussed, I will be:

* guarding existing `OnClick()` handlers with left click checks where relevant,
* guarding existing `ClickEvent` cases in `Handle()` with left click checks where relevant,
* reviewing existing `OnMouseUp()` implementations for potential workarounds for the lack of right clicks on `OnClick()`,
* finally concluding with changing `EnableClick` to `true` in `OsuUserInputManager.RightMouseManager`

I very much doubt all of this is going to fit in a reviewable PR size-wise, so I'll probably be splitting those changes into three or four. Before I even start working on the code however I'll enumerate all usages I can find and determine whether they need changing or not. I'll attach the reports I generate to the PRs.

I'll also be considering attaching at least some regression tests with the changes, but that might also inflate the volume a lot.

**Comment by bdach** [comment]
[Here's the preliminary report.](https://gist.github.com/bdach/96129a54f9454c959e6747965d465fb5) Honestly this is a lot and I'm a bit daunted by the amount of changes/PRs/regressions this could generate.

Posting for potential "is it worth it"/UX feedback. By the way, I looked at how right clicks are handled in stable, and it doesn't seem to differentiate between right clicks on buttons and similar UI items (ie. buttons can be clicked with both mouse buttons) - is lazer not handling it the same way intended? I guessed it was, but if it wasn't then a whole lot of those guards won't be necessary.

**Comment by peppy** [comment]
It's an interesting one. For lazer (and osu-framework) we've been trying to draw from user expectations, checking common UX patterns in all target operating systems (windows / macOS / mobile). 

In all of these cases, right click can generally not be used in most places a left click would actuate a control, so I think that *is* the correct direction (unlike stable).

**Comment by Joehuu** [comment]
No longer a problem in the new design (i.e. no more right click).
