### ISSUE TITLE
Small overlap between buttons at the bottom of song select

### ISSUE THREAD

**Issue by luaneko** [ppy/osu#5923]
**Describe the bug:**

There is a small (1 pixel?) overlap between the buttons at the bottom of song select.

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/27663662/64064632-7473c800-cc47-11e9-989e-70c9a1175285.png)

**osu!lazer version:** 2019.831.0

**Comment by Joehuu** [comment]
Removing from `good first issue` as there is more things concerned.

From what I think the problem is, is the `EdgeSmoothness` and the transparency the colors have when unhovered.

**Comment by LanTenDragon** [comment]
Discussing my findings, getting the ball rolling for alternative solutions

## Root causes

I'll try to explain in order of occurrence, as all these are connected one way or another

- ``Shearing`` causes jaggies to the ``light`` 
- ``EdgeSmoothness`` helps smooth out the artifacts caused by ``Shearing``, but
- ``EdgeSmoothness``'s ``Inflation`` causes the pixels to overflow to the neighbouring ``light``

## My Attempts
- Use ``DrawSizePreservingContainer`` is feasible for ``FooterButton`` that do not change their width, which is not applicable to ``FooterButtonsMods``. When ``ModIcons`` and ``Multiplier`` is added to the button, this attempt will scale wrongly
- Adding a spacing between the ``FooterButtons`` is not feasible either, as now the UI scaling and resolution comes into play.
- Using ``Masking = true`` can help reduce but not eliminate the number of pixels that overlap. Besides, using this will reintroduce jagged edges. 

## Potential Solutions
- Footer redesign so that the colours do not overlap
- Use skinning to overcome this issue (a la osu!stable)
- Give each ``FooterButton`` z-axis depth and do something similar to Front-to-Back pass
