### ISSUE TITLE
hiding the score overlay disables the hit error bar too

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#5931]
**Describe the bug:** when you disable the score overlay it hides the hit error bar too but in osu stable it doesnt

**Screenshots or videos showing encountered issue:** https://streamable.com/77n2f (dont mind the audio delay)

**osu!lazer version:** 2019.831.0

**Comment by bdach** [comment]
Additionally in stable it is possible to disable the error bar independently from the score overlay via settings (`Gameplay -> General -> Score meter type`), so _if_ stable behaviour is to be completely preserved that will also need to be added.

(Due to considerable overlap between both matters I'm posting this as a comment, but this might warrant a new issue instead.)

**Comment by mouzedrift** [comment]
> Additionally in stable it is possible to disable the error bar independently from the score overlay via settings (`Gameplay -> General -> Score meter type`), so _if_ stable behaviour is to be completely preserved that will also need to be added.
> 
> (Due to considerable overlap between both matters I'm posting this as a comment, but this might warrant a new issue instead.)

you can already do that here: 
![osu_2019-08-31_21-46-34](https://user-images.githubusercontent.com/43358824/64068480-088a6300-cc39-11e9-8531-0ac333c95521.png)
🤔

**Comment by bdach** [comment]
Whoops, sorry, good spot. Dunno how I missed that.

**Comment by peppy** [comment]
The "show score overlay" toggle is working as intended for now. Once we flesh out the settings/skinning system more custom options will be provided.

**Comment by jxu** [comment]
Is this still configurable in settings? Or is it done in skin editor?

**Comment by peppy** [comment]
Skin editor only.
