### ISSUE TITLE
Centered hit errors (like osu!stable)

### ISSUE THREAD

**Issue by Fatal3ty** [ppy/osu#5932]
I can't see the hit errors when it's set to the left or right side. It's further away from the sides than the bottom (Widescreen problem,it's not in the field of view) It would be nice if osu!lazer has the same hit error option as stable, as well as the scaling option.

One Option missed same on the stable:
![ss (2019-08-30 at 08 16 00)](https://user-images.githubusercontent.com/53025167/64068454-a0d41800-cc38-11e9-9f9b-3f4f76976dd7.jpg)

**Proposal designs of the feature:** 
Like this (is a screenshot montage, edited by paint.net)
![ss (2019-08-30 at 08 29 02)](https://user-images.githubusercontent.com/53025167/64068455-aaf61680-cc38-11e9-9a21-70d8e400e3b4.png)

**Comment by aspriddell** [comment]
In my opinion, whilst it looks good there may need to be an option to either have hit error or the song progress bar otherwise it could be too large and start to interfere with gameplay. It could be that it if this is turned on it hides the visualiser and compacts it down to a smaller, solid bar which then wouldn't be in the way of some maps. It all depends on the size of the 'stage' and how much padding is left above the percentage.

**Comment by peppy** [comment]
There's already an open PR to change the progress bar display. Adding a bottom aligned hit error display is welcomed.

**Comment by Joehuu** [comment]
Added in https://github.com/ppy/osu/pull/10511
