### ISSUE TITLE
Strange behavior with some settings sliders and the revert button

### ISSUE THREAD

**Issue by phosphene47** [ppy/osu#5940]
**Describe the bug:** 

I suppose this is due to floating point imprecision, but I don't understand why only some sliders are affected, hence why I'm creating this issue on the osu! side instead of framework.

**Screenshots or videos showing encountered issue:** 

1. The orange revert button does not appear even though UI scaling was changed to `1.01x`
![image](https://user-images.githubusercontent.com/27663662/64074456-ca4f7b00-ccee-11e9-97ed-2b70d7150211.png)
![image](https://user-images.githubusercontent.com/27663662/64074457-d4717980-ccee-11e9-864b-ed83af4e7abd.png)

2. Screen position/scale sliders always display the revert button even though the value appears to be the default.
Before changing:
![image](https://user-images.githubusercontent.com/27663662/64074541-f0294f80-ccef-11e9-9ba2-aad8286a4671.png)
After nudging slightly using a mouse:
![image](https://user-images.githubusercontent.com/27663662/64074548-033c1f80-ccf0-11e9-9862-d283d4bc6fba.png)
Bringing the knob back to its original position:
![image](https://user-images.githubusercontent.com/27663662/64074550-0b945a80-ccf0-11e9-993b-6d7dec0a4399.png)

**osu!lazer version:** 2019.831.0

**Logs:** 

[runtime.log](https://github.com/ppy/osu/files/3563309/runtime.log)

**Comment by bdach** [comment]
Yes, this is floating point. Sliders actually have a precision tolerance test using `Math.Abs`, but:

1. For the UI scaling precision is set to `0.01f` in `OsuConfigManager`, but when setting the scale to 51% the result of the precision test is something like `0.0099f`, and therefore `BindableFloat.IsDefault` returns true, as the result underflows slightly.
2. For the horizontal/vertical position the precision is not set, so it defaults to `float.Epsilon`, which is `1.401298E-45`, and so the precision test will pretty much always fail when using the mouse. Keyboard  is fine, since it uses the step property.

Fixing point 1. on floats might be extremely finicky. `decimal` for storage & manipulation might be easier, with conversion to `float` in all performance-intensive spots.

**Comment by phosphene47** [comment]
After digging into the code a bit, I discovered that UI scaling and the layout stuff are the only sliders that use a `float` bindable, whereas everything else like background dim, cursor size, etc. all use `double`. This is probably why the equality test is failing for those particular sliders.

https://github.com/ppy/osu/blob/master/osu.Game/Overlays/Settings/Sections/Graphics/LayoutSettings.cs#L77

I think increase the epsilon, or use `double` which should be sufficient.
