### ISSUE TITLE
Local scores don't link to user correctly in all cases

### ISSUE THREAD

**Issue by SansForSSBU** [ppy/osu#5966]
**Describe the bug:** 
On local leaderboards for a map, scores you set on the old client don't show your profile picture correctly. Clicking on your profile picture for this play brings up an empty profile.
**Screenshots or videos showing encountered issue:** 
(Top score was set on old client, 2nd score was set on new client)
![edited](https://user-images.githubusercontent.com/50700917/64692765-c7425080-d48d-11e9-8636-0f9d3bb4b7d5.PNG)
**osu!lazer version:** 
2019.831.0

**Comment by iiSaLMaN** [comment]
What do you mean by "old client", an old version of lazer? if so, why is this an issue?

**Comment by bdach** [comment]
Since the top score is >1 million, I assume it is from stable. When I scrolled for a bit through my local scores, I stumbled upon a stable play too, *but* strangely enough, it wasn't even mine:

![image](https://user-images.githubusercontent.com/20418176/64207824-b26a2980-ce9d-11e9-9bb5-cfe093011bbe.png)

Clicking on the (absent) profile picture of that user gives me a blank player info overlay:

![image](https://user-images.githubusercontent.com/20418176/64207870-cada4400-ce9d-11e9-8578-02f18f82db0b.png)

This seems to persist throughout restarts, so I'll debug this later - maybe it's a database issue? Not entirely sure it's the same issue, but it seems at least related.

**Comment by peppy** [comment]
This is the result of downloading a replay. This doesn't support user linking by `user_id` yet.

**Comment by SansForSSBU** [comment]
> What do you mean by "old client", an old version of lazer? if so, why is this an issue?

It's scores from the current osu! client, not osu!lazer.

**Comment by LittleEndu** [comment]
Even when the score correctly links the user, user's country flag isn't shown

**Comment by peppy** [comment]
As above, we are not populating or fetch users post-import. This requires database / online considerations which will come a bit later.

**Comment by szmarczak** [comment]
This has happened to me on `Lazer 2021.1113.0`. I saved a replay, restarted the game and all the scores from that particular beatmap I played are not shown. I don't have stable installed.

**Comment by bdach** [comment]
that doesn't even sound like the same issue, and i can't say i really understand what you're trying to report. what does "all the scores from that particular beatmap I played disappeared" mean? if they're still visible in the "local" tab, then in which way did they disappear?

**Comment by szmarczak** [comment]
<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/36894700/142269239-906e91ab-37ea-4888-8f04-20b520245af4.png)

</details>

However I restarted the game yet again and all scores (various difficulties) are visible as expected.

**Comment by bdach** [comment]
that is a separate issue. please note that the original report here concerns the profile overlay/avatar, and not the rank display on song select panels.

i've also attempted to reproduce using the most obvious scenario i could think of and was not able to. please open a separate discussion thread about this, including all details requested in discussion templates/contribution guidelines.
