### ISSUE TITLE
Add creator= and artist= search filters in song select

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#6186]
Recently added in stable https://github.com/ppy/osu-stable-issues/issues/50.

**Comment by bdach** [comment]
Is this done by regex in stable, and if so, mind sharing any details? Because I can see it works really well with spaces (ie. doing `blah1 blah2 artist=name of artist blah3 ar>9` works really well (ie. `blah1`, `blah2` *and* `blah3` are separated from the keyword filters, even when spaces are involved), and I might have quite a bit of trouble in replicating that exactly - I *could* try and reverse it but I figured I'd ask first.

I guess I can leave the implementation up to you too if you'd rather not, I'll just PR some tests and small fixes I did leading up to attempting this.

**Comment by smoogipoo** [comment]
Yeah, stable's regex is `^(\w*)([<>=]=?|!=)(.*)$`
