### ISSUE TITLE
Custom cursor trail appears in the top-left corner when starting a beatmap

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#6246]
**Describe the bug:** (Thanks to the help on Discord I can describe what's the issue)
At the beginning of a beatmap (which has a custom cursor trail in the skin, like [**this**](https://osu.ppy.sh/beatmapsets/64525#osu/200670) one), the cursor trail appears in the top-left corner of the window. This happens with and without autoplay/score overlay on any screen mode (windowed etc.).

**Screenshots or videos showing encountered issue:**
![cursor trail](https://user-images.githubusercontent.com/43073074/65546326-97785b80-df17-11e9-830d-f6e0a40c3f4e.gif)

**osu!lazer version:** 2019.919.0

**Comment by bdach** [comment]
Just so it doesn't get lost, here's a comparison of the cursor trail in the beatmap skin with alpha turned off with a captured frame showing the issue:

![image](https://user-images.githubusercontent.com/20418176/65547262-6f89f780-df19-11e9-952b-b2c2ad490e06.png)

When I looked at the gif above on Discord due to framerate issues it was hard to tell what was happening, but here it's looks more obvious that it's a case of the trail drawing over itself multiple times at (0,0).
