### ISSUE TITLE
Combo colours are very dark and hard to see

### ISSUE THREAD

**Issue by byDave251** [ppy/osu#6356]
**Describe the new feature:** 
I tried lazer on my Android phone in front of a window (I know, I'm genius) and I noticed that red approach circle is not visible at all under sun on fully dimmed background. The circles and sliders sometimes seem coal black in the same case (the border is the only one visible thing). All other colours are ok under sun on my phone. 

**Proposal designs of the feature:** 
Increase the contrast of the red combo colour.

**Comment by iiSaLMaN** [comment]
That should be a thing on your phone not on our game.

**Comment by byDave251** [comment]
> That should be a thing on your phone not on our game.

I don't think so. The game should be designed such a way to be payable under most conditions. 

But I don't want to argue about that. You are the developer and I'll respect your decision if you think it's not a thing which should be changed.

**Comment by iiSaLMaN** [comment]
> You are the developer and I'll respect your decision if you think it's not a thing which should be changed.

Keep in mind I'm not the one making decisions here (just an actively contributor atm), Just throwing in my opinion for this.

This should not be considered an issue in our game but rather a limitation in your device for not optimizing colors for current weather. 

If you really consider this an issue, you would need to be consistent and submit an issue in every app you open because there are "colors that are not visible in the sun" as you've just said.

**Comment by LittleEndu** [comment]
Some options regarding color would be nice to have. This would make the game more accessible (for instance colorblind people might still want to use beatmap combo colors). But a solution to "not visible under sunlight" isn't to add contrast. The real solution is to just have a stronger backlight, something that phones don't have because it kills battery life.

**Comment by byDave251** [comment]
I got your point but I consider this a issue. Most of apps are designed such a way to be very contrast and allow use under most weather conditions. 

> you would need to be consistent and submit an issue in every app you open because there are "colors that are not visible in the sun" as you've just said.

And don't worry, when I find one, I'll submit a issue 😉 (none found so far)

**Comment by byDave251** [comment]
> But a solution to "not visible under sunlight" isn't to add contrast. The real solution is to just have a stronger backlight, something that phones don't have because it kills battery life.

I had problem only with red colour. Most likely the solution would be just contrast on this one specific colour, nothing more.

**Comment by smoogipoo** [comment]
We do use fairly dark combo colours in general:

![image](https://user-images.githubusercontent.com/1329837/66013038-97bebb00-e504-11e9-86e9-5e9824fbf2a9.png)

Top: lazer, bottom: stable

It's definitely something we can consider, I very much prefer stable's colours in lazer with 30% dim + 70% blur:

lazer: https://streamable.com/ro6vo
lazer with stable colours: https://streamable.com/nbqsl

**Comment by peppy** [comment]
@arflyte please advise whether we should use the same combo colours as stable. the lazer ones have always been too dark, so if we aren't using stable colours please provide a set which match the brightness of the second set above.

**Comment by arflyte** [comment]
Hmm, the stable colour definitely looked better. Use that for now. I haven't looked into lazer colours for the longest time, will look into it sometime soon.
