### ISSUE TITLE
when default value changes with update, the old setting is saved

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#6367]
**Describe the bug:** Dont know if it is bad, but last time default value for scroll speed in mania changed. I didnt change it anytime. It stayed on older default after update. Idk if this should be somehow handled. 

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 2019.930 

**Logs:**

**Comment by bdach** [comment]
Those things are a bit problematic, as I don't think there is currently a reliable way to tell if a value of a setting *was* the default, or if it was *specifically* set/desired by the user to be such. Case 1 warrants an automatic change, case 2 does not.

I'm not sure if it is worth it to engage with this sort of problem at the current stage of development. As a finishing touch, maybe - if we wanted to handle this explicitly instead of deferring to the changelog, the best way of handling this kind of thing I can think of is having some sort of migration dialog after a default-changing update explicitly asking the user if they want to change.

**Comment by EVAST9919** [comment]
Imo it's expected. Even if update requires just a default value change, user is still expecting his own values being saved. For example if old default value is his preferable.

**Comment by peppy** [comment]
This is expected behaviour.
