### ISSUE TITLE
Quick retry should have an option to use hold-to-confirm even when it's set to 0ms

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#6397]
Quick retry depending on what key you have it set to might be the only button you can accidentally hit during gameplay and is the only button where such accidental hit loses you the entire run. As such it should have an option to use separate hold-to-confirm value.

**Comment by bdach** [comment]
The entire point of adding 0ms delay was to address the concerns of users who *specifically* did not want the hold-to-confirm behaviour (see #5402). In my opinion if the hold-to-confirm delay *was* set to 0ms, then the user explicitly agrees that it *will* be such, potentially to their detriment.

It is not wise to keep escalating the number of possible settings endlessly. I don't think anyone wants to end up with and/or maintain a baroque selection of multiplying settings with non-trivial interdependencies.

**Comment by LittleEndu** [comment]
I wouldn't call just having another slider explicitly for hold-to-retry a non-trivial interdependence. 

I'm one of those users who don't want hold-to-confirm behaviour. Except for hold-to-retry.

**Comment by kasdlk0** [comment]
Commenting here because I started moving from stable to lazer and it's actually really annoying me having to hold to pause the game in a game like osu where I do need to find the best possible time to pause so that I won't lose any combo or etc, while I still want the retry button to be a hold-to-confirm because one quick wrong tap, that should have been to pause the game, and I can lose all my progress in that map. For me the 100% best thing is it to be just like stable, tap to pause and hold to retry, it really annoys me having only 1 option to control these 2 things. So I think it would be ideal to separate these 2 options, like a 'hold to confirm' for things like retry, and 'hold to confirm pause' just for the pause, so that I can set it to 0ms. 
Things like this, 'quality of life' stuff that is worse in lazer is what is currently keeping me and lots of people from switching to it instead of just staying in stable and being afraid of being forced to play in lazer at some point in the future.

**Comment by peppy** [comment]
https://github.com/ppy/osu/discussions/15334
