### ISSUE TITLE
Beatmap options order does not correspond with keybindings

### ISSUE THREAD

**Issue by DentsHub** [ppy/osu#6399]
Pressing numbers from 1-4 when in the beatmap options does not select the respective action as shown by the menu.

**Current** 
1 - remove from unplayed
2 - clear local scores
3 - edit beatmap
4 - delete all difficulties
**Corrected**
1 - delete all difficulties
2 - remove from unplayer
3 - clear local scores
4 - edit beatmap

![image](https://user-images.githubusercontent.com/36710174/66240582-f480c800-e6f4-11e9-9d79-479302ccaa82.png)

Logs are irrellevant - Version 2019.930.0

**Comment by bdach** [comment]
I was curious why this surfaced, and it turns out the button order has regressed in the past in a non-obvious way - the *Delete all difficulties* moved from last to first. [Here's a bisection log.](https://github.com/ppy/osu/files/3692541/bisection-6399.txt)

Directly offending commit is 9037fb5. It innocuously substitutes an `Add`/`SetLayoutPosition` call to `Insert`:

https://github.com/ppy/osu/blob/80f7d5a0a3cbfa6dba77002c6a20bb80c4bb395b/osu.Game/Screens/Select/Options/BeatmapOptionsOverlay.cs#L113

The `Insert` calls *is* directly equivalent to the pair before. The problem is the cast. To make sure that the *Delete all difficulties* was always last, its depth was set to `float.MaxValue`:

https://github.com/ppy/osu/blob/35ef5a0007a0b0447641dee361ba2a7539dce8e2/osu.Game/Screens/Select/SongSelect.cs#L233

Which at the cast turns into an overflow, doing *precisely* the opposite thing to what was intended:
```csharp
> int p;
> unchecked { p = (int)float.MaxValue; }
> p
-2147483648
```
For added WTF factor, doing `int.MaxValue` is not correct either, since due to loss of precision it gets mangled too:
```csharp
> int p;
> unchecked { p = (int)((float)int.MaxValue); }
> p
-2147483648
```
Doing depth `1` restores the previous order and by extension fixes the invalid button mappings.
