### ISSUE TITLE
Mod buttons on mod select don't transition correctly on first open

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#6405]
Regressed in https://github.com/ppy/osu/pull/5210.

![](https://puu.sh/Ep6qT/6fd65d9000.gif)

**Comment by bdach** [comment]
Just to clarify here what the problem is for potential newcomers that would like to take a look at this - there is a spacing transition on the mod buttons that doesn't play on first open but does play from the second open onwards.

**Comment by amiteshn** [comment]
I'm having a pretty hard time trying to solve this. Since one of the changes which led to this issue was the addition of `protected override bool StartHidden => true;` into both `WaveContainer.cs` and `WaveOverlayContainer.cs`, I thought that maybe the problem was the implementation of `StartHidden` in the framework, but after changing some of the values in `VisibilityContainer.cs` in the `LoadComplete()` method (specifically, changing `PopOut()` to `PopIn()`), I didn't see any changes. My next thought was that the problem may be in the order in which the Drawables are drawn, because if we change the `StartHidden` property in `WaveContainer.cs` to `false`, the mod buttons transition does appear on the first open, but the wave transition does not. This makes me think that the problem is that the wave transition is being drawn on top of the mod buttons transition. I'm not too familiar with how Drawables are implemented, but I do know that they are drawn sequentially, one on top of the other, which is why I think this may be the problem. If this is indeed the problem, I'm not too sure on how to implement a solution, as I don't know which file the Drawables are drawn in, nor do I know at what point in time specific Drawables are drawn. Anyone have any ideas? I'm pretty new to this codebase and large-project development in general, so I'm really sorry if my observations are trivial or incorrect.

**Comment by peppy** [comment]
@amiteshn Please see my framework PR referenced above for a solution to this. You were on the right track but this was definitely not a "good first issue", as the cause was very hard to navigate to.

```
ModSelectOverlay.LoadComplete
   PopOut
   FinishTransforms

ModSelectOverlay.Show()
   PopIn

WavesContainer.LoadComplete
   PopOut
   FinishTransforms <- this is where things went wrong
```

The `FinishTransforms` above would recursively run on all children in WavesContainer, which happened to contain the items which had transforms applied from `ModSelectOverlay`. This would make them instantly complete rather than playing out.

Let me know if you need further clarification on the issue!

**Comment by amiteshn** [comment]
Okay, I think I get it now. The problem was that `LoadComplete()` (and, consequently, `FinishTransforms()`) was called two times on the children in WavesContainer, which contained both the mod items and the waves, causing the transitions to complete right away.

The thing that I am still a bit confused on is why the solution of dividing `LoadComplete()` into two different functions (one asynchronous and the other not) solved the issue. Is it because in `LoadAsyncComplete()` (which is now handling VisibilityContainers which have the attribute `StartHidden` set to `true`), `State.BindValueChanged()` is not called, and therefore, the drawables are not updated according to their visibility state (which would be hidden at this point), allowing the transitions to still appear?

**Comment by peppy** [comment]
you're spot on. it ensures `StarHidden` is applied before any visibility changes.

**Comment by amiteshn** [comment]
Thanks a ton for the clarification!
