### ISSUE TITLE
First time loading lazer on pc

### ISSUE THREAD

**Issue by Razkiery** [ppy/osu#6562]
On the first minutes on loading it goes very, very slow (from 300 fps to 20-30 and sometimes less).
Same for when going to singleplayer with tons of beatmaps (I got more than 3000), it takes around a minute and a half to load up all the bm.

**Screenshots or videos showing encountered issue:** 

Osu!Lazer PC Version: 2019.1021.0

**Logs:**

**Comment by bdach** [comment]
I'm pretty sure performance issues with big beatmap collections are well-known, but then again I can't seem to find an issue tracking that particular issue.

Would you mind elaborating on the second part of performance drops near startup, however? A video showing the issue would be particularly appreciated.

**Comment by Razkiery** [comment]
https://streamable.com/g9sd5

There is, it stays like that for 1:30 minutes more or less.

sometimes recording osu! forces up the fps

**Comment by peppy** [comment]
Known issue, wouldn't be surprised if it's a duplicate.

Will be solved by reducing the database query overhead and avoiding drawable creation on entering song select, via drawable pooling.

**Comment by Aidan-Kerr** [comment]
Just wanted to drop into here and say this is still an issue in Build 2020.418.0. All other issues on this topic were closed a while back after a database update, however I experience ~2mins of loading time every time I enter solo (~60000 Beatmaps). System config is as follows: Ryzen 2700, 32GB of RAM and everything installed on a MX300 NVME Drive (620GB remaining so that is not the bottleneck). Issue seems CPU Limited (i.e. raising my core frequency lowers the time substantially [it used to be almost 4 minutes]) and it seems to "only" use 8 threads.

**Comment by peppy** [comment]
sounds correct. we will be addressing this in the future.

**Comment by Aidan-Kerr** [comment]
After upgrading my PC (Sabrent PCIe Gen4 SSD and Ryzen 3950X) and updating osu! after getting my PC running for the first time in 10 days my loading time is now reduced to ~10 seconds. I'm assuming this improvement is due to the update, thanks for your hard work!

**Comment by peppy** [comment]
Will close this for now as I think we are in roughly acceptable ranges (via https://github.com/ppy/osu/pull/8889 / https://github.com/ppy/osu/pull/8895).
