### ISSUE TITLE
[Android] Random crashes.

### ISSUE THREAD

**Issue by reschan** [ppy/osu#6605]
**Describe the crash:** 
One happen at when I'm loading up a beatmap, one happen whe I'm accessing the setting menu.
Game closed immediately.
**Screenshots or videos showing encountered issue:** 
None.
**osu!lazer version:** 
2019.10.21.0
**Logs:** 
https://drive.google.com/folderview?id=1TewgdXVBwCuYqQXIiipO7lXQpj1BYZr7
**Phone Specifications:** 
Android 9 Xiaomi mi 8 Lite 6GB RAM

**Comment by bdach** [comment]
The crashes are functionally equivalent to #6264, as they also have to do with fetching online data (xamarin's `MobileAuthenticatedStream` seems to break on cancellation); closing.

I am however seeing another error that was supposed to be fixed in the latest release; will reopen the issue that tracked that one originally.
