### ISSUE TITLE
osu!lazer android won't run

### ISSUE THREAD

**Issue by wolfpat01** [ppy/osu#6620]
osu!lazer crush when i right after i lunch the game 
i tried to clear data and updating my android but its still the same
opsu and osu!droid work smothly but i want the official game and its not the same experiance 
 

osu!lazer v1.0  android

spec :
mini m8s ii
ram 2gb
android 6.1 with arm cpu

there is no log file existed 
![Screenshot_20191026-145940](https://user-images.githubusercontent.com/57036855/67619894-5ec2ef00-f801-11e9-8807-0ce508770923.png)
![Screenshot_20191026-142608](https://user-images.githubusercontent.com/57036855/67619895-5f5b8580-f801-11e9-9788-61bfb494b32d.png)
![Screenshot_20191026-150100](https://user-images.githubusercontent.com/57036855/67619904-726e5580-f801-11e9-9a12-11fd3cd3830d.png)

**Comment by enoslayd** [comment]
Your version is incorrect. You should report yhe version as YYYY.MMDD.X (e.g. 2019.1021.0, which is the latest)

**Comment by enoslayd** [comment]
Also logs (which should also be submittedl is located on either internal or external storage/Android/data/sh.ppy.osulazer/logs

**Comment by bdach** [comment]
Thanks for your report. Due to prioritising finishing the client for desktop first we are not accepting reports related to mobile platforms for the time being, unless you're willing to fix them. If you'd like to work on this particular problem, please reopen this issue and state that you'd like to address it yourself; mobile pull requests are also welcome. Otherwise, please check back in the future when the focus of development shifts towards mobile!

**Comment by enoslayd** [comment]
Wait, you're finishing the desktop version already?
