### ISSUE TITLE
Signifier for slider velocity change

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#6683]
**Describe the new feature:** Something I think was missing even from stable is a signifier for slider velocity change in standard and mania. If you haven't played a map before, you have no way of knowing if suddenly a slider (or the whole playfield in mania) is going to become faster or slower.
Also, I'm not sure the taiko approach would be the best (even though it could technically be compatible with mania's layout too), since it can make the playfield feel cluttered and confusing with all the hit objects coming in at once with different speeds.

**Proposal designs of the feature:** I was thinking of maybe arrows inside the slider. They are sense if the slider is quicker than the previous one and sparse if it's slower. They also go at the same speed as the slider ball will.
In mania (and taiko if you agree with me that it could be improved), they would be next to the track, approaching the judgement line at the point where the track will speed up, following the same principles.

![image](https://user-images.githubusercontent.com/15932372/67974793-4abd2a00-fc13-11e9-9af5-db172b08af73.gif)

**EDIT:** Made concept more osuey.

**Comment by bdach** [comment]
Maybe to go with the triangle theming of the game overall, the same triangle particle effects from hit circles can be used on slider bodies, moving along the slider with the appropriate speed? On mania/taiko you could have those floating on the sides of the playfield itself.

Could become too cluttered visually though, would have to see how that'd look. (And it'd obviously not be easy, too.)

**Comment by Snowmander** [comment]
I would also like an indicator, but I fear that the proposed design might be too eye grabbing. The ability to react to a note comes from detecting moving elements (hitcircles appearing, approach circles closing in, and slider expanding) and non-crucial elements shouldn't divert a player's focus too much. 

Instead of moving arrows, I want to suggest a static diagram such as a bunny for speeding up and a turtle for speeding down.

Here's where I got the idea from:

![Screenshot from 2019-11-02 01-02-01](https://user-images.githubusercontent.com/45163894/68038184-b8994c80-fd0c-11e9-90c6-4d8b4071d364.png)
https://youtu.be/6LAupbx_0QY?t=303

**Comment by smileyhead** [comment]
> Instead of moving arrows, I want to suggest a static diagram such as a bunny for speeding up and a turtle for speeding down.

Hmm, that's not a bad idea, especially as we already have similar icons in the hit error bar, but I'm not sure as to their placement, since I doubt it's an option to interfere with the combo number and just icons wouldn't be able to display the speed at which the slider ball is going to go.

![image](https://user-images.githubusercontent.com/15932372/68039701-faa29e00-fccc-11e9-9228-e69ccb576583.png) ![image](https://user-images.githubusercontent.com/15932372/68039724-055d3300-fccd-11e9-8949-5e2dc313d595.png)

**Comment by LanTenDragon** [comment]
Throwing out another idea: 
![Screenshot_20191102_014838](https://user-images.githubusercontent.com/43511642/68044850-234d8680-fd13-11e9-8385-46e3de139e97.png)

Repurpose this dev build warning bar, give it sliding animation or blinking animation, red for speed up, blue for slow down. Idea came from Cytus 2 https://youtu.be/0POctmRMMQU?t=46


>icons wouldn't be able to display the speed at which the slider ball is going to go

I'd argue that players only need to know that there is an impending SV change, then muscle memory would kick in?

**Comment by LanTenDragon** [comment]
Another thing to consider (for the future implementer) is how to handle edge cases of maps, where entire sections of maps are just crazy high and sudden SV changes.

Example maps are https://youtu.be/yzwtnWQhEW4?t=73 and quite a lot of Aspire  Maps (Hellblinde - Solace Of Oblivion comes to mind)

In this case, SV signifier could be turned off otherwise it would stay on screen all the time.

**Comment by smileyhead** [comment]
> Repurpose this dev build warning bar, give it sliding animation or blinking animation, red for speed up, blue for slow down. Idea came from Cytus 2

In Cytus 2, that bar is the judgement line. There is no such thing in standard (and in other game modes it's static). A moving line scanning across the screen would be way too large a signifier for something like this and just having it at the bottom of the screen (aka relying of the player's peripheral vision to notice it) is just bad design.

> I'd argue that players only need to know that there is an impending SV change, then muscle memory would kick in?

SV is a spectrum. You can't rely on muscle memory if all the information you get is it getting faster or slower.

> Another thing to consider (for the future implementer) is how to handle edge cases of maps, where entire sections of maps are just crazy high and sudden SV changes.

I'd imagine it would be a skinnable element and thus could be hidden by map creators, if desired.

**Comment by MightyHelper** [comment]
Couldn't we implement a `slider sub-tick` that would be only visual and would appear 3 to 2 times ( depending on time signature) between the slider ticks?
Maybe make them a bit smaller and darker so they are not confused and, since the player knows the bpm they can just see and "expect" the slider to take x s of time between slider sub-ticks.
The problem with this is if the BPM and SV change at the same time. Then, good luck.

**Comment by MitsukaiDokuro** [comment]
I would put a hue shift in my skin - blue for slower velocity, red for faster velocity. Though the default skin might visualize it with icons or a moving track, as suggested.

See [Redshift](https://en.wikipedia.org/wiki/Redshift), [Blueshift](https://en.wikipedia.org/wiki/Blueshift)
