### ISSUE TITLE
(android)when osu!direct is being in used and left open for a second, it crashed

### ISSUE THREAD

**Issue by dragonGod97677** [ppy/osu#6696]
**Describe the crash:** as in the title, when osu!direct is being in used and left open for a second, it crashed

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 2019.1029.0

**Logs:** 
[logs.zip](https://github.com/ppy/osu/files/3800487/logs.zip)

**Computer Specifications:** Vivo V5 lite Android 6.0 Marshmallow with Funtouch OS 3.0, MediaTek MT6750 1.5GHz Octa Core Cortex-A53 CPU, Mali-T760 GPU, 3GB RAM

**Comment by bdach** [comment]
Thanks for your report. Due to prioritising finishing the client for desktop first we are not accepting reports related to mobile platforms for the time being, unless you're willing to fix them. If you'd like to work on this particular problem, please reopen this issue and state that you'd like to address it yourself; mobile pull requests are also welcome. Otherwise, please check back in the future when the focus of development shifts towards mobile!
