### ISSUE TITLE
osu!lazer startup crash

### ISSUE THREAD

**Issue by fairyboy21** [ppy/osu#6727]
**Describe the crash:** 
osu!lazer startup crashes every time i open it idk why it doing it or how to fix it
**Screenshots or videos showing encountered issue:** 
https://prnt.sc/pswx3b
https://prnt.sc/pswxj9
https://youtu.be/xpsZ5TQFd_w
**osu!lazer version:** 
2019.1105.0
**Logs:** 
https://mega.nz/#!sVEjBYTa!xgjIsMbhVDFtw2C2-7Uk6HgvMJLKLzl1fvtS7Xmj5ck
**Computer Specifications:** 
4gb of ram cpu 2.20ghz

**Comment by bdach** [comment]
You have not provided any more significant information since the last time you tried to report this (#6714). On the video you're checking the wrong directory for logs (they're in `AppData/Roaming/osu/logs`, not in `AppData/Local/osulazer`) and you haven't provided the event viewer logs [I asked for previously](https://github.com/ppy/osu/issues/6714#issuecomment-549528535).

**Comment by fairyboy21** [comment]
ok ill send it to you sorry

**Comment by fairyboy21** [comment]
> You have not provided any more significant information since the last time you tried to report this (#6714). On the video you're checking the wrong directory for logs (they're in `AppData/Roaming/osu/logs`, not in `AppData/Local/osulazer`), and you haven't provided the event viewer logs [I asked for previously](https://github.com/ppy/osu/issues/6714#issuecomment-549528535).

ok i added the log now can you help me

**Comment by bdach** [comment]
The link you've added doesn't seem to work (404); please try again.

**Comment by fairyboy21** [comment]
can i do mega

**Comment by swoolcock** [comment]
https://pastebin.com/

You’re welcome.

**Comment by fairyboy21** [comment]
sorry i dont do that also i added it

**Comment by bdach** [comment]
Looking at the log attached the symptom is the same as #6496 - closing as duplicate.

It appears you're on an Intel card with a broken OpenGL driver that the vendor won't fix. We have some idea of what could help, but testing is difficult since this is a hardware-specific issue, so please bear with us while we try to figure it out.

**Comment by fairyboy21** [comment]
it work a long time ago in 2018 i dont remember that mouth or day

**Comment by fairyboy21** [comment]
idk if that helps

**Comment by bdach** [comment]
Yes, we know, this has started to appear with the bump to .NET Core 3.0 (release 2019.1011.0), any earlier releases should work for you - see referred issue above.
