### ISSUE TITLE
Profile "kudosu" section hyperlinks don't work

### ISSUE THREAD

**Issue by peppy** [ppy/osu#6747]
![image](https://user-images.githubusercontent.com/191335/68302973-519dde00-00e6-11ea-8327-c5d2e5f6974d.png)

Tested on my own profile. Clicking results in no action.

**Comment by EVAST9919** [comment]
Might be related to https://github.com/ppy/osu/pull/6591

**Comment by bdach** [comment]
After taking a look this does not appear to be any sort of regression - this broke because API is now returning beatmap discussion links:
```
https://osu.ppy.sh/beatmapsets/beatmap-discussions/{beatmap-id}
```
that are then not properly handled in [`GetLinkDetails`](https://github.com/ppy/osu/blob/af7322a763fa7876cf0badc3fee2394fa6b07bb1/osu.Game/Online/Chat/MessageFormatter.cs#L112) (they end up catching `beatmap-discussions` instead of the id). Incidentally I noticed in `#lazer` (thanks, @Gabixel!) that beatmap links with fragment components like
```
https://osu.ppy.sh/beatmapsets/{set-id}#{ruleset}/{beatmap-id}
```
are also not properly handled due to not splitting by the fragment delimiter `#`.
