### ISSUE TITLE
Thats Lot Crash + Very very laggy

### ISSUE THREAD

**Issue by DannyKurniawan642** [ppy/osu#6782]
![Screenshot_20191109-164428](https://user-images.githubusercontent.com/49144332/68526632-c3597000-0310-11ea-8e2f-9256fb7b569e.png)

Please Fix Crash even though I have active storage permissions and very laggy
Phone=Motorola E4 Plus (XT1770)
CPU=mediatek6737m

**Comment by DannyKurniawan642** [comment]
sorry i bad english :^

**Comment by bdach** [comment]
Thanks for your report. We are aware of the problems you mention, but due to prioritising finishing the client for desktop first we are not accepting reports related to mobile platforms for the time being, unless you're willing to fix them. If you'd like to work on this particular problem, please reopen this issue and state that you'd like to address it yourself; mobile pull requests are also welcome. Otherwise, please check back in the future when the focus of development shifts towards mobile!
