### ISSUE TITLE
Add "tap to BPM" beat timing wizard to editor

### ISSUE THREAD

**Issue by mcendu** [ppy/osu#6793]
## Feature description
Already in osu!stable, it gives a convenient way to adjust the BPM in case one do not know how to describe the BPM of a piece of music in terms of numbers. This issue is created on the grounds of
* the current, slider based timing looks too inconvenient to use, even for those who can describe the BPM,
* In case the feature described is already implemented, there is no explicit hint on how to use the feature, and
* No related issues (aside from this) are found in #6686.

## Proposed design
This can be added to the editor as either:

* A button, or
* A bound key

that the player clicks/presses on every supposed beat to adjust the BPM.

**Comment by peppy** [comment]
The current timing screen is a placeholder / general structure. It will be improved on as we go.

**Comment by manmathew** [comment]
I have a suggestion regarding the timing panel.
This is more for multi-bpm songs as timing them can be quite complicated.
What could be done for those songs is setting a timeline that is parallel to the waveform of the mp3, and having the ability to add "timing-lines" and line them up with the waveform (zooming would probably go very far). By adding multiple timing-lines (and I say lines instead of points because you can easily line up lines with waveform), the bpm is automatically calculated for each section between two lines, and if given manual input, can be changed to another bpm that is a multiple (or factor) of the original computer-generated value. This might be somewhat complex to understand (I don't know if it is, but when I try to explain to others they don't seem to understand too well), but this would greatly improve the timing panel for multi bpm songs.

**Comment by peppy** [comment]
The editor will be flexible enough to support multiple BPM scenarios.

**Comment by Joehuu** [comment]
Added in https://github.com/ppy/osu/pull/18523.
