### ISSUE TITLE
Taiko notes appear lately on screen

### ISSUE THREAD

**Issue by phosphene47** [ppy/osu#6889]
**Describe the bug:** 

Taiko notes appear (fade in) when their *center* reaches the edge of the field, in contrast to stable where the notes appear entirely.

**Screenshots or videos showing encountered issue:** 

Lazer: https://streamable.com/1sc9v
Stable: https://streamable.com/47c2v

Slow motion effect was applied by me, not the game.

**osu!lazer version:** 2019.1113.0

**Comment by bdach** [comment]
FWIW, I'm pretty sure I managed to track down something partly relevant, and it's around here:

https://github.com/ppy/osu/blob/3d13fe485d471ea83fc57a124218431fd3c91f83/osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableTaikoHitObject.cs#L108-L111

When I changed that to `new Vector2(0, DrawWidth / 2)`, the scrolling started working as intended. However that utterly breaks alignment of everything, so it's not a viable fix.

It seems that the origin of the hitobjects might be used to determine if they should be drawn (ie. if the origin is within screen space bounds, then draw, otherwise don't). What I *think* would be the best fix to make it consider drawable bounds and not only the origin, but that might come with a performance penalty.

**Comment by smoogipoo** [comment]
I’m fairly certain this is related to the lifetime start of hitobjects, which is computed exactly to the time hitobjects are supposed to become visible in the scrolling area. For taiko they’re offset by half their width via the origin.

A proper solution would consist of making ScrollingHitObjectContainer knowledgeable about the origin position and offset the lifetime start backwards. 

Performance hit should not be significant here, there’s code that does it in the reverse direction (`ScrollingHitObjectContainer.computeInitialStateRecursive`), and out should sit right beside that.
