### ISSUE TITLE
Clicking imported beatmap notification from menu doesn't select correct beatmap

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#6908]
It transitions to song select but most times it doesn't select the correct beatmap. Likely due to the first selection logic that's changed with recent song select changes.

https://streamable.com/t0u48 (sorry for the huge video)

Needs tests.

**Comment by bdach** [comment]
I tried a few times and haven't gotten this to reproduce once, both from direct and by importing from archives - unsure if I'm doing something wrong or there are some extra circumstances to take into account, like beatmap count?

**Comment by peppy** [comment]
You can reproduce it by being in the wrong ruleset before selecting.

**Comment by bdach** [comment]
Ok, I've managed to reproduce. Also requires converted beatmap setting to be off in addition to having the wrong ruleset selected.

**Comment by bdach** [comment]
As an update of sorts: I have a reproducing scenario and I thought I had a failing test, but in practice there seems to be some `OsuGame`/`SongSelect` crosstalk that makes the fix I wanted to apply only work some of the time. From what I've looked at the cause is very likely closely related to the debounce changes, but the obvious resolutions sometimes fail.

**Comment by bdach** [comment]
Leaving info for posterity at least. Reproduction scenario is:

* Disable displaying converted beatmaps
* Go to song select, use ruleset A
* Trigger import of map in ruleset B by any method
* Go back to main menu
* Click on notification

Song select will end up in the right ruleset but on the wrong song.

From actual code digging:

* The second time song select is navigated to, the carousel will filter itself twice: the first time in the old ruleset (A) without debounce, the second in the new one (B) with debounce since `OsuGame.PresentBeatmap` navigates to solo first before setting the new ruleset.
* At first I thought the "select beatmap without bypassing filters" path in `SongSelect.workingBeatmapChanged` was incorrectly not forcing the bypass due to the rulesets being equal, so I tried moving the selection out of the conditional. This would sometimes work but the more I tested it the more times it didn't, to the point where at the end it wouldn't work at all even though I could have sworn it did.
* Looking at the logs I think sometimes one of the ongoing filters would set `WorkingBeatmap` themselves and therefore overwrite what `OsuGame.PresentBeatmap` set, making this a race. Cannot say this with certainty however due to not having debugged to the bottom of it. Flushing filters doesn't help, it just makes it surefire.

In general the fix might end up being just essentially reordering `PresentBeatmap` to navigate to solo at the very end, but that feels (1) hacky and (2) not that testable. I also still think the `workingBeatmapChanged` thing is a bug but I'm not confident it won't regress more places.

**Comment by peppy** [comment]
I've created a reproduction test for this (https://github.com/ppy/osu/compare/master...peppy:wip-present-tests?expand=1). Note that this is not the exact case that is failing for you (ruleset specific) but is a similar one.

It looks like song select is not in a good state immediately after import to present a new beatmap. Going out and running the "present beatmap" step a second time succeeds as expected.

This test also brings up another fail case, which is that present *never* works if currently at song select.

I'll continue to add the remaining tests and then start looking at a solution tomorrow.
