### ISSUE TITLE
not installed osu!lazer after update 2019.1122.0

### ISSUE THREAD

**Issue by bruh-droid** [ppy/osu#6921]
app osu!lazer "packet seems to be broken "
![Screenshot_20191123-154719](https://user-images.githubusercontent.com/58106217/69477163-60d69880-0e15-11ea-8ef1-78a9eb679ba8.png)

**Comment by huoyaoyuan** [comment]
Confirmed on my Android device, which successed for USB Debug, and has Mono/Xamarin support packages present.

**Comment by huoyaoyuan** [comment]
apks produced locally by me even breaks for **older tags**, where CI provides working packages.
Not sure about the root cause. Maybe SDK configuration error.

**Comment by huoyaoyuan** [comment]
The root cause should be **missing signature**.
Comparing apks downloaded from GitHub release, the latest, not working one is missing a `META-INF` folder, which is for signing.
After trying some steps at local, I can produce _signed and unsigned apk together_, by invoking F5 in VS.
The **signed** apk for latest version installs successfully, and the **unsigned** version is complained broken.

The problem to solve becomes _why CI is uploading unsigned apk_.

**Comment by peppy** [comment]
Thanks for that. I'm uploading a fixed build imminently.

**Comment by bruh-droid** [comment]
I deserve to check the app

**Comment by huoyaoyuan** [comment]
The fixed apk works fine for me.

**Comment by smileyhead** [comment]
The problem persists for me (and I'd imagine everyone else) on the latest build (2019.1128.0).
I haven't been able to install new versions since 2019.1122.0. I assumed you'd be shipping the fixed APK with the newest version, but like I said it's still broken.
Also, ever since 2019.1122.0 I've been getting a Play Protect warning while attempting to install updates (shown below) (I'd imagine it has to do with the missing signature). Temporarily disabling Play Protect doesn't solve the issue.

![image](https://user-images.githubusercontent.com/15932372/69828664-05454a00-121d-11ea-9106-10efe94f0cd2.png)

**Comment by bdach** [comment]
I just installed from the release (cleanly) and it works fine. Perhaps the update functionality is not working for some reason, but the signature is not missing. I'd say if update is broken it's highly likely to be due to Play Protect complaining about whatever it doesn't like now.

**Comment by smileyhead** [comment]
I get a generic “⚠️ App not installed” screen whether Play Protect is enabled or not.

**Comment by bdach** [comment]
I can't even begin to act on that information alone seeing that a clean reinstall does certainly work here.

**Comment by smileyhead** [comment]
Right, sorry.
I'm trying to update 2019.1106.0 to the latest version. I'm running Android 9 on a Nokia 7 Plus.
