### ISSUE TITLE
Add note to "Background source" setting for non-supporters

### ISSUE THREAD

**Issue by elleyer** [ppy/osu#6932]
**Describe the bug:** 
"Beatmap source" isn't working correctly. (Maybe this should work another way?)
**Screenshots or videos showing encountered issue:** 
https://streamable.com/1d2d4
**osu!lazer version:** 
latest
**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3882532/runtime.log)

**Comment by bdach** [comment]
I can't seem to hit anything like this from a quick check, looks like it's working ok. Nothing in `runtime.log` that would point to a definite cause either from what I can see.

Does this happen reliably?

**Comment by elleyer** [comment]
Just skipped a part with "if the user is supporter". My bad, sorry.

**Comment by bdach** [comment]
Yeah, this setting probably shouldn't be even visible to non-supporters then. Going to rename this to track that appropriately.

**Comment by peppy** [comment]
Skin source is also supporter only. Should probably be text in settings to mention this.

**Comment by Wieku** [comment]
My loose proposal

Without supporter:
![image](https://user-images.githubusercontent.com/5307179/71877927-b0a1c280-312a-11ea-8e5b-1ae48f3ff9dc.png)

With supporter:
![image](https://user-images.githubusercontent.com/5307179/71878108-286fed00-312b-11ea-9f94-caf80df1f74d.png)

I think we don't want to hide options for supporters because then users may not know that certain features exist.
And I think "Default" option should be added, because even supporters may want to have default backgrounds.

**Comment by peppy** [comment]
Looks fine, although the text should read "Changes to this setting will only apply with an active supporter tag."

**Comment by Wieku** [comment]
I thought about disabling the setting (e.g. opening background source dropdown is disabled when user doesn't have supporter tag) but I think now that letting user choose the setting anyway is better UX (in case they get the supporter soon after).
