### ISSUE TITLE
Add the ability to test gameplay from the editor

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#7008]
**Describe the new feature:** 
When you press F5 in the osu!editor currently a No Mod play of the map will start at the point you were in the editor.
I suggest you can change this to use any(allowed) combination of mods. Just to see how it looks and save you going all the way 'round.

**Comment by bdach** [comment]
Is starting off with requiring the beatmap to be saved before preview via a dialog acceptable to start with, the same way stable does? Asking because that assumption looks to make gameplay preview pretty trivial to implement, while having it work without save would require some consideration on structure.

The main immediate issue with making it work on-the-fly is that `MasterGameplayClockContainer` is hard-dependent on `WorkingBeatmap`, which does not receive any changes until save in the context of editor. So I would have to decouple the gameplay clock from that first, or develop a way to get a `WorkingBeatmap` from an `EditorBeatmap`, which may prove to be a precarious and time-consuming task.

**Comment by peppy** [comment]
Yep, I think getting this working by the simplest means possible is a good starting point. The eventual vision can be refactored in some future.

**Comment by peppy** [comment]
Resolved via #15582.

**Comment by bdach** [comment]
Was hesitant to close this seeing the current version is somewhat crude, but may as well. I know you've said in the past that you've got a vision of how it should eventually work that's significantly different, but that may be better suited for a follow up issue (or multiple?), if you ever have the time and patience to write that up.

**Comment by peppy** [comment]
I'd prefer to create smaller issues for the remaining tasks, as the part which is mentioned in this issue is already completed.
