### ISSUE TITLE
osu!lazer bug report for Low-End Android devices

### ISSUE THREAD

**Issue by MicRy2578** [ppy/osu#7220]
The performance in osu!lazer version 2019.1213.0 is much worst than version 2019.1205.0 for Low-End Android devices because the screen is flickering more often and uses more RAM than usual

In my devices:
- Vsync: ±370MB RAM used
- 2x refresh rate: ±650 MB RAM used
- 4x refresh rate: ±890 MB RAM used
- 8x refresh rate: ±1,2 GB RAM used
- Unlimited: >1,6 GB RAM used

I'm using Xiaomi Redmi 7 (3/32GB) [1,8 RAM available] and always use 4x refresh rate as frame limiter

Note:
Please the osu!lazer developer consider performance update than UI update because for some Low-End devices like me can't handle 5* stars beatmaps rendering because of too much objects that has to be render

Xiaomi Redmi 7 specs:
https://www.google.com/amp/s/m.gsmarena.com/xiaomi_redmi_7-ampp-9498.php

osu!lazer (2019.1205.0) performance test video:
https://youtu.be/Z_TKyH6jJSo

**Comment by bdach** [comment]
As you should have noticed by the warnings placed when opening a new issue, we're currently not accepting bug reports for mobile. Performance is a constant work in progress on all platforms; if it turns out that it has degraded everywhere (while investigating #7218, for example), we'll take a look at possible causes. Otherwise you'll have to wait for overall performance improvements that will be coming in the future.

**Comment by smoogipoo** [comment]
Gonna keep this one open for a little bit longer, since if the performance has gone down so much then we’ve regressed somewhere.

**Comment by peppy** [comment]
Can't see any performance changes on iOS.

Not sure what the video is showing since it was uploaded at 30fps with no frame display visible and no signs of performance degradation.

**Comment by peppy** [comment]
Plesae reopen if you have any solid benchmarks (ie. side-by-side comparison with old builds, including frame display visible).
