### ISSUE TITLE
Move any transformations added at point of BDL

### ISSUE THREAD

**Issue by iiSaLMaN** [ppy/osu#7290]
Adding transformations at BDL [may never be applied](https://github.com/ppy/osu/pull/6288#issuecomment-538835727), which obviously causes issues as reported by users, see https://github.com/ppy/osu/issues/6269 & https://github.com/ppy/osu/issues/7288

Should be moved to `LoadComplete` which is the best point to start adding transformations on as the drawable is fully loaded.

**Comment by bdach** [comment]
Potentially another thing to throw a custom analyzer at if that ever happens.

**Comment by smoogipoo** [comment]
This is a general practice for our use-cases, but is fully supported by the framework - drawables _do_ get a clock inside BDL unlike the mentioned comment states. It is generally seen as unsafe since time may be progressing during the load (e.g. during an async context).

As such, fixes only need to be applied on a per-case basis and we don't need a general issue thread for this.
