### ISSUE TITLE
Sort by title is hidden on startup

### ISSUE THREAD

**Issue by vruss** [ppy/osu#7415]
**Describe the bug:** 
When going to the song select screen for the first time, the _green_ sort by title isn't showing. It's hidden inside the dropdown menu.

**Screenshots or videos showing encountered issue:** 
![Hidden title sort](https://user-images.githubusercontent.com/10886082/71640392-77c8a000-2c89-11ea-85f5-3651854d4196.png)

![Shows inside dropdown](https://user-images.githubusercontent.com/10886082/71640394-844cf880-2c89-11ea-94ab-ff4dab5f9f81.png)

**osu!lazer version:** 
2019.1227.0

**Logs:** 
I don't know where to find them.

**Comment by bdach** [comment]
I wouldn't necessarily call this a bug. The overflow showing up is desired behaviour - it only shows up when all sorting options cannot be displayed directly because of the screen being too narrow in size, and the options are ordered alphabetically. Perhaps this *does* need some design/UX discussion whether or not we want the active sort mode to always be visible outside of the overflow.

**Comment by peppy** [comment]
This is intended behaviour for now.
