### ISSUE TITLE
Hide menu cursor on touch devices

### ISSUE THREAD

**Issue by mcendu** [ppy/osu#7437]
**Describe the new feature:** Cursor showing up is not expected and looks bad on touch devices, and should be hidden. Cursor in std mode should not be hidden.

**Proposal designs of the feature:** When touch input is used, an invisible drawable would be drawn in place of the cursor.

**Comment by bdach** [comment]
Related to ppy/osu-framework#1514 (probably going to need to expose something framework-side to indicate a touch device is being used).

**Comment by ThatsNiceGuy** [comment]
> Cursor showing up is not expected and looks bad on touch devices, and should be hidden.

I think it looks great and with the cursor rotation it makes the menu cursor feel fun on mobile/touch screens. Also since this is osu!, I feel like not having a menu cursor would be strange considering the type of UI that is being used.
Maybe hiding menu cursor on touch devices could be added as a toggle somewhere near the bottom of the settings or in the section where cursor settings currently are.

**Comment by peppy** [comment]
a toggle is fine, but the default would be hidden.

**Comment by Luxiono** [comment]
@ThatsNiceGuy Keep in mind that on mobile the cursor may cause unneeded lag.
(This comment was not needed, just wanted to point it out.)

**Comment by mcendu** [comment]
Edited description for clarification.
