### ISSUE TITLE
Osu!Lazer stopped working after re-install (MacOS)

### ISSUE THREAD

**Issue by koshxd** [ppy/osu#7445]
I basically re-installed the osu.app.zip file (I meant the Application)  since I accidentally had removed something from the folder and couldn't get the application open again to fix it, and when I extracted the new Osu!Lazer application and opened it, it basically stopped responding after the "Welcome to Osu" message. The animation right after that will not play so I am permanently stuck and I have no idea why. Could it be because that file that I removed before the re-install or is it something else? And also I was wondering how to access the files folder without having to open the application itself (Because I think thats where the problem is).

**Comment by koshxd** [comment]
To elaborate the issue more I was experimenting on how to import the osu!stable skins/songs into the new Lazer version. I basically removed everything in the "file" folder, and I accidentally closed the folder. Without the files being in that folder there is no way of getting that folder back open (Or I'm just dumb and I haven't figured it out). That's why I re-installed it but the problem still persists.

**Comment by bdach** [comment]
Your explanation is quite convoluted, so let me clarify - you deleted the `~/.local/share/osu/files` directory? (Not entirely clear on what "closing the folder" means in this context)

If that's the case, either restore the deleted folder or remove `~/.local/share/osu/client.db` and reimport everything from stable.

Closing for now, will reopen if this turns out to be an actual issue.
