### ISSUE TITLE
Can osu mobile play with keypad and tablet?

### ISSUE THREAD

**Issue by JapaneseOsuMania** [ppy/osu#7461]
I want to play osu mobile with keyboard and tablet

https://youtu.be/jW0n4BYc9i8

This video can play with keyboard

But not upload osu mobile play with tablet video on youtube

Can osu mobile play with tablet too?

**Comment by smoogipoo** [comment]
That's a different game, called opsu!. With that said, it is unlikely that you'll be able to play with tablet on mobile.

**Comment by recapitalverb** [comment]
Android has tablet support if I recall correctly, though I'm not sure if you can configure anything.

**Comment by Wieku** [comment]
@smoogipoo Actually (sorry for video quality): https://youtu.be/Zb4l6mM0vic
Was able to pull it off on Galaxy S10+... partially. The problem is that not every Android device have tablet support. But when it does it only works in portrait mode. I think when lazer gets more popular on mobile some guy probably will port custom drivers to Android and Wacom tablets, matter of time.

@JapaneseOsuMania It's not a tablet but Samsung Galaxy Note which have pen included with the phone.

**Comment by smoogipoo** [comment]
Seems like it's acting in mouse-mode there correct? That's what I'd expect since phones don't usually have drivers. I believe it'll work on iPhones too, but again you're only going to get mouse-mode support.

Until custom drivers on Android, sure. Not our department though.

**Comment by Wieku** [comment]
Nope, it has absolute mapping. But as I said, only in portrait mode, sadly. It looks like mouse-mode because hovering doesn't work.

**Comment by JapaneseOsuMania** [comment]
Tablet for not support
But penmouse?
 Penmouse is can play?
