### ISSUE TITLE
Black colored sliders when scrolling very fast the editor timeline

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#7477]
**Describe the bug:** 
- Open osu!editor
- Scroll very fast the timeline
- You can see some black colored sliders for ~a few milliseconds~ one frame (This seems to happen with any skin)

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/43073074/71992542-d5cf2780-3235-11ea-81a3-d84bec611610.png)

**osu!lazer version:** `2020.104.0`

**Comment by peppy** [comment]
Can you make a video of this? Do they change to the correct colour after the "few milliseconds"?

**Comment by smoogipoo** [comment]
Seems like this happens only on sliders. Very weird but:
1. It's not related to the colour of sliders (i.e. `AccentColour`). This can be tested by setting the colour returned via `ColourAt()` to a single value.
2. It's not related to the _path_ drawnode (i.e. it's not drawing with a null/not-available texture). This can be tested by moving `validateTexture()` inside `ApplyState()` of a custom `DrawNode`.
3. It is not related to AA. This can be tested by removing the AA portion.
4. It is calculating a texture with a path radius of 1 inside `load()`, implying the path radius isn't set early enough. I don't know if this is primary contributor to the issue since the is re-validated in `GenerateDrawNodeSubtree`, but it is potentially contributing to some performance issues. Ideally we'd want the path radius to be set before `load()`.

This is probably the same issue that's causing slider corruption and buffered container corruption on window resize, maybe something inside `BufferedDrawNode`.

**Comment by peppy** [comment]
I believe this has since been resolved. Haven't seen it happen in a long time. Please comment if you still manage to reproduce it.

**Comment by Gabixel** [comment]
Hmm. Looks like it's still reproducible...
I'm not 100% sure, but it seems easier to reproduce it on longer maps: [I used this one](https://osu.ppy.sh/beatmapsets/1054045#osu/2202493) for example.

> This (slowed down) example shows that you can still see black-colored sliders for one frame:
![example gif](https://user-images.githubusercontent.com/43073074/95028037-8f600980-069d-11eb-913a-a8c072710127.gif)

> Here's a screenshot: 
![screenshot](https://user-images.githubusercontent.com/43073074/95028070-e665de80-069d-11eb-993a-a9d66096719a.png)

**Comment by Pennek** [comment]
I have also noticed this in build 2020.1109.0

**Comment by peppy** [comment]
Not sure if related, but I can reproduce weirdness on my slider velocity adjust PR #10417. I did manage to get the black thing to happen once or twice, but not captured on video:

https://user-images.githubusercontent.com/191335/133749191-25e23919-8ca9-4c11-97f9-f21e2496d08d.mp4

**Comment by Pennek** [comment]
Here's a clearer image of the above. May help analyse what is going wrong: 
![](https://pennek.s-ul.eu/qrlVTL85.png)
