### ISSUE TITLE
Mods selected in song select are also applied in other screens

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#7480]
**Describe the bug:**
- Select a mod in SongSelect (like Nightcore so you can hear the difference)
- Go to Multi
- Mods are selected again (with the Nightcore example, you can hear the music with the Nightcore effect)

**Screenshots or videos showing encountered issue:** [Video](https://drive.google.com/file/d/1lZzUKzrGbpnQnIWAgV1Gr23S8zyHmcqK/view?usp=sharing)

**osu!lazer version:** 2020.104.0

**Comment by peppy** [comment]
Can you confirm this doesn't actually apply to the multiplayer game? I think this is a known regression that we chose to accept for the time being.

**Comment by Gabixel** [comment]
Multiplayer game seems fine (except for the mod customization, but it's not related to this specific issue: with the Daycore mod, for example, the first game used the selected speed, and re-entering the room caused the game to use the default value).
With the Nightcore mod example, the audio is normal when creating/entering a room, so it seems to happen only in the lounge.

**Comment by Gabixel** [comment]
This issue also happens on the file import screen from the settings.
I'm including it here so I don't have to open a similar issue (and I'll also generalize the title).

![image](https://user-images.githubusercontent.com/43073074/132369003-70b5cab9-9716-429e-9bd6-282e4c223a1c.png)

**Comment by peppy** [comment]
I am so confused. What does "import files" have to do with anything?

**Comment by Gabixel** [comment]
If you mean the attached screenshot, it was just to indicate the button to open the file import screen. It was my mistake since it has nothing to do with the issue. I can add a video if needed.

**Comment by peppy** [comment]
I've started looking into this, but need a bit of discussion regarding the forward direction. Right now we have a default specification that any `OsuScreen` will apply adjustments. Then it is forcefully disabled at the top level screens (and the reason for this issue is that the `false` override is missing for `OnlinePlayScreen` and `DirectorySelectionScreen`).

An easy enough solution is to just add the override in the missing places, but it seems like something which will keep coming up as there is no safety against this.

A few options to make this more sane:

- Make the property `abstract` to force each new screen to make a choice (but this could not be flexible enough if the same screen may display at the main menu and also song select? not sure if this will ever be a thing)
- Make the property an `enum`, with the default mode `Inherit`. Or nullable where null means to inherit.

**Comment by Joehuu** [comment]
Playlists / multi lounge regressed in https://github.com/ppy/osu/pull/14743.
