### ISSUE TITLE
Key amount value for mania beatmaps in beatmap info is always zero

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#7502]
![Screenshot_1](https://user-images.githubusercontent.com/22874522/72210232-5194d280-34c9-11ea-937b-c0584db7c08c.png)
![Screenshot_3](https://user-images.githubusercontent.com/22874522/72210233-5194d280-34c9-11ea-9b88-a348d4fb5fa6.png)

**Comment by bdach** [comment]
As a side note I don't think a progress bar is the most apt way to show the number of keys, since it's not a sliding scale per se contrary to the other info. I'd imagine something like a segmented progress bar could be more suitable, with perhaps also a way (via segment colour?) to indicate special columns.

**Comment by EVAST9919** [comment]
It's not an online/API bug. It's trying to apply difficulty to this field, since Key Amount = Circle size. And for some reason adjusted difficulty is 0.
