### ISSUE TITLE
Hit explosions appear underneath hitcircles

### ISSUE THREAD

**Issue by RBRat3** [ppy/osu#7584]
Classic skin hitcircleoverlay always appears over hit300g etc... after hit & fade out, May cause aesthetic issues with skins that use the two as a layered effect.

![image](https://user-images.githubusercontent.com/13491985/72862803-6b3dd300-3c9c-11ea-9d05-dac9edcf6d51.png)

**osu!lazer version:** 2020.118.0

**Logs:** N/A

**Comment by smoogipoo** [comment]
That's weird. I was sure those things were already placed at a higher level than the hitobjects...

**Comment by RBRat3** [comment]
I honestly don't mind it like that, but others might so I thought it was worth mentioning.

**Comment by EVAST9919** [comment]
@RBRat3 can you please provide the skin?

**Comment by bdach** [comment]
the skin is not required. this happens on all legacy skins.

**Comment by frenzibyte** [comment]
I've looked at fixing this and while I was comparing my change to the current behaviour of osu!stable, turns out the judgements seem to be appearing behind the hitcircles on osu!stable:
![ezgif com-gif-maker-4](https://user-images.githubusercontent.com/22781491/93729359-d396d880-fbcc-11ea-8a1d-0300eb1da48e.gif)
[full video before changes](https://streamable.com/oos4u9)
[full video after changes](https://streamable.com/145yvq)
[full video osu!stable (from 0:15)](https://streamable.com/5l8hgm)

As can be seen above in the stable portion of the GIF, the first red hit circle appeared above the hit result from the previous object.

But at the same time, if a hit result overlapped with an object in osu!stable, the hit result will appear above it, not entirely sure what to do here...

<details>
<summary>my change</summary>

```diff
diff --git a/osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs b/osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
index 4ef9bbe09..902d3a8ba 100644
--- a/osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
+++ b/osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
@@ -44,11 +44,6 @@ public OsuPlayfield()
                     RelativeSizeAxes = Axes.Both
                 },
                 followPoints = new FollowPointRenderer
-                {
-                    RelativeSizeAxes = Axes.Both,
-                    Depth = 2,
-                },
-                judgementLayer = new JudgementContainer<DrawableOsuJudgement>
                 {
                     RelativeSizeAxes = Axes.Both,
                     Depth = 1,
@@ -64,6 +59,11 @@ public OsuPlayfield()
                     RelativeSizeAxes = Axes.Both,
                     Depth = -1,
                 },
+                judgementLayer = new JudgementContainer<DrawableOsuJudgement>
+                {
+                    RelativeSizeAxes = Axes.Both,
+                    Depth = -2,
+                },
             };
 
             hitPolicy = new OrderedHitPolicy(HitObjectContainer);
```
</details>

**Comment by peppy** [comment]
They 100% appear behind for the default skin. Have you tested using a custom skin?

**Comment by frenzibyte** [comment]
Nope, I haven't, thought it would be the same case for all skins; will check with a custom skin soon enough.

**Comment by smoogipoo** [comment]
Stable has a sort of dynamic depth ordering which is going to be interesting to replicate in lazer. Needs a bit more thought but the explosion might need to be part of the hitobject rather than at a playfield level.

**Comment by Finxert** [comment]
This is a pretty big problem since you really can't see if you're hitting anything on streams regardless of the skin, here's a video showing the effect.

https://youtu.be/cIq1LWFKvQQ

iirc this wasn't a problem in stable because judgments were offset to not appear right underneath the circle but to it's side.

**Comment by Finxert** [comment]
Sorry didn't see.
