### ISSUE TITLE
Easy mod for osu!mania halves key amount stat

### ISSUE THREAD

**Issue by AndyThePie** [ppy/osu#7610]
**Describe the bug:** 
If you use the Easy modifier in osu!mania mode, it seems to halve all stats - including key count (which it should not). This doesn't affect gameplay, just the key count number under the beatmap details.

**Screenshots or videos showing encountered issue:** 
With the Easy modifier enabled:
![Easy mod enabled](https://user-images.githubusercontent.com/25379179/73117259-a5170f80-3f10-11ea-8767-d642ed086b80.png)
Without the Easy modifier enabled:
![Without easy mod](https://user-images.githubusercontent.com/25379179/73117262-b3652b80-3f10-11ea-96d9-da0c945d7695.png)

**osu!lazer version:** 
2020.118.0
(self-compiled on Ubuntu 19.10)

**Logs:** 
...

**Comment by TheWildTree** [comment]
This happens because both Easy and HardRock affect all beatmap stats, no matter what mode is chosen.

What would be the preferred way to solve this here - to hide the issue by making `AdvancedStats` ignore the adjusted CS value in this case (since it doesn't make a difference gameplay-wise) or to override mania's EZ/HR `ApplyToDifficulty` to not touch circle size / key amount at all?

**Comment by bdach** [comment]
The second option seems much better than papering over the wrong value in the UI.
