### ISSUE TITLE
The application absolutely does not start on EMUI 9 (Android 9) after the last update

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#7612]
**Describe the crash:** 
After a welcome message that "this version is early", the application immediately turns off. Reinstallation did not help.
**osu!lazer version:** 
2020.125.0
**Logs:** 
[network.log](https://github.com/ppy/osu/files/4111682/network.log)
[runtime.log](https://github.com/ppy/osu/files/4111683/runtime.log)
[database.log](https://github.com/ppy/osu/files/4111684/database.log)
[performance.log](https://github.com/ppy/osu/files/4111685/performance.log)
Honor 8X, android 9

**Comment by swoolcock** [comment]
Likely related to #6507

**Comment by iiSaLMaN** [comment]
Actually
https://github.com/ppy/osu/blob/b9235ca863083bd8603b70cfba96ce249a6e85f3/osu.Game/Screens/Menu/MainMenu.cs#L119
is causing a null reference exception because the dialog will not be created for game hosts that can't exit (mobile hosts)
this can simply be fixed by `exitConfirmOverlay?.CreateProxy() ?? Drawable.Empty`.

**Comment by swoolcock** [comment]
This will also cause iOS to fail, then.  Your solution seems fair.
