### ISSUE TITLE
Beatmaps missing from listing

### ISSUE THREAD

**Issue by agausmann** [ppy/osu#7619]
**Describe the bug:** Since updating to 2020.125.0, most of my beatmaps have disappeared from the list.

**Screenshots or videos showing encountered issue:** 

![Capture](https://user-images.githubusercontent.com/6611767/73127643-07abf200-3f89-11ea-8b4a-8a8c6c7b83fb.PNG)

I have many more beatmaps than is shown, but almost none of them are displayed. Of the ones that are, only the hardest difficulties are available. This led me to think there might be some filter active based on difficulty, but I was unable to find anything like that.

**osu!lazer version:**  2020.125.0

**Logs:** 
[performance.log](https://github.com/ppy/osu/files/4112875/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4112876/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4112877/updater.log)
[database.log](https://github.com/ppy/osu/files/4112878/database.log)
[network.log](https://github.com/ppy/osu/files/4112879/network.log)

**Comment by bdach** [comment]
Could you check what your settings for displaying beatmap difficulty range are (see below)?

![image](https://user-images.githubusercontent.com/20418176/73127966-79eff700-3fc8-11ea-96ec-e2b8566f7bd5.png)

I'm thinking you might have set it high in the past, but the actual filter hasn't been hooked up since very recently, so once it started working it might have the effect you describe.

**Comment by agausmann** [comment]
Yes, thank you. It was changed from the default setting. I changed it back, and just to be sure nothing funny was going on I performed an upgrade from 118 to 125 again. Seems to be fine now.
