### ISSUE TITLE
Break overlay is hard to see on bright backgrounds

### ISSUE THREAD

**Issue by iSimpFor** [ppy/osu#7656]
when you have white text, if the background happens to be bright where the information text is at break, it may make it more difficult to read the text

example of the issue:
~~![osu_2020-01-28_14-13-34](https://user-images.githubusercontent.com/44514667/73302979-2c97a380-41db-11ea-8fd4-2b26b90d60b2.jpg)~~
edit: example is not working

**Comment by peppy** [comment]
@arflyte suggestions here? the break overlay needs to be visible but also not too-present as to block storyboards from view,

**Comment by arflyte** [comment]
We can't dim the background for a lil bit during the break time? Else another solution to move the overlay somewhere else; like close to the bottom where we can put some sort of gradient overlay.

**Comment by peppy** [comment]
Historically, breaks are *brighter* than gameplay, showing cutscenes in storyboards and the likes.

**Comment by Craftplacer** [comment]
Isn't adjusting text color to the contrast the way?

**Comment by peppy** [comment]
You're welcome to provide a suggestion, but what you just said hold no water. Unless you plan on using an invert filter (which will look like stupid).

**Comment by Craftplacer** [comment]
> Unless you plan on using an invert filter (which will look like stupid).

Inverting colors is of course not the way, every UI designer (especially the ones who are working on dark mode) don't do that.

I toyed around with colors and it seems like that doing my initial idea is indeed "hard" because 1) the text size is too small 2) the darker colors look out of place, even if they actually matched the contrast.

I tried looking into what can be done to the text itself, osu!framework does have the ability to give text a shadow, but it can't be set how wide it spreads, how light it is and so on. Text with outlines doesn't seem to be a thing either, so my attempt ended here.

I will look later into this again how it will look like with simply adding a translucent background.

**Comment by peppy** [comment]
For what it's worth, you can make custom "shadows" using blur parameters (see the leaderboard score text implementation).

**Comment by mcendu** [comment]
Maybe check out `EdgeEffectParameters`?

**Comment by Craftplacer** [comment]
> Maybe check out EdgeEffectParameters?

They don't work on OsuSpriteText.

> For what it's worth, you can make custom "shadows" using blur parameters (see the leaderboard score text implementation).

Doesn't seem to do much except remove the shadow.

![](https://files.catbox.moe/cw2bu5.png)

**Comment by peppy** [comment]
Please read what I said again. There is an existing implementation you need to follow.

**Comment by Malmik** [comment]
You can consider black outline. Think of an Windows cursor. It is basically white with black frame, so it is visible on both light and dark backgrounds.

**Comment by Joehuu** [comment]
Resolved in https://github.com/ppy/osu/pull/29615.
![osu!_uXytYMyPiD](https://github.com/user-attachments/assets/7f88f8b9-4e0e-4c71-9f42-491d624cd06a)
