### ISSUE TITLE
Weird Sliders When Customizing Mods

### ISSUE THREAD

**Issue by Squaduck** [ppy/osu#7688]
**Describe the bug:**
When using arrow keys to customize any mod it changes by weird increments.
It changes by 0.4 when above 3.0
**Screenshots or videos showing encountered issue:** 
![osu_2020-01-30_19-54-54](https://user-images.githubusercontent.com/55469508/73503530-7c709900-439a-11ea-84ac-b3e773e6674b.jpg)
![osu_2020-01-30_19-54-57](https://user-images.githubusercontent.com/55469508/73503531-7c709900-439a-11ea-871d-8f4e81166c75.jpg)
![osu_2020-01-30_19-55-14](https://user-images.githubusercontent.com/55469508/73503532-7d092f80-439a-11ea-96e2-d1c464d264e9.jpg)
**osu!lazer version:** 
2020.130.0
**Logs:**

**Comment by peppy** [comment]
To document my findings so far (because we are still unsure of a correct solution):

framework, `BindableNumber` line 86:

![image](https://user-images.githubusercontent.com/191335/73915783-682f1d80-48ff-11ea-8a74-18025e4a1e57.png)

Precision is a float in this case, and gets negligible error added as a result. By dividing by this value (with added error) the resulting number can flip sides of the round operation depends on the bindable's current value.

```
Math.Round(3.4500000476837158 / 0.10000000149011612, MidpointRounding.AwayFromZero) * 0.10000000149011612

3.4000000506639481

Math.Round(3.4500000476837158 / 0.1, MidpointRounding.AwayFromZero) * 0.1

3.5
```

This requires a framework fix to at least make it consistent across the whole range, but I'm unsure how this should be performed. @bdach any suggestions from your end?
