### ISSUE TITLE
No Drain mod

### ISSUE THREAD

**Issue by mcendu** [ppy/osu#7697]
**Describe the new feature:** Health does not drain with this mod enabled. Misses still causes HP to reduce.

**Proposal designs of the feature:** 
```c#
public class ModNoDrain : IApplicableToHealthProcessor
{
    public override string Name => "No Drain";
    public override string Acronym => "ND";
    public override ModType Type = ModType.DifficultyReduction;
    public override bool Ranked => false;
    public override double ScoreMultiplier => 0.75; // any value between 0.5 and 1

    public void ApplyToHealthProcessor(HealthProcessor healthProcessor)
    {
        if (healthProcessor is DrainingHealthProcessor drainingProcessor)
            // Do something...
    }
}
```

**Comment by venix12** [comment]
what's the use of it if No Fail exists though?

**Comment by recapitalverb** [comment]
@venix12 You can still fail without HP drain ("Misses still causes HP to reduce.") I think the use of this is because many players are extremely ticked off by the sense of urgency that HP drain occurs.

Also the current HP drain implementation drains way too much, but that's irrelevant in this issue thread.

**Comment by bdach** [comment]
@recapitalverb I'm pretty sure you *can't ever fail* on No Fail though. That's literally in the name; if that were the case, it'd be a bug. Your HP will go to 0, sure, which it *should*.

---

There was another mod proposal which had a "remove drain" part - see #7441.

It might be viable to have drain removal as a mod customisation option, but in general I'd be *extremely* wary of how such an option was to be implemented, since we don't want mods to become so convoluted that it is no longer possible to tell which mod does what.

**Comment by smoogipoo** [comment]
I'm gonna deny this one on the basis that HP0 only drains at most 5% throughout the entire beatmap.

HP1, the minimum settable via the difficulty adjustment mod, drains 10% (if my calculations are correct). It should probably be lowered to minimum HP0, but other than that it is very unnoticeable.
