### ISSUE TITLE
FullscreenOverlays have weird rendering / scaling issues

### ISSUE THREAD

**Issue by TheWildTree** [ppy/osu#7727]
**Describe the bug:** 
When trying to exactly match some osu-web designs, I noticed some elements aren't consistently rendered the same way, even on UI scale 1.

Here you can see the exact same `Height: 2` element (the separator) rendered differently in two places in `BeatmapSetOverlay`:
![image](https://user-images.githubusercontent.com/27722894/73759091-b4495900-476b-11ea-9c67-4f7832b3c1db.png)

Scroll just a bit and it goes the other way around:
![image](https://user-images.githubusercontent.com/27722894/73759206-e490f780-476b-11ea-9466-8f20ca48492b.png)

It visually changes its height by one pixel depending on what position it ends up after scrolling.

Font rendering feels off too, it's a bit blurry for me, I never realized why it seemed like that but it might be the same issue. It's not as visible though so no screenshots here.

edit: this is probably a framework issue, please transfer if needed

**Comment by peppy** [comment]
for the lines: this is due to how opengl draws quads. it can be alleviated via `EdgeSmoothness`. there are quite a few examples of this in the osu! code base already.

for the text: this is due to text not being forced to screen pixel locations, causing the textures to potentially get interpolated between pixels. for the time being this is something we're willing to sacrifice, but there are methods to improve this in the future.

**Comment by peppy** [comment]
Closing for now as per descriptions above.
