### ISSUE TITLE
The panel that shows map info displayed wrongly.

### ISSUE THREAD

**Issue by Pix-00** [ppy/osu#7842]
**Describe the bug:** 
The panel that shows map info displayed wrongly.
Length is always 0:00, and rest of the four icons have not been rendered.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/15878537/74581852-6516ea00-4fef-11ea-82e3-f3125996d56f.png)

**osu!lazer version:** 
2020.208.0

**Logs:** 
Runtime: https://paste.ubuntu.com/p/yMJxXrJQHM/
Database: https://paste.ubuntu.com/p/RxPjGDhSp8/

**Comment by Joehuu** [comment]
Seems like you had lazer since https://github.com/ppy/osu/pull/5290 (Jul 10, 2019), reimporting/redownloading will resolve the problem. Issue to fix old imports is tracked in https://github.com/ppy/osu/issues/5376.

Icons are not added yet, tracked in https://github.com/ppy/osu/issues/2229.

Closing as both issues are already being tracked.
