### ISSUE TITLE
Switching frame limiter to Vsync causes fps drops

### ISSUE THREAD

**Issue by Sinamer** [ppy/osu#7944]
**Describe the bug:** I can still move my cursor, hear the sounds and blindly click on UI, but the frame stays still. Happens in all screen modes

**Screenshots or videos showing encountered issue:** https://youtu.be/yWISRsL7Kys

**osu!lazer version:** 2020.221.0, but noticed the same issue right before updating (which is weird, I remember playing with Vsync on that release and it worked fine)

**Logs:** 
[performance.log](https://github.com/ppy/osu/files/4236710/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4236711/runtime.log)

**Comment by iiSaLMaN** [comment]
Can you please provide us with your GPU info here, can reproduce with `Intel HD Graphics 3000`.

**Comment by Snowmander** [comment]
Turning on Vsync drops the fps below 144. Setting it to unlimited, I get around 300.

Windows 10, `Vega RX 56`

Tested on the previous release (2020.215.0) as well, same performance there.

**Comment by Sinamer** [comment]
My GPU is Intel HD Graphics as well

**Comment by Sinamer** [comment]
I'm not sure if I provided enough info, so here's a dxdiag file:
[DxDiag.txt](https://github.com/ppy/osu/files/4239002/DxDiag.txt)

**Comment by smoogipoo** [comment]
This doesn't sound like an issue from our side - it's likely an issue with the graphics driver (the official Intel driver is stated to not support Win-10, the driver you have installed is provided by Microsoft to do so).

Does osu!stable vsync correctly for you?

If you're able to debug, clone `https://github.com/ppy/osu-framework` and run `osu.Framework.Tests` and see if the issue can be replicated there (Ctrl+F7 is supported). If so, try removing the following lines:

https://github.com/ppy/osu-framework/blob/067c7034215156356ac6c7ff1f2b3d1e0eddd4c2/osu.Framework/Platform/GameHost.cs#L395-L398

Otherwise report back and we'll make some builds for you.

**Comment by Sinamer** [comment]
osu!stable's and osu!lazer's vsync work just as expected up until and including 2020.208.0 version, since then, the issue is occurring. I'm not able to debug myself, so I would greatly appreciate the builds!

**Comment by peppy** [comment]
Great, that's enough to narrow it down to the [glFinish change](https://github.com/ppy/osu-framework/pull/3258).

**Comment by Sinamer** [comment]
Can no longer reproduce on latest osu!lazer release!
Here's proof: https://youtu.be/AhqZllMHJjo
