### ISSUE TITLE
Drain level does not match stable

### ISSUE THREAD

**Issue by MTGPROD** [ppy/osu#7975]
**Describe the bug:** 

When a map have hp drain 6, just some 100 and 50 can drain a lot of hp. After that, just one miss and you lost. In osu stable it's not hard at this point. 

**Screenshots or videos showing encountered issue:** 

https://youtu.be/vaOy9Dgqt2A

**osu!lazer version:** 

2020.221.0

**Logs:**
*please attach logs here, which are located at:*
- `%AppData%/osu/logs` *(on Windows),*
- `~/.local/share/osu/logs` *(on Linux & macOS).*

I'm on android

**Comment by bdach** [comment]
Raised as a concern before (#7606), was never reopened as a separate issue about the drain level itself (draining after break is tracked in #7607). Renamed for better searchability (not that I advocate for completely reverting to stable algorithm, maybe slightly less harsh drain will be ok too).

**Comment by MTGPROD** [comment]
Just reduce the difficulty because if you only do 100s or 50s and a few 300s the slightest miss and it's lost.

**Comment by recapitalverb** [comment]
> Just reduce the difficulty because if you only do 100s or 50s and a few 300s the slightest miss and it's lost.

After some testing, I think it's rather related to that the current HP drain implementation doesn't take into account how notes are spaced between each other time-wise instead of whether the difficulty is too high, as there are a lot of definitely passable HD6 maps. Not 100% sure though, I have not looked at the code related to this.

**Comment by MTGPROD** [comment]
Especially since I speak well of hp drain 6 in particular because I tested scarlet pink which has 7 hp drain and I lose much less hp when you have a 100, 50 or miss (When I was around 75% and I had a lot of miss and well a 300 gave much more hp than hp drain 6). The problem is more complex

**Comment by FAB1150** [comment]
noticed this too, i came back to lazer after some time and after updating HP drain became much higher than stable. I liked the slightly lower drain of the previous release I was in, now it's way too aggressive.

**Comment by ghm12** [comment]
can give a headsup to this. played "Chi no Iro wa Kiiro" by Hollow Wings and Extra was pretty much one miss and a couple of 100s at the middle and you're dead

**Comment by bdach** [comment]
Please refrain from posting "confirmation / +1" comments as they don't really bring in much value - you can use comment reactions instead. We are well aware that the current drain algorithm is not exactly as was in stable and it was a [conscious decision at the time of re-adding it](https://github.com/ppy/osu/pull/7361#issuecomment-569177204). Suggestions on what should be done to change this situation are however welcome.

**Comment by mcendu** [comment]
Instead of using the lowest percentage attainable during a perfect play, I propose that the lowest percentage of _the worst possible no miss_ play (or slightly harsher) should be used to determine the drain rate. This can make the drain more relaxed.

**Comment by MTGPROD** [comment]
The 2020.225.0 update seems to fix the problem. It's your turn to test

**Comment by bdach** [comment]
[There have been no changes to drain specifically in the latest update.](https://osu.ppy.sh/home/changelog/lazer/2020.225.0)

**Comment by smoogipoo** [comment]
I'm going to keep this issue open until people are satisfied with the HP drain.

@mcendu using the worst possible miss will make HP drain significantly more lenient, which isn't what we're aiming for. We want the drain rate to be rougher in these higher HP maps (HP>5); HP6 results in a minimum HP from drain of 62%.

The PR above raises the amount of HP awarded for GOODs from 1.5% to 2.5%, without lowering the drain rate.

**Comment by MTGPROD** [comment]
So, i we make a 50. what happens? @smoogipoo

**Comment by smoogipoo** [comment]
Currently, HP is decreased by 0.25%

**Comment by MTGPROD** [comment]
Legit

**Comment by MTGPROD** [comment]
But, what is HitResult.Ok it is for mania/taiko or something ?

**Comment by MTGPROD** [comment]
From hp drain 6 it's much more playable than before. Thanks @smoogipoo

**Comment by MTGPROD** [comment]
But for specific maps that's very hard like before...

**Comment by aemino** [comment]
I hope this anecdotal is all right to post here, apologies if not. I was playing [this map](https://osu.ppy.sh/beatmapsets/268431#osu/611157) on `master` and maintaining ~91-92% accuracy for the first minute, but my HP slowly dropped, leading to it bouncing around 20% by 1 minute in. This meant that when I hit two "meh"s within a small timespan I instantly failed the map with 92% accuracy.

I notice similar behavior with other maps too; some maps (due to the spacing of notes or BPM?) tend to have cases where your HP can drop to a very low percentage and then not recover while maintaining a "local" accuracy of >90%. Is this desired behavior?

**Comment by whizvox** [comment]
leaving my own anecdotal case as well

https://youtu.be/oJKFkNtdbNc

way too easy to fail the map towards the end of the chorus, struggle to get above half health the entire time despite maintaining a ~94% accuracy. I managed to lose about a *quarter* of my health in the ~1 second space between the end of the break and the next note. I instantly fail upon missing a note 58 combo later.

using the newest 2020.229.1 release for windows 10

**Comment by bdach** [comment]
Generalising this as drain has now been called both too harsh and too lenient, so clearly the user expectation that drain will be exactly the same as stable (which, to emphasise, *it might not necessarily end up being*).

**Comment by whizvox** [comment]
no, drain just doesn't make sense and is inconsistent when comparing theoretical vs. actual drain.

in my [previous post](https://github.com/ppy/osu/issues/7975#issuecomment-595118086), I demonstrated an instance where drain was way too high with a map with HP6 and OD7. here's an instance where drain is too low in comparison.

https://www.youtube.com/watch?v=NSTHwT5ntAA

notice that the map is HP7 and OD7.5, but even after intentionally not playing for a second or two, the HP bar doesn't even go below the halfway point.

how can both the HP and OD values be higher, but in gameplay, the drain and HP reduction be much, much lower?

**Comment by bdach** [comment]
I'm not sure what "theoretical drain" is supposed to mean but sure. I have a slight feeling the other mechanical changes (like removing sliderend leniency) could have a knock-on effect on how drain feels (since it's based on percentage of HP on a perfect play) but I have no concrete evidence to back that claim up at this point.

**Comment by huupoke12** [comment]
And I don't think there should be passive drain: https://youtu.be/Wyc-vVYsGOo

**Comment by bdach** [comment]
@huupoke12 see discussion at [#7370](https://github.com/ppy/osu/issues/7370#issuecomment-569241282).

**Comment by igontusuwu** [comment]
i feel as if on hp10 in its current state that goods and mehs give too much hp and allow the user to survive hitting a lot of goods and mehs
i think hp drain should be lessened a bit and goods and mehs should have a slight nerf in amount of hp given

**Comment by igontusuwu** [comment]
testing in mania with a hp7 map, poorer judgements give too much hp in the more dense sections to the point where it overrides all the misses you will get and it allows you to survive by getting 55% accuracy which allows mashing for hard passes you shouldn't get

adjusting/accounting for the previous 2 comments i made, in all modes expect taiko:
hp should account for map section density to increase/decrease hp accordingly
hp drain should be nerfed somewhat to prevent draining to 0 in low density sections
the good, ok, and meh judgements should give less hp to prevent poorer accuracy from passing through 

map i used for testing: https://osu.ppy.sh/beatmapsets/1034114#mania/2162156

**Comment by kiwec** [comment]
Reviving the discussion. The current hp drain mechanism makes it impossible to recover from your mistakes on a lot of maps, which means either you get rank S or you die. On the other hand, on other maps, you can stop playing for 30 seconds and not fail - I find it very confusing.

As an example, this map has HP drain 5.8, and gets to death range just by getting 100s : https://www.youtube.com/watch?v=TZM4yxJf0fc
For comparison, here is the same map with the classic hp drain system : https://www.youtube.com/watch?v=KLBuBgpd7TY (apologies for using mcosu, osu!classic crashes at startup since yesterday)

**Comment by Balcke** [comment]
Imma just leave my hp issue here
https://youtu.be/2JLs44a-NQs
5.2 hp drain, 95% accuracy. 2 misses and you're dead.
Same map on stable
https://youtu.be/R8UxJGYz6vY
Sam hp5.2, 90% accuracy. 9 misses and im somewhat doing just fine.

**Comment by messier102** [comment]
I've run into an HP-related issue on a newly ranked map: https://osu.ppy.sh/beatmapsets/1694155#osu/3474143

On lazer it becomes practically unpassable -- I suspect that is due to the lack of geki/katu. I have to play very precisely just to keep my HP from draining, and every miss is very punishing.

https://user-images.githubusercontent.com/79512127/166965243-11a8d7c3-c70b-4185-b4ce-4cdd08006828.mp4

Turning on classic (which I hope sufficiently emulates stable) makes the difficulty much more reasonable, and even allows me to recover from deliberately missing several notes in a row.

https://user-images.githubusercontent.com/79512127/166965472-e2628bdb-da0e-4933-b078-13f4d71aaa77.mp4

While classic mod is a reasonable workaround for older stuff that relies heavily on the HP model as it is in stable, as a player I would expect any map that gets ranked today to be completely playable in nomod. On the other hand I've seen 7*+ maps that I can first try on lazer, while a more skilled player cannot pass them on stable (namely https://osu.ppy.sh/beatmapsets/1392496#osu/2874944)

I don't have a solution to propose, but the current state doesn't seem very sustainable if both stable and lazer are to be maintained going forward, especially once score submission kicks in.

**Comment by jedel1043** [comment]
I'm pretty sure this still needs a bit more work. If you compare https://osu.ppy.sh/beatmapsets/480765#osu/1169864 with https://osu.ppy.sh/beatmapsets/991300#osu/2496646, lazer tends to drain HP in jump maps very heavily, while on stream maps you can even double tap and easily pass a map, and those have the same HP drain!

On stable, notelock probably took care of that by punishing misses within

**Comment by frenzibyte** [comment]
Open a discussion thread please.

**Comment by jedel1043** [comment]
> Open a discussion thread please.

There's already https://github.com/ppy/osu/discussions/17912, I think. I just wanted to bump this since it apparently was already fixed but the problem persists.

**Comment by Kyuunex** [comment]
I found a map that has much worse hp drain in lazer (with and without classic mod) than in stable. https://osu.ppy.sh/beatmapsets/469782#osu/1004556 

im bringing this up as my assumption for the classic mod was it's as close to stable as it gets and was told to leave the link in this thread.

**Comment by smoogipoo** [comment]
I'd love to avoid re-implementing osu!stable's HP calculation given that it _also_ has issues that are worked around by the whole not-being-able-to-die-until-you-miss thing, but it may be the path of least resistance.

Probably need some quick investigation into the issue here, and brainstorming for possible solutions that aren't re-implementing osu!stable first.

**Comment by bdach** [comment]
@smoogipoo https://github.com/ppy/osu/issues/24365 was already on the project. Seems like we should probably keep just one.

**Comment by smoogipoo** [comment]
Ah yep, my bad. Had this one sitting in my inbox for a few months...
