### ISSUE TITLE
Unable to use lazer tournament client due to crash while using OBS / Streamlabs / Discord

### ISSUE THREAD

**Issue by Mashsim** [ppy/osu#7979]
After launching the client (about 5 minutes), my pc somehow explodes and gives a Streamlabs' error, but I think it has something to do with GPU. I say so because everything gets black and my pc blocks, sometime it restarts by itself sometimes I have to do it on my own. I'm wondering how people are able to use it and stream tournaments while using Discord and such.

**Screenshots or videos showing encountered issue: ![aaaaa](https://user-images.githubusercontent.com/56738974/75118286-23361580-5679-11ea-82e4-87a6b24636eb.png)
![aaaaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/56738974/75118332-7d36db00-5679-11ea-89bb-892ff162e6f3.png)
https://clips.twitch.tv/BlazingShyHumanAsianGlow** 

**osu!lazer version: 2020.208.0** 

**Logs:
[performance.log](https://github.com/ppy/osu/files/4242241/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4242242/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4242243/updater.log)
[database.log](https://github.com/ppy/osu/files/4242244/database.log)
[network.log](https://github.com/ppy/osu/files/4242245/network.log)**

**Computer Specifications:
Motherboard: ROG STRIX Z390-F GAMING;
CPU: Intel Core i7 9700K;
GPU: NVIDIA GeForce GTX 1080 (MSI);
Memory: G.Skill Trident 16GB DDR4**

**Comment by bdach** [comment]
Can't ascertain anything by logs alone (probably due to this being an apparent system-wide crash). Please attach Windows Event Viewer info by performing the following steps:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by peppy** [comment]
likely causes: running afterburner, having discord overlay enabled, etc.

this is 100% going to be something your end hooking into the process. need to nail down what that something is.

**Comment by Mashsim** [comment]
Thanks both of you, now everything is working properly. I have to make another post because we're having problems on showing chat and making work the pick phase which has to show the maps' specifics (ar,od, etc.,). I've tried the two ways to fix it such as creating the ipc.txt files and moving all the tournament folder in osu folder in the AppData/Roaming.
