### ISSUE TITLE
Input is only 60hz on iDevices

### ISSUE THREAD

**Issue by KafuChinoDesu** [ppy/osu#8008]
**Describe the bug:** 
Input is only 60hz on iDevices. Output supports 120hz if your device supports 120hz output. (ex. iPad Pro 2nd Gen or later)
**Screenshots or videos showing encountered issue:** 
![9EF49944-4876-4ABB-BC7A-8CAADBD3D7D8](https://user-images.githubusercontent.com/39993457/75354673-b927a580-58f0-11ea-829c-46b21383ab1d.png)

**osu!lazer version:** 
2020.226.0
**Logs:**
Not needed

**Comment by peppy** [comment]
This may be relevant (see touch delivery rate):

![image](https://user-images.githubusercontent.com/191335/75355445-dad55c80-58f1-11ea-964e-8b3c3709cf1a.png)

I'd need to double-check how we are hooking up threading, but can you confirm which device you are seeing this on?

**Comment by KafuChinoDesu** [comment]
iPad Pro 11-inch.

**Comment by Kashouryo** [comment]
On my iPhone XS, I got 240hz input rate displayed in game. But the sample delivery rate of XS is 120hz(same as Chinos iPad pro).

**Comment by swoolcock** [comment]
On iOS, input updates are done using a `CADisplayLink`, set to a `frameInterval` of 1.  `frameInterval` is deprecated in favour of `preferredFramesPerSecond`, but from what I'm reading it might be better for us to switch to using an `NSTimer` as it will be a more reliable update rate.

https://github.com/ppy/osu-framework/blob/master/osu.Framework.iOS/GameAppDelegate.cs#L33

Suggestion is to change the `gameView.Run();` call to `gameView.Run(120);` which will use an `NSTimer` instead.  It might even be worth checking the maximum reporting rate to pass an accurate value here rather than assuming 120hz.  Having said that, running the input thread at 120hz on a 60hz device should not be a problem, it just means that every other input update would have nothing to do.

**Comment by peppy** [comment]
@swoolcock wanna open a framework side issue for this? i'd want to see the documentation that says `NSTimer` is better, because that sounds counter-intuitive for a draw thread.

**Comment by swoolcock** [comment]
Will do so later today.

**Comment by Kashouryo** [comment]
I double-checked my performance data on my iPhone tonight.
I am also having 60fps input rate on my iPhone XS. The 240fps was my update rate and I misread it as the input rate.

I am really sorry for the false information.

**Comment by yansaan** [comment]
why not to android too (like realme x2, Galaxy S20, ROG Phone 2, Razer Phone, and more)

**Comment by bdach** [comment]
@yansaan The input thread is not constrained to 60Hz refresh rate on Android (or, at least on my device it gets up to 1000Hz).
