### ISSUE TITLE
osu!catch red fruits don't work sometimes

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#8016]
**Screenshots or videos showing encountered issue:** 
https://streamable.com/70uzp

**osu!lazer version:** 
commit f1c97451d976c3e1d3fcd4bb9701302b188d6378

**Comment by bdach** [comment]
Mind linking the map for examination?

**Comment by mouzedrift** [comment]
sure https://osu.ppy.sh/beatmapsets/1070009#fruits/2241334

**Comment by TheBicPen** [comment]
The HitObject seems to be getting created with HyperDash being false, but I'm not sure exactly where, because the stack frame above
osu.Game.dll!osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.UpdateAfterChildren() Line 410
is external code. This stack is from when the hyperdash state is being set for the first object, where the issue first occurs on this map.

**Comment by peppy** [comment]
What's the point in the video we should be looking at?

**Comment by TheBicPen** [comment]
0:05 - the first time it happens.
0:17-0:20 has a few nice examples
0:23-0:25 too

**Comment by CelegaS** [comment]
https://osu.ppy.sh/beatmapsets/372337#fruits/815486 there is one part spamming 1/8 hyper dash no one seems to work. https://cdn.discordapp.com/attachments/344495519890014210/682961229232209948/osulazer_2020-02-28_15-40-20_Trim.mp4
