### ISSUE TITLE
Support for storyboard overlay layer

### ISSUE THREAD

**Issue by WhiteRedWolf** [ppy/osu#8017]
**Describe the bug:** 
After Starting a Map, The osu!lazer paused to show the notification bar and here is what came out.
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
![image](https://user-images.githubusercontent.com/33634370/75394809-43700980-58f1-11ea-8b99-b6edfc9530eb.png)

**Logs:**
*please attach logs here, which are located at:*
- `%AppData%/osu/logs` *(on Windows),*
- `~/.local/share/osu/logs` *(on Linux & macOS).*
[network.log](https://github.com/ppy/osu/files/4258518/network.log)
[performance.log](https://github.com/ppy/osu/files/4258519/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4258520/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4258521/updater.log)
[database.log](https://github.com/ppy/osu/files/4258522/database.log)

**Comment by bdach** [comment]
It's a storyboard parsing error, [the decoder doesn't know about the `Overlay` layer yet](https://github.com/ppy/osu/blob/5cdc7d3b184f21a053fcc07f35e05e78e6936587/osu.Game/Beatmaps/Legacy/LegacyStoryLayer.cs#L6-L12). Probably hasn't been implemented yet.

**Comment by Coppertine** [comment]
It's best to implement this layer as there has been ranked maps which utilise this feature and one of them is featured in the Beatmap Spotlights which might be in timeshift. (Currently, people will see an error that it hasn't been parsed)

**Comment by bdach** [comment]
I can't find any info on the wiki about the overlay layer - are there any resources that mention it? Is it in any way more special than a normal storyboard layer?

**Comment by smoogipoo** [comment]
There's nothing super special about this layer, only that it's drawn above the playfield and below the flashlight + hud.

**Comment by Coppertine** [comment]
*it's below the hud but above the key display panel on the right.

**Comment by smoogipoo** [comment]
I'm fairly it should be below the HUD at all times in lazer.

**Comment by bdach** [comment]
> *it's below the hud but above the key display panel on the right.

I'm not sure if that part should be preserved, to be honest. It doesn't make too much sense unless I'm missing something.

**Comment by Coppertine** [comment]
What I've noticed is that overlay objects are rendered between the hitobjects and hud, midway though that is the key display. But in lazer's case, I would say below the HUD

**Comment by bdach** [comment]
I'm a good way through implementing this, but I've hit an unexpected snag due to the way `DimmableStoryboard` works, namely the fact that the drawable storyboard is lazily instantiated based on user preference:

https://github.com/ppy/osu/blob/cf890efa420de62ccad053e62b7caac2407ebfdc/osu.Game/Screens/Play/DimmableStoryboard.cs#L38-L52

so it's not guaranteed to always be there on player load. The immediate thought was of course to notify player about the fact that it was instantiated, but it's not 100% obvious to me yet as to how to do that as player element z-order relies on the element order in `AddRange()`. Going to take a day more to think over how to deal with that if it isn't an issue.
