### ISSUE TITLE
cant sign in

### ISSUE THREAD

**Issue by therealpossum** [ppy/osu#8018]
**Describe the bug:I try to sign in and it says attempting to connect then goes back to the sign in screen and i try it again and it instantly goes back to the sign in screen** 

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:2020.225.0**

**Logs:**
*please attach logs here, which are located at:*
[network.log](https://github.com/ppy/osu/files/4258792/network.log)
[performance.log](https://github.com/ppy/osu/files/4258793/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4258794/runtime.log)
[database.log](https://github.com/ppy/osu/files/4258795/database.log)

**Comment by smoogipoo** [comment]
This is guaranteed to be an issue local to your system. It could be caused by the following:
1. Any antivirus web shields.
2. Any firewall web shields.
3. Any modifications to the `hosts` file.
4. Service packs / OS updates not installed.

You could try replicating and seeing if it works on another PC, or re-installing your PC.

**Comment by therealpossum** [comment]
so what should i do

**Comment by smoogipoo** [comment]
Please re-read my comment.

**Comment by therealpossum** [comment]
> Please re-read my comment.

Sorry I should of been more specific how do I re-install my PC.

**Comment by smoogipoo** [comment]
That is beyond the scope of what we're able to help you with here. This is an error specific to your system caused by one of the things I mentioned. The rest is up to you.
