### ISSUE TITLE
Legacy skins should fallback to default classic skin elements when not available from skin

### ISSUE THREAD

**Issue by Koto1** [ppy/osu#8019]
**Describe the bug:** 
My mix skin is not working well on laser for some reason, I know it used to work just fine around the time skins were implemented to laser and at some point, it broke, all of my other skins work great tho. I tried deleting all skins and importing back, and also importing by throwing the .osk on the laser and it still didn't work
**Screenshots or videos showing encountered issue:**
 
[skin.osk](https://drive.google.com/file/d/15WsHFoBSemZ0z0MkLQa49CrRkai2FbUN/view?usp=sharing)

[the skin on stable](http://prntscr.com/r87qjh)

[the skin on lazer](http://prntscr.com/r87rap)

**osu!lazer version:** 
2020.226.0
**Logs:**
*please attach logs here, which are located at:*
- `%AppData%/osu/logs` *(on Windows),*
- `~/.local/share/osu/logs` *(on Linux & macOS).*
[logs.zip](https://github.com/ppy/osu/files/4258817/logs.zip)

**Comment by smoogipoo** [comment]
Can see what's going on here. This skin is expecting the default skin's `hitcircleoverlay.png` to be used, but it isn't contained within the skin.

**Comment by xTerraUWU** [comment]
Not all elements from osu!stable work on osu!lazer if I remember. Could be hitcircleoverlay.png is not present when on the lazer client, but I could be wrong.

**Comment by enoslayd** [comment]
Just a thought, what if you want a legacy skin with a mix of lazer default skin?

**Comment by peppy** [comment]
You can't with legacy skinning – that's out of scope. That will be possibly with the future skinning system when we make that.

**Comment by cl8n** [comment]
issue's title is a bit misleading--- the problem in OP's screenshots comes from hitcircleoverlay being forced to load from whichever skin has hitcircle, so if there's no hitcircleoverlay there it just won't show anything. correct behavior would have hitcircleoverlay load from a fallback skin

coincidentally the title correctly reports a different bug, that legacy skins are falling back to the "osu!lazer" skin instead of "osu!classic" for missing elements

**Comment by peppy** [comment]
That's actually what the title is saying I think? The fallback to "default classic skin" is exactly what you're implying needs to be done.

**Comment by cl8n** [comment]
the specific problem with hitcircleoverlay won't be fixed by doing that, because the whole `LegacyMainCirclePiece` (includes hitcircle + hitcircleoverlay) depends on the presence of hitcircle only. it's not falling back to *anything* right now, where all the other stuff is falling back to osu!lazer at least

well even if I'm misreading the title I guess my point is there's two different problems at play here

**Comment by peppy** [comment]
The title implies that:

If you have loaded a legacy skin, and that skin is missing an element, that element should be read from the osu legacy (classic) skin. This will indeed solve the problem pointed out in this thread.

If you load a legacy skin and the fallback logic was in place, the hitcircle would be present, because it would be being read from the legacy skin.

**Comment by MLisDreaming** [comment]
Probably not a common case but my skin is made for osu!lazer and this update has caused alot of problems for the skin as it's expecting osu!lazer assets and uses osu!classic assets instead.

**Comment by bdach** [comment]
That was never officially supported and at most only invoking undefined behaviour/an interim state of things, sorry.

**Comment by MLisDreaming** [comment]
That's understandable. I guess I'll have to wait for osu!lazer to get it's own skin format.

**Comment by peppy** [comment]
To keep things clean, I'm tracking the remaining case at https://github.com/ppy/osu/issues/13448. The most common cases of this issue have been resolved via #13264.
