### ISSUE TITLE
Can't complete beatmaps on mobile

### ISSUE THREAD

**Issue by tsunadegodaime** [ppy/osu#8043]
Version: 2020.228.0
https://i.imgur.com/zHcnm2X.jpg

After finishing beatmap there is no score screen, osu just freezes.

**Comment by Luxiono** [comment]
What are your specs?

**Comment by tsunadegodaime** [comment]
> What are your specs?

Honor 9X China, Kirin 810. 4GB RAM.

**Comment by MTGPROD** [comment]
Same for me (Huawei Mate 9) when the beatmap ends, the game freeze definitely. But i have no message that says the game isn't responding. And lag spikes still here.

**Comment by bdach** [comment]
Expanding scope to cover both mobile platforms.

**Comment by ThatsNiceGuy** [comment]
happens on ios, game completely locks up (like with the render freezes) but doesnt crash

**Comment by bdach** [comment]
Root cause is a TPL-induced deadlock when trying to import score at the end of gameplay:

https://github.com/ppy/osu/blob/e85c76b52d2b2969e7e406d1979cf4944be47533/osu.Game/Screens/Play/Player.cs#L611-L612

Draw thread calls `.Wait()` therefore blocking on a monitor, the score import runs fine until the end, but at the end tries to continue execution from previous context which is impossible since the draw thread is still blocked on the monitor.

Both commenting the import or sprinkling `.ConfigureAwait(false)` at `Player` and `ArchiveModelManager` resolve the deadlock but they're both entirely invalid solutions so I won't bother even showing them. Propagating `async` upwards from `scheduleGotoRanking` isn't really viable either since it's called in a synchronous context from `OnExiting`.

If I were to guess what the proper solution is, it's probably finding a better place to import where `async` can be used freely, or failing that, providing a fully synchronous path (much much worse).
