### ISSUE TITLE
URL parsing support

### ISSUE THREAD

**Issue by peppy** [ppy/osu#806]
We need proper support for URL parsing.

We may be able to borrow some code for this from osu-stable, since it was quite recently rewritten and have unit tests.

**Comment by FreezyLemon** [comment]
So... seeing as you warned EVAST9919 for his PR as to "not relicense private code" but also mentioning "borrow"ing code from osu-stable, how much can we copy? The old code worked, no? I mean, all the regexs could probably stay the same, and the functionality would only be marginally different.. this is mostly implementation is it not? Sorry if this sounds passive-aggressive but I'm actually confused at how much rewriting there needs to be done if the old code works.

**Comment by peppy** [comment]
- `LinkFormatter` itself could be reused, but the integration needs to be redone. The `HandleLink` method and other stuff was copy-shitted from a private code base.
- `LinkFormatter` itself could do with some restructuring.
- The tests were left behind, which was the reason I mentioned we could borrow the code (this code has unit tests which cover it).

If you would like to attempt this and use the osu-stable code, please ask me for the code and I will make it publicly available under a usable licence and we can work from there.

**Comment by FreezyLemon** [comment]
Oh, that was a misunderstanding on my end then.. (not worth going into it too much)

Anyways, I would definitely work on this if you relicenced the old code, seems doable.

**Comment by peppy** [comment]
https://gist.github.com/peppy/fa0c51bfc14a7d553f8c75d61d59bbb6

will require modification but should provide a good place to start.

**Comment by FreezyLemon** [comment]
I started on this and got the URL parsing and highlighting working reliably.
Something that's not perfect yet, though, is the "on click" actions:

So far, you can
- Switch channels
- Show the `BeatmapSetOverlay` when clicking on an `/np` message OR `http[s]://osu.ppy.sh/` link to a map
- Send a link to the OS to start a browser or other external program (for unknown or unhandled links)

Anything that opens a new Screen (Editor timestamps, MP links, spectate links) cannot work yet since the ChatOverlay (and the link that's clicked) cannot access the screen or its state in any way.

- [ ] #1662 necessary addition/change for this to be possible.
