### ISSUE TITLE
Add notelock back with adjusted values

### ISSUE THREAD

**Issue by genericthing** [ppy/osu#8099]
the notelock will have 166ms of leniency which is about 1ms less than 2 1/4s or 1 1/2 on 180bpm

this means that up to 166ms after the current time in gameplay will not have notelock

i suggest this because it will prevent cheesing on lower difficulties but it will not be as annoying on streams on higher difficulties as on stable

**Comment by peppy** [comment]
We will definitely be looking to add back some degree of note lock as long as it improves playability.

**Comment by MillhioreF** [comment]
My suggestions for a more playable notelock:
- Notelock from clicking early should remain as it is in stable.
- If a note is clicked out of order and at the wrong time, it should shake, as in stable.
- If a note is clicked out of order but at the right time (happens a lot in spaced streams) then it should be counted as a normal click, rather than shaking, and cause all previous but still active notes to instantly miss. Exact range for this is debatable but maybe halfway through the 100 zone in either direction.

**Comment by Karoo13** [comment]
My opinion on how notelock should work is this:
At time t, you may click a clickable object with a start time of t1 when:
1. no clickable object with a start time after t1 has been clicked
2. all clickable objects with a start time after t and before t1 have been clicked

And you may earn judgement on held objects:
spinner: any time
reverse, tick, tail: no clickable object with a start time after [slider end time + 1ms] has been clicked

**Comment by peppy** [comment]
@Karoo13 what you just said is *more* harsh than stable, which is not a direction we are looking to go.

Please avoid open-ended discussion in this thread. If you want to discuss game mechanics please do so on [the forums](https://osu.ppy.sh/community/forums/13).

**Comment by Karoo13** [comment]
You clearly failed to read criterion 2 in my post, it is less strict than stable, less strict than what millhi just suggested (for stream bpm below 380 at od10, 280 at od8), and disallows out-of-order judgement on non-2b patterns.

**Comment by peppy** [comment]
Your point 2 is how stable works. Point 1 is making it more strict.

Going to lock discussion here until we have an initial implementation present in the game.
