### ISSUE TITLE
Editor doesn't render follow points after scrolling back in timeline

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8112]
**Describe the bug:** 
Editor only renders follow points once. After scrolling back in timeline, all follow points that had been rendered at some point stop getting rendered.

**Screenshots or videos showing encountered issue:**
![osu_2020-03-03_21-52-28](https://user-images.githubusercontent.com/11320483/75813876-730f8d80-5d99-11ea-9543-027df6e504e8.png)

**osu!lazer version:** 
2020.229.1

**Comment by LittleEndu** [comment]
Expected view
![osu_2020-03-03_21-55-12](https://user-images.githubusercontent.com/11320483/75814006-ad792a80-5d99-11ea-8daf-a31b16f6adb6.png)

**Comment by peppy** [comment]
Regression from https://github.com/ppy/osu/pull/7968 (need to retain old transforms).

**Comment by smoogipoo** [comment]
Not sure why that would be the case, since `RemoveCompletedTransforms => false` is set on the `FollowPointRenderer`, which is recursive;

https://github.com/ppy/osu/blob/master/osu.Game.Rulesets.Osu/Objects/Drawables/Connections/FollowPointRenderer.cs#L24

It's more likely to do with animations, since I cannot replicate this with the default skin? @LittleEndu can you provide the follow points for the skin?

**Comment by LittleEndu** [comment]
My skin files are available at https://github.com/LittleEndu/osuSkin/tree/master/u200B

I'll check if they are the latest when I get back at PC but that won't be for 10 hours.

**Comment by smoogipoo** [comment]
Yep, from the looks of that it will be related to animations.
