### ISSUE TITLE
Show mod settings in scores page

### ISSUE THREAD

**Issue by cupppu** [ppy/osu#8159]
**Describe the new feature:** 
Being able to see what settings for the difficulty adjust mod in past scores

**Proposal designs of the feature:** 
Tool tip showing what difficulty settings for the mod when hovering over the mod icon in scores page, currently it only says "difficulty adjust"

**Comment by bdach** [comment]
Should probably go for all customisable mods if this happens.

**Comment by peppy** [comment]
Rather than being on a "scores" page, showing on hovering the mod is probably sufficient, as a custom tooltip

**Comment by cupppu** [comment]
Yes this is actually what I was proposing, sorry if I worded it weird

**Comment by tybug** [comment]
Should this label be of the form `Difficulty adjust (CS 9, HP 5, OD 6, AR 8)` or `Difficulty Adjust (Circle Size 9, HP Drain 5, Accuracy 6, Approach Rate 8)`? 

The latter would be cleaner to implement since we could (I think) iterate over all the `SettingSource` attributes of each `Mod` with `mod.GetOrderedSettingsSourceProperties`, which only exposes the full name of the attribute, not the two letter acronym. Maybe I'm missing an easier way though.

**Comment by cupppu** [comment]
would the latter implementation take up too much space laterally? Or will you stack each attribute vertically? Personally I am fine with either

**Comment by tybug** [comment]
Long horizontal tooltips aren't great, but multiline tooltips seem worse.
