### ISSUE TITLE
Crash when changing filter query during transition to player loader

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#8168]
If you press Enter and any button on the keyboard at the same time (or with very little delay), then there are 3 options:
1. Everything will be fine.
2. The application will give an error, but will continue to work.
3. The application crashes (as I understand it, this happens if you click something immediately after clicking on Enter, and not before that)

https://youtu.be/8qSJ2gU9yiM
**osu!lazer version:** 
2020.306.0
**Logs:**
Logs are available only from complete crash.
[performance.log](https://github.com/ppy/osu/files/4302609/performance.log)
[network.log](https://github.com/ppy/osu/files/4302610/network.log)
[runtime.log](https://github.com/ppy/osu/files/4302611/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4302612/updater.log)

Logs of the error that is shown in the lazer (second option). Apparently, this error is also shown here.
[runtime.log](https://github.com/ppy/osu/files/4302618/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4302619/updater.log)
[network.log](https://github.com/ppy/osu/files/4302620/network.log)
[performance.log](https://github.com/ppy/osu/files/4302621/performance.log)

**Comment by bdach** [comment]
If I were to hazard a guess at the case it's probably the filter change debounce racing with `PlayerLoader` taking out a lease on `WorkingBeatmap`:

* Before transition, filter query is scheduled, triggering a debounce schedule in the future
* `PlayerLoader` takes lease, making beatmap bindable disabled
* Scheduled delegate tries to cause change of current beatmap but fails since bindable is now disabled since lease was taken

**Comment by peppy** [comment]
This scenario should already be handled by the `FinaliseSelection()` function in `SongSelect`, which ensures any pending schedule is run before the game loads `PlayerLoader`..
