### ISSUE TITLE
osu!catch playfield is wider than in stable

### ISSUE THREAD

**Issue by CelegaS** [ppy/osu#8221]
**Describe the bug:** osu!catch playfield is widher than in stable
I don't know if it's intended.

**Screenshots or videos showing encountered issue:** 
![comp](https://user-images.githubusercontent.com/11272924/76415412-727a8680-6399-11ea-926f-826055959377.png)

bottom is osu!lazer

**osu!lazer version:** 
2020.311.0

**Comment by peppy** [comment]
I believe this is intentional to make better use of the screen, but should be checked at some point in more detail.

**Comment by smoogipoo** [comment]
Putting this in the milestone since I have multiple people explaining that catch feels wrong to play with the current aspect ratio. Similar to moving between osu!stable and osu!lazer in osu!, I think this is probably something we should look into/adjust if it's hold players off from giving lazer a decent shot.
