### ISSUE TITLE
Skin Importing on Linux

### ISSUE THREAD

**Issue by GDJason12** [ppy/osu#8234]
Skins are not detected in osu!lazer

Version: 2020.311.0'

Reproduce:
1. download osu appimage on linux
2. download some skins
3. try to import and lazer wont detect the skins

**Comment by huupoke12** [comment]
How you are importing?

**Comment by GDJason12** [comment]
> How are you importing skins?
Um, there's something called .osk and importing system on lazer

**Comment by GSculerlor** [comment]
If you're talking about "Import skin from stable", then it actually importing skins that already on stable installation. If you want to add your skin, try drag and drop your .osk file to lazer

**Comment by bdach** [comment]
You can import skins by either drag & drop or by supplying the path to the `.osk` in question as a command-line parameter to the executable.

Closing for now until more details are provided as to what exactly isn't working.

**Comment by hyukage** [comment]
@bdach i downloaded osu lazer through linux on chromebook and i have a skin in my files, but i cant seem to get it on osu. I also dont exactly have an osu file due to it being through linux so i cant exactly just do as you say. i technically have an osu file but im using menulibre to open it please help
