### ISSUE TITLE
Result panel doesn't consider scaling of UI

### ISSUE THREAD

**Issue by tsunadegodaime** [ppy/osu#8321]
**Describe the bug:** 
Result just doesn't fit into the screen, when scaling is used.
**Screenshots or videos showing encountered issue:** 
https://i.imgur.com/cI50E9F.png
**osu!lazer version:** 
2020.317.0
**Logs:**
[logs.zip](https://github.com/ppy/osu/files/4344525/logs.zip)

**Comment by Joehuu** [comment]
Will fix. It can scroll, but the anchor/origin is off right now.

**Comment by tsunadegodaime** [comment]
Also there is msitake - "Mapped by power007" this is not mine map, it should say something like "Played by power007"

**Comment by cupppu** [comment]
> Also there is msitake - "Mapped by power007" this is not my beatmap, it should say something like "Played by power007"

This is tracked at #8317

**Comment by Joehuu** [comment]
Maybe I can't fix (without a padding hack). The score panel itself needs a refactor to fix this dimension problem.

![osu_2020-03-17_12-12-39](https://user-images.githubusercontent.com/35318437/76892894-9e3db680-6848-11ea-912c-ee612a362643.png)

It's caused by a hard coded size and move to y transforms.

https://github.com/ppy/osu/blob/156a3db57d7841c7eb26a2d2ae76ca0a754b281a/osu.Game/Screens/Ranking/ScorePanel.cs#L186

https://github.com/ppy/osu/blob/156a3db57d7841c7eb26a2d2ae76ca0a754b281a/osu.Game/Screens/Ranking/ScorePanel.cs#L208
