### ISSUE TITLE
Dropping sliderends breaks combo

### ISSUE THREAD

**Issue by STCapricorn** [ppy/osu#8371]
it was fine the release before (2020.317.0). must have something to do with recent slider judgement changes, and i don't think it's intended.

**osu!lazer version:** 2020.320.1

**Comment by peppy** [comment]
This is an intended change (part of the slider judgement changes). Discussion is welcome, as mentioned in the changelog.

**Comment by recapitalverb** [comment]
This makes maps like https://osu.ppy.sh/beatmapsets/756794#osu/1605148 no longer passable, it seems.

**Comment by peppy** [comment]
Such maps are not a number one priority for score considerations for now (we can make exceptions for them at a later point in time). Using no fail would be a good solution for now.

**Comment by ScubDomino** [comment]
What about this? https://osu.ppy.sh/beatmapsets/484689 or this? https://osu.ppy.sh/beatmapsets/437683 or even this? https://osu.ppy.sh/beatmapsets/517474

With this addition, especially when considering that sliderends are calculated 36 miliseconds before the actual sliderend, it makes for highly unnecessary luck-based difficulty curves to where you should move when playing a slider. This is crucial and is something to consider especially within the meta of fast-speed sliders and complex shapes that abuse this specific idea in their maps.

**Comment by osuShiro** [comment]
I don't think this is a good change.

First of all, this is a complete redirection of years of gameplay that affected mapping and playing techniques. Slider leniency is a huge thing and allows for interesting patterns and techniques (for example, 1/4 sliderjumps).

Second, if dropping a sliderend breaks combo, then you're giving a sliderend, which is a passive object, the same weight as all other active objects (hitcircles and sliderheads), while it doesn't have the same impact in terms of gameplay. I don't disagree with making the sliderhead net 100 or 50 depending on timing, because that's an active object, but I don't think having accuracy matter on sliderend is a good idea either. I think the current compromise of having a dropped sliderend reduce the score is healthy and fitting, but having it drop combo is too harsh for what sliderends are.

One thing you could do is drop the slider's timing judgement by one step if the sliderend is dropped. If the sliderhead is a 300, it becomes 100, if it's 100, it becomes 50, and if it's 50, then it becomes a miss. This gives a lot more weight to slider heads, which I think isn't too bad an idea given they're held objects, without removing the existing mechanics and techniques.

**Comment by peppy** [comment]
There's no accuracy involved here. The change is that the slider needs to be *tracking* when it end.

**Comment by ScubDomino** [comment]
I think you forgot to reply to the first point of his argument, which I think is the bigger issue here...

**Comment by peppy** [comment]
I am not forgetting it. I am addressing a piece of his argument which is not really correct.

Of course we are aware of playability of old beatmaps and it is something we will factor in going forward (just like slider head circle accuracy).

**Comment by Apo11oxd** [comment]
That would become a very simple case of me not playing "new" maps which has this mechanic, and I don't think you'd have to go very far to figure out that that would be a shared sentiment between many players.

**Comment by peppy** [comment]
Thank you for your opinion! We aim to be changing things up meta-wise going forward and I can understand if you are unable to keep up with forward changes, considering how stale osu! gameplay has become over the years. There will always be the ability to play old maps in some form.

**Comment by ScubDomino** [comment]
I think you're not realizing that by applying these changes, osu! gameplay will become even more stale due to:

1. rhythm being toned down a lot due to unfairness in accuracy/timing, which in turn also promotes safer, more generic ideas (1/2 rhythms with no variation to keep up with syncopation etc.) that is the norm within more generic maps like anime/DnB maps. (pairing with the sliderhead accuracy issue but that's not the point of discussion here)

2. Because of this change, mappers are essentially forced to use simpler shapes so players can keep up with gameplay. This is also very common within the same generic maps stated above.

These changes aren't making gameplay more challenging, but more restricting, especially to mappers.

Charles445 proposed a brilliant solution that can also be applied in this case, which is **making both of these issues a gameplay mod, and not the norm.** [https://www.youtube.com/watch?v=T-1SIUDm0S4]

**Comment by osuShiro** [comment]
> There's no accuracy involved here. The change is that the slider needs to be _tracking_ when it ends. Just like it needs to be tracking at the start and at each tick.

Sliderticks have more weight than sliderends. They have positional significance (they are the things that guarantee that a sliderpath is accurately followed), which makes them active objects when it comes to aiming. Sliderheads are active both in aiming and clicking, but sliderends are passive in both. You don't need to accurately aim a sliderend like a sliderbody or a circle, and you don't need to release the key accurately either thanks to slider leniency. Breaking combo for misaiming an absolutely passive objects is too big a punishment for the impact said object has on gameplay.

I'm not saying there should be no punishment for completely misaiming a sliderend - there currently is one and I think it's handled perfectly. I'm saying that changing the punishment to a full combobreak is too harsh.

**Comment by peppy** [comment]
Thanks but I think you are misunderstanding intention here. Changes in lazer are not considering "mapper flexibility" yet because there are many more changes coming to gameplay which will *also* change mapping.

Please wait to see what the future holds!

**Comment by peppy** [comment]
There seems to be some misunderstanding here. Lazer is a testbed project and we will continue to iterate testing new features and breaking existing ones. This does not mean changes will stick. Please stop spamming my socials / email just because of a feature which exists or has changes on lazer.

Please do not tell me what I can or cannot change in lazer because "this is a community game and you have no right". We will continue to strive to make osu! more enjoyable to all users and rest assured, we hear your voices and will not make any breaking changes to **stable** without proper discussion.

If you don't like what you see on lazer, please **do not install it**. Give us some breathing room. Thank you!
