### ISSUE TITLE
Interface bug after exiting the map

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#8381]
This bug occurs between the moments when the last note is pressed, but the results screen has not yet appeared. If at this moment you exit the map, then the interface will catch a serious visual glitch, which is not fixed by anything (only complete exit from the application).

You can repeat as many times as you like

https://www.youtube.com/watch?v=erCzCjhRCQk
osu!lazer version:
2020.320.1
Logs:
[performance.log](https://github.com/ppy/osu/files/4359602/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4359603/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4359604/updater.log)
[database.log](https://github.com/ppy/osu/files/4359605/database.log)

**Comment by cupppu** [comment]
I got a similar issue, but mine was worse in that, when I exit the replay, the replay started rewinding while I was in song select screen and then started playing *in song select screen*

Not sure if I should put it here as well
![osu_2020-03-20_16-54-21](https://user-images.githubusercontent.com/7279624/77187233-0cde7680-6acc-11ea-9dc4-c8f520519fc5.png)
![osu_2020-03-20_16-53-50](https://user-images.githubusercontent.com/7279624/77187248-123bc100-6acc-11ea-9232-c2ef65345f76.png)
![osu_2020-03-20_16-51-53](https://user-images.githubusercontent.com/7279624/77187251-14058480-6acc-11ea-9315-f9aa67497b5b.png)
![osu_2020-03-20_16-51-48](https://user-images.githubusercontent.com/7279624/77187257-15cf4800-6acc-11ea-9cf0-11f717e34513.png)

**Comment by TheWildTree** [comment]
Just a heads up, same thing happened in the OP's video @ 0:28.

**Comment by cupppu** [comment]
yes sorry I haven't watched it through

**Comment by TheWildTree** [comment]
The problem lies here:
https://github.com/ppy/osu/blob/29775ae27e7bc71eb5540e4c778f728254163f16/osu.Game/Screens/Play/Player.cs#L630-L641

The push in `else` isn't guarded properly like the one above is, resulting in an exception and the `Player` screen being stuck in a very weird state. An unfortunate oversight from the PR which added the guarding check above.

Adding a `IsCurrentScreen()` check there *does* seem to prevent the weirdness, **but** creates another - if you attempt to exit before the results screen is pushed, `Player` gets half-stuck, requiring user to press `esc` once again to exit. You can also move around the replay, but it's permanently paused. See here: https://streamable.com/4o4nl.

**Comment by mcendu** [comment]
This looks like a framework-side problem.

https://github.com/ppy/osu-framework/blob/20cf599582d5ec2e9cd1bfe7231e8352ba7efe0c/osu.Framework/Screens/ScreenStack.cs#L254-L270

Before the exit event fires, the screen is popped, and it is pushed back when the exit handler decides not to exit. Attempting to push a screen in the exit event therefore fails.

**Comment by peppy** [comment]
yeah, about what i expected. while that should also be fixed, a local solution may be possibly by just scheduling the push in the blocking exit call.

**Comment by mcendu** [comment]
Attempted to reproduce this bug and succeeded.

Version: 2020.325.0

**Comment by peppy** [comment]
We forgot a framework bump again. Should be fixed next release.
