### ISSUE TITLE
Crash when save beatmap on the editor android

### ISSUE THREAD

**Issue by MTGPROD** [ppy/osu#8608]
**Describe the crash:** 

When i save the map the game systematically crash.

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 

2022.404.0

**Logs:**
 Android

**Computer Specifications:** 

Huawei Mate 9

CPU: Kirin 960 (8 core, 2,4 Ghz)
RAM: 4 GB

**Comment by bdach** [comment]
File storage is [not implemented yet](https://github.com/ppy/osu-framework/blob/90c30724a9d3c47ff5ed4d471167a6359e94635b/osu.Framework.Android/AndroidStorage.cs#L22-L26) on android, and even if it were it would probably crash [due to the opengl context loss issue](https://github.com/ppy/osu/issues/6593#issuecomment-546041485) that will not be addressed anytime soon. Closing for now.

**Comment by MTGPROD** [comment]
Also when I go to the timing section, the game crash. This is due to "the opengl context loss issue" ? @bdach

**Comment by bdach** [comment]
No, that should not be related.

**Comment by MTGPROD** [comment]
So, can I open an issue to report this or it's useless ? @bdach

**Comment by bdach** [comment]
You could, so long as you provide enough details (especially logs from `Android/Data/sh.ppy.osulazer/logs`). I wouldn't expect a swift resolution of the issue, however, especially if it's linked to memory constraints (which it might well be).

**Comment by MTGPROD** [comment]
There is nothing in `Android/Data/sh.ppy.osulazer/files/logs` @bdach

**Comment by bdach** [comment]
If the game runs then I sincerely doubt that. Check both storages (internal and SD card) if you use both.

**Comment by MTGPROD** [comment]
Maybe 
![Screenshot_20200410_153509_com google android packageinstaller](https://user-images.githubusercontent.com/40500781/78996906-dd101500-7b45-11ea-8b17-02ec45723464.jpg)
