### ISSUE TITLE
Performance problems with multithreaded mode

### ISSUE THREAD

**Issue by MTGPROD** [ppy/osu#8631]
**Describe the bug:** 

I use multithreaded mode since this is possible. At the beginning I though that was better because i'm accurate but the game loss fdp + has micro lag spikes every seconds (approximately) and with singlethreaded mode, I have 60fps all the time but less accurate. So i have question, this is possible to remove the 60fps limit on android ? 

**Screenshots or videos showing encountered issue:** 

Nope. 

**osu!lazer version:** 

2020.404.0

**Logs:**
 Android

**Comment by MTGPROD** [comment]
?

**Comment by peppy** [comment]
There's a reason osu! runs single-threaded on mobile platforms: They have few cores and are not meant to be used in the way osu! does.

There is very little chance any mobile platform will run better with multi-threaded execution at any point in time – single-threaded mode was introduced to *improve* performance on mobile.

The 60fps "limit" is your device enforcing vsync. This is intentional.
