### ISSUE TITLE
Allow easier song browsing by expanding difficulties in the opposite direction of where you click relative to the currently selected song

### ISSUE THREAD

**Issue by Maoman1** [ppy/osu#8634]
In osu stable I can just hold my cursor in the same spot above or below the current song and click to quickly browse through my songs, like so https://i.imgur.com/Nxp6WuN.mp4

In osu lazer, the various difficulties will unpredictably expand out either up or down so whether I am trying to scroll down by clicking the next song or trying to scroll up by clicking the previous song, I have to keep moving around and clicking in different places, sometimes even needing to scroll to get past a song with many beatmaps, like so https://i.imgur.com/aAqGmDM.mp4

My suggestion is to alter the way songs expand so it responds intelligently to where you click:

- If you click the song directly below the one currently selected, the difficulties expand upward like "Cold as Ice" did
- If you click the song directly above the one currently selected, the difficulties expand downward like "Last Goodbye" did
- If you click a song anywhere else in the list, it expands however it currently does (I think it centers on the last played map?)

Alternatively, ignore the third statement and expand upward if the song is _any_ distance below the current song, and expand downward if it's anywhere above, though this would mean entirely throwing out the current implementation of expanding which might not be desirable.

**Comment by bdach** [comment]
You can use left/right keyboard arrow keys to get the scrolling behaviour you want.

**Comment by LittleEndu** [comment]
There's room in the left to add on screen buttons for all the navigation options the arrow keys provide.

**Comment by LittleEndu** [comment]
As for what the issue suggests, that's not going to happen. There's no "expanding up" nor "expanding down", current design expands out from where the first difficulty would be placed. It looks like things are scrolling in a direction because the entire carousel is scrolling to the selected difficulty. If that difficulty is last one, carousel has to scroll down meaning all the difficulties move upwards. Vice-versa for first difficulty.

**Comment by TheWildTree** [comment]
I mean, this issue is essentially caused by the lack of single-difficulty display in lazer. It currently only displays whole beatmapsets, because sorting / grouping functions are yet to be implemented. Actually, if you switch stable to grouping by the beatmapset, you'll end up with a very similar situation to the current lazer one.

I'd imagine this issue will be gone when proper (un)grouping is implemented in the song select to allow displaying individual difficulties on their own.

**Comment by bdach** [comment]
@TheWildTree See #2547 for relevant discussion on single-difficulty display.

(FWIW, sorting *is* implemented, but only partially - as it doesn't really make sense for beatmap sets as is the case right now because it doesn't make sense to compare sets with their spreads to other sets with different spreads.)

**Comment by peppy** [comment]
The only reason that's working in stable is due to there being no grouping. This isn't a regression in lazer and but rather a new UX consideration/proposal.
