### ISSUE TITLE
Hit sounds have incorrect timing relative to audio offset

### ISSUE THREAD

**Issue by Maoman1** [ppy/osu#8775]
> [hitsounds cannot and will not adjust with audio offset. they are triggered by your input.](https://github.com/ppy/osu/issues/8774#issuecomment-614974768) -peppy

See videos for proof. Effects like this are greatly exaggerated due to my sound card requiring a large offset of -155ms.

**Describe the bug:** 
Hit sounds either do not adjust with the audio offset when they should, or they _are_ adjusting when they should not. 
It looks to me like they trigger at the user's click but do not sound until click + offset
Note: I've actually _always_ had this issue even back in osu!stable and have simply been playing with effects volume at 0 this whole time. Just figured I'd mention it now since it's still an issue in lazer.

**Screenshots or videos showing encountered issue:** 
[Me with offset](https://drive.google.com/open?id=1nAVgsh7qGPpkrxy90y5qyfujol04wDzi) You can clearly hear I am clicking my mechanical keyboard in time with the music while the hit sounds are obviously out of sync (probably by 155ms...)
[Me without offset](https://drive.google.com/open?id=1C9Eze6iCDpI8s4ejJXc7yXPFzv3BuCv-) Here I am still clicking in time with the music (though I'm thrown off a bit by the graphics). The few times I don't completely miss a note you can hear the hit sounds are perfectly synced with my own clicks.
[Autoplay with offset](https://drive.google.com/open?id=1_2hfMHhWOABzAbPb-H4Wv0t9HelAhHPU) Here you can see that the visuals (the circles and also the display in the bottom right) are in perfect sync with the music but the hit sounds are just as far off as the first video.
[Autoplay without offset](https://drive.google.com/open?id=198gdaQi40qhZfJ3DzHG-DGeh0Pivz_6R) Now the hit sounds are in perfect sync with the music but the timing of the visuals are off (a bit hard to tell in the video, it's more obvious IRL)

**osu!lazer version:** 
2020.413.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/4490141/database.log)
[network.log](https://github.com/ppy/osu/files/4490142/network.log)
[performance.log](https://github.com/ppy/osu/files/4490143/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4490144/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4490145/updater.log)

**Comment by peppy** [comment]
think about it. there's no solution to this unless you decouple hitsounds from input.

you are using the universal offset to account for *input* latency, not playback latency. that is not its purpose.

**Comment by Maoman1** [comment]
Gee, thanks.

**Comment by peppy** [comment]
Unfortunately it is impossible (due to the way time works) to preempt user input and play sounds at the correct point in time. What I am trying to explain is that the only solution for your input latency would be to automatically play hitsounds back at their correct times, regardless of your input. This isn't something we plan on doing in osu! since osu! is heavily about hitsounds.

The solution others use is to disable hitsounds or fix the audio latency issue by switching sound card or output devices.

**Comment by Maoman1** [comment]
Why then can you accurately display when a circle has been clicked and show a score icon at the correct point in time? Are you telling me it is impossible to also play a sound effect at that same point in time? Is the underlying timing of playing a sound when input is received somehow fundamentally different from the timing of updating a visual with that same input?

**Comment by peppy** [comment]
It's completely possible.

Your issue is that your audio pathway has much higher latency than your visual pathway. As you mention above, you're requiring a 150ms offset, which generally means post-processing effects, bad audio drivers, or bluetooth / wireless output devices are adding an insane amount of latency. Meanwhile, your display is pushing through at 5-30ms latency, which is generally within human threshold of considering it "instant".

**Comment by Maoman1** [comment]
And I don't suppose support for ASIO (or similar) as a backup alternative is happening any time soon? I know it has its own slew of problems but it'd be nice if we could at least had the option to try it, even if it did only work for a small percentage of people with this sort of latency issue.

**Comment by peppy** [comment]
ASIO isn't going to help with 150ms latency. There is something else at play there. ASIO will help take 30-40ms down to 10-20ms on supported devices and we do plan on supporting it at some point.

**Comment by ZealyMax** [comment]
It is in fact a problem we can't really fix when playing the game cause hitsounds are made to be played when clicked and the default bluetooth delay will appear just because of that event so you can't really sync the click and the sound.

Nevertheless, I think it is possible to fix this hitsound delay in the editor by playing hitsounds according to the universal offset setting just like you're doing right now with the main audio. As a mapper, it would be a good improvement in my opinion.

**Comment by bdach** [comment]
> It is in fact a problem we can't really fix when playing the game cause hitsounds are made to be played when clicked and the default bluetooth delay will appear just because of that event so you can't really sync the click and the sound.

Well, it isn't fixable, no, because at that point to play the sound at the correct time [would require time travel](https://github.com/ppy/osu/issues/9811#issuecomment-671168153). And honestly playing a rhythm game through bluetooth is... suboptimal, let's just say?

Applying universal offset to editor sounds maybe workable, but the lack of frame stability might turn out to be a problem. It is a separate issue anyhow.

**Comment by ZealyMax** [comment]
> Applying universal offset to editor sounds maybe workable, but the lack of frame stability might turn out to be a problem.

So do you think it might be something that could be done ?

**Comment by peppy** [comment]
I've [opened an issue](https://github.com/ppy/osu/issues/11400) tracking the fallacies of the editor.
