### ISSUE TITLE
A threat in osu?

### ISSUE THREAD

**Issue by iwaQwQ** [ppy/osu#8866]
**Describe the bug:** 
Happens when I unzip the `osu.app.zip` file
It makes the .app damaged
Is that normal?

**Screenshots or videos showing encountered issue:** 
![Screen Shot 2020-04-25 at 23 32 39](https://user-images.githubusercontent.com/19956672/80291346-0edfc900-874d-11ea-8979-a878e415801d.png)

**osu!lazer version:** 
2020.421.0
macOS 10.15.4

**Comment by LittleEndu** [comment]
VirusTotal of said file has 0 detections: https://www.virustotal.com/gui/file/b96e3597c9adcf0774ed2944c8730c9bc999210e8b7f58ad767d0666facc26a5/detection

Can you make sure your anti-virus is up-to-date?

**Comment by iwaQwQ** [comment]
My anti-virus is up to date, I've retried by downloading the file again and I no longer have this pop-up
Strange :/
Anyway, sorry to have bothered you!

**Comment by bdach** [comment]
We can assure you it is nobody's goal here to ship malware, and the build server is secured, so the risk of it being compromised is very low. This is a false-positive from the AV software.

If this happens again, please submit the affected file(s) to the anti-virus developers so that they can analyse it and fix whatever checks or heuristics trigger this false-positive.
