### ISSUE TITLE
osu!taiko miss explosions don't display

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#8891]
**Describe the bug:** for some reason, one of my skin (taiko only) doesnt display its miss hitburst but displays other hitbursts. other skin (includes lazer default and classic) doesnt have the problem

**Screenshots or videos showing encountered issue:** 
https://drive.google.com/open?id=10adPg55b-SvEFRuoxAW2z_V_O6wnnXdp

**osu!lazer version:** master with commit b83a41e

**Logs:**
not needed?

**Skins:**
miss displays
[Kitkat - Copy.zip](https://github.com/ppy/osu/files/4547367/Kitkat.-.Copy.zip)

miss not displays
[taiko.zip](https://github.com/ppy/osu/files/4547345/taiko.zip)

**Comment by mouzedrift** [comment]
Everything is working as expected. Your provided skin has transparent files.
![explorer_8HJsIxwQsE](https://user-images.githubusercontent.com/43358824/80517462-6799a680-8985-11ea-8dcf-f62b710df0df.png)

**Comment by bdach** [comment]
Self-assigned since I thought it'd be a simple fix, but unassigning again as it's a little bit more involved to get full parity with stable here and I don't want to interfere too much as some of the changes outlined below might be coming due to taiko skinning being a current work-in-progress. In order:

* The default skin is actually *not* fine as `taiko-hit0` isn't displayed on it either. This is the simple part of the fix, as `TaikoPlayfield` does not actually _add_ explosions for misses to the hierarchy:
  
  https://github.com/ppy/osu/blob/d997b4d20ba13fac86aa4399f56d32ba09b982e3/osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs#L199-L205
* In addition to that, there are a few nits that prevent having full visual parity with stable that need some more handling, such as:
  * the hit explosion container being additively blended (should be opaque for legacy skins):
    
    https://github.com/ppy/osu/blob/d997b4d20ba13fac86aa4399f56d32ba09b982e3/osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs#L68-L72

  * stable seems to apply a random rotation to the explosion with the centre of origin of rotation applied in the centre of the hit target area, which lazer currently does not do,
  * and finally due to this particular skin's `taiko-hit0` being asymmetrical and protruding out of the hit target area I'm not convinced that its placement is completely correct. Probably best confirmed by comparing with stable source. On a rough comparison it seems too small:
    
    ![image](https://user-images.githubusercontent.com/20418176/80522916-9451bc00-898d-11ea-9f62-fbaf2b9214c6.png)
