### ISSUE TITLE
osu catch play doesnt display results

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#8952]
**Describe the bug:** when i tried to play osu catch, the play doesnt end though the song is already finished. can retry though but cant exit, tried to go to home using toolbar but cannot. (as the time of submitting this, the results screen still doesnt appear (8:42 recorded 8:52 submitted))

**Screenshots or videos showing encountered issue:** https://drive.google.com/open?id=1QxkdsUEWRHWrfMdwh4K9pNxSKRRsq0fd

**osu!lazer version:** commit c813416

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/4586790/logs.zip)

**Comment by bdach** [comment]
This is a result of changes to temporary changes to hit results in the diffcalc PR (#8934). `{Large,Small}Tick{Hit,Miss}`es aren't allowed as hit results in catch, therefore not showing up in the `Statistics` dictionary, therefore crashing when diffcalc attempts to access count of 100s and fails due to a missing key in `Statistics`.

I started on what I thought would be a "proper" fix for this, but it's not as easy - I got [this far](https://github.com/ppy/osu/compare/master...bdach:catch-crash-result-screen?expand=1). The [first commit](https://github.com/ppy/osu/commit/a4f7146a1b40549ec93716c71ea53dbaaf6cb27a) resolves the crash but still doesn't change the fact that no catch hit object actually *uses* those hit results (therefore I assuming making the diffcalc algorithm work incorrectly by treating everything as fruits).

The [second](https://github.com/ppy/osu/commit/a038c0602cbdb8648922a41ded0ad784479611b3) attempts to use them and the third is cosmetics for enum name ugliness, papering over the fact that after these changes the counts also start up showing at the results screen:

![osu_2020-05-06_19-28-42](https://user-images.githubusercontent.com/20418176/81209773-3e09fc00-8fd1-11ea-83db-7ca12bad2cb8.jpg)

Worse yet, the foibles of encoding/decoding legacy scores makes it so replays are displayed horribly wrong:

![osu_2020-05-06_19-31-53](https://user-images.githubusercontent.com/20418176/81209825-4a8e5480-8fd1-11ea-94b8-bfd1ac4e3843.jpg)

Due to the above I'm not PRing what I made just yet, but if it's deemed acceptable for now to get catch working I can submit it tomorrow.

**Comment by smoogipoo** [comment]
The primary fix is to make diffcalc not crash when retrieving unpopulated statistics (or `ScoreInfo`, which is likely where the crash is occurring).

Changes to make catch support these hitresults can happen at any point after that.
