### ISSUE TITLE
"Failed to process line" error when clicking on a specific beatmap

### ISSUE THREAD

**Issue by aplefull** [ppy/osu#8956]
"Failed to process line, value is too low" logs appear when clicking on 2017 aspire map:
https://osu.ppy.sh/beatmapsets/594828#osu/1258033

![image](https://user-images.githubusercontent.com/10453915/81224743-dbc0f380-8ff0-11ea-8eab-459d9e7dd179.png)

Version: 2020.429.0

Runtime log:
[runtime.log](https://github.com/ppy/osu/files/4589341/runtime.log)

**Comment by bdach** [comment]
Aspire maps exploit some stable behaviours that aren't exactly well-defined, and lazer's parser at this stage raises errors instead of trying to replicate those behaviours. We are however tracking such cases over at #750 and when the time is right, we'll get back to addressing them.

Closing as duplicate for now.
