### ISSUE TITLE
taiko scroller is bigger than the taiko fields

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#8994]
**Describe the bug:** taiko playfield is smaller compared to the scroller. i think it should at least have the same size if not bigger because the focus should be in the playfield

**Screenshots or videos showing encountered issue:** 
![osu_2020-05-11_15-50-53](https://user-images.githubusercontent.com/41866328/81537398-b12fbb80-939f-11ea-9a7b-a05e3bf613ec.png)

**osu!lazer version:** aa91288

**Logs:**
not needed

**Comment by peppy** [comment]
The scroller would look wrong is it did not take up all vertical screen space, no?

**Comment by enoslayd** [comment]
maybe move the playfields higher??????? then match their sizes???????

**Comment by peppy** [comment]
Yeah, that maybe a feasible solution. Will try and see how it feels.

**Comment by mouzedrift** [comment]
i would probably suggest fixing #5685 if possible since it's messing with a lot of stuff atm. 
![osu_2020-05-11_10-23-31](https://user-images.githubusercontent.com/43358824/81540725-5895f980-9372-11ea-9ad8-35dec457b286.png)

**Comment by peppy** [comment]
#5685 is not relevant and I'm not even sure if fixing it is what we want.

**Comment by Fvern** [comment]
the playfield is already higher in stable, so it would be what players are used to

**Comment by Fvern** [comment]
tested it - storyboard text is cut off by the playfield because it's much lower in lazer due to centering.
lazer:
![osu_2020-05-11_20-43-09](https://user-images.githubusercontent.com/25032854/81562908-26af8200-93c8-11ea-9b2f-56e692574896.jpg)
how it's supposed to look according to a youtube video:
![image](https://user-images.githubusercontent.com/25032854/81563007-48a90480-93c8-11ea-9bcf-392ec18053cd.png)
of course, some storyboard elements seem to not be implemented yet, but that shouldn't affect the fact that the text is cut off by the playfield.
