### ISSUE TITLE
Cant launch osu!lazer via appimaged menuicon

### ISSUE THREAD

**Issue by ackhack** [ppy/osu#9043]
**Describe the bug:** 
Issue from https://github.com/AppImage/appimaged/issues/111
> I download osu! from https://github.com/ppy/osu/releases and appimaged automatically installed it as expected. Trying to lauch it via the menu says:
Failed to launch "osu!"
Failed to change to directory "~" (no such file or directory)
Running on appimaged, continous build (commit b096cd3), build 221 built on 2020-03-30 19:16:46 UTC.
cd ~ works in terminal.

**osu!lazer version:** 
2020.515.0
**Logs:**
[network.log](https://github.com/ppy/osu/files/4638558/network.log)
[performance.log](https://github.com/ppy/osu/files/4638559/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4638561/runtime.log)
[database.log](https://github.com/ppy/osu/files/4638562/database.log)

**Comment by bdach** [comment]
For now running the appimage requires having a system-wide ffmpeg >=4 install alongside it. This is due to the fact that we're not shipping binaries of ffmpeg in the appimage due to not being able to find ones that would reliably work cross-distribution.

Closing; this will be tracked (and hopefully resolved at some point) in #7963.
