### ISSUE TITLE
winget support

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#9073]
**Describe the new feature:** 
Would be cool if osu!lazer could get package manager support via "winget"

**Proposal designs of the feature:** 
![image](https://user-images.githubusercontent.com/17437302/82468543-33686000-9ac3-11ea-89eb-479d2c0c44f2.png)

**Comment by bdach** [comment]
Not sure if this should be supported, at least in the near future. winget's [manifest specification](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv0.1.md) seems really annoying to deal with when releasing often as we do. Note that the SHA of the installer binary is required in that manifest, so that'd mean we'd either have to either:

* continually update the manifests in [the community repository](https://github.com/microsoft/winget-pkgs/tree/master/manifests) (which we'd probably get told to stop doing so often *really* quickly),
* compromise and stick one stale version in there which will only be updated every N months, which probably can wait until we're in a more stable state,
* set up our own [package source](https://github.com/microsoft/winget-cli#sources) which is work and apparently they're not even that well supported right now.

I'd say this can wait. This is hemorrhaging-edge software for now, I'd give it a couple of months to make sure it doesn't get dropped at some point.

**Comment by MiraiSubject** [comment]
(This would probably need a separate issue)

The SHA checksum problem could potentially be resolved by having a generally available web installer that pulls the latest full nupkg from GitHub and installs it. 

I believe the functionality somewhat replicates the update sequence in game except that Squirrel would just apply the full nupkg instead of doing a delta update.

**Comment by bdach** [comment]
It's an idea, but one that sort of defeats the purpose of SHA checks altogether in my view. Why verify a binary at all if it's going to pull potentially who knows what off of a server on the web anyway? (And yes, if the sources were publically available, then you could in theory build and compare checksums, but then reproducable builds are notoriously difficult, so to be entirely certain you'd have to reverse binaries, etc. etc.)

So far I'd say it's not worth the trouble for what is essentially a glorified CLI binary downloader & runner right now.

**Comment by peppy** [comment]
If we were to support anything it would be chocolatey, which i think is the better solution on windows?

Closing for now as a no, though.

**Comment by jorolf** [comment]
Fyi: [WinGet](https://github.com/microsoft/winget-cli) is Microsofts own Package Manager that was released/open-sourced 2 days ago as a preview version

**Comment by mcendu** [comment]
> 
> 
> Fyi: [WinGet](https://github.com/microsoft/winget-cli) is Microsofts own Package Manager that was released/open-sourced 2 days ago as a preview version

This still needs some time imo
