### ISSUE TITLE
Last mod disappears from the list before ModSelectOverlay finishes closing (on certain window sizes)

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#9155]
**Describe the bug:** I first noticed it on my phone, so I tried to reproduce the issue on my desktop setup.
Looks like when the game window is smaller than a certain size, you can see the last mod (currently _Traceable_ for osu!) disappearing before `ModSelectOverlay` is completely closed. It seems to happen only with the osu! ruleset for now.

**Screenshots or videos showing encountered issue:**

https://user-images.githubusercontent.com/43073074/108511580-65138f00-72c0-11eb-9faf-0f9398c06551.mp4

**Comment by frenzibyte** [comment]
This is due to the spacing of each mod button transforming on closing the mod select overlay (at line 369) causing the last button to jump into the next row:
https://github.com/ppy/osu/blob/9b277d52e52c926a30e9816393cd734d014c96c4/osu.Game/Overlays/Mods/ModSelectOverlay.cs#L360-L373

The overlay padding might needs some adjustments to fix that visually.

**Comment by Joehuu** [comment]
No longer a problem in the new design.
