### ISSUE TITLE
Play date in result screen always in MM/DD/YYYY format

### ISSUE THREAD

**Issue by cupppu** [ppy/osu#9202]
**Describe the bug:** self-explanatory, might want a setting to change format

**Screenshots or videos showing encountered issue:** 
<img width="316" alt="image" src="https://user-images.githubusercontent.com/7279624/83656586-4f572000-a5f2-11ea-8845-9225a2ab784d.png">
This score was set on 11th January, 2018

**osu!lazer version:** 2020.602.0

**Comment by frenzibyte** [comment]
The displayed date format might need to actually change, unlike the aforementioned suggestion thread, having this as-is might cause ambiguity because `1/11/2018` can be interpreted as both `January 11th, 2018` and also `November 1st, 2018` (unless you start looking up through existing scores to find which date unit is greater than 12). 

A better clear date format to use would be something like `MMMM d, yyyy` (`January 11, 2018`)

Can also use `DrawableDate` which offers a tooltip including the full clear date and time:
 - `Played 2 years ago` (tooltip: `11 January 2018 10:24:30 UTC+/-X`)

**Comment by bdach** [comment]
That ambiguity is inherent to short date formats. I wouldn't be opposed to using `DrawableDate` for consistency myself but some people really don't like relative dates (as was seen in the web-side debacle about relative rank date...)

Guess I'll reopen for discussion.

**Comment by smoogipoo** [comment]
Not using relative dates was a conscious decision. People often screenshot the result screen to share scores, in which the absolute date is always preferred.
