### ISSUE TITLE
Custom file paths for mania judging through skin.ini not implemented yet

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#9242]
Instead of using the correct files with a custom path in skin.ini, osu!lazer uses the default ones. Lazer will use mania-hit0 even if there's a different file specified in skin.ini, for example combo_display/judge/0 in this skin: https://www41.zippyshare.com/v/Jib9a9n4/file.html .
**osu!lazer version:** 2020.603.0

**Comment by mcendu** [comment]
After a bit of investigation, this is not the only configuration set that does not work. Custom file path for some other files (here `StageLeft` and `StageRight`) are also missing, [as demonstrated by this demo skin.](https://github.com/ppy/osu/files/4771589/special-skin.zip) I think it is because such data is not written into `ImageLookups` when generating a mania skin configuration.

**Comment by smoogipoo** [comment]
Yep, full list of ones that are missing:
```
StageLeft
StageRight
StageBottom
StageHint
StageLight
```

Should be done in a separate PR though.
