### ISSUE TITLE
Show desktop in Windows doesn't work with lazer

### ISSUE THREAD

**Issue by ciiii0001** [ppy/osu#9246]
**Describe the bug:** 
When I want to minimize osu! in fullscreen mode, I usually press Win key and click show desktop button at the end of the taskbar. This works well in stable (except the editor), but doesn't work in lazer (osu!lazer won't minimize after clicking show desktop button).
Another shortcut for showing desktop is Win+D. This shortcut makes the desktop shows up, but the osu!lazer will pop up automatically after I click anything (e.g. opening a folder).
The Win+M shortcut (minimize all windows) also doesn't minimize osu!lazer.

**Screenshots or videos showing encountered issue:** not required I guess

**osu!lazer version:** 
2020.603.0
Windows version: win10 1909 18363.836

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/4753229/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4753231/updater.log)
[network.log](https://github.com/ppy/osu/files/4753232/network.log)
[performance.log](https://github.com/ppy/osu/files/4753233/performance.log)

**Comment by bdach** [comment]
Fingers crossed SDL's fullscreen will sort this out for us.

**Comment by Joehuu** [comment]
Yup, fixed in SDL (Win key just minimizes fullscreen window like stable).

> When I want to minimize osu! in fullscreen mode, I usually press Win key and click show desktop button at the end of the taskbar.

Pressing win key already minimizes osu!, thus I'm not sure why you need to click the show desktop button.

> This works well in stable (except the editor), but doesn't work in lazer (osu!lazer won't minimize after clicking show desktop button).
Another shortcut for showing desktop is Win+D. This shortcut makes the desktop shows up, but the osu!lazer will pop up automatically after I click anything (e.g. opening a folder).
The Win+M shortcut (minimize all windows) also doesn't minimize osu!lazer.

This is borderless behavior in stable (editor in stable forces borderless for some reason). Somehow lazer's opentk fullscreen is acting like borderless, but SDL fixes that. Not sure if borderless will also act like this in SDL but it's still broken.

**Comment by peppy** [comment]
@Joehuu weird, because I get SDL treating both borderless and fullscreen as fullscreen..

**Comment by Joehuu** [comment]
Ya, sorry if the way I worded it confused you.

OpenTK: borderless and fullscreen act like stable's borderless when pressing win key, but fullscreen flickers black once
SDL: as you said, borderless and fullscreen act like stable's fullscreen when pressing win key

In the last comment, I said that SDL fixes fullscreen not minimizing correctly when win key is pressed, and that borderless is still broken (i.e. acting like fullscreen).

**Comment by Joehuu** [comment]
Fixed in SDL as of now. Borderless should leave window visible when pressing the win key, alt-tabbing, etc. though, but will make a separate issue in framework.
