### ISSUE TITLE
i can't uninstall osu!lazer

### ISSUE THREAD

**Issue by RiyadhAlmalki** [ppy/osu#9254]
**I want to uninstall osu!lazer completly but i can't,I need a solution ASAP please :** 

** https://youtu.be/5c1n3nJWoV8 :** 

**2020.603.0:** 

**i don't know what is logs:**

**Comment by Game4all** [comment]
The youtube video url you attached to this issue is private; As such it is hard to tell what's wrong without further explanations.

**Comment by RiyadhAlmalki** [comment]
i think now u can see the issue now

**Comment by GSculerlor** [comment]
You just removing the game files, not uninstall it. Use control panel to uninstall something

**Comment by Gabixel** [comment]
In order to uninstall an app (osu!lazer in this case), you should [go use the Control Panel](https://support.microsoft.com/en-us/help/13764/windows-where-is-control-panel) (for Windows users), otherwise you can use the [Windows 10 Settings app](https://support.microsoft.com/en-us/help/4028054/windows-10-repair-or-remove-programs).

**Comment by RiyadhAlmalki** [comment]
thx guys i don't know about the control panel
