### ISSUE TITLE
crashing multiple times

### ISSUE THREAD

**Issue by Mark333335** [ppy/osu#9320]
**Describe the bug:** 
just press the osu app and it crashed after a few seconds of black screen
**Screenshots or videos showing encountered issue:** 

https://m.imgur.com/gallery/IMSz6bC

**osu!lazer version:** 
2020.616.0

**Comment by Mark333335** [comment]
no log on my phone

**Comment by frenzibyte** [comment]
iOS or Android?

**Comment by Mark333335** [comment]
ios

**Comment by frenzibyte** [comment]
Well, if you read the [contribution guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md) (should be found at the side of opening an issue), at issue submission section, you'll find out it has been stated how to retrieve logs for iOS:
> - on iOS they can be obtained by connecting your device to your desktop and copying the logs directory from the app's own document storage using iTunes,

Please go through that and attach the logs here, otherwise it's very hard to help without any sort of logs.

**Comment by peppy** [comment]
Should be fixed via https://github.com/ppy/osu-framework/pull/3636
