### ISSUE TITLE
Make it possible to view the leaderboard and star rating at the same time

### ISSUE THREAD

**Issue by vruss** [ppy/osu#9412]
**Describe the new feature:** 
Currently in stable, it's possible to view the beatmap leaderboard and view the star rating at the same time. In Lazer, the star rating is only visible in the beatmap details screen. 

**Proposal designs of the feature:** 
Add the star rating to the beatmap card at the top. 
![Paint sketch](https://user-images.githubusercontent.com/10886082/86135879-ac5bce00-baeb-11ea-9c2a-ae775145fe1e.jpg)

Sidenote: Having proper icons for bpm etc. instead of the circle icon would be great!

**Comment by bdach** [comment]
Icons are tracked in #2229.

**Comment by peppy** [comment]
@smoogipoo is this already in the design? or something we need to clarify?

**Comment by smoogipoo** [comment]
Song select doesn't have an updated design yet...

**Comment by peppy** [comment]
@arflyte do you have anything in mind to display the numerical star rating somewhere always visible? probably something we want.

**Comment by arflyte** [comment]
Haven't touched song select for quite some time, but star difficulty is one of the top priorities for the new design. following is an old design that will be updated.

![Figma_200702-033717](https://user-images.githubusercontent.com/3632750/86280419-ba5a3d80-bc16-11ea-8719-a6ac7bea7e2f.png)

the new song tiles design already have star difficulty displayed with the new difficulty spectrum colour. this will be displayed on the main display along.

![Figma_200702-034222](https://user-images.githubusercontent.com/3632750/86280459-ccd47700-bc16-11ea-8e3d-597e7bd290a5.png)

I'll work on this soon.

**Comment by bdach** [comment]
As a semi-related note/heads-up I have found a method to generate bitmaps of the Torus font with the alternate glyphs (as depicted in the above design) leveraging fontforge. It requires some manual work (swapping glyphs and then exporting to `.ttf`, which then can be fed to bmfont). Can post the steps on request.

Not sure whether that method is something we can use, though (thinking about font licensing). I'm definitely not going to PR the glyphs myself since I *technically* don't have access to the font files.

**Comment by peppy** [comment]
Hmm, I guess if it's already being displayed as a number on the difficulty card it's not strictly required to the left display, but maybe consider adding the numerical display somewhere on the left if you can fit it, just for conformity.
