### ISSUE TITLE
Storyboard is not aligned perfectly to the playfield

### ISSUE THREAD

**Issue by CtrlAltWaverick** [ppy/osu#9457]
**Describe the bug:** 
circle size works differently in lazer than in stable, causing issues with maps that use storyboard for fake circles (disconnected hardkore, aleph-0, storyboard-based aspire maps)

**Screenshots or videos showing encountered issue:** 
![Screen Shot 2020-07-08 at 12 09 03 PM](https://user-images.githubusercontent.com/35770107/86943051-efcdc200-c113-11ea-8b73-ab47f7f48285.png)
From Aspire V's "RiraN - Unshakable". The slider that the cursor is on is real, as is the one fading in on the left, but the one in the bottom right is not.

**osu!lazer version:** 
2020.707.0

**Comment by CtrlAltWaverick** [comment]
![Screen Shot 2020-07-08 at 12 13 53 PM](https://user-images.githubusercontent.com/35770107/86943502-8601e800-c114-11ea-89bf-98bb566551f4.png)
Here's a different picture, from Disconnected Hardkore. The smaller circles are real (and invisible in stable but that's beside the point), while the ones in the back are part of the storyboard.

**Comment by bdach** [comment]
I cannot reproduce any circle size difference on either map mentioned. There are slight position mismatches, sure, but no circle size mismatch.

(Unshakable - [link to aspire V pack concerned](https://assets.ppy.sh/contests/105/category-105-entries.zip):)

![osu_2020-07-08_18-34-06](https://user-images.githubusercontent.com/20418176/86945995-0858cf00-c14a-11ea-8678-2e286172f734.jpg)

([Disconnected Hardkore](https://osu.ppy.sh/beatmapsets/832364#osu/1743837):)

![osu_2020-07-08_18-35-46](https://user-images.githubusercontent.com/20418176/86945999-0a229280-c14a-11ea-99b7-6505be2c5af3.jpg)

![osu_2020-07-08_18-39-38](https://user-images.githubusercontent.com/20418176/86946317-7e5d3600-c14a-11ea-8cfe-b3ec706008a5.jpg)

(beatmap skins purposely off to distinguish real & fake circles).

Do you have some sort of custom UI scaling on?

**Comment by CtrlAltWaverick** [comment]
forgot to mention, I’m on Mac. that might have something to do with it. my monitor resolution is 1920x1080, ui scaling is 1.00x, screen scaling is “gameplay”.

**Comment by bdach** [comment]
And I suppose that your "Horizontal scale" and "Vertical scale" settings are *not* set too 100%, right? That would entirely explain the difference.

Now whether storyboards should be scaled along with the playfield is a different matter entirely and actually would probably be situational.

**Comment by CtrlAltWaverick** [comment]
huh, they’re set to 80%. I just assumed that didn’t affect anything, because it didn’t have the little yellow bar that notes a setting not at default, so I didn’t check what it actually was. Changing screen-scaling to “off” fixed it, thanks

**Comment by bdach** [comment]
Renaming this to track the fact that the storyboard does not always adhere to the playfield coordinate-wise (although unsure if storyboard scaling should be a thing; the offset should probably be fixed, though).

**Comment by Wieku** [comment]
I'm trying to tackle this.
Fixing the offset was pretty straightforward:
```c#
private void addUnderlayComponents(Container target)
        {
            target.Add(DimmableStoryboard = new DimmableStoryboard(Beatmap.Value.Storyboard)
            {
                RelativeSizeAxes = Axes.Both,
                Position = new Vector2(0, -12.8f),
            });
        }
```
where `-12.8f` is basically `-16*OsuHeight/StoryboardHeight`. In playfield coordinate system that shift would be `-8`:
```go
func (camera *Camera) SetOsuViewport(width, height int, scale float64, offset bool) {
	baseScale := float64(height) / OsuHeight
	if OsuWidth/OsuHeight > float64(width)/float64(height) {
		baseScale = float64(width) / OsuWidth
	}

	scl := baseScale * 0.8 * scale

	shift := 0.0
	if offset {
		shift = 8 //matches with osu!stable
	}

	camera.SetViewport(width, height, true)
	camera.SetOrigin(NewVec2d(OsuWidth/2, OsuHeight/2))
	camera.SetPosition(NewVec2d(0, shift))
	camera.SetScale(NewVec2d(scl, scl))
	camera.Update()

	camera.rebuildCache = true
	camera.viewDirty = true
}
```

And it works flawlessly, exploding circles in [this](https://osu.ppy.sh/beatmapsets/484532#osu/1047758) storyboard are aligned properly (tested with FHD, FHD with 80% scale and WQHD), same with fake circles on Disconnected Hardkore (they're slightly misaligned but I guess that's the imperfection of the storyboard):

![image](https://user-images.githubusercontent.com/5307179/89120535-61045900-d4b7-11ea-825e-db39f273627b.png)
![image](https://user-images.githubusercontent.com/5307179/89120808-5cd93b00-d4b9-11ea-986b-195190244506.png)

But this fix creates a major problem. As playfield in lazer is not at the same position as in osu!stable, a little black bar appears at the bottom of the screen:
![image](https://user-images.githubusercontent.com/5307179/89120678-86459700-d4b8-11ea-8be6-f16ce78ddd09.png)

So the better solution would be to shift the playfield downwards a little but I guess that's out of question because of object heatmap at the bottom.

And I think storyboard scaling should exist as a visual option because they are crucial for some maps.

**Comment by bdach** [comment]
I'd probably suggest shifting all storyboard layers *except* background but there's probably some map out there that such a solution would not work with.

**Comment by Wieku** [comment]
That's why I think shifting the playfield downwards to match osu! stable is a better solution. I think it would also slightly help tablet players that come from stable.

**Comment by smoogipoo** [comment]
I also agree to moving the playfield/better match osu-stable's playfield in lazer, having experienced the same tablet awkwardness recently myself.
