### ISSUE TITLE
Very high HP drain on spinners

### ISSUE THREAD

**Issue by Larakagi** [ppy/osu#9513]
In osu!catch there are plenty of maps that features HP7 + a long spinner. One of the maps which is [Hyun - Grin](https://osu.ppy.sh/beatmapsets/1065368#fruits/2230881) it's quite impossible to pass because of this ridiculously high HP drain (to me it feels like HP10+).

Edit: apparently there is a simular issue on https://github.com/ppy/osu/issues/9367 but because of this new spotlight edition it should be fixed somehow (referring to osu!catch in stable spinner recovers your hp instead of reducing your hp drain during spinner section)

**Comment by KevKjef** [comment]
A map such as AugoEidEs (https://osu.ppy.sh/beatmapsets/418826#fruits/906421) will also be insanely hard to pass, if not impossible due to the long spinner at the end.
There are a lot of other ranked maps, which have long spinners, some of which will autofail you even when you do take the most-optimal spin route you can take.
This would also be an issue for HR, as spinning becomes harder, and the HP drain becomes even harsher.
Most of the maps with decently long spinners are currently passable, as long as you take the best spin-route and get the near-max amount of bananas.

While most players do atleast know how to spin in a way, that would prevent failing on these spinners, there are quite a lot of players who don't spin (or not to the extent of trying to take the best path) and will end up failing because of the HP drain
The same goes for newer players who don't know the spin paths and just move wherever.
This will result in certain spinners being really hard too pass, due to the need to take the best spinroute (which sometimes isn't even enough)
This will cause the hardest parts of some maps to be the spinner, which is quite ridiculous

Also, https://youtu.be/JYBZ-zW6iv0 is a video of me playing Grin. You can see I have full HP at the end, yet still fail because I didn't max spin.
I don't consider myself very good at spinning, but the path I took is a path that lets you consistently get a good amount of bananas. 
And yes, I do miss a couple bananas (which I why I didn't pass), but the hardest part of the map is 100% the spinner right now.
Also I am 99% sure you wouldn't be able to pass this map with HR due to the higher HP drain
