### ISSUE TITLE
combo-lightning in osu!catch is blinding

### ISSUE THREAD

**Issue by KevKjef** [ppy/osu#9515]
**Describe the bug:** Note: hit lightning is disabled
The lightning you get when catching a fruit is very blinding. I don't know what this is exactly called, since it isn't hit lightning, but rather an effect that appears for every fruit you catch.

This sort of 'combo'-lightning is also present in stable except it is way less blinding. 
It also is a lot bigger in stable, (as in the lightning effect goes as far as about the middle of the screen instead of just being a small 'ball' above the catcher)

The way to fix this would be to make it similar to the 'combo'-lightning in stable.
alternatively a way to turn this effect off could be added.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/JYBZ-zW6iv0 (lazer catch with skin)
https://youtu.be/INGFHIrtC1U (lazer catch with default skin)
It doesn't look as bad on video, but when playing these light are very blinding

Compared to the 'combo'-lightning in stable
https://www.youtube.com/watch?v=BkE6h8RSJio (stable osu!catch, you can see it here or in any other osu!catch video)

**osu!lazer version:** 
2020.710.0

**Comment by jai-x** [comment]
This is quite a large post!

While I appreciate the time and effort, making large posts with multiple issues makes it difficult to address the specifics of each issue and it becomes difficult to track each one in this post as they are fixed over time.

I would suggest that each specific point you have should be opened as a separate issue post with details given as needed.

Please make sure to search existing issues regarding catch so that you don't create duplicates. These can can be found here: https://github.com/ppy/osu/issues?q=is%3Aopen+is%3Aissue+label%3Aruleset%3Aosu%21catch

**Comment by peppy** [comment]
Should disable with hit lighting toggle.

**Comment by peppy** [comment]
Although I find it amusing that you call it "blinding" when it is much smaller and more subtle than the stable implementation.
