### ISSUE TITLE
Improve usability of mania scroll speed slider

### ISSUE THREAD

**Issue by mas-alone** [ppy/osu#9689]
**Describe the new feature:** 
I hope Lazer’s setting about notes’ falling speed can be the same as stable version.I wish Mania's falling speed can be used with a wild speed (the fixed) instead of the current slider. It is very inaccurate and it is very troublesome.
**Proposal designs of the feature:** 
just like stable >< please
![QQ截图20200727192808](https://user-images.githubusercontent.com/52590027/88537113-84ef1700-d03f-11ea-8032-bb32e7f0647d.png)
![QQ截图20200727193030](https://user-images.githubusercontent.com/52590027/88537190-aea83e00-d03f-11ea-815a-1023d299c3a4.png)

**Comment by peppy** [comment]
Are you asking for the "checked" version of the option you point at? Right now, scroll speed does *not* scale (ie. the unchecked state on stable) which is I think what you're asking for...?

**Comment by Joppe27** [comment]
I think they're asking for the specific stable BPM scaling (with numbers) instead of doing it in milliseconds. They can only be adjusted with the slider in settings in steps of 25ms or so (if you move the mouse VERY slowly) which is annoying and too sensitive when it comes to faster scroll speeds. You can't solve this by using the arrow keys since those adjustements are even bigger.

I think the BPM slider setting should not be linear and instead make smaller ms adjustements in the faster scroll speed area and bigger ms adjustements in the slow scroll speed area. There's no reason to make precise adjustements to very slow scroll speeds (e.g. 1050 -> 1000ms) because the difference there is almost unnoticable, however it is very much noticable on faster scroll speeds (e.g. 450 -> 400ms). There could also be a field where the user can just type the scroll speed they want which would solve this issue more easily (?)

There's also the in-game scroll adjustment that does use numbers like on stable, but the numbers represent completely different scroll speeds in comparison to stable which is pretty irritating.

**Comment by peppy** [comment]
As you've mentioned, if you use the keyboard controls, like stable, it shows numbers, like stable.

The new numbers are scaled in a similar way and should allow quit precise adjustment. @mas-alone could you please try that method first so we can ascertain what changes need to be made to make people feel at home?

**Comment by mas-alone** [comment]
> As you've mentioned, if you use the keyboard controls, like stable, it shows numbers, like stable.
> The new numbers are scaled in a similar way and should allow quit precise adjustment. @mas-alone could you please try that method first so we can ascertain what changes need to be made to make people feel at home?

As @Joppe27  said, this is what I want to express. Although slider is a new way to adjust the falling speed, it can't be adjusted to its precise value very accurately. (For example, I want to adjust it to 500ms now, and the mouse slides gently to the left to become 465ms, and then slides gently to the right to become 550 ms.) My suggestion is to add an input box next to it, so that players can freely input the "ms" they want.
