### ISSUE TITLE
osu!lazer won't open at all (Android)

### ISSUE THREAD

**Issue by CakeReport** [ppy/osu#9737]
**Describe the crash:** As the title said, osu!lazer immediately closed after opening it on android device

**osu!lazer version:** 2020.801.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5008257/runtime.log)

**Comment by Game4all** [comment]
Please specify your android device as well as your android version

**Comment by CakeReport** [comment]
Device : Vivo v15 pro (running snapdragon 675)
Android version : Android 10

**Comment by smoogipoo** [comment]
Can anyone else replicate this?

**Comment by peppy** [comment]
Didn't happen to me during debug. I don't have a device handy to test, unfortunately. If this is a common issue, a temporary solution is to run the previous version.

**Comment by Joehuu** [comment]
Can replicate on Pixel 3a with Android 10.

[runtime.log](https://github.com/ppy/osu/files/5008325/runtime.log)

**Comment by Yuuhei** [comment]
Can confirm, crashing on my device

Xiaomi Redmi Note 8
Android 9 (MIUI 11)
SD665, 3/32gb variant

Video:
https://streamable.com/6d57ft

Replicate:
Download the latest release, then run.

**Comment by peppy** [comment]
Will just pull the android build for now I guess. A PR fixing would be appreciated.

**Comment by MeguMario** [comment]
compiled the game from source seems to work fine for me

Google Pixel 2 on Android 11 Beta 2.5 (or as reported in VS, Android 10.0.99 API 30)
osu!lazer version: last commit f1d2312 

don't have 2020.801.0 to begin with but this should be identical
[runtime.log](https://github.com/ppy/osu/files/5010156/runtime.log)

**Comment by bdach** [comment]
This will only show up on release builds and is due to xamarin.android not returning the full, "hidden" path of the game DLLs due to not having debug symbols around.

Currently figuring out if there's a way to get that on release but it looks pretty grim right now.

**Comment by bdach** [comment]
After fighting with android's horrendous toolchain and garden-walling I know what the issue actually is. The problem is that on release builds the DLLs are straight up *not available* as a file, due to the release build config [specifying `EmbedAssembliesIntoApk` to true](https://github.com/ppy/osu/blob/246048825558a407c0d353fb9b4e49d228c0cda9/osu.Android.props#L38). Changing that to `false` makes the game launch, but also makes it virtually undeployable as it's just not a single `.apk` any more.

The only bandaid available right now seems to be outright disabling computing the hash on Android, at the cost of breaking spotlights (I assume web won't issue submission tokens without a hash). In general to get this working cross-platform, I think it might be necessary to use a deployment-time generated secret instead of relying on generating one at run-time. Not sure how to proceed right now myself.

**Comment by bdach** [comment]
Going to throw out an idea I just got: how opposed would we be to generating the hash of `osu.Game.dll` at build-time and embedding it into the `.apk` in some capacity? I think that could be the most elegant workaround for now. Unsure how bypassable it would be, but seems viable in my head.

**Comment by smoogipoo** [comment]
I think that's a fine path to go down for the time being.

**Comment by peppy** [comment]
Probably just going to drop back to a version check instead. I don't want to have to deal with per-platform details for the moment.

**Comment by bdach** [comment]
I think it could be possible to have msbuild do it in this repo (without requiring changes to `osu-deploy`) but I haven't tested whether the solution I have in mind is viable (it would be pretty hacky to say the least), so yeah, using version is probably best for now.

Not sure if just swapping the hash string for a version string is sufficient, or whether more infra work is required. If it's the former I could PR that within a day.

**Comment by peppy** [comment]
It's not worth it at this point in time.

A simple fallback should work for now

```csharp
try {
    // existing code
}
catch
{
    VersionHash = $"{Version}-{RuntimeInfo.OS}";
}
```

**Comment by bdach** [comment]
Confirming no crash on my device with the merged changes on a local release build.
