### ISSUE TITLE
Pause loop does not stop playing immediately after pressing continue

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#9739]
The new pause loop doesn't stop playing after pressing continue in the pause menu, it continues for about 2 more seconds instead. Seems like a small oversight.
https://youtu.be/CW6e-9jHk_M
**osu!lazer version:** 2020.801.0

**Comment by frenzibyte** [comment]
The whole playback seems to be kinda broken, but in this issue specifically: 

It's not actually about it not stopping, another play is triggered after stopping the loop on resume due to the added logic in https://github.com/ppy/osu/pull/9687, which assumes that all components that have a `GameplayClock` cached are all gameplay hit samples and shall be paused on gameplay pause and resumed on gameplay resume.

There seem to be two ways to solve this:
 1. Adding an overridable boolean property to disable this logic and using it for the pause loop sample. (easy way, but kind of a bandaid to the current hierarchy of `Player`, which (2) is proposing to fix)
 2. Moving all components that are not meant to follow the `GameplayClock` (overlays, etc..) out of the `GameplayClockContainer`, and provide them by constructor to the overlays that are designed to interact with it (such as `SkipOverlay` and otherwise).

**Comment by smoogipoo** [comment]
Yeeeeeah I knew that would come back to bite us when that thing was implemented, which is why I suggested having a `GameplaySkinnableSound` or similar with the pause/resume logic...

**Comment by frenzibyte** [comment]
`GameplaySkinnableSound` actually "sounds" like the best sensible way to go in fixing this, I'll push a fix for it.

**Comment by frenzibyte** [comment]
As an update to the status of this thread, the issue has been fixed by https://github.com/ppy/osu-framework/pull/3792, it had some relation with the pause logic of `SkinnableSound` but it should still behave the same, which the framework PR corrected as it was wrong (calling `Play()` a second time does not stop and free previous playing channel).

The reason I didn't mention to close this issue in the aforementioned framework PR is because I wanted to replace the whole `SkinnableSound` pause logic with something more elegant and does not arbitrarily decide on "gameplay" sounds by whether the component has a `GameplayClock` cached (like `PauseOverlay` has), but turns out `FrameStabilityContainer` does not update its clock's running state properly, which needs to be fixed first (and doesn't seem to be easy enough to do, I'll try to).

I think this can be closed now as I believe the "high priority" label and being set on "August 2020" milestone is meant for the pause loop playback to be corrected, which has been long done by the aforementioned framework PR.

**Comment by bdach** [comment]
Seeing that the pressing issue has been resolved I'll go ahead and close for now.
