### ISSUE TITLE
Pause loop requires pausing twice to actually play

### ISSUE THREAD

**Issue by ThatsNiceGuy** [ppy/osu#9740]
**Describe the bug:** 
Suspected to only be on mobile
When the player pauses the game, the pause loop is expected to play but it does not play until the player resumes the game then pauses for a second time.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/q3JL7k9TUes

**osu!lazer version:** 
TestFlight 2020.801.0
iOS 13.5 on iPhone XR

**Logs:**
N/A

**Comment by frenzibyte** [comment]
I cannot reproduce this one, but the only things that are interrupting sample playback or not updating the transforms for the volume to rise up or low down are:
 - The "pause playback on gameplay pause" logic, which is tracked in https://github.com/ppy/osu/issues/9739.
 - The `IsMaskedAway` property being set, which is reported framework-side in https://github.com/ppy/osu-framework/issues/3780.

Otherwise the `AudioContainer` inside `SkinnableSound` should be updating the transforms and there should not be any playback interruptions occurring.

So I would say try reproducing this in a release when all of the above are fixed.

**Comment by ThatsNiceGuy** [comment]
Just tested on an iPhone SE 1 running iOS 14 and it didn’t happen. Idk what it is

**Comment by peppy** [comment]
I've never seen this happen and can't repro. Going to close for now.
