### ISSUE TITLE
bootup loop

### ISSUE THREAD

**Issue by spyro12675** [ppy/osu#9749]
**Describe the bug:** 
Every single time i boot up osu lazer it doesn't work but just osu works sooo whats wrong?

**Screenshots or videos showing encountered issue:** 
Yes

https://photos.app.goo.gl/8w7bTd436SC6y5KQ7

**osu!lazer version:** 
all??

**Logs:**

**Specs:**
OS Name	Microsoft Windows 10 Home
Version	10.0.18363 Build 18363
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	LAPTOP-EC2GOIRB
System Manufacturer	ASUSTeK COMPUTER INC.
System Model	ROG Strix G731GT_G731GT
System Type	x64-based PC
System SKU	
Processor	Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz, 2592 Mhz, 6 Core(s), 12 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. G731GT.306, 11/03/2020
SMBIOS Version	3.2
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	ASUSTeK COMPUTER INC.
BaseBoard Product	G731GT
BaseBoard Version	1.0
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume3
Locale	United States
Hardware Abstraction Layer	Version = "10.0.18362.752"
User Name	LAPTOP-EC2GOIRB\rexsk
Time Zone	E. Australia Standard Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.9 GB
Available Physical Memory	4.69 GB
Total Virtual Memory	33.9 GB
Available Virtual Memory	14.3 GB
Page File Space	18.0 GB
Page File	D:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

**Comment by frenzibyte** [comment]
Logs are needed for further assistance, please attach them. (if you have custom path set, you can find the logs in `(your custom path)\osu-lazer\logs`, or `%AppData%\osu\logs` otherwise).

Next time, please read the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md) first to avoid posting bug reports with missing requirements.

**Comment by bdach** [comment]
In addition to the above:

* Can you use mouse scroll wheel to adjust volume while that black screen is showing? If yes, does it produce sound when you click the mouse button, for example?
* Have you deleted a large number of beatmaps recently?

**Comment by spyro12675** [comment]
@frenzibyte there is no logs there
@bdach 1. yes 2. no for sound no

**Comment by bdach** [comment]
I mis-spoke about the sound; sound should be produced if you hover over the mute button, for example. But given the fact that you have ran a large deletion recently I would recommend leaving the game open for a few minutes and seeing if it proceeds to intro. Beatmap deletions are not ran immediately; they are deferred until the next launch of the game, which is why you might be seeing that hang.

If you're not hearing audio either, though, this might be due to a misconfiguration/failure to initialise your audio device.

**Comment by spyro12675** [comment]
this started a while back and i have updated it to the new version every time it still doesn't work and ive uninstalled it and it doesn't work

**Comment by bdach** [comment]
Saying that "it doesn't work" on its own helps nothing.

Please try renaming `%AppData%/osu/client.db` and seeing if it helps anything.

**Comment by spyro12675** [comment]
well normal osu work so how can it be that

**Comment by bdach** [comment]
lazer is a from-the-ground-up reimplementation. many aspects of how it works were changed. comparisons to it are in many ways invalid in a technical sense.

if you're going to be questioning our efforts to try and resolve the problem you're having, then please don't open issues so that we can all save time.

**Comment by spyro12675** [comment]
no i was just curious i'll see if that works

**Comment by spyro12675** [comment]
wait what do i rename it to?

**Comment by bdach** [comment]
anything else than what it is named right now.

you could delete/move it somewhere else it too. so long as there is no file named `client.db` in the aforementioned directory.

**Comment by spyro12675** [comment]
ok then do i launch it?

**Comment by bdach** [comment]
i imagine that is pretty necessary to check if that did anything, so, yes, please do.

**Comment by spyro12675** [comment]
YAY it works thank you soooo much

**Comment by bdach** [comment]
this means that you had a lot of beatmaps queued for deletion, which we're tracking separately at #6568. please note that this fix means that you're starting from an empty database and need to reimport maps again. if you want to continue with the old ones, please restore the moved/renamed `client.db` file, launch the game and let it be for a while so that it can finish deleting what it needs to.

closing as duplicate/resolved.
