### ISSUE TITLE
Changing volume with Alt + Mouse Wheel Up/Down doesn't work inside overlays

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#9799]
**Describe the bug:** I guess when <kbd>Alt</kbd>+ <kbd>Mouse Wheel Up / Down</kbd> is used inside an overlay (e.g. user profile, osu! direct, etc.), Lazer should increase/decrease the volume. But it doesn't seem to consume that input properly.

**osu!lazer version:** 2020.806.0

**Comment by hbnrmx** [comment]
Probably related: https://github.com/ppy/osu/issues/6026#issuecomment-528930807

**Comment by smoogipoo** [comment]
I don't believe we currently have special handling for Alt+WhUp/WhDn. I slightly recall us discussing not implementing that for lazer, because you can whup/whdn anywhere in the background (the faded area) that's not a scrollable area, but my recollection may be incorrect.

**Comment by enoslayd** [comment]
Idk if related (or maybe just me) but it doesn't also work in gameplay (though it works in pause screen

**Comment by Game4all** [comment]
> 
> 
> Idk if related (or maybe just me) but it doesn't also work in gameplay (though it works in pause screen

Sounds like you toggled "Disable mouse wheel during gameplay" without noticing. Disabling it should allow you to set volume with mouse wheel while playing
![image](https://user-images.githubusercontent.com/20256717/89658963-7ae6d700-d8cf-11ea-927b-f14c7a309232.png)

**Comment by peppy** [comment]
We don't have alt-wheel handling (and likely won't be adding it due to being a very awkward UX). Discussion in discord happened recently, leaning towards making it easier to change the volume via on-screen elements (ie. a volume control in the toolbar or otherwise) rather than requiring hotkeys in some locations.

But we may have to add this back if there's enough demand from legacy users.

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu/pull/12225.
