### ISSUE TITLE
about mania accuracy question

### ISSUE THREAD

**Issue by mas-alone** [ppy/osu#9801]
**Describe the new feature:** 
Now, "mania" accuracy deduction is too serious. like the "great", the deduction seems to be more than expected. As can be seen in the figure, the accuracies are almost the same, but only 93.64% of the "Lazer" ACC and 98.91% of the ACC on the stable. This makes it difficult for players to achieve an "s" ranking

my lazer version is 2020.806.0
![QQ图片20200807225527](https://user-images.githubusercontent.com/52590027/89658424-1d6b7e00-d901-11ea-84ed-b6b893a619de.png)

**Proposal designs of the feature:** 
I hope it can be closer to the scoring method of "score V2"(osu!mania mode)

**Comment by smoogipoo** [comment]
This is intended for now.

Given that lazer's mania is based on 95% accuracy scoring, having PERFECTs count as their true scoring values rather than the same as GREATs actually gives a better indication of how well you did on a map.

From an improvement standpoint, most players generally take note of their acc% at least on their most-top play (and where they've previously dropped acc), and it's nice to be able to compare your acc% to that previous value to get a reasonable approximation for how well you're doing.

Also, rank is irrelevant.

**Comment by mas-alone** [comment]
> This is intended for now.
> 
> Given that lazer's mania is based on 95% accuracy scoring, having PERFECTs count as their true scoring values rather than the same as GREATs actually gives a better indication of how well you did on a map.
> 
> From an improvement standpoint, most players generally take note of their acc% at least on their most-top play (and where they've previously dropped acc), and it's nice to be able to compare your acc% to that previous value to get a reasonable approximation for how well you're doing.
> 
> Also, the grade is irrelevant.

well, it looks good. It may take some time to adapt.
