### ISSUE TITLE
Overlay pop in/out animations have inconsistent ordering

### ISSUE THREAD

**Issue by recapitalverb** [ppy/osu#9815]
**Describe the bug:** The News overlay has inconsistent ordering and always opens under other overlays.

**Screenshots or videos showing encountered issue:** https://youtu.be/h4xxZOPUVZI
Notice that when opening the overlays from right to left, the next overlay always go over the previous, except for News.

**osu!lazer version:** 2020.806.0

**Comment by bdach** [comment]
"Friends" -> "Beatmap listing" is also wrong (pop out then pop in instead of reverse).

We probably want to add explicit depth value specifications to fix this properly. Right now as far as I can tell z-ordering of the overlays is haphazard (depends on the duration/ordering of load completion callbacks).

**Comment by recapitalverb** [comment]
Should `area:overlays` label be added as well?

**Comment by peppy** [comment]
I think eventually we'll want them to reorder so the newest one is always on top, unless already started to be displayed.
