### ISSUE TITLE
Follow points are sometimes not rendered

### ISSUE THREAD

**Issue by firinael** [ppy/osu#9832]
**Describe the bug:** as the title says, followpoints are showing up inconsistently, sometimes at the start of a map, sometimes at the end of a map, sometimes not at all. no map I've played in the last two updates has had followpoints in its entirety, and I've tested multiple skins already, so I've absolutely no idea what the issue is here.

**Screenshots or videos showing encountered issue:** 
![osu_2020-08-11_16-54-31](https://user-images.githubusercontent.com/67032657/89942690-62d6c680-dbf3-11ea-8730-4ec21d815b74.png)
![osu_2020-08-11_16-56-30](https://user-images.githubusercontent.com/67032657/89942860-a92c2580-dbf3-11ea-8b17-0aaf9f7dec11.png)

https://youtu.be/cLCBel-ktA0 <- video showing the followpoints appearing at the start of the map and then just not showing up anymore

both screenshots were taken like 3s apart, also.

skin link: https://puu.sh/GgSWG/32363d5839.osk

**osu!lazer version:** 2020.806.0

**Comment by bdach** [comment]
Please attach the skin(s) in question.

**Comment by firinael** [comment]
updated the original post.

**Comment by frenzibyte** [comment]
There is a button in the settings right after the skin dropdown for exporting the selected skin, please export it and attach it here.

**Comment by firinael** [comment]
I am the big dumb.

skin link:
https://puu.sh/GgSWG/32363d5839.osk

**Comment by Joehuu** [comment]
FWIW it happens on the default skins too.

https://streamable.com/xcy5ys

**Comment by bdach** [comment]
Can reproduce, it happens on some maps (but didn't repro at first). If in autoplay and the follow points are not showing, rewinding will bring them back.

**Comment by bdach** [comment]
The follow point sprites seem to be stuck at zero alpha for some reason. This looks to have regressed with framework bump at #9773. Highly suspecting this is a regression from ppy/osu-framework#3779; this also partly corroborates with some discord reports of transforms working funny (cc: @LumpBloom7).

By presentation I'm guessing wrong clock readout, but I'm not overly familiar with the framework PR in question and won't be able to look much further tonight.

**Comment by bdach** [comment]
It appears that my shot in the dark was more or less correct. This is the call stack of the method that applies the follow point transforms:

```
FollowPointConnection.refresh() at /home/dachb/opensource/osu/osu.Game.Rulesets.Osu/Objects/Drawables/Connections/FollowPointConnection.cs:line 142
FollowPointConnection.set_End() at /home/dachb/opensource/osu/osu.Game.Rulesets.Osu/Objects/Drawables/Connections/FollowPointConnection.cs:line 74
FollowPointRenderer.addConnection() at /home/dachb/opensource/osu/osu.Game.Rulesets.Osu/Objects/Drawables/Connections/FollowPointRenderer.cs:line 73
FollowPointRenderer.AddFollowPoints() at /home/dachb/opensource/osu/osu.Game.Rulesets.Osu/Objects/Drawables/Connections/FollowPointRenderer.cs:line 32
OsuPlayfield.Add() at /home/dachb/opensource/osu/osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs:line 96
DrawableRuleset<OsuHitObject>.addHitObject() at /home/dachb/opensource/osu/osu.Game/Rulesets/UI/DrawableRuleset.cs:line 237
DrawableRuleset<OsuHitObject>.loadObjects() at /home/dachb/opensource/osu/osu.Game/Rulesets/UI/DrawableRuleset.cs:line 194
DrawableRuleset<OsuHitObject>.load() at /home/dachb/opensource/osu/osu.Game/Rulesets/UI/DrawableRuleset.cs:line 183
```

As you can see, it's called from `load()`, which is under the framed clock, and not the gameplay clock. As transforms are added, the underlying `TargetMemberTransformTracker` reads the framed clock's time instead of the gameplay clock's, therefore making `lastAppliedIndex` get stuck at `Count + 1`, disabling all transforms.

The dirty way to confirm is sticking a `scheduleRefresh()` in `FollowPointConnection.LoadComplete()` but it's not a good enough solution to PR as it makes the refresh needlessly execute twice. Unfortunately I can't submit a fix today, but I'll get round to it if this issue is still open when I can get a fix up, now that it's seemingly root-caused.

**Comment by bdach** [comment]
I think I've isolated this, and I'd say it's a framework bug. [Here's a minimal... -ish test case](https://github.com/ppy/osu-framework/commit/1e7ce765d8f538d6124eea01593969fcd1cc8b46).

The cause is pretty nasty. If a transform is added before `UpdateSubTree()` starts to run (so during load, for example, or before an add), it will use whatever clock value is available right then to apply transforms up to that point, setting `lastAppliedIndex` in the process.

The problem is that `Transformable` also does its tracking, as it has a `lastUpdateTransformsTime`. Adding a transform does not mutate that value. Worse yet that value is used to determine whether the tracker should run rewind logic. This causes the following scenario (apologies for image "quality"):

![obraz](https://user-images.githubusercontent.com/20418176/90323576-517b1a80-df63-11ea-81af-1966a58a3c7d.png)

`lastAppliedIndex` is essentially stuck until it can be reset again by clearing transforms, manually applying, etc.

I pushed a rudimentary fix [to this branch](https://github.com/ppy/osu-framework/compare/master...bdach:add-transform-in-the-past) but I'm uncertain that it's what we want - the fact that two places are now tracking transform times is concerning and one perhaps should be eliminated if necessary.

**Comment by peppy** [comment]
Doing heavy lifting there. Can confirm your reasoning, but not 100% on the solution. I think there may be an edge case where the `lastUpdateTransformsTime ` value is updated, but as it is global to all trackers it may be in an incorrect state for trackers apart from the one just added to. Going to need to do a bit more thinking to figure whether that is the case or not.

Maybe we want to call `UpdateTransforms` in the `Transformable` itself (across all trackers) rather than on the target tracker? Or maybe we want to better case the "apply immediately" to the non-loaded-drawable scenario and be ensured that *all* transforms to a point are guaranteed to be applied immediately?

**Comment by bdach** [comment]
Yeah, the branch linked is a 2am sort of solution. I also had the feeling that could not be entirely valid always. Your suggestions sound better for sure.
