### ISSUE TITLE
Auto-disabling No-Fail

### ISSUE THREAD

**Issue by ILuvSkins** [ppy/osu#9844]
**Describe the new feature:** 
Disabling NF when you pass the map without failing.
**Proposal designs of the feature:**
Whenever you pass a map without failing but you had No-Fail turned on, the game will ignore the score multiplier of NF and just give you the score you'd get without NF. For example, if I play a map with HRHDDTNF but I don't fail at all, the game would just handle it as a HRHDDT score. It may take a bit of time to recalculate the score without NF at the end of the map though...

**Comment by bdach** [comment]
Sounds like a cheap cop-out to me. I'd say either play with health and risk losing, or don't and take the score penalty.

**Comment by LastExceed** [comment]
by that logic sudden death should give a bonus

**Comment by bdach** [comment]
Then I'd rather the difficulty multiplier of no-fail removed. The idea of "only take the score hit when it doesn't really matter" makes no sense to me.

**Comment by LastExceed** [comment]
I think we have to consider 2 factors of NF: 

a) it removes the stress that a player is under when struggling to HP pass a map (which is the equivalent of the added stress from SD when going for FC) without affecting the logical difficulty

b) it allows allows submitting scores that are otherwise impossible (SD has no counterpart for this)

now the question is whether the score penalty NF currently has is there because of a or b. if the former then we'd have to adjust SD for consistency, but if its the latter then OP has a valid point (though then i'd argue that NF should be unranked rather than penalised but that's beside the point)

Quantifying stress is difficult and imo not a good idea because picking SD/NF during a tournament where you only have 1 attempt is a whole different thing than when you pick it while grinding a map over and over for pp

**Comment by Wieku** [comment]
NoFail makes gameplay easier because you won't die, thus score and pp penalty.
SD/PF is just a autorestart convenience when you want a FC or SS.
Picking SD during a tournament is the picker's fault. You have 1 attempt anyways.

**Comment by ILuvSkins** [comment]
yeah, it seemed a good idea at first but on second thought this is stupid.

**Comment by smoogipoo** [comment]
This isn't going to happen.
