### ISSUE TITLE
Music Controller toast ignores the "play track" message sometimes

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#9880]
**Describe the bug:** I was trying to reproduce #9876 on Windows, instead of the reported OS (Debian), but I noticed a different weird behaviour: the music controller toast seems to ignore/skip the "Play track" message sometimes.
By "sometimes" I mean pressing F3 at least two times (to switch between pause and play), or a few more (like in the following video) and it should skip the message _randomly_.

**Screenshots or videos showing encountered issue:** [Video](https://drive.google.com/file/d/1NTcXFzDutMv5krk11LQJ-sgTH6FfHoId/view?usp=sharing) (you can notice the issue at `0:16` and `0:23`)

**osu!lazer version:** after a couple of tests between versions, I think this issue started from version [2019.1128.0](https://osu.ppy.sh/home/changelog/lazer/2019.1128.0)

**Comment by bdach** [comment]
This I can definitely repro - the OSD is never flipped for me but does lose updates sometimes for some reason.

**Comment by peppy** [comment]
This looks to be due to a threading issue (oversight?).

`TogglePause` will call `Start` on the track which waits on `StartAsync`. This seems fine, until you realise that the IsRunning state is updated after the `PendingActions` queue is finished dequeueing, so there's actually no guarantee it is in the correct state after a synchronous `Start` operation.

https://github.com/ppy/osu-framework/blob/1fe98777107452e39b0c817ca7c1f6e9637f0007/osu.Framework/Audio/AudioComponent.cs#L100-L104

A potential fix may be to set the state correctly inside the StartAsync operation. Need feedback on this before going forward with it (it likely needs to also happen in other similar operations across multiple classes).

**Comment by peppy** [comment]
Closing this for now. Not going to open a framework side issue as again, I'm not sure if the current behaviour is necessarily incorrect. Let's wait for it to be reported for another reason before considering changing the state behaviour.
