### ISSUE TITLE
Don't force aspect ratio for custom flags in tournament client

### ISSUE THREAD

**Issue by nautzz** [ppy/osu#9963]
**Describe the new feature:** 
Title already explains it; reason for the request being that this would be very nice to have for 1v1 tournaments, since you could use peoples profile pictures as custom "flags". As it is right now, they get squished and look strange when you try to do this.
**Proposal designs of the feature:** 
Section doesn't really apply for this I think. Felt wrong to submit as a bug though

**Comment by MiraiSubject** [comment]
Just as a side note: I've actually been looking into a potential solution of this, like making the flags fit (or fill) a container instead of stretch. (depending on the desired direction) 

Right now the sprite itself in some spots uses a custom size and scale, in i.e. these places

https://github.com/ppy/osu/blob/0295ae29211420fa0dc6bcfcc0c28aa556968a99/osu.Game.Tournament/Screens/TeamIntro/SeedingScreen.cs#L290-L292

https://github.com/ppy/osu/blob/0295ae29211420fa0dc6bcfcc0c28aa556968a99/osu.Game.Tournament/Screens/TeamWin/TeamWinScreen.cs#L91-L94

It's a bit more complicated than I initially thought, but hopefully any others interested in finding a solution will find these pointers somewhat helpful.
