### ISSUE TITLE
Circles are drawn on top of judgements

### ISSUE THREAD

**Issue by Finxert** [ppy/osu#9964]
**Describe the bug:** 

Hitcircles appearing on screen are placed/drawn on top of accuracy markers such as 100s, 50s and even misses. This makes it so that you cannot see if you're accurately hitting a relatively, or fully, stacked stream. This also has the side effect of making 100s, 50s and misses quite a lot harder to see than in stable.

**osu!lazer version:** 
2020.820.0

**Comment by bdach** [comment]
Seems that it should be quite easily fixable by adjusting the depth specifications in `OsuPlayfield`:

https://github.com/ppy/osu/blob/93f8dddb2076ce9a3f5c530f26750ccddd0808b5/osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs#L51-L55

However as the original code comes from 2017 I'm unsure whether this was an intentional choice for the default skin, intentional choice for all skins going forward, or just plain oversight.

**Comment by igontusuwu** [comment]
i think this should be more of a option for skins
if the hit judgement is big, it will cover up circles and make them more difficult to hit
if the hit judgement is too small, the circles will cover the judgement and make it not visible

**Comment by TheWildTree** [comment]
Pretty sure this duplicates #7584.

**Comment by bdach** [comment]
Seems correct, closing as duplicate.
